Repository Agoric/agoric-sdk, pull requests merged in 2021-11, with the labels that each got.

#4016 Fix manual_dapp_testing.md
  .github/ISSUE_TEMPLATE/manual_dapp_testing.md
Labels: automerge:rebase

#4015 chore: allow multiple zcfMints for RUN to be registered
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/setupZcfTest.js
Labels: Zoe, automerge:squash

#3935 Cosmic swingset governance
  docs/env.md
  go.mod
  go.sum
  golang/cosmos/app/app.go
  golang/cosmos/proto/agoric/swingset/genesis.proto
  golang/cosmos/proto/agoric/swingset/query.proto
  golang/cosmos/proto/agoric/swingset/swingset.proto
  golang/cosmos/x/lien/genesis.go
  golang/cosmos/x/lien/genesis_test.go
  golang/cosmos/x/lien/module.go
  golang/cosmos/x/swingset/abci.go
  golang/cosmos/x/swingset/client/cli/query.go
  golang/cosmos/x/swingset/genesis.go
  golang/cosmos/x/swingset/genesis_test.go
  golang/cosmos/x/swingset/keeper/grpc_query.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/keeper/querier.go
  golang/cosmos/x/swingset/storage.go
  golang/cosmos/x/swingset/types/genesis.pb.go
  golang/cosmos/x/swingset/types/msgs.pb.go
  golang/cosmos/x/swingset/types/params.go
  golang/cosmos/x/swingset/types/query.pb.go
  golang/cosmos/x/swingset/types/query.pb.gw.go
  golang/cosmos/x/swingset/types/sim-params.go
  golang/cosmos/x/swingset/types/storage.pb.go
  golang/cosmos/x/swingset/types/swingset.pb.go
  golang/cosmos/x/vbank/README.md
  golang/cosmos/x/vbank/genesis_test.go
  golang/cosmos/x/vbank/types/genesis.pb.go
  golang/cosmos/x/vbank/types/params.go
  golang/cosmos/x/vbank/types/query.pb.go
  golang/cosmos/x/vbank/types/vbank.pb.go
  golang/cosmos/x/vibc/types/msgs.pb.go
  packages/agoric-cli/lib/chain-config.js
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/block-manager.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/cosmic-swingset/src/sim-params.js
Labels: cosmic-swingset, automerge:merge

#4028 feat(wallet): Create empty purses for issuers
  packages/dapp-svelte-wallet/react-ui/src/components/Card.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/CardItem.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/MakePurse.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/WalletConnection.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/tests/MakePurse.test.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/tests/WalletConnection.test.jsx
  packages/dapp-svelte-wallet/react-ui/src/contexts/Application.jsx
  packages/dapp-svelte-wallet/react-ui/src/views/Issuers.jsx
  packages/dapp-svelte-wallet/react-ui/src/views/Issuers.scss
  packages/dapp-svelte-wallet/react-ui/src/views/tests/Issuers.test.jsx
Labels: automerge:squash

#4006 Add Governance to the constantProduct AMM
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractHelper.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/vat-voter.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/vats/test/test-distributeFees.js
  packages/zoe/package.json
  packages/zoe/src/contracts/constantProduct/calcFees.js
  packages/zoe/src/contracts/vpool-xyk-amm/doublePool.js
  packages/zoe/src/contracts/vpool-xyk-amm/multipoolMarketMaker.js
  packages/zoe/src/contracts/vpool-xyk-amm/params.js
  packages/zoe/src/contracts/vpool-xyk-amm/pool.js
  packages/zoe/src/contracts/vpool-xyk-amm/singlePool.js
  packages/zoe/src/contracts/vpool-xyk-amm/swap.js
  packages/zoe/test/autoswapJig.js
  packages/zoe/test/unitTests/contractSupport/test-withdrawFrom.js
  packages/zoe/test/unitTests/contracts/test-autoswap.js
  packages/zoe/test/unitTests/contracts/vpool-xyk-amm/test-amm-governance.js
  packages/zoe/test/unitTests/contracts/vpool-xyk-amm/test-xyk-amm-swap.js
  packages/zoe/test/unitTests/zcf/test-zoeHelpersWZcf.js
  packages/zoe/test/zoeTestHelpers.js
Labels: Beta, Core Economy, treasury, Governance, AMM, automerge:squash

#4035 chore(react-ui): remove extra yarn.lock
  packages/dapp-svelte-wallet/react-ui/yarn.lock
Labels: hygiene, automerge:merge

#4022 feat(wallet): Add send functionality to purses
  packages/dapp-svelte-wallet/react-ui/public/index.html
  packages/dapp-svelte-wallet/react-ui/src/App.scss
  packages/dapp-svelte-wallet/react-ui/src/components/MakePurse.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/Purses.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/Purses.scss
  packages/dapp-svelte-wallet/react-ui/src/components/Transfer.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/tests/Purses.test.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/tests/Transfer.test.jsx
  packages/dapp-svelte-wallet/react-ui/src/contexts/Application.jsx
  packages/dapp-svelte-wallet/react-ui/src/index.jsx
  packages/dapp-svelte-wallet/react-ui/src/views/Issuers.jsx
  packages/dapp-svelte-wallet/react-ui/src/views/Issuers.scss
Labels: automerge:squash

#4034 chore: add swingset tests of multiple run mints
  packages/zoe/test/runMintContract.js
  packages/zoe/test/swingsetTests/runMint/bootstrap.js
  packages/zoe/test/swingsetTests/runMint/test-runMint.js
  packages/zoe/test/swingsetTests/runMint/vat-alice.js
  packages/zoe/test/swingsetTests/runMint/vat-zoe.js
Labels: automerge:squash

#4045 fix: avoid eslint escaping agoric-sdk package root
  package.json
Labels: automerge:merge

#4033 Notifier API updates
  packages/notifier/src/asyncIterableAdaptor.js
  packages/notifier/src/notifier.js
  packages/notifier/src/subscriber.js
  packages/notifier/src/types.js
  packages/notifier/test/iterable-testing-tools.js
Labels: notifier, automerge:merge

#4048 fix(wallet): automatically convert number values to bigints
  packages/dapp-svelte-wallet/api/package.json
  packages/dapp-svelte-wallet/api/src/lib-wallet.js
  packages/dapp-svelte-wallet/api/test/test-lib-wallet.js
Labels: automerge:squash

#4049 feat(wallet): dashboard layout changes + render basic request cards
  packages/dapp-svelte-wallet/react-ui/src/components/DappConnection.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/Offer.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/Payment.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/Purses.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/Request.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/Request.scss
  packages/dapp-svelte-wallet/react-ui/src/components/Requests.jsx
  packages/dapp-svelte-wallet/react-ui/src/components/Requests.scss
  packages/dapp-svelte-wallet/react-ui/src/components/tests/Requests.test.jsx
  packages/dapp-svelte-wallet/react-ui/src/views/Dashboard.jsx
  packages/dapp-svelte-wallet/react-ui/src/views/Dashboard.scss
Labels: automerge:squash

#4052 Implement `agoric start --debug` option
  docs/env.md
  packages/agoric-cli/bin/agoric
  packages/agoric-cli/jsconfig.json
  packages/agoric-cli/package.json
  packages/agoric-cli/src/anylogger-agoric.js
  packages/agoric-cli/src/chain-config.js
  packages/agoric-cli/src/cosmos.js
  packages/agoric-cli/src/deploy.js
  packages/agoric-cli/src/entrypoint.js
  packages/agoric-cli/src/helpers.js
  packages/agoric-cli/src/init.js
  packages/agoric-cli/src/install.js
  packages/agoric-cli/src/main.js
  packages/agoric-cli/src/open.js
  packages/agoric-cli/src/set-defaults.js
  packages/agoric-cli/src/start.js
  packages/agoric-cli/test/test-main.js
  packages/agoric-cli/tools/getting-started.js
  packages/cosmic-swingset/bin/ag-nchainz
  packages/solo/src/start.js
Labels: agoric-cli

#4046 feat(zoe/contracts): Support first-price auction, fix wakeup timer in current contract
  packages/zoe/src/contracts/auction/firstPriceLogic.js
  packages/zoe/src/contracts/auction/index.js
  packages/zoe/src/contracts/auction/secondPriceAuction.js
  packages/zoe/test/swingsetTests/zoe/test-zoe.js
  packages/zoe/test/swingsetTests/zoe/vat-alice.js
  packages/zoe/test/unitTests/contracts/test-auction.js
Labels: automerge:squash

#4051 feat(wallet): render contact cards
  packages/dapp-svelte-wallet/react-ui/src/views/Contacts.jsx
  packages/dapp-svelte-wallet/react-ui/src/views/Contacts.scss
  packages/dapp-svelte-wallet/react-ui/src/views/Issuers.jsx
  packages/dapp-svelte-wallet/react-ui/src/views/tests/Contacts.test.jsx
Labels: automerge:rebase

#4050 chore: make an escrow purse for RUN (aka: feeIssuer) at Zoe startup
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/swingsetTests/runMint/bootstrap.js
  packages/zoe/test/swingsetTests/runMint/test-runMint.js
  packages/zoe/test/swingsetTests/runMint/vat-alice.js
Labels: automerge:squash

#4073 test: repair tests that are breaking on master
  packages/governance/test/unitTests/test-param-manager.js
  packages/governance/test/unitTests/test-shareHolders.js
Labels: bug, marshal, Governance, automerge:merge

#4071 feat(wallet): add delete API for dapps
  packages/dapp-svelte-wallet/api/src/lib-wallet.js
Labels: automerge:merge, automerge:rebase

#4076 chore(wallet): upgrade to mui v5
  packages/dapp-wallet/ui/package.json
  packages/dapp-wallet/ui/src/App.jsx
  packages/dapp-wallet/ui/src/components/AppBar.jsx
  packages/dapp-wallet/ui/src/components/MakePurse.jsx
  packages/dapp-wallet/ui/src/components/NavDrawer.jsx
  packages/dapp-wallet/ui/src/components/NavMenu.jsx
  packages/dapp-wallet/ui/src/components/Offer.jsx
  packages/dapp-wallet/ui/src/components/Purses.jsx
  packages/dapp-wallet/ui/src/components/Request.jsx
  packages/dapp-wallet/ui/src/components/Transfer.jsx
  packages/dapp-wallet/ui/src/components/WalletConnection.jsx
  packages/dapp-wallet/ui/src/components/tests/MakePurse.test.jsx
  packages/dapp-wallet/ui/src/components/tests/NavDrawer.test.jsx
  packages/dapp-wallet/ui/src/components/tests/Offer.test.jsx
  packages/dapp-wallet/ui/src/components/tests/Purses.test.jsx
  packages/dapp-wallet/ui/src/components/tests/Transfer.test.jsx
  packages/dapp-wallet/ui/src/components/tests/WalletConnection.test.jsx
  packages/dapp-wallet/ui/src/index.jsx
  packages/dapp-wallet/ui/src/tests/App.test.jsx
  packages/dapp-wallet/ui/src/views/Contacts.jsx
  packages/dapp-wallet/ui/src/views/Dapps.jsx
  packages/dapp-wallet/ui/src/views/Dashboard.jsx
  packages/dapp-wallet/ui/src/views/Issuers.jsx
  packages/dapp-wallet/ui/src/views/tests/Contacts.test.jsx
  packages/dapp-wallet/ui/src/views/tests/Issuers.test.jsx
  yarn.lock
Labels: automerge:merge, automerge:squash, automerge:rebase

#4067 chore: add assert.note
  packages/ERTP/src/paymentLedger.js
Labels: automerge:squash

#4070 fix: if `makeEmptyPurse` fails, then `startInstance` and `saveIssuer` should fail
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
  packages/zoe/test/unitTests/zoe/test-escrowStorage.js
Labels: Zoe, automerge:squash

#4074 Add governance to the list of packages to be tested in CI
  .github/workflows/test-all-packages.yml
  packages/governance/test/unitTests/test-ballotBuilder.js
Labels: bug, test, XSmall, Beta, Governance, automerge:squash

#4069 fix(zoe): assert that amountKeywordRecord is a copyRecord
  packages/governance/test/unitTests/test-shareHolders.js
  packages/pegasus/src/pegasus.js
  packages/treasury/src/burn.js
  packages/treasury/src/collectRewardFees.js
  packages/treasury/src/liquidation.js
  packages/treasury/src/stablecoinMachine.js
  packages/treasury/src/vault.js
  packages/treasury/src/vaultManager.js
  packages/treasury/test/swingsetTests/governance/bootstrap.js
  packages/treasury/test/swingsetTests/governance/vat-owner.js
  packages/treasury/test/swingsetTests/treasury/bootstrap.js
  packages/treasury/test/swingsetTests/treasury/vat-owner.js
  packages/treasury/test/test-bootstrapPayment.js
  packages/treasury/test/test-stablecoin.js
  packages/treasury/test/vault-contract-wrapper.js
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/types.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/attestation/expiring/extendExpiration.js
  packages/zoe/src/contracts/attestation/helpers.js
  packages/zoe/src/contracts/attestation/returnable/returnableNFT.js
  packages/zoe/src/contracts/auction/firstPriceLogic.js
  packages/zoe/src/contracts/auction/secondPriceLogic.js
  packages/zoe/src/contracts/autoswap.js
  packages/zoe/src/contracts/barterExchange.js
  packages/zoe/src/contracts/callSpread/fundedCallSpread.js
  packages/zoe/src/contracts/callSpread/payoffHandler.js
  packages/zoe/src/contracts/callSpread/pricedCallSpread.js
  packages/zoe/src/contracts/loan/addCollateral.js
  packages/zoe/src/contracts/loan/borrow.js
  packages/zoe/src/contracts/loan/close.js
  packages/zoe/src/contracts/loan/scheduleLiquidation.js
  packages/zoe/src/contracts/mintPayments.js
  packages/zoe/src/contracts/multipoolAutoswap/pool.js
  packages/zoe/src/contracts/multipoolAutoswap/swap.js
  packages/zoe/src/contracts/newSwap/collectFees.js
  packages/zoe/src/contracts/newSwap/swap.js
  packages/zoe/src/contracts/oracle.js
  packages/zoe/src/contracts/otcDesk.js
  packages/zoe/src/contracts/sellItems.js
  packages/zoe/src/contracts/vpool-xyk-amm/doublePool.js
  packages/zoe/src/contracts/vpool-xyk-amm/pool.js
  packages/zoe/src/contracts/vpool-xyk-amm/singlePool.js
  packages/zoe/test/runMintContract.js
  packages/zoe/test/unitTests/bounty.js
  packages/zoe/test/unitTests/contracts/loan/test-liquidate.js
  packages/zoe/test/unitTests/contracts/multipoolAutoswap/test-constantProduct.js
  packages/zoe/test/unitTests/contracts/vpool-xyk-amm/test-amm-governance.js
  packages/zoe/test/unitTests/contracts/vpool-xyk-amm/test-xyk-amm-swap.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/registerFeeMintContract.js
  packages/zoe/test/unitTests/zcf/test-allStagedSeatsUsed.js
  packages/zoe/test/unitTests/zcf/test-reallocate-empty.js
  packages/zoe/test/unitTests/zcf/test-reallocateForZCFMint.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: automerge:squash

#4075 fix: make proto targets in golang/cosmos
  go.mod
  go.sum
  golang/cosmos/Makefile
  golang/cosmos/buf.work.yaml
  golang/cosmos/proto/buf.yaml
  golang/cosmos/scripts/protocgen.sh
  golang/cosmos/third_party/proto/buf.yaml
  golang/cosmos/third_party/proto/google/protobuf/any.proto
  golang/cosmos/tools/tools.go
  golang/cosmos/x/swingset/types/query.pb.gw.go
  golang/cosmos/x/vbank/types/query.pb.gw.go
Labels: bug, automerge:merge

#4083 feat(wallet): render dapps view and dapp connection requests
  packages/dapp-wallet/ui/public/agoric-blocks.png
  packages/dapp-wallet/ui/src/components/Dapp.jsx
  packages/dapp-wallet/ui/src/components/DappConnection.jsx
  packages/dapp-wallet/ui/src/components/Requests.jsx
  packages/dapp-wallet/ui/src/components/Transfer.jsx
  packages/dapp-wallet/ui/src/components/tests/Dapp.test.jsx
  packages/dapp-wallet/ui/src/components/tests/DappConnection.test.jsx
  packages/dapp-wallet/ui/src/views/Dapps.jsx
  packages/dapp-wallet/ui/src/views/Dapps.scss
  packages/dapp-wallet/ui/src/views/tests/Dapps.test.jsx
Labels: automerge:rebase

#4089 ci(Mergify): configuration update
  .mergify.yml
Labels: tooling

#4088 Proto workflows additions, remove unnecessary `master` refs
  .github/workflow-templates/test-dapp.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/integration.yml
  .github/workflows/pr-checks.yml
  .github/workflows/proto.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-dapp-card-store.yml
  .github/workflows/test-dapp-fungible-faucet.yml
  .github/workflows/test-dapp-oracle.yml
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml
  .github/workflows/test-documentation.yml
  .github/workflows/test-golang.yml
  golang/cosmos/Makefile
  golang/cosmos/proto/agoric/lien/genesis.proto
  golang/cosmos/proto/agoric/swingset/genesis.proto
  golang/cosmos/proto/agoric/swingset/msgs.proto
  golang/cosmos/proto/agoric/swingset/query.proto
  golang/cosmos/proto/agoric/swingset/storage.proto
  golang/cosmos/proto/agoric/swingset/swingset.proto
  golang/cosmos/proto/agoric/vbank/genesis.proto
  golang/cosmos/proto/agoric/vbank/msgs.proto
  golang/cosmos/proto/agoric/vbank/vbank.proto
  golang/cosmos/proto/agoric/vibc/msgs.proto
  golang/cosmos/x/lien/types/genesis.pb.go
  golang/cosmos/x/swingset/client/cli/query.go
  golang/cosmos/x/swingset/keeper/grpc_query.go
  golang/cosmos/x/swingset/types/genesis.pb.go
  golang/cosmos/x/swingset/types/msgs.pb.go
  golang/cosmos/x/swingset/types/query.pb.go
  golang/cosmos/x/swingset/types/query.pb.gw.go
  golang/cosmos/x/swingset/types/storage.pb.go
  golang/cosmos/x/swingset/types/swingset.pb.go
  golang/cosmos/x/vbank/types/genesis.pb.go
  golang/cosmos/x/vbank/types/vbank.pb.go
  golang/cosmos/x/vibc/types/msgs.pb.go
Labels: tooling, automerge:merge, agd, proto:expect-breakage

#4082 chore(lerna): include merged tags for version calculation
  lerna.json
Labels: tooling, automerge:merge

#4090 feat(wallet): implement offer actions
  packages/dapp-wallet/ui/src/components/Offer.jsx
  packages/dapp-wallet/ui/src/components/Request.jsx
  packages/dapp-wallet/ui/src/components/Requests.jsx
  packages/dapp-wallet/ui/src/components/tests/Offer.test.jsx
  packages/dapp-wallet/ui/src/components/tests/Requests.test.jsx
  packages/dapp-wallet/ui/src/contexts/Application.jsx
Labels: automerge:rebase

#4093 feat(wallet): add reject button for dapps
  packages/dapp-wallet/ui/src/components/DappConnection.jsx
  packages/dapp-wallet/ui/src/components/tests/DappConnection.test.jsx
Labels: automerge:rebase

#4094 feat(wallet): implement import issuer button
  packages/dapp-wallet/ui/src/components/ImportIssuer.jsx
  packages/dapp-wallet/ui/src/components/tests/ImportIssuer.test.jsx
  packages/dapp-wallet/ui/src/views/Issuers.jsx
  packages/dapp-wallet/ui/src/views/Issuers.scss
  packages/dapp-wallet/ui/src/views/tests/Issuers.test.jsx
Labels: automerge:rebase

#4095 chore: add caret
  packages/dapp-wallet/ui/package.json
Labels: automerge:rebase

#4026 Extract AMM from Vaults (ex-Treasury)
  packages/treasury/bundles/install-on-chain.js
  packages/treasury/scripts/build-bundles.js
  packages/treasury/src/collectRewardFees.js
  packages/treasury/src/interest.js
  packages/treasury/src/liquidateMinimum.js
  packages/treasury/src/liquidation.js
  packages/treasury/src/params.js
  packages/treasury/src/stablecoinMachine.js
  packages/treasury/src/types.js
  packages/treasury/src/vault.js
  packages/treasury/src/vaultManager.js
  packages/treasury/test/faucet.js
  packages/treasury/test/mockAmm.js
  packages/treasury/test/swingsetTests/governance/bootstrap.js
  packages/treasury/test/swingsetTests/governance/test-governance.js
  packages/treasury/test/swingsetTests/governance/vat-owner.js
  packages/treasury/test/swingsetTests/treasury/bootstrap.js
  packages/treasury/test/swingsetTests/treasury/test-treasury.js
  packages/treasury/test/swingsetTests/treasury/vat-owner.js
  packages/treasury/test/test-bootstrapPayment.js
  packages/treasury/test/test-interest.js
  packages/treasury/test/test-stablecoin.js
  packages/treasury/test/test-vault-interest.js
  packages/treasury/test/test-vault.js
  packages/treasury/test/vault-contract-wrapper.js
  packages/vats/src/bootstrap.js
  packages/vats/src/distributeFees.js
  packages/vats/src/issuers.js
  packages/vats/src/types.js
  packages/vats/src/vat-distributeFees.js
  packages/vats/test/test-distributeFees.js
  packages/zoe/src/contracts/exported.js
  packages/zoe/src/contracts/vpool-xyk-amm/addLiquidity.js
  packages/zoe/test/unitTests/contracts/vpool-xyk-amm/test-xyk-amm-swap.js
Labels: hygiene, Medium, Core Economy, treasury, AMM, automerge:squash

#4098 fix(cosmic-swingset): have `make install` do what you expect
  packages/cosmic-swingset/Makefile
Labels: cosmic-swingset, automerge:merge

#4102 Add displayInfo for the liquidity tokens created in the AMM
  packages/zoe/src/contracts/vpool-xyk-amm/pool.js
  packages/zoe/test/unitTests/contracts/vpool-xyk-amm/test-xyk-amm-swap.js
Labels: XSmall, UI, Zoe Contract, AMM, automerge:squash

#4105 Use paramMakers to simplify callers
  packages/governance/test/unitTests/test-param-manager.js
  packages/treasury/src/params.js
Labels: hygiene, XSmall, Beta, code-style, Governance, automerge:squash

#4079 ci(coverage): ensure `test-all-packages.yml` tests everything
  .github/workflows/test-all-packages.yml
  scripts/check-untested-packages.mjs
Labels: tooling, automerge:merge

#4055 Instructions for testing testnet-load-generator
  .github/ISSUE_TEMPLATE/manual_dapp_testing.md
Labels: automerge:rebase

#4097 feat!: remove newSwap; replace with constantProduct AMM where needed
  packages/SwingSet/misc-tools/measure-metering/measure.js
  packages/zoe/src/contracts/newSwap/getCurrentPrice.js
  packages/zoe/src/contracts/newSwap/multipoolAutoswap.js
  packages/zoe/src/contracts/newSwap/swap.js
  packages/zoe/src/contracts/newSwap/types.js
  packages/zoe/src/contracts/vpool-xyk-amm/collectFees.js
  packages/zoe/src/contracts/vpool-xyk-amm/multipoolMarketMaker.js
  packages/zoe/test/unitTests/contracts/constantProduct/test-compareNewSwapPrice.js
  packages/zoe/test/unitTests/contracts/constantProduct/test-readmeScenario.js
  packages/zoe/test/unitTests/contracts/newSwap/test-newSwap-swap.js
  packages/zoe/test/unitTests/contracts/newSwap/test-newSwapPrice.js
  packages/zoe/test/unitTests/contracts/newSwap/test-newswap-bug.js
Labels: hygiene, Small, Zoe Contract, Core Economy, AMM, automerge:squash

#4104 Conditional must be a guard so await is top-level
  packages/treasury/src/liquidateMinimum.js
Labels: XSmall, Beta, Risk: Low, code-style, technical-debt, treasury, automerge:squash

#3938 docs: add initial pegasus diagrams
  docs/threat_models/index.md
  docs/threat_models/pegasus/pegasus_component.png
  docs/threat_models/pegasus/pegasus_component.puml
  docs/threat_models/pegasus/pegasus_sequence.png
  docs/threat_models/pegasus/pegasus_sequence.puml
Labels: documentation, automerge:merge, threat modeling

#4108 build: basic Node.js v17 support
  .github/workflows/test-all-packages.yml
  package.json
  yarn.lock
Labels: tooling, automerge:merge

#4110 fix(agoric-cli): Docker support corrections
  .github/workflows/docker.yml
  packages/agoric-cli/src/main.js
  packages/agoric-cli/src/start.js
  packages/deployment/Dockerfile.sdk
Labels: agoric-cli, deployment, automerge:merge

#4112 ci(docker): fix `schedule` syntax
  .github/workflows/docker.yml
Labels: tooling, automerge:merge

#4107 Drop multipool autoswap
  packages/zoe/src/contracts/autoswap.js
  packages/zoe/src/contracts/exported.js
  packages/zoe/src/contracts/loan/index.js
  packages/zoe/src/contracts/loan/types.js
  packages/zoe/src/contracts/multipoolAutoswap/addLiquidity.js
  packages/zoe/src/contracts/multipoolAutoswap/constantProduct.js
  packages/zoe/src/contracts/multipoolAutoswap/docs/reallocateCatalog.md
  packages/zoe/src/contracts/multipoolAutoswap/getCurrentPrice.js
  packages/zoe/src/contracts/multipoolAutoswap/multipoolAutoswap.js
  packages/zoe/src/contracts/multipoolAutoswap/pool.js
  packages/zoe/src/contracts/multipoolAutoswap/removeLiquidity.js
  packages/zoe/src/contracts/multipoolAutoswap/swap.js
  packages/zoe/src/contracts/multipoolAutoswap/types.js
  packages/zoe/src/contracts/types.js
  packages/zoe/src/contracts/vpool-xyk-amm/pool.js
  packages/zoe/src/contracts/vpool-xyk-amm/priceAuthority.js
  packages/zoe/test/autoswapJig.js
  packages/zoe/test/unitTests/contracts/multipoolAutoswap/test-constantProduct.js
  packages/zoe/test/unitTests/contracts/multipoolAutoswap/test-feeCharged.js
  packages/zoe/test/unitTests/contracts/multipoolAutoswap/test-multipoolAutoswap.js
  packages/zoe/test/unitTests/contracts/multipoolAutoswap/test-multipoolPriceAuthority.js
  packages/zoe/test/unitTests/contracts/test-autoswapPool.js
Labels: hygiene, Small, Risk: Low, Zoe Contract, Core Economy, AMM, automerge:squash

#4077 Update docker-compose instructions
  docker/README.md
  docker/docker-compose.yml
Labels: automerge:squash

#4111 feat(wallet): Misc feedback changes
  packages/dapp-wallet/ui/src/components/NavMenu.jsx
  packages/dapp-wallet/ui/src/components/Offer.jsx
  packages/dapp-wallet/ui/src/components/Requests.scss
  packages/dapp-wallet/ui/src/components/WalletConnection.jsx
  packages/dapp-wallet/ui/src/components/tests/Offer.test.jsx
  packages/dapp-wallet/ui/src/views/Dapps.jsx
  packages/dapp-wallet/ui/src/views/Dapps.scss
  packages/dapp-wallet/ui/src/views/Issuers.jsx
  packages/dapp-wallet/ui/src/views/tests/Dapps.test.jsx
Labels: automerge:rebase

#4113 ci: optimise integration test
  .github/workflows/integration.yml
  docs/env.md
  packages/solo/src/outbound.js
Labels: solo, automerge:merge

#4118 fix: separate watch from non-watch testing
  packages/dapp-wallet/ui/package.json
Labels: automerge:rebase

#4116 build(cosmos): update Go dependencies to fix replay stall
  go.mod
  go.sum
Labels: automerge:merge

#4119 chore(wallet): decline instead of cancel
  packages/dapp-wallet/ui/src/components/Offer.jsx
  packages/dapp-wallet/ui/src/components/tests/Offer.test.jsx
Labels: automerge:merge

#4123 ci(test-all-packages): fork SwingSet and XS tests for speed
  .github/actions/restore-node/action.yml
  .github/actions/save-node/action.yml
  .github/workflows/test-all-packages.yml
  packages/xsnap/src/avaXS.js
Labels: automerge:merge

#4125 feat(agoric-cli): allow deploy `bundleSource` to have `options`
  packages/agoric-cli/src/deploy.js
Labels: agoric-cli, automerge:merge

#4126 feat(wallet-connection): fall back to same origin for admin socket
  packages/wallet-connection/src/admin-websocket-connector.js
Labels: wallet, automerge:merge

#4132 Publish a `dev` Docker tag on every push to `master`
  .github/workflows/docker.yml
  scripts/docker-tag.sh
Labels: tooling, automerge:merge

#4133 ci: schedule a Docker deployment test
  .github/actions/restore-golang/action.yml
  .github/actions/restore-node/action.yml
  .github/workflows/deployment-test.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-golang.yml
  packages/deployment/Dockerfile
  packages/deployment/ansible/config.yml
  packages/deployment/ansible/copy.yml
  packages/deployment/ansible/prepare-cosmos.yml
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
  packages/deployment/ansible/roles/cosmos-validators/tasks/main.yml
  packages/deployment/bin/ag-setup-cosmos
  packages/deployment/scripts/docker-deployment.cjs
  packages/deployment/scripts/install-deps.sh
  packages/deployment/scripts/integration-test.sh
  packages/deployment/scripts/setup.sh
  packages/deployment/src/init.js
  patches/ses+0.14.3.patch
Labels: deployment, automerge:merge

#4135 ci: publish deployment test artifacts
  .github/workflows/deployment-test.yml
  packages/deployment/README.md
  packages/deployment/scripts/capture-integration-results.sh
  packages/deployment/scripts/install-deps.sh
  packages/deployment/scripts/integration-test.sh
  packages/deployment/scripts/setup.sh
  packages/deployment/scripts/start-deployment-test.sh
  packages/deployment/src/main.js
Labels: deployment, tooling, automerge:merge

#4131 build: upgrade to Cosmos SDK v0.44.0-alpha.agoric.1
  go.mod
  go.sum
  golang/cosmos/daemon/cmd/root.go
  packages/cosmic-swingset/src/block-manager.js
Labels: automerge:merge, agd
