Repository Agoric/agoric-sdk, pull requests merged in 2022-12, with the labels that each got.

#6431 refactor: Use new M.splitArray and M.splitRecord
  packages/ERTP/src/typeGuards.js
  packages/SwingSet/src/typeGuards.js
  packages/casting/src/netconfig.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/psm/psmCharter.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/smart-wallet/src/typeGuards.js
  packages/smart-wallet/src/walletFactory.js
  packages/vats/src/core/boot-psm.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/contracts/coveredCall.js
  packages/zoe/src/typeGuards.js
Labels: automerge:squash

#6608 build(types): pack typedefs for casting, governance
  packages/casting/jsconfig.build.json
  packages/casting/package.json
  packages/governance/exported.js
  packages/governance/package.json
  packages/governance/src/exported.js
  packages/governance/src/index.js
  packages/governance/src/types-ambient.js
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/psm/psmCharter.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
Labels: automerge:merge, bypass:integration

#6605 feat!: adapt econCommitteeCharter to work with smart wallet continuing offers
  packages/agoric-cli/src/commands/psm.js
  packages/inter-protocol/scripts/build-bundles.js
  packages/inter-protocol/scripts/start-local-chain-config.json
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/proposals/committee-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psmCharter.js
  packages/inter-protocol/test/psm/gov-add-psm-permit.json
  packages/inter-protocol/test/psm/gov-replace-committee.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/psm/test-governedPsm.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-psm-config.json
  packages/vats/decentral-test-psm-config.json
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/test/devices.js
Labels: automerge:merge

#6599 test: Add Node.js 18.x to workflows
  .github/workflows/after-merge.yml
  .github/workflows/test-all-packages.yml
  packages/solo/test/captp-fixture.js
Labels: automerge:rebase, force:integration

#6614 refactor(types): EconCharterStartResult without runtime
  packages/governance/src/contractGovernor.js
  packages/governance/src/types-ambient.js
  packages/governance/test/swingsetTests/committeeBinary/bootstrap.js
  packages/governance/test/swingsetTests/committeeBinary/vat-voter.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/zoe/src/makeHandle.js
  packages/zoe/src/types.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/utils.d.ts
Labels: automerge:merge, bypass:integration

#6613 feat(assert): export assert.Fail from endo
  packages/assert/src/assert.js
  packages/assert/src/types.js
  packages/assert/test/test-assert.js
Labels: automerge:squash

#6612 fix: track endo 1382 fix to 6570 -- better getMethodNames algorithm
  packages/internal/src/utils.js
Labels: automerge:squash

#6607 6384 single fetch for data and block height
  packages/casting/src/follower-cosmjs.js
Labels: automerge:merge

#6630 ci: remove test-dapp-oracle
  .github/workflows/test-dapp-oracle.yml
Labels: automerge:merge, bypass:integration

#6621 refactor: use Fail template tag in inter-protocol
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/interchainPool.js
  packages/inter-protocol/src/interest.js
  packages/inter-protocol/src/my-lien.js
  packages/inter-protocol/src/proposals/demoIssuers.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/utils.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vpool-xyk-amm/addLiquidity.js
  packages/inter-protocol/src/vpool-xyk-amm/addPool.js
  packages/inter-protocol/src/vpool-xyk-amm/constantProduct/calcFees.js
  packages/inter-protocol/src/vpool-xyk-amm/constantProduct/core.js
  packages/inter-protocol/src/vpool-xyk-amm/constantProduct/getXY.js
  packages/inter-protocol/src/vpool-xyk-amm/constantProduct/invariants.js
  packages/inter-protocol/src/vpool-xyk-amm/constantProduct/swap.js
  packages/inter-protocol/src/vpool-xyk-amm/doublePool.js
  packages/inter-protocol/test/psm/gov-replace-committee.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/swingsetTests/governance/vat-alice.js
  packages/inter-protocol/test/swingsetTests/governance/vat-voter.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/vat-alice.js
  packages/inter-protocol/test/test-gov-collateral.js
Labels: automerge:squash

#6568 Harmonise `core/boot-psm.js` with `core/boot.js`
  packages/agoric-cli/src/start.js
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/economy-template.json
  packages/cosmic-swingset/src/sim-params.js
  packages/inter-protocol/scripts/add-collateral-core.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/proposals/committee-proposal.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/proposals/utils.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/internal/src/config.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/supports.js
  packages/solo/src/chain-cosmos-sdk.js
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-main-psm-config.json
  packages/vats/scripts/init-core.js
  packages/vats/src/bridge.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/types.js
  packages/vats/test/test-vat-bank.js
  packages/wallet/package.json
Labels: cosmic-swingset, automerge:merge, force:integration

#6653 style(store): Simplify makeSplitPayload
  packages/store/src/patterns/patternMatchers.js
Labels: automerge:merge

#6595 chore: bump commander to v9
  packages/agoric-cli/package.json
  packages/agoric-cli/src/main.js
  yarn.lock
Labels: automerge:merge

#6654 style(store): Clean up the MatcherNamespace typedef
  packages/store/src/types.js
Labels: automerge:rebase

#6651 feat: assertAllDefined throws "missing X" from object literal shorthand
  packages/governance/src/contractGovernance/paramManager.js
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/internal/jsconfig.json
  packages/internal/src/config.js
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
  packages/notifier/package.json
  packages/notifier/src/storesub.js
  packages/smart-wallet/src/walletFactory.js
  packages/zoe/src/contracts/priceAggregator.js
Labels: automerge:merge

#6577 fix: use atomicTransfers rather than stagings.
  packages/inter-protocol/src/collectFees.js
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/interchainPool.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/inter-protocol/src/vaultFactory/liquidateMinimum.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/src/vpool-xyk-amm/addPool.js
  packages/inter-protocol/src/vpool-xyk-amm/doublePool.js
  packages/inter-protocol/src/vpool-xyk-amm/pool.js
  packages/inter-protocol/src/vpool-xyk-amm/singlePool.js
  packages/pegasus/src/pegasus.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/types.js
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contractSupport/atomicTransfer.js
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/auction/firstPriceLogic.js
  packages/zoe/src/contracts/auction/secondPriceLogic.js
  packages/zoe/src/contracts/autoswap.js
  packages/zoe/src/contracts/barterExchange.js
  packages/zoe/src/contracts/callSpread/fundedCallSpread.js
  packages/zoe/src/contracts/callSpread/payoffHandler.js
  packages/zoe/src/contracts/callSpread/pricedCallSpread.js
  packages/zoe/src/contracts/loan/addCollateral.js
  packages/zoe/src/contracts/loan/borrow.js
  packages/zoe/src/contracts/loan/close.js
  packages/zoe/src/contracts/loan/scheduleLiquidation.js
  packages/zoe/src/contracts/oracle.js
  packages/zoe/src/contracts/otcDesk.js
  packages/zoe/src/contracts/sellItems.js
Labels: automerge:squash

#6664 fix(swingset): workaround XS garbage collection bugs
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-loader/transcript.js
Labels: force:integration

#6672 fix: add missing facet interface
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:merge

#6668 fix: Factor out `defendPrototypeKit` with consolidated error checking
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/store/src/index.js
  packages/store/src/patterns/interface-tools.js
Labels: automerge:squash

#6684 fix: replace unsafe then with E.when
  packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-node.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/watchedPromises.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/deploy-script-support/src/offer.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/inter-protocol/src/interchainPool.js
  packages/telemetry/package.json
  packages/telemetry/src/slog-file.js
  packages/telemetry/src/slog-sender-pipe.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/repl.js
  packages/vats/src/vat-provisioning.js
  packages/vats/src/virtual-purse.js
  packages/wallet/api/src/lib-wallet.js
  packages/zoe/src/contracts/callSpread/payoffHandler.js
Labels: automerge:squash

#6627 fix(SwingSet): Restore LRU cache flushing when stopping a vat
  packages/SwingSet/src/liveslots/stop-vat.js
  packages/SwingSet/test/bootstrap-relay.js
  packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-durable-singleton.js
Labels: automerge:rebase

#6680 6671 start local economy
  packages/agoric-cli/src/start.js
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/agoric-cli/test/agops-perf-smoketest.sh
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/economy-template.json
  packages/inter-protocol/scripts/start-local-chain-boot.js
  packages/inter-protocol/scripts/start-local-chain-config.json
  packages/inter-protocol/scripts/start-local-chain.sh
Labels: automerge:merge, bypass:integration

#6502 feat(notifier): Introduce durable publish kits
  packages/SwingSet/test/bootstrap-relay.js
  packages/notifier/package.json
  packages/notifier/src/index.js
  packages/notifier/src/publish-kit.js
  packages/notifier/src/types-ambient.js
  packages/notifier/test/test-publish-kit.js
  packages/notifier/test/vat-integration/vat-pubsub.js
Labels: automerge:squash

#6688 fix(solo): devnet faucet is now a web form
  packages/solo/src/chain-cosmos-sdk.js
Labels: automerge:squash

#6697 fix(types): type assertion for assertAllDefined
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
Labels: automerge:merge, bypass:integration

#6618 Zoe types
  packages/governance/src/contractGovernor.js
  packages/governance/src/types-ambient.js
  packages/inter-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/src/vpool-xyk-amm/priceAuthority.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contractSupport/priceAuthorityTransform.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/contracts/test-scaledPriceAuthority.js
  packages/zoe/tools/manualPriceAuthority.js
  packages/zoe/tools/priceAuthorityRegistry.js
  packages/zoe/tools/types.js
Labels: automerge:merge

#6706 fix(types): ZoeService
  packages/inter-protocol/test/test-gov-collateral.js
  packages/zoe/src/contracts/automaticRefund.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/contracts/test-priceAggregatorChainlink.js
  packages/zoe/test/unitTests/setupBasicMints.js
  packages/zoe/test/unitTests/test-zoe.js
Labels: automerge:merge, bypass:integration

#6629 make Chainlink the canonical priceAggregator
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/cosmic-swingset/economy-template.json
  packages/inter-protocol/scripts/price-feed-core.js
  packages/inter-protocol/scripts/start-local-chain.sh
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/zoe/scripts/build-bundles.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/contracts/test-priceAggregatorChainlink.js
Labels: automerge:merge

#6709 refactor: use Fail template tag in ERTP and zoe
  packages/ERTP/src/amountMath.js
  packages/ERTP/src/displayInfo.js
  packages/ERTP/src/mathHelpers/natMathHelpers.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/inter-protocol/test/amm/constantProduct/test-calcDeltaX.js
  packages/inter-protocol/test/amm/constantProduct/test-calcDeltaY.js
  packages/ui-components/src/ratio.js
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/contractFacet/allocationMath.js
  packages/zoe/src/contractFacet/exit.js
  packages/zoe/src/contractFacet/rightsConservation.js
  packages/zoe/src/contractFacet/vatRoot.js
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractSupport/bondingCurves.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/auction/assertBidSeat.js
  packages/zoe/src/contracts/auction/index.js
  packages/zoe/src/contracts/callSpread/pricedCallSpread.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/contracts/coveredCall.js
  packages/zoe/src/contracts/loan/borrow.js
  packages/zoe/src/contracts/loan/close.js
  packages/zoe/src/contracts/oracle.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/sellItems.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/objArrayConversion.js
  packages/zoe/src/zoeService/createZCFVat.js
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/offer/offer.js
  packages/zoe/test/unitTests/contractSupport/test-ratio.js
  packages/zoe/tools/priceAuthorityRegistry.js
Labels: automerge:squash

#6714 move priceAggregatorChainlink to inter-protocol
  packages/inter-protocol/scripts/build-bundles.js
  packages/inter-protocol/scripts/price-feed-core.js
  packages/inter-protocol/src/priceAggregatorChainlink.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/test-priceAggregatorChainlink.js
  packages/zoe/scripts/build-bundles.js
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/src/contracts/exported.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
Labels: automerge:merge

#6700 feat(vats): publish vbank asset list with agoricNames
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/utils.js
  packages/vats/src/vat-bank.js
Labels: automerge:rebase

#6662 docs(SwingSet): Fix some typos and ambiguities in Vatstore documentation
  packages/SwingSet/src/liveslots/vatstore-usage.md
Labels: automerge:squash

#6717 6571 throw errors
  packages/inter-protocol/src/priceAggregatorChainlink.js
  packages/inter-protocol/test/test-priceAggregatorChainlink.js
Labels: automerge:merge

#6719 fix(types): far class maker params
  packages/vat-data/src/far-class-utils.js
  packages/vat-data/test/test-durable-classes.js
  packages/vat-data/test/test-virtual-classes.js
  packages/vat-data/test/test-vivify.js
Labels: automerge:merge, bypass:integration

#6683 feat(vats): async serial bridge
  packages/SwingSet/test/device-plugin/bootstrap.js
  packages/notifier/src/types-ambient.js
  packages/notifier/tools/testSupports.js
  packages/vats/src/bridge.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/lib-chainStorage.js
  packages/vats/src/types.js
  packages/vats/src/vat-chainStorage.js
  packages/vats/test/test-lib-chainStorage.js
  packages/vats/tools/storage-test-utils.js
Labels: automerge:merge

#6699 Zoe checks start args shapes
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/test-startWalletFactory.js
  packages/vats/src/core/startWalletFactory.js
  packages/zoe/src/contractFacet/zcfZygote.js
Labels: automerge:merge

#6734 fix: dont reflect key back in error
  golang/cosmos/x/vstorage/keeper/querier.go
Labels: automerge:rebase

#6732 fix: command injection
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/chain.js
Labels: automerge:rebase

#6730 refactor(vats): scoped bridge managers
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/chain.js
  packages/inter-protocol/scripts/start-local-chain.sh
  packages/inter-protocol/src/my-lien.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/vats/src/bridge.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/boot.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/src/ibc.js
  packages/vats/src/provisionPool.js
  packages/vats/src/types.js
  packages/vats/src/vat-bank.js
  packages/vats/src/vat-chainStorage.js
  packages/vats/test/test-boot.js
  packages/vats/test/test-network.js
  packages/vats/test/test-provisionPool.js
  packages/vats/test/test-vat-bank.js
Labels: automerge:rebase, force:integration
