Repository Agoric/agoric-sdk, pull requests merged in 2022-08, with the labels that each got.

#5864 fix: lint warning cleanup
  packages/swingset-runner/src/main.js
  packages/swingset-runner/src/vat-launcher.js
Labels: swingset-runner, hygiene, automerge:rebase

#5866 docs: Reminder to flush next-release label
  MAINTAINERS.md
Labels: automerge:rebase

#5860 chore: route WalletAction, WalletSpendAction to walletFactory contract
  packages/cosmic-swingset/Makefile
  packages/vats/src/bridge.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/test/test-clientBundle.js
  packages/wallet/contract/package.json
  packages/wallet/contract/src/walletFactory.js
Labels: automerge:squash

#5781 fix(SwingSet): Add durability to vat-vattp objects
  packages/SwingSet/package.json
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/src/vats/vattp/vat-vattp.js
Labels: SwingSet, automerge:rebase

#5873 smart wallet refactorings
  lerna.json
  packages/vats/src/vat-bank.js
  packages/wallet/api/src/internal-types.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/wallet.js
  packages/wallet/api/test/test-getPursesNotifier.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/wallet/contract/package.json
  packages/wallet/contract/src/singleWallet.js
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/src/support.js
  packages/wallet/contract/src/walletFactory.js
  packages/wallet/contract/test/supports.js
  packages/wallet/contract/test/test-singleWallet.js
  packages/wallet/contract/test/test-walletFactory.js
  packages/xsnap/test/test-xs-js.js
Labels: automerge:rebase

#5859 5326 less RUN
  golang/cosmos/x/vbank/README.md
  packages/cosmic-swingset/Makefile
  packages/inter-protocol/README.md
  packages/inter-protocol/docs/governance-params.md
  packages/inter-protocol/docs/inter-preview-vault-asset.md
  packages/inter-protocol/docs/inter-protocol-preview.md
  packages/inter-protocol/exported.js
  packages/inter-protocol/scripts/deploy-contracts.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/reserve/doc.md
  packages/inter-protocol/src/stakeFactory/README.md
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/inter-protocol/src/stakeFactory/attestationTool.js
  packages/inter-protocol/src/stakeFactory/constants.js
  packages/inter-protocol/src/stakeFactory/params.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/src/stakeFactory/types.js
  packages/inter-protocol/src/vpool-xyk-amm/AttackersGuide.md
  packages/inter-protocol/test/attestation/test-attestation.js
  packages/inter-protocol/test/attestation/test-userFlow.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/stakeFactory/attestationFaker.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/faucet.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/wallet/contract/src/walletFactory.js
  packages/web-components/test/agoric-wallet-connection.test.js
Labels: automerge:rebase

#5846 Make the vatAdmin vat upgradeable
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/devices/vat-admin/device-vat-admin.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/metering/test-dynamic-vat-metered.js
  packages/SwingSet/test/metering/vat-load-dynamic.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-junk.js
  packages/SwingSet/test/util.js
  packages/SwingSet/test/vat-admin/terminate/bootstrap-terminate.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/vat-admin/test-create-vat.js
Labels: enhancement, SwingSet, automerge:rebase

#5884 Add a `defaultReapInterval` setting to active swingset configurations
  packages/solo/solo-config.json
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
Labels: enhancement, SwingSet, performance, hygiene, Governance, solo, automerge:rebase

#5882 Cosmic SwingSet Protobuf IDL stubs for JS and TS
  .github/workflows/test-all-packages.yml
  packages/agoric-cli/src/sdk-package-names.js
  packages/cosmic-proto/LICENSE
  packages/cosmic-proto/MAINTAINERS.md
  packages/cosmic-proto/NEWS.md
  packages/cosmic-proto/README.md
  packages/cosmic-proto/gen/agoric/swingset/msgs.js
  packages/cosmic-proto/gen/agoric/swingset/msgs.ts
  packages/cosmic-proto/gen/gogoproto/gogo.js
  packages/cosmic-proto/gen/gogoproto/gogo.ts
  packages/cosmic-proto/gen/google/protobuf/descriptor.js
  packages/cosmic-proto/gen/google/protobuf/descriptor.ts
  packages/cosmic-proto/jsconfig.json
  packages/cosmic-proto/package.json
  packages/cosmic-proto/proto/agoric
  packages/cosmic-proto/proto/gogoproto
  packages/cosmic-proto/proto/google
  packages/cosmic-proto/swingset/msgs.js
  packages/cosmic-proto/swingset/msgs.ts
  packages/cosmic-proto/test/sanity-test.js
  patches/@confio+ics23++protobufjs+6.11.3.patch
  patches/protobufjs+6.11.3.patch
Labels: automerge:rebase

#5892 fix: patch to suppress turn tracking diagnostics
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/SwingSet/test/vat-admin/test-create-vat.js
  packages/vats/test/test-boot.js
  patches/@endo+eventual-send+0.15.5.patch
Labels: automerge:squash

#5890 Implement swingset-runner test to validate vat process failure behavior
  packages/swingset-runner/demo/workerDeathTest/bootstrap.js
  packages/swingset-runner/demo/workerDeathTest/swingset.json
  packages/swingset-runner/demo/workerDeathTest/vat-busy.js
  packages/swingset-runner/demo/workerDeathTest/vat-idle.js
  packages/swingset-runner/src/main.js
Labels: SwingSet, swingset-runner, test, automerge:rebase

#5876 fix: correct input validation of displayInfo
  packages/ERTP/src/displayInfo.js
  packages/ERTP/src/typeGuards.js
  packages/ERTP/test/unitTests/test-inputValidation.js
  packages/ERTP/test/unitTests/test-issuerObj.js
  packages/store/src/patterns/match-helpers.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
Labels: automerge:squash

#5897 fix(swingset): re-enable refcount test
  packages/SwingSet/test/vat-admin/test-create-vat.js
Labels: SwingSet, automerge:rebase

#5893 test(swingset): exercise vat-vattp upgrade
  packages/SwingSet/test/files-vattp/bootstrap-test-vattp.js
  packages/SwingSet/test/test-vattp.js
Labels: SwingSet, automerge:rebase

#5839 chore: test-collections.js: exercise deletion during iteration
  packages/SwingSet/test/stores/test-collections.js
Labels: SwingSet, automerge:rebase

#4755 Fix typos
  packages/SwingSet/docs/configuration.md
  packages/SwingSet/docs/delivery.md
  packages/SwingSet/docs/devices.md
  packages/SwingSet/docs/garbage-collection.md
  packages/SwingSet/docs/liveslots.md
  packages/SwingSet/docs/persistence.md
  packages/SwingSet/docs/vat-worker.md
  packages/SwingSet/src/devices/timer/device-timer.js
  packages/SwingSet/src/lib/netstring.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/vats/comms/clist-kernel.js
  packages/SwingSet/src/vats/comms/clist.js
  packages/SwingSet/src/vats/comms/delivery.js
  packages/SwingSet/src/vats/comms/state.js
  packages/SwingSet/test/commsVatDriver.js
  packages/SwingSet/test/message-patterns.js
  packages/SwingSet/test/test-netstring.js
  packages/SwingSet/test/virtualObjects/test-retain-remotable.js
  packages/cosmic-swingset/README.md
  packages/governance/docs/AttackGuide.md
  packages/governance/docs/coreArchitecture.puml
  packages/inter-protocol/src/vpool-xyk-amm/constantProduct/README.md
  packages/inter-protocol/src/vpool-xyk-amm/constantProduct/swap.js
  packages/notifier/src/asyncIterableAdaptor.js
  packages/solo/src/web.js
  packages/spawner/README.md
  packages/store/docs/store-taxonomy.md
  packages/store/src/keys/compareKeys.js
  packages/store/src/keys/merge-bag-operators.js
  packages/store/src/keys/merge-set-operators.js
  packages/store/src/types.js
  packages/store/test/test-rankOrder.js
  packages/swingset-runner/demo/exchangeBenchmark/bootstrap.js
  packages/swingset-runner/demo/swapBenchmark/bootstrap.js
  packages/swingset-runner/src/slogulator.js
  packages/ui-components/src/components/NatPurseSelector.jsx
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/ui/src/components/tests/AppBar.test.jsx
  packages/xsnap/test/test-xs-js.js
  packages/xsnap/test/test-xsnap.js
  packages/zoe/test/unitTests/contracts/test-autoswap.js
  packages/zoe/test/unitTests/contracts/test-priceAggregatorChainlink.js
Labels: documentation, hygiene, UI, automerge:rebase

#5904 fix(swingset): don't delete heap snapshot if it didn't change
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/test/xsnap-snapshots/bootstrap-snapshots.js
  packages/SwingSet/test/xsnap-snapshots/test-xsnap-snapshots.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/test/test-snapstore.js
Labels: SwingSet, automerge:rebase

#5906 fix: Better pattern mismatch diagnostics
  packages/ERTP/src/mathHelpers/copyBagMathHelpers.js
  packages/ERTP/src/mathHelpers/copySetMathHelpers.js
  packages/ERTP/src/paymentLedger.js
  packages/SwingSet/src/vats/timer/timeMath.js
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/contracts/coveredCall.js
  packages/zoe/src/zoeService/offer/offer.js
Labels: automerge:squash

#5877 feat(wallet/ui): interactive, background signing
  packages/wallet/ui/package.json
  packages/wallet/ui/src/components/ChainConnector.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/util/SuggestChain.js
  packages/wallet/ui/src/util/chainInfo.js
  packages/wallet/ui/src/util/keyManagement.js
Labels: automerge:squash

#5902 fix: comment wording
  packages/store/src/types.js
Labels: automerge:rebase

#5895 ci(restore-node): verify no `yarn.lock` change after `yarn install`
  .github/actions/restore-node/action.yml
  yarn.lock
Labels: automerge:merge

#5880 fix: Add a script for fetching and flattening published capdata
  scripts/get-flattened-publication.sh
Labels: enhancement, Inter-protocol, automerge:rebase

#5909 dropContext → ignoreContext
  packages/governance/src/contractHelper.js
  packages/vat-data/src/kind-utils.js
  packages/zoe/src/contractFacet/zcfSeat.js
Labels: automerge:rebase

#5913 more RUN remnants
  packages/inter-protocol/docs/governance-params.md
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
Labels: automerge:rebase

#5879 4383 durable zoe
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/unitTests/zoe/test-escrowStorage.js
  packages/zoe/test/unitTests/zoe/test-installationStorage.js
  packages/zoe/test/unitTests/zoe/test-makeInvitation.js
Labels: Zoe, automerge:merge, force:integration, MUST-HAVE

#5921 chore(swingset): Replace ioutil.ReadFile with os.ReadFile
  .github/actions/restore-golang/action.yml
  .github/workflows/golangci-lint.yml
  golang/cosmos/x/swingset/client/cli/tx.go
Labels: SwingSet, hygiene, test

#5916 bump dev deps
  package.json
  packages/ERTP/package.json
  packages/ERTP/test/unitTests/test-amountProperties.js
  packages/eslint-config/package.json
  packages/inter-protocol/package.json
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-amm-calc.js
  packages/store/package.json
  packages/store/test/test-encodePassable.js
  packages/store/test/test-rankOrder.js
  packages/ui-components/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/xsnap/package.json
  yarn.lock
Labels: automerge:rebase

#5883 feat(wallet/api): marshal contexts for wallet, board
  packages/wallet/api/src/marshal-contexts.js
  packages/wallet/api/test/test-middleware.js
  packages/wallet/api/test/test-wallet-marshal.js
Labels: automerge:squash

#5917 feat(vaultFactory)!: split numVaults to numActiveVaults and numLiquidatingVaults
  packages/inter-protocol/src/vaultFactory/orderedVaultStore.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
Labels: Inter-protocol, automerge:squash, Vaults, MUST-HAVE

#5871 5868 ChainStorageCoordinator
  packages/cache/README.md
  packages/cache/package.json
  packages/cache/src/state.js
  packages/cache/src/store.js
  packages/cache/src/types.js
  packages/cache/test/test-storage.js
  packages/casting/src/casting-spec.js
  packages/casting/src/leader-netconfig.js
  packages/casting/test/fake-rpc-server.js
  packages/vats/src/lib-chainStorage.js
  packages/vats/src/vat-chainStorage.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/wallet.js
  packages/wallet/contract/src/singleWallet.js
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/src/support.js
Labels: automerge:rebase

#5905 feat(zoe): add E(userSeat).wasWantSatisfied()
  packages/zoe/src/contractFacet/offerSafety.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/test/unitTests/test-offerSafety.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: enhancement, Zoe, automerge:squash

#5919 feat(liquidation): If liquidation results in a shortfall, don't refund excess
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
Labels: enhancement, Inter-protocol, automerge:squash, Vaults, MUST-HAVE

#5612 quote refactorings
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/priceQuote.js
  packages/zoe/test/unitTests/test-fakePriceAuthority.js
Labels: automerge:rebase

#5922 fix: remove uses of __allowUnsafeMonkeyPatching__
  packages/wallet/ui/src/lockdown.js
  packages/web-components/demo/install-ses-lockdown.js
Labels: automerge:squash

#5941 fix: harden the right thing
  packages/store/src/patterns/rankOrder.js
Labels: automerge:squash

#5939 feat(wallet/api): marshal brand and issuer board ids
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-lib-wallet.js
Labels: automerge:rebase

#5943 style(xsnap): excuse test code from no-nested-await
  packages/xsnap/src/avaAssertXS.js
  packages/xsnap/src/avaXS.js
  packages/xsnap/src/build.js
  packages/xsnap/src/xsrepl.js
Labels: automerge:rebase

#5938 feat(inter-protocol): add amm liquidity script
  packages/inter-protocol/scripts/add-initial-liquidity.js
Labels: automerge:squash

#5935 publication record for AMM liquidityIssuer
  .eslintrc.cjs
  packages/cache/src/store.js
  packages/inter-protocol/README.md
  packages/inter-protocol/src/vpool-xyk-amm/pool.js
Labels: automerge:rebase

#5946 feat(wallet): smart wallet performAction
  packages/wallet/api/src/findOrMakeInvitation.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/src/walletFactory.js
Labels: automerge:squash

#5958 misc wallet-ui dev improvements
  packages/inter-protocol/scripts/add-initial-liquidity.js
  packages/solo/src/scratch.js
  packages/wallet/api/src/types.js
  packages/wallet/api/src/wallet.js
  packages/wallet/ui/package.json
  packages/wallet/ui/src/bridge.jsx
  packages/wallet/ui/src/components/ChainConnector.jsx
  packages/wallet/ui/src/index.jsx
  packages/wallet/ui/src/util/keyManagement.js
  yarn.lock
Labels: automerge:rebase

#5952 fix: bug in M.setOf and M.bagOf
  packages/ERTP/src/typeGuards.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
Labels: automerge:squash

#5949 Wallet UI services
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/marshal-contexts.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/wallet/ui/src/components/IssuerSuggestion.jsx
  packages/wallet/ui/src/components/Offer.jsx
  packages/wallet/ui/src/components/Proposal.jsx
  packages/wallet/ui/src/components/Requests.jsx
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/components/tests/Offer.test.jsx
  packages/wallet/ui/src/components/tests/Requests.test.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/service/Dapps.js
  packages/wallet/ui/src/service/Issuers.js
  packages/wallet/ui/src/service/Offers.js
  packages/wallet/ui/src/service/ScopedBridge.js
  packages/wallet/ui/src/store/Offers.js
  packages/wallet/ui/src/util/WalletBackendAdapter.js
Labels: automerge:squash

#5961 copyBag types
  packages/store/src/keys/checkKey.js
  packages/store/src/keys/copyBag.js
  packages/store/src/types.js
  packages/store/test/test-copyBag.js
Labels: bypass:integration

#5964 fix(wallet/ui): change makeFollower to getUnserializer
  packages/wallet/ui/src/service/ScopedBridge.js
Labels: automerge:squash, bypass:integration

#5944 chore: bump @cosmjs deps
  packages/casting/package.json
  packages/wallet/ui/package.json
  packages/wallet/ui/src/util/keyManagement.js
  yarn.lock
Labels: automerge:rebase, bypass:integration

#5947 fix: better mismatch errors
  packages/ERTP/test/unitTests/test-inputValidation.js
  packages/ERTP/test/unitTests/test-issuerObj.js
  packages/ERTP/test/unitTests/test-mintObj.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-liquidity.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/store/src/patterns/match-helpers.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
  packages/store/test/test-patterns.js
  packages/store/test/test-store.js
  packages/zoe/test/unitTests/test-cleanProposal.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
  packages/zoe/test/unitTests/zcf/test-zoeHelpersWZcf.js
Labels: automerge:squash

#5948 test storage nodes data
  packages/casting/src/casting-spec.js
  packages/casting/src/follower.js
  packages/casting/src/leader-netconfig.js
  packages/governance/test/swingsetTests/committeeBinary/test-committee.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/test-voPool.js
  packages/notifier/src/types.js
  packages/vats/jsconfig.json
  packages/vats/src/lib-chainStorage.js
  packages/vats/test/test-lib-chainStorage.js
  packages/vats/tools/storage-test-utils.js
Labels: automerge:rebase

#5891 make Zoe's instanceRecord durable
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/committee-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/pegasus/src/proposals/core-proposal.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/types.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/zoeService/feeMint.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/unitTests/test-instanceStorage.js
Labels: Zoe, automerge:squash, MUST-HAVE

#5963 feat(vats): publish agoricNames to chainStorage
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/utils.js
  packages/vats/src/nameHub.js
  packages/vats/src/types.js
  packages/vats/test/test-name-hub-published.js
  packages/vats/test/test-name-hub.js
Labels: automerge:merge, bypass:integration

#5957 Add `pinBootstrapRoot` swingset configuration option
  packages/SwingSet/docs/configuration.md
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/basedir-controller-2/bootstrap.js
  packages/SwingSet/test/test-controller.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: enhancement, SwingSet, cosmic-swingset, automerge:rebase

#5967 refactor: make privateArgs in governed contracts be private
  packages/governance/src/contractGovernor.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/swingsetTests/setup.js
Labels: bug, security, Zoe Contract, Governance, automerge:squash

#5945 refactor StorageNode type
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/src/vpool-xyk-amm/pool.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/notifier/src/storesub.js
  packages/notifier/src/types.js
  packages/notifier/test/test-stored-subscription.js
  packages/notifier/tools/testSupports.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/src/lib-chainStorage.js
  packages/vats/test/test-lib-chainStorage.js
  packages/wallet/contract/src/singleWallet.js
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/test/supports.js
  packages/wallet/contract/test/test-singleWallet.js
  packages/wallet/contract/test/test-walletFactory.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
Labels: automerge:rebase

#5980 fix: show more stacks
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/pegasus/src/ics20.js
Labels: automerge:squash, force:integration

#5981 chore: small improvements to replay-transcript tool
  packages/SwingSet/misc-tools/replay-transcript.js
Labels: SwingSet, automerge:squash

#5983 test: missing `await electorateOutcome`, so didn't detect paramChange
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
Labels: Governance, automerge:merge

#5978 style: Rename variables in Go-JS plumbing code for accuracy
  golang/cosmos/cmd/libdaemon/main.go
  golang/cosmos/src/agcosmosdaemon-node.cc
  golang/cosmos/x/swingset/keeper/keeper.go
  packages/cosmic-swingset/src/chain-main.js
  packages/vats/src/chain-storage-paths.js
Labels: cosmic-swingset, hygiene, code-style, automerge:squash, agoric-cosmos

#5984 fix(wallet/ui): style connection component better
  packages/wallet/ui/src/AgoricLogo.jsx
  packages/wallet/ui/src/bridge.jsx
  packages/wallet/ui/src/bridge.scss
  packages/web-components/src/AgoricIframeMessenger.js
  packages/web-components/src/AgoricWalletConnection.js
Labels: automerge:squash

#5988 feat(wallet/ui): expose netconfig url to dapp bridge
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/service/ScopedBridge.js
  packages/wallet/ui/src/util/WalletBackendAdapter.js
Labels: automerge:squash

#5926 feat(chainStorage)!: assertPathSegment (replacing sanitizePathSegment)
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/vats/src/lib-chainStorage.js
  packages/zoe/README.md
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
Labels: automerge:rebase

#5989 fix: prepare for inherited method representation
  packages/ERTP/test/unitTests/test-issuerObj.js
  packages/governance/src/contractHelper.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/store/src/index.js
  packages/store/src/utils.js
  packages/zoe/src/contractFacet/exit.js
  packages/zoe/src/contracts/autoswap.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/test/unitTests/contracts/test-atomicSwap.js
  packages/zoe/test/unitTests/contracts/test-auction.js
  packages/zoe/test/unitTests/contracts/test-coveredCall.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: automerge:squash

#5990 fix(store)!: move some util where they are more reusable
  packages/ERTP/src/paymentLedger.js
  packages/governance/src/contractHelper.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/proposals/demoIssuers.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/test-voPool.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/store/src/index.js
  packages/store/src/patterns/match-helpers.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/utils.js
  packages/vat-data/src/kind-utils.js
  packages/wallet/api/src/lib-wallet.js
  packages/zoe/src/zoeService/escrowStorage.js
Labels: automerge:squash

#5998 fix: avoid relying on bound `E` proxy methods
  packages/casting/test/deploy.js
  packages/governance/test/unitTests/test-committee.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/test/swingsetTests/governance/test-governance.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/test-vaultFactory.js
  packages/notifier/src/storesub.js
  packages/zoe/src/contractFacet/zcfZygote.js
Labels: automerge:squash

#5996 fix(wallet/ui): fix gas price in suggest chain
  packages/wallet/ui/src/util/SuggestChain.js
  packages/wallet/ui/src/util/chainInfo.js
Labels: automerge:rebase

#5847 overhaul vat-timer: virtualized, durable, upgradable, Clock, TimerBrand
  packages/SwingSet/docs/timer.md
  packages/SwingSet/src/vats/timer/types.d.ts
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/SwingSet/test/test-manual-timer.js
  packages/SwingSet/test/test-vat-timer.js
  packages/SwingSet/test/timer/bootstrap-timer.js
  packages/SwingSet/test/timer/test-timer.js
  packages/SwingSet/test/vat-timer-upgrade/bootstrap-vat-timer-upgrade.js
  packages/SwingSet/test/vat-timer-upgrade/test-vat-timer-upgrade.js
  packages/SwingSet/tools/internal-types.js
  packages/SwingSet/tools/manual-timer.js
  packages/governance/test/swingsetTests/committeeBinary/test-committee.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/swingsetTests/setup.js
  packages/inter-protocol/test/test-interest-labeled.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/solo/test/test-home.js
  packages/zoe/test/swingsetTests/zoe/test-zoe.js
  packages/zoe/test/unitTests/contracts/loan/test-borrow.js
  packages/zoe/test/unitTests/contracts/test-auction.js
  packages/zoe/test/unitTests/contracts/test-callSpread.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/test-fakePriceAuthority.js
  packages/zoe/test/unitTests/test-manualTimer.js
  packages/zoe/test/unitTests/test-scriptedOracle.js
  packages/zoe/tools/fakePriceAuthority.js
  packages/zoe/tools/internal-types.js
  packages/zoe/tools/manualTimer.js
Labels: SwingSet, automerge:merge

#5982 5979 fix priceFeed resolution
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/inter-protocol/test/supports.js
  packages/vats/tools/storage-test-utils.js
  packages/zoe/src/contractSupport/priceQuote.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
Labels: automerge:rebase

#4422 feat: NonNullish checked cast
  packages/assert/package.json
  packages/assert/src/assert.js
  packages/assert/test/test-assert.js
Labels: automerge:rebase

#5942 feat!: Support publishing and consuming chain storage stream cells
  .github/workflows/test-scripts.yml
  golang/cosmos/x/vstorage/keeper/keeper.go
  golang/cosmos/x/vstorage/vstorage.go
  packages/casting/src/follower-cosmjs.js
  packages/casting/test/fake-rpc-server.js
  packages/casting/test/test-mvp.js
  packages/notifier/src/types.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/lib-chainStorage.js
  packages/vats/src/vat-chainStorage.js
  packages/vats/test/test-lib-chainStorage.js
  packages/vats/tools/storage-test-utils.js
  scripts/get-flattened-publication.sh
  scripts/test/README.md
  scripts/test/test-get-flattened-publication/bin/curl
  scripts/test/test-get-flattened-publication/fixtures/capdata.json
  scripts/test/test-get-flattened-publication/fixtures/flattened-naked.json
  scripts/test/test-get-flattened-publication/fixtures/flattened-streamcell.json
  scripts/test/test-get-flattened-publication/test.sh
  scripts/test/test.sh
Labels: enhancement, automerge:rebase, javascript

#6013 4968 psm econ data
  packages/inter-protocol/README.md
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/vaultFactory/test-liquidator.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/inter-protocol/test/vaultFactory/test-vault-interest.js
  packages/inter-protocol/test/vaultFactory/test-vault.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
Labels: automerge:rebase

#6001 5992 internal package
  .github/workflows/test-all-packages.yml
  package.json
  packages/agoric-cli/src/sdk-package-names.js
  packages/governance/package.json
  packages/governance/src/contractHelper.js
  packages/inter-protocol/package.json
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/proposals/demoIssuers.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/test-voPool.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/internal/README.md
  packages/internal/jsconfig.json
  packages/internal/package.json
  packages/internal/src/index.js
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
  packages/store/package.json
  packages/store/src/index.js
  packages/store/src/patterns/patternMatchers.js
  packages/vat-data/package.json
  packages/vat-data/src/kind-utils.js
  packages/wallet/api/package.json
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/contract/src/support.js
  packages/zoe/package.json
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: automerge:rebase

#6012 fix: align issuer declaration order
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/types.js
Labels: automerge:squash

#6030 refactor(psm)!: split PSM invitations to enable pausing separately
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/test/psm/test-psm.js
Labels: Inter-protocol, automerge:squash, pso

#6029 fix(swingset): don't un-expose 'gc', to stop intermittent test failures
  packages/SwingSet/src/lib-nodejs/engine-gc.js
Labels: SwingSet, automerge:rebase

#6010 chore(zoe): missing setOfferFilter on ZCF type
  packages/zoe/src/contractFacet/types.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: automerge:rebase, bypass:integration

#6040 chore(swingset): update some utilities in misc-tools/
  packages/SwingSet/misc-tools/elapsed-per-method.py
  packages/SwingSet/misc-tools/extract-contract.js
  packages/SwingSet/misc-tools/syscall-by-type.py
Labels: SwingSet, automerge:rebase

#6036 store econ committee questions off-chain
  packages/governance/README.md
  packages/governance/docs/coreArchitecture.puml
  packages/governance/package.json
  packages/governance/src/committee.js
  packages/governance/src/electorateTools.js
  packages/governance/src/internalTypes.js
  packages/governance/src/noActionElectorate.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/committeeBinary/bootstrap.js
  packages/governance/test/swingsetTests/committeeBinary/test-committee.js
  packages/governance/test/swingsetTests/committeeBinary/vat-voter.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/vat-voter.js
  packages/governance/test/unitTests/test-committee.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/inter-protocol/README.md
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/swingsetTests/governance/vat-voter.js
Labels: automerge:rebase, pso

#6042 test(xsnap): disable timestamp test until it tolerates fast CI hosts
  packages/xsnap/test/test-xs-perf.js
Labels: xsnap, automerge:rebase

#5993 improve static typing of contract start terms
  packages/governance/src/contractGovernor.js
  packages/governance/test/unitTests/test-committee.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/committee-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/internal/package.json
  packages/internal/src/utils.js
  packages/vat-data/src/index.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/vat-data-bindings.js
  packages/vats/package.json
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/src/mintHolder.js
  packages/vats/test/test-bootstrapPayment.js
  packages/wallet/contract/src/singleWallet.js
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/src/walletFactory.js
  packages/wallet/contract/test/test-singleWallet.js
  packages/wallet/contract/test/test-walletFactory.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/utils.d.ts
Labels: automerge:rebase

#6043 chore(swingset): more misc-tools updates
  packages/SwingSet/misc-tools/correlate-timestamps.py
  packages/SwingSet/misc-tools/cranks-per-minute.py
  packages/SwingSet/misc-tools/extract-contract-from-transcript.js
  packages/SwingSet/misc-tools/extract-vat-from-transcript.js
  packages/SwingSet/misc-tools/measure-boyd-gc.py
  packages/SwingSet/misc-tools/pair-deltas.py
  packages/SwingSet/misc-tools/parse_timestamps.py
  packages/SwingSet/misc-tools/syscall-by-type.py
Labels: SwingSet, automerge:rebase

#6049 feat(cosmos): enable fees for MsgWalletAction, MsgWalletSpendAction
  golang/cosmos/x/swingset/types/msgs.go
Labels: automerge:merge, agoric-cosmos

#6066 ci(Mergify): remove check failed rules for integration tests
  .mergify.yml
Labels: bypass:integration

#6052 docs(swingset): document criticalVatKey
  packages/SwingSet/docs/dynamic-vats.md
  packages/SwingSet/docs/static-vats.md
Labels: SwingSet, automerge:rebase

#6037 5796 govern pause
  packages/governance/README.md
  packages/governance/src/contractGovernance/governApi.js
  packages/governance/src/contractGovernance/governFilter.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractHelper.js
  packages/governance/src/question.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/committeeBinary/vat-voter.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
Labels: Zoe, Governance, automerge:squash, pso

#6058 fix(swing-store): use sqlite transactions for streamStore operations
  packages/swing-store/package.json
  packages/swing-store/src/sqlStreamStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-state.js
  yarn.lock
Labels: SwingSet, automerge:merge

#6047 6007 test pause PSM
  packages/governance/src/contractHelper.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/psm/test-governedPsm.js
  packages/inter-protocol/test/psm/test-psm.js
Labels: test, Inter-protocol, automerge:squash, pso

#6063 Fix process-integration-results.sh
  scripts/process-integration-results.sh
  scripts/process-integration-swingstore-traces.sh
Labels: automerge:rebase

#6035 chore: Sync Endo versions
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/SwingSet/test/xsnap-snapshots/test-xsnap-snapshots.js
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/contract/package.json
  packages/wallet/ui/package.json
  packages/wallet/ui/public/index.html
  packages/web-components/README.md
  packages/web-components/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  patches/@endo+eventual-send+0.15.5.patch
  patches/@endo+ses-ava+0.2.31.patch
  yarn.lock
Labels: automerge:rebase, force:integration

#5970 fix(SwingSet)!: Representatives inherit bound methods
  packages/SwingSet/package.json
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/test-vat-timer.js
  packages/SwingSet/tools/manual-timer.js
  packages/internal/src/utils.js
  packages/zoe/tools/manualTimer.js
Labels: automerge:squash

#6080 refactor(store)!: split `provide` into collision vs no-collision variants
  packages/ERTP/src/transientNotifier.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/src/vats/vattp/vat-vattp.js
  packages/SwingSet/test/vo-test-harness/vat-dvo-test-test.js
  packages/assert/src/types.js
  packages/inter-protocol/scripts/deploy-contracts.js
  packages/inter-protocol/src/proposals/utils.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/store/src/index.js
  packages/store/src/stores/store-utils.js
  packages/store/test/test-store.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/vat-data-bindings.js
  packages/vats/src/core/basic-behaviors.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/makeHandle.js
Labels: automerge:squash

#6076 refactor(store)!: fix bad check defaults
  packages/store/src/keys/checkKey.js
  packages/store/src/keys/copyBag.js
  packages/store/src/keys/copySet.js
  packages/store/src/patterns/internal-types.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
  packages/store/test/test-patterns.js
Labels: automerge:squash

#6020 feat: PSM-only bootstrap
  packages/SwingSet/src/devices/mailbox/device-mailbox.js
  packages/cosmic-swingset/Makefile
  packages/inter-protocol/scripts/build-bundles.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/vats/decentral-psm-config.json
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/test/devices.js
  packages/vats/test/test-boot.js
Labels: automerge:merge

#6079 fix: ALWAYS default to safe
  packages/wallet/ui/src/lockdown.js
  packages/web-components/README.md
  packages/web-components/demo/index.html
  packages/web-components/demo/install-demo-ses-lockdown.js
  packages/web-components/test/agoric-wallet-connection.test.js
Labels: automerge:squash

#6068 fix(vats): chainStorage vat writes directly to device
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/vat-chainStorage.js
Labels: automerge:rebase

#6073 fix(telemetry): Use transactions for tmp telemetry DB
  packages/telemetry/src/kv-string-store.js
  packages/telemetry/src/slog-to-otel.js
Labels: automerge:rebase

#6078 fix(wallet/api): prune inactive historical offers
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-lib-wallet.js
Labels: automerge:squash

#6032 feat(scripts): Improve get-flattened-publication.sh
  scripts/get-flattened-publication.sh
  scripts/test/test-get-flattened-publication/fixtures/capdata.json
  scripts/test/test-get-flattened-publication/fixtures/flattened-naked.json
  scripts/test/test-get-flattened-publication/fixtures/flattened-streamcell.json
  scripts/test/test-get-flattened-publication/test.sh
Labels: enhancement, automerge:rebase

#6072 refactor(store)!: move from Schema to Shape terminology
  packages/ERTP/src/issuerKit.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/types.js
  packages/ERTP/test/unitTests/mathHelpers/test-natMathHelpers.js
  packages/ERTP/test/unitTests/test-mintObj.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/watchedPromises.js
  packages/SwingSet/test/gc-helpers.js
  packages/SwingSet/test/stores/test-collections.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/types.js
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/offer/offer.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/unitTests/contractSupport/test-offerTo.js
  packages/zoe/test/unitTests/makeOffer.js
  packages/zoe/test/unitTests/zoe/test-makeInvitation.js
Labels: automerge:squash

#6082 fix: patch to emulate endo #1275
  patches/@endo+marshal+0.7.3.patch
Labels: automerge:squash

#6095 fix(wallet/contract): bounded updates: recent offers / payments only
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/wallet/contract/src/smartWallet.js
Labels: automerge:squash
