Repository Agoric/agoric-sdk, pull requests merged in 2022-07, with the labels that each got.

#5705 fix(telemetry): do not mutate the original slog object
  packages/telemetry/src/ingest-slog-entrypoint.js
  packages/telemetry/src/slog-to-otel.js
Labels: automerge:squash

#5706 fix(swingset): stop using a persistent kernel bundle
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/test/device-hooks/test-device-hooks.js
  packages/SwingSet/test/device-mailbox/test-device-mailbox.js
  packages/SwingSet/test/devices/test-devices.js
  packages/SwingSet/test/devices/test-raw-device.js
  packages/SwingSet/test/test-message-patterns.js
  packages/SwingSet/test/upgrade/test-upgrade-replay.js
  packages/SwingSet/test/util.js
  packages/SwingSet/test/vat-admin/test-create-vat.js
Labels: SwingSet, automerge:rebase

#5689 fix: apparent error charging interest during liquidation
  packages/run-protocol/src/vaultFactory/prioritizedVaults.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/vaultFactory/test-prioritizedVaults.js
Labels: automerge:rebase

#5712 fix(wallet-api): dont rely on attestation brand
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-lib-wallet.js
Labels: automerge:rebase

#5710 fix: shutdown controller after tests
  packages/ERTP/test/swingsetTests/basicFunctionality/test-basicFunctionality.js
  packages/ERTP/test/swingsetTests/splitPayments/test-splitPayments.js
  packages/SwingSet/test/bundling/test-bundles-controller.js
  packages/SwingSet/test/bundling/test-bundles.js
  packages/SwingSet/test/change-parameters/test-change-parameters.js
  packages/SwingSet/test/definition/test-vat-definition.js
  packages/SwingSet/test/device-hooks/test-device-hooks.js
  packages/SwingSet/test/device-mailbox/test-device-mailbox.js
  packages/SwingSet/test/device-plugin/test-device.js
  packages/SwingSet/test/devices/test-devices.js
  packages/SwingSet/test/devices/test-raw-device.js
  packages/SwingSet/test/gc/test-gc-vat.js
  packages/SwingSet/test/metering/test-dynamic-vat-unmetered.js
  packages/SwingSet/test/promise-watcher/test-promise-watcher.js
  packages/SwingSet/test/run-policy/test-run-policy.js
  packages/SwingSet/test/test-controller.js
  packages/SwingSet/test/test-demos-comms.js
  packages/SwingSet/test/test-demos.js
  packages/SwingSet/test/test-device-bridge.js
  packages/SwingSet/test/test-exomessages.js
  packages/SwingSet/test/test-gc-kernel.js
  packages/SwingSet/test/test-promises.js
  packages/SwingSet/test/test-syscall-failure.js
  packages/SwingSet/test/test-transcript-light.js
  packages/SwingSet/test/test-transcriptlessness.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/test-vattp.js
  packages/SwingSet/test/timer-device/test-device.js
  packages/SwingSet/test/timer/test-timer.js
  packages/SwingSet/test/upgrade/test-upgrade-replay.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate-critical.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/vat-admin/test-create-vat.js
  packages/SwingSet/test/vat-admin/test-replay.js
  packages/SwingSet/test/vat-warehouse/test-reload-snapshot.js
  packages/SwingSet/test/virtualObjects/collection-slots/test-collection-slots.js
  packages/SwingSet/test/virtualObjects/delete-stored-vo/test-delete-stored-vo.js
  packages/SwingSet/test/virtualObjects/double-retire-import/test-double-retire-import.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-weakcollections.js
  packages/SwingSet/test/virtualObjects/vdata-promises/test-vdata-promises.js
  packages/SwingSet/tools/vo-test-harness.js
  packages/governance/test/swingsetTests/committeeBinary/test-committee.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/run-protocol/test/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/swingsetTests/vaultFactory/test-vaultFactory.js
  packages/sharing-service/test/swingsetTests/sharingService/test-sharing.js
  packages/spawner/test/swingsetTests/contractHost/test-contractHost.js
  packages/xsnap/src/xsnap.js
  packages/zoe/test/swingsetTests/brokenContracts/test-crashingContract.js
  packages/zoe/test/swingsetTests/makeKind/test-makeKind.js
  packages/zoe/test/swingsetTests/offerArgs/test-offerArgs.js
  packages/zoe/test/swingsetTests/privateArgs/test-privateArgs.js
  packages/zoe/test/swingsetTests/runMint/test-runMint.js
  packages/zoe/test/swingsetTests/zoe/test-zoe.js
Labels: automerge:rebase

#5715 chore: speed up test-upgrade.js by sharing kernel bundles
  packages/SwingSet/test/upgrade/test-upgrade.js
Labels: SwingSet, automerge:rebase

#5685 feat(wallet-ui): more robust connection config ui
  packages/wallet/ui/package.json
  packages/wallet/ui/src/components/AppBar.jsx
  packages/wallet/ui/src/components/ConnectionSettingsDialog.jsx
  packages/wallet/ui/src/components/Loading.jsx
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/components/WalletConnection.jsx
  packages/wallet/ui/src/components/tests/AppBar.test.jsx
  packages/wallet/ui/src/components/tests/WalletConnection.test.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/tests/App.test.jsx
  packages/wallet/ui/src/util/connections.js
  packages/wallet/ui/src/util/defaults.js
  packages/wallet/ui/src/views/Issuers.jsx
  yarn.lock
Labels: automerge:squash

#5698 ci: Constrain GitHub workflows to the agoric organization
  .github/workflows/after-merge.yml
  .github/workflows/docker.yml
  .github/workflows/integration.yml
Labels: automerge:squash

#5727 chore(swingset): hush logging in virtual-object test
  packages/SwingSet/test/virtualObjects/vdata-promises/test-vdata-promises.js
  packages/SwingSet/test/virtualObjects/vdata-promises/vat-vdata-promises.js
Labels: SwingSet, automerge:rebase

#5721 4484 multitenant smart wallet
  packages/store/src/stores/store-utils.js
  packages/store/test/test-AtomicProvider.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/scripts/build-bundles.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/test/devices.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/wallet.js
  packages/wallet/contract/package.json
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/src/walletFactory.js
  packages/wallet/contract/test/devices.js
  packages/wallet/contract/test/test-walletFactory.js
Labels: automerge:rebase

#5009 refactor(run-protocol)!: remove `interestRate` and `liquidationRatio` from vault notifier
  packages/run-protocol/src/runStake/runStakeKit.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: automerge:rebase

#5726 fix(swingset): don't double-allocate durable object vrefs
  packages/SwingSet/src/liveslots/vatstore-usage.md
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
Labels: SwingSet, automerge:rebase

#5732 ci: warn on nested awaits
  .eslintrc.cjs
Labels: automerge:rebase

#5728 use atomic store provider in AMM
  packages/run-protocol/src/vpool-xyk-amm/addPool.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/store/src/stores/store-utils.js
  packages/store/test/test-AtomicProvider.js
Labels: automerge:rebase

#5283 feat(ertp): durability
  packages/ERTP/package.json
  packages/ERTP/src/brand.js
  packages/ERTP/src/issuerKit.js
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/src/transientNotifier.js
  packages/ERTP/src/types.js
  packages/ERTP/test/swingsetTests/ertpService/bootstrap-ertp-service-upgrade.js
  packages/ERTP/test/swingsetTests/ertpService/test-ertp-service-upgrade.js
  packages/ERTP/test/swingsetTests/ertpService/vat-ertp-service.js
  packages/ERTP/test/unitTests/test-inputValidation.js
  packages/ERTP/test/unitTests/test-interfaces.js
  packages/ERTP/test/unitTests/test-mintObj.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/promise-watcher/vat-upton.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vo-test-harness/vat-dvo-test-test.js
  packages/SwingSet/tools/fakeVirtualObjectManager.js
  packages/SwingSet/tools/prepare-test-env.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/run-protocol/src/runStake/attestation.js
  packages/store/src/stores/store-utils.js
  packages/store/src/types.js
  packages/vat-data/src/index.js
  packages/vat-data/src/index.test-d.ts
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/types.d.ts
  packages/vat-data/src/vat-data-bindings.js
  packages/vats/src/vat-zoe.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/zoe/src/makeHandle.js
  packages/zoe/src/objArrayConversion.js
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/swingsetTests/brokenContracts/test-crashingContract.js
  packages/zoe/test/swingsetTests/offerArgs/test-offerArgs.js
  packages/zoe/test/swingsetTests/zoe/test-zoe.js
  yarn.lock
Labels: automerge:squash

#5741 feat: read only smart wallet
  packages/cosmic-swingset/Makefile
  packages/wallet/ui/public/network-config
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/util/connections.js
Labels: automerge:squash

#5651 Enforce size limits on syscalls containing capdata
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/tools/fakeCollectionManager.js
  packages/SwingSet/tools/fakeVirtualObjectManager.js
  packages/SwingSet/tools/fakeVirtualSupport.js
Labels: SwingSet, hygiene, automerge:rebase

#5111 fix: avoid race by requesting lien change as a delta
  golang/cosmos/x/lien/keeper/keeper.go
  golang/cosmos/x/lien/keeper/keeper_test.go
  golang/cosmos/x/lien/lien.go
  golang/cosmos/x/lien/lien_test.go
  golang/cosmos/x/lien/spec/02_messages.md
  packages/run-protocol/src/my-lien.js
  packages/run-protocol/src/runStake/README.md
  packages/run-protocol/src/runStake/attestation.js
  packages/run-protocol/src/runStake/types.js
  packages/run-protocol/test/attestation/test-attestation.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/vats/src/my-lien.js
Labels: cosmic-swingset, BLD-Boost, automerge:merge

#5641 Enable collection deletion without swapping in key objects
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/test/gc-helpers.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/store/src/index.js
  packages/store/src/patterns/encodePassable.js
Labels: enhancement, SwingSet, automerge:rebase

#5707 fix(swingset): remove xs-worker-no-gc and gcEveryCrank
  packages/SwingSet/docs/configuration.md
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
Labels: SwingSet, automerge:rebase

#5744 feat(wallet-ui): connect to keplr with smart wallet
  packages/wallet/ui/src/components/ConnectionSettingsDialog.jsx
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/util/DeepEquals.js
  packages/wallet/ui/src/util/SuggestChain.js
Labels: automerge:squash

#5743 fix(walletFactory): marshal using petnames
  packages/vats/src/core/basic-behaviors.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/types.js
  packages/wallet/api/src/wallet.js
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/src/walletFactory.js
Labels: automerge:squash

#5746 5622 vaultManager ephemera
  packages/run-protocol/src/contractSupport.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/tools/manualPriceAuthority.js
Labels: automerge:squash

#5753 Publish Reserve econ data: mint & burn
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/test/metrics.js
  packages/run-protocol/test/reserve/test-reserve.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: enhancement, Inter-protocol, automerge:squash

#5757 build(wallet-ui): lint types
  packages/ui-components/src/components/NatPurseSelector.jsx
  packages/wallet/ui/jsconfig.json
  packages/wallet/ui/package.json
Labels: automerge:squash

#5737 feat(notifier): Add makeNotifierFromSubscriber
  packages/notifier/src/index.js
  packages/notifier/src/notifier.js
  packages/notifier/test/iterable-testing-tools.js
  packages/notifier/test/test-makeNotifierFromSubscriber.js
Labels: automerge:squash

#5730 rewrite delivery-result processing, rewind failed upgrades
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/vat-admin-hooks.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/metering/test-dynamic-vat-metered.js
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
Labels: SwingSet, automerge:rebase

#5750 feat(wallet-connection): Connect dapp directly to wallet UI
  docs/env.md
  packages/casting/README.md
  packages/solo/package.json
  packages/solo/public/wallet-bridge.html
  packages/solo/src/web.js
  packages/wallet/api/src/wallet.js
  packages/wallet/ui/config-overrides/index.js
  packages/wallet/ui/jsconfig.json
  packages/wallet/ui/package.json
  packages/wallet/ui/public/bridge.html
  packages/wallet/ui/src/bridge.jsx
  packages/wallet/ui/src/components/Offer.jsx
  packages/wallet/ui/src/components/WalletConnection.jsx
  packages/wallet/ui/src/components/tests/Offer.test.jsx
  packages/wallet/ui/src/components/tests/WalletConnection.test.jsx
  packages/wallet/ui/src/lockdown.js
  packages/wallet/ui/src/util/BridgeStorage.js
  packages/web-components/demo/index.html
  packages/web-components/src/AgoricIframeMessenger.js
  packages/web-components/src/AgoricWalletConnection.js
  packages/web-components/src/bridge-iframe-connector.js
  yarn.lock
Labels: automerge:squash

#5765 feat(vats): bootstrap.produceItem(), consumeItem, resetItem
  packages/vats/src/core/boot.js
  packages/vats/test/test-boot.js
Labels: automerge:rebase

#5770 5764 upgrade contracts
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/types.d.ts
  packages/wallet/api/test/attestationExample.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/bootstrap-coveredCall-service-upgrade.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/coveredCall-durable-V3.js
  packages/zoe/test/unitTests/zcf/registerFeeMintContract.js
Labels: Zoe

#5755 Require that durable object kind shape be conserved across upgrades
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/vatstore-usage.md
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
Labels: bug, SwingSet, hygiene, automerge:rebase

#5766 feat(notifier): makeStoredPublishKit
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/notifier/src/storesub.js
  packages/notifier/src/types.js
  packages/notifier/test/test-publish-kit.js
  packages/notifier/test/test-stored-subscription.js
Labels: automerge:rebase

#5704 5346 replace uses of makeNotifierKit with makeNotifierFromSubscriber
  packages/run-protocol/src/contractSupport.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/proposals/startPSM.js
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/runStake/runStakeKit.js
  packages/run-protocol/src/runStake/runStakeManager.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultHolder.js
  packages/run-protocol/src/vaultFactory/vaultKit.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/priceAuthority.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/metrics.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/test-voPool.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/src/lib-chainStorage.js
  packages/vats/test/test-clientBundle.js
  packages/wallet/contract/test/test-singleWallet.js
  packages/wallet/contract/test/test-walletFactory.js
  packages/zoe/src/contractSupport/priceAuthority.js
Labels: automerge:rebase

#5777 Refactor liveslots options handling
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-node.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/supervisors/nodeworker/supervisor-nodeworker.js
  packages/SwingSet/src/supervisors/subprocess-node/supervisor-subprocess-node.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/liveslots-helpers.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/test-xsnap-errors.js
Labels: SwingSet, hygiene, automerge:rebase

#5774 testing improvements
  packages/SwingSet/test/test-message-patterns.js
  packages/notifier/test/test-publish-kit.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/solo/test/test-home.js
  packages/ui-components/test/display/test-display.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/test/unitTests/contracts/loan/test-addCollateral.js
  packages/zoe/test/unitTests/contracts/loan/test-borrow.js
  packages/zoe/test/unitTests/contracts/loan/test-close.js
  packages/zoe/test/unitTests/contracts/loan/test-loan-e2e.js
  patches/@endo+ses-ava+0.2.27.patch
Labels: automerge:rebase

#5778 fix(golang): swingset wallet-action cli was not quite wired up
  golang/cosmos/x/swingset/client/cli/tx.go
Labels: automerge:rebase

#5635 Durable ZCF
  packages/ERTP/test/swingsetTests/ertpService/vat-ertp-service.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/types.d.ts
  packages/vats/src/core/basic-behaviors.js
  packages/vats/test/test-boot.js
  packages/wallet/api/test/attestationExample.js
  packages/zoe/src/contractFacet/allocationMath.js
  packages/zoe/src/contractFacet/internal-types.js
  packages/zoe/src/contractFacet/offerHandlerStorage.js
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contractFacet/vatRoot.js
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/issuerStorage.js
  packages/zoe/src/zoeService/createZCFVat.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/bootstrap-coveredCall-service-upgrade.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/coveredCall-durable-V3.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/test-coveredCall-service-upgrade.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/vat-ertp-service.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/vat-zoe.js
  packages/zoe/test/unitTests/bounty.js
  packages/zoe/test/unitTests/contractSupport/test-depositTo.js
  packages/zoe/test/unitTests/contractSupport/test-offerTo.js
  packages/zoe/test/unitTests/contracts/test-sellTickets.js
  packages/zoe/test/unitTests/contracts/test-throwInOfferHandler.js
  packages/zoe/test/unitTests/test-issuerStorage.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/registerFeeMintContract.js
  packages/zoe/test/unitTests/zcf/test-offerHandlerStorage.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
  packages/zoe/test/unitTests/zcf/test-zcfSeat.js
  packages/zoe/test/unitTests/zcf/test-zoeHelpersWZcf.js
  packages/zoe/test/unitTests/zoe/test-createZCFVat.js
  packages/zoe/tools/fakeVatAdmin.js
Labels: enhancement, Zoe, automerge:squash

#5749 feature: give contracts the ability to pause invitations
  packages/zoe/package.json
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/offer/offer.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/makeOffer.js
  packages/zoe/test/unitTests/test-blockedOffers.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: enhancement, Zoe Contract, Governance, automerge:squash

#5784 fix: serialize all tests in test-terminate.js to avoid fatal memory-usage spike
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
Labels: SwingSet, automerge:rebase

#5748 fix(swingstore): clarify promise handling
  packages/swing-store/src/swingStore.js
Labels: automerge:rebase

#5768 Distinctive rejection values for promises severed by vat upgrade
  packages/SwingSet/src/devices/vat-admin/device-vat-admin.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-admin-hooks.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/lib/message.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/stop-vat.js
  packages/SwingSet/src/liveslots/watchedPromises.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/gc-helpers.js
  packages/SwingSet/test/promise-watcher/bootstrap-promise-watcher.js
  packages/SwingSet/test/promise-watcher/test-promise-watcher.js
  packages/SwingSet/test/promise-watcher/vat-upton.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/bootstrap-coveredCall-service-upgrade.js
Labels: enhancement, SwingSet, automerge:rebase

#5780 5386 off chain reads
  package.json
  packages/eslint-config/package.json
  packages/notifier/package.json
  packages/notifier/test/test-stored-subscription.js
  packages/notifier/tools/testSupports.js
  packages/run-protocol/README.md
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultHolder.js
  packages/run-protocol/src/vaultFactory/vaultKit.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/src/vpool-xyk-amm/addPool.js
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/priceAuthority.js
  packages/run-protocol/test/supports.js
  packages/run-protocol/test/test-voPool.js
  packages/run-protocol/test/vaultFactory/driver.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-storage.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/run-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/ui-components/package.json
  packages/vats/src/lib-chainStorage.js
  scripts/lint-with-types.sh
  yarn.lock
Labels: automerge:rebase

#5804 feat: store dapps in localstorage not contract
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/service/Dapps.js
  packages/wallet/ui/src/service/ScopedBridge.js
  packages/wallet/ui/src/store/Dapps.js
  packages/wallet/ui/src/util/WalletBackendAdapter.js
Labels: automerge:squash

#5736 4550 vault factory durable (unreachably)
  packages/SwingSet/tools/fakeVirtualSupport.js
  packages/inter-protocol/src/vaultFactory/orderedVaultStore.js
  packages/inter-protocol/src/vaultFactory/prioritizedVaults.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-orderedVaultStore.js
  packages/inter-protocol/test/vaultFactory/test-prioritizedVaults.js
  packages/inter-protocol/test/vaultFactory/test-vault.js
  packages/store/src/types.js
  packages/wallet/contract/src/walletFactory.js
Labels: automerge:rebase

#5802 rename run-protocol package to inter-protocol
  packages/SwingSet/misc-tools/measure-metering/measurement-bootstrap.js
  packages/agoric-cli/src/sdk-package-names.js
  packages/cosmic-swingset/economy-template.json
  packages/inter-protocol/package.json
  packages/vats/decentral-demo-config.json
  packages/vats/demo-proposals.json
  packages/vats/package.json
  packages/vats/src/core/boot.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/test/test-clientBundle.js
  packages/wallet/api/package.json
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/contract/package.json
  packages/wallet/contract/test/test-singleWallet.js
  packages/wallet/contract/test/test-walletFactory.js
  scripts/lint-with-types.sh
Labels: automerge:rebase, force:integration

#5820 fix(vault): move outerUpdater out of durable state
  packages/inter-protocol/src/vaultFactory/vault.js
Labels: automerge:rebase

#5785 make assetReserve reachably durable
  packages/governance/package.json
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractHelper.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/inter-protocol/test/reserve/setup.js
  packages/inter-protocol/test/reserve/test-reserve.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/types.d.ts
  packages/vats/src/core/chain-behaviors.js
Labels: Inter-protocol, automerge:squash, force:integration

#5813 5346 public subscribers
  packages/inter-protocol/src/runStake/runStake.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/test/swingsetTests/governance/vat-alice.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/vat-alice.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/continuingInvitationExample.js
Labels: automerge:rebase

#5812 last references to run-protocol
  packages/SwingSet/misc-tools/measure-metering/measure.js
  packages/cosmic-swingset/Makefile
  packages/inter-protocol/Makefile
  packages/inter-protocol/README.md
  packages/inter-protocol/docs/governance-params.md
  packages/inter-protocol/docs/run-preview-vault-asset.md
  packages/inter-protocol/docs/run-protocol-preview.md
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/runStake/types.js
  packages/inter-protocol/src/vpool-xyk-amm/AttackersGuide.md
  packages/pegasus/src/types.js
  packages/vats/src/core/basic-behaviors.js
  packages/zoe/src/contractSupport/types.js
Labels: automerge:rebase

#5829 ci: ensure deployment test runs some loadgen cycles
  packages/deployment/scripts/integration-test.sh
Labels: automerge:squash

#5831 chore: let virtual-object state be enumerable, for debugging
  packages/SwingSet/src/liveslots/virtualObjectManager.js
Labels: SwingSet, automerge:rebase

#5826 fix: userSeat allocation only for testing
  packages/inter-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-liquidity.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/wallet/api/src/lib-wallet.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: automerge:squash

#5805 clean up run-protocol exports
  packages/SwingSet/tools/bundleTool.js
  packages/inter-protocol/exported.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/collect.js
  packages/inter-protocol/src/exported.js
  packages/inter-protocol/src/index.js
  packages/inter-protocol/src/proposals/demoIssuers.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-addLiquidity.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-liquidity.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/reserve/test-reserve.js
  packages/inter-protocol/test/runStake/test-runStake.js
  packages/inter-protocol/test/swingsetTests/governance/test-governance.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/inter-protocol/test/test-interchainPool.js
  packages/inter-protocol/test/test-voPool.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/vat-data/src/kind-utils.js
  packages/wallet/contract/package.json
  packages/wallet/contract/test/supports.js
  packages/wallet/contract/test/test-singleWallet.js
  packages/wallet/contract/test/test-walletFactory.js
Labels: automerge:rebase

#5827 docs(SwingSet): Update virtual object documentation
  packages/SwingSet/docs/virtual-objects.md
Labels: documentation, automerge:squash

#5837 chore(vats): Improve description of chain storage segment name constraints
  packages/vats/src/lib-chainStorage.js
Labels: automerge:rebase

#5821 fix: time as branded value
  packages/SwingSet/misc-tools/measure-metering/measurement-bootstrap.js
  packages/SwingSet/package.json
  packages/SwingSet/src/vats/timer/timeMath.js
  packages/SwingSet/src/vats/timer/timed-iteration.js
  packages/SwingSet/src/vats/timer/typeGuards.js
  packages/SwingSet/src/vats/timer/types.js
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/SwingSet/test/timer/test-timeMath.js
  packages/inter-protocol/src/interest.js
  packages/inter-protocol/src/runStake/runStakeManager.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/reserve/test-reserve.js
  packages/inter-protocol/test/swingsetTests/governance/vat-alice.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/inter-protocol/test/test-interest-labeled.js
  packages/solo/test/test-home.js
  packages/store/src/patterns/patternMatchers.js
  packages/zoe/src/contracts/auction/index.js
  packages/zoe/src/contracts/loan/updateDebt.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/test/unitTests/contracts/loan/test-borrow.js
  packages/zoe/tools/manualTimer.js
Labels: automerge:squash

#5806 fix: SMART_WALLET account flag for smart wallet vs. ag-solo client
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/types.js
Labels: automerge:squash

#5858 simplify timer global types
  packages/SwingSet/exported.js
  packages/SwingSet/src/vats/timer/types.d.ts
  packages/SwingSet/src/vats/timer/types.js
Labels: automerge:rebase, bypass:integration

#5841 Reachable durability for the AMM
  packages/governance/src/contractHelper.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/inter-protocol/src/vpool-xyk-amm/addPool.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/src/vpool-xyk-amm/params.js
  packages/inter-protocol/src/vpool-xyk-amm/pool.js
  packages/inter-protocol/src/vpool-xyk-amm/singlePool.js
  packages/inter-protocol/src/vpool-xyk-amm/types.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/inter-protocol/test/test-voPool.js
  packages/vat-data/src/kind-utils.js
Labels: AMM, automerge:squash, force:integration, MUST-HAVE

#5779 fix(golang): complete ledger support for MsgWallet{Spend}Action
  golang/cosmos/x/swingset/types/codec.go
  golang/cosmos/x/swingset/types/msgs.go
Labels: automerge:squash

#5857 make the PSM reachably durable
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/test/psm/test-psm.js
Labels: enhancement, Zoe Contract, Core Economy, automerge:squash, force:integration

#5850 4652 public priceAggregator medians off-chain
  go.mod
  go.sum
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/vats/src/core/types.js
  packages/vats/src/lib-chainStorage.js
  packages/zoe/README.md
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contracts/oracle.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
Labels: automerge:rebase
