Repository Agoric/agoric-sdk, pull requests merged in 2022-03, with the labels that each got.

#4696 Remove possible spurious loss of slotToVal entries on export retirement
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
Labels: bug, SwingSet

#4682 fix(swingset): add stub vat-upgrade calls (always fails)
  packages/SwingSet/src/devices/vat-admin/device-vat-admin.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/lib/id.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/snapshots/test-state.js.md
  packages/SwingSet/test/snapshots/test-state.js.snap
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
Labels: SwingSet, automerge:rebase

#4683 Enforce `home.board` prefixes
  packages/solo/test/test-home.js
  packages/vats/package.json
  packages/vats/src/lib-board.js
  packages/vats/test/test-lib-board.js
  packages/wallet/api/test/test-getPursesNotifier.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/wallet/ui/src/components/ImportContact.jsx
  packages/wallet/ui/src/components/ImportIssuer.jsx
  packages/wallet/ui/src/views/Contacts.jsx
  packages/wallet/ui/src/views/Issuers.jsx
  packages/wallet/ui/src/views/tests/Contacts.test.jsx
Labels: wallet, automerge:merge

#4702 chore: remove email notification on deployment-test failure
  .github/workflows/deployment-test.yml
Labels: tooling, automerge:merge

#4708 refactor kernel message-routing code
  packages/SwingSet/src/kernel/kernel.js
Labels: SwingSet, automerge:rebase

#4701 docs: add an attacker's guide for the AMM
  packages/run-protocol/src/vpool-xyk-amm/AttackersGuide.md
Labels: documentation, RUN-protocol, AMM, automerge:merge, restival

#4710 chore: Ignore vim swap files
  golang/cosmos/.gitignore
  packages/ERTP/.gitignore
  packages/SwingSet/.gitignore
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/agoric-cli/.gitignore
  packages/cosmic-swingset/.gitignore
  packages/deploy-script-support/.gitignore
  packages/wallet/api/.gitignore
Labels: hygiene, automerge:squash

#4715 refactor(run-protocol): store liquidation cohort before liquidating
  packages/run-protocol/src/vaultFactory/vaultManager.js
Labels: automerge:squash

#4612 Prometheus update for loadgen telemetry
  docs/env.md
  packages/agoric-cli/package.json
  packages/agoric-cli/src/start.js
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/README-telemetry.md
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/kernel-stats.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/solo/src/pipe-entrypoint.js
  packages/solo/src/pipe.js
  packages/solo/src/start.js
  packages/solo/src/web.js
  packages/swing-store/src/swingStore.js
  packages/telemetry/package.json
  packages/telemetry/src/flight-recorder.js
  packages/telemetry/src/index.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/src/shutdown.js
  yarn.lock
Labels: automerge:merge, telemetry

#4709 docs: an Attacker's Guide for VaultFactory
  packages/run-protocol/src/vaultFactory/AttackersGuide.md
Labels: documentation, security, Core Economy, RUN-protocol, automerge:squash

#4716 refactor(swingset): improve vat deliveries
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/devices/vat-admin/device-vat-admin.js
  packages/SwingSet/src/index.js
  packages/SwingSet/src/kernel/deviceManager.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/kernelSyscall.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/supervisors/nodeworker/supervisor-nodeworker.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-exported.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/zoe/src/contractFacet/zcfZygote.js
Labels: SwingSet, automerge:rebase

#4725 fix(swingset): deliver startVat to setup() vats
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/vats/comms/dispatch.js
  packages/SwingSet/src/vats/comms/remote.js
  packages/SwingSet/test/commsVatDriver.js
  packages/SwingSet/test/devices/bootstrap-2.js
  packages/SwingSet/test/devices/bootstrap-4.js
  packages/SwingSet/test/devices/test-devices.js
  packages/SwingSet/test/test-comms.js
  packages/SwingSet/test/test-controller.js
  packages/SwingSet/test/vat-syscall-failure.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
Labels: SwingSet, automerge:rebase

#4717 docs(swingset): Improve "delivery" documentation
  packages/SwingSet/docs/delivery.md
Labels: documentation, SwingSet, automerge:squash

#4684 test(zoe): switch to E(zoe).installBundleID()
  packages/zoe/test/swingsetTests/brokenContracts/bootstrap.js
  packages/zoe/test/swingsetTests/brokenContracts/test-crashingContract.js
  packages/zoe/test/swingsetTests/makeKind/bootstrap.js
  packages/zoe/test/swingsetTests/makeKind/test-makeKind.js
  packages/zoe/test/swingsetTests/offerArgs/bootstrap.js
  packages/zoe/test/swingsetTests/offerArgs/test-offerArgs.js
  packages/zoe/test/swingsetTests/privateArgs/bootstrap.js
  packages/zoe/test/swingsetTests/privateArgs/test-privateArgs.js
  packages/zoe/test/swingsetTests/runMint/bootstrap.js
  packages/zoe/test/swingsetTests/runMint/test-runMint.js
  packages/zoe/test/swingsetTests/zoe/bootstrap.js
  packages/zoe/test/swingsetTests/zoe/test-zoe.js
  packages/zoe/test/unitTests/contractSupport/test-depositTo.js
  packages/zoe/test/unitTests/contractSupport/test-offerTo.js
  packages/zoe/test/unitTests/contractSupport/test-withdrawFrom.js
  packages/zoe/test/unitTests/contracts/attestation/test-attestation.js
  packages/zoe/test/unitTests/contracts/loan/helpers.js
  packages/zoe/test/unitTests/contracts/loan/test-borrow.js
  packages/zoe/test/unitTests/contracts/loan/test-loan-e2e.js
  packages/zoe/test/unitTests/contracts/test-atomicSwap.js
  packages/zoe/test/unitTests/contracts/test-auction.js
  packages/zoe/test/unitTests/contracts/test-automaticRefund.js
  packages/zoe/test/unitTests/contracts/test-autoswap.js
  packages/zoe/test/unitTests/contracts/test-barter.js
  packages/zoe/test/unitTests/contracts/test-brokenContract.js
  packages/zoe/test/unitTests/contracts/test-callSpread.js
  packages/zoe/test/unitTests/contracts/test-coveredCall-want-pattern.js
  packages/zoe/test/unitTests/contracts/test-coveredCall.js
  packages/zoe/test/unitTests/contracts/test-escrowToVote.js
  packages/zoe/test/unitTests/contracts/test-mintPayments.js
  packages/zoe/test/unitTests/contracts/test-oracle.js
  packages/zoe/test/unitTests/contracts/test-otcDesk.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/contracts/test-priceAggregatorChainlink.js
  packages/zoe/test/unitTests/contracts/test-sellTickets.js
  packages/zoe/test/unitTests/contracts/test-simpleExchange.js
  packages/zoe/test/unitTests/contracts/test-throwInOfferHandler.js
  packages/zoe/test/unitTests/contracts/test-useObj.js
  packages/zoe/test/unitTests/installFromSource.js
  packages/zoe/test/unitTests/setupMixedMints.js
  packages/zoe/test/unitTests/setupNonFungibleMints.js
  packages/zoe/test/unitTests/test-makeKind.js
  packages/zoe/test/unitTests/test-scriptedOracle.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/setupZcfTest.js
  packages/zoe/test/unitTests/zcf/test-feeMintAccess.js
  packages/zoe/test/unitTests/zcf/test-zcfSeat-exit.js
  packages/zoe/test/unitTests/zcf/test-zcfSeat.js
Labels: Zoe, automerge:rebase

#4732 refactor(run-protocol): extract `chargeInterest` for use outside vaults
  packages/run-protocol/src/interest.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/test-interest.js
  packages/run-protocol/test/vaultFactory/swingsetTests/governance/snapshots/test-governance.js.md
  packages/run-protocol/test/vaultFactory/swingsetTests/governance/snapshots/test-governance.js.snap
  packages/run-protocol/test/vaultFactory/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/vaultFactory/swingsetTests/governance/vat-alice.js
  packages/run-protocol/test/vaultFactory/swingsetTests/vaultFactory/vat-alice.js
  packages/run-protocol/test/vaultFactory/test-vault.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/src/issuerRecord.js
Labels: automerge:squash

#4711 refactor(run-protocol)!: vaults hold liquidation proceeds until closed
  packages/run-protocol/src/interest-math.js
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/test/swingsetTests/governance/bootstrap.js
  packages/run-protocol/test/swingsetTests/governance/snapshots/test-governance.js.md
  packages/run-protocol/test/swingsetTests/governance/snapshots/test-governance.js.snap
  packages/run-protocol/test/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/swingsetTests/governance/vat-alice.js
  packages/run-protocol/test/swingsetTests/governance/vat-owner.js
  packages/run-protocol/test/swingsetTests/governance/vat-priceAuthority.js
  packages/run-protocol/test/swingsetTests/governance/vat-voter.js
  packages/run-protocol/test/swingsetTests/governance/vat-zoe.js
  packages/run-protocol/test/swingsetTests/mockAmm.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/swingsetTests/vaultFactory/bootstrap.js
  packages/run-protocol/test/swingsetTests/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/run-protocol/test/swingsetTests/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/run-protocol/test/swingsetTests/vaultFactory/test-vaultFactory.js
  packages/run-protocol/test/swingsetTests/vaultFactory/vat-alice.js
  packages/run-protocol/test/swingsetTests/vaultFactory/vat-owner.js
  packages/run-protocol/test/swingsetTests/vaultFactory/vat-priceAuthority.js
  packages/run-protocol/test/swingsetTests/vaultFactory/vat-zoe.js
  packages/run-protocol/test/test-interest-math.js
  packages/run-protocol/test/vaultFactory/test-vault-interest.js
  packages/run-protocol/test/vaultFactory/test-vault.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/types.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/otcDesk.js
Labels: automerge:merge

#4746 chore(vats): refine bootstrap logging for installations etc. in agoricNames
  packages/vats/src/core/utils.js
Labels: automerge:rebase

#4743 refactor(run-protocol): extract a vaultKit module
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultKit.js
  packages/run-protocol/test/vaultFactory/test-vault-interest.js
  packages/run-protocol/test/vaultFactory/test-vault.js
Labels: automerge:merge

#4611 Basic OpenTelemetry tracing support
  packages/solo/src/start.js
  packages/telemetry/bin/ingest-slog
  packages/telemetry/sample-otel-collector.yaml
  packages/telemetry/scripts/ingest.sh
  packages/telemetry/scripts/otelcol.sh
  packages/telemetry/src/all.js
  packages/telemetry/src/ingest-slog-entrypoint.js
  packages/telemetry/src/kv-string-store.js
  packages/telemetry/src/null.js
  packages/telemetry/src/otel-trace.js
  packages/telemetry/src/shutdown.js
  packages/telemetry/src/slog-to-otel.js
Labels: automerge:merge, telemetry

#4745 feat(vats): move BLD mint, issuer to its own vat (DRAFT)
  packages/run-protocol/scripts/build-bundles.js
  packages/run-protocol/src/importedBundles.js
  packages/run-protocol/src/mintHolder.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/types.js
  packages/vats/src/demoIssuers.js
  packages/vats/src/vat-bank.js
  packages/vats/test/test-clientBundle.js
  packages/vats/test/test-vat-bank.js
Labels: automerge:merge

#4753 fix: freeze globalThis in coreEval to enforce OCap discipline
  packages/vats/src/core/chain-behaviors.js
Labels: automerge:rebase

#4754 test(zoe): good error message if payment not wrapped with keywords
  packages/zoe/test/unitTests/test-zoe.js
Labels: automerge:rebase

#4659 test(store): Verify the properties of compareRank
  packages/store/test/test-rankOrder.js
Labels: test, automerge:squash

#4733 docs(cosmic-swingset): Clean up the readme
  packages/cosmic-swingset/README.md
  packages/cosmic-swingset/readme-assets/pixel-demo.png
  packages/cosmic-swingset/readme-assets/rplace.png
Labels: documentation, cosmic-swingset, hygiene, automerge:squash

#4756 chore: upgrade TypeScript to 4.6
  package.json
  packages/run-protocol/test/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/swingsetTests/vaultFactory/test-vaultFactory.js
  packages/ui-components/package.json
  yarn.lock
Labels: automerge:squash

#4744 build: remove PR check for conventional commits
  .github/workflows/pr-checks.yml
Labels: automerge:squash

#4757 chore: clean up threat model docs
  docs/threat_models/README.md
  docs/threat_models/gen.sh
  docs/threat_models/index.md
  docs/threat_models/pegasus/pegasus_component.png
  docs/threat_models/pegasus/pegasus_component.svg
  docs/threat_models/pegasus/pegasus_sequence.png
  docs/threat_models/pegasus/pegasus_sequence.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_component.png
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_component.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence.png
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_001.png
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_001.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_002.png
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_002.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_003.png
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_003.svg
  docs/threat_models/vaultFactory/VaultFactory.svg
  docs/threat_models/vaultFactory/vaultFactory.png
  docs/threat_models/vaultFactory/vaultFactory.puml
Labels: automerge:squash, threat modeling

#4760 feat(cosmos): clawback lien
  go.mod
  go.sum
  golang/cosmos/proto/agoric/lien/genesis.proto
  golang/cosmos/proto/agoric/lien/lien.proto
  golang/cosmos/x/lien/genesis.go
  golang/cosmos/x/lien/keeper/account.go
  golang/cosmos/x/lien/keeper/account_test.go
  golang/cosmos/x/lien/keeper/keeper.go
  golang/cosmos/x/lien/keeper/keeper_test.go
  golang/cosmos/x/lien/lien.go
  golang/cosmos/x/lien/lien_test.go
  golang/cosmos/x/lien/spec/01_concepts.md
  golang/cosmos/x/lien/types/accountkeeper.go
  golang/cosmos/x/lien/types/accountstate.go
  golang/cosmos/x/lien/types/expected_keepers.go
  golang/cosmos/x/lien/types/genesis.pb.go
  golang/cosmos/x/lien/types/lien.pb.go
Labels: enhancement, automerge:merge, proto:expect-breakage, agoric-cosmos, audit-restival

#4758 refactor: Relieve dependency on babel-standalone
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/agoric-cli/src/entrypoint.js
  packages/agoric-cli/test/test-main.js
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/eventual-send/package.json
  packages/governance/package.json
  packages/governance/test/swingsetTests/committeeBinary/test-committee.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/run-protocol/package.json
  packages/run-protocol/test/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/swingsetTests/vaultFactory/test-vaultFactory.js
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/swingset-runner/src/runner-debug-entrypoint.js
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/vats/src/vat-network.js
  packages/vats/test/test-boot.js
  packages/wallet/api/package.json
  packages/wallet/ui/package.json
  packages/web-components/package.json
  packages/xsnap/package.json
  packages/xsnap/src/ava-xs.js
  packages/xsnap/src/avaHandler.js
  packages/xsnap/src/avaXS.js
  packages/zoe/package.json
  packages/zoe/test/swingsetTests/brokenContracts/test-crashingContract.js
  packages/zoe/test/swingsetTests/makeKind/test-makeKind.js
  packages/zoe/test/swingsetTests/offerArgs/test-offerArgs.js
  packages/zoe/test/swingsetTests/privateArgs/test-privateArgs.js
  packages/zoe/test/swingsetTests/runMint/test-runMint.js
  packages/zoe/test/swingsetTests/zoe/test-zoe.js
  yarn.lock
Labels: automerge:merge

#4781 chore: update linting deps
  package.json
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/vat-warehouse/bootstrap.js
  packages/SwingSet/test/virtualObjects/vat-vom-gc-bootstrap.js
  packages/eslint-config/package.json
  packages/swingset-runner/demo/vatStore3/bootstrap.js
  packages/ui-components/package.json
  packages/wallet/ui/package.json
  packages/web-components/package.json
  yarn.lock
Labels: automerge:squash

#4765 docs(run-protocol): Improve constant product example arithmetic
  packages/run-protocol/src/vpool-xyk-amm/constantProduct/README.md
Labels: documentation, RUN-protocol, automerge:squash

#4803 docs(cosmic-swingset): document bridge interaction
  packages/cosmic-swingset/README-bridge.md
Labels: automerge:rebase

#4751 feat(swingset-vat): Integrate Endo checkBundle
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/lib-nodejs/validate-archive.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/bundles/test-bundles-controller.js
  packages/SwingSet/test/bundles/test-bundles-kernel.js
  packages/SwingSet/test/bundles/test-bundles.js
  yarn.lock
Labels: automerge:merge

#4789 build: 'module' type for root package
  golang/cosmos/package.json
  golang/cosmos/src/index.cjs
  package.json
  packages/ui-components/test/components/test-NatAmountInput.js
  scripts/check-mismatched-dependencies.cjs
Labels: automerge:squash

#4418 feat: script to configure .vscode
  scripts/configure-vscode.sh
Labels: tooling, automerge:squash

#4826 chore: Document configure-vscode.sh and update it to run from anywhere
  CONTRIBUTING.md
  scripts/configure-vscode.sh
Labels: documentation, hygiene, automerge:squash

#4827 docs(swingset): Improve SwingSet networking documentation
  packages/SwingSet/docs/networking.md
Labels: documentation, SwingSet, hygiene, automerge:squash

#4812 refactor(run-protocol): simplify centralSupply.js contract
  packages/run-protocol/src/centralSupply.js
Labels: automerge:squash

#4787 move vatParameters to startVat() delivery
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-node.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/lib/message.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/supervisors/nodeworker/supervisor-nodeworker.js
  packages/SwingSet/src/supervisors/subprocess-node/supervisor-subprocess-node.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/comms/dispatch.js
  packages/SwingSet/src/vats/comms/state.js
  packages/SwingSet/test/devices/test-devices.js
  packages/SwingSet/test/liveslots-helpers.js
  packages/SwingSet/test/test-comms.js
  packages/SwingSet/test/test-controller.js
  packages/SwingSet/test/test-gc-kernel.js
  packages/SwingSet/test/test-kernel.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/util.js
Labels: SwingSet, automerge:rebase

#4825 chore: configure VSCode to autofix eslint
  scripts/configure-vscode.sh
Labels: automerge:squash

#4768 fix(SwingSet): remove `consensusMode` flip-flop
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-node.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/supervisors/nodeworker/supervisor-nodeworker.js
  packages/SwingSet/src/supervisors/subprocess-node/supervisor-subprocess-node.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js
  packages/SwingSet/src/types-external.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
Labels: SwingSet, xsnap, automerge:merge

#4840 chore(ci): add golangci-lint to workflows
  .github/workflows/golangci-lint.yml
Labels: security, automerge:rebase

#4841 fix(cosmosswingset): check negativity before castnig to uint
  golang/cosmos/x/swingset/types/types.go
Labels: security, automerge:rebase

#4843 chore(golang): fix lint errors
  golang/cosmos/app/app.go
  golang/cosmos/daemon/cmd/testnet.go
  golang/cosmos/vm/controller.go
  golang/cosmos/x/lien/keeper/keeper_test.go
  golang/cosmos/x/swingset/handler.go
  golang/cosmos/x/swingset/module.go
  golang/cosmos/x/vbank/keeper/keeper.go
  golang/cosmos/x/vbank/module.go
  golang/cosmos/x/vbank/vbank_test.go
  golang/cosmos/x/vibc/module.go
Labels: automerge:rebase

#4846 chore(golang): fix lint errors and enable lint errors
  .github/workflows/golangci-lint.yml
  golang/cosmos/x/swingset/types/types.go
  golang/cosmos/x/vbank/module.go
Labels: automerge:rebase

#4857 chore: bump ts eslint to 5.15
  package.json
  packages/eslint-config/package.json
  packages/ui-components/package.json
  yarn.lock
Labels: automerge:squash

#4858 refactor: seat.decrementBy() before incrementBy
  packages/run-protocol/src/vpool-xyk-amm/addLiquidity.js
  packages/run-protocol/src/vpool-xyk-amm/doublePool.js
  packages/run-protocol/src/vpool-xyk-amm/singlePool.js
Labels: hygiene, Zoe Contract, AMM, automerge:merge

#4742 Implement multifaceted virtual objects
  packages/SwingSet/docs/virtual-objects.md
  packages/SwingSet/src/lib/parseVatSlots.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectCache.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bob.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bootstrap.js
Labels: enhancement, SwingSet, automerge:rebase

#4824 Implement durable kind API
  packages/ERTP/globals.d.ts
  packages/SwingSet/docs/virtual-objects.md
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/storeModule.js
  packages/SwingSet/test/stores/test-durabilityChecks.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
  packages/SwingSet/tools/fakeVirtualObjectManager.js
  packages/SwingSet/tools/prepare-test-env.js
  packages/deploy-script-support/globals.d.ts
  packages/pegasus/globals.d.ts
  packages/run-protocol/globals.d.ts
  packages/vats/globals.d.ts
  packages/xsnap/src/globals.d.ts
  packages/zoe/test/minimalMakeKindContract.js
  packages/zoe/test/unitTests/test-makeKind.js
  packages/zoe/test/unitTests/test-zoe-env.js
Labels: enhancement, SwingSet, automerge:rebase

#4839 fix(swingset): startVat(vatParameters) are now capdata
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/lib/message.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/comms/dispatch.js
  packages/SwingSet/test/commsVatDriver.js
  packages/SwingSet/test/liveslots-helpers.js
  packages/SwingSet/test/test-comms.js
  packages/SwingSet/test/test-controller.js
  packages/SwingSet/test/test-kernel.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/test-xsnap-errors.js
  packages/SwingSet/test/vat-util.js
Labels: SwingSet

#4831 refactor(governance): statically typed param manager
  packages/ERTP/src/payment.js
  packages/ERTP/src/types.js
  packages/governance/README.md
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/committee.js
  packages/governance/src/constants.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractHelper.js
  packages/governance/src/index.js
  packages/governance/src/noActionElectorate.js
  packages/governance/src/paramGovernance/paramMakers.js
  packages/governance/src/paramGovernance/paramManager.js
  packages/governance/src/paramGovernance/typedParamManager.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/governedContract.js
  packages/governance/test/unitTests/test-buildParamManager.js
  packages/governance/test/unitTests/test-paramChangePositions.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/pegasus/src/pegasus.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/params.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/swingsetTests/governance/vat-alice.js
  packages/run-protocol/test/swingsetTests/vaultFactory/vat-alice.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/vats/src/core/types.js
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contracts/atomicSwap.js
  packages/zoe/src/contracts/automaticRefund.js
  packages/zoe/src/contracts/autoswap.js
  packages/zoe/src/contracts/barterExchange.js
  packages/zoe/src/contracts/callSpread/payoffHandler.js
  packages/zoe/src/contracts/callSpread/pricedCallSpread.js
  packages/zoe/src/contracts/callSpread/types.js
  packages/zoe/src/contracts/coveredCall.js
  packages/zoe/src/contracts/mintPayments.js
  packages/zoe/src/contracts/otcDesk.js
  packages/zoe/src/contracts/sellItems.js
  packages/zoe/src/contracts/simpleExchange.js
  packages/zoe/src/contracts/types.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/types.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/test/privateArgsUsageContract.js
  packages/zoe/test/swingsetTests/brokenContracts/crashingAutoRefund.js
  packages/zoe/test/unitTests/contracts/escrowToVote.js
  packages/zoe/test/unitTests/contracts/throwInOfferHandler.js
  packages/zoe/test/unitTests/zcf/registerFeeMintContract.js
  packages/zoe/test/unitTests/zcf/zcfTesterContract.js
Labels: automerge:squash

#4641 feat(cosmic-swingset): grant addVaultType based on addr
  packages/cosmic-swingset/src/chain-main.js
  packages/run-protocol/src/econ-behaviors.js
  packages/vats/decentral-loadgen-config.json
  packages/vats/src/core/manifest.js
Labels: automerge:squash

#4865 feat(swingset): add "device hooks"
  packages/SwingSet/docs/devices.md
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/kernel/deviceManager.js
  packages/SwingSet/src/kernel/deviceTranslator.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/kernelSyscall.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/device-hooks/bootstrap-device-hook.js
  packages/SwingSet/test/device-hooks/device-use-hook.js
  packages/SwingSet/test/device-hooks/test-device-hooks.js
  packages/SwingSet/test/devices/bootstrap-raw.js
  packages/SwingSet/test/devices/device-raw-0.js
  packages/SwingSet/test/devices/test-raw-device.js
  packages/SwingSet/test/util.js
Labels: SwingSet, automerge:rebase

#4876 fix(wallet-api): don't drop unused invitations on the floor
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-lib-wallet.js
Labels: wallet, automerge:merge

#4874 Implement and display zoe offer arguments in the wallet
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/wallet/ui/src/components/Offer.jsx
  packages/wallet/ui/src/components/tests/Offer.test.jsx
Labels: wallet, automerge:merge

#4871 fix: typo
  packages/ERTP/src/types.js
Labels: automerge:squash

#4873 Implement baggage
  packages/SwingSet/src/lib/djson.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/SwingSet/test/gc/test-gc-vat.js
  packages/SwingSet/test/liveslots-helpers.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/test-gc-kernel.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/test-vpid-liveslots.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/workers/test-worker.js
  packages/vats/src/core/boot.js
  packages/vats/test/test-boot.js
  packages/zoe/src/contractFacet/vatRoot.js
  packages/zoe/tools/fakeVatAdmin.js
Labels: enhancement, SwingSet, automerge:rebase

#4872 feat(swingset): allow object refs in create/upgrade/terminate vat
  packages/SwingSet/src/devices/vat-admin/device-vat-admin.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-admin-hooks.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-admin/bootstrap.js
  packages/SwingSet/test/vat-admin/new-vat-13.js
  packages/SwingSet/test/vat-admin/new-vat-44.js
  packages/SwingSet/test/vat-admin/new-vat-refcount.js
  packages/SwingSet/test/vat-admin/terminate/bootstrap-terminate-with-presence.js
  packages/SwingSet/test/vat-admin/terminate/swingset-terminate-with-presence.json
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/vat-admin/test-create-vat.js
  packages/SwingSet/test/vat-admin/vat-export-held.js
Labels: SwingSet, automerge:rebase

#4470 fix: Encode Passables, not just keys
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/test/stores/test-durabilityChecks.js
  packages/run-protocol/src/vaultFactory/storeUtils.js
  packages/store/src/index.js
  packages/store/src/patterns/encodePassable.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
  packages/store/test/test-encodePassable.js
Labels: automerge:squash

#4618 fix: virtualize payments, purses, ledger
  packages/ERTP/package.json
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/test/unitTests/test-issuerObj.js
  packages/SwingSet/src/storeModule.js
  packages/governance/test/unitTests/test-buildParamManager.js
  packages/governance/test/unitTests/test-typedParamManager.js
Labels: automerge:squash

#4896 fix: renamings #4470 missed
  packages/run-protocol/src/vaultFactory/storeUtils.js
  packages/store/src/patterns/encodePassable.js
Labels: automerge:squash

#4603 refactor(swingset-vat): move VatData to new vat-data package
  .github/workflows/test-all-packages.yml
  packages/ERTP/globals.d.ts
  packages/ERTP/package.json
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/SwingSet/docs/virtual-objects.md
  packages/SwingSet/package.json
  packages/SwingSet/src/storeModule.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bob.js
  packages/SwingSet/test/virtualObjects/vat-representative-bootstrap.js
  packages/SwingSet/test/virtualObjects/vat-vom-gc-bob.js
  packages/SwingSet/test/virtualObjects/vat-weakcollections-alice.js
  packages/SwingSet/tools/prepare-test-env-ava.js
  packages/agoric-cli/src/sdk-package-names.js
  packages/deploy-script-support/globals.d.ts
  packages/pegasus/globals.d.ts
  packages/run-protocol/globals.d.ts
  packages/run-protocol/package.json
  packages/run-protocol/src/vaultFactory/orderedVaultStore.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/swingset-runner/demo/vatStore1/vat-bob.js
  packages/swingset-runner/demo/vatStore2/thingHolder.js
  packages/swingset-runner/demo/vatStore3/vat-bob.js
  packages/swingset-runner/demo/virtualObjectGC/vat-bob.js
  packages/swingset-runner/package.json
  packages/vat-data/package.json
  packages/vat-data/src/index.js
  packages/vat-data/src/index.test-d.ts
  packages/vat-data/src/types.d.ts
  packages/vat-data/test/absent.test.js
  packages/vat-data/test/present.test.js
  packages/vat-data/tsconfig.json
  packages/vats/globals.d.ts
  packages/xsnap/src/globals.d.ts
  packages/zoe/package.json
  packages/zoe/src/contractFacet/evalContractCode.js
  packages/zoe/test/unitTests/test-makeKind.js
  packages/zoe/test/unitTests/test-zoe-env.js
  packages/zoe/tools/prepare-test-env-ava.js
Labels: automerge:squash

#4898 Allocate ID numbers from counters that are kept in persistent storage
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/test/liveslots-helpers.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/test-marshal.js
  packages/SwingSet/test/test-vpid-liveslots.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/tools/fakeCollectionManager.js
  packages/SwingSet/tools/fakeVirtualSupport.js
Labels: bug, SwingSet, automerge:rebase

#4890 ci: Re-enable loadgen integration test
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
  packages/deployment/scripts/integration-test.sh
  packages/deployment/src/main.js
Labels: automerge:rebase

#4902 feat(docker): publish more than one architecture
  .github/workflows/docker.yml
Labels: automerge:merge

#4913 refactor(run-protocol): innerVault as virtual object
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
Labels: automerge:squash

#4919 Endow a `lookup(...path)` function to REPL and deploy scripts
  packages/agoric-cli/src/deploy.js
  packages/solo/src/vat-http.js
  packages/vats/src/lib-board.js
  packages/vats/src/types.js
  packages/vats/test/test-lib-board.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/wallet.js
  packages/wallet/api/test/test-lib-wallet.js
Labels: agoric-cli, wallet, solo, automerge:merge

#4920 test(xsnap): XS round-trips surrogate pairs
  packages/xsnap/test/test-xs-js.js
Labels: automerge:rebase

#4869 feat!: add the ability to invoke an API to contract governance
  packages/governance/README.md
  packages/governance/docs/contractGovernance.png
  packages/governance/docs/contractGovernance.puml
  packages/governance/index.md
  packages/governance/package.json
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/contractGovernance/assertions.js
  packages/governance/src/contractGovernance/governApi.js
  packages/governance/src/contractGovernance/governParam.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractHelper.js
  packages/governance/src/index.js
  packages/governance/src/question.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/committeeBinary/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/governedContract.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/governance/test/unitTests/test-ballotBuilder.js
  packages/governance/test/unitTests/test-ballotCount.js
  packages/governance/test/unitTests/test-committee.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/test/unitTests/zcf/setupZcfTest.js
Labels: enhancement, Core Economy, Governance, automerge:squash

#4923 fix(docker): increase network timeout
  packages/deployment/Dockerfile.sdk
Labels: automerge:merge

#4922 docs: document how virtual/durable objects/collections use vatstore
  packages/SwingSet/src/liveslots/vatstore-usage.md
Labels: SwingSet

#4937 docs(swingset): apply vatstore-usage.md feedback
  packages/SwingSet/src/liveslots/vatstore-usage.md
Labels: SwingSet

#4926 fix: liveslots: initialize counters in startVat, not on-demand
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
Labels: SwingSet

#4924 fix(swingset): initializeStoreKindInfo() earlier, unconditionally
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
  packages/SwingSet/tools/fakeCollectionManager.js
Labels: SwingSet

#4927 feat(swingset): get a small upgrade to work
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/test/upgrade/test-upgrade.js
Labels: SwingSet

#4933 fix(swingset): stopVat rejects lingering promises
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
Labels: SwingSet, automerge:merge

#4891 Updates for oracle bootstrap
  packages/ERTP/src/types.js
  packages/agoric-cli/src/chain-config.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/src/demoIssuers.js
  packages/wallet/api/src/wallet.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/tools/types.js
Labels: automerge:merge, oracle

#4886 fix(run-protocol): restructure vault notifiers to work with wallet
  packages/run-protocol/src/vaultFactory/vaultKit.js
  packages/run-protocol/test/swingsetTests/governance/vat-alice.js
  packages/run-protocol/test/swingsetTests/vaultFactory/vat-alice.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/run-protocol/test/vaultFactory/vault-contract-wrapper.js
Labels: automerge:squash, automerge:rebase

#4635 feat!: add collateral Reserve to hold collateral and add to AMM under governance control
  packages/run-protocol/scripts/build-bundles.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/importedBundles.js
  packages/run-protocol/src/reserve/collateralReserve.js
  packages/run-protocol/src/reserve/params.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/reserve/setup.js
  packages/run-protocol/test/reserve/test-reserve.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
Labels: documentation, enhancement, Core Economy, RUN-protocol, Governance, AMM, automerge:squash, restival

#4904 fix(deployment): correct quoting in `faucet-helper.sh`
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
Labels: deployment, automerge:merge

#4942 chore(swingset): improve virtual-object code and tests
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
Labels: SwingSet, automerge:rebase

#4868 refactor(governance): less boilerplate in param handling
  packages/governance/README.md
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractHelper.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/contractGovernor/governedContract.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/run-protocol/src/reserve/collateralReserve.js
  packages/run-protocol/src/reserve/params.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/params.js
Labels: automerge:squash

#4943 fix(bots): add slack to notify bot
  .github/actions/notify-status/action.yml
Labels: automerge:merge

#4947 fix: reenable master CI notifier
  .github/actions/notify-status/action.yml
  .github/workflows/deployment-test.yml
  .github/workflows/docker.yml
Labels: tooling, automerge:merge

#4946 chore: drop an extraneous reference to `main`.
  packages/governance/src/contractGovernor.js
  packages/run-protocol/src/psm/psm.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/run-protocol/test/psm/test-psm.js
Labels: hygiene, Governance, automerge:squash

#4889 feat(wallet): support reading notifiers from offer result
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/continuingInvitationExample.js
  packages/wallet/api/test/test-lib-wallet.js
Labels: automerge:squash, automerge:rebase

#4741 feat(run-protocol): RUNstake contract only, without payoff from rewards
  packages/run-protocol/exported.js
  packages/run-protocol/scripts/build-bundles.js
  packages/run-protocol/src/collect.js
  packages/run-protocol/src/contractSupport.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/importedBundles.js
  packages/run-protocol/src/runStake/README.md
  packages/run-protocol/src/runStake/attestation.js
  packages/run-protocol/src/runStake/params.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/runStake/runStakeKit.js
  packages/run-protocol/src/runStake/runStakeManager.js
  packages/run-protocol/src/runStake/types.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/test/attestation/exampleLoanUsage.js
  packages/run-protocol/test/attestation/test-attestation.js
  packages/run-protocol/test/attestation/test-userFlow.js
  packages/run-protocol/test/runStake/attestationFaker.js
  packages/run-protocol/test/runStake/runStake-test-steps.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/zoe/scripts/build-zcfBundle.js
  packages/zoe/src/contractSupport/types.js
  packages/zoe/src/contracts/attestation/attMaker.js
  packages/zoe/src/contracts/attestation/attestation.js
  packages/zoe/src/contracts/attestation/helpers.js
  packages/zoe/src/contracts/attestation/prerequisites.js
  packages/zoe/src/contracts/attestation/returnable/returnableHelpers.js
  packages/zoe/src/contracts/attestation/returnable/returnableNFT.js
  packages/zoe/src/contracts/attestation/storedTime.js
  packages/zoe/src/contracts/attestation/types.js
  packages/zoe/src/contracts/exported.js
  packages/zoe/test/unitTests/contracts/attestation/test-attestation.js
Labels: automerge:squash

#4952 Eliminate the propertyNames Set
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
Labels: enhancement, SwingSet, automerge:rebase

#4958 chore(swingset): force GC on some intermittently-failing tests
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
Labels: SwingSet

#4956 feat(swingset-runner): add option to dump out the activityhash after each crank
  packages/swingset-runner/src/main.js
Labels: automerge:rebase

#4950 refactor(run-protocol): throw in getParamMgrRetriever.get for unsupported paramDesc
  packages/run-protocol/src/vaultFactory/vaultFactory.js
Labels: automerge:squash

#4965 Disowning some of my codeowner-ship
  .github/CODEOWNERS
Labels: automerge:merge

#4948 feat(run-protocol): debtLimit governed param
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/vats/src/demoIssuers.js
Labels: automerge:squash

#4966 chore: correct the root level pattern
  .github/CODEOWNERS
Labels: automerge:squash

#4970 ci(mergify): ensure that all the required checks pass
  .mergify.yml
Labels: tooling, automerge:merge

#4973 fix(dockerfile): add terrible retry logic for yarn install on failure
  packages/deployment/Dockerfile.sdk
Labels: automerge:rebase

#4961 chore(swingset): force GC on more intermittently-failing tests
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
Labels: SwingSet, automerge:rebase

#4979 fix liveslots double-retire bug by using a Set for importsToDrop/Retire
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/test/virtualObjects/double-retire-import/bootstrap-dri.js
  packages/SwingSet/test/virtualObjects/double-retire-import/test-double-retire-import.js
  packages/SwingSet/test/virtualObjects/double-retire-import/vat-dri.js
Labels: SwingSet, automerge:rebase

#4944 fix(swingset): initializeKindHandleKind early enough to support durables
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/gc/test-gc-vat.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/test-gc-kernel.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/test-vpid-liveslots.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
  packages/SwingSet/tools/fakeVirtualObjectManager.js
  packages/SwingSet/tools/fakeVirtualSupport.js
Labels: SwingSet, automerge:rebase

#4957 feat(swingset): add syscall.abandonExports
  packages/SwingSet/docs/garbage-collection.md
  packages/SwingSet/src/kernel/kernelSyscall.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/lib/message.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/test-abandon-export.js
  packages/SwingSet/test/util.js
Labels: SwingSet, automerge:rebase

#4959 test(swingset): test that baggage and durables survive vat upgrade
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
Labels: SwingSet, automerge:rebase

#4976 feat(swingset-runner): folloup to also include step mode in activityhash output
  packages/swingset-runner/src/main.js
Labels: automerge:rebase

#4945 chore(swingset): update vatstore-usage docs with new example IDs
  packages/SwingSet/src/liveslots/vatstore-usage.md
Labels: SwingSet, automerge:rebase

#4971 feat(run-protocol): debt limit for RUNstake
  packages/governance/src/contractHelper.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/runStake/params.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/runStake/runStakeManager.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: automerge:merge

#4984 ci(mergify): fix mergify branch pattern
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/deployment-test.yml
  .github/workflows/docker.yml
  .github/workflows/golangci-lint.yml
Labels: automerge:squash

#4960 fix: check that all durable kinds are reconnected in new version
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
Labels: SwingSet, automerge:rebase

#4988 ci(mergify): The queue name is main
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/deployment-test.yml
  .github/workflows/golangci-lint.yml
Labels: automerge:squash
