Repository Agoric/agoric-sdk, pull requests merged in 2022-10, with the labels that each got.

#6349 fix: avoid __proto__ accessor
  packages/SwingSet/test/virtualObjects/vat-orphan-bob.js
Labels: automerge:squash

#6370 fix: protect zoe from keyword collision
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
  packages/zoe/src/contractSupport/zoeHelpers.js
Labels: automerge:squash

#6362 5833 add getFinalAllocation
  packages/zoe/src/contractSupport/types.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: Zoe, automerge:squash

#6367 chore(web-components): use wallet site for locator url
  packages/web-components/src/AgoricWalletConnection.js
Labels: automerge:squash, automerge:rebase, bypass:integration

#6377 Slog sender improvements
  packages/cosmic-swingset/src/chain-main.js
  packages/telemetry/src/make-slog-sender.js
Labels: automerge:rebase

#6351 fix: vbank updates for new zero balance
  golang/cosmos/x/vbank/module.go
  golang/cosmos/x/vbank/vbank.go
  golang/cosmos/x/vbank/vbank_test.go
Labels: bug, cosmic-swingset, automerge:merge, MUST-HAVE

#6380 fix(wallet-ui): parse purse.brand in fetchCurrent
  packages/wallet/ui/src/util/WalletBackendAdapter.js
Labels: automerge:rebase, bypass:integration

#6383 wallet ui misc
  packages/agoric-cli/package.json
  packages/casting/package.json
  packages/wallet/ui/package.json
  packages/wallet/ui/src/index.jsx
  packages/wallet/ui/src/util/SuggestChain.js
  packages/wallet/ui/src/util/chainInfo.js
  yarn.lock
Labels: automerge:merge, bypass:integration

#6385 Revert "feat: show git sha of build source"
  packages/wallet/ui/package.json
  packages/wallet/ui/src/index.jsx
  yarn.lock
Labels: automerge:merge, bypass:integration

#6386 Merge release-pismo into trunk
  golang/cosmos/x/vbank/module.go
  golang/cosmos/x/vbank/vbank.go
  golang/cosmos/x/vbank/vbank_test.go
Labels: automerge:merge, force:integration

#6247 Telemetry enhancement
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernel.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/swingset-runner/package.json
  packages/swingset-runner/src/main.js
  packages/swingset-runner/src/slogulator.js
  packages/telemetry/src/frcat-entrypoint.js
  packages/telemetry/src/ingest-slog-entrypoint.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/src/slog-to-otel.js
Labels: enhancement, SwingSet, cosmic-swingset, swingset-runner, performance, hygiene, automerge:rebase, telemetry

#6388 fix: swingset amino codec / Ledger support
  golang/cosmos/x/swingset/alias.go
  golang/cosmos/x/swingset/types/codec.go
  golang/cosmos/x/swingset/types/msgs.go
  packages/agoric-cli/src/start.js
  packages/cosmic-swingset/Makefile
  packages/wallet/ui/public/network-config
  packages/wallet/ui/src/util/keyManagement.js
Labels: automerge:rebase

#6397 fix(provisionPool): update metrics on trades
  packages/vats/src/provisionPool.js
  packages/vats/test/test-provisionPool.js
Labels: automerge:rebase

#6381 feat: limit inbound queue
  golang/cosmos/ante/ante.go
  golang/cosmos/ante/expected_keepers.go
  golang/cosmos/ante/inbound.go
  golang/cosmos/app/app.go
  golang/cosmos/proto/agoric/swingset/genesis.proto
  golang/cosmos/proto/agoric/swingset/swingset.proto
  golang/cosmos/x/swingset/abci.go
  golang/cosmos/x/swingset/genesis.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/types/default-params.go
  golang/cosmos/x/swingset/types/genesis.pb.go
  golang/cosmos/x/swingset/types/params.go
  golang/cosmos/x/swingset/types/swingset.pb.go
  golang/cosmos/x/swingset/types/types.go
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/params.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/cosmic-swingset/src/sim-params.js
Labels: automerge:rebase

#6390 fix(ci): handle breaking change in skip duplicate action
  .github/workflows/pre-check-integration.yml
Labels: automerge:squash

#6395 feat(wallet-ui): require 100IST in pool to provision smart wallet
  packages/wallet/ui/src/components/ProvisionDialog.jsx
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
Labels: automerge:squash, automerge:rebase, bypass:integration

#6405 chore(wallet-ui): update token icons
  packages/wallet/ui/public/tokens/BLD.svg
  packages/wallet/ui/public/tokens/IST.png
  packages/wallet/ui/public/tokens/RUN.svg
  packages/wallet/ui/public/tokens/default.png
  packages/wallet/ui/public/tokens/generic.ico
  packages/wallet/ui/src/components/BrandIcon.jsx
  packages/wallet/ui/src/components/Proposal.jsx
  packages/wallet/ui/src/components/PurseAmount.jsx
  packages/wallet/ui/src/components/Purses.scss
  packages/wallet/ui/src/logo.svg
  packages/wallet/ui/src/util/Icons.js
  packages/wallet/ui/src/views/Issuers.jsx
Labels: automerge:rebase, bypass:integration

#6398 simplify Wallet UI network chooser
  packages/wallet/ui/src/components/AppBar.jsx
  packages/wallet/ui/src/components/ConnectionSettingsDialog.jsx
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/contexts/Application.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/util/connections.js
Labels: automerge:merge, bypass:integration

#6407 Wallet fixes
  packages/wallet/ui/src/components/ConnectionSettingsDialog.jsx
  packages/wallet/ui/src/service/Offers.js
  packages/wallet/ui/src/service/ScopedBridge.js
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/util/connections.js
Labels: automerge:rebase, bypass:integration

#6415 fix(wallet/ui): signing offers (PSM trades) with Ledger
  packages/wallet/ui/src/tests/keyManagement.test.js
  packages/wallet/ui/src/util/keyManagement.js
Labels: automerge:rebase, bypass:integration

#6412 docs(swingset): remove stale badges from README
  packages/SwingSet/README.md
Labels: SwingSet, automerge:rebase

#6418 chore(wallet-ui): disable exit offer button
  packages/wallet/ui/src/components/Offer.jsx
  packages/wallet/ui/src/components/tests/Offer.test.jsx
Labels: automerge:rebase, bypass:integration

#6421 fix: implement upgrade handler
  golang/cosmos/app/app.go
  packages/vats/decentral-prod-config.json
Labels: automerge:rebase

#6427 feat(wallet/ui): show JSON in keplr signer even without Ledger
  packages/wallet/ui/src/util/keyManagement.js
Labels: automerge:rebase, bypass:integration, want-in-pismo

#6426 fix: strike "Initial" from Economic Committee
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/governance/README.md
  packages/inter-protocol/README.md
  packages/inter-protocol/src/proposals/startEconCommittee.js
Labels: automerge:rebase, want-in-pismo

#6422 fixes to Economic Governance abilities
  packages/agoric-cli/src/lib/rpc.js
  packages/governance/docs/contractGovernance.png
  packages/governance/docs/contractGovernance.puml
  packages/governance/package.json
  packages/governance/src/contractGovernor.js
  packages/governance/src/types.js
  packages/inter-protocol/Makefile
  packages/inter-protocol/test/psm/gov-replace-committee.js
  packages/inter-protocol/test/psm/gov-replace-committee.md
  packages/inter-protocol/test/psm/test-governedPsm.js
  packages/inter-protocol/test/psm/wildcard-permit.json
  packages/inter-protocol/test/test-gov-collateral.js
Labels: automerge:rebase, want-in-pismo

#6428 chore(release): publish @agoric/sdk@28
  golang/cosmos/CHANGELOG.md
  golang/cosmos/package.json
  packages/ERTP/CHANGELOG.md
  packages/ERTP/package.json
  packages/SwingSet/CHANGELOG.md
  packages/SwingSet/package.json
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/cache/CHANGELOG.md
  packages/cache/package.json
  packages/casting/CHANGELOG.md
  packages/casting/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/CHANGELOG.md
  packages/deploy-script-support/package.json
  packages/governance/CHANGELOG.md
  packages/governance/package.json
  packages/import-manager/CHANGELOG.md
  packages/import-manager/package.json
  packages/inter-protocol/CHANGELOG.md
  packages/inter-protocol/package.json
  packages/pegasus/CHANGELOG.md
  packages/pegasus/package.json
  packages/sharing-service/CHANGELOG.md
  packages/sharing-service/package.json
  packages/smart-wallet/CHANGELOG.md
  packages/smart-wallet/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
  packages/spawner/CHANGELOG.md
  packages/spawner/package.json
  packages/store/CHANGELOG.md
  packages/store/package.json
  packages/swingset-runner/CHANGELOG.md
  packages/swingset-runner/package.json
  packages/ui-components/CHANGELOG.md
  packages/ui-components/package.json
  packages/vat-data/CHANGELOG.md
  packages/vat-data/package.json
  packages/vats/CHANGELOG.md
  packages/vats/package.json
  packages/wallet-connection/CHANGELOG.md
  packages/wallet-connection/package.json
  packages/wallet/CHANGELOG.md
  packages/wallet/api/CHANGELOG.md
  packages/wallet/api/package.json
  packages/wallet/package.json
  packages/wallet/ui/CHANGELOG.md
  packages/wallet/ui/package.json
  packages/web-components/CHANGELOG.md
  packages/web-components/package.json
  packages/zoe/CHANGELOG.md
  packages/zoe/package.json
Labels: tooling, automerge:merge

#6435 fix: allow test flag for update
  golang/cosmos/app/app.go
  golang/cosmos/app/const.go
  packages/vats/decentral-main-psm-config.json
  packages/vats/decentral-test-psm-config.json
Labels: automerge:rebase

#6439 chore(wallet-ui): rename signal wallet button
  packages/wallet/ui/src/bridge.jsx
Labels: automerge:rebase, bypass:integration

#6442 fix(swingset): only preload maxVatsOnline/2 vats
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/test/vat-warehouse/test-preload.js
  packages/SwingSet/test/vat-warehouse/test-warehouse.js
  packages/SwingSet/test/vat-warehouse/vat-preload-bootstrap.js
  packages/SwingSet/test/vat-warehouse/vat-preload-extra.js
Labels: SwingSet, automerge:merge, force:integration, want-in-pismo

#6446 Wallet logos
  packages/ui-components/src/display/natValue/stringifyNat.js
  packages/ui-components/test/display/natValue/test-stringifyNat.js
  packages/wallet/ui/public/tokens/USDC_axl.png
  packages/wallet/ui/public/tokens/USDC_grv.webp
  packages/wallet/ui/public/tokens/USDT_axl.png
  packages/wallet/ui/public/tokens/USDT_grv.webp
  packages/wallet/ui/src/util/Icons.js
Labels: automerge:rebase, bypass:integration

#6437 feat: main, test config: anchor IBC denoms, encon committee addresses
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-main-psm-config.json
  packages/vats/decentral-psm-config.json
  packages/vats/decentral-test-psm-config.json
Labels: automerge:rebase

#6441 fix: upgradehandler agoric-upgrade-8 init in the right order
  golang/cosmos/app/app.go
  golang/cosmos/app/const.go
  golang/cosmos/x/swingset/types/default-params.go
  golang/cosmos/x/swingset/types/params.go
Labels: automerge:rebase

#6452 feat(web-components): add 'makeAgoricKeplrConnection' util
  packages/wallet/ui/src/util/onLoad.js
  packages/web-components/index.js
  packages/web-components/src/keplr-connection/KeplrConnection.js
  packages/web-components/src/keplr-connection/errors.js
  packages/web-components/src/keplr-connection/fetchCurrent.js
  packages/web-components/src/keplr-connection/followLatest.js
  packages/web-components/src/keplr-connection/getChainId.js
  packages/web-components/src/keplr-connection/getKeplrAddress.js
  packages/web-components/src/keplr-connection/onLoad.js
  packages/web-components/src/keplr-connection/watchWallet.js
Labels: automerge:squash, bypass:integration

#6456 build: remove some test-dapp checks
  .github/workflows/test-dapp-card-store.yml.DISABLED
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
  .github/workflows/test-dapp-treasury.yml.DISABLED
Labels: automerge:merge

#6464 chore: set default PSM fees to 0%
  packages/inter-protocol/src/proposals/startPSM.js
  packages/smart-wallet/test/test-psm-integration.js
Labels: automerge:merge, force:integration

#6465 fix(vats): Toy USDC denom in test config
  packages/vats/decentral-test-psm-config.json
Labels: automerge:rebase, want-in-pismo

#6467 chore(release): publish
  golang/cosmos/CHANGELOG.md
  golang/cosmos/package.json
  packages/ERTP/CHANGELOG.md
  packages/ERTP/package.json
  packages/SwingSet/CHANGELOG.md
  packages/SwingSet/package.json
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/cache/CHANGELOG.md
  packages/cache/package.json
  packages/casting/CHANGELOG.md
  packages/casting/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/CHANGELOG.md
  packages/deploy-script-support/package.json
  packages/governance/CHANGELOG.md
  packages/governance/package.json
  packages/import-manager/CHANGELOG.md
  packages/import-manager/package.json
  packages/inter-protocol/CHANGELOG.md
  packages/inter-protocol/package.json
  packages/pegasus/CHANGELOG.md
  packages/pegasus/package.json
  packages/sharing-service/CHANGELOG.md
  packages/sharing-service/package.json
  packages/smart-wallet/CHANGELOG.md
  packages/smart-wallet/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
  packages/spawner/CHANGELOG.md
  packages/spawner/package.json
  packages/store/CHANGELOG.md
  packages/store/package.json
  packages/swingset-runner/CHANGELOG.md
  packages/swingset-runner/package.json
  packages/ui-components/CHANGELOG.md
  packages/ui-components/package.json
  packages/vat-data/CHANGELOG.md
  packages/vat-data/package.json
  packages/vats/CHANGELOG.md
  packages/vats/package.json
  packages/wallet-connection/CHANGELOG.md
  packages/wallet-connection/package.json
  packages/wallet/CHANGELOG.md
  packages/wallet/api/CHANGELOG.md
  packages/wallet/api/package.json
  packages/wallet/package.json
  packages/wallet/ui/CHANGELOG.md
  packages/wallet/ui/package.json
  packages/web-components/CHANGELOG.md
  packages/web-components/package.json
  packages/zoe/CHANGELOG.md
  packages/zoe/package.json
Labels: tooling, automerge:merge

#6451 Patch bug in `stack-utils` npm package
  patches/stack-utils+2.0.5.patch
Labels: bug, automerge:rebase

#6296 fix: arb passable tools
  packages/store/package.json
  packages/store/test/test-rankOrder.js
  packages/store/tools/arb-passable.js
Labels: automerge:squash

#6389 docs: a set of diagrams on Zoe and Zcf datastores and initialization
  packages/zoe/docs/Invitations,Offers,Seats.png
  packages/zoe/docs/ZcfDataInitialization.puml
  packages/zoe/docs/Zoe+ZCF-DataStores.png
  packages/zoe/docs/ZoeDataInitialization.puml
  packages/zoe/docs/ZoeZCFDataStoreInitialization.png
  packages/zoe/docs/ZoeZCFInvitations,Offers,Seats.png
  packages/zoe/docs/offers+invitations+seats.puml
Labels: documentation, Zoe, automerge:squash

#6444 5791 update price authority
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/test-oracle-integration.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/nameHub.js
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
Labels: automerge:merge

#6470 fix: typo in error message
  packages/store/src/patterns/encodePassable.js
Labels: automerge:squash

#6477 fix: better proposal mismatch errors
  packages/inter-protocol/test/psm/test-psm.js
  packages/zoe/src/zoeService/offer/offer.js
Labels: automerge:squash

#6479 fix: simplify unnecessary promise
  packages/inter-protocol/src/proposals/econ-behaviors.js
Labels: automerge:squash

#6463 Dapp wallet bridge
  packages/wallet/ui/config-overrides/index.js
  packages/wallet/ui/package.json
  packages/wallet/ui/src/bridge-dapp.jsx
  packages/wallet/ui/src/bridge.jsx
  packages/wallet/ui/src/bridge.scss
  packages/wallet/ui/src/components/AppBar.jsx
  packages/wallet/ui/src/components/ChainConnector.jsx
  packages/wallet/ui/src/components/Dapp.jsx
  packages/wallet/ui/src/components/Offer.jsx
  packages/wallet/ui/src/components/Requests.jsx
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/components/WalletConnection.jsx
  packages/wallet/ui/src/components/tests/AppBar.test.jsx
  packages/wallet/ui/src/components/tests/ChainConnector.test.jsx
  packages/wallet/ui/src/components/tests/Dapp.test.jsx
  packages/wallet/ui/src/components/tests/DappConnection.test.jsx
  packages/wallet/ui/src/components/tests/Offer.test.jsx
  packages/wallet/ui/src/components/tests/Requests.test.jsx
  packages/wallet/ui/src/components/tests/WalletConnection.test.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/service/Dapps.js
  packages/wallet/ui/src/service/Offers.js
  packages/wallet/ui/src/service/ScopedBridge.js
  packages/wallet/ui/src/store/Dapps.js
  packages/wallet/ui/src/store/Offers.js
  packages/wallet/ui/src/tests/App.test.jsx
  packages/wallet/ui/src/util/BridgeStorage.js
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/util/storage.js
  packages/wallet/ui/src/views/Dapps.jsx
  packages/wallet/ui/src/views/tests/Dapps.test.jsx
  packages/web-components/dapp-wallet-bridge.js
  packages/web-components/index.js
  packages/web-components/react.js
  packages/web-components/src/AgoricWalletConnection.js
  packages/web-components/src/dapp-wallet-bridge/DappWalletBridge.js
  packages/web-components/src/keplr-connection/KeplrConnection.js
  packages/web-components/src/keplr-connection/watchWallet.js
Labels: automerge:squash, bypass:integration

#6487 docs: PSM README
  packages/inter-protocol/src/psm/README.md
Labels: automerge:merge, bypass:integration

#6486 build(web-components): add necessary dependencies
  packages/wallet/ui/package.json
  packages/wallet/ui/src/bridge-dapp.jsx
  packages/web-components/package.json
  packages/web-components/src/dapp-wallet-bridge/DappWalletBridge.js
Labels: automerge:squash, bypass:integration

#6488 fix(wallet-ui): dont overwrite all offers when adding new one
  packages/wallet/ui/src/store/Offers.js
Labels: automerge:rebase, bypass:integration

#6492 omit superfluous 'SEVERED: ' from wallet spend proposal
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/service/Offers.js
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/util/keyManagement.js
Labels: automerge:merge, bypass:integration

#6493 sync Endo versions
  MAINTAINERS.md
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deploy-script-support/src/install.js
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/internal/src/index.js
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/ui/package.json
  packages/web-components/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/xsnap/test/test-xs-perf.js
  packages/zoe/package.json
  patches/@endo+bundle-source+2.3.1.patch
  patches/@endo+ses-ava+0.2.35.patch
  yarn.lock
Labels: automerge:merge

#6369 no more maxNodeModuleJsDepth
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernelSyscall.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/src/config.js
  packages/notifier/package.json
  packages/notifier/src/asyncIterableAdaptor.js
  packages/notifier/src/storesub.js
  packages/notifier/test/prepare-test-env-ava.js
  packages/notifier/test/test-publish-kit.js
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/smart-wallet/src/smartWallet.js
  packages/solo/package.json
  packages/store/package.json
  packages/store/src/patterns/interface-tools.js
  packages/swing-store/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/ui/endo-promise-kit.d.ts
  packages/web-components/package.json
  packages/zoe/package.json
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contracts/priceAggregator.js
Labels: automerge:merge

#6496 docs: some doc on typeguards for parameters
  packages/store/src/types.js
Labels: documentation, automerge:merge

#6498 feat(wallet-ui): reenable solo-only wallet
  packages/wallet/README.md
  packages/wallet/package.json
  yarn.lock
Labels: automerge:merge

#6495 feat(wallet-ui): add terms dialog on first pageview
  packages/wallet/ui/src/components/AppBar.jsx
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/components/TermsDialog.jsx
  packages/wallet/ui/src/components/TermsDialog.module.scss
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/service/Terms.js
  packages/wallet/ui/src/store/Terms.js
  packages/wallet/ui/src/tests/App.test.jsx
  packages/wallet/ui/src/util/storage.js
Labels: automerge:squash, automerge:rebase, bypass:integration

#6504 feat(makeChainInfo)!: rpc param as authoritative
  packages/wallet/ui/src/util/SuggestChain.js
Labels: automerge:merge, bypass:integration

#6499 e2e demo of priceAggregator updates by smart wallet
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/cosmic-swingset/Makefile
  packages/inter-protocol/scripts/start-local-chain-boot.js
  packages/inter-protocol/scripts/start-local-chain-config.json
  packages/inter-protocol/scripts/start-local-chain.sh
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startEconCommittee.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/proposals/utils.js
  packages/smart-wallet/test/devices.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/test/devices.js
  packages/zoe/scripts/build-bundles.js
  packages/zoe/src/contracts/oracle.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/test/unitTests/contracts/test-oracle.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/contracts/test-priceAggregatorChainlink.js
  packages/zoe/tools/scriptedOracle.js
Labels: automerge:merge

#6510 fix: include swingset/* file for export
  packages/cosmic-proto/package.json
Labels: automerge:merge, bypass:integration

#6505 feat(makeChainInfo): optional apiAddrs
  packages/casting/package.json
  packages/casting/src/leader-netconfig.js
  packages/casting/src/netconfig.js
  packages/casting/test/fake-rpc-server.js
  packages/casting/test/test-mvp.js
  packages/casting/test/test-netconfig.js
  packages/wallet/ui/src/util/SuggestChain.js
  packages/wallet/ui/src/util/tests/SuggestChain.test.js
Labels: automerge:merge
