Repository Agoric/agoric-sdk, pull requests merged in 2022-05, with the labels that each got.

#5206 feat(wallet): support attestations in offers
  packages/run-protocol/src/runStake/types.js
  packages/wallet/api/package.json
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/wallet.js
  packages/wallet/api/test/attestationExample.js
  packages/wallet/api/test/test-lib-wallet.js
Labels: automerge:squash, automerge:rebase

#5255 refactor(notifier): clearer signature for makeNotifierKit()
  packages/notifier/src/notifier.js
  packages/notifier/test/test-notifier.js
Labels: automerge:squash

#5259 chore: Fix harmless bootstrap-related bugs and typos
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/vat-ibc.js
Labels: hygiene, automerge:squash

#5272 ci: only notify if integration job fails on master
  .github/workflows/deployment-test.yml
  .github/workflows/integration.yml
Labels: automerge:squash

#5258 chore: Improve StorageAPI-related comments and code consistency
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/storageWrapper.js
  packages/cosmic-swingset/src/chain-main.js
Labels: SwingSet, cosmic-swingset, hygiene, automerge:squash

#5274 chore(swingset): add the failing deliveryNum to anachrophobia errors
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/transcript.js
Labels: SwingSet, automerge:rebase

#5270 test(swingset): improve tests on result promises that appear in args
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/test/message-patterns.js
  packages/SwingSet/test/test-comms.js
  packages/SwingSet/test/test-kernel.js
  packages/SwingSet/test/test-liveslots.js
Labels: SwingSet, automerge:rebase

#5273 feat: add governance for RECORDS as a parameter type
  packages/governance/src/constants.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/test/unitTests/test-buildParamManager.js
Labels: enhancement, Governance, automerge:squash

#5276 ci: require integration tests only before merging
  .mergify.yml
Labels: automerge:squash

#5275 Store metadata for each virtual object kind
  packages/SwingSet/src/liveslots/vatstore-usage.md
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/stores/test-storeGC/gc-helpers.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
Labels: enhancement, SwingSet, automerge:rebase

#5235 feature!: impose a minimum loan size when opening a vault
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: enhancement, RUN-protocol, Governance, automerge:squash, Vaults

#5279 chore: Better document use of StorageAPI
  packages/SwingSet/docs/state.md
  packages/SwingSet/src/controller/hostStorage.js
  packages/SwingSet/src/kernel/state/storageWrapper.js
  packages/SwingSet/src/lib/storageAPI.js
  packages/access-token/src/json-store.js
  packages/swing-store/src/swingStore.js
Labels: SwingSet, hygiene, automerge:rebase

#5214 refactor(vault): make liquidation recursion a loop
  packages/run-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
Labels: automerge:squash

#5252 feat(swingset): queue to promise
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/test/message-patterns.js
  packages/SwingSet/test/test-kernel.js
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
Labels: SwingSet, automerge:rebase, force:integration

#5291 chore(swingset): split test out to a separate file
  packages/SwingSet/test/vat-admin/terminate/test-terminate-replay.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
Labels: SwingSet, automerge:rebase

#5297 Persistently track transcript start position
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade-replay.js
  packages/SwingSet/test/upgrade/test-upgrade-replay.js
  packages/SwingSet/test/upgrade/vat-upton-replay.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
Labels: bug, SwingSet, automerge:rebase

#5289 ci: cancel other jobs on pull-requests only
  .github/workflows/pre-check-integration.yml
Labels: automerge:squash, bypass:integration

#5292 refactor(cosmic-swingset): Improve makeChainStorage parameters
  packages/cosmic-swingset/src/chain-main.js
Labels: cosmic-swingset, code-style, automerge:rebase

#5320 fix(dependabot): ignore devDependencies
  .github/dependabot.yml
Labels: automerge:rebase

#5321 feat(SwingSet): implement `console` event `source` property
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/slogger.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js
  packages/SwingSet/src/types-external.js
  packages/swingset-runner/test/test-demo.js
Labels: SwingSet

#5322 fix(deployment): Update CI script
  .github/workflows/deployment-test.yml
  packages/deployment/scripts/capture-integration-results.sh
  scripts/run-deployment-integration.sh
Labels: automerge:squash, force:integration

#5323 fix(deployment): disable swingstore consistency check
  packages/deployment/scripts/capture-integration-results.sh
Labels: automerge:squash, bypass:integration

#5257 test: governance for vault collateral, oracles
  .github/workflows/integration.yml
  MAINTAINERS.md
  docker/docker-compose.yml
  packages/cosmic-swingset/src/launch-chain.js
  packages/deploy-script-support/src/code-gen.js
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/run-protocol/Makefile
  packages/run-protocol/docs/run-preview-vault-asset.md
  packages/run-protocol/package.json
  packages/run-protocol/scripts/add-collateral-core.js
  packages/run-protocol/scripts/build-bundles.js
  packages/run-protocol/scripts/invite-committee-core.js
  packages/run-protocol/src/committee-proposal.js
  packages/run-protocol/src/core-proposal.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/econCommitteeCharter.js
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/src/vaultFactory/addAssetToVault.js
  packages/run-protocol/test/bundleTool.js
  packages/run-protocol/test/supports.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/types.js
  packages/vats/src/distributeFees.js
  scripts/docker-tag.sh
Labels: RUN-protocol, Governance, automerge:merge

#5302 Defend against LMDB key size overflow
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-node.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/supervisors/nodeworker/supervisor-nodeworker.js
  packages/SwingSet/src/supervisors/subprocess-node/supervisor-subprocess-node.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/supervisor-subprocess-xsnap.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/liveslots-helpers.js
  packages/SwingSet/test/run-policy/test-run-policy.js
  packages/SwingSet/test/run-policy/vat-policy-right.js
  packages/SwingSet/test/stores/test-collections.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/test-vatstore.js
  packages/SwingSet/test/vat-vatstore.js
  packages/SwingSet/test/workers/bootstrap.js
  packages/SwingSet/test/workers/test-worker.js
  packages/SwingSet/test/workers/vat-target.js
Labels: bug, SwingSet, automerge:rebase

#5223 test(vault): multiple liquidations
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
Labels: automerge:squash

#5324 Prevent bootstrap coreProposal path nondeterminism
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/vats/src/core/chain-behaviors.js
Labels: cosmic-swingset, deployment, automerge:merge

#5325 chore(release): publish 22
  .github/workflows/docker.yml
  go.mod
  go.sum
  packages/ERTP/CHANGELOG.md
  packages/ERTP/package.json
  packages/SwingSet/CHANGELOG.md
  packages/SwingSet/package.json
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/CHANGELOG.md
  packages/deploy-script-support/package.json
  packages/deployment/CHANGELOG.md
  packages/deployment/package.json
  packages/governance/CHANGELOG.md
  packages/governance/package.json
  packages/import-manager/CHANGELOG.md
  packages/import-manager/package.json
  packages/pegasus/CHANGELOG.md
  packages/pegasus/package.json
  packages/run-protocol/CHANGELOG.md
  packages/run-protocol/package.json
  packages/sharing-service/CHANGELOG.md
  packages/sharing-service/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
  packages/spawner/CHANGELOG.md
  packages/spawner/package.json
  packages/store/CHANGELOG.md
  packages/store/package.json
  packages/swingset-runner/CHANGELOG.md
  packages/swingset-runner/package.json
  packages/ui-components/CHANGELOG.md
  packages/ui-components/package.json
  packages/vat-data/CHANGELOG.md
  packages/vat-data/package.json
  packages/vats/CHANGELOG.md
  packages/vats/package.json
  packages/wallet/CHANGELOG.md
  packages/wallet/api/CHANGELOG.md
  packages/wallet/api/package.json
  packages/wallet/package.json
  packages/wallet/ui/CHANGELOG.md
  packages/wallet/ui/package.json
  packages/zoe/CHANGELOG.md
  packages/zoe/package.json
Labels: tooling, automerge:merge

#5331 fix: array.map that should be array.forEach
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/virtualObjects/delete-stored-vo/test-delete-stored-vo.js
Labels: automerge:squash

#5337 fix(run-protocol): raise demo issuer debt limit
  packages/run-protocol/src/demoIssuers.js
Labels: automerge:rebase

#5336 improve run-protocol types
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/src/contractHelper.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/contractGovernor/governedContract.js
  packages/run-protocol/src/psm/psm.js
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
Labels: automerge:merge

#5339 Fix bug in fake virtual stuff due to recent liveslots additions
  packages/SwingSet/tools/fakeVirtualSupport.js
Labels: bug, SwingSet, automerge:rebase

#5340 Scaled unit ratios and `overrideManifest`
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/run-protocol/src/vaultFactory/addAssetToVault.js
  packages/run-protocol/test/test-gov-collateral.js
Labels: cosmic-swingset, RUN-protocol, Governance, automerge:merge

#5357 fix: deployment job should capture results on failure
  .github/workflows/deployment-test.yml
Labels: automerge:squash, bypass:integration

#5351 feat(web-components): handle solo reset
  packages/cosmic-swingset/src/launch-chain.js
  packages/solo/public/wallet-bridge.html
  packages/web-components/src/AgoricWalletConnection.js
  packages/web-components/src/bridge-iframe-connector.js
Labels: solo, automerge:merge, web-components

#5360 fix(deployment): Do not override explicit faucet SOLO_COINS
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
Labels: automerge:squash

#5362 Decentral economy config
  docs/env.md
  golang/cosmos/x/vbank/vbank.go
  packages/agoric-cli/src/start.js
  packages/cosmic-swingset/Makefile
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/run-protocol/scripts/add-collateral-core.js
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/scripts/invite-committee-core.js
  packages/run-protocol/src/committee-proposal.js
  packages/run-protocol/src/core-proposal.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/psm/startPSM.js
  packages/run-protocol/src/vaultFactory/addAssetToVault.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/solo/src/init-basedir.js
  packages/vats/decentral-economy-config.json
  packages/vats/scripts/set-core-proposal-env.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/types.js
Labels: cosmic-swingset, RUN-protocol, automerge:merge

#5373 Reconnect wallet more robustly
  packages/solo/public/main.js
  packages/wallet/ui/public/index.html
  packages/wallet/ui/src/components/WalletConnection.jsx
  packages/wallet/ui/src/components/tests/WalletConnection.test.jsx
  packages/wallet/ui/src/contexts/Application.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/web-components/src/AgoricWalletConnection.js
  packages/web-components/src/admin-websocket-connector.js
  packages/web-components/src/bridge-iframe-connector.js
Labels: wallet, automerge:merge, web-components

#5305 fix(run-protocol): add diagrams for reserve, and fix a typo in the reserve
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/src/reserve/doc.md
Labels: automerge:rebase

#5372 fix(vats): store results of createVatByName for zoe etc.
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/manifest.js
Labels: automerge:rebase

#5374 Bootstrap with oracle invitations
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/decentral-economy-template.json
  packages/pegasus/scripts/init-core.js
  packages/pegasus/src/proposals/core-proposal.js
  packages/run-protocol/package.json
  packages/run-protocol/scripts/add-collateral-core.js
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/scripts/invite-committee-core.js
  packages/run-protocol/scripts/manual-price-feed.js
  packages/run-protocol/scripts/price-feed-core.js
  packages/run-protocol/src/proposals/addAssetToVault.js
  packages/run-protocol/src/proposals/committee-proposal.js
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/demoIssuers.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/proposals/price-feed-proposal.js
  packages/run-protocol/src/proposals/sim-behaviors.js
  packages/run-protocol/src/proposals/startPSM.js
  packages/run-protocol/src/proposals/utils.js
  packages/run-protocol/src/proposals/writePsmScript.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/run-protocol/test/reserve/setup.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/supports.js
  packages/run-protocol/test/test-demoAMM.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/vats/scripts/set-core-proposal-env.js
  packages/vats/src/core/boot.js
  packages/vats/src/nameHub.js
  packages/vats/src/types.js
  packages/vats/test/test-clientBundle.js
  packages/vats/test/test-name-hub.js
Labels: RUN-protocol, Governance, automerge:merge, oracle

#5281 feat(swingset): get queues length
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/metrics.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/stats.js
  packages/SwingSet/test/bundling/test-bundles-kernel.js
  packages/SwingSet/test/snapshots/test-state.js.md
  packages/SwingSet/test/snapshots/test-state.js.snap
  packages/SwingSet/test/test-state.js
Labels: automerge:rebase, force:integration

#5343 feat(vault): liquidation penalty handled by liquidation contracts
  packages/governance/src/contractGovernance/paramManager.js
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/reserve/setup.js
  packages/run-protocol/test/swingsetTests/mockAmm.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/vaultFactory/test-liquidation-helpers.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/otcDesk.js
  packages/zoe/src/types.js
Labels: automerge:squash

#5378 fix(run-protocol): adapt PSM bootstrap to core proposal conventions
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/decentral-economy-template.json
  packages/run-protocol/package.json
  packages/run-protocol/scripts/add-collateral-core.js
  packages/run-protocol/scripts/gov-startPSM-permit.json
  packages/run-protocol/scripts/gov-startPSM.js
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/src/proposals/addAssetToVault.js
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/startPSM.js
  packages/run-protocol/src/proposals/utils.js
  packages/run-protocol/src/proposals/writePsmScript.js
Labels: automerge:merge

#5371 fix(solo): introduce runStake attMaker to wallet admin facet
  packages/solo/src/vat-http.js
Labels: wallet, RUN-protocol, automerge:squash

#5382 fix(wallet-ui): put back missing dapps notifier
  packages/wallet/ui/src/contexts/Application.jsx
Labels: automerge:squash, automerge:rebase

#5260 feat(vault): econ metrics notifiers
  packages/run-protocol/src/runStake/runStakeKit.js
  packages/run-protocol/src/vaultFactory/prioritizedVaults.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/src/vaultFactory/vaultTitle.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/test/unitTests/zcf/setupZcfTest.js
Labels: automerge:squash

#5391 test(zoe): offerTo handling of broken invitation
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/test/unitTests/contractSupport/test-offerTo.js
Labels: automerge:merge, bypass:integration

#5388 Generate economy and loadgen configs from the core config
  packages/agoric-cli/src/deploy.js
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/decentral-economy-template.json
  packages/cosmic-swingset/economy-template.json
  packages/deploy-script-support/src/extract-proposal.js
  packages/deployment/scripts/integration-test.sh
  packages/telemetry/src/slog-to-otel.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-loadgen-config.json
  packages/vats/demo-proposals.json
  packages/vats/src/nameHub.js
  packages/vats/src/types.js
  packages/vats/test/test-name-hub.js
Labels: cosmic-swingset, agoric-cli, automerge:merge, telemetry

#5394 fix(keeper): do not delete keys with descendents
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/keeper_test.go
Labels: cosmic-swingset, automerge:merge

#5370 refactor(swingset): Reserve host prefix in the store
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/storageWrapper.js
  packages/SwingSet/test/test-state.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:squash

#5399 fix(deploy): enforce `--hostport` URLs use `/private/captp`
  packages/agoric-cli/src/deploy.js
Labels: agoric-cli, automerge:merge

#5395 Support symbol-named methods in virtual objects
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
Labels: enhancement, SwingSet, automerge:rebase

#5405 ci(Mergify): configuration update
  .mergify.yml
Labels: automerge:squash, bypass:integration

#5402 test: metrics subscription testing support
  packages/run-protocol/package.json
  packages/run-protocol/test/metrics.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  yarn.lock
Labels: automerge:squash

#5411 Make legibilizeValue behave better given weird input
  packages/SwingSet/src/lib/kdebug.js
  packages/SwingSet/test/test-kdebug.js
Labels: bug, SwingSet, automerge:rebase

#5401 refactor: improved debugging messages for durability
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/stores/test-durabilityChecks.js
Labels: marshal, cosmic-swingset, devex, automerge:squash

#5414 Cosmos vbank reserve purse
  golang/cosmos/app/app.go
  golang/cosmos/x/vbank/keeper/keeper.go
  golang/cosmos/x/vbank/types/expected_keepers.go
  golang/cosmos/x/vbank/types/key.go
  golang/cosmos/x/vbank/vbank.go
  golang/cosmos/x/vbank/vbank_test.go
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/vat-bank.js
  packages/vats/test/test-vat-bank.js
Labels: cosmic-swingset, automerge:merge, agoric-cosmos

#5397 feat: permissionless AMM pools from Interchain assets
  packages/run-protocol/scripts/add-collateral-core.js
  packages/run-protocol/scripts/build-bundles.js
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/src/interchainPool.js
  packages/run-protocol/src/proposals/addAssetToVault.js
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/vpool-xyk-amm/addLiquidity.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/supports.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/run-protocol/test/test-interchainPool.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
Labels: automerge:merge

#5415 chore(wallet-ui): upgrade react-scripts to v5
  package.json
  packages/wallet/ui/config-overrides/index.js
  packages/wallet/ui/config-overrides/package.json
  packages/wallet/ui/package.json
  patches/acorn+7.4.1.patch
  patches/acorn+8.7.1.patch
  patches/depd+2.0.0.patch
  patches/express+4.18.1.patch
  yarn.lock
Labels: automerge:squash

#5377 feat(AMM)!: make amm.addPool() require minimum collateral
  packages/run-protocol/src/interchainPool.js
  packages/run-protocol/src/proposals/addAssetToVault.js
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/demoIssuers.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/vpool-xyk-amm/AttackersGuide.md
  packages/run-protocol/src/vpool-xyk-amm/addLiquidity.js
  packages/run-protocol/src/vpool-xyk-amm/addPool.js
  packages/run-protocol/src/vpool-xyk-amm/constantProduct/internal-types.js
  packages/run-protocol/src/vpool-xyk-amm/doublePool.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/params.js
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/singlePool.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-amm-calc.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-liquidity.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
  packages/run-protocol/test/reserve/setup.js
  packages/run-protocol/test/reserve/test-reserve.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/run-protocol/test/test-interchainPool.js
  packages/run-protocol/test/test-voPool.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/test/autoswapJig.js
Labels: Inter-protocol, AMM, automerge:squash

#5423 fix(interchainPool): get MinInitialLiquidity from AMM on demand
  packages/run-protocol/src/interchainPool.js
  packages/run-protocol/test/test-gov-collateral.js
Labels: automerge:squash

#5420 feat: publish econ stats from AMM
  packages/run-protocol/src/vpool-xyk-amm/addPool.js
  packages/run-protocol/src/vpool-xyk-amm/constantProduct/calcFees.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/singlePool.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
  packages/run-protocol/test/metrics.js
  packages/run-protocol/test/test-voPool.js
Labels: enhancement, Inter-protocol, AMM, automerge:squash

#5387 liquidation penalty proceeds to reserve
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/run-protocol/test/bundleTool.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
Labels: automerge:merge

#5426 fix(swing-store): check fs streams are ready
  packages/swing-store/src/snapStore.js
  packages/xsnap/src/replay.js
Labels: automerge:rebase

#5425 fix: default missed signed blocks should be higher
  packages/agoric-cli/src/chain-config.js
Labels: automerge:rebase

#5434 refactor(vaults): rename VaultTitle to VaultHolder
  packages/run-protocol/src/vaultFactory/vaultHolder.js
  packages/run-protocol/src/vaultFactory/vaultKit.js
Labels: automerge:merge

#5393 feat(vaultManager): expose liquidation metrics
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/prioritizedVaults.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/metrics.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/run-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/xsnap/src/avaAssertXS.js
Labels: automerge:squash

#5427 Reward distribution mechanics
  golang/cosmos/app/ante/expected_keepers.go
  golang/cosmos/app/ante/fees.go
  golang/cosmos/app/ante/handler.go
  golang/cosmos/app/ante/vm_admission.go
  golang/cosmos/app/app.go
  golang/cosmos/proto/agoric/vbank/vbank.proto
  golang/cosmos/x/vbank/README.md
  golang/cosmos/x/vbank/keeper/keeper.go
  golang/cosmos/x/vbank/keeper/rewards.go
  golang/cosmos/x/vbank/module.go
  golang/cosmos/x/vbank/types/key.go
  golang/cosmos/x/vbank/types/params.go
  golang/cosmos/x/vbank/types/vbank.pb.go
  golang/cosmos/x/vbank/vbank.go
  golang/cosmos/x/vbank/vbank_test.go
  packages/agoric-cli/src/chain-config.js
Labels: automerge:merge, agoric-cosmos, proto:expect-breakage

#5368 feat(swingset): add vatAdminService.getBundleIDByName()
  packages/SwingSet/docs/bundles.md
  packages/SwingSet/src/devices/vat-admin/device-vat-admin.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/bundling/bootstrap-bundles.js
  packages/SwingSet/test/bundling/test-bundles.js
Labels: SwingSet, automerge:rebase

#5431 feat: Reserves track liquidation shortfall
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/reserve/test-reserve.js
  packages/run-protocol/test/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/swingsetTests/vaultFactory/test-vaultFactory.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: enhancement, Zoe Contract, Inter-protocol, automerge:squash, Vaults

#5441 fix: reinstate economy boot using minInitialPoolLiquidity=0
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/economy-template.json
  packages/run-protocol/scripts/add-collateral-core.js
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/src/proposals/addAssetToVault.js
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/vpool-xyk-amm/addPool.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: automerge:merge

#5444 feat(Reserve): Reserve can burn RUN to reduce shortfall
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/test/reserve/test-reserve.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: enhancement, Inter-protocol, automerge:squash

#5446 fix(amm): update metrics whenever pool balances change, including init
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/singlePool.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-liquidity.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
Labels: bug, AMM, automerge:merge

#4975 feat: Support publishing source bundles to chain and installing hash bundles to Zoe
  golang/cosmos/proto/agoric/swingset/msgs.proto
  golang/cosmos/x/swingset/client/cli/tx.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/types/msgs.go
  golang/cosmos/x/swingset/types/msgs.pb.go
  packages/agoric-cli/jsconfig.json
  packages/agoric-cli/package.json
  packages/agoric-cli/src/deploy.js
  packages/agoric-cli/src/json-http-client-node.js
  packages/agoric-cli/src/main.js
  packages/agoric-cli/src/publish.js
  packages/agoric-cli/test/test-publish-bundle.js
  packages/cosmic-swingset/src/action-types.js
  packages/cosmic-swingset/src/block-manager.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/solo/package.json
  packages/solo/src/chain-cosmos-sdk.js
  packages/solo/src/start.js
  packages/solo/src/web.js
  packages/solo/test/test-home.js
  packages/vats/package.json
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/tools/fakeVatAdmin.js
  yarn.lock
Labels: automerge:rebase

#5440 vault security improvements
  packages/deploy-script-support/test/unitTests/test-startInstance.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/runStake/runStakeManager.js
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/prioritizedVaults.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/supports.js
  packages/zoe/src/zoeService/zoe.js
Labels: automerge:merge

#5429 feat(amm)!: push reserved assets to reserve contract
  packages/run-protocol/src/proposals/addAssetToVault.js
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vpool-xyk-amm/addPool.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-liquidity.js
  packages/run-protocol/test/reserve/setup.js
  packages/run-protocol/test/reserve/test-reserve.js
  packages/run-protocol/test/supports.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/run-protocol/test/test-interchainPool.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/src/contractSupport/zoeHelpers.js
Labels: automerge:squash

#5452 rename Store param 'keyName' to 'tag'
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/src/liveslots/watchedPromises.js
  packages/store/src/legacy/legacyMap.js
  packages/store/src/legacy/legacyWeakMap.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/swing-store/src/ephemeralSwingStore.js
Labels: automerge:merge

#5450 refactor: notification of pool balances use amount for liquidity
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-liquidity.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
Labels: bug, AMM, automerge:squash

#5451 fix(swingset): fsync snapshots
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
Labels: automerge:squash, force:integration

#5448 Fee distributor contract
  packages/deployment/Dockerfile.sdk
  packages/governance/test/unitTests/test-committee.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/src/feeDistributor.js
  packages/run-protocol/src/proposals/core-proposal.js
  packages/run-protocol/src/proposals/econ-behaviors.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
  packages/run-protocol/test/reserve/setup.js
  packages/run-protocol/test/reserve/test-reserve.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/test-feeDistributor.js
  packages/run-protocol/test/test-gov-collateral.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/src/distributeFees.js
  packages/vats/src/types.js
  packages/vats/src/vat-distributeFees.js
  packages/vats/test/test-boot.js
  packages/zoe/test/unitTests/contracts/loan/test-addCollateral.js
  packages/zoe/test/unitTests/contracts/loan/test-borrow.js
  packages/zoe/test/unitTests/contracts/loan/test-loan-e2e.js
  packages/zoe/test/unitTests/contracts/test-auction.js
  packages/zoe/test/unitTests/contracts/test-callSpread.js
  packages/zoe/test/unitTests/contracts/test-coveredCall-want-pattern.js
  packages/zoe/test/unitTests/contracts/test-coveredCall.js
  packages/zoe/test/unitTests/contracts/test-otcDesk.js
  packages/zoe/test/unitTests/test-cleanProposal.js
  packages/zoe/test/unitTests/test-fakePriceAuthority.js
  packages/zoe/test/unitTests/test-manualTimer.js
  packages/zoe/test/unitTests/test-scriptedOracle.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: Inter-protocol, automerge:merge

#5458 Publish release 23
  golang/cosmos/CHANGELOG.md
  golang/cosmos/package.json
  packages/ERTP/CHANGELOG.md
  packages/ERTP/package.json
  packages/SwingSet/CHANGELOG.md
  packages/SwingSet/package.json
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/CHANGELOG.md
  packages/deploy-script-support/package.json
  packages/deployment/CHANGELOG.md
  packages/deployment/package.json
  packages/governance/CHANGELOG.md
  packages/governance/package.json
  packages/import-manager/CHANGELOG.md
  packages/import-manager/package.json
  packages/pegasus/CHANGELOG.md
  packages/pegasus/package.json
  packages/run-protocol/CHANGELOG.md
  packages/run-protocol/package.json
  packages/same-structure/CHANGELOG.md
  packages/same-structure/package.json
  packages/sharing-service/CHANGELOG.md
  packages/sharing-service/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
  packages/spawner/CHANGELOG.md
  packages/spawner/package.json
  packages/store/CHANGELOG.md
  packages/store/package.json
  packages/swing-store/CHANGELOG.md
  packages/swing-store/package.json
  packages/swingset-runner/CHANGELOG.md
  packages/swingset-runner/package.json
  packages/telemetry/CHANGELOG.md
  packages/telemetry/package.json
  packages/ui-components/CHANGELOG.md
  packages/ui-components/package.json
  packages/vat-data/CHANGELOG.md
  packages/vat-data/package.json
  packages/vats/CHANGELOG.md
  packages/vats/package.json
  packages/wallet-connection/CHANGELOG.md
  packages/wallet-connection/package.json
  packages/wallet/CHANGELOG.md
  packages/wallet/api/CHANGELOG.md
  packages/wallet/api/package.json
  packages/wallet/package.json
  packages/wallet/ui/CHANGELOG.md
  packages/wallet/ui/package.json
  packages/web-components/CHANGELOG.md
  packages/web-components/package.json
  packages/xsnap/CHANGELOG.md
  packages/xsnap/package.json
  packages/zoe/CHANGELOG.md
  packages/zoe/package.json
Labels: tooling, automerge:merge

#5436 feat: allow vats to be marked critical and panic the kernel if a critical vat fails
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/vat-admin/terminate/bootstrap-badVatKey.js
  packages/SwingSet/test/vat-admin/terminate/bootstrap-terminate.js
  packages/SwingSet/test/vat-admin/terminate/swingset-bad-vat-key.json
  packages/SwingSet/test/vat-admin/terminate/swingset-terminate.json
  packages/SwingSet/test/vat-admin/terminate/test-terminate-critical.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate-non-critical.js
  packages/swingset-runner/package.json
  packages/swingset-runner/src/vat-launcher.js
Labels: enhancement, SwingSet, automerge:rebase

#5459 fix(agoric-cli): publishBundle types
  packages/agoric-cli/src/publish.js
  packages/agoric-cli/test/test-publish-bundle.js
Labels: automerge:squash, bypass:integration

#5265 TypeScript 4.7
  package.json
  packages/run-protocol/test/attestation/test-attestation.js
  packages/ui-components/package.json
  packages/vat-data/src/index.js
  yarn.lock
Labels: automerge:rebase

#5455 feat(telemetry): `otel-and-flight-recorder.js` for the best of both
  golang/cosmos/cmd/libdaemon/main.go
  packages/deployment/scripts/integration-test.sh
  packages/deployment/src/main.js
  packages/telemetry/src/kv-string-store.js
  packages/telemetry/src/otel-and-flight-recorder.js
  packages/telemetry/src/otel-trace.js
  packages/telemetry/src/slog-to-otel.js
Labels: automerge:merge, telemetry
