Repository Agoric/agoric-sdk, pull requests merged in 2022-01, with the labels that each got.

#4234 feat(web-components): Add Powerbox-compatible petname component
  packages/web-components/agoric-petname.js
  packages/web-components/package.json
  packages/web-components/src/AgoricPetname.js
  packages/web-components/src/Powerbox.js
  packages/web-components/test/agoric-petname.test.js
  yarn.lock
Labels: automerge:squash, automerge:rebase

#4210 Patterns and Keys
  packages/marshal/index.js
  packages/marshal/src/assertPassStyleOf.js
  packages/marshal/src/helpers/copyArray.js
  packages/marshal/src/helpers/copyRecord.js
  packages/marshal/src/helpers/error.js
  packages/marshal/src/helpers/internal-types.js
  packages/marshal/src/helpers/tagged.js
  packages/marshal/src/passStyleOf.js
  packages/marshal/src/types.js
  packages/store/src/index.js
  packages/store/src/keys/checkKey.js
  packages/store/src/keys/copyMap.js
  packages/store/src/keys/copySet.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/patterns/rankOrder.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/stores/store-utils.js
  packages/store/src/types.js
  packages/store/test/test-patterns.js
Labels: automerge:squash

#4214 Use patterns in ERTP
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/src/typeGuards.js
  packages/ERTP/src/types.js
  packages/ERTP/test/unitTests/test-inputValidation.js
  packages/store/src/types.js
  packages/vats/src/virtual-purse.js
Labels: automerge:squash

#4215 Use patterns in Zoe
  packages/ERTP/src/typeGuards.js
  packages/store/src/patterns/patternMatchers.js
  packages/wallet/api/src/findOrMakeInvitation.js
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/coveredCall.js
  packages/zoe/src/typeGuards.js
  packages/zoe/test/unitTests/contracts/test-coveredCall-want-pattern.js
  packages/zoe/test/unitTests/test-cleanProposal.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
  packages/zoe/test/unitTests/zcf/test-zoeHelpersWZcf.js
Labels: automerge:squash

#4196 Use ordered merge for set operations
  packages/ERTP/src/amountMath.js
  packages/ERTP/src/mathHelpers/natMathHelpers.js
  packages/ERTP/src/mathHelpers/setMathHelpers.js
  packages/ERTP/test/unitTests/mathHelpers/test-setMathHelpers.js
  packages/ERTP/test/unitTests/mathHelpers/test-strSetMathHelpers.js
  packages/ERTP/test/unitTests/test-issuerObj.js
  packages/ERTP/test/unitTests/test-mintObj.js
  packages/store/src/index.js
  packages/store/src/keys/compareKeys.js
  packages/store/src/keys/merge-set-operators.js
  packages/store/src/patterns/rankOrder.js
  packages/zoe/test/swingsetTests/zoe/test-zoe.js
  packages/zoe/test/unitTests/contracts/test-sellTickets.js
  packages/zoe/test/zoeTestHelpers.js
Labels: automerge:squash

#4231 docs: add an Attacker's Guide for Zoe
  packages/zoe/docs/AttackGuide.md
Labels: documentation, Zoe, security, automerge:squash, threat modeling

#4239 feat(web-components): add petimage component
  packages/web-components/agoric-petimage.js
  packages/web-components/src/AgoricPetimage.js
  packages/web-components/test/agoric-petimage.test.js
Labels: automerge:squash, automerge:rebase

#4236 feat(agoric-cli): allow NPM-based `agoric install` to work with dapps
  .github/workflows/integration.yml
  packages/agoric-cli/package.json
  packages/agoric-cli/scripts/get-sdk-package-names.js
  packages/agoric-cli/src/helpers.js
  packages/agoric-cli/src/install.js
  packages/agoric-cli/src/main.js
  packages/agoric-cli/src/sdk-package-names.js
  packages/agoric-cli/src/start.js
  packages/agoric-cli/tools/getting-started.js
  packages/install-ses/package.json
  packages/solo/package.json
  packages/solo/src/start.js
  packages/solo/src/web.js
  packages/spawner/package.json
  packages/wallet/ui/package.json
  packages/xsnap/package.json
Labels: agoric-cli, automerge:merge

#4191 Improved Store API
  packages/SwingSet/src/kernel/virtualObjectManager.js
  packages/SwingSet/src/vats/network/network.js
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/electorateTools.js
  packages/governance/src/paramGovernance/paramManager.js
  packages/governance/src/types.js
  packages/pegasus/src/pegasus.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/store/src/legacy/legacyMap.js
  packages/store/src/legacy/legacyWeakMap.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/stores/store-utils.js
  packages/store/src/types.js
  packages/vats/package.json
  packages/vats/src/ibc.js
  packages/vats/src/nameHub.js
  packages/vats/src/types.js
  packages/vats/test/test-name-hub.js
  packages/wallet/api/src/internal-types.js
  packages/wallet/api/src/lib-dehydrate.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contracts/attestation/expiring/expiringHelpers.js
  packages/zoe/src/contracts/attestation/expiring/expiringNFT.js
  packages/zoe/src/contracts/attestation/expiring/unlienExpiredAmounts.js
  packages/zoe/src/contracts/attestation/expiring/updateLien.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/test/unitTests/contracts/attestation/exampleVotingUsage.js
  packages/zoe/tools/manualTimer.js
Labels: automerge:squash

#4217 Prepare for want patterns
  packages/governance/test/unitTests/test-shareHolders.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/test/test-patterns.js
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/typeGuards.js
  packages/zoe/test/unitTests/test-cleanProposal.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: automerge:squash

#4224 Update comment in installationStorage.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/zoeService/installationStorage.js
Labels: documentation, Zoe, XSmall, automerge:squash

#4251 Restore nameHub behaviour (arrays, not iterators)
  packages/vats/src/nameHub.js
  packages/vats/src/types.js
  packages/vats/test/test-name-hub.js
Labels: cosmic-swingset, automerge:merge

#4253 Clarify and correct writeup of XYK AMM README
  packages/run-protocol/src/vpool-xyk-amm/constantProduct/AMM-Trade.jpeg
  packages/run-protocol/src/vpool-xyk-amm/constantProduct/README.md
Labels: documentation, RUN-protocol, AMM, automerge:squash

#4081 chore: update internal Zoe documentation
  packages/ERTP/docs/user-safety.md
  packages/zoe/docs/handling-authority.md
  packages/zoe/docs/platform-specification.md
  packages/zoe/docs/seats.md
  packages/zoe/docs/user-seat-exit-flow.png
  packages/zoe/docs/user-seat-exit-flow.puml
  packages/zoe/docs/zcf-reallocate-flow.png
  packages/zoe/docs/zcf-reallocate-flow.puml
  packages/zoe/docs/zcf-seat-exit-flow.png
  packages/zoe/docs/zcf-seat-exit-flow.puml
  packages/zoe/docs/zoe-catalog-of-storage.md
  packages/zoe/docs/zoe-zcf.md
  packages/zoe/docs/zoe-zcf.png
  packages/zoe/docs/zoe-zcf.puml
Labels: automerge:squash

#4252 fix: update sort order so undefined comes last
  packages/store/src/patterns/rankOrder.js
Labels: bug, enhancement, automerge:rebase, stores

#4259 Dedeprecate exports from same-structure
  packages/ERTP/package.json
  packages/ERTP/src/types.js
  packages/ERTP/test/unitTests/mathHelpers/test-setMathHelpers.js
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/contractHelper.js
  packages/governance/src/electorateTools.js
  packages/governance/src/paramGovernance/governParam.js
  packages/governance/src/question.js
  packages/governance/test/swingsetTests/committeeBinary/vat-voter.js
  packages/governance/test/swingsetTests/contractGovernor/governedContract.js
  packages/run-protocol/package.json
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/test/vaultFactory/swingsetTests/governance/vat-voter.js
  packages/same-structure/package.json
  packages/swingset-runner/demo/zoeTests/vat-bob.js
  packages/swingset-runner/demo/zoeTests/vat-carol.js
  packages/swingset-runner/demo/zoeTests/vat-dave.js
  packages/swingset-runner/package.json
  packages/vats/package.json
  packages/vats/src/bootstrap.js
  packages/web-components/test/agoric-wallet-connection.test.js
  packages/zoe/package.json
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/test/swingsetTests/zoe/vat-bob.js
  packages/zoe/test/swingsetTests/zoe/vat-carol.js
  packages/zoe/test/swingsetTests/zoe/vat-dave.js
  packages/zoe/test/unitTests/contracts/test-coveredCall-want-pattern.js
  packages/zoe/test/unitTests/contracts/test-coveredCall.js
Labels: automerge:squash

#4262 use CopySets directly for set-valued amounts
  packages/ERTP/src/amountMath.js
  packages/ERTP/src/mathHelpers/copySetMathHelpers.js
  packages/ERTP/src/mathHelpers/setMathHelpers.js
  packages/ERTP/src/typeGuards.js
  packages/ERTP/src/types.js
  packages/ERTP/test/unitTests/mathHelpers/test-copySetMathHelpers.js
  packages/ERTP/test/unitTests/mathHelpers/test-natMathHelpers.js
  packages/ERTP/test/unitTests/mathHelpers/test-setMathHelpers.js
  packages/ERTP/test/unitTests/mathHelpers/test-strSetMathHelpers.js
  packages/ERTP/test/unitTests/test-inputValidation.js
  packages/governance/src/shareHolders.js
  packages/marshal/index.js
  packages/marshal/src/typeGuards.js
  packages/store/src/index.js
  packages/store/src/keys/compareKeys.js
  packages/store/src/keys/copyMap.js
  packages/store/src/keys/copySet.js
  packages/store/src/keys/merge-set-operators.js
  packages/store/src/patterns/rankOrder.js
  packages/store/src/stores/store-utils.js
  packages/store/src/types.js
  packages/ui-components/src/display/display.js
  packages/wallet/api/src/internal-types.js
  packages/zoe/test/unitTests/contractSupport/test-ratio.js
  packages/zoe/test/unitTests/contracts/test-callSpread.js
  packages/zoe/test/unitTests/contracts/test-otcDesk.js
  packages/zoe/test/unitTests/setupBasicMints.js
  packages/zoe/test/unitTests/setupNonFungibleMints.js
  packages/zoe/test/unitTests/test-scriptedOracle.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: automerge:squash

#4265 chore(wallet-connection): prevent top level `yarn lint-fix` error
  packages/wallet-connection/package.json
Labels: automerge:merge

#4235 feat(cosmos): charge SwingSet deliver inbound fees
  golang/cosmos/app/ante_handler.go
  golang/cosmos/app/app.go
  golang/cosmos/app/vm_admission.go
  golang/cosmos/vm/controller.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/types/default-params.go
  golang/cosmos/x/swingset/types/expected_keepers.go
  golang/cosmos/x/swingset/types/msgs.go
  packages/cosmic-swingset/src/action-types.js
  packages/cosmic-swingset/src/block-manager.js
  packages/cosmic-swingset/src/params.js
  packages/cosmic-swingset/src/sim-params.js
Labels: cosmic-swingset, automerge:merge

#4266 Improve explanation of copyRecord guarantees.
  packages/marshal/docs/copyArray-guarantees.md
  packages/marshal/docs/copyRecord-guarantees.md
Labels: automerge:squash

#4250 Fix missing Far declarations on some iterables
  packages/store/src/keys/copyMap.js
  packages/store/src/stores/store-utils.js
  packages/store/test/test-copyMap.js
  packages/store/test/test-store.js
Labels: automerge:squash

#4267 docs: add a section on Fred for the Zoe Attacker's Guide
  packages/zoe/docs/AttackGuide.md
Labels: documentation, Zoe, security, automerge:squash

#4257 Deflake wallet-connection tests
  packages/web-components/src/AgoricWalletConnection.js
  packages/web-components/test/agoric-wallet-connection.test.js
Labels: automerge:squash, automerge:rebase

#4271 Minor adjustments from purple day1
  packages/store/src/types.js
  packages/zoe/src/typeGuards.js
Labels: automerge:squash, audit-zestival

#4273 fix(agoric-cli): use `https://github.com` instead of `git://...`
  packages/agoric-cli/src/main.js
Labels: agoric-cli, automerge:merge

#4275 Fix import file name for image
  packages/run-protocol/src/vpool-xyk-amm/constantProduct/README.md
Labels: documentation, AMM, automerge:squash

#4278 refactor: Relax internal dependencies
  packages/captp/package.json
  packages/captp/src/atomics.js
  packages/captp/src/captp.js
  packages/captp/test/traplib.js
  packages/captp/test/worker.js
  packages/eventual-send/package.json
  packages/import-bundle/package.json
  packages/import-bundle/src/index.js
  packages/import-bundle/test/test-compartment-wrapper.js
  packages/marshal/package.json
  packages/marshal/src/dot-membrane.js
  packages/marshal/src/helpers/copyArray.js
  packages/marshal/src/helpers/copyRecord.js
  packages/marshal/src/helpers/error.js
  packages/marshal/src/helpers/passStyle-helpers.js
  packages/marshal/src/helpers/remotable.js
  packages/marshal/src/helpers/tagged.js
  packages/marshal/src/make-far.js
  packages/marshal/src/makeTagged.js
  packages/marshal/src/marshal-justin.js
  packages/marshal/src/marshal-stringify.js
  packages/marshal/src/marshal.js
  packages/marshal/src/pureCopy.js
Labels: automerge:merge

#4281 Sanitise use of Cosmos helper
  packages/agoric-cli/src/cosmos.js
  packages/agoric-cli/src/helpers.js
  packages/agoric-cli/src/start.js
  packages/solo/src/init-basedir.js
Labels: agoric-cli, solo, automerge:merge

#4290 feat(agoric): implement `agoric run <script> [-- script-args...]`
  packages/agoric-cli/src/deploy.js
  packages/agoric-cli/src/main.js
Labels: agoric-cli, automerge:merge

#4289 Support `$CHAIN_BOOTSTRAP_VAT_CONFIG` and default to SwingSet params
  docs/env.md
  golang/cosmos/app/app.go
  golang/cosmos/proto/agoric/swingset/swingset.proto
  golang/cosmos/x/swingset/alias.go
  golang/cosmos/x/swingset/types/default-params.go
  golang/cosmos/x/swingset/types/genesis.pb.go
  golang/cosmos/x/swingset/types/params.go
  golang/cosmos/x/swingset/types/swingset.pb.go
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/cosmic-swingset/src/sim-params.js
Labels: cosmic-swingset, automerge:merge, agd

#4295 docs(SwingSet): update description of ACK handling to match reality
  packages/SwingSet/docs/networking.md
Labels: documentation, automerge:merge

#4309 Initial bootstrap core
  packages/run-protocol/bundles/install-on-chain.js
  packages/solo/src/start.js
  packages/vats/decentral-core-config.json
  packages/vats/src/bootstrap.js
  packages/vats/src/core/behaviors.js
  packages/vats/src/core/boot.js
  packages/vats/src/core/sim-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/test/test-extract.js
  packages/wallet/api/deploy.js
Labels: cosmic-swingset, automerge:merge

#4322 Add --wide option to kerneldump utility
  packages/swingset-runner/src/dumpstore.js
  packages/swingset-runner/src/kerneldump.js
Labels: enhancement, swingset-runner, tooling, devex, automerge:rebase

#4316 Fix seat isolation
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/test/unitTests/zcf/test-allStagedSeatsUsed.js
Labels: audit-zestival

#4269 docs: makeSubscriberKit → makeSubscriptionKit
  packages/notifier/README.md
Labels: notifier

#4328 fix: getPublicFacet accepts promise for instance
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/test/unitTests/test-zoe.js
Labels: automerge:squash

#4304 fix: minor, from purple
  packages/marshal/src/helpers/error.js
  packages/marshal/src/marshal.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/types.js
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/offer/offer.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoe.js
Labels: automerge:squash

#4338 feat(wallet-ui): use wallet backend adapter
  packages/wallet/ui/src/components/MakePurse.jsx
  packages/wallet/ui/src/components/Offer.jsx
  packages/wallet/ui/src/components/WalletConnection.jsx
  packages/wallet/ui/src/components/tests/MakePurse.test.jsx
  packages/wallet/ui/src/components/tests/Offer.test.jsx
  packages/wallet/ui/src/components/tests/WalletConnection.test.jsx
  packages/wallet/ui/src/contexts/Application.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/views/Contacts.jsx
  packages/wallet/ui/src/views/Issuers.jsx
  packages/wallet/ui/src/views/tests/Contacts.test.jsx
  packages/wallet/ui/src/views/tests/Dapps.test.jsx
  packages/wallet/ui/src/views/tests/Issuers.test.jsx
Labels: wallet, automerge:merge

#4292 fix(wallet): handle cancelled offer state
  packages/wallet/ui/src/components/Offer.jsx
  packages/wallet/ui/src/components/tests/Offer.test.jsx
Labels: automerge:squash

#4359 ci: fail build if `yarn install` changes files
  .github/workflow-templates/test-dapp.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/integration.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-dapp-card-store.yml
  .github/workflows/test-dapp-fungible-faucet.yml
  .github/workflows/test-dapp-oracle.yml
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml
  .github/workflows/test-documentation.yml
  packages/eslint-config/package.json
Labels: tooling, automerge:merge

#4357 fix: don't swallow errors that happen during delivery into a vat
  packages/SwingSet/src/kernel/liveSlots.js
Labels: bug, SwingSet, automerge:rebase

#4353 Harden args in`E(x)[method](...args)` to match SwingSet better
  packages/ERTP/test/unitTests/test-inputValidation.js
  packages/eventual-send/src/E.js
Labels: eventual-send, automerge:merge

#4367 fix(wallet): fix indefinite loading state
  packages/wallet/ui/src/contexts/Application.jsx
Labels: automerge:rebase

#4365 chore: Sync Endo versions
  packages/SwingSet/package.json
  packages/SwingSet/test/test-xsnap-store.js
  packages/agoric-cli/package.json
  packages/bundle-source/package.json
  packages/captp/package.json
  packages/eventual-send/package.json
  packages/far/package.json
  packages/governance/package.json
  packages/import-bundle/package.json
  packages/lockdown/package.json
  packages/marshal/package.json
  packages/notifier/package.json
  packages/telemetry/package.json
  packages/xsnap/package.json
  packages/xsnap/test/test-boot-lockdown.js
  packages/xsnap/test/test-err-stack.js
  packages/xsnap/test/test-gc.js
  packages/xsnap/test/test-replay.js
  packages/xsnap/test/test-xs-js.js
  packages/xsnap/test/test-xs-limits.js
  packages/xsnap/test/test-xs-perf.js
  packages/xsnap/test/test-xsnap.js
  yarn.lock
Labels: automerge:merge

#4364 `liveSlots` consensus mode and better verbosity switches
  .prettierignore
  packages/SwingSet/src/kernel/liveSlots.js
  packages/SwingSet/src/kernel/vatManager/manager-local.js
  packages/SwingSet/src/kernel/vatManager/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vatManager/supervisor-helper.js
  packages/SwingSet/src/kernel/vatManager/supervisor-nodeworker.js
  packages/SwingSet/src/kernel/vatManager/supervisor-subprocess-node.js
  packages/SwingSet/src/kernel/vatManager/supervisor-subprocess-xsnap.js
  packages/SwingSet/test/test-xsnap-store.js
  packages/agoric-cli/src/anylogger-agoric.js
  packages/agoric-cli/src/start.js
  packages/cosmic-swingset/src/anylogger-agoric.js
  packages/xsnap/lib/console-shim.js
  packages/xsnap/lib/object-inspect.js
  packages/xsnap/lib/ses-boot-debug.js
  packages/xsnap/lib/ses-boot.js
  packages/xsnap/package.json
  packages/xsnap/src/xsrepl.js
  packages/xsnap/test/test-boot-lockdown.js
  packages/xsnap/test/test-inspect.js
  yarn.lock
Labels: SwingSet, agoric-cli, automerge:merge

#4371 build(xsnap): `--show-env` prefers override vars over Git
  packages/xsnap/src/build.js
Labels: deployment, xsnap, automerge:merge

#4385 chore(swingset): re-enable all message-patterns tests
  packages/SwingSet/test/message-patterns.js
  packages/SwingSet/test/test-message-patterns.js
Labels: SwingSet, automerge:rebase

#4386 chore(swingset): fix funky use of test.log in test-promises.js
  packages/SwingSet/test/basedir-promises/bootstrap.js
Labels: SwingSet, automerge:rebase

#4388 docs(zoe): fix amount/Amount typo, duplicate MultiplyBy
  packages/zoe/src/contractSupport/types.js
Labels: automerge:squash

#4393 fix(wallet): fix offer id reference
  packages/wallet/ui/src/util/WalletBackendAdapter.js
Labels: automerge:squash

#4377 Update vault interest rate when it changes in vault factory
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/test/vaultFactory/swingsetTests/governance/bootstrap.js
  packages/run-protocol/test/vaultFactory/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/vaultFactory/swingsetTests/governance/vat-alice.js
Labels: automerge:merge

#4408 chore: rearrange device test files
  packages/SwingSet/test/devices/bootstrap-0.js
  packages/SwingSet/test/devices/bootstrap-1.js
  packages/SwingSet/test/devices/bootstrap-2.js
  packages/SwingSet/test/devices/bootstrap-3.js
  packages/SwingSet/test/devices/bootstrap-4.js
  packages/SwingSet/test/devices/device-0.js
  packages/SwingSet/test/devices/device-1.js
  packages/SwingSet/test/devices/device-2.js
  packages/SwingSet/test/devices/device-3.js
  packages/SwingSet/test/devices/test-devices.js
  packages/SwingSet/test/devices/vat-left.js
Labels: SwingSet, automerge:rebase

#4409 chore(swingset): fix typos, improve types
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
Labels: SwingSet, automerge:rebase

#4378 test(swingset): check vatstore/vatExit are present in all worker types
  packages/SwingSet/test/workers/bootstrap.js
  packages/SwingSet/test/workers/test-worker.js
  packages/SwingSet/test/workers/vat-target.js
Labels: SwingSet, automerge:rebase

#4400 refactor(SwingSet): use Ava's built-in snapshot testing
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/SwingSet/test/test-xsnap-store.js
Labels: automerge:squash

#4380 docs(swingset): update GC docs, virtual-objects are properly GCed
  packages/SwingSet/docs/garbage-collection.md
Labels: SwingSet, automerge:rebase

#4307 Improve claims about store types
  packages/store/src/keys/compareKeys.js
  packages/store/src/types.js
Labels: automerge:squash, stores

#4414 don't panic the kernel upon a device error
  packages/SwingSet/docs/devices.md
  packages/SwingSet/src/kernel/deviceManager.js
  packages/SwingSet/src/kernel/deviceSlots.js
  packages/SwingSet/src/kernel/deviceTranslator.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/kernelSyscall.js
  packages/SwingSet/src/kernel/state/deviceKeeper.js
  packages/SwingSet/src/kernel/vatManager/supervisor-helper.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/types.js
  packages/SwingSet/test/devices/bootstrap-5.js
  packages/SwingSet/test/devices/bootstrap-6.js
  packages/SwingSet/test/devices/device-5.js
  packages/SwingSet/test/devices/device-6.js
  packages/SwingSet/test/devices/test-devices.js
  packages/SwingSet/test/test-gc-kernel.js
Labels: SwingSet, automerge:merge
