Repository Agoric/agoric-sdk, pull requests merged in 2022-04, with the labels that each got.

#4982 chore(wallet): add getPublicNotifiers to WalletBridge
  packages/wallet/api/src/wallet.js
Labels: automerge:squash, automerge:rebase

#4990 ci(mergify): experiment with merge queue
  .github/workflows/mergify-test.yml
  .mergify.yml
Labels: tooling, automerge:merge

#4995 ci(mergify): check-success only works with jobs that already run
  .mergify.yml
Labels: tooling

#4987 Clear up some `NameAdmin` power access
  packages/vats/src/core/boot.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/src/nameHub.js
  packages/vats/src/types.js
  packages/vats/test/test-name-hub.js
Labels: cosmic-swingset, automerge:merge

#5005 ci(mergify): restore jobs on master push
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/deployment-test.yml
  .github/workflows/golangci-lint.yml
Labels: tooling, automerge:squash

#5003 feat: liens properly wrap clawback vesting accounts
  go.mod
  go.sum
  golang/cosmos/x/lien/genesis.go
  golang/cosmos/x/lien/genesis_test.go
  golang/cosmos/x/lien/keeper/account.go
  golang/cosmos/x/lien/keeper/keeper.go
  golang/cosmos/x/lien/keeper/keeper_test.go
  golang/cosmos/x/lien/lien_test.go
Labels: cosmic-swingset, getRUN, automerge:merge

#5011 test(run-protocol): inline golden log
  packages/run-protocol/test/swingsetTests/governance/snapshots/test-governance.js.md
  packages/run-protocol/test/swingsetTests/governance/snapshots/test-governance.js.snap
  packages/run-protocol/test/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/swingsetTests/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/run-protocol/test/swingsetTests/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/run-protocol/test/swingsetTests/vaultFactory/test-vaultFactory.js
Labels: automerge:squash

#5007 fix: implement store snapshot
  packages/SwingSet/src/liveslots/collectionManager.js
Labels: automerge:squash

#5017 fix(cosmos): make swingset key cli easier to use
  golang/cosmos/x/swingset/client/cli/query.go
Labels: automerge:rebase

#4996 feat(run-protocol): charge penalty for liquidation
  packages/governance/src/contractGovernor.js
  packages/run-protocol/src/collect.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/vaultFactory/test-liquidation.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/vats/src/core/types.js
  packages/vats/src/demoIssuers.js
  packages/zoe/src/zoeService/types.js
Labels: automerge:squash

#4962 Implement the latest version of the `defineKind` API
  packages/ERTP/src/payment.js
  packages/ERTP/src/purse.js
  packages/SwingSet/docs/virtual-objects.md
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/test/stores/test-durabilityChecks.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
  packages/SwingSet/test/virtualObjects/double-retire-import/vat-dri.js
  packages/SwingSet/test/virtualObjects/test-reachable-vrefs.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-retain-remotable.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bob.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bootstrap.js
  packages/SwingSet/test/virtualObjects/vat-representative-bootstrap.js
  packages/SwingSet/test/virtualObjects/vat-vom-gc-bob.js
  packages/SwingSet/test/virtualObjects/vat-weakcollections-alice.js
  packages/SwingSet/tools/fakeVirtualSupport.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/swingset-runner/demo/vatStore1/vat-bob.js
  packages/swingset-runner/demo/vatStore2/thingHolder.js
  packages/swingset-runner/demo/vatStore3/vat-bob.js
  packages/swingset-runner/demo/virtualObjectGC/vat-bob.js
  packages/vat-data/src/index.test-d.ts
  packages/vat-data/src/types.d.ts
  packages/vat-data/test/present.test.js
  packages/zoe/test/minimalMakeKindContract.js
  packages/zoe/test/unitTests/test-makeKind.js
  packages/zoe/test/unitTests/test-zoe-env.js
Labels: enhancement, SwingSet, automerge:rebase

#5001 test(runStake): use test driver rather than data file
  packages/run-protocol/test/runStake/runStake-test-steps.js
  packages/run-protocol/test/runStake/test-runStake.js
Labels: automerge:squash

#4949 docs(swingset): Synchronize networking docs with public docs
  packages/SwingSet/docs/networking.md
Labels: documentation, SwingSet, hygiene

#5034 chore: bump lerna to latest non-breaking
  package.json
  patches/@lerna+conventional-commits+3.18.5.dev.patch
  yarn.lock
Labels: automerge:squash

#5038 chore(run-protocol): type facets of vault
  packages/run-protocol/src/vaultFactory/vault.js
Labels: automerge:squash

#5035 chore: format package.json and document why not others
  .prettierignore
  package.json
  packages/eslint-config/package.json
  yarn.lock
Labels: automerge:squash

#5043 fix(swingset): disable metering on both initial and from-snapshot workers
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/test/test-xsnap-metering.js
Labels: SwingSet, xsnap, automerge:rebase

#5042 Core-eval governance support
  golang/cosmos/x/swingset/types/proposal_test.go
  packages/agoric-cli/tools/getting-started.js
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/scripts/clean-core-eval.js
  packages/cosmic-swingset/src/is-entrypoint.js
  packages/cosmic-swingset/test/gov-code.js
  packages/cosmic-swingset/test/test-clean-core-eval.js
  packages/deploy-script-support/package.json
  packages/deploy-script-support/src/assertOfferResult.js
  packages/deploy-script-support/src/depositInvitation.js
  packages/deploy-script-support/src/endo-pieces-contract.js
  packages/deploy-script-support/src/getBundlerMaker.js
  packages/deploy-script-support/src/helpers.js
  packages/deploy-script-support/src/install.js
  packages/deploy-script-support/src/installInPieces.js
  packages/deploy-script-support/src/offer.js
  packages/deploy-script-support/src/saveIssuer.js
  packages/deploy-script-support/src/startInstance.js
  packages/deploy-script-support/test/unitTests/test-getBundlerMaker.js
  packages/deploy-script-support/test/unitTests/test-installInPieces.js
  packages/deploy-script-support/test/unitTests/test-offer.js
  packages/deploy-script-support/test/unitTests/test-startInstance.js
  packages/vats/src/core/chain-behaviors.js
Labels: cosmic-swingset, automerge:merge

#5033 chore: bump deps
  package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/deployment/package.json
  packages/governance/package.json
  packages/pegasus/package.json
  packages/run-protocol/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  yarn.lock
Labels: automerge:squash

#5051 fix(actions): slack webhook url
  .github/workflows/after-merge.yml
Labels: automerge:rebase

#5050 fix(ui-components): dont throw on negative nat input
  packages/ui-components/src/components/NatAmountInput.jsx
  packages/ui-components/test/components/test-NatAmountInput.js
Labels: automerge:squash

#4767 Rework `xsnap/src/object-inspect.js`
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/xsnap/lib/confined-object-inspect.js
  packages/xsnap/lib/console-shim.js
  packages/xsnap/lib/object-inspect.js
  packages/xsnap/lib/ses-boot-debug.js
  packages/xsnap/lib/ses-boot.js
  packages/xsnap/package.json
  packages/xsnap/rollup.config.js
  packages/xsnap/src/object-inspect.js
  packages/xsnap/test/test-inspect.js
  yarn.lock
Labels: xsnap, automerge:merge

#5057 ci: fix coverage job
  yarn.lock
Labels: automerge:rebase

#5059 Virtualize weak store GC tables
  packages/SwingSet/src/lib/parseVatSlots.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/vatstore-usage.md
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
Labels: bug, SwingSet, automerge:rebase, stores

#5086 chore(vat-data): fix and test defineKind types
  packages/vat-data/package.json
  packages/vat-data/src/index.test-d.ts
  packages/vat-data/src/types.d.ts
  yarn.lock
Labels: automerge:squash

#5008 fix: Make payments recoverable
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/src/types.js
  packages/ERTP/test/unitTests/test-recovery.js
  packages/vats/src/virtual-purse.js
Labels: ERTP, automerge:merge

#5028 refactor(run-protocol): broaden scope of collateral reserve to assets generally
  packages/run-protocol/scripts/build-bundles.js
  packages/run-protocol/src/reserve/assetReserve.js
  packages/run-protocol/test/reserve/setup.js
Labels: automerge:squash

#5055 fix(swingset): track doMoreGC correctly
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/virtualObjects/collection-slots/bootstrap-collection-slots.js
  packages/SwingSet/test/virtualObjects/collection-slots/test-collection-slots.js
  packages/SwingSet/test/virtualObjects/collection-slots/vat-collection-slots.js
  packages/SwingSet/test/virtualObjects/delete-stored-vo/bootstrap-delete-stored-vo.js
  packages/SwingSet/test/virtualObjects/delete-stored-vo/test-delete-stored-vo.js
  packages/SwingSet/test/virtualObjects/delete-stored-vo/vat-delete-stored-vo.js
Labels: SwingSet, automerge:rebase

#5088 chore: weaken swingset dependency on vat-data to dev-dependency
  packages/SwingSet/package.json
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/virtualObjects/collection-slots/test-collection-slots.js
  packages/SwingSet/test/virtualObjects/delete-stored-vo/test-delete-stored-vo.js
  packages/SwingSet/test/virtualObjects/double-retire-import/test-double-retire-import.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-weakcollections.js
Labels: SwingSet, automerge:rebase

#5056 fix(swingset): abandon/delete most non-durables during stopVat()
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/stop-vat.js
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/num-sensors.js
  packages/SwingSet/test/upgrade/object-graph.pdf
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
Labels: SwingSet, automerge:rebase

#4999 feat(priceAggregator): `deleteOracle` and `getRoundCompleteNotifier`
  packages/agoric-cli/src/deploy.js
  packages/deploy-script-support/src/endo-pieces-contract.js
  packages/deploy-script-support/src/installInPieces.js
  packages/solo/src/scratch.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
Labels: automerge:merge, oracle

#5094 feat(run-protocol): expose wrapLienedAmount on attestationTool
  packages/run-protocol/src/runStake/attestation.js
Labels: automerge:rebase

#5091 fix!: fix a bug in addLiquidity
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-liquidity.js
Labels: bug, RUN-protocol, AMM, automerge:squash

#5052 refactor(run-protocol): virtual kind for vault manager
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/vaultFactory/vault-contract-wrapper.js
Labels: automerge:squash

#5097 Split single- and multi-faceted VO definitions into their own functions
  packages/ERTP/src/purse.js
  packages/SwingSet/docs/virtual-objects.md
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bob.js
  packages/SwingSet/tools/fakeVirtualObjectManager.js
  packages/SwingSet/tools/prepare-test-env.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/vat-data/src/index.js
  packages/vat-data/src/index.test-d.ts
  packages/vat-data/src/types.d.ts
  packages/zoe/test/minimalMakeKindContract.js
  packages/zoe/test/unitTests/test-makeKind.js
  packages/zoe/test/unitTests/test-zoe-env.js
Labels: enhancement, SwingSet, automerge:rebase

#5098 Support private `offerArgs` in `offerTo` helper
  packages/zoe/src/contractSupport/zoeHelpers.js
Labels: automerge:squash

#5102 chore(docs): update naming
  docs/threat_models/README.md
  docs/threat_models/pegasus/pegasus_component.svg
  docs/threat_models/pegasus/pegasus_sequence.svg
  docs/threat_models/smart_contracts/amm/amm_component.puml
  docs/threat_models/smart_contracts/amm/amm_component.svg
  docs/threat_models/smart_contracts/amm/amm_sequence.puml
  docs/threat_models/smart_contracts/amm/amm_sequence.svg
  docs/threat_models/smart_contracts/amm/amm_sequence_001.svg
  docs/threat_models/smart_contracts/amm/amm_sequence_002.svg
  docs/threat_models/smart_contracts/amm/amm_sequence_003.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_component.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_001.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_002.svg
  docs/threat_models/smart_contracts/multipool_autoswap/mpas_sequence_003.svg
  docs/threat_models/vaultFactory/VaultFactory.svg
Labels: automerge:rebase

#5101 refactor(vault): liquidate with offerArgs
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
Labels: automerge:squash

#5105 refactor(run-protocol): virtual kind for vault manager
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/vaultFactory/vault-contract-wrapper.js
Labels: automerge:squash

#5109 refactor(run-protocol): extract vaultDirector kind from vaultFactory contract
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
Labels: automerge:squash

#5104 chore: Sync Endo versions
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/run-protocol/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/ui/package.json
  packages/web-components/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zoe/tools/scriptedOracle.js
  yarn.lock
Labels: automerge:rebase

#5103 Vault test refactor
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/makeTracer.js
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/psm/test-psm.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/supports.js
  packages/run-protocol/test/vaultFactory/test-bootstrapPayment.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/src/contractFacet/internal-types.js
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contractFacet/vatRoot.js
  packages/zoe/tools/manualPriceAuthority.js
Labels: automerge:merge

#5063 refactor!: atomically update multiple parameters via governance
  packages/governance/README.md
  packages/governance/src/contractGovernance/governParam.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/index.js
  packages/governance/src/question.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/governance/test/swingsetTests/contractGovernor/vat-voter.js
  packages/governance/test/unitTests/test-ballotCount.js
  packages/governance/test/unitTests/test-buildParamManager.js
  packages/governance/test/unitTests/test-paramChangePositions.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/swingsetTests/governance/bootstrap.js
  packages/run-protocol/test/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/swingsetTests/governance/vat-voter.js
  packages/run-protocol/test/swingsetTests/setup.js
Labels: enhancement, Governance, automerge:squash

#5118 chore: Sync Endo versions
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/run-protocol/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/ui/package.json
  packages/web-components/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  yarn.lock
Labels: automerge:merge

#5117 fix: update types to specify ERef<Issuer> on addPool()
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
  packages/vats/src/demoIssuers.js
Labels: bug, devex, AMM, automerge:merge

#5122 fix(run-protocol): store Presences, not Promises, in VaultManager
  packages/run-protocol/src/econ-behaviors.js
Labels: RUN-protocol, automerge:rebase

#5120 fix(swingset): only ceaseRecognition facets on virtual objects
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/test/virtualObjects/test-cease-recognition.js
Labels: SwingSet, automerge:rebase

#5136 fix(run-protocol): use wallet-friendly offer result notifiers
  packages/run-protocol/src/runStake/runStakeKit.js
Labels: automerge:rebase

#4989 chore: gitignore output (build, bundles, compiled, dist, _agstate)
  .gitignore
  packages/SwingSet/test/bundles/.gitignore
Labels: automerge:squash

#5137 chore: rename 'bundles' dir that wasn't build output
  packages/SwingSet/test/bundles/.gitignore
  packages/SwingSet/test/bundling/bootstrap-bundles.js
  packages/SwingSet/test/bundling/nonvat-importable.js
  packages/SwingSet/test/bundling/nonvat-install.js
  packages/SwingSet/test/bundling/test-bundles-controller.js
  packages/SwingSet/test/bundling/test-bundles-kernel.js
  packages/SwingSet/test/bundling/test-bundles.js
  packages/SwingSet/test/bundling/vat-disk.js
  packages/SwingSet/test/bundling/vat-install.js
  packages/SwingSet/test/bundling/vat-named.js
Labels: automerge:squash

#4888 fix(run-protocol): addVaultType with invalid args modified state
  packages/run-protocol/src/contractSupport.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: automerge:rebase

#5147 fix(attestation): handle return of empty attestation
  packages/run-protocol/src/runStake/attestation.js
  packages/run-protocol/test/attestation/test-attestation.js
Labels: automerge:rebase

#5148 style(run-protocol): @jessie-check for runStake
  packages/run-protocol/src/runStake/attestation.js
  packages/run-protocol/src/runStake/params.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/runStake/runStakeKit.js
  packages/run-protocol/src/runStake/runStakeManager.js
Labels: Zoe, Zoe Contract, RUN-protocol, automerge:rebase

#5149 fix(run-protocol): vault debt ratio ordering after interest charges
  packages/run-protocol/src/vaultFactory/orderedVaultStore.js
  packages/run-protocol/src/vaultFactory/prioritizedVaults.js
  packages/run-protocol/test/supports.js
  packages/run-protocol/test/vaultFactory/interestSupport.js
  packages/run-protocol/test/vaultFactory/test-orderedVaultStore.js
  packages/run-protocol/test/vaultFactory/test-prioritizedVaults.js
Labels: automerge:squash

#5159 fix: repair types left as <any>
  packages/governance/src/contractGovernance/governParam.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
Labels: bug, hygiene, Governance, automerge:squash

#5150 chore(vat-data): improve type definitions
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/vat-data/src/index.test-d.ts
  packages/vat-data/src/types.d.ts
Labels: automerge:squash

#5158 feat(dockerfile): include otel collector
  packages/deployment/Dockerfile.sdk
Labels: automerge:rebase

#5116 refactor(run-protocol): vaultDirector to multifacted vobj
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/governance/test/swingsetTests/contractGovernor/vat-voter.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vpool-xyk-amm/doublePool.js
  packages/run-protocol/test/swingsetTests/governance/bootstrap.js
  packages/run-protocol/test/swingsetTests/governance/vat-voter.js
  packages/vat-data/src/types.d.ts
Labels: automerge:squash

#5125 feat(amm): support `maxOut` optional arg to `swap`
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vpool-xyk-amm/doublePool.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/singlePool.js
  packages/run-protocol/src/vpool-xyk-amm/swap.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-xyk-amm-swap.js
Labels: automerge:squash

#5163 fix: hotfix for @endo/init#1166
  patches/@endo+init+0.5.41.patch
Labels: automerge:squash

#5162 ci: eslint and fix .ts files
  golang/cosmos/package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/access-token/package.json
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/run-protocol/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/solo/package.json
  packages/sparse-ints/package.json
  packages/spawner/package.json
  packages/stat-logger/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/ui/package.json
  packages/zoe/package.json
Labels: automerge:squash

#5161 refactor(run-protocol): DRY checkDebtLimit
  packages/run-protocol/src/contractSupport.js
  packages/run-protocol/src/runStake/runStakeManager.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
Labels: automerge:squash

#5126 test(governance): fix some async validation
  packages/governance/src/contractGovernor.js
  packages/governance/src/types.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/run-protocol/test/swingsetTests/governance/vat-voter.js
Labels: automerge:squash

#5135 feat(run-protocol): convert RunStakeManager to vobj
  packages/run-protocol/src/runStake/attestation.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/runStake/runStakeManager.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
Labels: automerge:squash

#5168 refactor(run-protocol): RunStakeKit facets for vobj
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/runStake/runStakeKit.js
Labels: automerge:squash

#5144 feat: cli for sending Wallet{Spend}Action transactions
  golang/cosmos/x/swingset/client/cli/tx.go
  golang/cosmos/x/swingset/types/msgs.go
  golang/cosmos/x/swingset/types/msgs_test.go
Labels: enhancement, cosmic-swingset, wallet, automerge:merge

#5174 chore: remove noActionElectorate from uiConfig
  packages/run-protocol/src/core-proposal.js
  packages/run-protocol/src/econ-behaviors.js
Labels: automerge:merge

#5173 refactor(run-protocol): vault title vobj
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultKit.js
  packages/run-protocol/src/vaultFactory/vaultTitle.js
Labels: automerge:squash

#5178 ci(docker): parallel multiarch manifests
  .github/workflows/docker.yml
Labels: tooling, automerge:merge

#5177 chore: clean up eslintignores
  packages/SwingSet/.eslintignore
  packages/SwingSet/misc-tools/db-dump.js
  packages/SwingSet/misc-tools/measure-metering/measure.js
  packages/SwingSet/misc-tools/vat-stats.js
  packages/SwingSet/test/bundling/test-bundles.js
  packages/access-token/.eslintignore
  packages/agoric-cli/.eslintignore
  packages/deployment/.eslintignore
  packages/stat-logger/.eslintignore
  packages/swing-store/.eslintignore
Labels: automerge:squash

#5171 refactor(run-protocol): convert runStakeKit to vobj
  packages/run-protocol/src/runStake/attestation.js
  packages/run-protocol/src/runStake/constants.js
  packages/run-protocol/src/runStake/params.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/runStake/runStakeKit.js
  packages/run-protocol/src/runStake/runStakeManager.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/vat-data/src/types.d.ts
Labels: automerge:squash

#5164 feat(swingset-vat): Include alleged bundleID in checkBundle diagnostics
  packages/SwingSet/src/controller/controller.js
Labels: automerge:rebase

#5186 refactor(run-protocol): AttestationTool vobj
  packages/run-protocol/src/runStake/attestation.js
  packages/run-protocol/src/runStake/attestationTool.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/src/runStake/types.js
Labels: automerge:squash

#5188 fix(ci): use a stable docker snapshot-tag
  .github/workflows/docker.yml
Labels: automerge:squash

#5130 Implement durable promise watchers
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/lib/parseVatSlots.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/liveslots/watchedPromises.js
  packages/SwingSet/test/promise-watcher/bootstrap-promise-watcher.js
  packages/SwingSet/test/promise-watcher/test-promise-watcher.js
  packages/SwingSet/test/promise-watcher/unhandledRejectionDetector.js
  packages/SwingSet/test/promise-watcher/vat-upton.js
  packages/SwingSet/test/stores/test-storeGC.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/tools/fakeVirtualSupport.js
  packages/SwingSet/tools/prepare-test-env.js
  packages/vat-data/src/index.js
  packages/vat-data/src/types.d.ts
Labels: enhancement, SwingSet, automerge:rebase

#5165 RUN protocol governance to start PSM, runStake, etc.
  packages/agoric-cli/src/deploy.js
  packages/cosmic-swingset/Makefile
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/endo-pieces-contract.js
  packages/deploy-script-support/src/installInPieces.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/deploy-script-support/test/unitTests/test-installInPieces.js
  packages/run-protocol/package.json
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/src/core-proposal.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/my-lien.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
Labels: automerge:merge

#5143 fix: Correct a dead link for package @agoric/cosmos
  golang/cosmos/package.json
Labels: documentation, automerge:squash, agoric-cosmos

#5191 real governance for PSM
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/run-protocol/src/psm/psm.js
  packages/run-protocol/test/psm/test-psm.js
Labels: automerge:merge

#5192 Add swing store trace option
  packages/SwingSet/src/controller/hostStorage.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/deployment/scripts/capture-integration-results.sh
  packages/deployment/scripts/integration-test.sh
  packages/swing-store/src/swingStore.js
Labels: automerge:rebase

#5187 feat: virtualize pools for the AMM.
  packages/SwingSet/docs/virtual-objects.md
  packages/run-protocol/src/vaultFactory/vaultKit.js
  packages/run-protocol/src/vpool-xyk-amm/addLiquidity.js
  packages/run-protocol/src/vpool-xyk-amm/addPool.js
  packages/run-protocol/src/vpool-xyk-amm/doublePool.js
  packages/run-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/run-protocol/src/vpool-xyk-amm/pool.js
  packages/run-protocol/src/vpool-xyk-amm/singlePool.js
  packages/run-protocol/src/vpool-xyk-amm/swap.js
  packages/run-protocol/src/vpool-xyk-amm/types.js
Labels: RUN-protocol, AMM, automerge:squash, contract-upgrade

#5197 feat(run-protocol): collect runStake fees
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/runStake/runStake.js
  packages/run-protocol/test/runStake/test-runStake.js
Labels: automerge:squash

#5199 fix(bundleTool): don't ignore module path in metadata check
  packages/run-protocol/test/bundleTool.js
Labels: tooling, hygiene, automerge:squash

#5129 feat(vault): Liquidate incrementally
  packages/governance/src/contractGovernance/assertions.js
  packages/run-protocol/src/collect.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/makeTracer.js
  packages/run-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/params.js
  packages/run-protocol/src/vaultFactory/prioritizedVaults.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultFactory.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/src/vpool-xyk-amm/swap.js
  packages/run-protocol/test/swingsetTests/setup.js
  packages/run-protocol/test/vaultFactory/faucet.js
  packages/run-protocol/test/vaultFactory/test-liquidation-helpers.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/zoe/src/contractSupport/priceAuthority.js
Labels: automerge:squash

#5208 refactor: change notification of param changes to be once per set
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
Labels: hygiene, Governance, automerge:merge

#5211 feat(vault): governance upgrade of liquidation
  packages/SwingSet/misc-tools/vat-map.py
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/run-protocol/src/vaultFactory/liquidateMinimum.js
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vaultDirector.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/supports.js
  packages/run-protocol/test/swingsetTests/governance/test-governance.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
Labels: automerge:squash

#5205 fix(run-protocol): restore wrapLienedAmount on AttestationTool
  packages/run-protocol/src/runStake/attestationTool.js
  packages/run-protocol/test/runStake/test-runStake.js
Labels: automerge:merge

#5124 Restrict promise redirect
  packages/SwingSet/docs/comms.md
  packages/SwingSet/docs/delivery.md
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/lib/capdata.js
  packages/SwingSet/src/vats/comms/clist-inbound.js
  packages/SwingSet/src/vats/comms/delivery.js
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/SwingSet/test/test-comms.js
  packages/SwingSet/test/test-kernel.js
  packages/SwingSet/test/test-vpid-kernel.js
  packages/SwingSet/test/test-vpid-liveslots.js
  patches/@endo+eventual-send+0.15.3.patch
Labels: automerge:rebase

#5190 Price feed fixes
  packages/cosmic-swingset/src/chain-main.js
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
  packages/deployment/scripts/integration-test.sh
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contractSupport/priceAuthorityTransform.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
  packages/zoe/src/contracts/scaledPriceAuthority.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/contracts/test-priceAggregatorChainlink.js
  packages/zoe/test/unitTests/contracts/test-scaledPriceAuthority.js
  packages/zoe/tools/types.js
Labels: cosmic-swingset, deployment, tooling, Zoe Contract, automerge:merge

#5213 fix(run-protocol): complete permits for startRewardDistributor, makeAnchorAsset
  packages/run-protocol/src/core-proposal.js
Labels: automerge:squash

#5221 fix(deployment): default `faucet-helper.sh` to `show-rpcaddrs`
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
Labels: deployment, automerge:merge

#5215 feat(run-protocol): preview launch support, PSM work-around
  packages/run-protocol/Makefile
  packages/run-protocol/docs/run-protocol-preview.md
  packages/run-protocol/package.json
  packages/run-protocol/scripts/deploy-contracts.js
  packages/run-protocol/scripts/gov-startPSM-permit.json
  packages/run-protocol/scripts/gov-startPSM.js
  packages/run-protocol/scripts/init-core.js
  packages/run-protocol/src/core-proposal.js
  packages/run-protocol/src/econ-behaviors.js
  packages/run-protocol/src/psm/startPSM.js
  packages/run-protocol/src/psm/writePsmScript.js
  packages/run-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/run-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/run-protocol/test/runStake/test-runStake.js
  packages/run-protocol/test/vaultFactory/test-liquidator.js
  packages/run-protocol/test/vaultFactory/test-vaultFactory.js
  packages/vats/src/mintHolder.js
Labels: automerge:merge

#5225 fix: fix types of stopAcceptingOffers
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/zoeService/startInstance.js
Labels: automerge:squash

#5231 fix(extract-proposal): make results deterministic
  packages/cosmic-swingset/src/extract-proposal.js
Labels: cosmic-swingset, automerge:merge

#5234 refactor(ertp): makePaymentMaker → definePaymentKind
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
Labels: automerge:squash

#5236 chore: drop no-longer-needed deeplyFulfilled
  packages/governance/src/contractGovernance/paramManager.js
Labels: hygiene, Governance, automerge:squash

#5228 Add more deployment tracing
  .gitignore
  packages/SwingSet/src/controller/controller.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/deployment/scripts/capture-integration-results.sh
  packages/deployment/scripts/integration-test.sh
  packages/deployment/src/main.js
  packages/solo/src/start.js
  packages/swing-store/src/swingStore.js
  scripts/run-deployment-integration.sh
Labels: automerge:rebase

#5193 ci: Prototype of run integration tests before merge
  .github/workflows/mergify-test.yml
  .github/workflows/pre-check-integration.yml
Labels: tooling, automerge:squash

#5240 ci(docker): tolerate unordered arches in create manifest
  .github/workflows/docker.yml
Labels: tooling, automerge:merge

#5207 First pass at VO and DVO test harnesses
  packages/SwingSet/test/liveslots-helpers.js
  packages/SwingSet/test/vo-test-harness/test-dvo-test-harness.js
  packages/SwingSet/test/vo-test-harness/test-vo-test-harness.js
  packages/SwingSet/test/vo-test-harness/vat-dvo-test-test.js
  packages/SwingSet/tools/bootstrap-dvo-test.js
  packages/SwingSet/tools/vo-test-harness.js
Labels: enhancement, SwingSet, tooling, automerge:rebase

#5232 chore(swingset-vat): declare deps of testing tools
  packages/SwingSet/package.json
  packages/SwingSet/tools/prepare-test-env-ava.js
Labels: automerge:rebase

#5181 simplify inner/outer vault naming
  packages/run-protocol/src/vaultFactory/liquidation.js
  packages/run-protocol/src/vaultFactory/orderedVaultStore.js
  packages/run-protocol/src/vaultFactory/prioritizedVaults.js
  packages/run-protocol/src/vaultFactory/types.js
  packages/run-protocol/src/vaultFactory/vault.js
  packages/run-protocol/src/vaultFactory/vaultKit.js
  packages/run-protocol/src/vaultFactory/vaultManager.js
  packages/run-protocol/src/vaultFactory/vaultTitle.js
  packages/run-protocol/test/vaultFactory/interestSupport.js
  packages/run-protocol/test/vaultFactory/test-orderedVaultStore.js
  packages/run-protocol/test/vaultFactory/test-prioritizedVaults.js
  packages/run-protocol/test/vaultFactory/vault-contract-wrapper.js
Labels: automerge:merge

#5224 test: a virtual object test for AMM pools.
  packages/run-protocol/test/test-voPool.js
Labels: tooling, test, AMM, automerge:squash, contract-upgrade

#5233 bankers rounding
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/src/contractSupport/safeMath.js
  packages/zoe/test/unitTests/contractSupport/test-ratio.js
Labels: automerge:merge

#5248 fix: conform to Agoric arrow-only function style
  packages/SwingSet/test/upgrade/bootstrap-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
Labels: automerge:rebase

#5250 feat(swingset): allow buildRootObject to return a Promise
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
  packages/SwingSet/test/vat-admin/broken-hang-vat.js
  packages/SwingSet/test/vat-admin/new-vat-13.js
  packages/SwingSet/test/vat-admin/test-create-vat.js
Labels: SwingSet, automerge:rebase

#5254 ci: integration tests before merge
  .github/actions/restore-golang/action.yml
  .github/workflows/deployment-test.yml
  .github/workflows/integration.yml
  .github/workflows/mergify-test.yml
  .github/workflows/pre-check-integration.yml
  .github/workflows/test-all-packages.yml
  CONTRIBUTING.md
  packages/deployment/scripts/install-deps.sh
Labels: automerge:rebase, force:integration

#5256 ci: improve test parallelism
  .github/actions/build-node/action.yml
  .github/workflows/deployment-test.yml
  .github/workflows/proto.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-dapp-card-store.yml
  .github/workflows/test-dapp-fungible-faucet.yml
  .github/workflows/test-dapp-oracle.yml
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml
  .github/workflows/test-documentation.yml
  .github/workflows/test-golang.yml
  scripts/check-untested-packages.mjs
Labels: automerge:rebase

#5264 Ratios for `priceAggregator`
  packages/spawner/src/vat-spawned.js
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/src/contractSupport/statistics.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/priceAggregatorChainlink.js
  packages/zoe/src/contracts/priceAggregatorTypes.js
  packages/zoe/src/types.js
  packages/zoe/test/unitTests/contractSupport/test-ratio.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
Labels: spawner, Zoe Contract, automerge:merge, oracle
