Repository Agoric/agoric-sdk, pull requests merged in 2022-09, with the labels that each got.

#6101 feat: save PSM adminFacet in bootstrap
  packages/governance/src/contractGovernor.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/zoeService/utils.d.ts
Labels: Inter-protocol, automerge:squash, pso

#6090 feat: charter for the PSM, enabling governance
  packages/governance/src/types.js
  packages/inter-protocol/src/psm/psmCharter.js
  packages/inter-protocol/test/psm/test-governedPsm.js
Labels: Inter-protocol, Governance, automerge:squash, pso

#5900 test(vaultFactory): refactor to macro
  packages/SwingSet/package.json
  packages/inter-protocol/test/test-interest-math.js
  packages/inter-protocol/test/vaultFactory/test-storeUtils.js
Labels: automerge:rebase, bypass:integration

#6102 fix(inter-protocol): ensure PSM availability after staging failure
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/zoe/src/contractFacet/zcfSeat.js
Labels: automerge:merge, bypass:integration

#6122 refactorings for new smart-wallet
  packages/ERTP/package.json
  packages/ERTP/src/types.js
  packages/SwingSet/src/devices/bridge/device-bridge.js
  packages/inter-protocol/README.md
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/psm/psm.js
  packages/internal/src/utils.js
  packages/vats/src/bridge.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/boot.js
  packages/vats/src/vat-chainStorage.js
  packages/vats/test/test-boot.js
  packages/vats/test/test-vat-bank.js
  packages/vats/tools/boot-test-utils.js
  packages/zoe/src/zoeService/types.js
Labels: automerge:rebase, bypass:integration

#5660 fix(agoric-cli): Thread rpcAddresses for Cosmos publishBundle
  packages/agoric-cli/src/deploy.js
  packages/agoric-cli/src/publish.js
Labels: automerge:rebase

#5960 fix: far classes with interface guards, used by ERTP
  packages/ERTP/src/interfaces.js
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/src/typeGuards.js
  packages/ERTP/src/types.js
  packages/ERTP/test/unitTests/test-inputValidation.js
  packages/ERTP/test/unitTests/test-issuerObj.js
  packages/ERTP/test/unitTests/test-mintObj.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/liveslots/watchedPromises.js
  packages/SwingSet/test/promise-watcher/vat-upton.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
  packages/SwingSet/test/virtualObjects/test-reachable-vrefs.js
  packages/SwingSet/test/virtualObjects/test-retain-remotable.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bob.js
  packages/assert/src/assert.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/store/src/index.js
  packages/store/src/keys/checkKey.js
  packages/store/src/patterns/interface-tools.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
  packages/store/test/test-patterns.js
  packages/vat-data/src/far-class-utils.js
  packages/vat-data/src/index.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/types.d.ts
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/makeHandle.js
  packages/zoe/src/zoeService/feeMint.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/test/unitTests/contracts/loan/helpers.js
Labels: automerge:squash

#6120 fix: convert upgradable covered call to far classes
  packages/zoe/src/typeGuards.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/coveredCall-durable-V3.js
Labels: automerge:squash

#6107 fix: heap far classes
  packages/store/src/index.js
  packages/store/src/patterns/interface-tools.js
  packages/store/test/test-heap-classes.js
  packages/vat-data/test/test-durable-classes.js
  packages/vat-data/test/test-virtual-classes.js
  packages/vat-data/test/test-vivify.js
Labels: automerge:squash

#6133 ps0 wallet ui
  packages/wallet/ui/README.md
  packages/wallet/ui/src/components/ConnectionSettingsDialog.jsx
  packages/wallet/ui/src/components/NavMenu.jsx
  packages/wallet/ui/src/components/Purses.jsx
  packages/wallet/ui/src/components/Transfer.jsx
  packages/wallet/ui/src/components/tests/Purses.test.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/util/connections.js
Labels: automerge:merge

#6136 fix(SwingSet): liveslots and supervisor errors to console.warn
  packages/SwingSet/src/liveslots/liveslots.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
Labels: automerge:squash

#6119 feat(psm): far class and guard patterns
  packages/governance/src/contractHelper.js
  packages/governance/src/index.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/vats/src/mintHolder.js
Labels: automerge:squash

#6137 fix(scripts): Remove a typo
  scripts/get-flattened-publication.sh
Labels: automerge:rebase

#6140 test(store): misc tests for record with optional fields
  packages/store/test/test-patterns.js
Labels: automerge:rebase

#6128 refactorings to support new smart wallet
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/committee.js
  packages/governance/src/types.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/vats/scripts/build-bundles.js
  packages/vats/src/core/types.js
  packages/vats/test/devices.js
  packages/wallet/api/src/marshal-contexts.js
  packages/wallet/contract/test/devices.js
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
Labels: automerge:rebase

#6057 fix: patterns impose resource limits
  packages/SwingSet/test/gc-helpers.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/store/src/patterns/internal-types.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
  packages/store/test/test-pattern-limits.js
  packages/store/test/test-patterns.js
  packages/zoe/test/unitTests/test-cleanProposal.js
Labels: automerge:squash

#6145 refactor(psm): rename "stable" to "minted" for PSM
  packages/inter-protocol/docs/governance-params.md
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/test/psm/test-governedPsm.js
  packages/inter-protocol/test/psm/test-psm.js
Labels: automerge:squash

#6146 feat: make PSM bootstrap support multiple brands
  packages/ERTP/package.json
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/vats/src/core/boot-psm.js
  packages/vats/test/test-boot.js
Labels: automerge:squash, pso

#6114 refactor: method schemas in Governance contracts
  packages/governance/package.json
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/committee.js
  packages/governance/src/contractGovernance/governParam.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/index.js
  packages/governance/src/noActionElectorate.js
  packages/governance/src/question.js
  packages/governance/src/typeGuards.js
  packages/governance/src/types.js
  packages/governance/test/unitTests/test-ballotBuilder.js
  packages/governance/test/unitTests/test-ballotCount.js
  packages/zoe/src/typeGuards.js
  packages/zoe/test/unitTests/test-cleanProposal.js
Labels: Governance, automerge:squash

#6155 fix(smart-wallet): invitation issuer is remote
  packages/smart-wallet/src/walletFactory.js
Labels: wallet, automerge:squash, pso

#6142 feat(vats): facilitate launching additional PSMs
  packages/inter-protocol/scripts/build-bundles.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startEconCommittee.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psmCharter.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/test-amm-governance.js
  packages/inter-protocol/test/psm/gov-add-psm-permit.json
  packages/inter-protocol/test/psm/gov-add-psm.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/smart-wallet/test/test-psm-integration.js
  packages/vats/decentral-psm-config.json
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/test/devices.js
  packages/vats/test/test-boot.js
Labels: automerge:merge

#6124 feat: charge fee based on bundle size
  golang/cosmos/x/swingset/types/msgs.go
Labels: enhancement, cosmic-swingset, metering, automerge:rebase

#5541 fix(cosmic-swingset): Publish installation success and failure topic
  golang/cosmos/x/swingset/keeper/keeper.go
  packages/agoric-cli/src/publish.js
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/block-manager.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/solo/src/start.js
  packages/vats/src/chain-storage-paths.js
Labels: automerge:rebase

#6048 chore: update to match gaia 7.0.2
  go.mod
  go.sum
  golang/cosmos/Makefile
  golang/cosmos/agoric/config.go
  golang/cosmos/ante/ante.go
  golang/cosmos/ante/expected_keepers.go
  golang/cosmos/ante/fee.go
  golang/cosmos/ante/vm_admission.go
  golang/cosmos/app/app.go
  golang/cosmos/app/sim_test.go
  golang/cosmos/daemon/cmd/testnet.go
  golang/cosmos/daemon/main.go
  golang/cosmos/third_party/proto/ibc/core/channel/v1/channel.proto
  golang/cosmos/third_party/proto/ibc/core/client/v1/client.proto
  golang/cosmos/x/vibc/ibc.go
  golang/cosmos/x/vibc/keeper/keeper.go
  golang/cosmos/x/vibc/module.go
  golang/cosmos/x/vibc/types/expected_keepers.go
  golang/cosmos/x/vibc/types/msgs.go
  golang/cosmos/x/vibc/types/msgs.pb.go
  packages/agoric-cli/src/chain-config.js
  packages/deployment/ansible/roles/init-cosmos/tasks/main.yml
  packages/deployment/ansible/roles/unsafe_reset/tasks/main.yml
Labels: automerge:rebase, agd, agoric-cosmos, proto:expect-breakage, MUST-HAVE, pso

#6153 6062 wallet patterns
  packages/smart-wallet/package.json
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/typeGuards.js
  packages/smart-wallet/src/types.d.ts
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/test-psm-integration.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/wallet/api/src/marshal-contexts.js
  packages/wallet/api/test/test-wallet-marshal.js
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/typeGuards.js
Labels: automerge:merge

#6161 fix(vats): Mark bootstrap vats as critical
  packages/inter-protocol/test/test-gov-collateral.js
  packages/smart-wallet/test/supports.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-psm-config.json
  packages/vats/src/authorityViz.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/types.js
  packages/vats/test/test-boot.js
  packages/vats/test/test-clientBundle.js
  packages/vats/test/test-vat-bank.js
  packages/vats/tools/boot-test-utils.js
  packages/wallet/contract/test/supports.js
Labels: enhancement, cosmic-swingset, automerge:rebase

#6166 feat: distribute PSM Charter Invitatitons
  packages/inter-protocol/src/proposals/startPSM.js
  packages/smart-wallet/test/test-psm-integration.js
  packages/vats/src/core/boot-psm.js
  packages/vats/test/test-boot.js
Labels: enhancement, Inter-protocol, automerge:squash, pso

#6159 chore(web-components): fix devDependencies
  packages/web-components/package.json
Labels: automerge:squash

#6093 Provision charge
  golang/cosmos/proto/agoric/swingset/swingset.proto
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/keeper_test.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/types/default-params.go
  golang/cosmos/x/swingset/types/params.go
  golang/cosmos/x/swingset/types/swingset.pb.go
  packages/cosmic-swingset/src/sim-params.js
Labels: automerge:rebase

#6162 chore(smart-wallet): take out limitation against spending
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/test/test-walletFactory.js
Labels: automerge:rebase

#6170 fix(vats): economicCommitteeAddresses {} update
  packages/vats/decentral-psm-config.json
Labels: automerge:rebase, bypass:integration

#6165 4489 walletFactory virtual
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/test-psm-integration.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/store/src/patterns/interface-tools.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
  packages/store/test/test-heap-classes.js
  packages/vat-data/src/types.d.ts
Labels: automerge:merge, bypass:integration

#6158 fix: Make pattern matching faster
  packages/ERTP/src/typeGuards.js
  packages/store/src/keys/checkKey.js
  packages/store/src/patterns/interface-tools.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/test/borrow-guards.js
  packages/store/test/perf-patterns.js
  packages/store/test/test-patterns.js
Labels: automerge:squash

#6172 feat(smartWallet): defer deposits until purse available
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/payments.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/test/test-psm-integration.js
Labels: automerge:squash

#6178 walletFactory misc
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
Labels: automerge:merge

#6185 fix(smart-wallet): not yet durable-able
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
Labels: automerge:merge, bypass:integration

#6103 refactor(casting): Use stream cells and release I/O handles
  packages/agoric-cli/src/follow.js
  packages/casting/package.json
  packages/casting/src/defaults.js
  packages/casting/src/follower-cosmjs.js
  packages/casting/src/follower.js
  packages/casting/src/iterable.js
  packages/casting/src/types.js
  packages/casting/test/fake-rpc-server.js
  packages/casting/test/test-mvp.js
  packages/wallet/ui/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#6039 fix(agoric-cli): Reliable publishBundle client
  packages/agoric-cli/package.json
  packages/agoric-cli/src/deploy.js
  packages/agoric-cli/src/publish.js
Labels: automerge:rebase

#6157 provide starter IST to newly provisoned accounts
  golang/cosmos/app/app.go
  golang/cosmos/x/vbank/types/key.go
  packages/cosmic-swingset/Makefile
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/inter-protocol/test/test-interchainPool.js
  packages/smart-wallet/test/devices.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-psm-config.json
  packages/vats/scripts/build-bundles.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/src/provisionPool.js
  packages/vats/test/devices.js
  packages/vats/test/test-provisionPool.js
  packages/wallet/contract/test/devices.js
Labels: automerge:merge, bypass:integration

#6176 5119 wallet cli
  packages/agoric-cli/bin/agops
  packages/agoric-cli/package.json
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/follow.js
  packages/agoric-cli/src/lib/casting.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/keys.js
  packages/agoric-cli/src/lib/psm.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/src/main.js
  packages/agoric-cli/test/agops-smoketest.sh
  packages/agoric-cli/test/test-main.js
  packages/casting/src/defaults.js
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:merge, bypass:integration

#6105 feat(agoric-cli): follow options for lossy and block height prefixes
  packages/agoric-cli/src/follow.js
  packages/agoric-cli/src/main.js
Labels: automerge:rebase, force:integration

#6147 feat(agoric-cli): Add agoric publish subcommand
  packages/agoric-cli/src/json.js
  packages/agoric-cli/src/main-publish.js
  packages/agoric-cli/src/main.js
Labels: automerge:rebase, force:integration

#6191 wallet misc
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/lib/psm.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/agops-smoketest.sh
  packages/smart-wallet/README.md
  packages/smart-wallet/package.json
  packages/smart-wallet/scripts/build-bundles.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:merge, bypass:integration

#6194 test: withAmountUtils expects IssuerKit
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/vats/test/test-provisionPool.js
Labels: automerge:merge, bypass:integration

#6177 fix(SwingSet): transcript tools support snapshot save and load
  packages/SwingSet/misc-tools/extract-transcript-from-slogfile.js
  packages/SwingSet/misc-tools/replay-transcript.js
Labels: automerge:squash, bypass:integration

#6167 feat: ensure voting via PSMCharter works with a unit test
  packages/cosmic-swingset/economy-template.json
  packages/governance/src/committee.js
  packages/governance/src/contractGovernance/governFilter.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/inter-protocol/src/proposals/startEconCommittee.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/psm/psmCharter.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/psm/test-governedPsm.js
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/test/test-psm-integration.js
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-psm-config.json
  packages/vats/src/core/boot-psm.js
Labels: enhancement, Inter-protocol, Governance, automerge:squash, pso

#6180 feat(provision): use governance in provisioning
  packages/agoric-cli/package.json
  packages/agoric-cli/src/commands/wallet.js
  packages/inter-protocol/docs/governance-params.md
  packages/pegasus/src/courier.js
  packages/pegasus/src/pegasus.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/vats/src/bridge.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/src/nameHub.js
  packages/vats/src/provisionPool.js
  packages/vats/src/types.js
  packages/vats/test/test-boot.js
  packages/vats/test/test-provisionPool.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/wallet.js
  packages/wallet/contract/src/singleWallet.js
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/src/support.js
  packages/wallet/contract/src/walletFactory.js
Labels: automerge:merge

#6201 chore: Sync Endo versions
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/contract/package.json
  packages/wallet/ui/package.json
  packages/web-components/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  patches/@endo+marshal+0.7.3.patch
  patches/@endo+ses-ava+0.2.32.patch
  yarn.lock
Labels: automerge:rebase

#6202 fix: psmCharter.addInstance interface shape correction
  packages/inter-protocol/src/psm/psmCharter.js
Labels: bug, wallet, Inter-protocol, automerge:merge, bypass:integration, pso

#6205 fix(vats): snapshot 5x less often
  packages/SwingSet/src/index.js
  packages/SwingSet/src/typeGuards.js
  packages/vats/decentral-psm-config.json
  packages/vats/src/core/boot-psm.js
  packages/vats/test/test-boot-config.js
Labels: automerge:merge

#6134 Wallet UI working with new Smart Wallet contract
  .github/workflows/integration.yml
  packages/casting/src/change-follower.js
  packages/casting/src/follower-cosmjs.js
  packages/casting/src/follower.js
  packages/casting/src/iterable.js
  packages/casting/src/types.js
  packages/cosmic-swingset/Makefile
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/utils.js
  packages/smart-wallet/test/devices.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/package.json
  packages/vats/scripts/build-bundles.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/test/devices.js
  packages/wallet/api/src/marshal-contexts.js
  packages/wallet/contract/README.md
  packages/wallet/contract/src/walletFactory.js
  packages/wallet/contract/test/devices.js
  packages/wallet/contract/test/test-walletFactory.js
  packages/wallet/ui/src/components/ConnectionSettingsDialog.jsx
  packages/wallet/ui/src/components/Proposal.jsx
  packages/wallet/ui/src/service/Offers.js
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/util/keyManagement.js
Labels: wallet, automerge:merge

#6197 6108 psm governance cli
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/psm.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/agoric-cli/test/agops-perf-smoketest.sh
  packages/smart-wallet/src/invitations.js
Labels: automerge:merge, bypass:integration

#6208 clean up smart wallet
  .github/workflows/test-all-packages.yml
  package.json
  packages/agoric-cli/src/sdk-package-names.js
  packages/smart-wallet/test/devices.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-psm-config.json
  packages/vats/demo-proposals.json
  packages/vats/scripts/build-bundles.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/test/devices.js
  packages/wallet/contract/README.md
  packages/wallet/contract/jsconfig.json
  packages/wallet/contract/package.json
  packages/wallet/contract/src/singleWallet.js
  packages/wallet/contract/src/smartWallet.js
  packages/wallet/contract/src/support.js
  packages/wallet/contract/test/devices.js
  packages/wallet/contract/test/supports.js
  packages/wallet/contract/test/test-singleWallet.js
Labels: automerge:merge

#6204 feat: publish vote results from the voteCounter
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/committee.js
  packages/governance/src/electorateTools.js
  packages/governance/src/internalTypes.js
  packages/governance/src/types.js
  packages/governance/test/unitTests/test-ballotCount.js
Labels: enhancement, Governance, automerge:squash, pso

#6188 feat: Write makeSnapshot telemetry to slog
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/SwingSet/test/test-xsnap-metering.js
  packages/SwingSet/test/test-xsnap-store.js
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
  packages/swing-store/package.json
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-snapstore.js
Labels: automerge:rebase

#6216 6211 cli provision
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/chain.js
  packages/agoric-cli/src/lib/keys.js
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/agoric-cli/test/agops-perf-smoketest.sh
Labels: automerge:merge, bypass:integration

#6192 governance cleanup
  packages/governance/src/contractGovernor.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/swingsetTests/setup.js
Labels: automerge:merge

#6193 refactor(cosmic-swingset): merge block-manager into launch-chain
  packages/cosmic-swingset/src/block-manager.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/smart-wallet/src/walletFactory.js
Labels: automerge:rebase, force:integration

#6217 feat: Wallet UI offer status
  packages/cosmic-swingset/Makefile
  packages/wallet/api/src/marshal-contexts.js
  packages/wallet/ui/src/service/Offers.js
  packages/wallet/ui/src/util/WalletBackendAdapter.js
Labels: wallet, automerge:merge

#6214 feat: add dd-trace to dependencies
  packages/agoric-cli/package.json
  yarn.lock
Labels: automerge:rebase

#6222 fix(psm): "mint" limits for IST rather than anchor
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/vats/test/test-provisionPool.js
Labels: automerge:rebase, pso

#6224 fix(SwingSet): Apply netstring limit to xsnap workers
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/lib-nodejs/spawnSubprocessWorker.js
  packages/xsnap/src/xsnap.js
Labels: automerge:merge

#6238 fix(cosmic-swingset): Fix consensus failure on bundle parse errors
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:rebase

#6241 misc Wallet UI
  packages/agoric-cli/test/agops-perf-smoketest.sh
  packages/casting/src/defaults.js
  packages/casting/src/follower-cosmjs.js
  packages/cosmic-swingset/Makefile
  packages/wallet/ui/README.md
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/util/keyManagement.js
Labels: automerge:merge, bypass:integration

#6236 fix: hoist suspicious nested await to top level
  packages/SwingSet/src/controller/initializeSwingset.js
Labels: bug, SwingSet, security, automerge:rebase

#6221 feat(cosmic-swingset): Depth first scheduling
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/make-queue.js
  packages/telemetry/src/slog-to-otel.js
Labels: automerge:merge, force:integration

#6251 feat: uncurryThis performance improvements
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  patches/ses+0.15.22.patch
Labels: performance, automerge:rebase

#6246 fix(cosmic-swingset): add inboundQueue metrics
  packages/cosmic-swingset/src/kernel-stats.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/make-queue.js
Labels: cosmic-swingset, automerge:merge, force:integration

#6248 Improve the efficiency of writing snapshots
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/internal/src/utils.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-snapstore.js
Labels: enhancement, SwingSet, performance, automerge:rebase, force:integration

#6264 chore(xsnap): refactor command/response names for clarity
  packages/xsnap/src/xsnap.js
Labels: xsnap

#6261 feat(zoe): expose keywords in error messages
  packages/ERTP/src/paymentLedger.js
  packages/inter-protocol/src/vpool-xyk-amm/addPool.js
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/contractFacet/allocationMath.js
Labels: automerge:rebase, psmo-rc1

#6277 fix(psmCharter): ParamChangesOfferArgsShape path
  packages/inter-protocol/src/psm/psmCharter.js
Labels: automerge:rebase, psmo-rc1

#6278 feat(agoric-cli): proposeChangeMintLimit
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/test/agops-governance-smoketest.sh
Labels: automerge:squash

#6265 fix wallet show latest
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/psm.js
  packages/agoric-cli/src/lib/wallet.js
  packages/smart-wallet/src/utils.js
Labels: automerge:merge, bypass:integration

#6282 feat(vats): devnet config with anchorAssets, econ cttee addrs
  packages/vats/decentral-devnet-config.json
Labels: automerge:rebase, bypass:integration

#6252 refactor(swing-store): Use the same stream-based approach for loading snapshots as saving them
  packages/swing-store/src/snapStore.js
Labels: SwingSet, automerge:rebase

#6287 static type improvements to contracts
  packages/ERTP/src/amountMath.js
  packages/ERTP/src/types.js
  packages/SwingSet/src/vats/network/multiaddr.js
  packages/SwingSet/tools/manual-timer.js
  packages/agoric-cli/package.json
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/psm.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/types.d.ts
  packages/governance/src/types.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/psm/types.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vpool-xyk-amm/addPool.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/src/vpool-xyk-amm/params.js
  packages/inter-protocol/src/vpool-xyk-amm/pool.js
  packages/inter-protocol/src/vpool-xyk-amm/types.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/reserve/setup.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/offers.js
  packages/solo/src/chain-cosmos-sdk.js
  packages/solo/src/outbound.js
  packages/store/src/patterns/interface-tools.js
  packages/ui-components/package.json
  packages/ui-components/src/display/natValue/stringifyRatioAsFraction.js
  packages/ui-components/src/display/natValue/stringifyRatioAsPercent.js
  packages/ui-components/src/ratio.js
  packages/ui-components/test/display/natValue/test-stringifyRatio.js
  packages/vat-data/src/far-class-utils.js
  packages/wallet/api/src/findOrMakeInvitation.js
  packages/wallet/ui/package.json
  packages/wallet/ui/src/index.jsx
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/otcDesk.js
  packages/zoe/src/types.js
  packages/zoe/src/zoeService/offer/offer.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/test/unitTests/contracts/test-priceAggregatorChainlink.js
  packages/zoe/test/unitTests/test-fakePriceAuthority.js
  packages/zoe/test/unitTests/test-manualTimer.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
  packages/zoe/tools/internal-types.js
Labels: automerge:merge

#6289 feat(wallet-ui): provision new wallet
  packages/cosmic-proto/MAINTAINERS.md
  packages/wallet/ui/package.json
  packages/wallet/ui/src/components/AppBar.jsx
  packages/wallet/ui/src/components/ConnectionSettingsDialog.jsx
  packages/wallet/ui/src/components/Loading.jsx
  packages/wallet/ui/src/components/ProvisionDialog.jsx
  packages/wallet/ui/src/components/Purses.jsx
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/components/tests/AppBar.test.jsx
  packages/wallet/ui/src/components/tests/WalletConnection.test.jsx
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/index.jsx
  packages/wallet/ui/src/tests/App.test.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/util/keyManagement.js
Labels: automerge:squash, automerge:rebase, bypass:integration

#6309 fix(wallet-ui): wait until window loads to access keplr
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/util/onLoad.js
Labels: automerge:rebase

#6316 feat(agoric-cli): support --home, --keyring-backend
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/chain.js
Labels: automerge:squash

#6328 fix(wallet-ui): show rejected offers properly
  packages/wallet/ui/src/components/Proposal.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
Labels: automerge:squash, automerge:rebase

#6307 fix(vats): handle duplicate provision requests
  packages/smart-wallet/package.json
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-psm-integration.js
  packages/vats/src/provisionPool.js
  packages/vats/test/test-provisionPool.js
Labels: automerge:squash

#6310 feat: upgrade handler for upgrade-8
  golang/cosmos/app/app.go
  golang/cosmos/app/const.go
Labels: automerge:merge, agd, agoric-cosmos, MUST-HAVE

#6332 feat(wallet-ui): bridge storage without click when possible
  packages/wallet/ui/src/bridge.jsx
Labels: automerge:rebase, bypass:integration

#6325 feat(telemetry): concentrate slog handling in separate process
  docs/env.md
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/test/vat-admin/test-create-vat.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/deployment/scripts/integration-test.sh
  packages/deployment/src/main.js
  packages/internal/src/utils.js
  packages/solo/src/start.js
  packages/swing-store/src/snapStore.js
  packages/telemetry/package.json
  packages/telemetry/src/all.js
  packages/telemetry/src/flight-recorder.js
  packages/telemetry/src/index.js
  packages/telemetry/src/ingest-slog-entrypoint.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/src/otel-and-flight-recorder.js
  packages/telemetry/src/otel-trace.js
  packages/telemetry/src/serialize-slog-obj.js
  packages/telemetry/src/slog-file.js
  packages/telemetry/src/slog-sender-pipe-entrypoint.js
  packages/telemetry/src/slog-sender-pipe.js
Labels: automerge:rebase

#6331 chore: Sync Endo versions
  MAINTAINERS.md
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/ui/package.json
  packages/web-components/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/xsnap/test/test-xs-perf.js
  packages/zoe/package.json
  patches/@endo+ses-ava+0.2.33.patch
  patches/ses+0.15.22.patch
  yarn.lock
Labels: automerge:rebase

#6333 fix(agoric-cli): don't crash on non-contract offers
  packages/agoric-cli/src/lib/format.js
Labels: automerge:rebase

#6339 Sync CI and mergify config
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/deployment-test.yml
  .github/workflows/docker.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
  .github/workflows/pre-check-integration.yml
  .mergify.yml
  SECURITY.md
  golang/cosmos/Makefile
Labels: automerge:rebase

#6317 fix: wallet show coalesced updates
  packages/agoric-cli/package.json
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/init.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/psm.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/src/types.d.ts
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/casting/src/follower-cosmjs.js
  packages/casting/src/follower.js
  packages/casting/src/types.js
  packages/smart-wallet/package.json
  packages/smart-wallet/scripts/start-local-chain.sh
  packages/smart-wallet/src/utils.js
  packages/wallet/ui/package.json
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/web-components/src/bridge-iframe-connector.js
Labels: automerge:merge

#6348 fix: make it possible to set decimalPlaces when calling startPSM
  packages/agoric-cli/src/lib/psm.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/psm/gov-add-psm-permit.json
  packages/inter-protocol/test/psm/gov-add-psm.js
Labels: bug, Inter-protocol, automerge:squash

#6352 fix(telemetry): handle misbehaving slog senders
  packages/cosmic-swingset/src/chain-main.js
  packages/telemetry/src/flight-recorder.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/src/null.js
  packages/telemetry/src/otel-trace.js
Labels: automerge:rebase

#6353 fix(telemetry): handle misbehaving slog senders [pismo]
  packages/cosmic-swingset/src/chain-main.js
  packages/telemetry/src/flight-recorder.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/src/null.js
  packages/telemetry/src/otel-trace.js
Labels: automerge:rebase

#6358 deterministic xsnap bundles on release-pismo
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeSwingset.js
  patches/@endo+bundle-source+2.3.0.patch
Labels: SwingSet, automerge:merge, force:integration

#6327 fix: test-rankOrder works on ava 3 or 4
  packages/store/test/test-rankOrder.js
Labels: automerge:squash

#6354 fix(wallet-ui): show all significant digits in nat amounts
  packages/ui-components/src/display/display.js
  packages/ui-components/src/display/natValue/stringifyNat.js
  packages/ui-components/test/display/natValue/test-stringifyNat.js
Labels: automerge:squash, automerge:rebase, bypass:integration

#6359 6184 wallet.current record
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/lib/wallet.js
  packages/smart-wallet/scripts/start-local-chain.sh
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/utils.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-psm-integration.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/vats/src/core/basic-behaviors.js
  packages/wallet/ui/endo-promise-kit.d.ts
  packages/wallet/ui/jsconfig.json
  packages/wallet/ui/package.json
  packages/wallet/ui/src/components/SmartWalletConnection.jsx
  packages/wallet/ui/src/index.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
  packages/wallet/ui/src/util/keyManagement.js
Labels: automerge:merge

#6365 Merge branch 'release-pismo' into merge-pismo-into-trunk
  golang/cosmos/app/app.go
  golang/cosmos/app/const.go
  packages/smart-wallet/package.json
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-psm-integration.js
  packages/vats/decentral-devnet-config.json
  packages/vats/src/provisionPool.js
  packages/vats/test/test-provisionPool.js
Labels: automerge:merge, force:integration

#6366 fix(wallet-ui): detect unprovisioned wallet
  packages/smart-wallet/src/utils.js
  packages/wallet/ui/src/contexts/Provider.jsx
  packages/wallet/ui/src/util/WalletBackendAdapter.js
Labels: automerge:merge, bypass:integration
