Repository Agoric/agoric-sdk, pull requests merged in 2023-10, with the labels that each got.

#8414 refactor(ERTP): Delete some dead type declarations
  packages/ERTP/src/types-ambient.js
Labels: automerge:squash

#8415 docs: identify language in some markdown blocks
  CONTRIBUTING.md
  docs/env.md
  packages/ERTP/docs/INPUT_VALIDATION.md
  packages/SwingSet/README.md
  packages/SwingSet/docs/debugging.md
  packages/SwingSet/docs/delivery.md
  packages/SwingSet/docs/devices.md
  packages/SwingSet/docs/dynamic-vats.md
  packages/SwingSet/docs/how-to-replay.md
  packages/cosmic-proto/MAINTAINERS.md
  packages/cosmic-swingset/README.md
  packages/pegasus/demo.md
  packages/xsnap/README.md
Labels: automerge:squash

#8429 fix(swing-store): ensure crank savepoint is wrapped in transaction
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-state.js
Labels: automerge:rebase

#8226 fix(inter): remove excess authority in price-feed-proposal.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
Labels: automerge:rebase

#8258 fix(inter-protocol): brands in CLI need not start with A-Z
  packages/inter-protocol/src/clientSupport.js
  packages/inter-protocol/test/test-clientSupport.js
Labels: automerge:squash, bypass:linear-history

#8229 fix(addAssetToVault): support issuerName separate from keyword
  packages/builders/scripts/inter-protocol/add-collateral-core.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/core/utils.js
  packages/vats/src/mintHolder.js
Labels: automerge:rebase

#8174 docs: Tweak swing-store export example code to show process synchronization
  packages/swing-store/docs/data-export.md
Labels: automerge:rebase

#8398 refactor: delay addition of issuer to auctioneer until a good time
  packages/boot/test/bootstrapTests/test-addAssets.ts
  packages/inter-protocol/package.json
  packages/inter-protocol/src/proposals/addAssetToVault.js
Labels: automerge:rebase, auction

#8422 Multi collateral support - add concurrent liquidation tests
  packages/boot/test/bootstrapTests/liquidation.ts
  packages/boot/test/bootstrapTests/test-liquidation-1.ts
  packages/boot/test/bootstrapTests/test-liquidation-2b.ts
  packages/boot/test/bootstrapTests/test-liquidation-concurrent-1.ts
  packages/boot/test/bootstrapTests/test-liquidation-concurrent-2b.ts
Labels: automerge:rebase

#8438 feat: catch all exceptions in auction wakers
  packages/inter-protocol/src/auction/scheduler.js
Labels: automerge:squash, auction

#8432 feat(cosmic-swingset): add begin block check and transaction
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:squash

#8452 await scaledPriceAuthority
  packages/agoric-cli/src/commands/oracle.js
  packages/boot/test/bootstrapTests/drivers.ts
  packages/inter-protocol/src/price/README.md
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/utils.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
Labels: automerge:rebase

#8154 test(vat-data): use ses-ava
  packages/vat-data/package.json
  packages/vat-data/test/prepare-test-env-ava.js
  packages/vat-data/test/prepare-test-env.js
  packages/vat-data/test/test-absent.js
  packages/vat-data/test/test-durable-classes.js
  packages/vat-data/test/test-prepare.js
  packages/vat-data/test/test-present.js
  packages/vat-data/test/test-scalar-only-keys.js
  packages/vat-data/test/test-virtual-classes.js
Labels: automerge:squash

#8475 docs(vstorage): Add an example external protobuf interface interaction
  golang/cosmos/x/vstorage/README.md
Labels: automerge:rebase

#8477 test: show that smartWallet fails if zoe upgrades. due to #8445
  packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts
  packages/builders/package.json
  packages/builders/scripts/vats/upgrade-zoe.js
  packages/vats/src/proposals/null-upgrade-zoe-proposal.js
Labels: automerge:rebase

#8449 Fix timing issue when re-using proposal in bootstrap tests
  packages/boot/test/bootstrapTests/liquidation.ts
  packages/boot/test/bootstrapTests/supports.ts
  packages/boot/test/bootstrapTests/test-addAssets.ts
  packages/boot/test/bootstrapTests/test-vats-restart.ts
  packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts
  packages/boot/test/bootstrapTests/test-zcf-upgrade.ts
  packages/builders/package.json
Labels: automerge:rebase
