Repository Agoric/agoric-sdk, pull requests merged in 2023-12, with the labels that each got.

#8587 Unreleased upgrade name for master branch
  golang/cosmos/app/app.go
  packages/boot/test/bootstrapTests/test-zcf-upgrade.ts
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/Makefile
  packages/deployment/upgrade-test/Readme.md
  packages/deployment/upgrade-test/upgrade-test-scripts/package.json
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/.gitignore
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/actions.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/actions.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/pre.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/tools/vat-status.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/run-prober-script.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/run-prober.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/zcf-upgrade-driver.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/zcf-upgrade-permit.json
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/zcf-upgrade-script.js
Labels: automerge:rebase, force:integration

#8588 agoric-upgrade-13
  golang/cosmos/app/app.go
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/Makefile
  packages/deployment/upgrade-test/Readme.md
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-12/.gitignore
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-12/actions.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-12/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-12/pre.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/.gitignore
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/actions.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/actions.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/pre.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/tools/vat-status.js
Labels: force:integration

#8590 chore(deps): bump better-sqlite to 9.1
  packages/SwingSet/package.json
  packages/deployment/package.json
  packages/deployment/upgrade-test/upgrade-test-scripts/package.json
  packages/swing-store/package.json
  packages/telemetry/package.json
  yarn.lock
Labels: automerge:rebase

#8598 Remove upgrade-test BOOTSTRAP_MODE=test
  .github/workflows/integration.yml
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/Makefile
  packages/deployment/upgrade-test/upgrade-test-scripts/constants.js
  packages/deployment/upgrade-test/upgrade-test-scripts/env_setup.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/start_to_to.sh
Labels: automerge:rebase

#8604 fix(casting): properly follow an unpopulated node
  packages/agoric-cli/src/follow.js
  packages/casting/src/follower-cosmjs.js
Labels: agoric-cli, automerge:no-update

#8619 fix: export state-sync snapshot without a DB write-lock
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/cosmic-swingset/src/import-kernel-db.js
  packages/swing-store/src/exporter.js
  packages/swing-store/test/exports.js
  packages/swing-store/test/test-bundles.js
  packages/swing-store/test/test-export.js
Labels: cosmic-swingset, automerge:rebase

#8618 test: support for watchedPromises in fakeVirtualSupport
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
Labels: cosmic-swingset, automerge:rebase

#8616 feat: allow clawback vesting accounts to return grants
  golang/cosmos/Makefile
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/x/lien/keeper/account.go
Labels: enhancement, automerge:rebase, agoric-cosmos

#8602 Auto-provision smart wallet
  golang/cosmos/ante/inbound_test.go
  golang/cosmos/app/app.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/migrations.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/legacy/v32/params.go
  golang/cosmos/x/swingset/legacy/v32/params_test.go
  golang/cosmos/x/swingset/types/default-params.go
  golang/cosmos/x/swingset/types/expected_keepers.go
  golang/cosmos/x/swingset/types/msgs.go
  golang/cosmos/x/swingset/types/params.go
  golang/cosmos/x/swingset/types/params_test.go
  packages/deployment/upgrade-test/upgrade-test-scripts/econHelpers.js
  packages/deployment/upgrade-test/upgrade-test-scripts/env_setup.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/actions.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/actions.test.js
  packages/vats/src/core/startWalletFactory.js
Labels: automerge:rebase, force:integration

#8582 feat(cosmos): un-wire x/crisis
  golang/cosmos/app/app.go
  golang/cosmos/app/export.go
  golang/cosmos/daemon/cmd/root.go
  packages/agoric-cli/src/chain-config.js
Labels: automerge:squash, force:integration

#8527 chore: fix release instructions and tools
  MAINTAINERS.md
  scripts/get-released-tags
Labels: automerge:squash

#8491 Swingset startup & benchmark plumbing for node/v8 per-vat profiling & debugging
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/startNodeSubprocess.js
  packages/SwingSet/src/controller/startXSnap.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-node.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/supervisors/subprocess-node/supervisor-subprocess-node.js
  packages/benchmark/doc/benchmarkerator.md
  packages/benchmark/src/benchmarkerator.js
  packages/boot/tools/supports.ts
  packages/cosmic-swingset/src/launch-chain.js
Labels: enhancement, SwingSet, performance, automerge:rebase

#8603 Price feed benchmarks
  packages/benchmark/benchmark/benchmark-liquidation.js
  packages/benchmark/benchmark/benchmark-pricefeed.js
  packages/benchmark/doc/benchmarkerator.md
  packages/benchmark/src/benchmarkerator.js
  packages/boot/test/bootstrapTests/test-addAssets.ts
  packages/boot/test/bootstrapTests/test-liquidation-1.ts
  packages/boot/test/bootstrapTests/test-liquidation-2b.ts
  packages/boot/test/bootstrapTests/test-liquidation-concurrent-1.ts
  packages/boot/test/bootstrapTests/test-liquidation-concurrent-2b.ts
  packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts
  packages/boot/tools/drivers.ts
  packages/boot/tools/liquidation.ts
  packages/vm-config/decentral-itest-vaults-config.json
Labels: enhancement, performance, automerge:rebase

#8649 feat: guard ContractGovernorKit
  .github/workflows/integration.yml
  packages/governance/src/contractGovernorKit.js
Labels: automerge:rebase

#8634 Add a `reapAllVats` method to the controller
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/reap-all/bootstrap-reap-all.js
  packages/SwingSet/test/reap-all/test-reap-all.js
  packages/SwingSet/test/reap-all/vat-dumbo.js
Labels: enhancement, SwingSet, automerge:rebase

#8639 Benchmarkerator documentation copy editing
  packages/SwingSet/src/controller/startNodeSubprocess.js
  packages/benchmark/doc/benchmarkerator.md
  packages/benchmark/src/benchmarkerator.js
Labels: documentation, automerge:rebase

#8659 refactor(SwingSet): convert `run-utils.ts` to JS
  packages/SwingSet/tools/run-utils.js
  packages/boot/test/upgrading/test-upgrade-vats.js
  packages/boot/tools/drivers.ts
Labels: SwingSet, automerge:no-update

#8642 fix(zoe): Fix guards to accurately guard args
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/test/unitTests/test-zoe.js
Labels: automerge:squash

#8593 Wallet factory upgrade 2 branch
  .github/workflows/deployment-test.yml
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/Makefile
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/actions.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/tools/vat-status.js
  packages/deployment/upgrade-test/upgrade-test-scripts/package.json
  packages/deployment/upgrade-test/upgrade-test-scripts/wallet-factory-upgrade/.gitignore
  packages/deployment/upgrade-test/upgrade-test-scripts/wallet-factory-upgrade/actions.js
  packages/deployment/upgrade-test/upgrade-test-scripts/wallet-factory-upgrade/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/wallet-factory-upgrade/pre.test.js
Labels: force:integration

#8637 feat: agd query vstorage trailing slash for children
  golang/cosmos/x/vstorage/README.md
  golang/cosmos/x/vstorage/client/cli/query.go
Labels: automerge:rebase

#8661 support for watchedPromises in fakeVirtualSupport
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
Labels: test, force:integration, liveslots

#8666 feat(types): coreEvalEnv
  packages/inter-protocol/test/psm/gov-add-psm.js
  packages/inter-protocol/test/psm/gov-replace-committee.js
  packages/vats/src/core/boot-chain.js
  packages/vats/src/core/core-eval-env.d.ts
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/test/test-vat-bank-integration.js
Labels: automerge:rebase

#8663 docs: improve hints about cli commands that don't submit offers
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/lib/wallet.js
Labels: automerge:rebase

#8674 chore: Avoid out-of-bounds reads in go-lang code
  golang/cosmos/x/swingset/client/cli/tx.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/keeper/querier.go
  golang/cosmos/x/swingset/types/types.go
  golang/cosmos/x/vbank/keeper/querier.go
  golang/cosmos/x/vstorage/keeper/querier.go
Labels: automerge:squash

#8673 Update links to docs
  README.md
Labels: automerge:squash

#8688 Endo sync types
  packages/inter-protocol/src/price/roundsManager.js
  packages/internal/src/callback.js
  packages/vat-data/src/exo-utils.js
  packages/zone/src/durable.js
Labels: automerge:rebase

#8677 chore(golang): Clarify error messages
  golang/cosmos/x/swingset/client/cli/tx.go
  golang/cosmos/x/swingset/keeper/querier.go
  golang/cosmos/x/swingset/types/types.go
  golang/cosmos/x/vbank/keeper/querier.go
  golang/cosmos/x/vstorage/keeper/querier.go
Labels: automerge:squash

#8701 restore 'store' types
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/base-zone/package.json
  packages/base-zone/src/heap.js
  packages/base-zone/src/store-types.d.ts
  packages/boot/package.json
  packages/builders/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/governance/package.json
  packages/governance/test/swingsetTests/utils.js
  packages/inter-protocol/package.json
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/internal/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-startWalletFactory.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/solo/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/vat-data/package.json
  packages/vats/src/bridge.js
  packages/zoe/package.json
  packages/zone/package.json
Labels: automerge:rebase
