Repository Agoric/agoric-sdk, pull requests merged in 2023-11, with the labels that each got.

#8455 SECURITY.md updates and ownership
  CODEOWNERS
  SECURITY.md
Labels: automerge:squash

#8481 Update RecorderKit to use Awaited<FarAway<StorageNode>>
  packages/zoe/src/contractSupport/recorder.js
Labels: automerge:rebase

#8484 chore(cosmos): update max block size
  golang/cosmos/app/app.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-12/pre.test.js
Labels: automerge:rebase

#8497 refactor(ertp): reallyPrepareIssuerKit
  packages/ERTP/src/issuerKit.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/src/types-ambient.js
  packages/ERTP/test/swingsetTests/ertpService/vat-ertp-service.js
  packages/inter-protocol/src/price/fluxAggregatorContract.js
  packages/vats/src/mintHolder.js
  packages/zoe/src/contractSupport/priceAuthorityQuoteMint.js
  packages/zoe/src/zoeService/feeMint.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/zoeStorageManager.js
Labels: automerge:squash

#8504 refactor(ertp): rename reallyPrepareIssuerKit to prepareIssuerKit
  packages/ERTP/src/issuerKit.js
  packages/inter-protocol/src/price/fluxAggregatorContract.js
  packages/vats/src/mintHolder.js
  packages/zoe/src/contractSupport/priceAuthorityQuoteMint.js
  packages/zoe/src/zoeService/feeMint.js
  packages/zoe/src/zoeService/makeInvitation.js
Labels: automerge:squash

#8391 Workaround babel override mistake
  packages/internal/src/node/createBundles.js
  packages/solo/src/entrypoint.js
  packages/solo/src/pipe-entrypoint.js
Labels: automerge:rebase

#8507 chore(cosmos): update cosmos-sdk
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: automerge:squash

#8476 base upgrade tests on agoric-3-proposals
  .github/workflows/integration.yml
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/Makefile
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-10/actions.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-10/actions.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-10/legacy.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-10/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-10/pre.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-10/upgradeHelpers.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/actions.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/legacy.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/pre.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-12/actions.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-12/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8-1/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8/actions.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8/pre_test.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8/test.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-9/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-9/actions.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-9/test.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/cliHelper.js
  packages/deployment/upgrade-test/upgrade-test-scripts/commonUpgradeHelpers.js
  packages/deployment/upgrade-test/upgrade-test-scripts/constants.js
  packages/deployment/upgrade-test/upgrade-test-scripts/env_setup.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/propose-agoric-upgrade-11/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/propose-agoric-upgrade-12/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/start_ag0.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/start_to_to.sh
Labels: automerge:rebase, bypass:integration

#8515 ci(install-deps): work around Ansible PPA breakage
  .github/workflows/test-all-packages.yml
  packages/deployment/scripts/install-deps.sh
Labels: automerge:rebase, force:integration

#8375 chore: change branch name used for creating releases
  MAINTAINERS.md
Labels: automerge:squash

#8390 fix latest NPM packages
  packages/eslint-config/package.json
  packages/governance/test/unitTests/test-puppetContractGovernor.js
  packages/governance/tools/puppetGovernance.js
  packages/internal/src/node/createBundles.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/supports.js
  packages/solo/src/entrypoint.js
  packages/solo/src/pipe-entrypoint.js
  packages/solo/src/start.js
  packages/swingset-liveslots/package.json
  packages/wallet/package.json
Labels: force:integration

#8506 Specify sender in ICS20 packet
  packages/pegasus/src/courier.js
  packages/pegasus/src/ics20.js
  packages/pegasus/src/pegasus.js
  packages/pegasus/src/types.js
  packages/pegasus/test/test-peg.js
Labels: automerge:squash

#8522 feat(swing-store): faster import of swing-store
  packages/SwingSet/test/transcript/test-state-sync-reload.js
  packages/swing-store/docs/data-export.md
  packages/swing-store/src/importer.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-bundles.js
  packages/swing-store/test/test-exportImport.js
  packages/swing-store/test/test-import.js
  packages/swing-store/test/test-repair-metadata.js
Labels: automerge:rebase

#8519 fix liveslots types
  packages/SwingSet/src/vats/vattp/vat-vattp.js
  packages/swingset-liveslots/src/vatDataTypes.d.ts
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/src/watchedPromises.js
  packages/swingset-liveslots/test/test-durabilityChecks.js
  packages/swingset-liveslots/tools/setup-vat-data.js
  packages/vat-data/src/index.test-d.ts
Labels: automerge:rebase

#8409 feat: update ibc-go to v4, adapt packages and API
  CHANGELOG.md
  golang/cosmos/ante/ante.go
  golang/cosmos/app/app.go
  golang/cosmos/app/sim_test.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/x/vibc/ibc.go
  golang/cosmos/x/vibc/keeper/keeper.go
  golang/cosmos/x/vibc/types/expected_keepers.go
  golang/cosmos/x/vibc/types/msgs.go
  golang/cosmos/x/vibc/types/msgs.pb.go
Labels: enhancement, automerge:rebase, agoric-cosmos

#8533 fix(solo): properly expose `/wallet/bridge.html`
  packages/solo/src/web.js
Labels: wallet, solo, automerge:squash

#8538 fix(cli): handle not found error in vstorage requests
  golang/cosmos/x/vstorage/keeper/querier_test.go
  packages/agoric-cli/src/lib/rpc.js
Labels: automerge:rebase

#8526 Wrap calls to pegasusConnectionsAdmin with Eventual Send
  packages/pegasus/src/proposals/core-proposal.js
Labels: pegasus, automerge:squash

#8421 Move benchmarkerator and some test support code out of the `boot` package
  .github/workflows/test-all-packages.yml
  packages/SwingSet/package.json
  packages/SwingSet/tools/run-utils.ts
  packages/agoric-cli/src/sdk-package-names.js
  packages/benchmark/CHANGELOG.md
  packages/benchmark/benchmark/benchmark-vault-adjust.js
  packages/benchmark/benchmark/benchmark-vault-open.js
  packages/benchmark/doc/benchmarkerator.md
  packages/benchmark/package.json
  packages/benchmark/src/benchmarkerator.js
  packages/benchmark/tsconfig.json
  packages/boot/package.json
  packages/boot/test/bootstrapTests/bench-vaults-performance.js
  packages/boot/test/bootstrapTests/liquidation.ts
  packages/boot/test/bootstrapTests/test-addAssets.ts
  packages/boot/test/bootstrapTests/test-demo-config.ts
  packages/boot/test/bootstrapTests/test-vats-restart.ts
  packages/boot/test/bootstrapTests/test-vaults-integration.ts
  packages/boot/test/bootstrapTests/test-vaults-upgrade.ts
  packages/boot/test/bootstrapTests/test-zcf-upgrade.ts
  packages/boot/test/upgrading/test-upgrade-vats.js
  packages/boot/tools/drivers.ts
  packages/boot/tools/supports.ts
Labels: performance, hygiene, test, automerge:rebase

#8562 fix(casting): dont crash on bad capdata
  packages/agoric-cli/src/lib/wallet.js
  packages/casting/src/follower-cosmjs.js
  packages/casting/src/types.js
  packages/casting/test/test-mvp.js
Labels: automerge:rebase

#8568 typedefs for Zoe privateArgs
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js
  packages/inter-protocol/test/swingsetTests/reserve/bootstrap-assetReserve-upgrade.js
  packages/vats/src/proposals/null-upgrade-zoe-proposal.js
  packages/zoe/src/contractFacet/types-ambient.d.ts
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/src/zoeService/utils.test-d.ts
Labels: automerge:rebase

#8343 generate HTML documentation from TS/JSDoc
  .github/workflows/test-all-packages.yml
  .gitignore
  docs/typescript.md
  package.json
  packages/ERTP/typedoc.json
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/assert/src/types.js
  packages/assert/typedoc.json
  packages/boot/tools/supports.ts
  packages/cosmic-swingset/calc-rpcport.js
  packages/governance/src/question.js
  packages/governance/typedoc.json
  packages/inter-protocol/typedoc.json
  packages/internal/src/batched-deliver.js
  packages/internal/src/utils.js
  packages/notifier/src/storesub.js
  packages/notifier/typedoc.json
  packages/store/src/types.js
  packages/store/typedoc.json
  packages/swingset-liveslots/README.md
  packages/swingset-liveslots/src/message.js
  packages/swingset-liveslots/typedoc.json
  packages/time/typedoc.json
  packages/vat-data/src/index.js
  packages/vat-data/typedoc.json
  packages/vats/src/core/demoIssuers.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/proposals/zcf-proposal.js
  packages/zoe/typedoc.json
  tsconfig.build.json
  tsconfig.json
  typedoc.base.json
  typedoc.json
  typings.d.ts
  yarn.lock
Labels: automerge:rebase

#8571 chore(types): upgrade TypeScript to 5.3
  package.json
  yarn.lock
Labels: automerge:rebase

#8457 fix(agops): fix continuing id lookup in oracle setPrice
  packages/agoric-cli/src/commands/oracle.js
Labels: automerge:rebase
