Repository Agoric/agoric-sdk, pull requests merged in 2023-01, with the labels that each got.

#6739 Clear up uncertain await safety
  package.json
  packages/SwingSet/package.json
  packages/SwingSet/src/vats/network/network.js
  packages/agoric-cli/package.json
  packages/agoric-cli/src/cosmos.js
  packages/agoric-cli/src/deploy.js
  packages/cache/package.json
  packages/cache/src/store.js
  packages/cosmic-swingset/src/chain-main.js
  packages/eslint-config/eslint-config.json
  packages/eslint-config/package.json
  packages/telemetry/src/ingest-slog-entrypoint.js
  yarn.lock
Labels: automerge:merge

#6744 refactor: pulling up more await weeds
  packages/SwingSet/package.json
  packages/SwingSet/src/devices/plugin/device-plugin.js
  packages/SwingSet/src/vats/network/network.js
  packages/agoric-cli/package.json
  packages/agoric-cli/src/deploy.js
  packages/agoric-cli/src/init.js
  packages/agoric-cli/src/install.js
  packages/agoric-cli/src/open.js
  packages/agoric-cli/src/publish.js
  packages/agoric-cli/src/start.js
  packages/cache/package.json
  packages/cache/src/store.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/inter-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/internal/package.json
  packages/internal/src/utils.js
  packages/smart-wallet/src/offers.js
  packages/vats/src/vat-bank.js
  packages/web-components/src/admin-websocket-connector.js
  packages/xsnap/package.json
  packages/xsnap/src/replay.js
  packages/xsnap/src/xsnap.js
  packages/zoe/src/contracts/callSpread/pricedCallSpread.js
Labels: automerge:squash

#6743 feat(vats): provide one `icacontroller-*` port per client
  packages/vats/src/core/chain-behaviors.js
Labels: cosmic-swingset, automerge:merge

#6747 improve diagnostics for interface-tools
  packages/store/src/patterns/interface-tools.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
  packages/store/test/test-heap-classes.js
Labels: automerge:merge

#6738 bump testing deps
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/access-token/package.json
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/sharing-service/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/ui-components/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/web-components/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  patches/ava+5.1.0.patch
  patches/stack-utils+2.0.5.patch
  yarn.lock
Labels: automerge:merge

#6754 chore(deps): bump Prettier to 2.8
  package.json
  packages/eslint-config/package.json
  yarn.lock
Labels: automerge:merge, bypass:integration

#6746 chore: make oracle smoketest wsl compatible
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/inter-protocol/scripts/start-local-chain.sh
Labels: automerge:squash

#6716 6571 durable priceAggregator
  packages/inter-protocol/scripts/build-bundles.js
  packages/inter-protocol/scripts/price-feed-core.js
  packages/inter-protocol/scripts/start-local-chain.sh
  packages/inter-protocol/src/price/priceAggregatorChainlink.js
  packages/inter-protocol/src/price/priceOracleAdmin.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/priceAggregatorChainlink.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/test-priceAggregatorChainlink.js
  packages/notifier/src/storesub.js
  packages/zoe/src/typeGuards.js
Labels: Inter-protocol, automerge:merge, oracle, vaults-release

#6761 feat: include oracleId in OracleStatus
  packages/inter-protocol/src/price/priceAggregatorChainlink.js
  packages/inter-protocol/src/price/priceOracleAdmin.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/test/test-priceAggregatorChainlink.js
Labels: automerge:merge

#6008 chore: Update links
  packages/ERTP/README.md
  packages/SwingSet/docs/delivery.md
  packages/SwingSet/docs/garbage-collection.md
  packages/SwingSet/misc-tools/monitor-slog-block-time.py
  packages/assert/src/assert.js
  packages/assert/src/types.js
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/README-bridge.md
  packages/cosmic-swingset/README.md
  packages/cosmic-swingset/bin/ag-nchainz
  packages/notifier/src/asyncIterableAdaptor.js
  packages/pegasus/src/ics20.js
  packages/vats/test/test-dump.js
  packages/web-components/README.md
  packages/xsnap/src/avaAssertXS.js
  packages/zoe/CONTRIBUTING.md
Labels: documentation, hygiene, automerge:rebase

#6187 test(cosmic-swingset): pay 10 BLD for account with 0.25 IST to start
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/test/scenario2.js
  packages/cosmic-swingset/test/test-make.js
  packages/cosmic-swingset/test/test-provision-smartwallet.js
Labels: automerge:rebase

#6764 fix: incomparables have no min or max
  packages/ERTP/src/amountMath.js
  packages/ERTP/test/unitTests/test-amountProperties.js
Labels: automerge:squash

#6751 docs: Miscellaneous commentary cleanup
  packages/assert/src/types.js
  packages/vat-data/src/types.d.ts
Labels: automerge:squash

#6723 feat(swingset-tools): Expand replay tool for anachrophobia diagnosis
  packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js
  packages/SwingSet/misc-tools/extract-transcript-from-slogfile.js
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/package.json
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/transcript.js
  packages/SwingSet/src/types-external.js
Labels: automerge:rebase

#6776 6771 pricefeed errors
  packages/inter-protocol/src/price/priceAggregatorChainlink.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
Labels: automerge:rebase

#6772 convert vaultFactory entities to FarClass
  packages/ERTP/src/typeGuards.js
  packages/ERTP/src/types-ambient.js
  packages/SwingSet/src/devices/loopbox/loopbox.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/access-token/src/json-store.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/typeGuards.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/notifier/src/typeGuards.js
  packages/notifier/tools/testSupports.js
  packages/swing-store/src/swingStore.js
  packages/vat-data/test/test-durable-classes.js
  packages/vats/src/core/utils.js
Labels: automerge:merge

#6726 refactor: complete and test zoe durability
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/swingsetTests/governance/bootstrap.js
  packages/inter-protocol/test/swingsetTests/governance/vat-zoe.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/bootstrap.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/vat-zoe.js
  packages/inter-protocol/test/vaultFactory/test-vault-interest.js
  packages/inter-protocol/test/vaultFactory/test-vault.js
  packages/smart-wallet/test/supports.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/vat-zoe.js
  packages/vats/test/test-bootstrapPayment.js
  packages/vats/test/test-clientBundle.js
  packages/vats/test/test-vat-bank.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/issuerStorage.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/createZCFVat.js
  packages/zoe/src/zoeService/feeMint.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/swingsetTests/runMint/bootstrap.js
  packages/zoe/test/swingsetTests/runMint/vat-zoe.js
  packages/zoe/test/swingsetTests/zoe/vat-zoe.js
  packages/zoe/test/unitTests/test-instanceStorage.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/zcf/setupZcfTest.js
  packages/zoe/test/unitTests/zcf/test-feeMintAccess.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
  packages/zoe/test/unitTests/zoe/test-createZCFVat.js
  packages/zoe/test/unitTests/zoe/test-instanceAdminStorage.js
  packages/zoe/test/unitTests/zoe/test-makeInvitation.js
Labels: Zoe, automerge:squash, Vaults

#6715 test(zoe): Add a test for contracts surviving Zoe vat upgrade
  packages/SwingSet/test/bootstrap-relay.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/bootstrap-coveredCall-service-upgrade.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/vat-ertp-service.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/vat-zoe.js
  packages/zoe/test/swingsetTests/zoe/test-zoe-upgrade.js
Labels: Zoe, automerge:squash

#6740 test: add a fakeContractGovernor that doesn't need an electorate
  packages/governance/jsconfig.json
  packages/governance/package.json
  packages/governance/src/contractGovernor.js
  packages/governance/test/unitTests/test-puppetContractGovernor.js
  packages/governance/tools/puppetContractGovernor.js
Labels: Zoe, test, Governance, automerge:squash

#6783 5285 durable publishkits
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/metrics.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/notifier/src/storesub.js
Labels: automerge:merge

#6660 refactor: use encodePassable,rankOrder from endo
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/inter-protocol/src/vaultFactory/storeUtils.js
  packages/store/src/index.js
  packages/store/src/keys/checkKey.js
  packages/store/src/keys/compareKeys.js
  packages/store/src/keys/copyBag.js
  packages/store/src/keys/copySet.js
  packages/store/src/keys/merge-bag-operators.js
  packages/store/src/keys/merge-set-operators.js
  packages/store/src/patterns/encodePassable.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/patterns/rankOrder.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/test/test-encodePassable.js
  packages/store/test/test-rankOrder.js
  packages/store/tools/arb-passable.js
Labels: automerge:squash

#6803 resolve lint warnings in inter-protocol
  packages/inter-protocol/scripts/add-initial-liquidity.js
  packages/inter-protocol/src/price/priceAggregatorChainlink.js
  packages/inter-protocol/src/proposals/demoIssuers.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
Labels: automerge:merge

#6755 feat: move snapstore into SQLite database with the rest of the swingstore
  packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/test-xsnap-errors.js
  packages/SwingSet/test/test-xsnap-metering.js
  packages/SwingSet/test/test-xsnap-store.js
  packages/SwingSet/test/vat-warehouse/test-preload.js
  packages/SwingSet/test/vat-warehouse/test-reload-snapshot.js
  packages/SwingSet/test/vat-warehouse/test-warehouse.js
  packages/SwingSet/test/xsnap-snapshots/test-xsnap-snapshots.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/streamStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-snapstore.js
  packages/swing-store/test/test-state.js
Labels: enhancement, SwingSet, automerge:rebase

#6802 chore: Add "Scaling Considerations" to GitHub templates
  .github/ISSUE_TEMPLATE/work_item.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automerge:rebase

#6813 misc types improvements
  packages/inter-protocol/src/price/priceAggregatorChainlink.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vpool-xyk-amm/constantProduct/invariants.js
  packages/inter-protocol/src/vpool-xyk-amm/estimate.js
  packages/smart-wallet/src/smartWallet.js
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/src/contractSupport/safeMath.js
  packages/zoe/src/contractSupport/types.js
  packages/zoe/src/contracts/callSpread/pricedCallSpread.js
  packages/zoe/src/contracts/loan/types.js
  packages/zoe/tools/fakePriceAuthority.js
  packages/zoe/tools/types.js
Labels: automerge:merge

#6808 bump deps
  package.json
  packages/SwingSet/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/pegasus/package.json
  packages/solo/package.json
  packages/swingset-runner/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/package.json
  packages/zoe/package.json
  patches/ava+5.1.1.patch
  yarn.lock
Labels: automerge:rebase

#6796 fix(swing-store): replace getAllState/etc with a debug facet
  packages/SwingSet/test/change-parameters/test-change-parameters.js
  packages/SwingSet/test/devices/test-devices.js
  packages/SwingSet/test/promise-watcher/test-promise-watcher.js
  packages/SwingSet/test/test-activityhash-vs-start.js
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/test-transcript-light.js
  packages/SwingSet/test/test-transcript.js
  packages/SwingSet/test/upgrade/test-upgrade-replay.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate-replay.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/vat-admin/test-replay.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/streamStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-state.js
Labels: SwingSet, automerge:merge

#6774 fix(smart-wallet): create purses for new assets lazily
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/payments.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/test-addAsset.js
  packages/smart-wallet/test/test-startWalletFactory.js
  packages/vats/src/core/startWalletFactory.js
Labels: automerge:merge

#6820 ci(docker): use single `docker buildx imagetools` for multiarch
  .github/workflows/docker.yml
Labels: tooling, automerge:merge

#6789 6665 publicSubscribers
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/vaults.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/casting/src/casting-spec.js
  packages/inter-protocol/scripts/start-local-chain.sh
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startEconCommittee.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/src/vaultFactory/liquidateIncrementally.js
  packages/inter-protocol/src/vaultFactory/liquidateMinimum.js
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/src/vaultFactory/prioritizedVaults.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/inter-protocol/test/metrics.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-liquidator.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/inter-protocol/test/vaultFactory/test-vault-interest.js
  packages/inter-protocol/test/vaultFactory/test-vault.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/internal/src/debug.js
  packages/internal/src/index.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/types.d.ts
  packages/smart-wallet/src/utils.js
  packages/zoe/src/contractSupport/priceAuthority.js
Labels: automerge:merge

#6825 BREAKING CHANGE: rename vivify* to prepare*
  packages/ERTP/src/issuerKit.js
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/test/swingsetTests/ertpService/vat-ertp-service.js
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/src/vats/vattp/vat-vattp.js
  packages/SwingSet/test/vat-durable-singleton.js
  packages/inter-protocol/src/price/priceAggregatorChainlink.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/src/vpool-xyk-amm/pool.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/notifier/src/index.js
  packages/notifier/src/publish-kit.js
  packages/notifier/test/test-publish-kit.js
  packages/notifier/test/vat-integration/vat-pubsub.js
  packages/vat-data/src/far-class-utils.js
  packages/vat-data/src/index.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/types.d.ts
  packages/vat-data/src/vat-data-bindings.js
  packages/vat-data/test/test-prepare.js
  packages/zoe/docs/ZoeDataInitialization.puml
  packages/zoe/src/contractFacet/exit.js
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/makeHandle.js
  packages/zoe/src/zoeService/feeMint.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/coveredCall-durable-V3.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/vat-ertp-service.js
Labels: automerge:squash

#6323 BREAKING CHANGE: rename from FarClass to ExoClass, etc
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/SwingSet/test/vat-durable-singleton.js
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/committee.js
  packages/governance/src/multiCandidateVoteCounter.js
  packages/governance/src/noActionElectorate.js
  packages/governance/src/question.js
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/price/priceOracleAdmin.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/notifier/src/publish-kit.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/store/docs/exo-taxonomy.md
  packages/store/docs/store-taxonomy.md
  packages/store/src/index.js
  packages/store/src/patterns/interface-tools.js
  packages/store/test/test-heap-classes.js
  packages/vat-data/src/exo-utils.js
  packages/vat-data/src/index.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/types.d.ts
  packages/vat-data/src/vat-data-bindings.js
  packages/vat-data/test/test-durable-classes.js
  packages/vat-data/test/test-prepare.js
  packages/vat-data/test/test-virtual-classes.js
  packages/zoe/src/contractFacet/exit.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/makeHandle.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/coveredCall-durable-V3.js
Labels: automerge:squash

#6827 refactor(store): stop using legacy names
  packages/SwingSet/docs/garbage-collection.md
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/src/vats/network/network.js
  packages/SwingSet/src/vats/network/router.js
  packages/SwingSet/src/vats/plugin-manager.js
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/committee.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/electorateTools.js
  packages/governance/src/multiCandidateVoteCounter.js
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vpool-xyk-amm/multipoolMarketMaker.js
  packages/inter-protocol/test/amm/constantProduct/test-estimator.js
  packages/store/README.md
  packages/store/src/types.js
  packages/store/test/test-store.js
  packages/vats/src/bridge.js
  packages/vats/src/ibc.js
  packages/vats/src/lib-board.js
  packages/vats/src/vat-bank.js
  packages/vats/src/vat-mints.js
  packages/vats/test/test-provisionPool.js
  packages/wallet/api/src/internal-types.js
  packages/wallet/api/src/issuerTable.js
  packages/wallet/api/src/lib-dehydrate.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/marshal-contexts.js
  packages/zoe/src/contractFacet/offerHandlerStorage.js
  packages/zoe/src/contractFacet/rightsConservation.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/issuerStorage.js
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/test/unitTests/contractSupport/test-zoeHelpers.js
  packages/zoe/test/unitTests/contracts/escrowToVote.js
  packages/zoe/test/unitTests/setupBasicMints.js
  packages/zoe/tools/fakeVatAdmin.js
  packages/zoe/tools/priceAuthorityRegistry.js
Labels: automerge:squash

#6824 use command opts param
  packages/agoric-cli/package.json
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/wallet.js
  yarn.lock
Labels: automerge:rebase

#6828 fix(zoe): installBundle handles HashBundle format
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/test/unitTests/zoe/test-installationStorage.js
Labels: automerge:squash, force:integration

#6829 BREAKING CHANGE: Retire some unused deprecated names
  packages/store/src/index.js
  packages/store/src/types.js
Labels: automerge:squash

#6797 feat(internal): iterable produces values and can be async
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
Labels: tooling, automerge:merge

#6833 fix smartWallet purse creation from vbank
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:merge

#6835 feat(vats): share Invitation issuer/brand in agoricNames
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
Labels: automerge:rebase

#6814 swingstore+kernel: replace getKeys/vatstoreGetAfter with getNext
  packages/SwingSet/src/kernel/deviceTranslator.js
  packages/SwingSet/src/kernel/kernelSyscall.js
  packages/SwingSet/src/kernel/metrics.js
  packages/SwingSet/src/kernel/state/deviceKeeper.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/storageHelper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/lib/message.js
  packages/SwingSet/src/lib/storageAPI.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/stop-vat.js
  packages/SwingSet/src/liveslots/vatstore-iterators.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/liveslots/virtualReferences.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/comms/state.js
  packages/SwingSet/test/gc-helpers.js
  packages/SwingSet/test/liveslots-helpers.js
  packages/SwingSet/test/metering/test-dynamic-vat-metered.js
  packages/SwingSet/test/stores/test-storeGC/test-lifecycle.js
  packages/SwingSet/test/stores/test-storeGC/test-refcount-management.js
  packages/SwingSet/test/stores/test-storeGC/test-weak-key.js
  packages/SwingSet/test/test-baggage.js
  packages/SwingSet/test/test-liveslots.js
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/test-syscall-failure.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/virtualObjects/test-cease-recognition.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectGC.js
  packages/SwingSet/test/virtualObjects/test-virtualObjectManager.js
  packages/SwingSet/tools/fakeVirtualSupport.js
  packages/cosmic-swingset/src/bufferedStorage.js
  packages/cosmic-swingset/src/chain-main.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-state.js
Labels: SwingSet, automerge:merge

#6117 feat(deploy-script-helpers): Publish bundle
  packages/deploy-script-support/src/helpers.js
  packages/deploy-script-support/src/install.js
Labels: automerge:rebase, force:integration

#6819 fix: prepare for patterns to schematize storage
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/test/stores/test-collections.js
  packages/store/src/patterns/interface-tools.js
  packages/vat-data/src/types.d.ts
  packages/vat-data/src/vat-data-bindings.js
Labels: automerge:squash

#6851 work around ambient issues in prepack
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/contractGovernor.js
  packages/governance/tools/puppetContractGovernor.js
Labels: automerge:merge

#6843 6666 vault actions
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/lib/vaults.js
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/agoric-cli/test/agops-perf-smoketest.sh
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:merge

#6848 Rename 'fit' to 'mustMatch'
  packages/ERTP/src/displayInfo.js
  packages/ERTP/src/mathHelpers/copyBagMathHelpers.js
  packages/ERTP/src/mathHelpers/copySetMathHelpers.js
  packages/ERTP/src/paymentLedger.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/SwingSet/src/vats/timer/timeMath.js
  packages/agoric-cli/src/lib/psm.js
  packages/agoric-cli/src/lib/vaults.js
  packages/casting/src/netconfig.js
  packages/governance/src/contractGovernance/governFilter.js
  packages/governance/src/contractGovernance/governParam.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/question.js
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/store/src/index.js
  packages/store/src/patterns/interface-tools.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/types.js
  packages/store/test/perf-patterns.js
  packages/store/test/test-pattern-limits.js
  packages/store/test/test-patterns.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/provisionPool.js
  packages/vats/test/test-boot-config.js
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/atomicTransfer.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/contracts/coveredCall.js
  packages/zoe/src/zoeService/offer/offer.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/coveredCall-durable-V3.js
  packages/zoe/test/unitTests/contracts/test-coveredCall-want-pattern.js
  packages/zoe/test/unitTests/zcf/test-zoeHelpersWZcf.js
Labels: enhancement, automerge:rebase

#6798 feat(vstorage): overhaul event emissions
  golang/cosmos/app/app.go
  golang/cosmos/types/events.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/vstorage/keeper/keeper.go
  golang/cosmos/x/vstorage/keeper/keeper_test.go
  golang/cosmos/x/vstorage/module.go
  golang/cosmos/x/vstorage/vstorage.go
  packages/cosmic-swingset/src/bufferedStorage.js
  packages/cosmic-swingset/src/chain-main.js
Labels: cosmic-swingset, automerge:merge, agd

#6852 fix(deploy-script-support): RESM compatible bundle powers
  packages/agoric-cli/src/deploy.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/deployment/scripts/integration-test.sh
  packages/internal/src/createBundles.js
  patches/@endo+static-module-record+0.7.15.patch
Labels: automerge:rebase

#6862 6765 publish vaultManager's price feed
  packages/ERTP/src/typeGuards.js
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/internal/src/lib-chainStorage.js
  packages/notifier/src/index.js
  packages/notifier/src/stored-notifier.js
  packages/notifier/src/storesub.js
Labels: automerge:merge

#6854 Update vega to get rid of override mistake problem
  packages/stat-logger/package.json
  packages/stat-logger/patches/vega-util+1.16.0.patch
Labels: hygiene, automerge:rebase

#6861 feat(web-components): read purses from bank instead of smart wallet
  packages/web-components/src/keplr-connection/KeplrConnection.js
  packages/web-components/src/keplr-connection/getChainInfo.js
  packages/web-components/src/keplr-connection/queryBankBalances.js
  packages/web-components/src/keplr-connection/watchWallet.js
Labels: automerge:squash

#6869 docs: rename HEAD to master in md files
  packages/ERTP/README.md
  packages/SwingSet/docs/delivery.md
  packages/SwingSet/docs/networking.md
  packages/web-components/README.md
  packages/zoe/CONTRIBUTING.md
Labels: automerge:squash

#6845 5285 vaultFactory prepares
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/notifier/src/types-ambient.js
  packages/vat-data/src/vat-data-bindings.js
Labels: automerge:merge

#6855 fix: implement test metrics
  .github/workflows/test-all-packages.yml
  .gitignore
  patches/ava+5.1.1.patch
  scripts/ava-etap-to-junit.mjs
  scripts/ci-collect-testruns.sh
Labels: automerge:squash

#6865 refactor(store): split exo tools
  packages/SwingSet/src/liveslots/virtualObjectManager.js
  packages/store/package.json
  packages/store/src/index.js
  packages/store/src/patterns/exo-makers.js
  packages/store/src/patterns/exo-tools.js
  packages/store/test/test-heap-classes.js
  packages/store/tools.js
Labels: automerge:squash

#6874 fix: test on main merge as well for baselines
  .github/workflows/test-all-packages.yml
Labels: automerge:merge

#6876 feat(web-components): read wallet offer public subscribers
  packages/smart-wallet/src/marshal-contexts.js
  packages/smart-wallet/src/smartWallet.js
  packages/web-components/package.json
  packages/web-components/src/keplr-connection/errors.js
  packages/web-components/src/keplr-connection/getKeplrAddress.js
  packages/web-components/src/keplr-connection/watchWallet.js
  yarn.lock
Labels: automerge:squash, automerge:rebase

#6804 resolve lint warnings in smart-wallet
  packages/smart-wallet/src/marshal-contexts.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/utils.js
Labels: automerge:merge

#6832 clean up GitHub Actions deprecations
  .github/actions/restore-golang/action.yml
  .github/actions/restore-node/action.yml
  .github/workflow-templates/test-dapp.yml
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/deployment-test.yml
  .github/workflows/docker.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
  .github/workflows/proto.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-dapp-card-store.yml.DISABLED
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml.DISABLED
  .github/workflows/test-documentation.yml
  .github/workflows/test-golang.yml
  .github/workflows/test-scripts.yml
Labels: automerge:rebase, force:integration

#6877 clean up no-continue
  packages/SwingSet/misc-tools/extract-contract-from-transcript.js
  packages/SwingSet/misc-tools/extract-transcript-from-slogfile.js
  packages/SwingSet/misc-tools/extract-vat-from-transcript.js
  packages/SwingSet/src/liveslots/collectionManager.js
  packages/casting/src/follower-cosmjs.js
  packages/cosmic-swingset/src/kernel-stats.js
  packages/deployment/scripts/crunch.mjs
  packages/deployment/src/init.js
  packages/deployment/src/main.js
  packages/solo/src/outbound.js
  packages/swingset-runner/src/push-metrics.js
  packages/telemetry/src/frcat-entrypoint.js
  packages/vats/src/authorityViz.js
  packages/web-components/package.json
  packages/xsnap/src/avaXS.js
  packages/xsnap/src/object-inspect.js
Labels: automerge:rebase

#6864 docs: rename in two missed comments
  packages/agoric-cli/src/lib/vaults.js
Labels: automerge:squash

#6882 docs: fix readme url
  packages/web-components/README.md
Labels: automerge:rebase

#6886 build: set shell to bash so GA sets pipefail correctly
  .github/workflows/test-all-packages.yml
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
Labels: automerge:squash

#6873 feat(vaultFactory): UI version hash governed param
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
Labels: automerge:squash

#6081 chore: more swingset/misc-tool improvements
  packages/SwingSet/misc-tools/correlate-timestamps.py
  packages/SwingSet/misc-tools/pair-deltas.py
  packages/SwingSet/misc-tools/parse_timestamps.py
Labels: SwingSet, automerge:rebase

#6890 fix(swingset): remove unused worker types: node-subprocess, nodeworker
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-nodeworker.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-node.js
  packages/SwingSet/src/lib-nodejs/spawnSubprocessWorker.js
  packages/SwingSet/src/supervisors/nodeworker/supervisor-nodeworker.js
  packages/SwingSet/src/supervisors/subprocess-node/supervisor-subprocess-node.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/workers/test-worker.js
Labels: SwingSet, automerge:rebase

#6891 fix(liveslots): update stale comment about addRecognizableValue
  packages/SwingSet/src/liveslots/virtualReferences.js
Labels: SwingSet, automerge:rebase, liveslots

#6894 feat(vats): upgradeable mintHolder contract
  packages/ERTP/src/issuerKit.js
  packages/vats/src/core/types.js
  packages/vats/src/mintHolder.js
  packages/vats/test/upgrading/bootstrap.js
  packages/vats/test/upgrading/test-upgrade-contracts.js
Labels: automerge:merge

#6896 bootstrap handles BundleIDs, not full bundles
  packages/ERTP/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/smart-wallet/test/supports.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/manifest.js
  packages/vats/test/devices.js
  packages/vats/test/test-boot.js
  packages/vats/test/test-clientBundle.js
  packages/vats/test/test-vat-bank.js
  packages/vats/tools/boot-test-utils.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/tools/fakeVatAdmin.js
Labels: automerge:rebase
