Repository Agoric/agoric-sdk, pull requests merged in 2023-05, with the labels that each got.

#7543 Enable `agoric run init-core.js` to work without a solo VM connection
  golang/cosmos/ante/vm_admission.go
  packages/access-token/src/access-token.js
  packages/agoric-cli/src/deploy.js
  packages/agoric-cli/src/main.js
  packages/agoric-cli/src/publish.js
  packages/agoric-cli/src/run.js
  packages/agoric-cli/src/scripts.js
  packages/agoric-cli/src/start.js
  packages/deploy-script-support/src/cachedBundleSpec.js
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/getBundlerMaker.js
  packages/deploy-script-support/src/helpers.js
  packages/deploy-script-support/src/installInPieces.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/inter-protocol/src/proposals/utils.js
  packages/internal/src/scratch.js
  packages/solo/src/vat-uploads.js
Labels: agoric-cli, Governance, automerge:merge

#7555 7495 price vat upgradable
  packages/ERTP/src/amountMath.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/tools/bundleTool.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/vat-priceAuthority.js
  packages/vats/test/snapshots/test-boot-config.js.md
  packages/vats/test/snapshots/test-boot-config.js.snap
  packages/vats/test/test-boot-config.js
  packages/vats/test/upgrading/test-upgrade-vats.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contracts/scaledPriceAuthority.js
  packages/zoe/test/types.test-d.ts
  packages/zoe/test/unitTests/contracts/test-scaledPriceAuthority.js
  packages/zoe/tools/priceAuthorityRegistry.js
Labels: automerge:merge

#7566 feat(agoric-cli): propose PriceLockPeriod change
  packages/agoric-cli/src/commands/auction.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
Labels: automerge:rebase

#7554 6791 vaults upgrade dependencies
  packages/SwingSet/src/types-external.js
  packages/governance/src/contractHelper.js
  packages/inter-protocol/scripts/add-collateral-core.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vault-collateralization.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/swingset-liveslots/src/liveslots.js
  packages/vats/test/bootstrapTests/supports.js
  packages/zoe/src/zoeService/startInstance.js
Labels: automerge:merge

#7546 Address many floating promises detected by our linter
  .eslintrc.cjs
  packages/notifier/src/stored-notifier.js
  packages/notifier/test/test-publish-kit.js
  packages/store/test/test-AtomicProvider.js
  packages/swing-store/test/test-bundles.js
  packages/swingset-runner/demo/exchangeBenchmark/prepareContracts.js
  packages/swingset-runner/demo/resolvePromiseComplicated/vat-bob.js
  packages/swingset-runner/demo/swapBenchmark/prepareContracts.js
  packages/swingset-runner/demo/zoeTests/prepareContracts.js
  packages/swingset-runner/src/graphDisk.js
  packages/swingset-runner/src/graphMem.js
  packages/swingset-runner/src/graphStats.js
  packages/swingset-runner/src/graphTime.js
  packages/swingset-runner/src/kerneldump-entrypoint.js
  packages/swingset-runner/src/main.js
  packages/swingset-runner/src/runner-debug-entrypoint.js
  packages/swingset-runner/src/runner-entrypoint.js
  packages/swingset-runner/src/slogulator-entrypoint.js
  packages/vats/test/bootstrapTests/supports.js
Labels: automerge:rebase

#7568 Extend Prometheus kernel stats
  packages/SwingSet/src/kernel/metrics.js
  packages/cosmic-swingset/src/kernel-stats.js
Labels: enhancement, SwingSet, cosmic-swingset, automerge:rebase

#7569 feat(smartWallet): fail early on offerId re-use
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:merge

#7547 feat(controller): louder UnhandledPromiseRejection log
  packages/SwingSet/src/controller/controller.js
Labels: automerge:merge

#7571 ci: add debug info for github support
  .github/workflows/docker.yml
Labels: automerge:rebase

#7572 fix(agoric-cli): dont throw when reading history
  packages/agoric-cli/src/lib/rpc.js
Labels: automerge:rebase

#7150 feat(vaults)!: vstorage index node for managers
  packages/inter-protocol/README.md
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/inter-protocol/test/vaultFactory/test-storage.js
Labels: automerge:merge

#6904 TimerService emits branded TimeStampRecord/RelativeTimeRecord
  packages/SwingSet/docs/timer.md
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/SwingSet/test/test-manual-timer.js
  packages/SwingSet/test/test-vat-timer.js
  packages/SwingSet/test/timer/bootstrap-timer.js
  packages/SwingSet/test/timer/test-timer.js
  packages/SwingSet/test/vat-timer-upgrade/bootstrap-vat-timer-upgrade.js
  packages/SwingSet/tools/manual-timer.js
  packages/agoric-cli/src/commands/auction.js
  packages/governance/test/swingsetTests/committeeBinary/test-committee.js
  packages/inter-protocol/src/auction/params.js
  packages/inter-protocol/src/auction/scheduleMath.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-computeRoundTiming.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/price/snapshots/test-fluxAggregatorKit.js.md
  packages/inter-protocol/test/price/snapshots/test-fluxAggregatorKit.js.snap
  packages/inter-protocol/test/price/test-fluxAggregatorKit.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/test-interest-labeled.js
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/solo/package.json
  packages/solo/test/test-home.js
  packages/store/package.json
  packages/store/test/borrow-guards.js
  packages/time/src/timeMath.js
  packages/time/src/types.d.ts
  packages/time/test/test-timeMath.js
  packages/zoe/package.json
  packages/zoe/src/contractFacet/exit.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contracts/auction/index.js
  packages/zoe/src/contracts/loan/types.js
  packages/zoe/src/contracts/loan/updateDebt.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/typeGuards.js
  packages/zoe/test/unitTests/contracts/loan/test-borrow.js
  packages/zoe/test/unitTests/contracts/test-coveredCall-want-pattern.js
  packages/zoe/test/unitTests/contracts/test-coveredCall.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/contracts/test-scaledPriceAuthority.js
  packages/zoe/test/unitTests/test-cleanProposal.js
  packages/zoe/test/unitTests/test-fakePriceAuthority.js
  packages/zoe/test/unitTests/test-manualTimer.js
  packages/zoe/test/unitTests/test-scriptedOracle.js
  packages/zoe/test/unitTests/test-testHelpers.js
  packages/zoe/test/zoeTestHelpers.js
  packages/zoe/tools/fakePriceAuthority.js
  packages/zoe/tools/manualTimer.js
  packages/zoe/tools/scriptedOracle.js
  packages/zoe/tools/scriptedPriceAuthority.js
Labels: automerge:rebase

#7476 6791 vaults upgrade
  packages/SwingSet/src/devices/timer/timer.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/vats/src/core/types.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-vaults-upgrade.js
  packages/zoe/src/contractSupport/durability.js
Labels: automerge:merge

#7542 feat: flag to compress bundles in transit
  golang/cosmos/proto/agoric/swingset/msgs.proto
  golang/cosmos/x/swingset/client/cli/tx.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/types/msgs.go
  golang/cosmos/x/swingset/types/msgs.pb.go
  golang/cosmos/x/swingset/types/msgs_test.go
Labels: enhancement, cosmic-swingset, automerge:merge

#7585 switch to smallcaps everywhere
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/test-inter-cli.js
  packages/cache/src/store.js
  packages/cache/test/test-storage.js
  packages/casting/src/defaults.js
  packages/cosmic-swingset/src/chain-main.js
  packages/governance/test/unitTests/snapshots/test-committee.js.md
  packages/governance/test/unitTests/snapshots/test-committee.js.snap
  packages/governance/test/unitTests/test-committee.js
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.md
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.snap
  packages/inter-protocol/test/price/snapshots/test-fluxAggregatorKit.js.md
  packages/inter-protocol/test/price/snapshots/test-fluxAggregatorKit.js.snap
  packages/inter-protocol/test/price/test-fluxAggregatorKit.js
  packages/inter-protocol/test/psm/snapshots/test-psm.js.md
  packages/inter-protocol/test/psm/snapshots/test-psm.js.snap
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/reserve/snapshots/test-reserve.js.md
  packages/inter-protocol/test/reserve/snapshots/test-reserve.js.snap
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/internal/src/storage-test-utils.js
  packages/internal/test/test-storage-test-utils.js
  packages/notifier/src/storesub.js
  packages/smart-wallet/src/marshal-contexts.js
  packages/smart-wallet/test/test-marshal-contexts.js
  packages/vats/src/lib-board.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/test-board-utils.js
  packages/vats/test/test-lib-board.js
  packages/vats/tools/board-utils.js
  packages/wallet/api/src/lib-dehydrate.js
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/test/test-getPursesNotifier.js
  packages/wallet/api/test/test-lib-dehydrate.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/wallet/api/test/test-middleware.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
Labels: automerge:merge, force:integration

#7584 remove leftover makeMarshal from vatPowers
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js
Labels: SwingSet, automerge:rebase

#7596 fix(SwingSet): dedupe `bundleTool.js` with Endo
  packages/SwingSet/tools/bundleTool.js
Labels: SwingSet, tooling, automerge:merge

#7593 upgradable econCommittee
  packages/governance/src/committee.js
  packages/governance/src/electorateTools.js
  packages/governance/src/voterKit.js
  packages/governance/test/swingsetTests/committeeBinary/vat-voter.js
  packages/governance/test/unitTests/test-committee.js
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/psm/test-governedPsm.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/swingsetTests/fluxAggregator/bootstrap-fluxAggregator-service-upgrade.js
  packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
Labels: automerge:merge

#7545 refactor: add contract starting tools; use in startWalletFactory
  packages/governance/src/types-ambient.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/inter-protocol/test/psm/gov-add-psm-permit.json
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/test/bootstrapTests/test-vaults-upgrade.js
  packages/vats/test/snapshots/test-board-utils.js.md
  packages/vats/test/snapshots/test-board-utils.js.snap
  packages/vats/test/snapshots/test-boot-config.js.md
  packages/vats/test/snapshots/test-boot-config.js.snap
  packages/web-components/index.js
Labels: automerge:merge

#7586 feat(internal): new `prepareAttenuator` leveraging callbacks
  packages/internal/src/callback.js
  packages/internal/src/types.d.ts
  packages/internal/test/test-callback.js
  packages/vats/package.json
Labels: automerge:merge, patterns

#7597 smallcaps followup changes
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/test-inter-cli.js
  packages/cache/src/store.js
  packages/casting/src/defaults.js
  packages/governance/test/unitTests/test-committee.js
  packages/internal/src/storage-test-utils.js
  packages/notifier/src/storesub.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/test-board-utils.js
  packages/vats/test/test-lib-board.js
  packages/vats/tools/board-utils.js
  packages/wallet/api/src/lib-dehydrate.js
Labels: automerge:rebase

#7607 ci: bump ava exit timeout in hope to reduce flakes
  patches/ava+5.2.0.patch
Labels: automerge:squash

#7583 fix(oracles): set min oracles in devnet to 3
  packages/inter-protocol/scripts/price-feed-core.js
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-test-vaults-config.json
Labels: automerge:rebase, oracle, Vaults

#7609 feat(vats): allow replacing a scoped bridge handler
  packages/vats/src/bridge.js
  packages/vats/src/types.js
Labels: automerge:squash

#7582 assetReserve upgradable
  packages/governance/tools/puppetContractGovernor.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/reserve/assetReserveKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/tools.js
  packages/inter-protocol/test/metrics.js
  packages/inter-protocol/test/reserve/test-reserve.js
  packages/inter-protocol/test/swingsetTests/reserve/bootstrap-assetReserve-upgrade.js
  packages/inter-protocol/test/swingsetTests/reserve/test-assetReserve-upgrade.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/vats/src/core/types.js
Labels: automerge:merge, bypass:integration

#7603 test: audit bootstrap exports
  packages/vats/test/bootstrapTests/test-vaults-integration.js
Labels: automerge:rebase, bypass:integration

#7615 fix(agoric-cli): harden bridgeAction
  packages/agoric-cli/src/lib/wallet.js
Labels: automerge:rebase, bypass:integration

#7574 fix(auction): publish updates when lockedPrice changes
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/auction/tools.js
Labels: bug, automerge:squash, Vaults, auction

#7616 fix(provisionPool): metrics publishing path
  packages/vats/src/provisionPool.js
  packages/vats/src/provisionPoolKit.js
  packages/vats/test/test-provisionPool.js
Labels: automerge:rebase, bypass:integration

#7619 ci: fix ava hang in CI when v8 coverage is set
  patches/ava+5.2.0.patch
Labels: automerge:squash, bypass:integration

#7608 remove stakeFactory
  packages/cosmic-swingset/Makefile
  packages/inter-protocol/README.md
  packages/inter-protocol/docs/governance.md
  packages/inter-protocol/docs/inter-protocol-preview.md
  packages/inter-protocol/exported.js
  packages/inter-protocol/scripts/deploy-contracts.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/my-lien.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/stakeFactory/README.md
  packages/inter-protocol/src/stakeFactory/attestation.js
  packages/inter-protocol/src/stakeFactory/attestationTool.js
  packages/inter-protocol/src/stakeFactory/constants.js
  packages/inter-protocol/src/stakeFactory/params.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/src/stakeFactory/types.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/test/attestation/exampleLoanUsage.js
  packages/inter-protocol/test/attestation/test-attestation.js
  packages/inter-protocol/test/attestation/test-userFlow.js
  packages/inter-protocol/test/stakeFactory/attestationFaker.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/supports.js
  packages/pegasus/src/ibc-trace.js
  packages/pegasus/src/pegasus.js
  packages/pegasus/src/types.js
  packages/solo/src/vat-http.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/test/bootstrapTests/test-demo-config.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/wallet/api/package.json
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/wallet.js
  packages/wallet/api/test/attestationExample.js
  packages/wallet/api/test/test-lib-wallet.js
Labels: automerge:rebase

#7612 7602 fix double econCommittee
  packages/agoric-cli/src/commands/ec.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/cosmic-swingset/economy-template.json
  packages/inter-protocol/scripts/add-collateral-core.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/smartWallet/boot-psm.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-main-psm-config.json
  packages/vats/decentral-psm-config.json
  packages/vats/decentral-test-psm-config.json
  packages/vats/decentral-test-vaults-config.json
  packages/vats/test/test-boot-config.js
  packages/vats/test/test-boot.js
Labels: automerge:rebase

#7598 chore: Upgrade to cosmjs 0.30.1
  packages/agoric-cli/package.json
  packages/agoric-cli/src/publish.js
  packages/casting/package.json
  yarn.lock
Labels: automerge:rebase, bypass:integration

#7620 refactor(vats): explicit set/init handler for scoped bridge manager
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/walletFactory-V2.js
  packages/vats/src/bridge.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/types.js
  packages/vats/src/vat-bank.js
  packages/vats/test/test-vat-bank.js
  packages/vats/test/upgrading/test-upgrade-vats.js
Labels: automerge:squash

#7613 chore(internal): fix comment typo
  packages/internal/src/storage-test-utils.js
Labels: automerge:rebase, bypass:integration

#7623 move vat-ibc/vat-network from config to network-proposal.js
  packages/cosmic-swingset/economy-template.json
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-test-vaults-config.json
  packages/vats/demo-proposals.json
  packages/vats/scripts/init-network.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/client-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/src/proposals/network-proposal.js
  packages/vats/test/bootstrapTests/test-demo-config.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/snapshots/test-boot-config.js.md
  packages/vats/test/snapshots/test-boot-config.js.snap
  packages/vats/test/test-boot-config.js
Labels: automerge:rebase

#7595 7585 cleanup
  packages/agoric-cli/src/lib/rpc.js
  packages/casting/README.md
  packages/casting/src/defaults.js
  packages/casting/src/follower-cosmjs.js
  packages/casting/src/types.js
  packages/casting/test/fake-rpc-server.js
  packages/internal/src/lib-chainStorage.js
  packages/notifier/src/stored-notifier.js
  packages/notifier/src/storesub.js
  packages/notifier/src/types-ambient.js
  packages/notifier/src/types.js
  packages/notifier/test/test-stored-subscription.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/test/test-marshal-contexts.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/tools/board-utils.js
  packages/wallet/api/test/test-middleware.js
  packages/zoe/src/contractSupport/recorder.js
Labels: automerge:merge, bypass:integration

#7604 fix: remove well-known-name limitation on reserved brands etc.
  packages/inter-protocol/README.md
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/test/reserve/setup.js
  packages/inter-protocol/test/reserve/test-reserve.js
  packages/inter-protocol/test/smartWallet/boot-psm.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vault-interest.js
  packages/inter-protocol/test/vaultFactory/test-vault.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/promise-space.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/src/nameHub.js
  packages/vats/src/types.js
  packages/vats/test/test-name-hub-published.js
  packages/vats/test/test-name-hub.js
  packages/vats/test/test-promise-space.js
Labels: automerge:merge, bypass:integration

#7628 chore: ensure adminFacet for bldHolder is saved.
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/test/snapshots/test-boot-config.js.md
  packages/vats/test/snapshots/test-boot-config.js.snap
  packages/vats/test/test-vat-bank.js
Labels: Inter-protocol

#7629 update workflows to trigger merge_group checks
  .github/workflows/deployment-test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
  .github/workflows/mergify-ready.yml
  .github/workflows/proto.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-dapp-card-store.yml
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml.DISABLED
  .github/workflows/test-documentation.yml
  .github/workflows/test-golang.yml
  .github/workflows/test-scripts.yml
Labels: tooling

#7606 State dir cleanup
  docs/env.md
  packages/SwingSet/docs/how-to-replay.md
  packages/SwingSet/misc-tools/db-dump.js
  packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/cosmic-swingset/src/import-kernel-db.js
  packages/deployment/scripts/capture-integration-results.sh
  scripts/process-integration-results.sh
  scripts/process-integration-swingstore-traces.sh
Labels: automerge:rebase

#7592 Update go version and fix govulncheck warnings
  .github/actions/restore-golang/action.yml
  .github/workflows/deployment-test.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-golang.yml
  bin/agd
  go.mod
  go.sum
  repoconfig.sh
Labels: enhancement, agoric-cosmos

#7605 feat: durable agoricNames, namesByAddress
  packages/deploy-script-support/test/unitTests/test-coreProposalBehavior.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/reserve/setup.js
  packages/inter-protocol/test/smartWallet/boot-psm.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
  packages/internal/src/callback.js
  packages/internal/test/test-callback.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/bootstrap-walletFactory-service-upgrade.js
  packages/solo/solo-config.json
  packages/solo/src/start.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-test-vaults-config.json
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/lib-boot.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/src/lib-board.js
  packages/vats/src/nameHub.js
  packages/vats/src/types.js
  packages/vats/src/vat-agoricNames.js
  packages/vats/src/vat-board.js
  packages/vats/src/vat-provisioning.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/snapshots/test-boot-config.js.md
  packages/vats/test/snapshots/test-boot-config.js.snap
  packages/vats/test/test-boot.js
  packages/vats/test/test-clientBundle.js
  packages/vats/test/test-name-hub-published.js
  packages/vats/test/test-name-hub.js
  packages/vats/tools/boot-test-utils.js
  packages/wallet/api/test/test-getPursesNotifier.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/zone/src/durable.js
Labels: automerge:rebase

#7617 Durable vat-bank and virtual-purse
  .eslintrc.cjs
  packages/ERTP/src/types-ambient.js
  packages/agoric-cli/src/commands/reserve.js
  packages/agoric-cli/src/lib/format.js
  packages/inter-protocol/src/price/fluxAggregatorKit.js
  packages/internal/src/callback.js
  packages/internal/test/test-callback.js
  packages/notifier/src/asyncIterableAdaptor.js
  packages/notifier/src/subscribe.js
  packages/notifier/src/types-ambient.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/test-addAsset.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/nameHub.js
  packages/vats/src/vat-bank.js
  packages/vats/src/vat-provisioning.js
  packages/vats/src/virtual-purse.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/setup-vat-data.js
  packages/vats/test/test-clientBundle.js
  packages/vats/test/test-provisionPool.js
  packages/vats/test/test-vat-bank-integration.js
  packages/vats/test/test-vat-bank.js
  packages/vats/test/test-vpurse.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/zoe/src/contracts/exported.js
Labels: cosmic-swingset

#7610 chore(internal): smallcaps followup followup
  packages/internal/src/storage-test-utils.js
  packages/internal/test/test-storage-test-utils.js
Labels: automerge:merge

#7652 Bump docker package go version
  packages/deployment/Dockerfile
  packages/deployment/Dockerfile.sdk
Labels: deployment, go

#7662 Upgrade test refactor
  .github/workflows/test-all-packages.yml
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/Readme.md
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-10/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-10/agoric-upgrade-10_pre_test.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/agoric-upgrade-11_actions.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8-1/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8/agoric-upgrade-8_actions.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8/agoric-upgrade-8_pre_test.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8/agoric-upgrade-8_test.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8_pre_test.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-8_test.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-9/.keep
  packages/deployment/upgrade-test/upgrade-test-scripts/env_setup.sh
Labels: deployment

#7664 fix(agoric-cli): allow `follow` to work with smallcaps
  packages/agoric-cli/src/follow.js
Labels: agoric-cli

#7624 ci: docker build bump
  .github/workflows/docker.yml
Labels: automerge:rebase

#7676 fix(vaults): reset lockedQuote at start of auction
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: bug, Vaults

#7680 feat(agoric-cli): add `follow --first-value-only` or `-F`
  packages/agoric-cli/src/follow.js
  packages/agoric-cli/src/main.js
Labels: agoric-cli

#7684 Reboot SwingSet on bulldozer upgrade
  golang/cosmos/app/app.go
  golang/cosmos/x/swingset/genesis.go
Labels: agd

#7686 fix(auction): handle auction waking a little bit late gracefully
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/test/auction/test-scheduler.js
Labels: bug, auction

#7694 fix: repair a provide collision in priceAuthorityRegistry
  packages/zoe/test/unitTests/tools/test-priceAuthorityRegistry.js
  packages/zoe/tools/priceAuthorityRegistry.js
Labels: bug, Vaults

#7711 chore: kernel logs vat upgrades, with bundleID and old/new incarnations
  packages/SwingSet/src/kernel/kernel.js
Labels: SwingSet

#7720 chore: add collateralBrand to vault and auction trace() calls
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
Labels: Vaults, auction

#7691 test(deployment): end-to-end test of on-chain contract upgrade
  golang/cosmos/x/swingset/keeper/keeper.go
  packages/agoric-cli/package.json
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/commands/test-upgrade.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/upgrade-contract/buggy-contract.js
  packages/agoric-cli/test/upgrade-contract/contract-upgrade-smoketest.sh
  packages/agoric-cli/test/upgrade-contract/fixed-contract.js
  packages/agoric-cli/test/upgrade-contract/init-proposal.js
  packages/agoric-cli/test/upgrade-contract/propose-buggy-contract.js
  packages/agoric-cli/test/upgrade-contract/propose-upgrade-contract.js
  packages/agoric-cli/test/upgrade-contract/upgrade-proposal.js
Labels: agoric-cli

#7723 Jimlarson vaults changelog
  CHANGELOG.md
Labels: documentation

#7728 Allow external transfers to the reserve account
  golang/cosmos/app/app.go
Labels: enhancement, cosmic-swingset, Inter-protocol

#7741 refactor: handle missing quotes, which cause all kinds of trouble
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/params.js
  packages/inter-protocol/src/auction/scheduleMath.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/src/auction/util.js
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-scheduleMath.js
  packages/inter-protocol/test/auction/test-scheduler.js
Labels: bug, Vaults, auction

#7756 fix: agd install for cli bidding
  bin/agd
  packages/inter-protocol/test/auction/README-bidding-cli.md
  repoconfig.sh
Labels: bug

#7752 fix(vaults): when reconstituting vaults, report correct shortfall
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: Vaults

#7760 handle floating promises in /inter-protocol and /vats
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/reserve/assetReserveKit.js
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/utils.js
  packages/vats/src/virtual-purse.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/bootstrapTests/test-vaults-upgrade.js
  packages/vats/test/test-name-hub.js
Labels: bug, vaults_triage

#7767 7346 don't overpay
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: bug, Vaults

#7667 build(notifier): properly use the `types-ambient.js` pattern
  packages/SwingSet/src/vats/network/network.js
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/notifier/src/types-ambient.js
  packages/notifier/src/types.js
  packages/smart-wallet/src/walletFactory.js
  packages/vats/src/vat-bank.js
Labels: notifier, hygiene

#7785 fix(vaults): return correct collateral after liquidation
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
  packages/vats/test/bootstrapTests/test-vaults-upgrade.js
Labels: Vaults

#7788 fix(vaults): reconstitute vaults correctly
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
Labels: bug, Vaults, auction

#7803 7794 capture market price at auction start
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/auction/tools.js
Labels: auction

#7813 7794 regression test
  .github/workflows/test-all-packages.yml
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
Labels: test, devex, Vaults

#7840 Fix `agops-vaults-smoketest.sh` and `start-local-chain.sh`
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/inter-protocol/scripts/start-local-chain.sh
Labels: agoric-cli

#7843 feat!: rename EndorsedUI to ReferencedUI
  packages/inter-protocol/docs/governance.md
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/test/test-proposal-stuff.js
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-itest-vaults-config.json
  packages/vats/decentral-main-vaults-config.json
  packages/vats/decentral-test-vaults-config.json
Labels: v1_triaged

#7827 7806 missing collateral
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/vats/test/bootstrapTests/test-liquidation-1.js
  packages/vats/test/bootstrapTests/test-liquidation-2b.js
  packages/vats/test/bootstrapTests/test-liquidation.js
  packages/vats/test/bootstrapTests/test-vaults-upgrade.js
Labels: bug, Vaults

#7868 refactor: vaults publish the locked price for the upcoming auction
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/vats/test/bootstrapTests/test-liquidation-1.js
Labels: Vaults
