Repository Agoric/agoric-sdk, pull requests merged in 2023-03, with the labels that each got.

#7081 refactor: track endo changes
  packages/store/src/keys/checkKey.js
  packages/store/src/keys/merge-bag-operators.js
  packages/store/src/keys/merge-set-operators.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/types.js
  packages/store/test/test-copyBag.js
Labels: automerge:squash

#6971 feat(vstorage): Disambiguate empty strings and deletions
  golang/cosmos/app/app.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/querier.go
  golang/cosmos/x/vstorage/keeper/grpc_query.go
  golang/cosmos/x/vstorage/keeper/keeper.go
  golang/cosmos/x/vstorage/keeper/keeper_test.go
  golang/cosmos/x/vstorage/keeper/querier.go
  golang/cosmos/x/vstorage/types/path_keys.go
  golang/cosmos/x/vstorage/types/types.go
  golang/cosmos/x/vstorage/vstorage.go
  packages/cache/test/test-storage.js
  packages/casting/src/casting-spec.js
  packages/casting/src/follower-cosmjs.js
  packages/casting/src/types.js
  packages/cosmic-swingset/src/chain-main.js
  packages/internal/src/lib-chainStorage.js
  packages/internal/src/storage-test-utils.js
  packages/internal/test/test-storage-test-utils.js
  packages/notifier/src/types-ambient.js
Labels: automerge:rebase

#7103 6878 misc fixes and refactors
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/test/swingsetTests/ertpService/test-ertp-service-upgrade.js
  packages/SwingSet/misc-tools/measure-metering/measure.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/device-mailbox/test-device-mailbox.js
  packages/SwingSet/test/gc/test-gc-vat.js
  packages/SwingSet/test/metering/test-dynamic-vat-unmetered.js
  packages/SwingSet/test/run-policy/test-run-policy.js
  packages/SwingSet/test/test-activityhash-vs-start.js
  packages/SwingSet/test/test-vat-env.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-warehouse/test-preload.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/zcf-ish-upgrade/test-zcf-ish-upgrade.js
  packages/SwingSet/tools/bundleTool.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/notifier/test/test-publish-kit.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/test-startWalletFactory.js
  packages/vat-data/src/exo-utils.js
  packages/vat-data/test/test-prepare.js
  packages/vats/test/test-provisionPool.js
  packages/vats/test/upgrading/test-upgrade-vats.js
  packages/vats/tools/bank-utils.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/test-coveredCall-service-upgrade.js
  packages/zoe/test/swingsetTests/zoe/test-zoe-upgrade.js
Labels: automerge:merge, bypass:integration

#7109 feat(bundleTool): color the console output
  packages/SwingSet/package.json
  packages/SwingSet/tools/bundleTool.js
  packages/agoric-cli/package.json
  packages/deployment/package.json
Labels: automerge:merge, bypass:integration

#7106 refactor: Simplify {jsconfig,tsconfig}.json files by inheritance
  packages/ERTP/jsconfig.json
  packages/SwingSet/jsconfig.json
  packages/access-token/jsconfig.json
  packages/agoric-cli/jsconfig.json
  packages/assert/jsconfig.json
  packages/cache/jsconfig.json
  packages/casting/jsconfig.json
  packages/cosmic-proto/tsconfig.json
  packages/cosmic-swingset/jsconfig.json
  packages/deploy-script-support/jsconfig.json
  packages/deployment/jsconfig.json
  packages/governance/jsconfig.json
  packages/import-manager/jsconfig.json
  packages/inter-protocol/jsconfig.json
  packages/internal/jsconfig.json
  packages/notifier/jsconfig.json
  packages/pegasus/jsconfig.json
  packages/same-structure/jsconfig.json
  packages/sharing-service/jsconfig.json
  packages/smart-wallet/jsconfig.json
  packages/solo/jsconfig.json
  packages/sparse-ints/jsconfig.json
  packages/sparse-ints/package.json
  packages/spawner/jsconfig.json
  packages/stat-logger/jsconfig.json
  packages/stat-logger/package.json
  packages/store/jsconfig.json
  packages/swing-store/jsconfig.json
  packages/swing-store/test/test-hasher.js
  packages/swingset-liveslots/jsconfig.json
  packages/swingset-runner/jsconfig.json
  packages/telemetry/jsconfig.json
  packages/time/jsconfig.json
  packages/ui-components/jsconfig.json
  packages/vat-data/tsconfig.json
  packages/vats/jsconfig.json
  packages/wallet/api/jsconfig.json
  packages/web-components/jsconfig.json
  packages/xsnap-lockdown/jsconfig.json
  packages/xsnap/jsconfig.json
  packages/zoe/jsconfig.json
  tsconfig.json
Labels: automerge:merge

#7100 refactor: faster assert style
  packages/ERTP/src/paymentLedger.js
  packages/internal/src/createBundles.js
  packages/internal/src/storage-test-utils.js
  packages/internal/src/utils.js
  packages/store/src/stores/store-utils.js
  packages/time/src/timeMath.js
  packages/vat-data/src/vat-data-bindings.js
  packages/zoe/src/contractFacet/vatRoot.js
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contractSupport/priceAuthorityTransform.js
  packages/zoe/src/contractSupport/priceQuote.js
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/issuerStorage.js
  packages/zoe/src/zoeService/feeMint.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/offer/burnInvitation.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/tools/fakePriceAuthority.js
  packages/zoe/tools/fakeVatAdmin.js
  packages/zoe/tools/manualTimer.js
Labels: automerge:squash

#6866 feat(notifier)!: housecleaning
  packages/SwingSet/test/metering/vat-load-dynamic.js
  packages/assert/src/assert.js
  packages/casting/src/follower.js
  packages/casting/src/iterable.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/test/metrics.js
  packages/internal/src/index.js
  packages/internal/src/typeGuards.js
  packages/notifier/README.md
  packages/notifier/exports.js
  packages/notifier/jsconfig.json
  packages/notifier/package.json
  packages/notifier/src/asyncIterableAdaptor.js
  packages/notifier/src/index.js
  packages/notifier/src/notifier.js
  packages/notifier/src/publish-kit.js
  packages/notifier/src/stored-notifier.js
  packages/notifier/src/stored-topic.js
  packages/notifier/src/storesub.js
  packages/notifier/src/subscribe.js
  packages/notifier/src/subscriber.js
  packages/notifier/src/topic.js
  packages/notifier/src/typeGuards.js
  packages/notifier/src/types-ambient.js
  packages/notifier/subscribe.js
  packages/notifier/test/iterable-testing-tools.js
  packages/notifier/test/test-makeNotifierFromSubscriber.js
  packages/notifier/test/test-notifier-examples.js
  packages/notifier/test/test-publish-kit.js
  packages/notifier/test/test-stored-subscription.js
  packages/notifier/test/test-subscriber-examples.js
  packages/smart-wallet/src/smartWallet.js
  packages/solo/src/chain-cosmos-sdk.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/types.js
  packages/wallet/api/test/test-lib-wallet.js
  packages/zoe/src/contractSupport/durability.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
Labels: notifier, automerge:merge

#7000 feat(auction): add an auctioneer to manage vault liquidation
  packages/SwingSet/tools/manual-timer.js
  packages/governance/src/constants.js
  packages/governance/src/contractGovernance/assertions.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/src/contractHelper.js
  packages/governance/src/types-ambient.js
  packages/inter-protocol/scripts/add-collateral-core.js
  packages/inter-protocol/scripts/deploy-contracts.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/offerBook.js
  packages/inter-protocol/src/auction/params.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/src/auction/sortedOffers.js
  packages/inter-protocol/src/auction/util.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/storeUtils.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-computeRoundTiming.js
  packages/inter-protocol/test/auction/test-proportionalDist.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/auction/test-sortedOffers.js
  packages/inter-protocol/test/auction/tools.js
  packages/inter-protocol/test/swingsetTests/setup.js
  packages/internal/src/utils.js
  packages/time/src/typeGuards.js
  packages/vats/decentral-psm-config.json
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/ratio.js
Labels: enhancement, Zoe Contract, automerge:squash, Vaults, MUST-HAVE

#6816 fix: adapt to deeplyFulfilled being async
  packages/internal/src/utils.js
  packages/store/src/patterns/exo-tools.js
Labels: automerge:squash

#7122 fix: patch solo wallet to not depend on local.agoric.com
  patches/@agoric+wallet-ui+0.1.3-solo.0.patch
Labels: automerge:rebase

#7128 fix(ci): detect all repo changes during build
  .github/actions/restore-node/action.yml
  packages/xsnap/build-env
Labels: automerge:rebase

#7111 6678 assetRegistry through walletFactory upgrade
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/smart-wallet/package.json
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/bootstrap-walletFactory-service-upgrade.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/test-walletFactory-service-upgrade.js
  packages/smart-wallet/test/test-addAsset.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/tools/bank-utils.js
Labels: automerge:merge

#7120 chore: touch up bundleTool output
  packages/SwingSet/tools/bundleTool.js
Labels: automerge:merge, bypass:integration

#7097 refactor: clean up inbound queue ante handler and add unit tests
  golang/cosmos/ante/inbound.go
  golang/cosmos/ante/inbound_test.go
  golang/cosmos/vm/controller.go
  golang/cosmos/x/swingset/types/msgs.go
Labels: bug, cosmic-swingset, automerge:merge

#7133 fix(agops): collateralBrandKey option name
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/vaults.js
Labels: automerge:merge, bypass:integration

#7131 misc refactorings
  packages/inter-protocol/src/auction/auctioneer.js
  packages/smart-wallet/src/smartWallet.js
  packages/store/src/stores/store-utils.js
  packages/zoe/src/contractSupport/ratio.js
Labels: automerge:merge

#7135 7004 wallet errors
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/payments.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/devices.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/bootstrap-walletFactory-service-upgrade.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
Labels: automerge:merge

#7136 7025 eliminate staging
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/reserve/doc.md
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/zoe/test/unitTests/bounty.js
  packages/zoe/test/unitTests/contracts/loan/test-liquidate.js
Labels: automerge:merge

#7140 chore(types): document store type parameters
  packages/SwingSet/src/vats/network/router.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/store/src/keys/checkKey.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/types.js
  packages/vats/tools/bank-utils.js
  packages/wallet/api/src/lib-wallet.js
  packages/zoe/src/contractFacet/rightsConservation.js
Labels: automerge:merge

#7067 fix: stratify customDetails
  packages/zoe/src/zoeService/zoeStorageManager.js
Labels: automerge:squash

#7144 ci(runner): bump actions/setup-node to v3
  .github/actions/restore-node/action.yml
  .github/workflow-templates/test-dapp.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/integration.yml
  .github/workflows/test-dapp-card-store.yml.DISABLED
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml.DISABLED
  .github/workflows/test-documentation.yml
Labels: automerge:merge

#7147 board remote as remotable
  packages/agoric-cli/src/commands/ec.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/rpc.js
  packages/inter-protocol/src/clientSupport.js
  packages/smart-wallet/src/utils.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/test-board-utils.js
  packages/vats/tools/board-utils.js
Labels: automerge:merge, bypass:integration

#7139 use entries to represent maps in vstorage
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/lib/format.js
  packages/inter-protocol/src/clientSupport.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/test/test-walletFactory.js
Labels: automerge:merge

#7164 refactor(zoe): more precise startInstance
  packages/zoe/src/zoeService/startInstance.js
Labels: automerge:squash

#7163 fix: awaits were missing in tests
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/zoe/test/unitTests/contracts/loan/test-addCollateral.js
  packages/zoe/test/unitTests/contracts/loan/test-loan-e2e.js
  packages/zoe/test/unitTests/contracts/test-callSpread.js
Labels: automerge:squash

#7166 fix: change docker publishing to github
  .github/workflows/docker.yml
  packages/deployment/Dockerfile
  packages/deployment/Dockerfile.ibc-alpha
  packages/solo/Dockerfile
Labels: automerge:rebase

#7169 chore: avoid some unnecessary bundling in vaultFactory etc.
  packages/governance/src/index.js
  packages/governance/test/unitTests/test-binaryballotCount.js
  packages/vats/src/tokens.js
  packages/vats/test/test-tokens.js
Labels: automerge:rebase, bypass:integration

#7026 feat: implement swingStore data export/import in support of state sync
  packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/device-plugin/test-device.js
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/test-xsnap-metering.js
  packages/SwingSet/test/test-xsnap-store.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/vat-warehouse/test-preload.js
  packages/SwingSet/test/vat-warehouse/test-reload-snapshot.js
  packages/swing-store/docs/data-export.md
  packages/swing-store/docs/images/data-export-1.jpg
  packages/swing-store/docs/images/data-export-2a.jpg
  packages/swing-store/docs/images/data-export-2b.jpg
  packages/swing-store/docs/images/data-export-3.jpg
  packages/swing-store/docs/images/data-export-4.jpg
  packages/swing-store/package.json
  packages/swing-store/src/hasher.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/streamStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/src/transcriptStore.js
  packages/swing-store/test/test-deletion.js
  packages/swing-store/test/test-exportImport.js
  packages/swing-store/test/test-snapstore.js
  packages/swing-store/test/test-state.js
  packages/swingset-runner/src/dumpstore.js
Labels: enhancement, SwingSet, automerge:rebase

#7130 fix(SwingSet): move promise rejection from stopVat to the kernel
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/kernelQueue.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/test/bootstrap-syscall-failure.js
  packages/SwingSet/test/test-marshal.js
  packages/SwingSet/test/test-promises.js
  packages/SwingSet/test/vat-durable-promise-watcher.js
  packages/SwingSet/test/vat-syscall-failure.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/stop-vat.js
  packages/swingset-liveslots/src/vpid-tracking.md
  packages/swingset-liveslots/src/watchedPromises.js
  packages/swingset-liveslots/test/liveslots-helpers.js
  packages/swingset-liveslots/test/storeGC/test-lifecycle.js
  packages/swingset-liveslots/test/storeGC/test-refcount-management.js
  packages/swingset-liveslots/test/storeGC/test-scalar-store-kind.js
  packages/swingset-liveslots/test/storeGC/test-weak-key.js
  packages/swingset-liveslots/test/test-baggage.js
  packages/swingset-liveslots/test/test-handled-promises.js
  packages/swingset-liveslots/test/test-initial-vrefs.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectGC.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
  packages/swingset-liveslots/tools/vo-test-harness.js
  packages/vat-data/src/exo-utils.js
  packages/vat-data/src/index.js
  packages/vat-data/src/kind-utils.js
  packages/vat-data/src/vat-data-bindings.js
Labels: SwingSet, automerge:merge

#7158 add (failing) tests of liveslots GC sensitivity
  packages/swingset-liveslots/test/mock-gc.js
  packages/swingset-liveslots/test/test-gc-sensitivity.js
  packages/swingset-liveslots/test/test-liveslots.js
Labels: automerge:rebase, liveslots

#7177 fix(store): fix exo-tools TSC problem
  packages/store/src/patterns/exo-tools.js
Labels: automerge:squash

#7094 vaultFactory proposal shapes
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
Labels: automerge:merge

#7037 build(cosmos): create build wrapper in `bin/agd`
  .github/actions/restore-node/action.yml
  bin/agd
  packages/cosmic-swingset/Makefile
  packages/solo/src/chain-cosmos-sdk.js
  packages/xsnap/build.env
  packages/xsnap/package.json
  packages/xsnap/src/build.js
  repoconfig.sh
Labels: automerge:merge, force:integration

#7057 feat(zone): abstract heap, virtual, and durable object interface
  .github/workflows/test-all-packages.yml
  packages/agoric-cli/src/sdk-package-names.js
  packages/store/src/patterns/exo-makers.js
  packages/store/src/types.js
  packages/store/test/test-heap-classes.js
  packages/vat-data/src/index.js
  packages/vat-data/src/vat-data-bindings.js
  packages/zone/durable.js
  packages/zone/heap.js
  packages/zone/jsconfig.json
  packages/zone/package.json
  packages/zone/src/durable.js
  packages/zone/src/heap.js
  packages/zone/src/index.js
  packages/zone/src/virtual.js
  packages/zone/virtual.js
Labels: tooling, automerge:merge, stores, contract-upgrade

#7154 bump deps
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/access-token/package.json
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/sharing-service/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/ui-components/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/web-components/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  patches/ava+5.2.0.patch
  patches/rxjs+7.5.5.patch
  yarn.lock
Labels: automerge:merge

#7184 7181 durable auctioneer
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/offerBook.js
  packages/inter-protocol/src/clientSupport.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/test-clientSupport.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/watchedPromises.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/client-behaviors.js
  packages/vats/src/core/lib-boot.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/src/ibc.js
  packages/vats/src/nameHub.js
  packages/vats/src/provisionPool.js
  packages/vats/src/repl.js
  packages/vats/src/vat-provisioning.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-demo-config.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/test-vat-bank.js
  packages/vats/test/test-vpurse.js
  packages/vats/tools/authorityViz.js
Labels: automerge:merge

#7141 WIP fix: fewer deprecated defineKind etc
  packages/zoe/src/contractFacet/zcfMint.js
Labels: automerge:squash

#7189 build(deployment): install symlinks in Docker `/usr/local/bin`
  bin/agd
  packages/deployment/Dockerfile.sdk
Labels: deployment, automerge:merge

#7113 fix: remove deprecated issuer payment methods
  packages/ERTP/src/legacy-payment-helpers.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/typeGuards.js
  packages/ERTP/src/types-ambient.js
  packages/ERTP/test/unitTests/test-legacy-payment-helpers.js
Labels: automerge:squash

#7194 eslint extend @endo/recommended
  .eslintrc.cjs
  package.json
  packages/ERTP/test/swingsetTests/ertpService/bootstrap-ertp-service-upgrade.js
  packages/ERTP/test/swingsetTests/ertpService/vat-ertp-service.js
  packages/SwingSet/test/vat-controller-1.js
  packages/agoric-cli/src/lib/casting.js
  packages/agoric-cli/tools/resm-plugin/src/plugin.js
  packages/eslint-config/eslint-config.cjs
  packages/eslint-config/eslint-config.json
  packages/eslint-config/package.json
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/inter-protocol/src/price/fluxAggregator.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/test/swingsetTests/governance/bootstrap.js
  packages/inter-protocol/test/swingsetTests/governance/vat-alice.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/bootstrap.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/inter-protocol/test/vaultFactory/test-vault-collateralization.js
  packages/inter-protocol/test/vaultFactory/test-vault-pause.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
  packages/internal/src/config.js
  packages/swingset-liveslots/src/liveslots.js
  packages/ui-components/src/ratio.js
  packages/web-components/src/keplr-connection/KeplrConnection.js
  packages/web-components/src/keplr-connection/getChainInfo.js
  packages/web-components/src/keplr-connection/getKeplrAddress.js
  packages/web-components/src/keplr-connection/watchWallet.js
  packages/zoe/test/swingsetTests/zoe/vat-alice.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  yarn.lock
Labels: automerge:merge

#7186 fix: rename docker image root
  packages/agoric-cli/src/cosmos.js
  packages/agoric-cli/src/start.js
  packages/cosmic-swingset/Makefile
  packages/deployment/Makefile
  packages/deployment/docker/ag-setup-cosmos
  packages/deployment/terraform/docker/cluster/main.tf
  scripts/docker-tag.sh
Labels: automerge:squash

#7200 ci: add simple smoketest to binaries for docker, and add docker build to the PR ci
  .github/workflows/test-all-packages.yml
  packages/deployment/Dockerfile.sdk
  packages/deployment/scripts/smoketest-binaries.sh
  packages/deployment/scripts/test-docker-build.sh
  scripts/ci-collect-testruns.sh
Labels: automerge:rebase

#7206 cleanup: remove .appveyor
  .appveyor/appveyor.yml
  .appveyor/build.sh
  .appveyor/install-build-tools.sh
  .appveyor/install-go.sh
  .appveyor/install-node-13.sh
  .appveyor/install-nvm.sh
  .appveyor/install-yarn.sh
  .appveyor/no-stderr
  .appveyor/test.sh
Labels: automerge:rebase

#7203 fix: include liquidationMargin in liquidation
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/src/vaultFactory/prioritizedVaults.js
  packages/inter-protocol/src/vaultFactory/storeUtils.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-collatRatio.js
  packages/inter-protocol/test/vaultFactory/test-prioritizedVaults.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: bug, Inter-protocol, automerge:squash, Vaults

#7202 bump ESLint 8 / airbnb-base 15
  package.json
  packages/deployment/src/init.js
  packages/eslint-config/eslint-config.cjs
  packages/eslint-config/package.json
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-sortedOffers.js
  packages/web-components/package.json
  packages/zoe/src/internal-types.js
  yarn.lock
Labels: automerge:rebase

#7207 ci: coverage
  .github/workflows/test-all-packages.yml
  codecov.yaml
  scripts/ci-collect-testruns.sh
Labels: automerge:rebase

#7214 ci: code coverage for golang
  .github/workflows/test-golang.yml
  .gitignore
  codecov.yaml
Labels: automerge:rebase

#7195 fix(action): handle missing Collateral allocation
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
Labels: automerge:rebase, bypass:integration

#7107 Rename `vat-chainStorage` to `vat-bridge` and make it upgradable
  codecov.yaml
  packages/SwingSet/docs/vat-upgrade.md
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/devices/bridge/device-bridge.js
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/SwingSet/test/bootstrap-relay.js
  packages/SwingSet/tools/passableEncoding.js
  packages/internal/package.json
  packages/internal/src/callback.js
  packages/internal/src/lib-chainStorage.js
  packages/internal/src/method-tools.js
  packages/internal/src/storage-test-utils.js
  packages/internal/src/types.d.ts
  packages/internal/src/utils.js
  packages/internal/test/test-callback.js
  packages/internal/test/test-utils.js
  packages/vats/decentral-core-config.json
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-main-psm-config.json
  packages/vats/decentral-psm-config.json
  packages/vats/decentral-test-psm-config.json
  packages/vats/decentral-test-vaults-config.json
  packages/vats/package.json
  packages/vats/src/bridge.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types.js
  packages/vats/src/vat-bridge.js
  packages/vats/src/vat-chainStorage.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/snapshots/test-boot-config.js.md
  packages/vats/test/snapshots/test-boot-config.js.snap
  packages/vats/test/upgrading/device-bridge.js
  packages/vats/test/upgrading/test-upgrade-vats.js
  packages/zoe/tools/internal-types.js
  packages/zoe/tools/manualTimer.js
  packages/zone/README.md
Labels: cosmic-swingset, automerge:merge, contract-upgrade

#7205 fix(oracle): default restartDelay parameter
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/inter-protocol/scripts/price-feed-core.js
  packages/inter-protocol/src/price/fluxAggregator.js
  packages/inter-protocol/src/price/priceOracleKit.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/test/price/test-fluxAggregator.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
Labels: automerge:merge

#7224 Implement `test:xs` for `vats` package
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/vats/package.json
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-demo-config.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/upgrading/test-upgrade-contracts.js
  packages/vats/test/upgrading/test-upgrade-vats.js
  scripts/configure-vscode.sh
Labels: cosmic-swingset, automerge:merge

#7230 fix devDependencies glob for import/no-extraneous-dependencies
  .eslintrc.cjs
  packages/eslint-config/eslint-config.cjs
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/sparse-ints/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swingset-runner/package.json
  packages/zoe/package.json
Labels: automerge:merge, bypass:integration

#7222 fix(xsnap-lockdown): change the API to get hash of the lockdown bundle
  packages/xsnap-lockdown/README.md
  packages/xsnap-lockdown/scripts/build-bundle.js
  packages/xsnap-lockdown/src/index.js
  packages/xsnap-lockdown/src/paths.js
  packages/xsnap-lockdown/test/test-bundle.js
Labels: SwingSet, automerge:squash

#7233 improve error thrown during collection.get(missingRemotable)
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/test/test-collections.js
  packages/zoe/test/unitTests/contracts/test-throwInOfferHandler.js
  packages/zoe/test/unitTests/test-issuerStorage.js
  packages/zoe/test/unitTests/zcf/test-zoeHelpersWZcf.js
Labels: SwingSet, automerge:rebase

#7235 refactor startXSnap
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/controller/startXSnap.js
  packages/SwingSet/test/bundling/test-bundles-kernel.js
  packages/SwingSet/test/test-abandon-export.js
  packages/SwingSet/test/test-gc-kernel.js
  packages/SwingSet/test/test-kernel.js
  packages/SwingSet/test/test-vpid-kernel.js
  packages/SwingSet/test/test-xsnap-errors.js
  packages/SwingSet/test/test-xsnap-metering.js
Labels: SwingSet, automerge:rebase

#7238 ci: disable codecov annotations
  codecov.yaml
Labels: automerge:merge, bypass:integration

#7176 feat: implement bundleStore
  packages/SwingSet/src/types-external.js
  packages/swing-store/package.json
  packages/swing-store/src/bundleStore.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/src/util.js
  packages/swing-store/test/bohr-module.js
  packages/swing-store/test/faux-module.js
  packages/swing-store/test/test-exportImport.js
  packages/swing-store/test/test-state.js
Labels: enhancement, SwingSet, automerge:rebase

#7217 chore: Correct a misspelling of "Remotable"
  packages/SwingSet/test/test-comms.js
Labels: automerge:rebase

#7227 refactor(internal): Rename an object property to indicate expected string value
  packages/internal/src/callback.js
  packages/internal/src/types.d.ts
  packages/internal/test/test-callback.js
Labels: automerge:rebase

#7028 feat(smart-wallet): exit offer
  packages/inter-protocol/src/clientSupport.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/test-clientSupport.js
  packages/internal/src/storage-test-utils.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/utils.js
  packages/vats/src/core/lib-boot.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/tools/board-utils.js
Labels: automerge:merge

#6794 feat(fluxAggregator): add startedBy to latestRoundPublisher
  packages/inter-protocol/src/price/README.md
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/test/price/test-fluxAggregator.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
Labels: automerge:squash, bypass:integration

#7241 enforce that buildRootObject() returns an ephemeral, not durable
  packages/SwingSet/docs/static-vats.md
  packages/SwingSet/docs/vat-upgrade.md
  packages/SwingSet/src/vats/vattp/vat-vattp.js
  packages/SwingSet/test/vat-admin/durable-root-vat.js
  packages/SwingSet/test/vat-admin/test-create-vat.js
  packages/swingset-liveslots/docs/liveslots.md
  packages/swingset-liveslots/src/liveslots.js
Labels: SwingSet, automerge:rebase, liveslots

#7252 ci(deployment): remove tracing from integration-test
  packages/deployment/scripts/integration-test.sh
Labels: tooling, automerge:squash, force:integration

#7132 initial inter liquidation bidding CLI
  packages/agoric-cli/package.json
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/lib/chain.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/snapshots/test-inter-cli.js.md
  packages/agoric-cli/test/snapshots/test-inter-cli.js.snap
  packages/agoric-cli/test/test-inter-cli.js
  packages/inter-protocol/src/clientSupport.js
  packages/inter-protocol/test/test-clientSupport.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
Labels: automerge:rebase

#7174 docs: Update MAINTAINERS.md with notes from pismoC post release discussion
  MAINTAINERS.md
Labels: documentation, automerge:rebase, bypass:integration

#7232 fix(inter-protocol): add to reserve did not update metrics
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/test/reserve/test-reserve.js
Labels: automerge:squash, bypass:integration

#7254 ci: detect and warn about stale prs
  .github/actions/notify-status/action.yml
  .github/workflows/cron-stale-prs.yml
Labels: automerge:rebase

#6885 README for vat-data
  packages/vat-data/README.md
Labels: automerge:merge

#7257 fix: adding dup entries to virtual sets is OK
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/test/test-collections.js
Labels: bug, automerge:rebase, liveslots

#7255 ci: explicitly ignore jsons
  .github/actions/post-test/action.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-golang.yml
  codecov.yaml
Labels: automerge:rebase

#7247 7246 fix vaults list
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/snapshots/test-inter-cli.js.md
  packages/agoric-cli/test/snapshots/test-inter-cli.js.snap
  packages/agoric-cli/test/test-inter-cli.js
Labels: automerge:merge, bypass:integration

#7251 feat: Integrate kernel with bundleStore
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/test/bundling/test-bundles-kernel.js
  packages/SwingSet/test/commsVatDriver.js
  packages/swing-store/src/bundleStore.js
Labels: enhancement, SwingSet, automerge:rebase

#7242 feat(swingstore): add support for b0- bundles
  packages/SwingSet/test/bundling/test-bundles-kernel.js
  packages/swing-store/package.json
  packages/swing-store/src/bundleStore.js
  packages/swing-store/test/test-bundles.js
Labels: SwingSet, automerge:rebase

#7262 ci: enforce lower ci job timeout
  .github/workflows/deployment-test.yml
  .github/workflows/test-all-packages.yml
Labels: automerge:squash, bypass:integration

#5577 fix: minor tweak to make `sortObjectProperties` use `hasOwn`
  packages/SwingSet/src/controller/initializeSwingset.js
Labels: SwingSet, hygiene, automerge:rebase

#7239 feat(auction): Auction allows vaults to specify an amount to raise
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-proportionalDist.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: Inter-protocol, automerge:squash, Vaults

#7269 feat(auction): allow orders to automatically exit after partial fill
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/offerBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
Labels: Zoe Contract, Inter-protocol, automerge:squash, Vaults

#7210 minimum bid for auction
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/test/auction/test-auctionContract.js
Labels: automerge:merge

#7258 refactor: move around some helpers before state-sync
  golang/cosmos/x/swingset/keeper/keeper.go
  packages/cosmic-swingset/scripts/clean-core-eval.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/helpers/bufferedStorage.js
  packages/cosmic-swingset/src/helpers/is-entrypoint.js
  packages/cosmic-swingset/src/helpers/json-stable-stringify.js
  packages/cosmic-swingset/src/helpers/make-queue.js
  packages/cosmic-swingset/src/helpers/process-value.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/deploy-script-support/src/helpers.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/governance/scripts/build-bundles.js
  packages/inter-protocol/scripts/build-bundles.js
  packages/internal/package.json
  packages/internal/src/node/createBundles.js
  packages/internal/src/node/fs-stream.js
  packages/internal/src/node/shutdown.js
  packages/smart-wallet/scripts/build-bundles.js
  packages/solo/src/pipe-entrypoint.js
  packages/solo/src/pipe.js
  packages/solo/src/start.js
  packages/spawner/scripts/build-bundles.js
  packages/swing-store/src/snapStore.js
  packages/telemetry/src/otel-trace.js
  packages/telemetry/src/slog-file.js
  packages/telemetry/src/slog-sender-pipe-entrypoint.js
  packages/telemetry/src/slog-sender-pipe.js
  packages/vats/scripts/build-bundles.js
  packages/wallet/api/scripts/build-bundles.js
  packages/zoe/scripts/build-bundles.js
Labels: automerge:rebase

#7280 test for vaults perf
  .gitignore
  packages/inter-protocol/src/clientSupport.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-vaults-performance.js
Labels: automerge:merge

#7259 Various swing-store fixes
  packages/internal/src/node/buffer-line-transform.js
  packages/swing-store/package.json
  packages/swing-store/src/bundleStore.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/src/transcriptStore.js
  packages/swing-store/test/test-bundles.js
  packages/swing-store/test/test-state.js
Labels: automerge:rebase

#7285 lint: adds a warn lint for incorrect terminology
  .eslintrc.cjs
Labels: automerge:rebase

#7288 lint: specify name for identifier
  .eslintrc.cjs
Labels: automerge:rebase

#7293 fix: update package.json engines to 16 LTS
  package.json
Labels: automerge:squash, bypass:integration

#7294 fix Zoe offerResult durability handling
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoeSeat.js
Labels: automerge:rebase

#7296 fix(vaults): durable invitationMakers
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
Labels: automerge:rebase
