Repository Agoric/agoric-sdk, pull requests merged in 2023-04, with the labels that each got.

#7304 fix: only the exo api change
  packages/store/src/patterns/exo-makers.js
  packages/store/src/patterns/exo-tools.js
  packages/swingset-liveslots/src/virtualObjectManager.js
Labels: automerge:rebase

#7299 fix: agops: no I/O (errors) until command action
  packages/agoric-cli/src/commands/ec.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/reserve.js
  packages/agoric-cli/src/commands/vaults.js
Labels: automerge:rebase

#7301 fix(wallet): recording handleBridgeAction errors
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/test-walletFactory.js
Labels: automerge:rebase

#7121 docs: document upgrade requirement for prepare
  packages/zoe/README.md
Labels: automerge:rebase

#5389 style: disable space-comment eslint rule
  packages/eslint-config/eslint-config.cjs
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/test/psm/gov-replace-committee.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/test-proposal-stuff.js
  packages/inter-protocol/test/vaultFactory/test-math.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/test-startWalletFactory.js
  packages/solo/test/test-home.js
  packages/vats/src/core/lib-boot.js
  packages/vats/src/lib-board.js
  packages/vats/test/test-boot-config.js
  packages/vats/test/test-boot.js
Labels: automerge:merge, bypass:integration

#7320 refactor: resync endo MinMethodGuard migration
  packages/store/src/patterns/exo-tools.js
  packages/store/src/patterns/patternMatchers.js
Labels: automerge:rebase

#7305 fix: connect auctioneer governance to EC charter
  packages/inter-protocol/src/proposals/committee-proposal.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/src/core/utils.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/snapshots/test-boot-config.js.md
  packages/vats/test/snapshots/test-boot-config.js.snap
Labels: automerge:rebase

#7314 7313 enforce min initial debt
  packages/inter-protocol/src/vaultFactory/math.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-math.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
Labels: automerge:merge

#7326 fix: update eslint-plugin-import to absorb json5@1.0.2
  yarn.lock
Labels: automerge:rebase

#7244 fix(SwingSet): Don't send stopVat during upgrade
  packages/SwingSet/docs/garbage-collection.md
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/test/bootstrap-relay.js
  packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js
  packages/SwingSet/test/upgrade/num-sensors.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/vat-exporter.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/stop-vat.js
Labels: automerge:merge

#7327 fix: update bufferfromfile
  patches/bufferfromfile+0.4.377.patch
  yarn.lock
Labels: automerge:rebase

#7307 Improve swingset tests
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/virtualObjects/test-facet-retention.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bob.js
  packages/SwingSet/test/virtualObjects/vat-orphan-bootstrap.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/test/test-liveslots-mock-gc.js
  packages/swingset-liveslots/test/test-liveslots-real-gc.js
  packages/swingset-liveslots/test/test-liveslots.js
  packages/swingset-liveslots/test/test-vo-test-harness.js
  packages/swingset-liveslots/test/virtual-objects/test-cross-facet.js
  packages/swingset-liveslots/test/virtual-objects/test-empty-data.js
Labels: SwingSet, automerge:rebase, liveslots

#7272 persist xsnap bundle IDs at vat creation/upgrade
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/bundle-handler.js
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/controller/startXSnap.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/lib/workerOptions.js
  packages/SwingSet/src/typeGuards.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/test-bundle-handler.js
  packages/SwingSet/test/test-controller.js
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/test-xsnap-errors.js
  packages/SwingSet/test/test-xsnap-metering.js
  packages/SwingSet/test/workers/test-worker.js
  packages/SwingSet/test/xsnap-stable-bundles/test-stable-bundles.js
  packages/SwingSet/test/xsnap-stable-bundles/vat-stable.js
Labels: SwingSet, automerge:rebase

#7138 rewrite VOM LRU cache
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/change-parameters/test-change-parameters.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate-replay.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
  packages/SwingSet/test/virtualObjects/collection-slots/test-collection-slots.js
  packages/SwingSet/test/virtualObjects/delete-stored-vo/test-delete-stored-vo.js
  packages/SwingSet/test/virtualObjects/double-retire-import/bootstrap-dri.js
  packages/SwingSet/test/virtualObjects/test-facet-retention.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/SwingSet/test/virtualObjects/vat-representatives.js
  packages/SwingSet/test/virtualObjects/vdata-promises/test-vdata-promises.js
  packages/SwingSet/tools/prepare-test-env.js
  packages/swingset-liveslots/src/cache.js
  packages/swingset-liveslots/src/facetiousness.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/parseVatSlots.js
  packages/swingset-liveslots/src/types.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/src/virtualReferences.js
  packages/swingset-liveslots/test/liveslots-helpers.js
  packages/swingset-liveslots/test/test-baggage.js
  packages/swingset-liveslots/test/test-cache.js
  packages/swingset-liveslots/test/test-durabilityChecks.js
  packages/swingset-liveslots/test/test-facetiousness.js
  packages/swingset-liveslots/test/test-gc-sensitivity.js
  packages/swingset-liveslots/test/test-liveslots.js
  packages/swingset-liveslots/test/virtual-objects/test-cross-facet.js
  packages/swingset-liveslots/test/virtual-objects/test-facets.js
  packages/swingset-liveslots/test/virtual-objects/test-reachable-vrefs.js
  packages/swingset-liveslots/test/virtual-objects/test-retain-remotable.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectCache.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
  packages/swingset-liveslots/test/virtual-objects/test-vo-real-gc.js
  packages/swingset-liveslots/test/virtual-objects/test-weakcollections-vref-handling.js
  packages/swingset-liveslots/tools/fakeVirtualObjectManager.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
Labels: SwingSet, automerge:rebase, liveslots

#7323 scope restricted-syntax
  .eslintrc.cjs
Labels: automerge:merge, bypass:integration

#7336 feat: support version suffix to publish `dev` dist-tags
  MAINTAINERS.md
  scripts/npm-dist-tag.sh
Labels: tooling, automerge:merge, bypass:integration

#7168 Add rosetta testing to CI
  packages/agoric-cli/src/chain-config.js
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/bootstrap.json
  packages/cosmic-swingset/rosetta.json
  packages/cosmic-swingset/scripts/faucet.py
  packages/cosmic-swingset/scripts/run-rosetta-ci.sh
  packages/cosmic-swingset/scripts/send_funds.sh
  packages/cosmic-swingset/test/scenario2.js
  packages/cosmic-swingset/test/test-make.js
  packages/cosmic-swingset/transfer.ros
  packages/rosetta/README.md
  packages/rosetta/configuration/faucet.py
  packages/rosetta/configuration/run_tests.sh
  packages/rosetta/configuration/send_funds.sh
  packages/rosetta/docker-compose.yaml
  packages/rosetta/rosetta-ci/Dockerfile
  scripts/build-rosetta-ci.sh
Labels: automerge:rebase

#7335 feat: governable interestTiming
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/src/contractHelper.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/swingsetTests/setup.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
Labels: automerge:merge

#7345 remove obsolete swingset tests
  packages/inter-protocol/test/swingsetTests/governance/bootstrap.js
  packages/inter-protocol/test/swingsetTests/governance/test-governance.js
  packages/inter-protocol/test/swingsetTests/governance/vat-alice.js
  packages/inter-protocol/test/swingsetTests/governance/vat-owner.js
  packages/inter-protocol/test/swingsetTests/governance/vat-priceAuthority.js
  packages/inter-protocol/test/swingsetTests/governance/vat-voter.js
  packages/inter-protocol/test/swingsetTests/governance/vat-zoe.js
  packages/inter-protocol/test/swingsetTests/mockAmm.js
  packages/inter-protocol/test/swingsetTests/setup.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/bootstrap.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/vat-alice.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/vat-owner.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/vat-priceAuthority.js
  packages/inter-protocol/test/swingsetTests/vaultFactory/vat-zoe.js
Labels: automerge:merge, bypass:integration

#7341 fix(notifier): Add a makeDurablePublishKit "onAdvance" option
  packages/internal/src/callback.js
  packages/internal/test/test-callback.js
  packages/notifier/src/publish-kit.js
  packages/notifier/src/types-ambient.js
  packages/notifier/test/test-publish-kit.js
  packages/notifier/test/vat-integration/vat-pubsub.js
  patches/@endo+marshal+0.8.1.patch
Labels: automerge:merge

#7290 feat: add new bean cost for bytes in permanent storage
  golang/cosmos/x/swingset/keeper/migrations.go
  golang/cosmos/x/swingset/legacy/v32/params.go
  golang/cosmos/x/swingset/legacy/v32/params_test.go
  golang/cosmos/x/swingset/module.go
  golang/cosmos/x/swingset/types/default-params.go
  golang/cosmos/x/swingset/types/msgs.go
Labels: enhancement, automerge:merge, agoric-cosmos

#7330 Workaround ava worker deadlocks
  packages/ERTP/test/swingsetTests/ertpService/test-ertp-service-upgrade.js
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/test/test-message-patterns.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate-replay.js
  packages/SwingSet/test/zcf-ish-upgrade/test-zcf-ish-upgrade.js
  packages/agoric-cli/test/test-publish-bundle.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/test-walletFactory-service-upgrade.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-demo-config.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/bootstrapTests/test-vaults-performance.js
  packages/vats/test/upgrading/test-upgrade-contracts.js
  packages/xsnap/test/test-boot-lockdown.js
  packages/xsnap/test/test-err-stack.js
  packages/xsnap/test/test-inspect.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/test-coveredCall-service-upgrade.js
  patches/ava+5.2.0.patch
Labels: automerge:rebase

#7351 refactor: Vaults get price updates continuously
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
Labels: Inter-protocol, automerge:rebase, Vaults

#7223 `gen-upgrade-proposal.sh` chain software upgrade helper
  bin/agd
  scripts/gen-upgrade-proposal.sh
Labels: tooling, automerge:rebase, bypass:integration

#7360 chore(store): Define narrow VOM context types
  packages/store/src/patterns/exo-makers.js
  packages/store/src/patterns/exo-tools.js
Labels: automerge:squash

#7339 7266 auction status
  packages/inter-protocol/README.md
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/scheduleMath.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-computeRoundTiming.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/metrics.js
  packages/zoe/tools/types-ambient.js
Labels: Inter-protocol, automerge:squash, Vaults, auction

#7145 chore(SwingSet): Consolidate logic for picking a queued event
  packages/SwingSet/src/kernel/gc-actions.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/test-state.js
Labels: automerge:merge

#7363 fix(store,ERTP): collection type param defaults
  packages/ERTP/src/mathHelpers/copyBagMathHelpers.js
  packages/ERTP/src/mathHelpers/copySetMathHelpers.js
  packages/ERTP/src/mathHelpers/natMathHelpers.js
  packages/ERTP/src/mathHelpers/setMathHelpers.js
  packages/ERTP/src/typeGuards.js
  packages/ERTP/src/types-ambient.js
  packages/ERTP/test/unitTests/mathHelpers/test-copyBagMathHelpers.js
  packages/ERTP/test/unitTests/mathHelpers/test-copySetMathHelpers.js
  packages/store/src/keys/checkKey.js
  packages/store/src/types.js
Labels: automerge:rebase

#7287 Fix every assert!! For great speediness!
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/devices/plugin/device-plugin.js
  packages/SwingSet/src/devices/vat-admin/device-vat-admin.js
  packages/SwingSet/src/kernel/deviceManager.js
  packages/SwingSet/src/kernel/deviceTranslator.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/kernelSyscall.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/reachable.js
  packages/SwingSet/src/kernel/state/stats.js
  packages/SwingSet/src/kernel/state/storageHelper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/SwingSet/src/lib/message.js
  packages/SwingSet/src/lib/parseVatSlots.js
  packages/SwingSet/src/vats/comms/clist-inbound.js
  packages/SwingSet/src/vats/comms/clist-kernel.js
  packages/SwingSet/src/vats/comms/clist-outbound.js
  packages/SwingSet/src/vats/comms/dispatch.js
  packages/SwingSet/src/vats/comms/gc-comms.js
  packages/SwingSet/src/vats/comms/state.js
  packages/SwingSet/src/vats/network/network.js
  packages/SwingSet/src/vats/network/router.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/bundling/test-bundles-controller.js
  packages/SwingSet/test/commsVatDriver.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-admin/test-create-vat.js
  packages/SwingSet/tools/bundleTool.js
  packages/SwingSet/tools/manual-timer.js
  packages/swing-store/src/swingStore.js
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/message.js
  packages/swingset-liveslots/src/parseVatSlots.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/src/virtualReferences.js
  packages/swingset-liveslots/test/vat-util.js
Labels: SwingSet, performance, hygiene, automerge:rebase

#7362 Add APIs for tracking/debugging undesired object retention (aka "leaks")
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/lib/message.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/types.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/src/virtualReferences.js
  packages/swingset-liveslots/test/test-liveslots-mock-gc.js
  packages/swingset-liveslots/test/test-liveslots.js
  packages/swingset-runner/demo/virtualObjectGC/swingset.json
  packages/swingset-xsnap-supervisor/lib/supervisor-helper.js
Labels: enhancement, SwingSet, performance, automerge:rebase

#7372 Improve test timeouts and gc sensitivity
  packages/SwingSet/test/test-message-patterns-comms.js
  packages/SwingSet/test/test-message-patterns-local.js
  packages/SwingSet/test/upgrade/test-upgrade-replay.js
  packages/SwingSet/test/vat-admin/test-replay.js
  patches/ava+5.2.0.patch
Labels: SwingSet, tooling, automerge:rebase

#7354 fix liveslots double-free of virtual object/collection
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/virtualReferences.js
  packages/swingset-liveslots/test/storeGC/test-weak-key.js
  packages/swingset-liveslots/test/test-liveslots-mock-gc.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
Labels: SwingSet, automerge:rebase, force:integration, liveslots

#7333 cache the collection schema, only read from vatstore once per crank
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/swingset-liveslots/src/cache.js
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/vatstore-usage.md
  packages/swingset-liveslots/test/gc-helpers.js
  packages/swingset-liveslots/test/storeGC/test-lifecycle.js
  packages/swingset-liveslots/test/test-baggage.js
  packages/swingset-liveslots/test/test-gc-sensitivity.js
  packages/swingset-liveslots/test/test-handled-promises.js
  packages/swingset-liveslots/test/test-initial-vrefs.js
  packages/swingset-liveslots/test/test-liveslots-mock-gc.js
  packages/swingset-liveslots/test/test-liveslots.js
Labels: SwingSet, automerge:rebase, force:integration, liveslots

#7334 collectionManager: refcount remotables in keyShape/valueShape
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/test/test-collection-schema-refcount.js
  packages/swingset-liveslots/test/test-collection-upgrade.js
Labels: SwingSet, automerge:rebase, liveslots

#7328 ci: attempt to fix dependabot again
  .github/dependabot.yml
Labels: automerge:rebase

#7387 terminate bootstrap vat on startup failure
  packages/vats/src/core/boot-chain.js
  packages/vats/src/core/boot-sim.js
  packages/vats/src/core/boot-solo.js
  packages/vats/src/core/lib-boot.js
  packages/vats/test/test-boot.js
Labels: automerge:merge

#7370 fix(notifier): Remove the makeDurablePublishKit "onUpdate" option
  packages/notifier/src/publish-kit.js
  packages/notifier/src/types-ambient.js
  packages/notifier/test/test-publish-kit.js
Labels: automerge:squash

#7393 rebalance CI
  .github/workflows/test-all-packages.yml
Labels: automerge:merge, bypass:integration

#7396 refactor(cosmic-swingset): remove notifier from bundle publish
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:merge, force:integration

#7374 Stop doing object-inspect type checks the hard way
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/xsnap-lockdown/lib/object-inspect.js
Labels: performance, hygiene, automerge:rebase

#7383 refactor(auction): settle detect excessive want before atomicRearrange
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/zoe/src/zoeService/types.js
Labels: Inter-protocol, automerge:squash, Vaults, auction

#7365 record durable-kind stateShape, with refcounts
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/types.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/test/virtual-objects/test-state-shape.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
Labels: SwingSet, automerge:rebase, liveslots

#7389 7300 remove pipeTopicToStorage
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/src/price/fluxAggregator.js
  packages/inter-protocol/src/price/fluxAggregatorContract.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/auction/tools.js
  packages/inter-protocol/test/price/test-fluxAggregator.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/notifier/src/index.js
  packages/notifier/src/stored-topic.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/utils.js
  packages/smart-wallet/test/supports.js
  packages/zoe/src/contractSupport/durability.js
  packages/zoe/src/contractSupport/recorder.js
  packages/zoe/src/contractSupport/topics.js
Labels: automerge:merge

#7386 chore: install devnet `oracleAddresses`
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-test-vaults-config.json
Labels: automerge:rebase

#7390 ci: updates and refinements to reconcile Endo
  .github/actions/restore-node/action.yml
  .github/workflow-templates/test-dapp.yml
  .github/workflows/deployment-test.yml
  .github/workflows/integration.yml
  .github/workflows/test-dapp-card-store.yml
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml.DISABLED
  .github/workflows/test-documentation.yml
  .github/workflows/update-hackathon-branch.yml.DISABLED
  scripts/replace-packages.sh
Labels: tooling, automerge:merge

#7409 feat(store): reconcile with endo #1554
  packages/store/src/patterns/exo-makers.js
  packages/store/test/prepare-test-env-ava-label-instances.js
  packages/store/test/prepare-test-env-ava.js
  packages/store/test/test-heap-classes.js
  packages/store/test/test-label-instances.js
Labels: automerge:rebase

#7414 test(vats): use test.after.always to shutdown kernel, and disable AVA's workerThreads
  packages/vats/package.json
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-demo-config.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/bootstrapTests/test-vaults-performance.js
Labels: tooling, automerge:squash, bypass:integration

#7410 feat(swingset-liveslots): label virtual instances
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/test/virtual-objects/set-debug-label-instances.js
  packages/swingset-liveslots/test/virtual-objects/test-rep-tostring.js
Labels: automerge:rebase

#7408 fix(vats): repl tolerates toStringTag override
  packages/vats/src/repl.js
  packages/vats/test/test-dump.js
Labels: automerge:rebase

#7417 chore: clean up bitrot in swingset-runner
  packages/swingset-runner/demo/exchangeBenchmark/bootstrap.js
  packages/swingset-runner/demo/exchangeBenchmark/exchanger.js
  packages/swingset-runner/demo/swapBenchmark/bootstrap.js
  packages/swingset-runner/demo/swapBenchmark/exchanger.js
  packages/swingset-runner/demo/zoeTests/bootstrap.js
  packages/swingset-runner/demo/zoeTests/prepareContracts.js
  packages/swingset-runner/demo/zoeTests/sampleArgs
  packages/swingset-runner/demo/zoeTests/swingset.json
  packages/swingset-runner/demo/zoeTests/vat-alice.js
  packages/swingset-runner/demo/zoeTests/vat-bob.js
  packages/swingset-runner/demo/zoeTests/vat-carol.js
  packages/swingset-runner/demo/zoeTests/vat-dave.js
  packages/swingset-runner/src/main.js
Labels: swingset-runner, automerge:rebase

#7391 fix: minor cleanups in preparation for Endo upgrade
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/solo/src/captp.js
  packages/solo/src/web.js
  packages/vats/src/core/types.js
  packages/zoe/src/contracts/mintAndSellNFT.js
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/test/unitTests/contracts/test-automaticRefund.js
Labels: test, automerge:merge

#7368 test(inter-protocol): snapshot storage/RPC API for auction, vaultFactory, reserve, psm, committees
  packages/governance/test/unitTests/snapshots/test-committee.js.md
  packages/governance/test/unitTests/snapshots/test-committee.js.snap
  packages/governance/test/unitTests/test-committee.js
  packages/governance/tools/storageDoc.js
  packages/inter-protocol/README.md
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.md
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.snap
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/price/snapshots/test-fluxAggregator.js.md
  packages/inter-protocol/test/price/snapshots/test-fluxAggregator.js.snap
  packages/inter-protocol/test/price/test-fluxAggregator.js
  packages/inter-protocol/test/psm/snapshots/test-psm.js.md
  packages/inter-protocol/test/psm/snapshots/test-psm.js.snap
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/reserve/setup.js
  packages/inter-protocol/test/reserve/snapshots/test-reserve.js.md
  packages/inter-protocol/test/reserve/snapshots/test-reserve.js.snap
  packages/inter-protocol/test/reserve/test-reserve.js
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/internal/src/storage-test-utils.js
Labels: automerge:rebase, bypass:integration

#7418 feat: Support for labeling contract vats at runtime
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
Labels: enhancement, Zoe, Zoe Contract, automerge:rebase

#7388 refactor(auction): make auction robust to time skipping forward
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-scheduler.js
Labels: Inter-protocol, automerge:squash, Vaults, auction

#7273 Endo integration
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/agoric-cli/src/follow.js
  packages/assert/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/inter-protocol/test/test-interest.js
  packages/inter-protocol/test/vaultFactory/test-storeUtils.js
  packages/internal/package.json
  packages/notifier/package.json
  packages/notifier/src/types-ambient.js
  packages/pegasus/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/vats/src/core/client-behaviors.js
  packages/vats/src/lib-board.js
  packages/vats/tools/board-utils.js
  packages/wallet/api/package.json
  packages/wallet/api/src/lib-wallet.js
  packages/web-components/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zone/package.json
  patches/@endo+bundle-source+2.4.2.patch
  patches/@endo+import-bundle+0.3.0.patch
  patches/@endo+marshal+0.8.1.patch
  patches/@endo+ses-ava+0.2.36.patch
  patches/@endo+static-module-record+0.7.15.patch
  patches/@endo+stream-node+0.2.22.patch
  patches/@lit+reactive-element+1.0.1.patch
  patches/lit+2.0.2.patch
  patches/lit-element+3.0.1.patch
  patches/lit-html+2.0.1.patch
  yarn.lock
Labels: dependencies, tooling, automerge:merge

#7415 fix: nextAuction timing when startFrequency is reduced
  packages/governance/src/types-ambient.js
  packages/inter-protocol/src/auction/params.js
  packages/inter-protocol/src/auction/scheduleMath.js
  packages/inter-protocol/src/auction/scheduler.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/auction/tools.js
Labels: Inter-protocol, automerge:squash, Vaults, auction

#7421 feat(zoe): error on unexpected properties from start()
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/test/unitTests/test-zoe.js
  packages/zoe/test/unitTests/unexpectedPropertiesContract.js
Labels: automerge:rebase

#7419 refactor(swingset-liveslots): rep vs instance label tests more similar
  packages/store/test/test-label-instances.js
  packages/swingset-liveslots/test/virtual-objects/test-rep-tostring.js
Labels: automerge:rebase

#7427 refactor(store): Use @endo/(pass-style,patterns,exo) and drop our stale copies
  packages/ERTP/src/paymentLedger.js
  packages/agoric-cli/src/follow.js
  packages/deploy-script-support/src/code-gen.js
  packages/deploy-script-support/src/depositInvitation.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/inter-protocol/src/vaultFactory/storeUtils.js
  packages/store/docs/exo-taxonomy.md
  packages/store/exported.js
  packages/store/package.json
  packages/store/src/index.js
  packages/store/src/keys/checkKey.js
  packages/store/src/keys/compareKeys.js
  packages/store/src/keys/copyBag.js
  packages/store/src/keys/copySet.js
  packages/store/src/keys/merge-bag-operators.js
  packages/store/src/keys/merge-set-operators.js
  packages/store/src/legacy/legacyMap.js
  packages/store/src/patterns/exo-makers.js
  packages/store/src/patterns/exo-tools.js
  packages/store/src/patterns/internal-types.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/stores/scalarMapStore.js
  packages/store/src/stores/scalarSetStore.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/stores/store-utils.js
  packages/store/src/types.js
  packages/store/test/borrow-guards.js
  packages/store/test/perf-patterns.js
  packages/store/test/test-copyBag.js
  packages/store/test/test-copyMap.js
  packages/store/test/test-copySet.js
  packages/store/test/test-heap-classes.js
  packages/store/test/test-label-instances.js
  packages/store/test/test-pattern-limits.js
  packages/store/test/test-patterns.js
  packages/store/tools.js
  packages/swingset-liveslots/package.json
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/zoe/src/contractSupport/recorder.js
  packages/zoe/src/contracts/callSpread/calculateShares.js
  yarn.lock
Labels: automerge:merge

#7397 VOM: split nextInstanceID into a separate vatstore key
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/test/test-handled-promises.js
  packages/swingset-liveslots/test/test-liveslots.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectGC.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
Labels: SwingSet, automerge:rebase, liveslots

#7430 docs(notifier): Fix typo in README
  packages/notifier/README.md
Labels: automerge:squash

#7384 feat(auction): auction send leftovers to Reserve
  packages/governance/src/contractHelper.js
  packages/governance/src/types-ambient.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/params.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.md
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.snap
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-proportionalDist.js
  packages/inter-protocol/test/auction/tools.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
  packages/vats/test/test-provisionPool.js
Labels: Inter-protocol, automerge:merge, Vaults, auction

#7423 feat(cosmic-swingset): poll timer after swingset quiescent
  packages/cosmic-swingset/src/launch-chain.js
Labels: cosmic-swingset, automerge:rebase

#7426 feat: label contract vats
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/electorateTools.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/committee-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startEconCommittee.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/startWalletFactory.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/src/zoeService/zoeStorageManager.js
Labels: automerge:rebase

#7443 refactor: only readability improvements to vom
  packages/swingset-liveslots/src/virtualObjectManager.js
Labels: automerge:merge

#7432 Port pismo replay tool improvements
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/startXSnap.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/transcript.js
  packages/SwingSet/src/types-internal.js
  packages/internal/src/queue.js
Labels: automerge:rebase

#7440 feat: improved error diagnostic on timer event handler failure
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/SwingSet/test/test-vat-timer.js
Labels: enhancement, SwingSet, automerge:rebase

#7434 Fix extract transcript
  packages/SwingSet/misc-tools/extract-bundle-from-kerneldb.js
  packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js
  packages/SwingSet/misc-tools/extract-transcript-from-slogfile.js
  packages/swing-store/src/bundleStore.js
  packages/swing-store/src/transcriptStore.js
Labels: automerge:rebase

#7451 feat: change offerArgs keyword from want to maxBuy, wire through CLI
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/test/snapshots/test-inter-cli.js.md
  packages/agoric-cli/test/snapshots/test-inter-cli.js.snap
  packages/agoric-cli/test/test-inter-cli.js
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/clientSupport.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/test-clientSupport.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
Labels: automerge:squash, Vaults, auction

#7225 feat: Support state-sync
  go.mod
  go.sum
  golang/cosmos/app/app.go
  golang/cosmos/daemon/cmd/root.go
  golang/cosmos/proto/agoric/swingset/swingset.proto
  golang/cosmos/x/swingset/abci.go
  golang/cosmos/x/swingset/alias.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/snapshotter.go
  golang/cosmos/x/swingset/types/swingset.pb.go
  golang/cosmos/x/vstorage/keeper/keeper.go
  golang/cosmos/x/vstorage/keeper/keeper_test.go
  packages/cosmic-proto/dist/agoric/swingset/swingset.d.ts
  packages/cosmic-proto/dist/agoric/swingset/swingset.js
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/cosmic-swingset/src/helpers/process-value.js
  packages/cosmic-swingset/src/import-kernel-db.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/deployment/ansible/roles/install-cosmos/tasks/main.yml
  packages/deployment/scripts/integration-test.sh
  packages/internal/src/action-types.js
  packages/internal/src/chain-storage-paths.js
  packages/telemetry/src/slog-to-otel.js
Labels: automerge:rebase

#7450 fix feeDistributor bootstrap
  packages/inter-protocol/src/feeDistributor.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
Labels: automerge:rebase

#7436 contract start types
  packages/governance/src/contractHelper.js
  packages/governance/src/typeGuards.js
  packages/governance/src/types-ambient.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/psm/test-governedPsm.js
  packages/vats/src/core/types.js
  packages/zoe/jsconfig.json
  packages/zoe/package.json
  packages/zoe/src/contractSupport/recorder.js
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/test/types.test-d.ts
  packages/zoe/test/unitTests/contracts/test-scaledPriceAuthority.js
  yarn.lock
Labels: automerge:merge

#7458 Updated oracle address for Simply Staking
  packages/vats/decentral-devnet-config.json
Labels: automerge:rebase, bypass:integration

#7412 excise Currency
  packages/agoric-cli/src/chain-config.js
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/test/snapshots/test-inter-cli.js.md
  packages/agoric-cli/test/snapshots/test-inter-cli.js.snap
  packages/agoric-cli/test/test-inter-cli.js
  packages/governance/README.md
  packages/governance/test/unitTests/test-buildParamManager.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/auction/offerBook.js
  packages/inter-protocol/src/clientSupport.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.md
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.snap
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-proportionalDist.js
  packages/inter-protocol/test/test-clientSupport.js
  packages/inter-protocol/test/vaultFactory/test-collatRatio.js
  packages/inter-protocol/test/vaultFactory/test-prioritizedVaults.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/vats/src/tokens.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/test-board-utils.js
  packages/zoe/test/unitTests/test-instanceStorage.js
  packages/zoe/test/unitTests/test-issuerStorage.js
  packages/zoe/test/unitTests/zoe/test-escrowStorage.js
Labels: automerge:rebase, auction

#7464 Don't retain a vat's raw bundle string after use
  packages/swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js
Labels: enhancement, SwingSet, automerge:rebase

#7455 fix(liveslots): allow new Kind upgrade to add new facets
  packages/SwingSet/test/upgrade/bootstrap-scripted-upgrade.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/upgrade/vat-ulrik-1.js
  packages/SwingSet/test/upgrade/vat-ulrik-2.js
  packages/swingset-liveslots/src/facetiousness.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/src/virtualReferences.js
  packages/swingset-liveslots/test/test-facetiousness.js
  packages/swingset-liveslots/test/virtual-objects/test-kind-changes.js
  packages/swingset-liveslots/tools/fakeCollectionManager.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
Labels: SwingSet, automerge:rebase, liveslots

#7461 when adjusting vaults consider the liquidation price
  packages/inter-protocol/src/vaultFactory/math.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: automerge:merge

#7460 chore(xsnap-lockdown): Optimize object-inspect
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/xsnap-lockdown/lib/object-inspect.js
Labels: automerge:merge

#7469 governance types inferred by start functions
  packages/ERTP/src/types-ambient.js
  packages/governance/README.md
  packages/governance/src/contractGovernance/governFilter.js
  packages/governance/src/contractGovernance/governParam.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractHelper.js
  packages/governance/src/types-ambient.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/tools/puppetContractGovernor.js
  packages/governance/tools/puppetGovernance.js
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/feeDistributor.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/supports.js
  packages/vats/src/core/types.js
  packages/vats/src/provisionPool.js
  packages/vats/test/test-provisionPool.js
Labels: automerge:merge

#7470 test(cosmic-swingset): fix Rosetta flake
  packages/cosmic-swingset/scripts/run-rosetta-ci.sh
  packages/cosmic-swingset/test/scenario2.js
  packages/cosmic-swingset/test/test-make.js
Labels: cosmic-swingset, test, automerge:merge

#7472 add extract-xs-snapshot and ingest-xs-snapshot tools
  packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js
  packages/SwingSet/misc-tools/extract-xs-snapshot.js
  packages/SwingSet/misc-tools/ingest-xs-snapshot.js
  packages/swing-store/src/snapStore.js
Labels: SwingSet, automerge:rebase

#7471 Sync Endo
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/same-structure/package.json
  packages/sharing-service/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/ui-components/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/web-components/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zoe/src/contractSupport/recorder.js
  packages/zone/package.json
  yarn.lock
Labels: automerge:merge, endo, force:integration

#7457 Better shutdown
  packages/internal/src/node/shutdown.js
  packages/telemetry/src/index.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/src/otel-trace.js
  packages/telemetry/src/slog-file.js
  packages/telemetry/src/slog-sender-pipe-entrypoint.js
  packages/telemetry/src/slog-sender-pipe.js
Labels: automerge:rebase

#7442 integration test for endo types
  packages/ERTP/package.json
  packages/internal/package.json
  packages/internal/test/endo-integration.test-d.ts
  packages/vat-data/package.json
  yarn.lock
Labels: automerge:merge, bypass:integration

#7428 rewrite transcript handling
  packages/SwingSet/misc-tools/extract-transcript-from-kerneldb.js
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-loader/transcript.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/lib/recordVatOptions.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/test-kernel.js
  packages/SwingSet/test/test-xsnap-errors.js
  packages/swingset-liveslots/src/types.js
  packages/swingset-xsnap-supervisor/lib/supervisor-helper.js
  packages/swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js
Labels: SwingSet, automerge:rebase

#7473 Only "module account" transfer events cause vpurse balance updates
  golang/cosmos/x/vbank/README.md
  golang/cosmos/x/vbank/keeper/keeper.go
  golang/cosmos/x/vbank/module.go
  golang/cosmos/x/vbank/types/expected_keepers.go
  golang/cosmos/x/vbank/vbank_test.go
Labels: automerge:merge, agd

#7468 feat: tweak state-sync logging
  golang/cosmos/x/swingset/keeper/snapshotter.go
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/cosmic-swingset/src/import-kernel-db.js
Labels: automerge:squash

#7479 Eliminate nugatory "workerCanBlock" support
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/swingset-xsnap-supervisor/lib/supervisor-helper.js
  packages/swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js
Labels: SwingSet, hygiene, automerge:rebase

#7429 docs(notifier): Document PublishKit and deprecate NotifierKit/SubscriberKit
  packages/notifier/README.md
Labels: automerge:rebase

#7486 refactor(inter-protocol): jessie-check where easy
  packages/inter-protocol/src/auction/scheduleMath.js
  packages/inter-protocol/src/auction/sortedOffers.js
  packages/inter-protocol/src/auction/util.js
  packages/inter-protocol/src/collectFees.js
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/index.js
  packages/inter-protocol/src/interest-math.js
  packages/inter-protocol/src/interest.js
  packages/inter-protocol/src/my-lien.js
  packages/inter-protocol/src/price/fluxAggregatorContract.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/core-proposal.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/psm/types.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/reserve/params.js
  packages/inter-protocol/src/stakeFactory/attestationTool.js
  packages/inter-protocol/src/stakeFactory/constants.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/src/stakeFactory/types.js
  packages/inter-protocol/src/typeGuards.js
  packages/inter-protocol/src/vaultFactory/burn.js
  packages/inter-protocol/src/vaultFactory/math.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/storeUtils.js
  packages/inter-protocol/src/vaultFactory/type-imports.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
Labels: automerge:rebase

#7487 refactor(ertp): jessie-check where easy
  packages/ERTP/src/displayInfo.js
  packages/ERTP/src/index.js
  packages/ERTP/src/legacy-payment-helpers.js
  packages/ERTP/src/mathHelpers/copyBagMathHelpers.js
  packages/ERTP/src/mathHelpers/copySetMathHelpers.js
  packages/ERTP/src/mathHelpers/natMathHelpers.js
  packages/ERTP/src/mathHelpers/setMathHelpers.js
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/transientNotifier.js
  packages/ERTP/src/typeGuards.js
  packages/ERTP/src/types-ambient.js
Labels: automerge:rebase

#7295 docs: Inter Protocol Liquidation Bidding Test Tool
  packages/agoric-cli/src/commands/ec.js
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/test/snapshots/test-inter-cli.js.md
  packages/agoric-cli/test/snapshots/test-inter-cli.js.snap
  packages/agoric-cli/test/test-inter-cli.js
  packages/inter-protocol/test/auction/README-bidding-cli.md
Labels: automerge:squash

#7477 misc fixes
  packages/governance/tools/puppetContractGovernor.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/inter-protocol/src/collectFees.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/internal/package.json
  packages/internal/src/typeGuards.js
  packages/smart-wallet/src/smartWallet.js
  packages/vat-data/src/vat-data-bindings.js
  packages/vats/test/bootstrapTests/supports.js
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/recorder.js
Labels: automerge:merge

#7401 feat(notifier): subscribeEach/subscribeLatest iterators retry when broken by vat upgrade
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/types-external.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/internal/src/upgrade-api.js
  packages/internal/test/test-upgrade-api.js
  packages/notifier/src/subscribe.js
  packages/notifier/src/types.js
  packages/notifier/test/test-publish-kit.js
  packages/notifier/test/test-subscriber-examples.js
  packages/notifier/test/vat-integration/vat-pubsub.js
Labels: automerge:merge

#7489 feat(cosmic-swingset): Add a config property for exporting storage to bootstrap
  golang/cosmos/x/vstorage/types/types.go
  golang/cosmos/x/vstorage/vstorage.go
  golang/cosmos/x/vstorage/vstorage_test.go
  packages/SwingSet/src/types-external.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:merge

#7402 7400 governance docs
  packages/inter-protocol/docs/governance-params.md
  packages/inter-protocol/docs/governance.md
  packages/inter-protocol/src/auction/params.js
Labels: automerge:merge, bypass:integration

#7505 fix(vbank): properly detect module accounts
  golang/cosmos/x/vbank/keeper/keeper.go
  golang/cosmos/x/vbank/types/expected_keepers.go
  golang/cosmos/x/vbank/vbank_test.go
Labels: automerge:merge, agd

#7506 Add incarnation number to the transcript store records
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/test/metering/test-dynamic-vat-metered.js
  packages/SwingSet/test/promise-watcher/test-promise-watcher.js
  packages/SwingSet/test/test-promises.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/inter-protocol/test/swingsetTests/fluxAggregator/bootstrap-fluxAggregator-service-upgrade.js
  packages/notifier/test/test-publish-kit.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/bootstrap-walletFactory-service-upgrade.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/src/transcriptStore.js
  packages/swing-store/test/test-exportImport.js
  packages/swing-store/test/test-state.js
  packages/vats/test/upgrading/bootstrap.js
  packages/vats/test/upgrading/test-upgrade-vats.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/bootstrap-coveredCall-service-upgrade.js
  packages/zoe/test/swingsetTests/zoe/test-zoe-upgrade.js
Labels: enhancement, SwingSet, automerge:rebase, swing-store

#7508 fix(zcf): mint kind during reincarnation
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfZygote.js
Labels: automerge:rebase

#7516 refactor(cache): jessie-check where easy
  packages/cache/src/cache.js
  packages/cache/src/main.js
  packages/cache/src/state.js
  packages/cache/src/types.js
Labels: automerge:rebase

#7515 refactor(casting): jessie-check where easy
  packages/casting/node-fetch-shim.js
  packages/casting/src/follower.js
  packages/casting/src/main.js
  packages/casting/src/netconfig.js
  packages/casting/src/types.js
Labels: automerge:rebase

#7514 refactor(cosmic-swingset): jessie-check where easy
  packages/cosmic-swingset/calc-rpcport.js
  packages/cosmic-swingset/check-validator.cjs
  packages/cosmic-swingset/src/entrypoint.js
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/cosmic-swingset/src/helpers/is-entrypoint.js
  packages/cosmic-swingset/src/import-kernel-db.js
  packages/cosmic-swingset/src/params.js
  packages/cosmic-swingset/src/sim-params.js
Labels: automerge:rebase

#7513 refactor(notifier): jessie-check where easy
  packages/notifier/exported.js
  packages/notifier/src/index.js
  packages/notifier/src/stored-notifier.js
  packages/notifier/src/subscriber.js
  packages/notifier/src/topic.js
  packages/notifier/src/types-ambient.js
  packages/notifier/src/types.js
  packages/notifier/subscribe.js
Labels: automerge:rebase

#7512 refactor(vat-data): jessie-check where easy
  packages/vat-data/src/exo-utils.js
  packages/vat-data/src/index.js
Labels: automerge:rebase

#7511 refactor(zone): jessie-check where easy
  packages/zone/durable.js
  packages/zone/heap.js
  packages/zone/src/durable.js
  packages/zone/src/heap.js
  packages/zone/src/index.js
  packages/zone/src/virtual.js
  packages/zone/virtual.js
Labels: automerge:rebase

#7518 refactor(internal): jessie-check where easy
  packages/internal/src/action-types.js
  packages/internal/src/batched-deliver.js
  packages/internal/src/chain-storage-paths.js
  packages/internal/src/config.js
  packages/internal/src/debug.js
  packages/internal/src/index.js
  packages/internal/src/magic-cookie-test-only.js
  packages/internal/src/queue.js
  packages/internal/src/typeGuards.js
  packages/internal/src/utils.js
Labels: automerge:rebase

#7459 fix(notifier)!: Stop retaining durable publish kit values in RAM
  packages/notifier/src/publish-kit.js
  packages/notifier/test/test-publish-kit.js
Labels: automerge:merge

#7522 fix(deploy-script-support): avoid pulling in notifiers
  packages/deploy-script-support/src/offer.js
Labels: automerge:squash

#7510 refactor(zoe): jessie-check where easy
  packages/zoe/contractFacet.js
  packages/zoe/exported.js
  packages/zoe/scripts/build-bundles.js
  packages/zoe/src/contractFacet/evalContractCode.js
  packages/zoe/src/contractFacet/internal-types.js
  packages/zoe/src/contractFacet/offerHandlerStorage.js
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contractFacet/vatRoot.js
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractSupport/bondingCurves.js
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/priceAuthorityInitial.js
  packages/zoe/src/contractSupport/priceQuote.js
  packages/zoe/src/contractSupport/types.js
  packages/zoe/src/handleWarning.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/issuerRecord.js
  packages/zoe/src/makeHandle.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/types.js
  packages/zoe/src/zoeService/createZCFVat.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/invitationQueries.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/offer/burnInvitation.js
  packages/zoe/src/zoeService/offer/offer.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/tools/fakeVatAdmin.js
  packages/zoe/tools/internal-types.js
  packages/zoe/tools/manualPriceAuthority.js
  packages/zoe/tools/prepare-test-env-ava.js
  packages/zoe/tools/prepare-test-env.js
  packages/zoe/tools/types-ambient.js
Labels: automerge:rebase

#7478 feat: functional upgrade-10 handler
  go.mod
  go.sum
  golang/cosmos/app/app.go
Labels: enhancement, automerge:merge, agd

#7441 test: Reconstitute liquidation scenario
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: Inter-protocol, automerge:rebase, Vaults, auction

#7500 7220 high priority senders manager
  packages/governance/test/unitTests/test-buildParamManager.js
  packages/governance/test/unitTests/test-committee.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/governance/test/unitTests/test-typedParamManager.js
  packages/governance/tools/storageDoc.js
  packages/inter-protocol/src/price/fluxAggregatorContract.js
  packages/inter-protocol/src/proposals/committee-proposal.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/inter-protocol/test/psm/gov-add-psm-permit.json
  packages/inter-protocol/test/psm/test-governedPsm.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/test-feeDistributor.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/internal/src/chain-storage-paths.js
  packages/internal/src/priority-senders.js
  packages/internal/src/storage-test-utils.js
  packages/internal/src/testing-utils.js
  packages/internal/test/test-priority-senders.js
  packages/notifier/tools/testSupports.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-addAsset.js
  packages/vats/src/core/README.md
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/types.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/bootstrapTests/test-vaults-performance.js
  packages/vats/test/snapshots/test-boot-config.js.md
  packages/vats/test/snapshots/test-boot-config.js.snap
  packages/vats/test/test-boot.js
  packages/vats/test/test-name-hub-published.js
  packages/vats/test/test-provisionPool.js
  packages/zoe/test/unitTests/contracts/loan/test-borrow.js
  packages/zoe/test/unitTests/contracts/test-auction.js
  packages/zoe/test/unitTests/contracts/test-callSpread.js
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/test/unitTests/test-fakePriceAuthority.js
  packages/zoe/test/unitTests/test-manualTimer.js
  packages/zoe/test/unitTests/test-scriptedOracle.js
Labels: automerge:rebase

#7463 7099 drop loan terminology in Vaults and StakeFactory
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/stakeFactory/constants.js
  packages/inter-protocol/src/stakeFactory/params.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/stakeFactory/test-stakeFactory.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/test-vaultFactory.js.snap
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
  packages/vats/src/core/demoIssuers.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/test-demoAMM.js
Labels: Inter-protocol, automerge:merge, Vaults

#7529 fix: correct accounting numbers in liquidation and auction
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.md
  packages/inter-protocol/test/auction/snapshots/test-auctionContract.js.snap
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: bug, automerge:merge, Vaults, auction

#7527 config.defaultManagerType beats env.SWINGSET_WORKER_TYPE
  docs/env.md
  packages/ERTP/test/swingsetTests/basicFunctionality/test-basicFunctionality.js
  packages/ERTP/test/swingsetTests/ertpService/test-ertp-service-upgrade.js
  packages/ERTP/test/swingsetTests/splitPayments/test-splitPayments.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/test/test-controller.js
  packages/governance/test/swingsetTests/committeeBinary/test-committee.js
  packages/inter-protocol/test/swingsetTests/fluxAggregator/test-fluxAggregator-service-upgrade.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/test-walletFactory-service-upgrade.js
  packages/vats/test/upgrading/test-upgrade-contracts.js
  packages/vats/test/upgrading/test-upgrade-vats.js
Labels: tooling, automerge:rebase

#7480 feat: start PSM contracts with metrics, governance from previous published state
  packages/inter-protocol/package.json
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/test/psm/psm-storage-fixture.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/vats/src/core/boot-psm.js
  packages/vats/src/core/types.js
  packages/vats/test/test-board-utils.js
  packages/vats/tools/board-utils.js
Labels: automerge:squash

#7484 add transcript events: init, snapshot save/load, shutdown
  packages/SwingSet/docs/images/transcript/image-1.jpg
  packages/SwingSet/docs/images/transcript/image-2.jpg
  packages/SwingSet/docs/images/transcript/image-3.jpg
  packages/SwingSet/docs/transcript.md
  packages/SwingSet/misc-tools/extract-xs-snapshot.js
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/types-ambient.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/test-controller.js
  packages/SwingSet/test/test-kernel.js
  packages/SwingSet/test/transcript/test-state-sync-reload.js
  packages/SwingSet/test/transcript/test-transcript-entries.js
  packages/SwingSet/test/transcript/vat-bootstrap-transcript.js
  packages/SwingSet/test/vat-warehouse/test-reload-snapshot.js
  packages/SwingSet/test/xsnap-stable-bundles/test-stable-bundles.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-exportImport.js
  packages/swing-store/test/test-snapstore.js
Labels: SwingSet, automerge:rebase

#7526 fix(vat-data): normalize kindName mangling
  packages/vat-data/src/exo-utils.js
Labels: automerge:rebase

#7517 refactor(agoric-cli): jessie-check where easy
  packages/agoric-cli/.ava-integration-test.config.js
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/entrypoint.js
  packages/agoric-cli/tools/resm-plugin/src/plugin.js
Labels: automerge:rebase

#7483 feat: high priority processing of economic activity
  golang/cosmos/ante/expected_keepers.go
  golang/cosmos/ante/inbound.go
  golang/cosmos/ante/inbound_test.go
  golang/cosmos/vm/controller.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/keeper/proposal.go
  golang/cosmos/x/swingset/types/expected_keepers.go
  golang/cosmos/x/swingset/types/msgs.go
  golang/cosmos/x/vstorage/keeper/keeper.go
  packages/SwingSet/src/kernel/vatTranslator.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/helpers/make-queue.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/internal/src/chain-storage-paths.js
Labels: automerge:rebase

#7485 build: resolve some floating promise warnings
  packages/ERTP/test/unitTests/test-inputValidation.js
  packages/ERTP/test/unitTests/test-issuerObj.js
  packages/agoric-cli/src/deploy.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/test/supports.js
  packages/web-components/package.json
  packages/web-components/src/AgoricWalletConnection.js
  packages/web-components/src/keplr-connection/watchWallet.js
  packages/web-components/test/agoric-petimage.test.js
  packages/web-components/test/agoric-petname.test.js
  packages/web-components/test/agoric-wallet-connection.test.js
  packages/zoe/test/unitTests/contracts/test-autoswap.js
  packages/zoe/test/unitTests/test-zoe.js
Labels: automerge:rebase

#7531 feat(xsnap)!: refactor xsnap wrapper and snapStore to use streams for snapshots
  packages/SwingSet/misc-tools/extract-xs-snapshot.js
  packages/SwingSet/misc-tools/measure-metering/measure.js
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/startXSnap.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/SwingSet/test/test-gc-and-finalize.js
  packages/SwingSet/test/test-xsnap-errors.js
  packages/SwingSet/test/test-xsnap-metering.js
  packages/SwingSet/test/test-xsnap-store.js
  packages/swing-store/package.json
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/test/test-deletion.js
  packages/swing-store/test/test-exportImport.js
  packages/swing-store/test/test-snapstore.js
  packages/xsnap/README.md
  packages/xsnap/package.json
  packages/xsnap/src/avaXS.js
  packages/xsnap/src/replay.js
  packages/xsnap/src/xsnap.js
  packages/xsnap/src/xsrepl.js
  packages/xsnap/test/message-tools.js
  packages/xsnap/test/test-boot-lockdown.js
  packages/xsnap/test/test-err-stack.js
  packages/xsnap/test/test-gc.js
  packages/xsnap/test/test-inspect.js
  packages/xsnap/test/test-replay.js
  packages/xsnap/test/test-xs-js.js
  packages/xsnap/test/test-xs-limits.js
  packages/xsnap/test/test-xs-perf.js
  packages/xsnap/test/test-xsnap.js
  scripts/process-integration-results.sh
Labels: automerge:rebase

#7528 7466 PSM upgradability
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/test/psm/test-psm.js
  packages/inter-protocol/test/swingsetTests/fluxAggregator/bootstrap-fluxAggregator-service-upgrade.js
  packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js
  packages/inter-protocol/test/swingsetTests/psmUpgrade/test-psm-upgrade.js
  packages/vats/src/core/types.js
  packages/vats/test/test-provisionPool.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/feeMint.js
Labels: automerge:merge

#7538 feat!(vaults): prioritize liquidation proceeds by collateral ratio
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
Labels: enhancement, automerge:merge, Vaults

#7544 chore(swingset): clean up TODOs, add replay syscall results to slog
  packages/SwingSet/src/devices/bridge/bridge.js
  packages/SwingSet/src/devices/command/command.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/vat-warehouse.js
Labels: SwingSet, automerge:rebase

#7497 fix: IbcATOM->ATOM
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/commands/reserve.js
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/start.js
  packages/agoric-cli/test/snapshots/test-inter-cli.js.md
  packages/agoric-cli/test/snapshots/test-inter-cli.js.snap
  packages/agoric-cli/test/test-inter-cli.js
  packages/casting/test/deploy.js
  packages/cosmic-swingset/economy-template.json
  packages/inter-protocol/README.md
  packages/inter-protocol/scripts/add-collateral-core.js
  packages/inter-protocol/scripts/start-local-chain.sh
  packages/inter-protocol/test/test-gov-collateral.js
  packages/inter-protocol/test/test-proposal-stuff.js
  packages/vats/decentral-demo-config.json
  packages/vats/decentral-devnet-config.json
  packages/vats/decentral-test-vaults-config.json
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/bootstrapTests/test-vaults-performance.js
  packages/vats/test/snapshots/test-board-utils.js.md
  packages/vats/test/test-board-utils.js
  packages/zoe/test/unitTests/contracts/test-scaledPriceAuthority.js
Labels: automerge:merge

#7552 fix(liveslots): retain WeakRefs to voAware collections
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/src/virtualReferences.js
  packages/swingset-liveslots/test/mock-gc.js
  packages/swingset-liveslots/test/test-dropped-collection-weakrefs.js
  packages/swingset-liveslots/test/virtual-objects/test-cease-recognition.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
Labels: SwingSet, automerge:rebase, liveslots

#7550 fix(swingset): make slog deliveryNum match transcript position
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/test/test-state.js
  packages/SwingSet/test/upgrade/test-upgrade.js
  packages/SwingSet/test/vat-admin/terminate/test-terminate.js
Labels: SwingSet, automerge:rebase

#7559 fix: do not error on shutdown
  packages/cosmic-swingset/src/chain-main.js
  packages/internal/src/node/shutdown.js
  packages/telemetry/src/slog-sender-pipe.js
Labels: automerge:rebase

#7551 fix(SwingSet): increase default snapshotInitial from 2 to 3
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/test/snapshots/test-state.js.md
  packages/SwingSet/test/snapshots/test-state.js.snap
  packages/SwingSet/test/test-state.js
Labels: SwingSet, automerge:rebase

#7560 feat(internal): add sync tee util
  packages/internal/package.json
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
Labels: automerge:squash

#7558 fix(swingset): better snapshot scheduling, do BOYD before each
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/test/transcript/test-transcript-entries.js
  packages/SwingSet/test/vat-warehouse/test-reload-snapshot.js
  packages/SwingSet/test/xsnap-stable-bundles/test-stable-bundles.js
Labels: SwingSet, automerge:rebase

#7561 feat(SwingSet): force reload worker from snapshot
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/startXSnap.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-helper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/test-controller.js
  packages/SwingSet/test/test-xsnap-metering.js
  packages/SwingSet/test/vat-warehouse/test-reload-snapshot.js
  packages/swing-store/src/snapStore.js
Labels: SwingSet, automerge:rebase, force:integration

#7556 7494 provisionPool upgradable
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/vats/src/core/types.js
  packages/vats/src/provisionPool.js
  packages/vats/src/provisionPoolKit.js
  packages/vats/test/test-provisionPool.js
  packages/zoe/src/contractSupport/durability.js
Labels: automerge:merge
