Repository Agoric/agoric-sdk, pull requests merged in 2023-02, with the labels that each got.

#6881 various cosmic-swingset tweaks
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/make-queue.js
  packages/cosmic-swingset/src/params.js
  packages/internal/src/fs-stream.js
  packages/internal/src/utils.js
  packages/swing-store/src/snapStore.js
  packages/telemetry/src/slog-file.js
  packages/xsnap/src/xsnap.js
  patches/@endo+bundle-source+2.4.2.patch
  patches/@endo+stream-node+0.2.22.patch
  patches/acorn+8.8.2.patch
  patches/node-fetch+2.6.8.patch
  scripts/process-integration-results.sh
Labels: automerge:rebase

#6871 5894 durable smartwallet
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/zoe/src/contractSupport/durability.js
  packages/zoe/src/contractSupport/index.js
Labels: automerge:merge

#6884 feat(types): export explicit tools types
  packages/zoe/exported.js
  packages/zoe/package.json
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/tools/eventLoopIteration.js
  packages/zoe/tools/fakePriceAuthority.js
  packages/zoe/tools/manualTimer.js
  packages/zoe/tools/types-ambient.js
Labels: automerge:rebase, bypass:integration

#6899 ci: always attempt to upload tests even on failure
  .github/workflows/test-all-packages.yml
Labels: automerge:rebase

#6908 chore!: remove 'asset' from publicSubscribers
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
Labels: automerge:merge

#6909 ci: skip uploading for forks
  .github/workflows/test-all-packages.yml
Labels: automerge:rebase

#6815 Adding packages/rosetta
  packages/rosetta/README.md
  packages/rosetta/configuration/bootstrap.json
  packages/rosetta/configuration/faucet.py
  packages/rosetta/configuration/rosetta.json
  packages/rosetta/configuration/run_tests.sh
  packages/rosetta/configuration/send_funds.sh
  packages/rosetta/configuration/transfer.ros
  packages/rosetta/docker-compose.yaml
  packages/rosetta/rosetta-ci/Dockerfile
  scripts/build-rosetta-ci.sh
Labels: automerge:rebase

#6902 6900 durable topics
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/cosmic-swingset/src/chain-main.js
  packages/inter-protocol/src/price/priceAggregatorChainlink.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/reserve/test-reserve.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/test-priceAggregatorChainlink.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/notifier/src/index.js
  packages/notifier/src/stored-topic.js
  packages/notifier/src/storesub.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/utils.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/zoe/src/contractSupport/durability.js
Labels: automerge:merge

#6917 fix(liveslots): use Map for vrefStatus, not object
  packages/swingset-liveslots/src/virtualReferences.js
Labels: automerge:rebase, liveslots

#6912 fix(cosmic-swingset): no actionQueue.consumeAll in hangover recovery
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:squash

#6918 5286 fix heap for getPublicTopics
  packages/inter-protocol/src/price/priceAggregatorChainlink.js
  packages/inter-protocol/src/vaultFactory/vaultHolder.js
  packages/smart-wallet/src/smartWallet.js
  packages/zoe/src/contractSupport/durability.js
Labels: automerge:rebase

#6922 ci(docker): use single docker buildx imagetools for multiarch
  .github/workflows/docker.yml
Labels: automerge:squash

#6925 refactor(vat-data): use fewer deprecated things
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/stakeFactory/types.js
  packages/vat-data/src/index.js
  packages/vat-data/src/vat-data-bindings.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/feeMint.js
Labels: automerge:squash

#6921 fix(cosmic-swingset): no actionQueue.consumeAll in hangover recovery
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:squash

#6924 test(liveslots): call startVat properly in liveslots-helpers.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/test/liveslots-helpers.js
  packages/swingset-liveslots/test/storeGC/test-refcount-management.js
  packages/swingset-liveslots/test/test-liveslots.js
  packages/swingset-liveslots/test/test-vpid-liveslots.js
  packages/swingset-liveslots/test/util.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectGC.js
Labels: automerge:merge, liveslots

#6938 fix vaultManager asset topic
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
Labels: automerge:merge, bypass:integration

#6923 annotate virtual/durable vrefs
  packages/SwingSet/docs/c-lists.md
  packages/SwingSet/src/lib/parseVatSlots.js
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/swingset-liveslots/docs/liveslots.md
  packages/swingset-liveslots/package.json
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/src/parseVatSlots.js
  packages/swingset-liveslots/src/stop-vat.js
  packages/swingset-liveslots/src/vatstore-usage.md
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/src/virtualReferences.js
  packages/swingset-liveslots/src/watchedPromises.js
  packages/swingset-liveslots/test/gc-helpers.js
  packages/swingset-liveslots/test/liveslots-helpers.js
  packages/swingset-liveslots/test/storeGC/test-lifecycle.js
  packages/swingset-liveslots/test/storeGC/test-scalar-store-kind.js
  packages/swingset-liveslots/test/test-baggage.js
  packages/swingset-liveslots/test/test-initial-vrefs.js
  packages/swingset-liveslots/test/test-liveslots.js
  packages/swingset-liveslots/test/test-vpid-liveslots.js
  packages/swingset-liveslots/test/virtual-objects/test-cease-recognition.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectGC.js
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
  packages/swingset-liveslots/test/virtual-objects/test-weakcollections-vref-handling.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
Labels: SwingSet, automerge:merge, liveslots

#6910 6519 liquidationPadding
  golang/cosmos/x/swingset/types/types.go
  packages/inter-protocol/src/proposals/demoIssuers.js
  packages/inter-protocol/src/vaultFactory/math.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-math.js
  packages/inter-protocol/test/vaultFactory/test-vault-collateralization.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
Labels: automerge:merge

#6903 feat(vats): upgradeable board
  packages/ERTP/test/swingsetTests/ertpService/test-ertp-service-upgrade.js
  packages/SwingSet/test/bootstrap-relay.js
  packages/SwingSet/test/vat-timer-upgrade/test-vat-timer-upgrade.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/smart-wallet/src/marshal-contexts.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-marshal-contexts.js
  packages/vats/package.json
  packages/vats/src/lib-board.js
  packages/vats/src/vat-board.js
  packages/vats/test/test-boot.js
  packages/vats/test/test-clientBundle.js
  packages/vats/test/test-lib-board.js
  packages/vats/test/upgrading/test-upgrade-contracts.js
  packages/vats/test/upgrading/test-upgrade-vats.js
  packages/vats/tools/boot-test-utils.js
  packages/wallet/api/src/lib-wallet.js
  packages/zoe/src/contractSupport/durability.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/test-coveredCall-service-upgrade.js
Labels: automerge:merge, bypass:integration

#6939 chore(wallet): validate action types in contract
  golang/cosmos/x/swingset/keeper/msg_server.go
  packages/smart-wallet/src/typeGuards.js
  packages/smart-wallet/src/types.d.ts
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/supports.js
  packages/smart-wallet/test/test-walletFactory.js
Labels: automerge:merge

#6941 docs for fluxAggregator
  packages/agoric-cli/src/commands/oracle.js
  packages/inter-protocol/README.md
  packages/inter-protocol/scripts/build-bundles.js
  packages/inter-protocol/scripts/price-feed-core.js
  packages/inter-protocol/src/price/README.md
  packages/inter-protocol/src/price/fluxAggregator.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/psm/README.md
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/test-priceAggregatorChainlink.js
  packages/zoe/src/contracts/priceAggregator.js
Labels: automerge:merge

#6959 feat: null upgrade handler for upgrade-9
  golang/cosmos/app/app.go
  golang/cosmos/app/const.go
Labels: enhancement, automerge:merge, agd

#6807 fix!(smart-wallet): omit redundant chainStorage balances updates
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/rpc.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/utils.js
  packages/smart-wallet/src/walletFactory.js
  packages/web-components/src/keplr-connection/fetchCurrent.js
  packages/web-components/src/keplr-connection/followLatest.js
  packages/web-components/src/keplr-connection/watchWallet.js
Labels: automerge:rebase

#6958 feat: upgrade dependencies to latest minor or patch release
  .github/workflows/deployment-test.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-golang.yml
  go.mod
  go.sum
Labels: automerge:merge, agoric-cosmos

#6942 ci(deployment-test): bump dependency to new Ubuntu LTS
  .github/actions/restore-node/action.yml
  .github/workflows/deployment-test.yml
  .github/workflows/docker.yml
  .github/workflows/pre-check-integration.yml
  .github/workflows/test-all-packages.yml
  packages/deployment/Dockerfile
  packages/deployment/Dockerfile.deployment
  packages/deployment/Dockerfile.sdk
  packages/deployment/Dockerfile.ssh-node
  packages/deployment/Makefile
  packages/deployment/ansible/prepare-machine.yml
  packages/deployment/ansible/roles/copy/tasks/main.yml
  packages/deployment/ansible/roles/fluentd/handlers/main.yml
  packages/deployment/ansible/roles/fluentd/tasks/main.yml
  packages/deployment/ansible/roles/start/tasks/main.yml
  packages/deployment/ansible/roles/status/tasks/main.yml
  packages/deployment/ansible/roles/stop/tasks/main.yml
  packages/deployment/ansible/update_known_hosts.yml
  packages/deployment/docker/init.sh
  packages/deployment/package.json
  packages/deployment/scripts/docker-deployment.cjs
  packages/deployment/scripts/integration-test.sh
  packages/deployment/scripts/setup.sh
  packages/deployment/src/init.js
  packages/deployment/src/main.js
  packages/deployment/terraform/docker/cluster/main.tf
  packages/deployment/terraform/docker/main.tf
Labels: deployment, automerge:merge, force:integration

#6973 chore(agoric-cli): accept sdk-package-names fixpoint
  .github/actions/restore-node/action.yml
  packages/agoric-cli/src/sdk-package-names.js
Labels: automerge:rebase

#6976 improve types of fulfillment helpers
  packages/inter-protocol/src/collect.js
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
Labels: automerge:merge, bypass:integration

#6980 feat: cherry-pick upgrade-9 handler and ibc etc update
  .github/workflows/deployment-test.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-golang.yml
  go.mod
  go.sum
  golang/cosmos/app/app.go
  golang/cosmos/app/const.go
Labels: enhancement, automerge:merge, agd, agoric-cosmos

#6984 6970 debtLimit threshold
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/test/test-contractSupport.js
Labels: automerge:merge

#6975 6701 EC addOracles to a governed fluxAggregator
  packages/governance/src/contractGovernance/governApi.js
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractHelper.js
  packages/governance/test/unitTests/test-puppetContractGovernor.js
  packages/governance/tools/puppetContractGovernor.js
  packages/governance/tools/puppetGovernance.js
  packages/inter-protocol/scripts/build-bundles.js
  packages/inter-protocol/scripts/price-feed-core.js
  packages/inter-protocol/src/econCommitteeCharter.js
  packages/inter-protocol/src/price/fluxAggregator.js
  packages/inter-protocol/src/price/fluxAggregatorContract.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/utils.js
  packages/inter-protocol/test/price/test-fluxAggregator.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/pegasus/package.json
  packages/pegasus/src/courier.js
  packages/vats/src/core/types.js
  packages/wallet/api/src/lib-wallet.js
Labels: automerge:merge

#6986 fix: update docker golang version
  packages/deployment/Dockerfile
  packages/deployment/Dockerfile.sdk
Labels: bug, deployment, automerge:merge

#6979 feat: null handlers for upgrade-10
  golang/cosmos/app/app.go
  golang/cosmos/app/const.go
Labels: enhancement, automerge:merge, agd

#6988 6859 CLI reserve command to burn
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/commands/ec.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/reserve.js
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/inter-protocol/src/reserve/assetReserve.js
Labels: automerge:rebase, bypass:integration

#6898 fix: replace other zoe.install with zoe.installBundleID
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/test/test-make.js
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/deploy-script-support/test/unitTests/test-coreProposalBehavior.js
  packages/inter-protocol/src/proposals/startPSM.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/test/test-boot.js
  packages/zoe/tools/fakeVatAdmin.js
Labels: Zoe, automerge:rebase, force:integration

#6977 6701 EC removeOracles
  packages/inter-protocol/src/price/fluxAggregator.js
  packages/inter-protocol/src/price/fluxAggregatorContract.js
  packages/inter-protocol/src/price/priceOracleAdmin.js
  packages/inter-protocol/src/price/priceOracleKit.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/test/price/test-fluxAggregator.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
Labels: automerge:merge

#6914 refactor(ERTP): better issuer provide pattern
  packages/ERTP/src/issuerKit.js
  packages/ERTP/test/swingsetTests/ertpService/vat-ertp-service.js
  packages/ERTP/test/unitTests/test-inputValidation.js
Labels: automerge:squash

#6995 chore: guide people to support channels
  .github/ISSUE_TEMPLATE/support_request.md
Labels: automerge:squash, bypass:integration

#6996 6850 targeting by agoricNames
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/lib/vaults.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/smart-wallet/src/invitations.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/typeGuards.js
Labels: automerge:merge

#6983 6944 pause vault offers
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/metrics.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vault-pause.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contractSupport/durability.js
Labels: automerge:merge

#6999 6689 fix watchPurse race
  packages/internal/src/lib-chainStorage.js
  packages/notifier/src/stored-notifier.js
  packages/notifier/src/stored-topic.js
  packages/notifier/src/storesub.js
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:rebase

#7003 fix(telemetry): some otel housekeeping
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/kernel-stats.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/solo/src/start.js
  packages/telemetry/package.json
  packages/telemetry/src/index.js
  packages/telemetry/src/slog-to-otel.js
  yarn.lock
Labels: automerge:merge

#7008 fix(scaledPriceAuthority): invert initialPrice; support quoteGiven
  packages/inter-protocol/scripts/add-collateral-core.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/test/test-proposal-stuff.js
  packages/vats/decentral-test-vaults-config.json
  packages/zoe/src/contractSupport/priceAuthorityTransform.js
  packages/zoe/test/unitTests/contracts/test-scaledPriceAuthority.js
Labels: automerge:rebase

#7010 fix(telemetry): fix otel-slog converter and update @opentelemetry
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/kernel-stats.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/solo/src/start.js
  packages/telemetry/package.json
  packages/telemetry/src/index.js
  packages/telemetry/src/slog-to-otel.js
  yarn.lock
Labels: automerge:rebase

#7016 fix(scaledPriceAuthority): initialPrice in/out in quote notifier
  packages/zoe/src/contractSupport/priceAuthorityTransform.js
  packages/zoe/test/unitTests/contracts/test-scaledPriceAuthority.js
Labels: automerge:rebase

#7018 feat(cosmic-swingset): validate smart wallet actions
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/scripts/validate-transcript-actions.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/validate-inbound.js
  packages/cosmic-swingset/test/test-validate-inbound.js
Labels: automerge:squash

#7017 use test-vaults-config for start-local-chain and smoketests
  packages/agoric-cli/test/README.md
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/agoric-cli/test/agops-perf-smoketest.sh
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/cosmic-swingset/Makefile
  packages/inter-protocol/scripts/start-local-chain.sh
Labels: automerge:rebase, bypass:integration

#7019 docs: update changelog for Pismo-C
  CHANGELOG.md
Labels: documentation, automerge:merge

#6962 feat(inter-protocol): set keyword shares on feeDistributor
  packages/inter-protocol/src/feeDistributor.js
  packages/inter-protocol/test/test-feeDistributor.js
Labels: automerge:squash

#7023 refactor(scaledPriceAuthority): initialPrice by composition
  packages/zoe/src/contractSupport/priceAuthorityInitial.js
  packages/zoe/src/contractSupport/priceAuthorityTransform.js
  packages/zoe/src/contracts/scaledPriceAuthority.js
Labels: automerge:rebase

#7011 fix(notifier): For durable `fail()`, persist the reason rather than a rejected promise
  packages/notifier/src/publish-kit.js
Labels: automerge:squash

#7027 fix: multiple deposits of unknown brand
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:merge, bypass:integration

#6940 docs(store): Sync with endo
  packages/store/src/types.js
Labels: documentation, hygiene, automerge:rebase, patterns, endo

#6916 docs: Clarify the upgrade process and requirements for vats and contracts
  packages/SwingSet/docs/dynamic-vats.md
  packages/SwingSet/docs/vat-upgrade.md
  packages/store/docs/exo-taxonomy.md
  packages/swingset-liveslots/src/vatstore-usage.md
  packages/zoe/README.md
  packages/zoe/docs/zoe-zcf.md
Labels: automerge:squash

#7039 fix: pass msg into go func
  golang/cosmos/ante/vm_admission.go
Labels: automerge:rebase

#7015 fix(deps): removed duplicate @endo/nat dependency in inter-protocols …
  packages/inter-protocol/package.json
Labels: automerge:squash

#7020 6969 fix vaults error recovery
  packages/agoric-cli/src/commands/wallet.js
  packages/inter-protocol/src/interest.js
  packages/inter-protocol/src/stakeFactory/stakeFactory.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryKit.js
  packages/inter-protocol/src/stakeFactory/stakeFactoryManager.js
  packages/inter-protocol/src/vaultFactory/types.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-storage.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/zoe/src/contractSupport/atomicTransfer.js
Labels: automerge:merge

#7054 fix(CI): update test-documentation to use Node 16.x, not 14.x
  .github/workflows/test-documentation.yml
Labels: tooling, automerge:rebase

#7048 create new xsnap-lockdown package
  .github/workflows/test-all-packages.yml
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/package.json
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/supervisors/subprocess-xsnap/lockdown-subprocess-xsnap.js
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/SwingSet/test/test-xsnap-errors.js
  packages/SwingSet/test/test-xsnap-store.js
  packages/agoric-cli/src/sdk-package-names.js
  packages/xsnap-lockdown/.gitignore
  packages/xsnap-lockdown/README.md
  packages/xsnap-lockdown/jsconfig.json
  packages/xsnap-lockdown/lib/confined-object-inspect.js
  packages/xsnap-lockdown/lib/console-shim.js
  packages/xsnap-lockdown/lib/object-inspect.js
  packages/xsnap-lockdown/lib/ses-boot-debug.js
  packages/xsnap-lockdown/lib/ses-boot.js
  packages/xsnap-lockdown/package.json
  packages/xsnap-lockdown/rollup.config.js
  packages/xsnap-lockdown/scripts/build-bundle.js
  packages/xsnap-lockdown/src/index.js
  packages/xsnap-lockdown/src/paths.js
  packages/xsnap-lockdown/test/test-bundle.js
  packages/xsnap-lockdown/test/test-inspect.js
  packages/xsnap/lib/ses-boot-debug.js
  packages/xsnap/lib/ses-boot.js
  packages/xsnap/package.json
  packages/xsnap/rollup.config.js
  packages/xsnap/src/avaXS.js
  packages/xsnap/test/test-boot-lockdown.js
  packages/xsnap/test/test-inspect.js
  yarn.lock
Labels: xsnap, automerge:merge

#7065 feat(agoric-cli): add `ibc-setup` and `ibc-relayer` commands with docs
  packages/agoric-cli/README.md
  packages/agoric-cli/package.json
  packages/agoric-cli/registry.yaml
  packages/agoric-cli/src/entrypoint.js
  packages/agoric-cli/src/main.js
  yarn.lock
Labels: agoric-cli, automerge:merge

#7066 fix(cosmic-swingset): silence incorrect kernel-stats warnings
  packages/cosmic-swingset/src/kernel-stats.js
Labels: cosmic-swingset, automerge:merge, telemetry

#7071 build(deps): loosen `@cosmjs/*` version specifiers
  packages/agoric-cli/package.json
  packages/casting/package.json
  patches/bl++readable-stream+3.6.1.patch
  patches/node-fetch+2.6.9.patch
  yarn.lock
Labels: tooling, automerge:merge

#7073 drop Node 14.x
  .github/workflow-templates/test-dapp.yml
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/integration.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-dapp-card-store.yml.DISABLED
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml.DISABLED
Labels: automerge:merge

#7070 fix(swing-store): remove explicit wal_checkpoint
  packages/swing-store/src/swingStore.js
Labels: SwingSet, automerge:rebase, bypass:integration

#7077 fix(ci): Downgrade node for integration test
  .github/workflows/integration.yml
Labels: automerge:squash

#7042 docs: more release process details
  MAINTAINERS.md
Labels: documentation, automerge:squash

#7075 refactor: move allValues, zip to internal
  packages/inter-protocol/src/collect.js
  packages/inter-protocol/src/proposals/demoIssuers.js
  packages/inter-protocol/test/amm/vpool-xyk-amm/setup.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/internal/src/index.js
  packages/internal/src/method-tools.js
  packages/internal/src/utils.js
  packages/vats/src/core/chain-behaviors.js
Labels: automerge:squash

#7059 Consistently generate build tags on Make 4.3+
  golang/cosmos/Makefile
Labels: automerge:rebase

#7035 fix: without assertKeyPattern
  packages/SwingSet/test/virtualObjects/test-representatives.js
  packages/store/src/index.js
  packages/store/src/patterns/patternMatchers.js
  packages/store/src/types.js
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/test/test-collections.js
  packages/swingset-liveslots/test/test-initial-vrefs.js
  packages/vat-data/test/test-scalar-only-keys.js
Labels: automerge:squash

#7085 fix: cosmic_swingset_inbound_queue_length is a gauge
  packages/cosmic-swingset/src/kernel-stats.js
Labels: automerge:rebase

#7021 6880 bootstrap integration test of vaultFactory with smart wallet
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/lib/kmarshal.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/bootstrap-relay.js
  packages/SwingSet/tools/bundleTool.js
  packages/SwingSet/tools/passableEncoding.js
  packages/agoric-cli/package.json
  packages/agoric-cli/src/lib/rpc.js
  packages/agoric-cli/src/lib/vaults.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/test/test-clean-core-eval.js
  packages/cosmic-swingset/test/test-provision-smartwallet.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/inter-protocol/package.json
  packages/inter-protocol/src/collectFees.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/inter-protocol/test/test-interchainPool.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/internal/src/config.js
  packages/internal/src/storage-test-utils.js
  packages/internal/test/test-storage-test-utils.js
  packages/swing-store/src/swingStore.js
  packages/vats/package.json
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/boot.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/test/bootstrapTests/supports.js
  packages/vats/test/bootstrapTests/test-vaults-integration.js
  packages/vats/test/snapshots/test-board-utils.js.md
  packages/vats/test/snapshots/test-board-utils.js.snap
  packages/vats/test/test-board-utils.js
  packages/vats/tools/board-utils.js
Labels: automerge:merge

#7080 fix: step towards stratifying customDetails
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/smart-wallet/src/invitations.js
  packages/swingset-runner/demo/zoeTests/vat-bob.js
  packages/swingset-runner/demo/zoeTests/vat-carol.js
  packages/swingset-runner/demo/zoeTests/vat-dave.js
  packages/zoe/NEWS.md
  packages/zoe/src/contractFacet/types.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contracts/auction/index.js
  packages/zoe/src/contracts/callSpread/fundedCallSpread.js
  packages/zoe/src/contracts/coveredCall-durable.js
  packages/zoe/src/contracts/coveredCall.js
  packages/zoe/src/contracts/loan/close.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/coveredCall-durable-V3.js
  packages/zoe/test/swingsetTests/zoe/vat-bob.js
  packages/zoe/test/swingsetTests/zoe/vat-carol.js
  packages/zoe/test/swingsetTests/zoe/vat-dave.js
  packages/zoe/test/unitTests/contracts/loan/helpers.js
  packages/zoe/test/unitTests/contracts/loan/test-borrow.js
  packages/zoe/test/unitTests/contracts/loan/test-loan-e2e.js
  packages/zoe/test/unitTests/contracts/test-atomicSwap.js
  packages/zoe/test/unitTests/contracts/test-auction.js
  packages/zoe/test/unitTests/contracts/test-callSpread.js
  packages/zoe/test/unitTests/contracts/test-coveredCall-want-pattern.js
  packages/zoe/test/unitTests/contracts/test-coveredCall.js
  packages/zoe/test/unitTests/contracts/test-oracle.js
  packages/zoe/test/unitTests/contracts/test-otcDesk.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: automerge:squash
