Repository Agoric/agoric-sdk, pull requests merged in 2024-01, with the labels that each got.

#8559 feat(deploy-script-support): Write out bundle file names in machine r…
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/internal/src/node/createBundles.js
Labels: automerge:rebase

#8453 feat: Zoe use watchPromise() to wait for contract finish
  packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts
  packages/builders/package.json
  packages/builders/scripts/vats/upgrade-zoe.js
  packages/vats/src/proposals/upgrade-zoe-proposal.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/test/swingsetTests/zoe/test-zoe-upgrade.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: Zoe, automerge:squash, contract-upgrade

#8710 Zoe use watchPromises for the release branch
  packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/test/swingsetTests/zoe/test-zoe-upgrade.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: Zoe, next-release

#8488 8445 add promiseWatcher to smartWallet
  packages/boot/test/bootstrapTests/test-vaults-integration.ts
  packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts
  packages/boot/test/bootstrapTests/walletFactory.ts
  packages/builders/scripts/smart-wallet/build-wallet-factory2-upgrade.js
  packages/inter-protocol/src/price/roundsManager.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/smart-wallet/src/offerWatcher.js
  packages/smart-wallet/src/offers.js
  packages/smart-wallet/src/payments.js
  packages/smart-wallet/src/proposals/upgrade-wallet-factory2-proposal.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/gameAssetContract.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/walletFactory-V2.js
Labels: wallet, automerge:rebase

#8499 feat(SwingSet): Add a tool for classifying unsettled promises
  packages/SwingSet/misc-tools/build-mezzanine-db.js
  packages/SwingSet/misc-tools/classify-promises.js
  packages/kmarshal/src/kmarshal.js
Labels: automerge:rebase

#8703 feat(cosmos): contextual and declarative VM action field defaults
  golang/cosmos/app/app.go
  golang/cosmos/vm/action.go
  golang/cosmos/vm/action_test.go
  golang/cosmos/vm/controller.go
  golang/cosmos/x/lien/keeper/keeper_test.go
  golang/cosmos/x/swingset/abci.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/keeper/proposal.go
  golang/cosmos/x/vbank/vbank.go
  golang/cosmos/x/vbank/vbank_test.go
  golang/cosmos/x/vibc/handler.go
  golang/cosmos/x/vibc/ibc.go
Labels: automerge:no-update, agd, agoric-cosmos

#8731 ci: allow externally forked PRs to pass CI
  .github/workflows/integration.yml
  .github/workflows/manage-integration-check.yml
  .github/workflows/mergify-ready.yml
  .mergify.yml
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/pre.test.js
Labels: tooling, force:integration, bypass:automerge

#8462 Fix for MacOS Sonoma Ledger detection issues
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: automerge:rebase, agd, agoric-cosmos

#8723 refactor(internal): remove unused functions migrating to endo
  packages/assert/src/assert.js
  packages/internal/src/utils.js
Labels: automerge:squash

#8732 Update README.md
  README.md
Labels: automerge:rebase

#8734 SECURITY.md: fix HackerOne link
  SECURITY.md
Labels: automerge:rebase

#8691 feat: auctioneer detects failing priceAuthority; requests new one
  packages/builders/scripts/vats/restart-vats.js
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/test-auctionBook.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-replacePriceAuthority.js
  packages/inter-protocol/test/vaultFactory/test-vaultFactory.js
  packages/inter-protocol/test/vaultFactory/test-vaultLiquidation.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/tools/manualPriceAuthority.js
Labels: performance, automerge:squash, resource-exhaustion, oracle, auction

#8736 Revert "test(upgrade-test): tolerate running after `a3p:main` zoe upgrade"
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/pre.test.js
Labels: automerge:rebase

#8712 chore(deploy-script-support): Sync code patterns across files
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/deploy-script-support/src/writeCoreProposal.js
Labels: automerge:rebase

#8717 move priceAuthorityRegistry with its vat
  packages/SwingSet/src/kernel/state/storageHelper.js
  packages/boot/test/upgrading/test-upgrade-vats.js
  packages/inter-protocol/test/auction/test-auctionContract.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/test-replacePriceAuthority.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/priceAuthorityRegistry.js
  packages/vats/src/vat-priceAuthority.js
  packages/vats/test/test-priceAuthorityRegistry.js
Labels: automerge:rebase

#8635 8605 a3p integration
  .eslintrc.cjs
  .github/workflows/integration.yml
  a3p-integration/.gitignore
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/sanity.test.js
  a3p-integration/proposals/a:upgrade-next/test.sh
  a3p-integration/proposals/a:upgrade-next/use.sh
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/yarn.lock
  package.json
  packages/agoric-cli/package.json
  packages/boot/tools/liquidation.ts
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/Makefile
  packages/deployment/upgrade-test/Readme.md
  packages/deployment/upgrade-test/upgrade-test-scripts/cliHelper.js
  packages/deployment/upgrade-test/upgrade-test-scripts/commonUpgradeHelpers.js
  packages/deployment/upgrade-test/upgrade-test-scripts/constants.js
  packages/deployment/upgrade-test/upgrade-test-scripts/econHelpers.js
  packages/deployment/upgrade-test/upgrade-test-scripts/env_setup.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/package.json
  packages/deployment/upgrade-test/upgrade-test-scripts/start_to_to.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/.gitignore
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/actions.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/actions.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/post.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/pre.test.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/tools/vat-status.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/run-prober-script.js
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/run-prober.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/zcf-upgrade-driver.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/zcf-upgrade-permit.json
  packages/deployment/upgrade-test/upgrade-test-scripts/unreleased-upgrade/zoe-full-upgrade/zcf-upgrade-script.js
  yarn.lock
Labels: automerge:rebase

#8744 chore(ci): use synthetic-chain build config
  .github/workflows/integration.yml
  a3p-integration/package.json
  a3p-integration/yarn.lock
Labels: automerge:rebase

#8748 fix(zoe): Fix OfferHandlerI.handle returns guard
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/typeGuards.js
Labels: automerge:squash

#8750 fix: "x" parameter in many tests is optional
  packages/vat-data/test/test-durable-classes.js
  packages/vat-data/test/test-prepare.js
  packages/vat-data/test/test-virtual-classes.js
Labels: automerge:squash

#8754 ci: restore core proposal in upgrade test
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/post.test.js
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/yarn.lock
Labels: automerge:no-update

#8738 Explicitly harden some shared prototypes
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/storageHelper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/casting/src/follower-cosmjs.js
  packages/casting/src/iterable.js
  packages/internal/test/test-utils.js
  packages/swing-store/src/bundleStore.js
  packages/swing-store/src/exporter.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/transcriptStore.js
  packages/swing-store/test/test-deletion.js
  packages/swing-store/test/test-exportImport.js
  packages/swing-store/test/test-snapstore.js
  packages/swing-store/test/test-state.js
  packages/swing-store/test/util.js
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/vatstore-iterators.js
  packages/swingset-liveslots/test/gc-helpers.js
  packages/vats/src/vat-bank.js
  packages/wallet/api/src/wallet.js
  packages/xsnap/api.js
  packages/xsnap/src/xsnap.js
  packages/zoe/tools/fakePriceAuthority.js
Labels: automerge:rebase

#8752 refactor(liveslots): minor improvements to prepare for upcoming changes
  packages/swingset-liveslots/src/cache.js
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/vatDataTypes.d.ts
  packages/swingset-liveslots/src/virtualObjectManager.js
Labels: automerge:squash

#8760 Default to unreleased docker tag
  .github/workflows/integration.yml
  a3p-integration/proposals/a:upgrade-next/package.json
  packages/deployment/Makefile
Labels: automerge:rebase

#8763 chore: Sync Endo versions
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/same-structure/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/xsnap/test/test-xs-perf.js
  packages/zoe/package.json
  packages/zone/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#8769 fix: update protobuf download and generation for ibc-go v4
  golang/cosmos/Makefile
  golang/cosmos/scripts/protocgen.sh
  golang/cosmos/third_party/proto/cosmos/base/query/v1beta1/pagination.proto
  golang/cosmos/third_party/proto/cosmos/upgrade/v1beta1/upgrade.proto
  golang/cosmos/third_party/proto/cosmos_proto/cosmos.proto
  golang/cosmos/third_party/proto/ibc/core/channel/v1/channel.proto
  golang/cosmos/third_party/proto/ibc/core/client/v1/client.proto
Labels: bug, automerge:rebase, agoric-cosmos, proto:expect-breakage

#8743 Cherry-pick CI improvements to release branch
  .eslintrc.cjs
  .github/actions/get-latest-check/action.yml
  .github/actions/notify-status/action.yml
  .github/actions/restore-golang/action.yml
  .github/actions/restore-node/action.yml
  .github/workflows/deployment-test.yml
  .github/workflows/integration.yml
  .github/workflows/manage-integration-check.yml
  .github/workflows/mergify-ready.yml
  .github/workflows/pre-check-integration.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-dapp-card-store.yml
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml.DISABLED
  .github/workflows/test-documentation.yml
  .mergify.yml
  SECURITY.md
  a3p-integration/.gitignore
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-13/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-13/package.json
  a3p-integration/proposals/a:upgrade-13/post.test.js
  a3p-integration/proposals/a:upgrade-13/test.sh
  a3p-integration/proposals/a:upgrade-13/use.sh
  a3p-integration/proposals/a:upgrade-13/yarn.lock
  a3p-integration/yarn.lock
  packages/SwingSet/test/test-xsnap-store.js
  packages/agoric-cli/package.json
  packages/deployment/Makefile
  packages/deployment/scripts/capture-integration-results.sh
  packages/deployment/scripts/install-deps.sh
  packages/deployment/scripts/start-github-integration-test.sh
  packages/deployment/upgrade-test/Dockerfile
  packages/deployment/upgrade-test/Makefile
  packages/deployment/upgrade-test/Readme.md
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/actions.js
  packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-13/tools/vat-status.js
  packages/deployment/upgrade-test/upgrade-test-scripts/cliHelper.js
  packages/deployment/upgrade-test/upgrade-test-scripts/commonUpgradeHelpers.js
  packages/deployment/upgrade-test/upgrade-test-scripts/constants.js
  packages/deployment/upgrade-test/upgrade-test-scripts/econHelpers.js
  packages/deployment/upgrade-test/upgrade-test-scripts/env_setup.sh
  packages/deployment/upgrade-test/upgrade-test-scripts/package.json
  packages/deployment/upgrade-test/upgrade-test-scripts/start_to_to.sh
  scripts/get-packed-versions.sh
  scripts/resolve-versions.sh
  yarn.lock
Labels: force:integration

#8705 docs: Hyperlink package references
  packages/ERTP/docs/INPUT_VALIDATION.md
  packages/ERTP/docs/user-safety.md
  packages/SwingSet/docs/dynamic-vats.md
  packages/SwingSet/docs/metering.md
  packages/SwingSet/docs/virtual-objects.md
  packages/base-zone/README.md
  packages/casting/README.md
  packages/inter-protocol/docs/governance.md
  packages/store/docs/store-taxonomy.md
  packages/swing-store/docs/data-export.md
  packages/swingset-xsnap-supervisor/README.md
  packages/vm-config/README.md
  packages/wallet/README.md
  packages/xsnap-lockdown/README.md
  packages/zoe/docs/zoe-catalog-of-storage.md
  packages/zoe/docs/zoe-zcf.md
Labels: automerge:rebase

#8755 Prepare upgrade-14 branch
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-13/post.test.js
  a3p-integration/proposals/a:upgrade-14/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-14/package.json
  a3p-integration/proposals/a:upgrade-14/sanity.test.js
  a3p-integration/proposals/a:upgrade-14/test.sh
  a3p-integration/proposals/a:upgrade-14/use.sh
  a3p-integration/proposals/a:upgrade-14/yarn.lock
  golang/cosmos/app/app.go
Labels: force:integration

#8678 style(golang): Align CLI command fields with upstream recommendations
  golang/cosmos/daemon/cmd/genaccounts.go
  golang/cosmos/daemon/cmd/testnet.go
  golang/cosmos/x/swingset/client/cli/query.go
  golang/cosmos/x/swingset/client/cli/tx.go
  golang/cosmos/x/vstorage/client/cli/query.go
Labels: automerge:rebase

#8747 Cherry-pick core proposal and deploy-script-support changes
  packages/agoric-cli/src/init.js
  packages/agoric-cli/test/upgrade-contract/propose-buggy-contract.js
  packages/agoric-cli/test/upgrade-contract/propose-upgrade-contract.js
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/helpers/json.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/cosmic-swingset/test/scenario2.js
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/endo-pieces-contract.js
  packages/deploy-script-support/src/externalTypes.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/deploy-script-support/src/getBundlerMaker.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/deploy-script-support/test/unitTests/test-getBundlerMaker.js
  packages/deploy-script-support/test/unitTests/test-installInPieces.js
  packages/inter-protocol/scripts/add-collateral-core.js
  packages/inter-protocol/scripts/init-core.js
  packages/inter-protocol/test/test-gov-collateral.js
  packages/internal/src/action-types.js
  packages/internal/src/node/createBundles.js
  packages/vats/scripts/build-game1-start.js
  packages/vats/scripts/build-walletFactory-upgrade.js
  packages/vats/scripts/set-core-proposal-env.js
Labels: force:integration

#8778 restore 'builders' typecheck
  packages/builders/scripts/inter-protocol/add-collateral-core.js
  packages/builders/scripts/inter-protocol/init-core.js
  packages/builders/scripts/smart-wallet/build-game1-start.js
  packages/builders/scripts/smart-wallet/build-wallet-factory2-upgrade.js
  packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js
  packages/builders/scripts/vats/set-core-proposal-env.js
  packages/builders/tsconfig.json
  packages/deploy-script-support/src/endo-pieces-contract.js
  packages/deploy-script-support/src/externalTypes.js
  packages/deploy-script-support/src/getBundlerMaker.js
  packages/deploy-script-support/src/writeCoreProposal.js
  packages/deploy-script-support/test/unitTests/test-installInPieces.js
Labels: automerge:rebase, bypass:integration

#8772 fake virtual watched promises for upgrade 14
  packages/swingset-liveslots/test/virtual-objects/test-virtualObjectManager.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
Labels: force:integration

#8751 ci(registry): use Endo workspace packages
  packages/eslint-config/package.json
  scripts/registry.sh
Labels: automerge:no-update, force:integration

#8764 Clean up minor issues found during benchmark writeup
  packages/SwingSet/src/controller/startNodeSubprocess.js
  packages/SwingSet/src/lib/kdebug.js
Labels: SwingSet, automerge:rebase

#8765 Clean up Benchmarkerator doc and Benchmarkerator report output formatting
  packages/benchmark/doc/benchmarkerator.md
  packages/benchmark/src/benchmarkerator.js
Labels: performance, automerge:rebase

#8768 A blog-post-like writeup of using one of our benchmarks for performance engineering
  packages/benchmark/doc/usingBenchmarks/annot-vault-open.json
  packages/benchmark/doc/usingBenchmarks/flamegraph1.png
  packages/benchmark/doc/usingBenchmarks/flamegraph2.png
  packages/benchmark/doc/usingBenchmarks/flamegraph3.png
  packages/benchmark/doc/usingBenchmarks/usingBenchmarks.md
  packages/benchmark/doc/usingBenchmarks/vault-open-vslog
  packages/benchmark/doc/usingBenchmarks/vault-open-vslog-reduced
Labels: documentation, performance, automerge:rebase

#8775 fix: smartWallet watch ERTP purse balances across zoe upgrades
  packages/inter-protocol/test/smartWallet/test-psm-integration.js
  packages/smart-wallet/src/offerWatcher.js
  packages/smart-wallet/src/smartWallet.js
Labels: wallet, automerge:rebase

#8790 chore: minor formatting changes to match master version of smartWallet
  packages/smart-wallet/src/smartWallet.js
Labels: wallet, code-style, force:integration

#8792 8453 release zoe
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/test/swingsetTests/zoe/test-zoe-upgrade.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: Zoe

#8370 feat(extract-proposal): organize proposals into steps
  packages/boot/tools/supports.ts
  packages/cosmic-swingset/economy-template.json
  packages/cosmic-swingset/src/launch-chain.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/swingset-runner/src/chain.js
  packages/vats/src/core/boot-chain.js
  packages/vats/src/core/boot-sim.js
  packages/vats/src/core/boot-solo.js
  packages/vats/src/core/lib-boot.js
  packages/vm-config/decentral-devnet-config.json
Labels: cosmic-swingset, automerge:no-update

#8799 feat: pull `create-dapp`, `xsnap`, and `agoric-cli` changes from release-getting-started branch
  .github/workflows/test-all-packages.yml
  packages/agoric-cli/package.json
  packages/agoric-cli/src/main.js
  packages/agoric-cli/src/sdk-package-names.js
  packages/create-dapp/.gitignore
  packages/create-dapp/.npmignore
  packages/create-dapp/CHANGELOG.md
  packages/create-dapp/README.md
  packages/create-dapp/package.json
  packages/create-dapp/src/create-dapp.js
  packages/create-dapp/test/test-sanity.js
  packages/create-dapp/tsconfig.json
  packages/xsnap/package.json
Labels: automerge:rebase

#8815 fix(vats): include index.js in NPM package
  packages/vats/package.json
Labels: automerge:squash

#8771 refactor: postponed removals and simplifications
  .github/workflows/test-all-packages.yml
  packages/agoric-cli/src/sdk-package-names.js
  packages/assert/src/types.js
  packages/internal/package.json
  packages/internal/src/index.js
  packages/internal/src/utils.js
  packages/internal/test/test-utils.js
  packages/same-structure/CHANGELOG.md
  packages/same-structure/CONTRIBUTING.md
  packages/same-structure/NEWS.md
  packages/same-structure/README.md
  packages/same-structure/index.js
  packages/same-structure/package.json
  packages/same-structure/tsconfig.json
  packages/store/src/index.js
  packages/store/src/stores/scalarWeakMapStore.js
  packages/store/src/stores/scalarWeakSetStore.js
  packages/store/src/stores/store-utils.js
  packages/swingset-liveslots/src/virtualObjectManager.js
Labels: automerge:rebase, force:integration

#8827 chore(internal): Remove unused ENACTED_UPGRADE action type
  packages/internal/src/action-types.js
Labels: automerge:squash

#8828 ci: add `dev-` branches as supported PR target
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/docker.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
  .github/workflows/pre-check-integration.yml
Labels: automerge:squash

#8630 fix: use dapp-offer-up by default
  packages/agoric-cli/src/main.js
  packages/agoric-cli/tools/getting-started.js
Labels: automerge:squash, force:integration

#8821 fix(provisioning): export useful namesByAddress
  packages/boot/test/bootstrapTests/test-demo-config.ts
  packages/builders/scripts/vats/replace-provisioning.js
  packages/vats/src/proposals/namesByAddress-fix-proposal.js
  packages/vats/src/vat-provisioning.js
Labels: automerge:rebase

#8749 refactor(base-zone,store): prepare for migration to endo repo
  packages/base-zone/README.md
  packages/store/README.md
  packages/store/package.json
  packages/store/src/legacy/legacyMap.js
  packages/store/src/legacy/legacyWeakMap.js
  packages/store/test/borrow-guards.js
Labels: automerge:squash

#8839 a3p dx
  .github/workflows/integration.yml
  a3p-integration/.gitignore
  a3p-integration/.yarnrc.yml
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/yarn.lock
Labels: automerge:rebase

#8844 Core proposals in upgrade handler
  golang/cosmos/app/app.go
  golang/cosmos/vm/core_proposals.go
  packages/cosmic-swingset/src/launch-chain.js
  packages/deploy-script-support/src/extract-proposal.js
Labels: automerge:rebase, force:integration
