Repository Agoric/agoric-sdk, pull requests merged in 2024-09, with the labels that each got.

#10012 Endo Sync 2024-08-31
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/xsnap-store.test.js.md
  packages/SwingSet/test/snapshots/xsnap-store.test.js.snap
  packages/agoric-cli/src/follow.js
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/stat-logger/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zone/package.json
  patches/@endo+compartment-mapper+1.2.2.patch
  patches/@endo+eventual-send+1.2.5.patch
  yarn.lock
Labels: automerge:rebase, force:integration

#10022 docs: Further steps for Endo sync documentation
  MAINTAINERS.md
Labels: automerge:rebase, force:integration

#10002 multichain-testing: `make start` single command start
  multichain-testing/Makefile
  multichain-testing/README.md
  multichain-testing/scripts/pod-readiness.ts
Labels: automerge:rebase

#10015 chore(xsnap): improve currentHeapCount in metering results
  packages/xsnap/src/xsnap.js
  packages/xsnap/test/xs-perf.test.js
Labels: xsnap, automerge:rebase

#9977 a3p vaults-auctions cleanup
  a3p-integration/proposals/a:vaults-auctions/agd-tools.js
  a3p-integration/proposals/a:vaults-auctions/eval.sh
  a3p-integration/proposals/a:vaults-auctions/package.json
  a3p-integration/proposals/a:vaults-auctions/prepare.sh
  a3p-integration/proposals/a:vaults-auctions/saveAuctionInstance.js
  a3p-integration/proposals/a:vaults-auctions/upgradeVaults.test.js
  a3p-integration/proposals/a:vaults-auctions/vatDetails.js
  a3p-integration/proposals/a:vaults-auctions/yarn.lock
Labels: automerge:rebase

#10004 feat: `cosmosOrchAccount.getBalances()`
  multichain-testing/test/account-balance-queries.test.ts
  multichain-testing/test/chain-queries.test.ts
  multichain-testing/test/config.ts
  packages/builders/scripts/testing/start-query-flows.js
  packages/orchestration/src/examples/basic-flows.contract.js
  packages/orchestration/src/examples/basic-flows.flows.js
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/fixtures/README.md
  packages/orchestration/src/fixtures/query-flows.contract.js
  packages/orchestration/src/fixtures/query-flows.flows.js
  packages/orchestration/test/examples/basic-flows.contract.test.ts
  packages/orchestration/test/examples/snapshots/stake-ica.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/stake-ica.contract.test.ts.snap
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/make-test-coa-kit.ts
  packages/orchestration/test/fixtures/query-flows.contract.test.ts
Labels: automerge:rebase, force:integration

#7901 refactor(vaultFactory!): vaultFactory use zcf.atomicRearrange
  packages/inter-protocol/src/vaultFactory/liquidation.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
Labels: Zoe, automerge:rebase, Vaults

#7904 refactor(Auction!): make Auction use zcf.atomicRearrange()
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctioneer.js
Labels: Zoe, automerge:rebase, contract-upgrade, auction

#10030 refactor: Errors do not need `new`
  a3p-integration/proposals/b:enable-orchestration/test-lib/wallet.js
  a3p-integration/proposals/c:stake-bld/test-lib/wallet.js
  multichain-testing/test/ica-channel-close.test.ts
  multichain-testing/tools/address.ts
  multichain-testing/tools/deploy.ts
  multichain-testing/tools/makeHttpClient.js
  multichain-testing/tools/marshalTables.js
  multichain-testing/tools/sleep.ts
  packages/SwingSet/README.md
  packages/agoric-cli/src/commands/auction.js
  packages/agoric-cli/src/commands/gov.js
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/commands/test-upgrade.js
  packages/agoric-cli/src/lib/bundles.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/test/inter-cli.test.js
  packages/casting/src/makeHttpClient.js
  packages/cosmic-proto/src/codegen/binary.ts
  packages/cosmic-proto/src/codegen/helpers.ts
  packages/cosmic-proto/src/codegen/varint.ts
  packages/cosmic-proto/src/helpers.ts
  packages/network/src/network.js
  packages/notifier/src/publish-kit.js
  packages/smart-wallet/test/invitation1.test.js
  packages/vats/src/proposals/localchain-test.js
  packages/vow/src/vow.js
  packages/vow/test/watch-utils.test.js
  packages/xsnap/src/build.js
Labels: automerge:squash

#10024 calling flows from flows and other support for 9796
  packages/async-flow/index.js
  packages/async-flow/src/endowments.js
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/internal/src/utils.js
  packages/internal/test/utils.test.js
  packages/orchestration/src/examples/README.md
  packages/orchestration/src/examples/basic-flows.flows.js
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/swap.contract.js
  packages/orchestration/src/examples/swap.flows.js
  packages/orchestration/src/examples/unbond.contract.js
  packages/orchestration/src/examples/unbond.flows.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/portfolio-holder-kit.js
  packages/orchestration/src/facade.js
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbondExample.test.ts.snap
  packages/orchestration/test/examples/swap.contract.test.ts
  packages/orchestration/test/examples/unbond.contract.test.ts
  packages/orchestration/test/exos/portfolio-holder-kit.test.ts
  packages/orchestration/test/facade-durability.test.ts
  packages/orchestration/test/facade.test.ts
Labels: automerge:rebase

#10034 bump noble/hashes to 1.5.0
  package.json
  packages/orchestration/package.json
  patches/@noble+hashes+1.4.0.patch
  yarn.lock
Labels: automerge:rebase

#10029 feat: `localOrchAccount.getBalance` (non-vbank assets) and `localOrchAccount.getBalances`
  multichain-testing/test/account-balance-queries.test.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/fixtures/query-flows.flows.js
  packages/orchestration/src/utils/amounts.js
  packages/orchestration/src/utils/cosmos.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/exos/make-test-loa-kit.ts
  packages/orchestration/test/fixtures/query-flows.contract.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/supports.ts
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase, force:integration

#10032 Add cosmos-sdk vat snapshot/transcript retention configuration
  golang/cosmos/util/util.go
  golang/cosmos/x/swingset/config.go
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/swing-store/docs/data-export.md
  packages/swing-store/src/transcriptStore.js
  packages/swing-store/test/state.test.js
Labels: automerge:rebase

#10023 9796 continuing ica
  packages/orchestration/src/examples/staking-combinations.contract.js
  packages/orchestration/src/examples/staking-combinations.flows.js
  packages/orchestration/src/exos/combine-invitation-makers.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/staking-combinations.test.ts
  packages/orchestration/test/network-fakes.ts
Labels: automerge:rebase

#10041 docs: Orchestration API product features covered by example contracts and e2e testing
  packages/orchestration/USAGE.md
  packages/orchestration/src/exos/README.md
Labels: automerge:rebase, bypass:integration

#10042 refactor: rename sendAnywhere -> send-anywhere
  multichain-testing/test/send-anywhere.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/builders/scripts/testing/restart-send-anywhere.js
  packages/builders/scripts/testing/start-send-anywhere.js
  packages/orchestration/USAGE.md
  packages/orchestration/src/examples/README.md
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/send-anywhere.flows.js
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
Labels: automerge:rebase, force:integration

#10044 refactor: simplify ExtraInvitationMaker
  packages/orchestration/src/examples/staking-combinations.contract.js
Labels: automerge:rebase

#10050 9757 Orchestration docs timebox
  package.json
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/network/package.json
  packages/orchestration/index.js
  packages/orchestration/package.json
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/auto-stake-it.contract.js
  packages/orchestration/src/examples/basic-flows.contract.js
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/staking-combinations.contract.js
  packages/orchestration/src/examples/swap.contract.js
  packages/orchestration/src/examples/unbond.contract.js
  packages/orchestration/src/examples/unbond.flows.js
  packages/orchestration/src/exos/chain-hub-admin.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/cosmos-interchain-service.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/exo-interfaces.ts
  packages/orchestration/src/exos/ica-account-kit.js
  packages/orchestration/src/exos/icq-connection-kit.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/src/vat-orchestration.js
  packages/orchestration/test/types.test-d.ts
  packages/pegasus/package.json
  packages/solo/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  typedoc.json
  yarn.lock
Labels: automerge:rebase, bypass:integration

#10051 10026 enable orchestration
  a3p-integration/debug-current.sh
  a3p-integration/proposals/b:enable-orchestration/.gitignore
  a3p-integration/proposals/b:enable-orchestration/.yarnrc.yml
  a3p-integration/proposals/b:enable-orchestration/README.md
  a3p-integration/proposals/b:enable-orchestration/initial.test.js
  a3p-integration/proposals/b:enable-orchestration/package.json
  a3p-integration/proposals/b:enable-orchestration/test.sh
  a3p-integration/proposals/b:enable-orchestration/yarn.lock
  a3p-integration/proposals/e:upgrade-next/initial.test.js
  a3p-integration/proposals/g:stake-bld/.yarnrc.yml
  a3p-integration/proposals/g:stake-bld/README.md
  a3p-integration/proposals/g:stake-bld/package.json
  a3p-integration/proposals/g:stake-bld/stakeBld.test.js
  a3p-integration/proposals/g:stake-bld/test-lib/chain.js
  a3p-integration/proposals/g:stake-bld/test-lib/index.js
  a3p-integration/proposals/g:stake-bld/test-lib/rpc.js
  a3p-integration/proposals/g:stake-bld/test-lib/wallet.js
  a3p-integration/proposals/g:stake-bld/test.sh
  a3p-integration/proposals/g:stake-bld/yarn.lock
  a3p-integration/proposals/z:acceptance/.gitignore
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/test-lib/chain.js
  a3p-integration/proposals/z:acceptance/test-lib/index.js
  a3p-integration/proposals/z:acceptance/test-lib/rpc.js
  a3p-integration/proposals/z:acceptance/test-lib/wallet.js
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/valueVow.test.js
  a3p-integration/proposals/z:acceptance/yarn.lock
  golang/cosmos/app/upgrade.go
Labels: automerge:rebase, force:integration

#10056 use particular fromTag in a3p-integration
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/README.md
  a3p-integration/proposals/n:upgrade-next/.gitignore
  a3p-integration/proposals/n:upgrade-next/.yarnrc.yml
  a3p-integration/proposals/n:upgrade-next/README.md
  a3p-integration/proposals/n:upgrade-next/agd-tools.js
  a3p-integration/proposals/n:upgrade-next/initial.test.js
  a3p-integration/proposals/n:upgrade-next/localchain.test.js
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/prepare.sh
  a3p-integration/proposals/n:upgrade-next/priceFeed-follower-auction.test.js
  a3p-integration/proposals/n:upgrade-next/provisionPool.test.js
  a3p-integration/proposals/n:upgrade-next/synthetic-chain-excerpt.js
  a3p-integration/proposals/n:upgrade-next/test.sh
  a3p-integration/proposals/n:upgrade-next/tsconfig.json
  a3p-integration/proposals/n:upgrade-next/vatDetails.js
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/s:stake-bld/.yarnrc.yml
  a3p-integration/proposals/s:stake-bld/README.md
  a3p-integration/proposals/s:stake-bld/package.json
  a3p-integration/proposals/s:stake-bld/stakeBld.test.js
  a3p-integration/proposals/s:stake-bld/test-lib/chain.js
  a3p-integration/proposals/s:stake-bld/test-lib/index.js
  a3p-integration/proposals/s:stake-bld/test-lib/rpc.js
  a3p-integration/proposals/s:stake-bld/test-lib/wallet.js
  a3p-integration/proposals/s:stake-bld/test.sh
  a3p-integration/proposals/s:stake-bld/yarn.lock
Labels: automerge:rebase, bypass:integration

#10052 chore: mark zcf.reallocate() deprecated in types-ambient
  packages/zoe/src/contractFacet/types-ambient.d.ts
Labels: documentation, Zoe, automerge:rebase

#10045 feat: complete `UndelegateAndTransfer` and `DepositAndDelegate` flows
  multichain-testing/test/config.ts
  multichain-testing/test/stake-ica.test.ts
  packages/async-flow/src/types.d.ts
  packages/async-flow/test/types.test-d.ts
  packages/orchestration/USAGE.md
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/examples/staking-combinations.contract.js
  packages/orchestration/src/examples/staking-combinations.flows.js
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/chain-hub-admin.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/orchestration/test/examples/staking-combinations.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/make-test-coa-kit.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/supports.ts
Labels: automerge:rebase, force:integration

#10058 10011 restore addAsset tests
  packages/boot/test/bootstrapTests/addAssets.test.ts
Labels: automerge:rebase, bypass:integration

#10040 chore(lint): remove obsolete suppressions
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contractSupport/priceAuthorityInitial.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/auction/index.js
  packages/zoe/src/contracts/callSpread/payoffHandler.js
  packages/zoe/src/contracts/callSpread/pricedCallSpread.js
  packages/zoe/src/contracts/loan/scheduleLiquidation.js
  packages/zoe/src/contracts/oracle.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/sellItems.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/originalZoeSeat.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/tools/manualPriceAuthority.js
  packages/zoe/tools/scriptedPriceAuthority.js
Labels: automerge:rebase, bypass:integration

#10060 fix(swing-store): Delete transcript spans in stopUsingTranscript as in rollover
  packages/internal/tools/ava-assertions.js
  packages/swing-store/src/transcriptStore.js
  packages/swing-store/test/deletion.test.js
Labels: automerge:rebase

#10055 fix: Add consensus-independent vat snapshot/transcript archiving configuration
  golang/cosmos/x/swingset/config.go
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-admin-hooks.js
  packages/SwingSet/test/snapshots/xsnap-store.test.js.md
  packages/SwingSet/test/snapshots/xsnap-store.test.js.snap
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/internal/src/node/utils.js
  packages/internal/src/utils.js
  packages/swing-store/docs/transcriptstore.md
  packages/swing-store/src/archiver.js
  packages/swing-store/src/index.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/src/transcriptStore.js
  packages/swing-store/test/deletion.test.js
  packages/swing-store/test/export.test.js
  packages/swing-store/test/exportImport.test.js
  packages/swing-store/test/snapstore.test.js
  packages/swing-store/test/state.test.js
  packages/telemetry/src/make-slog-sender.js
Labels: automerge:rebase

#10070 refactor(internal): Make better use of endo makeError
  packages/internal/src/utils.js
Labels: automerge:rebase

#9634 fix(scripts): Update GitHub release template to document recursive `git clean`
  MAINTAINERS.md
  scripts/gen-github-release.sh
Labels: automerge:rebase

#10081 chore(x/swingset): Include "default" in vat-transcript-retention invalid value error message
  golang/cosmos/x/swingset/config.go
Labels: automerge:rebase

#10082 fix(xsnap): Accommodate spaces in installation path
  packages/xsnap/src/avaXS.js
  packages/xsnap/src/build.js
  packages/xsnap/src/replay.js
  packages/xsnap/src/xsnap.js
Labels: automerge:rebase

#10039 ci(docker): use Depot for multiarch images
  .github/workflows/docker.yml
  .github/workflows/integration.yml
  a3p-integration/.yarn/patches/@agoric-synthetic-chain-npm-0.1.0-148de716a6.patch
  a3p-integration/package.json
  a3p-integration/yarn.lock
Labels: tooling, automerge:no-update

#10087 chore(depot): add `depot.json` project ID file
  depot.json
Labels: tooling, automerge:no-update

#10085 test(swingset): use xs-worker to avoid gc flake
  packages/SwingSet/test/gc-kernel.test.js
Labels: automerge:squash

#10080 fix Telescope encoding Decimal
  .gitignore
  packages/cosmic-proto/package.json
  packages/cosmic-proto/src/codegen/binary.ts
  packages/cosmic-proto/src/codegen/google/protobuf/descriptor.ts
  packages/cosmic-proto/src/codegen/helpers.ts
  packages/cosmic-proto/src/codegen/index.ts
  packages/cosmic-proto/src/codegen/json-safe.ts
  packages/cosmic-proto/src/codegen/tendermint/abci/types.ts
  packages/cosmic-proto/src/codegen/tendermint/types/types.ts
  packages/cosmic-proto/src/codegen/utf8.ts
  packages/cosmic-proto/src/codegen/varint.ts
  packages/cosmic-proto/test/helpers.test-d.ts
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/ibc-mocks.test.ts
  packages/orchestration/test/snapshots/ibc-mocks.test.ts.md
  packages/orchestration/test/snapshots/ibc-mocks.test.ts.snap
  packages/vats/tools/fake-bridge.js
  patches/@cosmology+telescope+1.7.1.patch
  yarn.lock
Labels: automerge:rebase

#10059 drop node-fetch
  a3p-integration/proposals/s:stake-bld/package.json
  a3p-integration/proposals/s:stake-bld/test-lib/index.js
  a3p-integration/proposals/s:stake-bld/yarn.lock
  multichain-testing/package.json
  multichain-testing/scripts/fetch-starship-chain-info.ts
  multichain-testing/yarn.lock
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/entrypoint.js
  packages/agoric-cli/test/main.test.js
  packages/casting/README.md
  packages/casting/node-fetch-shim.js
  packages/casting/package.json
  packages/casting/test/lockdown.js
  packages/casting/test/mvp.test.js
  packages/deployment/package.json
  packages/deployment/src/entrypoint.js
  packages/solo/package.json
  packages/solo/src/add-chain.js
  yarn.lock
Labels: automerge:rebase

#10088 chore: Initialize dev-upgrade-17
  a3p-integration/proposals/a:upgrade-17/.gitignore
  a3p-integration/proposals/a:upgrade-17/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-17/README.md
  a3p-integration/proposals/a:upgrade-17/agd-tools.js
  a3p-integration/proposals/a:upgrade-17/initial.test.js
  a3p-integration/proposals/a:upgrade-17/localchain.test.js
  a3p-integration/proposals/a:upgrade-17/package.json
  a3p-integration/proposals/a:upgrade-17/prepare.sh
  a3p-integration/proposals/a:upgrade-17/priceFeed-follower-auction.test.js
  a3p-integration/proposals/a:upgrade-17/provisionPool.test.js
  a3p-integration/proposals/a:upgrade-17/synthetic-chain-excerpt.js
  a3p-integration/proposals/a:upgrade-17/test.sh
  a3p-integration/proposals/a:upgrade-17/tsconfig.json
  a3p-integration/proposals/a:upgrade-17/vatDetails.js
  a3p-integration/proposals/a:upgrade-17/yarn.lock
  a3p-integration/proposals/n:upgrade-next/README.md
  golang/cosmos/app/app.go
  golang/cosmos/app/upgrade.go
Labels: force:integration

#10090 chore: update maintainers instructions
  MAINTAINERS.md
Labels: automerge:squash

#10078 feat: env-doctor script
  package.json
  scripts/env-doctor.sh
Labels: automerge:rebase, bypass:integration

#9795 Typescript 5.6
  package.json
  packages/ERTP/package.json
  packages/SwingSet/misc-tools/replay-transcript.js
  packages/SwingSet/package.json
  packages/SwingSet/src/kernel/deviceTranslator.js
  packages/SwingSet/src/kernel/gc-actions.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/gc-actions.test.js
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/casting/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/internal/src/utils.js
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/smart-wallet/package.json
  packages/smart-wallet/test/supports.js
  packages/solo/package.json
  packages/swing-store/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/xsnap/test/leakiness.mjs
  packages/zoe/package.json
  packages/zone/package.json
  tsconfig.json
  yarn.lock
Labels: automerge:rebase, bypass:integration

#10069 10016 StakingAccountQueries
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/unbond.contract.js
  packages/orchestration/src/examples/unbond.flows.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/cosmos.js
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/examples/unbond.contract.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/network-fakes.ts
  packages/orchestration/test/utils/cosmos.test.ts
  packages/orchestration/tools/protobuf-decoder.js
Labels: automerge:rebase

#10108 chore: cleanup chain info
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/builders/scripts/testing/append-chain-info.js
  packages/builders/scripts/testing/tweak-chain-info.js
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/fetched-chain-info.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/registry.js
  packages/orchestration/test/chain-info.test.js
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/exos/make-test-loa-kit.ts
  packages/orchestration/test/facade-durability.test.ts
  packages/orchestration/test/snapshots/chain-info.test.js.md
  packages/orchestration/test/snapshots/chain-info.test.js.snap
  packages/orchestration/test/staking-ops.test.ts
Labels: automerge:rebase, force:integration

#10110 fix: write-chain-info after u17
  packages/boot/test/bootstrapTests/vat-orchestration.test.ts
  packages/builders/scripts/orchestration/write-chain-info.js
  packages/orchestration/src/proposals/init-chain-info.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/vm-config/decentral-devnet-config.json
  packages/vm-config/decentral-itest-orchestration-config.json
Labels: automerge:rebase, force:integration

#10077 feat: `vowTools.allSettled`
  packages/vow/README.md
  packages/vow/src/tools.js
  packages/vow/src/types.js
  packages/vow/src/watch-utils.js
  packages/vow/test/types.test-d.ts
  packages/vow/test/watch-utils.test.js
Labels: automerge:rebase

#10113 chore: upgrade-17 RC1 cherry picks
  packages/boot/test/bootstrapTests/vat-orchestration.test.ts
  packages/builders/scripts/orchestration/write-chain-info.js
  packages/orchestration/src/proposals/init-chain-info.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/vm-config/decentral-devnet-config.json
  packages/vm-config/decentral-itest-orchestration-config.json
Labels: force:integration

#9902 feat: zoeTools.localTransfer error paths
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/send-anywhere.flows.js
  packages/orchestration/src/examples/staking-combinations.flows.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/src/utils/zoe-tools.js
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/examples/staking-combinations.test.ts
  packages/orchestration/test/fixtures/zoe-tools.contract.js
  packages/orchestration/test/fixtures/zoe-tools.flows.js
  packages/orchestration/test/supports.ts
  packages/orchestration/test/utils/zoe-tools.test.ts
  packages/vats/tools/bank-utils.js
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase, force:integration

#10117 feat(localOrchAccount): Deposit, Withdraw invitationMakers
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/examples/basic-flows.contract.test.ts
  packages/orchestration/test/examples/send-anywhere.test.ts
Labels: automerge:rebase

#10121 simplify and finish unbond example
  packages/orchestration/src/examples/unbond.flows.js
  packages/orchestration/test/examples/unbond.contract.test.ts
Labels: automerge:rebase

#10116 Chore: Update gen-github-release.sh for usage and awk portability
  MAINTAINERS.md
  scripts/gen-github-release.sh
Labels: automerge:rebase

#10125 bump typescript-eslint and cleanup Orch examples filenames
  package.json
  packages/boot/test/bootstrapTests/lca.test.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/builders/scripts/orchestration/init-stakeAtom.js
  packages/builders/scripts/orchestration/init-stakeBld.js
  packages/builders/scripts/orchestration/init-stakeOsmo.js
  packages/builders/scripts/testing/restart-stakeAtom.js
  packages/orchestration/USAGE.md
  packages/orchestration/src/examples/README.md
  packages/orchestration/src/examples/stake-bld.contract.js
  packages/orchestration/src/examples/stake-ica.contract.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeBld.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  yarn.lock
Labels: automerge:rebase

#10057 feat(orchestration): ZCFTools
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/staking-combinations.contract.js
  packages/orchestration/src/examples/swap.contract.js
  packages/orchestration/src/examples/unbond.contract.js
  packages/orchestration/src/examples/unbond.flows.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/src/utils/zcf-tools.js
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/facade.test.ts
  packages/orchestration/test/fixtures/zcfTester.contract.js
  packages/orchestration/test/fixtures/zoe-tools.contract.js
  packages/orchestration/test/utils/zcf-tools.test.ts
Labels: automerge:rebase

#10129 fix(orchestration): chainHub accepts zone
  packages/orchestration/src/examples/stake-bld.contract.js
  packages/orchestration/src/examples/stake-ica.contract.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/supports.ts
Labels: automerge:squash

#10128 test(boot): Add entropy to Swingset config file names for uniqueness in concurrent testing
  packages/boot/package.json
  packages/boot/tools/supports.ts
Labels: automerge:rebase

#8680 chore(swingset): add tools to classify mainnet runs
  packages/SwingSet/misc-tools/classify-runs.py
  packages/SwingSet/misc-tools/classify-types.py
Labels: SwingSet, automerge:rebase

#10139 feat!: transfer(dest, amount, opts)
  packages/orchestration/src/examples/auto-stake-it-tap-kit.js
  packages/orchestration/src/examples/send-anywhere.flows.js
  packages/orchestration/src/examples/staking-combinations.flows.js
  packages/orchestration/src/examples/unbond.flows.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
Labels: automerge:rebase, force:integration

#10126 Add strict liveslots test env with upgrade tools
  packages/SwingSet/tools/prepare-strict-test-env-ava.js
  packages/async-flow/package.json
  packages/async-flow/test/prepare-test-env-ava.js
  packages/swingset-liveslots/test/exo-utils.js
  packages/swingset-liveslots/test/handled-promises.test.js
  packages/swingset-liveslots/test/strict-test-env-upgrade.test.js
  packages/swingset-liveslots/test/virtual-objects/virtualObjectManager.test.js
  packages/swingset-liveslots/tools/fakeVirtualObjectManager.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
  packages/swingset-liveslots/tools/prepare-strict-test-env.js
  packages/swingset-liveslots/tools/setup-vat-data.js
  packages/vow/package.json
  packages/vow/test/watch-upgrade.test.js
  packages/zone/package.json
  packages/zone/test/exos.test.js
  packages/zone/test/make-once.test.js
  packages/zone/test/prepare-test-env-ava.js
Labels: automerge:rebase

#10132 test(boot): simulate incoming vtransfer bridge events
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/boot/tools/supports.ts
  packages/orchestration/tools/ibc-mocks.ts
Labels: automerge:rebase

#10149 fix(orchestration): Resolve module import issues
  packages/builders/test/orchestration-imports.test.js
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/orchestration/index.js
  packages/orchestration/types.d.ts
  packages/orchestration/types.js
Labels: automerge:rebase

#10063 fix(swing-store)!: Remove unsafe hostStorage.setExportCallback method
  packages/swing-store/docs/swingstore.md
  packages/swing-store/src/swingStore.js
Labels: automerge:rebase

#10145 10143 require extensions
  .eslintrc.cjs
  multichain-testing/scripts/pod-readiness.ts
  package.json
  packages/orchestration/src/exos/exo-interfaces.ts
  packages/zoe/src/zoeService/utils.test-d.ts
  yarn.lock
Labels: automerge:rebase

#10152 ci: updated fixup check to only run for up to date PR
  .github/workflows/mergify-ready.yml
Labels: automerge:rebase

#10153 chore(repo): Update CODEOWNERS file with "* @Agoric/engprodexec" Rule
  CODEOWNERS
Labels: automerge:rebase

#10141 document Promise temporality and VowTools
  packages/SwingSet/docs/async.md
  packages/vow/src/tools.js
Labels: automerge:rebase, bypass:integration

#10158 document and adopt best practices for using `.ts` for typedefs
  docs/typescript.md
  packages/async-flow/index.js
  packages/async-flow/src/types-index.d.ts
  packages/async-flow/src/types-index.js
  packages/async-flow/src/types.ts
  packages/boot/test/bootstrapTests/ibcClientMock.js
  packages/internal/src/index.js
  packages/internal/src/types-index.d.ts
  packages/internal/src/types-index.js
  packages/internal/src/types.ts
  packages/notifier/src/index.js
  packages/notifier/src/types-index.d.ts
  packages/notifier/src/types-index.js
  packages/notifier/src/types.js
  packages/notifier/src/types.ts
  packages/orchestration/index.js
  packages/orchestration/src/types-index.d.ts
  packages/orchestration/src/types-index.js
  packages/orchestration/test/network-fakes.ts
  packages/orchestration/types.d.ts
  packages/swingset-liveslots/src/index.js
  packages/swingset-liveslots/src/types-index.d.ts
  packages/swingset-liveslots/src/types-index.js
  packages/swingset-liveslots/src/vatDataTypes.js
  packages/swingset-liveslots/src/vatDataTypes.ts
  packages/time/index.js
  packages/time/src/types-index.d.ts
  packages/time/src/types-index.js
  packages/time/src/types.ts
  packages/vats/index.js
  packages/vats/src/ibc.js
  packages/vats/src/types-index.d.ts
  packages/vats/src/types-index.js
  packages/vats/src/types.ts
  packages/vow/src/index.js
  packages/vow/src/tools.js
  packages/vow/src/types-index.d.ts
  packages/vow/src/types-index.js
  packages/vow/src/types.js
  packages/vow/src/types.ts
  packages/vow/test/types.test-d.ts
  tsconfig-build-options.json
Labels: automerge:rebase, force:integration

#9719 9303 test upgrading send-anywhere
  packages/boot/test/orchestration/contract-upgrade.test.ts
  packages/builders/scripts/testing/fix-buggy-sendAnywhere.js
  packages/builders/scripts/testing/start-buggy-sendAnywhere.js
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/send-anywhere.flows.js
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
Labels: automerge:rebase

#10160 fix(async-flow): panic if a guest fulfills during replay
  packages/async-flow/docs/async-flow-states.key
  packages/async-flow/docs/async-flow-states.md
  packages/async-flow/docs/async-flow-states.png
  packages/async-flow/src/async-flow.js
  packages/async-flow/src/types.ts
  packages/async-flow/test/_utils.js
  packages/async-flow/test/async-flow-crank.test.js
  packages/async-flow/test/async-flow-early-completion.test.js
  packages/async-flow/test/async-flow-no-this.js
  packages/async-flow/test/async-flow.test.js
  packages/async-flow/test/bad-host.test.js
Labels: automerge:no-update, asyncFlow
