Repository Agoric/agoric-sdk, pull requests merged in 2024-05, with the labels that each got.

#9310 cosmic-proto export patterns
  packages/boot/test/bootstrapTests/test-vat-orchestration.ts
  packages/cosmic-proto/package.json
  packages/cosmic-proto/package.json.md
  packages/cosmic-proto/test/test-vatsafe.js
  packages/orchestration/src/exos/stakingAccountKit.js
  packages/orchestration/src/utils/tx.js
  packages/orchestration/test/utils/tx.test.js
Labels: automerge:rebase

#9312 fix(orchestration): remove `cancelToken` + rename `createAccount` -> `makeAccount`
  packages/boot/test/bootstrapTests/test-orchestration.ts
  packages/boot/test/bootstrapTests/test-vat-orchestration.ts
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/exos/chainAccountKit.js
  packages/orchestration/src/exos/stakingAccountKit.js
  packages/orchestration/src/service.js
  packages/orchestration/src/types.d.ts
  packages/vats/src/localchain.js
  packages/vats/src/proposals/localchain-test.js
Labels: automerge:rebase

#9315 Tagged helper for StartFunction
  packages/governance/src/types.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/reserve/setup.js
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/internal/src/tagged.d.ts
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/test/unitTests/contracts/test-priceAggregator.js
  packages/zoe/tools/internal-types.js
  packages/zoe/tools/manualTimer.js
  packages/zoe/typedoc.json
Labels: automerge:rebase

#9307 feat: withdrawReward on StakingAccountHolder
  packages/boot/test/bootstrapTests/test-orchestration.ts
  packages/cosmic-proto/package.json
  packages/orchestration/src/exos/stakingAccountKit.js
  packages/orchestration/test/test-tx-encoding.js
  packages/orchestration/test/test-withdraw-reward.js
Labels: automerge:rebase

#9198 feat(orchestration): icq balance query
  packages/boot/test/bootstrapTests/test-orchestration.ts
  packages/boot/test/bootstrapTests/test-vat-orchestration.ts
  packages/boot/tools/ibc/mocks.js
  packages/boot/tools/supports.ts
  packages/builders/scripts/orchestration/init-stakeAtom.js
  packages/cosmic-proto/package.json
  packages/cosmic-proto/proto/ibc/applications/interchain_accounts/README.md
  packages/cosmic-proto/proto/icq/README.md
  packages/cosmic-proto/proto/icq/v1/genesis.proto
  packages/cosmic-proto/proto/icq/v1/icq.proto
  packages/cosmic-proto/proto/icq/v1/packet.proto
  packages/cosmic-proto/proto/icq/v1/query.proto
  packages/cosmic-proto/proto/icq/v1/tx.proto
  packages/cosmic-proto/src/codegen/icq/bundle.ts
  packages/cosmic-proto/src/codegen/icq/v1/genesis.ts
  packages/cosmic-proto/src/codegen/icq/v1/icq.ts
  packages/cosmic-proto/src/codegen/icq/v1/packet.ts
  packages/cosmic-proto/src/codegen/icq/v1/query.ts
  packages/cosmic-proto/src/codegen/icq/v1/tx.ts
  packages/cosmic-proto/src/codegen/ics23/bundle.ts
  packages/cosmic-proto/src/codegen/index.ts
  packages/cosmic-proto/src/codegen/tendermint/bundle.ts
  packages/cosmic-proto/src/helpers.ts
  packages/cosmic-proto/test/snapshots/test-exports.js.md
  packages/cosmic-proto/test/snapshots/test-exports.js.snap
  packages/cosmic-proto/test/test-helpers.js
  packages/network/src/network.js
  packages/network/test/test-network-misc.js
  packages/orchestration/index.js
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/exos/chainAccountKit.js
  packages/orchestration/src/exos/icqConnectionKit.js
  packages/orchestration/src/exos/stakingAccountKit.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/service.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/types.d.ts
  packages/orchestration/src/utils/address.js
  packages/orchestration/src/utils/packet.js
  packages/orchestration/src/utils/tx.js
  packages/orchestration/src/vat-orchestration.js
  packages/orchestration/test/test-withdraw-reward.js
  packages/orchestration/test/utils/address.test.js
  packages/orchestration/test/utils/packet.test.js
  packages/orchestration/test/utils/tx.test.js
  packages/vats/tools/ibc-utils.js
  packages/vm-config/decentral-devnet-config.json
Labels: automerge:rebase

#9283 8981 upgrade vaults
  a3p-integration/proposals/a:upgrade-next/agd-tools.js
  a3p-integration/proposals/a:upgrade-next/priceFeed.test.js
  a3p-integration/proposals/a:upgrade-next/test.sh
  a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js
  a3p-integration/scripts/generate-a3p-submissions.sh
  golang/cosmos/app/app.go
  packages/boot/test/bootstrapTests/test-vaults-upgrade.ts
  packages/builders/scripts/vats/upgradeVaults.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/contractHelper.js
  packages/governance/test/swingsetTests/contractGovernor/test-governor.js
  packages/governance/test/unitTests/test-puppetContractGovernor.js
  packages/inter-protocol/src/proposals/add-auction.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
  packages/inter-protocol/src/proposals/upgrade-vaults.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
Labels: test, automerge:rebase, contract-upgrade, Vaults, force:integration, auction

#9321 feat(base-zone):`zone.watchPromise`
  packages/base-zone/src/heap.js
  packages/base-zone/src/index.js
  packages/base-zone/src/types.js
  packages/base-zone/src/watch-promise.js
  packages/vat-data/package.json
  packages/vat-data/src/index.test-d.ts
  packages/vat-data/vow.js
  packages/vow/README.md
  packages/vow/package.json
  packages/vow/src/tools.js
  packages/vow/src/vow.js
  packages/vow/src/watch.js
  packages/vow/test/test-vat.js
  packages/vow/vat.js
  packages/zone/src/durable.js
  packages/zone/src/virtual.js
Labels: tooling, automerge:no-update

#9329 refactor: use `@agoric/vow/vat.js`
  .prettierignore
  packages/boot/package.json
  packages/boot/test/bootstrapTests/ibcClientMock.js
  packages/boot/test/bootstrapTests/ibcServerMock.js
  packages/boot/test/bootstrapTests/test-net-ibc-upgrade.ts
  packages/boot/test/upgrading/vat-vow.js
  packages/network/package.json
  packages/network/test/test-network-misc.js
  packages/orchestration/package.json
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/exos/chainAccountKit.js
  packages/orchestration/src/exos/icqConnectionKit.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/orchestration/src/service.js
  packages/pegasus/package.json
  packages/pegasus/src/contract.js
  packages/pegasus/test/test-peg.js
  packages/vats/package.json
  packages/vats/src/proposals/network-proposal.js
  packages/vats/src/repl.js
  packages/vats/src/vat-ibc.js
  packages/vats/src/vat-network.js
  packages/vats/test/test-network.js
  packages/vow/src/E.js
  packages/vow/src/tools.js
  packages/vow/src/types.js
  packages/vow/src/vow-utils.js
  packages/vow/src/vow.js
  packages/vow/src/watch-utils.js
  packages/vow/src/watch.js
  packages/vow/src/when.js
  packages/vow/test/test-disconnect.js
  packages/vow/test/test-watch.js
Labels: hygiene, automerge:no-update

#9339 a3p misc improvements
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/proposals/b:localchain/package.json
  a3p-integration/proposals/b:localchain/yarn.lock
  a3p-integration/proposals/c:stake-bld/README.md
  a3p-integration/proposals/c:stake-bld/package.json
  a3p-integration/proposals/c:stake-bld/yarn.lock
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/yarn.lock
  a3p-integration/scripts/build-all-submissions.sh
  a3p-integration/scripts/build-submission.sh
  a3p-integration/scripts/generate-a3p-submissions.sh
  a3p-integration/yarn.lock
Labels: automerge:rebase, force:integration

#9351 proto msg response types
  packages/cosmic-proto/package.json
  packages/cosmic-proto/src/helpers.ts
  packages/cosmic-proto/test/helpers.test-d.ts
  packages/orchestration/test/types.test-d.ts
  packages/vats/src/localchain.js
Labels: automerge:rebase

#9235 docs(MAINTAINERS): Cover pre-release generation
  MAINTAINERS.md
  scripts/gen-rebase-todo.sh
  scripts/get-released-tags
Labels: automerge:rebase

#9337 fix(scripts): Update gen-upgrade-proposal.sh to take a target tag argument
  scripts/gen-upgrade-proposal.sh
Labels: automerge:rebase

#9353 refactor(vats): for state upgrade, use single field
  packages/vats/src/localchain.js
  packages/vats/src/proposals/localchain-proposal.js
  packages/vats/src/vat-localchain.js
Labels: automerge:rebase

#9354 fix(vats): don't give all of bankManager to 1 account
  packages/vats/src/localchain.js
Labels: automerge:rebase

#9332 fix(types): board values
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/smart-wallet/src/marshal-contexts.js
  packages/smart-wallet/test/marshal-contexts.test.js
  packages/vats/src/lib-board.js
  packages/wallet/api/src/findOrMakeInvitation.js
  packages/wallet/api/test/lib-wallet.test.js
Labels: automerge:rebase

#9359 feat(graph): also generate the transitive reduction
  scripts/graph.sh
Labels: automerge:squash

#9331 feat: redelegate, undelegate on StakingAccountKit
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/exos/stakingAccountKit.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/types.d.ts
  packages/orchestration/test/staking-ops.test.js
  packages/orchestration/test/withdraw-reward.test.js
Labels: automerge:rebase

#9341 deps(go): use cosmos/ibc-go v6.3.0
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/x/vibc/types/ibc_module.go
Labels: automerge:squash, force:integration

#9356 Orch api factoring
  .github/workflows/test-all-packages.yml
  packages/inter-protocol/package.json
  packages/notifier/package.json
  packages/orchestration/index.js
  packages/orchestration/package.json
  packages/orchestration/src/chain-info.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/ethereum-api.ts
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/exos/chainAccountKit.js
  packages/orchestration/src/exos/icqConnectionKit.js
  packages/orchestration/src/exos/localchainAccountKit.js
  packages/orchestration/src/exos/stakingAccountKit.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeBld.js
  packages/orchestration/src/service.js
  packages/orchestration/src/types.d.ts
  packages/orchestration/src/types.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/utils/address.js
  packages/orchestration/src/utils/orc.js
  packages/orchestration/src/utils/packet.js
  packages/orchestration/src/vat-orchestration.js
  packages/orchestration/test/staking-ops.test.js
  packages/orchestration/test/tx-encoding.test.js
  packages/orchestration/test/utils/address.test.js
  packages/orchestration/test/utils/packet.test.js
  packages/orchestration/tsconfig.json
  packages/vats/src/core/basic-behaviors.js
Labels: automerge:rebase

#9366 fix(ci): move untrusted gh context to envvar
  .github/workflows/mergify-ready.yml
Labels: automerge:rebase

#9374 Zoe .d.ts libcheck
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/vats/package.json
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/test/types-ambient.test-d.ts
  packages/vats/tsconfig.json
  packages/zoe/package.json
  packages/zoe/src/contractFacet/types-ambient.d.ts
  packages/zoe/src/contracts/oracle.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/src/zoeService/utils.test-d.ts
  packages/zoe/test/types.test-d.ts
  packages/zoe/test/unitTests/blockedOffers.test.js
  packages/zoe/test/unitTests/contractSupport/depositTo.test.js
  packages/zoe/test/unitTests/contractSupport/withdrawFrom.test.js
  packages/zoe/test/unitTests/zcf/zcfSeat-exit.test.js
  packages/zoe/test/unitTests/zoe/burnInvitation.test.js
  packages/zoe/tsconfig.json
Labels: automerge:rebase

#9097 feat(async-flow): asyncFlow
  .github/workflows/test-all-packages.yml
  packages/agoric-cli/src/sdk-package-names.js
  packages/async-flow/CHANGELOG.md
  packages/async-flow/README.md
  packages/async-flow/docs/async-flow-states.key
  packages/async-flow/docs/async-flow-states.md
  packages/async-flow/docs/async-flow-states.png
  packages/async-flow/index.js
  packages/async-flow/package.json
  packages/async-flow/src/async-flow.js
  packages/async-flow/src/bijection.js
  packages/async-flow/src/convert.js
  packages/async-flow/src/ephemera.js
  packages/async-flow/src/equate.js
  packages/async-flow/src/log-store.js
  packages/async-flow/src/replay-membrane.js
  packages/async-flow/src/type-guards.js
  packages/async-flow/src/types.js
  packages/async-flow/test/async-flow-crank.test.js
  packages/async-flow/test/async-flow-no-this.js
  packages/async-flow/test/async-flow.test.js
  packages/async-flow/test/bad-host.test.js
  packages/async-flow/test/bijection.test.js
  packages/async-flow/test/convert.test.js
  packages/async-flow/test/equate.test.js
  packages/async-flow/test/log-store.test.js
  packages/async-flow/test/prepare-test-env-ava.js
  packages/async-flow/test/replay-membrane-settlement.test.js
  packages/async-flow/test/replay-membrane-zombie.test.js
  packages/async-flow/test/replay-membrane.test.js
  packages/async-flow/tsconfig.build.json
  packages/async-flow/tsconfig.json
  packages/async-flow/typedoc.json
  packages/vow/src/index.js
  packages/vow/src/vow-utils.js
Labels: automerge:squash, asyncFlow

#9390 basic tests of example Orchestration contracts
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/utils/orc.js
  packages/orchestration/test/examples/swapExample.test.ts
  packages/orchestration/test/examples/unbondExample.test.ts
  packages/orchestration/test/supports.ts
Labels: automerge:rebase

#9379 feat(localchain): withdraw payment
  packages/vats/src/localchain.js
  packages/vats/test/localchain.test.js
Labels: automerge:rebase

#9396 ScopedBridgeManager utils
  packages/boot/test/bootstrapTests/ibcBridgeMock.js
  packages/boot/test/bootstrapTests/net-ibc-upgrade.test.ts
  packages/boot/test/bootstrapTests/vats-restart.test.ts
  packages/boot/tools/supports.ts
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/internal/src/config.js
  packages/orchestration/test/examples/swapExample.test.ts
  packages/orchestration/test/examples/unbondExample.test.ts
  packages/orchestration/test/supports.ts
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/supports.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/ibc.js
  packages/vats/src/localchain.js
  packages/vats/src/proposals/localchain-proposal.js
  packages/vats/src/proposals/network-proposal.js
  packages/vats/src/types.d.ts
  packages/vats/src/vat-bank.js
  packages/vats/src/vat-bridge.js
  packages/vats/test/localchain.test.js
  packages/vats/test/network.test.js
  packages/vats/test/vat-bank.test.js
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase

#9380 feat(localchain): add `transfer` method to LocalChainAccountKit holder
  packages/cosmic-proto/package.json
  packages/cosmic-proto/src/helpers.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/exos/chainAccountKit.js
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/src/exos/localchainAccountKit.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/proposals/start-stakeBld.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/mockChainInfo.js
  packages/orchestration/src/utils/time.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/types.test-d.ts
  packages/orchestration/test/utils/time.test.ts
  packages/vats/test/localchain.test.js
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase

#9241 build: Add a gen-github-release.sh script for generating GitHub release contents
  MAINTAINERS.md
  scripts/gen-github-release.sh
Labels: documentation, enhancement, deployment, hygiene, automerge:rebase

#9382 upgrade scaledPriceAuthorities
  golang/cosmos/app/app.go
  packages/ERTP/src/issuerKit.js
  packages/builders/scripts/vats/upgradeScaledPriceAuthorities.js
  packages/deploy-script-support/README.md
  packages/inter-protocol/src/proposals/README.md
  packages/inter-protocol/src/proposals/upgrade-scaledPriceAuthorities.js
Labels: ERTP, automerge:rebase, contract-upgrade, oracle, next-release

#9413 ci(dependency-graph): remove packing artifacts from cache
  .github/workflows/test-all-packages.yml
  a3p-integration/package.json
Labels: tooling, automerge:no-update

#9352 8273 remove custom Ava glob
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/access-token/package.json
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/create-dapp/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vm-config/package.json
  packages/vow/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zone/package.json
Labels: automerge:rebase

#9416 6000 reduce floating promises
  packages/SwingSet/misc-tools/extract-xs-snapshot.js
  packages/SwingSet/test/transcript/state-sync-reload.test.js
  packages/SwingSet/test/transcript/transcript-entries.test.js
  packages/SwingSet/test/vat-timer.test.js
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/start.js
  packages/boot/test/bootstrapTests/zcf-upgrade.test.ts
  packages/cosmic-swingset/scripts/clean-core-eval.js
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/multiCandidateVoteCounter.js
  packages/governance/test/unitTests/binaryballotCount.test.js
  packages/governance/test/unitTests/multiCandidateBallotCount.test.js
  packages/governance/test/unitTests/puppetContractGovernor.test.js
  packages/internal/src/queue.js
  packages/orchestration/test/types.test-d.ts
  packages/pegasus/test/peg.test.js
  packages/smart-wallet/test/addAsset.test.js
  packages/smart-wallet/test/gameAssetContract.js
  packages/solo/public/main.js
  packages/solo/src/captp.js
  packages/solo/src/chain-cosmos-sdk.js
  packages/solo/src/vat-http.js
  packages/solo/test/captp-fixture.js
  packages/swingset-liveslots/src/liveslots.js
  packages/vats/test/types-ambient.test-d.ts
  packages/wallet/api/src/lib-wallet.js
  packages/wallet/api/src/wallet.js
  packages/wallet/api/test/lib-wallet.test.js
  packages/xsnap/src/avaXS.js
  packages/xsnap/src/xsnap.js
  packages/xsnap/src/xsrepl.js
  packages/xsnap/test/fixture-xsnap-script.js
Labels: automerge:rebase

#9394 stkAtom price feed
  a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js
  golang/cosmos/app/app.go
  packages/builders/scripts/vats/updateStkAtomPriceFeed.js
Labels: automerge:rebase, contract-upgrade, oracle, next-release

#9420 9087 defer ownable LCA/ICA accounts
  a3p-integration/proposals/c:stake-bld/package.json
  a3p-integration/proposals/c:stake-bld/yarn.lock
  packages/base-zone/src/prepare-revocable.js
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/chainAccountKit.js
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/types.test-d.ts
  packages/vat-data/src/exo-utils.js
  packages/zoe/src/contractSupport/prepare-ownable.js
Labels: automerge:rebase

#9428 7747 distinguish Zoe's manual timer
  packages/governance/test/swingsetTests/committeeBinary/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/unitTests/ballotBuilder.test.js
  packages/governance/test/unitTests/binaryballotCount.test.js
  packages/governance/test/unitTests/committee.test.js
  packages/governance/test/unitTests/multiCandidateBallotCount.test.js
  packages/governance/test/unitTests/paramGovernance.test.js
  packages/governance/test/unitTests/puppetContractGovernor.test.js
  packages/inter-protocol/test/feeDistributor.test.js
  packages/inter-protocol/test/price/fluxAggregatorKit.test.js
  packages/inter-protocol/test/psm/governedPsm.test.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/inter-protocol/test/reserve/reserve.test.js
  packages/inter-protocol/test/reserve/setup.js
  packages/inter-protocol/test/smartWallet/boot-test-utils.js
  packages/inter-protocol/test/smartWallet/oracle-integration.test.js
  packages/inter-protocol/test/supports.js
  packages/inter-protocol/test/swingsetTests/fluxAggregator/bootstrap-fluxAggregator-service-upgrade.js
  packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js
  packages/inter-protocol/test/swingsetTests/reserve/bootstrap-assetReserve-upgrade.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/inter-protocol/test/vaultFactory/vaultFactory.test.js
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/test/utils/time.test.ts
  packages/swingset-runner/demo/zoeTests/bootstrap.js
  packages/vats/tools/boot-test-utils.js
  packages/zoe/test/unitTests/contracts/priceAggregator.test.js
  packages/zoe/tools/manualTimer.js
Labels: automerge:rebase

#9421 delegate/undelegate
  packages/boot/test/bootstrapTests/lca.test.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/cosmic-proto/src/helpers.ts
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/src/exos/stakingAccountKit.js
  packages/orchestration/src/utils/cosmos.js
  packages/orchestration/src/utils/time.js
  packages/orchestration/test/examples/unbondExample.test.ts
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/tx-encoding.test.ts
  packages/orchestration/test/utils/time.test.ts
  packages/time/src/types.d.ts
  packages/vats/src/localchain.js
  packages/vats/tools/bank-utils.js
  packages/vats/tools/fake-bridge.js
  packages/zoe/tools/manualTimer.js
Labels: automerge:rebase

#9423 fix: start swing-store export without blocking checks
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/swing-store/src/exporter.js
  packages/swing-store/test/exportImport.test.js
Labels: SwingSet, automerge:rebase, swing-store

#9426 Add support for iavl options in cosmos config
  golang/cosmos/daemon/cmd/root.go
  golang/cosmos/daemon/cmd/root_test.go
Labels: automerge:rebase

#9437 docs(a3p-integration): Add hyperlinks
  a3p-integration/proposals/a:upgrade-next/README.md
  a3p-integration/proposals/b:localchain/README.md
  a3p-integration/proposals/c:stake-bld/README.md
  a3p-integration/proposals/z:acceptance/README.md
Labels: automerge:rebase
