Repository Agoric/agoric-sdk, pull requests merged in 2024-06, with the labels that each got.

#9442 test(swingset): fix GC test flake by forcing xsnap worker, not V8
  packages/SwingSet/test/gc/gc-vat.test.js
Labels: SwingSet, automerge:rebase

#9436 chore: Integrate on top of upgrade-15
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/exit-reclaim.test.js
  a3p-integration/proposals/a:upgrade-next/exitOffer.js
  a3p-integration/proposals/a:upgrade-next/prepare.sh
  a3p-integration/proposals/a:upgrade-next/tsconfig.json
  golang/cosmos/app/app.go
Labels: automerge:rebase, force:integration

#9391 Operational swing-store artifact level
  golang/cosmos/x/swingset/genesis.go
  golang/cosmos/x/swingset/keeper/extension_snapshotter.go
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/cosmic-swingset/src/import-kernel-db.js
Labels: automerge:rebase, force:integration

#9440 network test tools
  packages/network/src/network.js
  packages/network/test/fakes.js
  packages/network/test/network-misc.test.js
Labels: automerge:rebase

#9448 simplify Orch types
  a3p-integration/proposals/c:stake-bld/stakeBld.test.js
  packages/cosmic-proto/package.json
  packages/cosmic-proto/src/codegen/binary.ts
  packages/cosmic-proto/src/codegen/helpers.ts
  packages/cosmic-proto/src/codegen/index.ts
  packages/cosmic-proto/src/codegen/json-safe.ts
  packages/cosmic-proto/src/codegen/utf8.ts
  packages/cosmic-proto/src/codegen/varint.ts
  packages/cosmic-proto/src/helpers.ts
  packages/cosmic-proto/test/helpers.test-d.ts
  packages/vats/tools/fake-bridge.js
  patches/@cosmology+telescope+1.7.1.patch
  yarn.lock
Labels: automerge:rebase

#9447 feat(vlocalchain): use `jsonp.Marshaller` with `OrigName: false` for response marshalling
  golang/cosmos/vm/proto_json.go
  golang/cosmos/vm/proto_json_test.go
  golang/cosmos/x/vlocalchain/keeper/keeper_test.go
  golang/cosmos/x/vlocalchain/vlocalchain.go
  golang/cosmos/x/vlocalchain/vlocalchain_test.go
Labels: automerge:rebase

#9439 9212 chain helpers
  a3p-integration/proposals/c:stake-bld/stakeBld.test.js
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/orchestration/src/chain-info.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/exos/chainAccountKit.js
  packages/orchestration/src/exos/cosmosOrchestrationAccount.js
  packages/orchestration/src/exos/icqConnectionKit.js
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/mockChainInfo.js
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/examples/stake-atom.contract.test.ts
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/examples/swapExample.test.ts
  packages/orchestration/test/examples/unbondExample.test.ts
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/network-fakes.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/test/types.test-d.ts
  packages/smart-wallet/src/offerWatcher.js
  packages/smart-wallet/src/types.d.ts
Labels: automerge:rebase, force:integration

#9450 fix(vlocalchain): sdkerrors.Wrap is deprecated
  golang/cosmos/x/vlocalchain/handler.go
Labels: automerge:rebase

#9452 register any chain info
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/chain-info.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/facade.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/facade.test.ts
  packages/orchestration/test/utils/address.test.ts
  packages/vats/src/localchain.js
Labels: automerge:rebase

#9457 fix tsc errors detected by skipLibCheck: false
  package.json
  packages/ERTP/exported.d.ts
  packages/ERTP/package.json
  packages/base-zone/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cosmic-swingset/package.json
  packages/governance/exported.d.ts
  packages/inter-protocol/package.json
  packages/internal/exported.d.ts
  packages/internal/package.json
  packages/internal/src/types.d.ts
  packages/network/package.json
  packages/notifier/exported.d.ts
  packages/orchestration/package.json
  packages/smart-wallet/package.json
  packages/store/exported.d.ts
  packages/swing-store/package.json
  packages/vats/package.json
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/core-eval-env.d.ts
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/types.d.ts
  packages/xsnap/package.json
  packages/zoe/src/contractFacet/types-ambient.d.ts
  packages/zoe/src/zoeService/utils.d.ts
  yarn.lock
Labels: automerge:rebase

#9459 9063 chain lookup
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/mockChainInfo.js
  packages/orchestration/test/examples/swapExample.test.ts
  packages/orchestration/test/examples/unbondExample.test.ts
  packages/orchestration/test/facade.test.ts
  packages/orchestration/test/supports.ts
Labels: automerge:rebase

#9464 9063 localChain metadata by agoricNames
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/src/proposals/start-stakeBld.js
  packages/orchestration/src/utils/mockChainInfo.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/supports.ts
Labels: automerge:rebase

#9458 6000 remove zoe floating promises
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/priceAuthority.js
  packages/zoe/src/contractSupport/priceAuthorityInitial.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/auction/index.js
  packages/zoe/src/contracts/callSpread/payoffHandler.js
  packages/zoe/src/contracts/callSpread/pricedCallSpread.js
  packages/zoe/src/contracts/loan/scheduleLiquidation.js
  packages/zoe/src/contracts/oracle.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/sellItems.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/originalZoeSeat.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/test/swingsetTests/brokenContracts/crashingContract.test.js
  packages/zoe/test/swingsetTests/brokenContracts/vat-alice.js
  packages/zoe/test/types.test-d.ts
  packages/zoe/test/unitTests/contracts/atomicSwap.test.js
  packages/zoe/test/unitTests/contracts/coveredCall.test.js
  packages/zoe/test/unitTests/contracts/loan/borrow.test.js
  packages/zoe/test/unitTests/contracts/loan/helpers.js
  packages/zoe/test/unitTests/contracts/priceAggregator.test.js
  packages/zoe/test/unitTests/fakePriceAuthority.test.js
  packages/zoe/test/unitTests/manualTimer.test.js
  packages/zoe/test/unitTests/zcf/zcf.test.js
  packages/zoe/test/unitTests/zoe/escrowStorage.test.js
  packages/zoe/test/unitTests/zoe/instanceAdminStorage.test.js
  packages/zoe/tools/manualPriceAuthority.js
  packages/zoe/tools/scriptedPriceAuthority.js
Labels: Zoe, hygiene, code-style, automerge:rebase

#9467 test(a3p): move localchain test to upgrade-next
  a3p-integration/proposals/a:upgrade-next/localchain.test.js
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/b:localchain/.gitignore
  a3p-integration/proposals/b:localchain/.yarnrc.yml
  a3p-integration/proposals/b:localchain/README.md
  a3p-integration/proposals/b:localchain/package.json
  a3p-integration/proposals/b:localchain/test.sh
  a3p-integration/proposals/b:localchain/yarn.lock
Labels: automerge:rebase

#9474 test(async-flow): demonstrate #9465
  packages/async-flow/test/async-flow-early-completion.test.js
Labels: automerge:squash

#9468 clarify CoreEval vs proposal
  packages/agoric-cli/test/upgrade-contract/propose-buggy-contract.js
  packages/agoric-cli/test/upgrade-contract/propose-upgrade-contract.js
  packages/builders/scripts/inter-protocol/add-STARS.js
  packages/builders/scripts/inter-protocol/add-collateral-core.js
  packages/builders/scripts/inter-protocol/init-core.js
  packages/builders/scripts/inter-protocol/invite-committee-core.js
  packages/builders/scripts/inter-protocol/price-feed-core.js
  packages/builders/scripts/orchestration/init-stakeAtom.js
  packages/builders/scripts/orchestration/init-stakeBld.js
  packages/builders/scripts/pegasus/init-core.js
  packages/builders/scripts/smart-wallet/build-game1-start.js
  packages/builders/scripts/smart-wallet/build-wallet-factory2-upgrade.js
  packages/builders/scripts/smart-wallet/build-walletFactory-upgrade.js
  packages/builders/scripts/vats/add-auction.js
  packages/builders/scripts/vats/init-core.js
  packages/builders/scripts/vats/init-localchain.js
  packages/builders/scripts/vats/init-network.js
  packages/builders/scripts/vats/init-orchestration.js
  packages/builders/scripts/vats/init-transfer.js
  packages/builders/scripts/vats/priceFeedSupport.js
  packages/builders/scripts/vats/probe-zcf-bundle.js
  packages/builders/scripts/vats/replace-provisioning.js
  packages/builders/scripts/vats/replace-zoe.js
  packages/builders/scripts/vats/restart-vats.js
  packages/builders/scripts/vats/test-localchain.js
  packages/builders/scripts/vats/test-vtransfer.js
  packages/builders/scripts/vats/updateAtomPriceFeed.js
  packages/builders/scripts/vats/updateStAtomPriceFeed.js
  packages/builders/scripts/vats/updateStOsmoPriceFeed.js
  packages/builders/scripts/vats/updateStTiaPriceFeed.js
  packages/builders/scripts/vats/updateStkAtomPriceFeed.js
  packages/builders/scripts/vats/upgrade-zcf.js
  packages/builders/scripts/vats/upgrade-zoe.js
  packages/builders/scripts/vats/upgradeScaledPriceAuthorities.js
  packages/builders/scripts/vats/upgradeVaults.js
  packages/deploy-script-support/src/coreProposalBehavior.js
  packages/deploy-script-support/src/externalTypes.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/deploy-script-support/src/helpers.js
  packages/deploy-script-support/src/writeCoreEvalParts.js
  packages/deploy-script-support/test/unitTests/coreProposalBehavior.test.js
Labels: automerge:rebase

#9460 feat: generic chain with sendAnywhere demo contract
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/proposals/start-stakeBld.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/chainHub.js
  packages/orchestration/src/utils/time.js
  packages/orchestration/test/examples/sendAnywhere.test.ts
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/facade.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/test/utils/time.test.ts
Labels: automerge:rebase

#9443 feat(async-flow): error on guest E use
  packages/async-flow/src/replay-membrane.js
  packages/async-flow/test/replay-membrane-eventual.test.js
Labels: automerge:squash, asyncFlow

#9470 refactor(vtransfer): transfer interceptor updates
  packages/vats/src/transfer.js
Labels: automerge:no-update

#9471 refactor(vats): Remove makeBridgeTargetKit from prepareTransferTools
  packages/orchestration/test/supports.ts
  packages/vats/src/transfer.js
  packages/vats/test/localchain.test.js
Labels: automerge:no-update

#9376 9063 getChain
  a3p-integration/proposals/b:enable-orchestration/initial.test.js
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/boot/test/configs.test.js
  packages/boot/test/snapshots/boot-config.test.js.snap
  packages/boot/test/snapshots/configs.test.js.md
  packages/boot/test/snapshots/configs.test.js.snap
  packages/builders/scripts/orchestration/init-stakeAtom.js
  packages/eslint-config/eslint-config.cjs
  packages/network/src/network.js
  packages/network/src/types.js
  packages/orchestration/package.json
  packages/orchestration/scripts/fetch-chain-info.ts
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/fetched-chain-info.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/chainHub.js
  packages/orchestration/test/chain-info.test.js
  packages/orchestration/test/examples/sendAnywhere.test.ts
  packages/orchestration/test/examples/stake-atom.contract.test.ts
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/snapshots/chain-info.test.js.md
  packages/orchestration/test/snapshots/chain-info.test.js.snap
  packages/orchestration/test/staking-ops.test.ts
  patches/@chain-registry+client+1.47.4.patch
  yarn.lock
Labels: automerge:rebase, force:integration

#9486 fixes to chainConnection key and vstorage
  a3p-integration/proposals/b:enable-orchestration/initial.test.js
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/governance/tools/storageDoc.js
  packages/inter-protocol/README.md
  packages/inter-protocol/test/auction/README-bidding-cli.md
  packages/internal/src/storage-test-utils.js
  packages/orchestration/scripts/fetch-chain-info.ts
  packages/orchestration/src/fetched-chain-info.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/orchestration/src/utils/chainHub.js
  packages/orchestration/test/chain-info.test.js
Labels: automerge:rebase

#9489 9063 make account
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/boot/test/bootstrapTests/vat-orchestration.test.ts
  packages/orchestration/scripts/fetch-chain-info.ts
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/exos/chainAccountKit.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/fetched-chain-info.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/service.js
  packages/orchestration/src/utils/chainHub.js
  packages/orchestration/test/chain-info.test.js
  packages/orchestration/test/examples/sendAnywhere.test.ts
  packages/orchestration/test/examples/stake-atom.contract.test.ts
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/facade.test.ts
  packages/orchestration/test/snapshots/chain-info.test.js.md
  packages/orchestration/test/snapshots/chain-info.test.js.snap
  packages/orchestration/test/supports.ts
Labels: automerge:rebase

#9481 8722 provisionPool re-register notifiers
  a3p-integration/proposals/a:upgrade-next/agd-tools.js
  a3p-integration/proposals/a:upgrade-next/localchain.test.js
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/priceFeed-follower-auction.test.js
  a3p-integration/proposals/a:upgrade-next/probeZcfBundleCap.test.js
  a3p-integration/proposals/a:upgrade-next/provisionPool.test.js
  a3p-integration/proposals/a:upgrade-next/provisioning.test.js
  a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js
  packages/builders/scripts/testing/add-LEMONS.js
  packages/builders/scripts/testing/add-OLIVES.js
  packages/builders/scripts/vats/upgrade-bank.js
  packages/builders/scripts/vats/upgrade-provisionPool.js
  packages/inter-protocol/src/provisionPoolKit.js
  packages/vats/src/proposals/upgrade-bank-proposal.js
  packages/vats/src/proposals/upgrade-provisionPool-proposal.js
  packages/vats/src/proposals/upgrade-zoe-proposal.js
Labels: bug, test, Inter-protocol, automerge:rebase, contract-upgrade

#9487 fix(vow): make watch/when more robust against loops and hangs
  packages/SwingSet/tools/bootstrap-relay.js
  packages/boot/test/upgrading/upgrade-vats.test.js
  packages/boot/test/upgrading/vat-vow.js
  packages/vat-data/vow.js
  packages/vats/src/vat-transfer.js
  packages/vow/src/tools.js
  packages/vow/src/types.js
  packages/vow/src/vow.js
  packages/vow/src/watch.js
  packages/vow/src/when.js
  packages/vow/vat.js
Labels: automerge:no-update

#9499 ci(mergify): strip merge commit HTML comments
  .github/PULL_REQUEST_TEMPLATE.md
  .mergify.yml
Labels: tooling, automerge:no-update

#9462 feat: multichain-testing
  .github/workflows/multichain-e2e.yml
  multichain-testing/.gitignore
  multichain-testing/.yarnrc.yml
  multichain-testing/Makefile
  multichain-testing/README.md
  multichain-testing/config.yaml
  multichain-testing/package.json
  multichain-testing/patches/js-yaml+4.1.0.patch
  multichain-testing/patches/node-fetch+2.6.12.patch
  multichain-testing/patches/starshipjs+2.0.0.patch
  multichain-testing/scripts/dev-setup.sh
  multichain-testing/scripts/install.sh
  multichain-testing/scripts/port-forward.sh
  multichain-testing/test/smart-wallet.test.ts
  multichain-testing/test/support.ts
  multichain-testing/test/tools/registry.test.ts
  multichain-testing/test/tools/wallet.test.ts
  multichain-testing/third-party-licenses/starship-LICENSE
  multichain-testing/tools/agd-lib.js
  multichain-testing/tools/batchQuery.js
  multichain-testing/tools/bundle-tools.js
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/makeHttpClient.js
  multichain-testing/tools/marshalTables.js
  multichain-testing/tools/query.ts
  multichain-testing/tools/queryKit.js
  multichain-testing/tools/registry.ts
  multichain-testing/tools/sleep.ts
  multichain-testing/tools/wallet.ts
  multichain-testing/tsconfig.json
  multichain-testing/yarn.lock
Labels: automerge:rebase

#9500 8879 add umee
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/orchestration/scripts/fetch-chain-info.ts
  packages/orchestration/src/fetched-chain-info.js
  packages/orchestration/test/chain-info.test.js
  packages/orchestration/test/snapshots/chain-info.test.js.md
  packages/orchestration/test/snapshots/chain-info.test.js.snap
Labels: automerge:rebase

#9506 fix(SwingSet): Undo deviceTools behavioral change from #9153
  packages/SwingSet/src/devices/lib/deviceTools.js
Labels: automerge:squash

#9507 fix(liveslots): promise watcher to cause unhandled rejection if no handler
  packages/swingset-liveslots/src/watchedPromises.js
Labels: automerge:squash

#9488 feat: make vat-localchain resumable
  packages/boot/test/bootstrapTests/ibcClientMock.js
  packages/internal/src/types.d.ts
  packages/network/src/network.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/src/facade.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/exos/local-chain-account-kit.test.ts
  packages/orchestration/test/supports.ts
  packages/vats/src/localchain.js
  packages/vats/src/proposals/localchain-test.js
  packages/vats/src/vat-localchain.js
  packages/vats/test/localchain.test.js
  packages/vow/src/E.js
  packages/vow/src/types.js
  packages/vow/src/when.js
Labels: automerge:no-update, asyncFlow

#9510 ci(mergify): clarify `queue_conditions` and `merge_conditions`
  .mergify.yml
Labels: bypass:integration, bypass:automerge

#9509 fix(liveslots): cache.delete() does not return a useful value
  packages/swingset-liveslots/src/cache.js
Labels: SwingSet, automerge:rebase, liveslots

#8694 chore(swingset): re-enable test of unrecognizable orphan cleanup
  packages/SwingSet/test/gc-kernel.test.js
Labels: SwingSet, automerge:rebase

#9508 refactor(internal): move async helpers using AggregateError to node
  packages/internal/src/node/utils.js
  packages/internal/src/utils.js
  packages/swing-store/src/snapStore.js
  packages/telemetry/src/make-slog-sender.js
Labels: automerge:squash

#9501 feat(multichain-testing): request body too large
  multichain-testing/README.md
  multichain-testing/config.yaml
  multichain-testing/scripts/update-config.sh
Labels: automerge:rebase

#9503 report bundle sizing in agoric run
  packages/agoric-cli/package.json
  packages/agoric-cli/scripts/stat-bundle.js
  packages/agoric-cli/scripts/stat-plans.js
  packages/agoric-cli/src/lib/bundles.js
  packages/agoric-cli/src/main.js
  packages/deploy-script-support/src/writeCoreEvalParts.js
Labels: automerge:rebase

#9511 ci(test-boot): split up test jobs via AVA recipe
  .github/workflows/test-all-packages.yml
  packages/boot/test/bootstrapTests/demo-config.test.ts
  packages/boot/test/bootstrapTests/net-ibc-upgrade.test.ts
  packages/boot/test/bootstrapTests/vats-restart.test.ts
  packages/boot/test/bootstrapTests/vaults-integration.test.ts
  packages/boot/test/bootstrapTests/vaults-upgrade.test.ts
  packages/boot/test/bootstrapTests/vtransfer.test.ts
  packages/boot/test/bootstrapTests/walletFactory.ts
  packages/boot/test/bootstrapTests/zcf-upgrade.test.ts
  packages/boot/tools/liquidation.ts
Labels: tooling, automerge:no-update

#9514 fix: endow with original unstructured `assert`
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/vat-loader/manager-local.js
  packages/SwingSet/src/supervisors/subprocess-node/supervisor-subprocess-node.js
  packages/SwingSet/test/zcf-ish-upgrade/pseudo-zcf.js
  packages/cosmic-swingset/scripts/clean-core-eval.js
  packages/spawner/src/vat-spawned.js
  packages/swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/core-eval-env.d.ts
  packages/vats/src/repl.js
  packages/xsnap/src/avaAssertXS.js
  packages/xsnap/test/boot-lockdown.test.js
  packages/zoe/src/contractFacet/evalContractCode.js
Labels: automerge:squash

#9518 9281 provideOrchestration to provide asyncTools
  packages/async-flow/src/async-flow.js
  packages/async-flow/src/bijection.js
  packages/async-flow/src/convert.js
  packages/async-flow/src/ephemera.js
  packages/async-flow/src/log-store.js
  packages/async-flow/src/replay-membrane.js
  packages/async-flow/src/types.js
  packages/async-flow/test/async-flow-crank.test.js
  packages/async-flow/test/async-flow-early-completion.test.js
  packages/async-flow/test/async-flow-no-this.js
  packages/async-flow/test/async-flow.test.js
  packages/async-flow/test/bad-host.test.js
  packages/async-flow/test/bijection.test.js
  packages/async-flow/test/convert.test.js
  packages/async-flow/test/equate.test.js
  packages/async-flow/test/log-store.test.js
  packages/async-flow/test/replay-membrane-eventual.test.js
  packages/async-flow/test/replay-membrane-settlement.test.js
  packages/async-flow/test/replay-membrane-zombie.test.js
  packages/async-flow/test/replay-membrane.test.js
  packages/orchestration/package.json
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/facade.test.ts
  packages/orchestration/test/supports.ts
Labels: automerge:rebase

#9529 refactor: exofy Orchestrator, RemoteChainFacade
  packages/orchestration/src/exos/local-chain-account-kit.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/facade.test.ts
Labels: automerge:rebase

#9532 9281 durable orchestrator
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/exos/chain-account-kit.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/icq-connection-kit.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/service.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/utils/chainHub.js
  packages/orchestration/src/utils/orc.js
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/facade.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/types.test-d.ts
Labels: automerge:rebase

#9535 fix(swingset): log vat termination and upgrade better
  packages/SwingSet/src/kernel/kernel.js
Labels: automerge:squash

#9454 feat(orchestration): return unwrapped vows
  packages/orchestration/package.json
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/exos/chain-account-kit.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/icq-connection-kit.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
  packages/orchestration/src/service.js
  packages/orchestration/src/utils/chainHub.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/src/utils/time.js
  packages/orchestration/src/vat-orchestration.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/network-fakes.ts
  packages/orchestration/test/service.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/test/types.test-d.ts
  packages/orchestration/test/utils/chainHub.test.ts
  packages/vats/tools/fake-bridge.js
  packages/vow/src/tools.js
  packages/vow/src/types.js
Labels: automerge:rebase

#9538 9281 chainHub exo
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/examples/sendAnywhere.test.ts
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
Labels: automerge:rebase

#9533 types(zoe): setTestJig param type optional
  packages/zoe/src/contractFacet/types-ambient.d.ts
Labels: automerge:rebase, bypass:integration

#9531 feat(zoe): Make zcf singleton durable
  packages/zoe/package.json
  packages/zoe/src/contractFacet/typeGuards.js
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/typeGuards.js
  packages/zoe/test/unitTests/zcf/zcf.test.js
Labels: automerge:squash

#9537 feat(orchestrator): return unwrapped vows
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/src/utils/time.js
Labels: automerge:rebase

#9476 adopt TypeScript 5.5
  package.json
  packages/cosmic-proto/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#9543 lint: warn on non-resumable code
  .eslintrc.cjs
Labels: automerge:rebase

#9544 9449 resumable chainHub
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
  packages/orchestration/test/examples/sendAnywhere.test.ts
  packages/orchestration/test/exos/chain-hub.test.ts
Labels: automerge:rebase

#9550 retry flaky agoric-cli integration test
  .github/workflows/integration.yml
Labels: automerge:rebase, force:integration

#9547 9449 chain facades return vows
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/chain-info.test.js
  packages/orchestration/test/facade.test.ts
Labels: automerge:rebase, force:integration

#9552 test of revising chain info
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/builders/scripts/inter-protocol/add-STARS.js
  packages/builders/scripts/smart-wallet/build-game1-start.js
  packages/builders/scripts/testing/add-LEMONS.js
  packages/builders/scripts/testing/add-OLIVES.js
  packages/builders/scripts/testing/append-chain-info.js
  packages/builders/scripts/testing/tweak-chain-info.js
  packages/orchestration/scripts/fetch-chain-info.ts
  packages/orchestration/src/proposals/revise-chain-info.js
  packages/orchestration/src/utils/registry.js
Labels: automerge:rebase

#9556 fix(vow): watcher args instead of context
  packages/vow/src/types.js
  packages/vow/src/watch-utils.js
  packages/vow/src/watch.js
  packages/vow/test/watch.test.js
Labels: automerge:squash, force:integration

#9561 fix(vow): handle resolution loops in vows
  packages/vow/src/watch.js
  packages/vow/src/when.js
  packages/vow/test/watch.test.js
Labels: automerge:squash

#9557 Restore a3p tests
  a3p-integration/proposals/a:upgrade-next/localchain.test.js
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/priceFeed-follower-auction.test.js
  a3p-integration/proposals/a:upgrade-next/probeZcfBundleCap.test.js
  a3p-integration/proposals/a:upgrade-next/provisioning.test.js
  a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js
  packages/vats/src/localchain.js
Labels: automerge:rebase, force:integration

#9559 fix(agoric): convey tx opts to `agoric wallet` and subcommands
  packages/agoric-cli/src/commands/wallet.js
Labels: automerge:squash

#9548 explicit heapVowTools
  packages/boot/test/bootstrapTests/ibcClientMock.js
  packages/boot/test/bootstrapTests/ibcServerMock.js
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/facade.test.ts
  packages/vats/src/proposals/localchain-test.js
  packages/vats/src/proposals/network-proposal.js
  packages/vats/src/repl.js
  packages/vats/test/localchain.test.js
  packages/vow/test/vat.test.js
  packages/vow/vat.js
Labels: automerge:rebase, force:integration

#9564 fix(bn-patch): fix bad html evasion
  patches/bn.js+5.2.0.patch
Labels: automerge:squash

#9565 feat(cosmos): Next upgrade is agoric-upgrade-16
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-16/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-16/README.md
  a3p-integration/proposals/a:upgrade-16/agd-tools.js
  a3p-integration/proposals/a:upgrade-16/initial.test.js
  a3p-integration/proposals/a:upgrade-16/localchain.test.js
  a3p-integration/proposals/a:upgrade-16/package.json
  a3p-integration/proposals/a:upgrade-16/prepare.sh
  a3p-integration/proposals/a:upgrade-16/priceFeed-follower-auction.test.js
  a3p-integration/proposals/a:upgrade-16/probeZcfBundleCap.test.js
  a3p-integration/proposals/a:upgrade-16/provisioning-test-submission/send-script-permit.json
  a3p-integration/proposals/a:upgrade-16/provisioning-test-submission/send-script.tjs
  a3p-integration/proposals/a:upgrade-16/provisioning.test.js
  a3p-integration/proposals/a:upgrade-16/synthetic-chain-excerpt.js
  a3p-integration/proposals/a:upgrade-16/test.sh
  a3p-integration/proposals/a:upgrade-16/tsconfig.json
  a3p-integration/proposals/a:upgrade-16/upgradeVaults.test.js
  a3p-integration/proposals/a:upgrade-16/use.sh
  a3p-integration/proposals/a:upgrade-16/vatDetails.js
  a3p-integration/proposals/a:upgrade-16/yarn.lock
  a3p-integration/proposals/a:upgrade-next/README.md
  golang/cosmos/app/app.go
Labels: force:integration

#9526 Fix upgrade behaviors
  a3p-integration/proposals/a:upgrade-next/agd-tools.js
  a3p-integration/proposals/a:upgrade-next/initial.test.js
  a3p-integration/proposals/a:upgrade-next/probeZcfBundleCap.test.js
  a3p-integration/proposals/a:upgrade-next/upgradeVaults.js
  a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js
  a3p-integration/proposals/a:upgrade-next/use.sh
  a3p-integration/proposals/b:enable-orchestration/initial.test.js
  a3p-integration/proposals/z:acceptance/create-kread-item-test.sh
  a3p-integration/proposals/z:acceptance/generate-kread-item-request.mjs
  a3p-integration/proposals/z:acceptance/test.sh
  golang/cosmos/app/app.go
  packages/builders/scripts/vats/revive-kread.js
  packages/vats/src/proposals/kread-proposal.js
  packages/vats/src/proposals/probeZcfBundle.js
Labels: automerge:rebase, force:integration

#9563 Support for `snapshots export` command
  a3p-integration/.yarn/patches/@agoric-synthetic-chain-npm-0.1.0-148de716a6.patch
  a3p-integration/package.json
  a3p-integration/proposals/z:acceptance/state-sync-snapshots-test.sh
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/yarn.lock
  golang/cosmos/daemon/cmd/root.go
Labels: automerge:rebase, force:integration

#9516 fix: many typing improvements
  packages/governance/src/types.js
  packages/inter-protocol/src/proposals/add-auction.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/smartWallet/contexts.js
  packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/smart-wallet/test/contexts.js
  packages/smart-wallet/test/supports.js
  packages/swingset-liveslots/src/vatDataTypes.d.ts
  packages/vats/src/bridge.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/core/demoIssuers.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/core/utils.js
  packages/vats/src/proposals/localchain-proposal.js
  packages/vats/src/proposals/network-proposal.js
  packages/vats/src/proposals/transfer-proposal.js
  packages/vats/src/types.d.ts
  packages/vats/src/vat-zoe.js
  packages/vats/test/clientBundle.test.js
  packages/vats/test/vat-bank-integration.test.js
Labels: automerge:no-update

#9573 test(orchestration): skip non-invitation-based boot tests
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/vat-orchestration.test.ts
Labels: automerge:rebase

#9549 Swing-store export data outside of genesis file
  a3p-integration/proposals/z:acceptance/genesis-test.sh
  a3p-integration/proposals/z:acceptance/test.sh
  golang/cosmos/proto/agoric/swingset/genesis.proto
  golang/cosmos/types/kv_entry_helpers.go
  golang/cosmos/x/swingset/genesis.go
  golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go
  golang/cosmos/x/swingset/types/genesis.pb.go
Labels: automerge:rebase, force:integration

#9551 feat(orchestrate): membrane friendly wrapper for agoricNames
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/exos/agoric-names-tools.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/exos/agoric-names-tools.test.ts
Labels: automerge:rebase

#9566 feat(async-flow): endowments
  packages/async-flow/index.js
  packages/async-flow/package.json
  packages/async-flow/src/async-flow.js
  packages/async-flow/src/bijection.js
  packages/async-flow/src/convert.js
  packages/async-flow/src/endowments.js
  packages/async-flow/src/ephemera.js
  packages/async-flow/src/equate.js
  packages/async-flow/src/log-store.js
  packages/async-flow/src/replay-membrane.js
  packages/async-flow/src/types.js
  packages/async-flow/test/bijection.test.js
  packages/async-flow/test/endowments.test.js
  packages/async-flow/test/equate.test.js
  packages/async-flow/test/log-store.test.js
  packages/async-flow/test/replay-membrane-eventual.test.js
  packages/async-flow/test/replay-membrane-settlement.test.js
  packages/async-flow/test/replay-membrane-zombie.test.js
  packages/async-flow/test/replay-membrane.test.js
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/facade.js
  packages/orchestration/test/examples/sendAnywhere.test.ts
  packages/orchestration/test/examples/swapExample.test.ts
Labels: automerge:squash, asyncFlow

#9562 feat: ChainAccountKit returns vows
  .eslintrc.cjs
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/exos/chain-account-kit.js
  packages/orchestration/src/exos/icq-connection-kit.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/service.test.ts
  packages/vow/src/vow-utils.js
Labels: automerge:rebase

#9585 Remove scaled price authority upgrade
  a3p-integration/proposals/a:upgrade-next/agd-tools.js
  a3p-integration/proposals/a:upgrade-next/upgradeVaults.test.js
  golang/cosmos/app/app.go
Labels: bug, automerge:rebase, contract-upgrade, Vaults, force:integration, auction

#9575 feat: make software upgrade `coreProposals` conditional on upgrade plan name
  a3p-integration/proposals/a:upgrade-next/package.json
  golang/cosmos/app/app.go
  golang/cosmos/app/upgrade.go
  golang/cosmos/vm/core_proposals.go
  packages/builders/scripts/vats/priceFeedSupport.js
  packages/builders/scripts/vats/updateStAtomPriceFeed.js
  packages/builders/scripts/vats/updateStkAtomPriceFeed.js
  packages/inter-protocol/src/proposals/upgrade-vaults.js
Labels: automerge:rebase, force:integration

#9607 fix(vow): include vat.js in package files
  packages/vow/package.json
Labels: automerge:rebase

#9593 fix(orchestration): errors should have error messages
  packages/orchestration/package.json
  packages/orchestration/src/utils/packet.js
  packages/orchestration/test/service.test.ts
  packages/orchestration/test/utils/packet.test.ts
Labels: automerge:squash

#9586 refactor(orchestration): simplify example guest code
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
Labels: automerge:squash

#9558 refactor(SwingSet): minor tidying extracted from #9539
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
Labels: technical-debt, automerge:squash

#9601 fix(cosmos): only allow snapshot export at latest height
  golang/cosmos/daemon/cmd/root.go
Labels: automerge:squash

#9590 docs: fix typo in a comment in vat-data-bindings.js
  packages/vat-data/src/vat-data-bindings.js
Labels: automerge:squash

#9583 Patch @cosmjs/math for SES compatibility
  packages/cosmic-proto/package.json
  packages/cosmic-proto/test/bundle-cosmjs-math.js
  packages/cosmic-proto/test/bundle-cosmjs-math.test.js
  patches/@cosmjs+math+0.32.3.patch
Labels: automerge:rebase, force:integration

#9591 chore(orchestration): endowments are membrane-friendly
  .eslintrc.cjs
  packages/boot/test/bootstrapTests/lca.test.ts
  packages/boot/test/bootstrapTests/vat-orchestration.test.ts
  packages/boot/tools/supports.ts
  packages/orchestration/src/exos/agoric-names-tools.js
  packages/orchestration/src/exos/chain-account-kit.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/internal.ts
  packages/orchestration/src/service.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/examples/stake-atom.contract.test.ts
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/service.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/types.test-d.ts
  packages/smart-wallet/package.json
  packages/smart-wallet/src/offerWatcher.js
  packages/vats/tools/fake-bridge.js
  packages/vow/test/watch-utils.test.js
Labels: automerge:rebase, force:integration

#9619 fix: typescript-estree does not support Node.js LTS
  patches/@typescript-eslint+typescript-estree+7.13.0.patch
Labels: automerge:rebase
