Repository Agoric/agoric-sdk, pull requests merged in 2024-08, with the labels that each got.

#9824 docs: added PR guidelines wiki link to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: automerge:rebase

#9809 refactor: Remove extraneous CapTP types imports
  packages/agoric-cli/src/init.js
Labels: automerge:rebase, force:integration

#9811 chore: Sync Endo 2024-07-30
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/xsnap-store.test.js.md
  packages/SwingSet/test/snapshots/xsnap-store.test.js.snap
  packages/agoric-cli/package.json
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/builders/scripts/inter-protocol/manual-price-feed.js
  packages/builders/scripts/testing/start-auto-stake-it.js
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/stat-logger/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vats/src/localchain.js
  packages/vats/src/proposals/upgrade-provisionPool-proposal.js
  packages/vow/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zone/package.json
  patches/@endo+lockdown+1.0.7.patch
  patches/ses+1.5.0.patch
  yarn.lock
Labels: automerge:rebase, force:integration

#9787 ci: fix flakiness in `update-check` in Manage integration check workflow
  .github/workflows/manage-integration-check.yml
Labels: automerge:rebase

#9798 feat: getVBankAssetInfo() on orch.getChain('agoric')
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/sendAnywhere.flows.js
  packages/orchestration/src/exos/agoric-names-tools.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/examples/snapshots/sendAnywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/sendAnywhere.test.ts.snap
  packages/orchestration/test/exos/agoric-names-tools.test.ts
Labels: automerge:rebase

#9802 ci: added a new high priority queue to mergify
  .mergify.yml
Labels: automerge:rebase

#9820 feat(orch): packet affordances for `LocalOrchestrationAccount`
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/boot/tools/supports.ts
  packages/orchestration/src/exos/ibc-packet.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/packet-tools.js
  packages/orchestration/test/examples/auto-stake-it.contract.test.ts
  packages/orchestration/test/examples/sendAnywhere.test.ts
  packages/orchestration/test/examples/snapshots/sendAnywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/sendAnywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbondExample.test.ts.md
  packages/orchestration/test/examples/snapshots/unbondExample.test.ts.snap
  packages/orchestration/test/examples/swapExample.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/tools/ibc-mocks.ts
  packages/vats/src/localchain.js
  packages/vats/src/types.d.ts
  packages/vow/test/vat.test.js
Labels: automerge:no-update, IBC

#9799 ci(getting-started): mitigate `registry/yarn` flake
  .github/workflows/integration.yml
  packages/agoric-cli/src/helpers.js
  packages/agoric-cli/tools/getting-started.js
  scripts/get-versions.sh
  scripts/registry.sh
  scripts/resolve-versions.sh
Labels: automerge:no-update, force:integration

#9804 check dirty git tree after running CI jobs
  .github/actions/restore-node/action.yml
  .github/actions/restore-node/check-git-status.sh
  .gitignore
  a3p-integration/.gitignore
  packages/cosmic-swingset/.gitignore
Labels: automerge:rebase, force:integration

#9833 feat: robustify allManagersDo
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/vaultFactory/director-allMgrsDo.test.js
Labels: code-style, automerge:squash, Vaults

#9847 chore: narrow scope of .gitignore for proposals/a:upgrade-next folder
  a3p-integration/.gitignore
  a3p-integration/proposals/a:upgrade-next/.gitignore
Labels: automerge:rebase, force:integration

#9849 ci: ignore yarn.lock when the branch is valid
  .github/actions/restore-node/action.yml
  .github/actions/restore-node/check-git-status.sh
Labels: automerge:rebase, force:integration

#9861 ci: fix failing `post-test` action
  .github/actions/post-test/action.yml
Labels: automerge:rebase

#9727 docs: bump typedoc to 0.26.4
  package.json
  scripts/update-typedoc-functions-path.cjs
  yarn.lock
Labels: automerge:rebase

#9410 refactor(ERTP,vats): AmountPatternShape
  packages/ERTP/src/typeGuards.js
  packages/vats/src/localchain.js
  packages/vats/src/virtual-purse.js
  packages/vats/test/vpurse.test.js
Labels: technical-debt, automerge:squash

#9794 ci: force rebase and autosquash before merging
  .github/workflows/mergify-ready.yml
  .mergify.yml
Labels: automerge:rebase

#9870 feat: implement `OrchestrationAccountI` .send() and .sendAll() methods
  packages/boot/test/bootstrapTests/lca.test.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/boot/tools/supports.ts
  packages/cosmic-proto/package.json
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/examples/auto-stake-it.contract.test.ts
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/ibc-mocks.ts
  packages/orchestration/test/network-fakes.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase

#9825 ci: removed deprecated fields in mergify
  .mergify.yml
Labels: automerge:rebase

#9734 config lint to harden exports
  packages/boot/test/bootstrapTests/zcf-upgrade.test.ts
  packages/boot/test/bootstrapTests/zcfProbe.contract.js
  packages/eslint-config/eslint-config.cjs
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/test/supports.js
  packages/orchestration/src/examples/auto-stake-it.contract.js
  packages/orchestration/src/examples/auto-stake-it.flows.js
  packages/orchestration/src/examples/basic-flows.contract.js
  packages/orchestration/src/examples/basic-flows.flows.js
  packages/orchestration/src/examples/sendAnywhere.contract.js
  packages/orchestration/src/examples/sendAnywhere.flows.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/test/examples/bad.flows.js
Labels: automerge:rebase

#9169 fix(swingset): use "dirt" to schedule vat reap/bringOutYourDead
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/controller/upgradeSwingset.js
  packages/SwingSet/src/index.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
  packages/SwingSet/src/lib/recordVatOptions.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/bundling/bundles-kernel.test.js
  packages/SwingSet/test/change-parameters/change-parameters.test.js
  packages/SwingSet/test/clist.test.js
  packages/SwingSet/test/controller.test.js
  packages/SwingSet/test/kernel.test.js
  packages/SwingSet/test/snapshots/state.test.js.md
  packages/SwingSet/test/snapshots/state.test.js.snap
  packages/SwingSet/test/state.test.js
  packages/SwingSet/test/transcript-light.test.js
  packages/SwingSet/test/upgrade-swingset.test.js
  packages/SwingSet/test/vat-admin/bootstrap.js
  packages/SwingSet/test/vat-admin/create-vat.test.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: SwingSet, automerge:rebase

#9478 feat(swing-store): budget-limited deletion of snapshot and transcripts
  packages/SwingSet/docs/configuration.md
  packages/swing-store/docs/bundlestore.md
  packages/swing-store/docs/kvstore.md
  packages/swing-store/docs/snapstore.md
  packages/swing-store/docs/swingstore.md
  packages/swing-store/docs/transcriptstore.md
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/src/transcriptStore.js
  packages/swing-store/test/deletion.test.js
Labels: SwingSet, automerge:rebase, swing-store

#9227 feat(swingset): allow slow deletion of terminated vats
  packages/SwingSet/docs/run-policy.md
  packages/SwingSet/src/controller/upgradeSwingset.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/lib/runPolicies.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/snapshots/state.test.js.md
  packages/SwingSet/test/snapshots/state.test.js.snap
  packages/SwingSet/test/state.test.js
  packages/SwingSet/test/stripPrefix.test.js
  packages/SwingSet/test/transcript-light.test.js
  packages/SwingSet/test/upgrade-swingset.test.js
  packages/SwingSet/test/vat-admin/slow-termination/bootstrap-slow-terminate.js
  packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
  packages/SwingSet/test/vat-admin/slow-termination/vat-slow-terminate.js
  packages/SwingSet/test/vat-admin/terminate/terminate.test.js
  packages/internal/src/index.js
Labels: SwingSet, automerge:rebase, swing-store

#9253 feat(swingset): add controller.terminateVat(vatID, reason)
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/test/external-termination/bootstrap-external-termination.js
  packages/SwingSet/test/external-termination/external-termination.test.js
  packages/SwingSet/test/external-termination/vat-doomed.js
Labels: SwingSet, automerge:rebase

#9829 feat: add the ability to override param values
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/test/unitTests/typedParamManager.test.js
  packages/inter-protocol/src/proposals/upgrade-vaults.js
  packages/inter-protocol/src/vaultFactory/vaultFactory.js
Labels: Governance, automerge:rebase, contract-upgrade, Vaults

#9759 auction scheduler robustness
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/auction/auctionMath.js
  packages/inter-protocol/test/auction/auctionMath.test.js
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/test/unitTests/contractSupport/ratio.test.js
Labels: automerge:rebase

#9884 import .ts modules with .js
  packages/benchmark/benchmark/benchmark-liquidation.js
  packages/benchmark/src/benchmarkerator.js
  packages/benchmark/tsconfig.json
  packages/boot/test/bootstrapTests/addAssets.test.ts
  packages/boot/test/bootstrapTests/demo-config.test.ts
  packages/boot/test/bootstrapTests/lca.test.ts
  packages/boot/test/bootstrapTests/liquidation-1.test.ts
  packages/boot/test/bootstrapTests/liquidation-2b.test.ts
  packages/boot/test/bootstrapTests/liquidation-concurrent-1.test.ts
  packages/boot/test/bootstrapTests/liquidation-concurrent-2b.test.ts
  packages/boot/test/bootstrapTests/net-ibc-upgrade.test.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/vat-orchestration.test.ts
  packages/boot/test/bootstrapTests/vats-restart.test.ts
  packages/boot/test/bootstrapTests/vaults-integration.test.ts
  packages/boot/test/bootstrapTests/vaults-upgrade.test.ts
  packages/boot/test/bootstrapTests/vow-offer-results.test.ts
  packages/boot/test/bootstrapTests/vtransfer.test.ts
  packages/boot/test/bootstrapTests/walletFactory.ts
  packages/boot/test/bootstrapTests/walletSurvivesZoeRestart.test.ts
  packages/boot/test/bootstrapTests/zcf-upgrade.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/boot/test/upgrading/upgrade-vats.test.ts
  packages/boot/tools/drivers.ts
  packages/boot/tsconfig.json
  packages/cosmic-proto/test/helpers.test-d.ts
Labels: automerge:rebase

#9898 test(e2e): sendAnywhere contract
  a3p-integration/package.json
  multichain-testing/test/auto-stake-it.test.ts
  multichain-testing/test/basic-flows.test.ts
  multichain-testing/test/send-anywhere.test.ts
  multichain-testing/test/smart-wallet.test.ts
  multichain-testing/test/stake-ica.test.ts
  multichain-testing/tools/e2e-tools.js
  packages/builders/scripts/testing/start-sendAnywhere.js
  packages/orchestration/src/examples/sendAnywhere.flows.js
  packages/orchestration/src/exos/packet-tools.js
  packages/orchestration/src/utils/zoe-tools.js
  packages/orchestration/test/examples/swapExample.test.ts
Labels: automerge:rebase, force:integration

#9882 feat: implement `.transfer` on `CosmosOrchestrationAccount`
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/vat-orchestration.test.ts
  packages/boot/test/tools/ibc/mocks.test.ts
  packages/boot/tools/ibc/mocks.ts
  packages/boot/tools/supports.ts
  packages/builders/scripts/testing/restart-stakeAtom.js
  packages/cosmic-proto/package.json
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/src/utils/time.js
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/exos/make-test-coa-kit.ts
  packages/orchestration/test/exos/make-test-loa-kit.ts
  packages/orchestration/test/ibc-mocks.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/types.test-d.ts
  packages/orchestration/tools/ibc-mocks.ts
Labels: automerge:rebase

#9878 Update a3p-integration after upgrade 16
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/README.md
  a3p-integration/proposals/a:upgrade-next/README.md
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/probeZcfBundleCap.test.js
  a3p-integration/proposals/a:upgrade-next/provisioning-test-submission/send-script-permit.json
  a3p-integration/proposals/a:upgrade-next/provisioning-test-submission/send-script.tjs
  a3p-integration/proposals/a:upgrade-next/provisioning.test.js
  golang/cosmos/app/app.go
  golang/cosmos/app/upgrade.go
Labels: test, automerge:rebase, contract-upgrade, force:integration, next-release

#9880 improve slow-deletion runPolicy cleanup budget API
  packages/SwingSet/docs/run-policy.md
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/lib/runPolicies.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
  packages/swing-store/docs/snapstore.md
  packages/swing-store/docs/transcriptstore.md
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/transcriptStore.js
Labels: SwingSet, automerge:rebase, swing-store

#9874 feat(swingset-liveslots): endow passStyleOf to liveslots guest compartment
  packages/SwingSet/package.json
  packages/SwingSet/test/vat-env.test.js
  packages/SwingSet/test/vat-envtest.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/test/vat-environment.test.js
  packages/swingset-liveslots/tools/setup-vat-data.js
  packages/vats/package.json
  patches/@endo+compartment-mapper+1.2.1.patch
Labels: automerge:squash

#9910 chore: include test-multichain-e2e in finalize-integration-result
  .github/workflows/integration.yml
Labels: automerge:rebase

#9907 fix(vaultFactory): don't prevent repayment based on DebtLimit
  packages/inter-protocol/src/contractSupport.js
  packages/inter-protocol/test/contractSupport.test.js
  packages/inter-protocol/test/vaultFactory/vault-collateralization.test.js
Labels: automerge:rebase

#9911 Add a coreEval for vaults auctions and test in a3p
  a3p-integration/proposals/a:upgrade-next/upgradeVaults.js
  a3p-integration/proposals/a:vaults-auctions/.yarnrc.yml
  a3p-integration/proposals/a:vaults-auctions/README.md
  a3p-integration/proposals/a:vaults-auctions/agd-tools.js
  a3p-integration/proposals/a:vaults-auctions/package.json
  a3p-integration/proposals/a:vaults-auctions/test.sh
  a3p-integration/proposals/a:vaults-auctions/upgradeVaults.test.js
  a3p-integration/proposals/a:vaults-auctions/use.sh
  a3p-integration/proposals/a:vaults-auctions/vatDetails.js
  a3p-integration/proposals/a:vaults-auctions/yarn.lock
  a3p-integration/proposals/e:upgrade-next/.gitignore
  a3p-integration/proposals/e:upgrade-next/.yarnrc.yml
  a3p-integration/proposals/e:upgrade-next/README.md
  a3p-integration/proposals/e:upgrade-next/agd-tools.js
  a3p-integration/proposals/e:upgrade-next/initial.test.js
  a3p-integration/proposals/e:upgrade-next/localchain.test.js
  a3p-integration/proposals/e:upgrade-next/package.json
  a3p-integration/proposals/e:upgrade-next/prepare.sh
  a3p-integration/proposals/e:upgrade-next/priceFeed-follower-auction.test.js
  a3p-integration/proposals/e:upgrade-next/provisionPool.test.js
  a3p-integration/proposals/e:upgrade-next/synthetic-chain-excerpt.js
  a3p-integration/proposals/e:upgrade-next/test.sh
  a3p-integration/proposals/e:upgrade-next/tsconfig.json
  a3p-integration/proposals/e:upgrade-next/vatDetails.js
  a3p-integration/proposals/e:upgrade-next/yarn.lock
  golang/cosmos/app/upgrade.go
  package.json
  packages/inter-protocol/src/proposals/add-auction.js
  packages/inter-protocol/src/proposals/upgrade-vaults.js
  packages/orchestration/package.json
  patches/@noble+hashes+1.4.0.patch
  yarn.lock
Labels: automerge:rebase, contract-upgrade, Vaults, auction

#9873 fix: giving collateral should not change totalDebt
  packages/inter-protocol/src/interest.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/snapshots/vaultFactory.test.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/vaultFactory.test.js.snap
  packages/inter-protocol/test/vaultFactory/vault-collateralization.test.js
  packages/inter-protocol/test/vaultFactory/vaultFactory.test.js
Labels: automerge:rebase, Vaults

#9899 fix npm registry flake
  .github/workflows/integration.yml
  scripts/registry.sh
Labels: automerge:rebase, force:integration

#9926 Ratio.quantize() shouldn't increase precision unnecessarily
  packages/inter-protocol/test/auction/sortedOffers.test.js
  packages/inter-protocol/test/vaultFactory/snapshots/vaultFactory.test.js.md
  packages/inter-protocol/test/vaultFactory/snapshots/vaultFactory.test.js.snap
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/test/unitTests/contractSupport/ratio.test.js
Labels: automerge:rebase

#9932 fix(vow): export vat-compatible tools by default
  packages/vow/README.md
  packages/vow/src/index.js
  packages/vow/src/tools.js
  packages/vow/test/asVow.test.js
  packages/vow/test/disconnect.test.js
  packages/vow/test/watch-utils.test.js
  packages/vow/test/watch.test.js
  packages/vow/vat.js
Labels: automerge:no-update, contract-upgrade

#9937 Specify a bundle to use when upgrading auctions
  a3p-integration/proposals/a:vaults-auctions/upgradeVaults.test.js
  packages/builders/scripts/vats/add-auction.js
  packages/inter-protocol/src/proposals/add-auction.js
  packages/inter-protocol/src/proposals/upgrade-vaults.js
Labels: automerge:squash, contract-upgrade, force:integration, auction, next-release

#9929 ci(integration): add a step to archive core eval scripts
  .github/workflows/integration.yml
Labels: automerge:squash, force:integration

#9927 feat: plumb `icqConnection` through `orchestrate` facade
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/basic-flows.contract.js
  packages/orchestration/src/examples/basic-flows.flows.js
  packages/orchestration/src/exos/icq-connection-kit.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/examples/basic-flows.contract.test.ts
  packages/orchestration/test/network-fakes.ts
  packages/vats/src/types.d.ts
Labels: automerge:rebase

#9917 docs: Update multichain-testing README.md
  multichain-testing/Makefile
  multichain-testing/README.md
Labels: automerge:rebase

#9944 get auction instance from promise returned by addAuction
  packages/inter-protocol/src/proposals/add-auction.js
  packages/inter-protocol/src/proposals/upgrade-vaults.js
Labels: automerge:rebase, contract-upgrade, Vaults, auction

#9947 fixup dapp CI config
  .github/actions/restore-node/action.yml
  .github/workflow-templates/test-dapp.yml
  .github/workflows/README.md
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/test-dapp-treasury.yml.DISABLED
  .github/workflows/test-documentation.yml
  .github/workflows/update-hackathon-branch.yml.DISABLED
Labels: automerge:rebase

#9950 ci: update versions for github actions
  .github/actions/restore-golang/action.yml
  .github/actions/restore-node/action.yml
  .github/workflows/after-merge.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
Labels: automerge:rebase, force:integration

#9953 feat: add null upgrade of vaultFactoryGovernor to upgrade-vaults.js
  .gitignore
  a3p-integration/proposals/z:acceptance/lib/vaults.mts
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/scripts/test-vaults.mts
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/tsconfig.json
  a3p-integration/proposals/z:acceptance/yarn.lock
  packages/inter-protocol/src/proposals/upgrade-vaults.js
Labels: Governance, automerge:rebase, contract-upgrade, Vaults, force:integration

#9868 feat(ibc): clean up channel closure process
  a3p-integration/proposals/e:upgrade-next/.gitignore
  a3p-integration/proposals/e:upgrade-next/initial.test.js
  golang/cosmos/app/upgrade.go
  golang/cosmos/x/vibc/types/ibc_module.go
  golang/cosmos/x/vtransfer/ibc_middleware.go
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/builders/scripts/vats/upgrade-orch-core.js
  packages/network/src/network.js
  packages/network/src/router.js
  packages/network/src/shapes.js
  packages/network/test/fakes.js
  packages/network/test/network-misc.test.js
  packages/orchestration/test/network-fakes.ts
  packages/pegasus/test/peg.test.js
  packages/vats/src/ibc.js
  packages/vats/src/proposals/upgrade-orch-core-proposal.js
  packages/vats/src/types.d.ts
  packages/vats/src/vat-network.js
  packages/vats/test/network.test.js
  packages/vats/tools/fake-bridge.js
Labels: automerge:no-update, force:integration, IBC

#9970 feat: update auction in agoricNames, test that the boardId changed
  a3p-integration/proposals/a:vaults-auctions/agd-tools.js
  a3p-integration/proposals/a:vaults-auctions/eval.sh
  a3p-integration/proposals/a:vaults-auctions/prepare.sh
  a3p-integration/proposals/a:vaults-auctions/saveAuctionInstance.js
  a3p-integration/proposals/a:vaults-auctions/upgradeVaults.test.js
  packages/inter-protocol/src/proposals/add-auction.js
Labels: automerge:rebase, contract-upgrade, force:integration, auction, next-release

#9857 9068 close account
  packages/boot/tools/ibc/README.md
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/ica-account-kit.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/cosmos-interchain-service.test.ts
  packages/orchestration/test/network-fakes.ts
  packages/orchestration/test/service.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/tools/ibc-mocks.ts
Labels: automerge:rebase, force:integration

#9930 docs(swingset): fix run-policy docs, didCleanup returns keep-going
  packages/SwingSet/docs/run-policy.md
Labels: automerge:rebase

#9984 agops setPrice ux improvements
  packages/agoric-cli/src/commands/oracle.js
Labels: automerge:rebase, bypass:integration

#9975 chore (packages): Fix remaining lint issues (#9632)
  packages/agoric-cli/test/inter-cli.test.js
  packages/inter-protocol/src/proposals/startPSM.js
Labels: agoric-cli, test, code-style, Inter-protocol, automerge:rebase

#9974 test: increase attempts for rewards available condition
  multichain-testing/test/stake-ica.test.ts
  multichain-testing/tools/sleep.ts
Labels: automerge:rebase, force:integration

#9864 9068 close account e2e
  multichain-testing/test/auto-stake-it.test.ts
  multichain-testing/test/basic-flows.test.ts
  multichain-testing/test/ica-channel-close.test.ts
  multichain-testing/test/send-anywhere.test.ts
  multichain-testing/test/support.ts
  multichain-testing/test/tools/address.test.ts
  multichain-testing/tools/address.ts
  multichain-testing/tools/hermes-tools.ts
  multichain-testing/tools/query.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/orchestration/src/examples/stakeIca.contract.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/test/examples/snapshots/stake-ica.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/stake-ica.contract.test.ts.snap
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/orchestration/test/exos/make-test-coa-kit.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/types.test-d.ts
Labels: automerge:rebase, force:integration

#9976 chore: make `create-dapp` compatible with yarn4
  packages/create-dapp/package.json
  packages/create-dapp/test/sanity.test.js
  yarn.lock
Labels: automerge:rebase

#9993 fix: use controllerConnectionId for ICQConnection
  packages/orchestration/src/exos/remote-chain-facade.js
Labels: automerge:rebase, force:integration

#8840 build(golang): Support faster local iteration and align better with upstream
  golang/cosmos/Makefile
  packages/cosmic-proto/update-protos.sh
Labels: automerge:rebase

#9935 feat: plumb `localchain.queryMany` through orchestrate facade
  multichain-testing/config.yaml
  multichain-testing/test/chain-queries.test.ts
  multichain-testing/test/stake-ica.test.ts
  multichain-testing/test/support.ts
  packages/cosmic-proto/src/helpers.ts
  packages/orchestration/src/examples/basic-flows.contract.js
  packages/orchestration/src/examples/basic-flows.flows.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/examples/basic-flows.contract.test.ts
  packages/orchestration/test/types.test-d.ts
  packages/vats/src/localchain.js
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase, force:integration

#9960 docs: add README to orchestration/src/examples
  packages/orchestration/src/examples/README.md
Labels: automerge:rebase

#9983 9211 lookup denom
  multichain-testing/test/auto-stake-it.test.ts
  multichain-testing/test/config.ts
  multichain-testing/test/stake-ica.test.ts
  multichain-testing/tools/ibc-transfer.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/orchestration/src/examples/auto-stake-it.flows.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/exos/chain-hub-admin.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/amounts.js
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/examples/auto-stake-it.contract.test.ts
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/exos/make-test-coa-kit.ts
  packages/orchestration/test/exos/make-test-loa-kit.ts
  packages/orchestration/test/exos/portfolio-holder-kit.test.ts
  packages/orchestration/test/facade.test.ts
  packages/orchestration/test/ibc-mocks.test.ts
  packages/orchestration/test/ibc-mocks.ts
  packages/orchestration/test/network-fakes.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/test/types.test-d.ts
  packages/orchestration/tools/ibc-mocks.ts
Labels: automerge:rebase, force:integration

#9987 fix(cosmic-swingset)!: Extend and partition cosmos-sdk configuration for cosmic-swingset
  golang/cosmos/app/app.go
  golang/cosmos/daemon/cmd/root.go
  golang/cosmos/go.mod
  golang/cosmos/util/util.go
  golang/cosmos/x/swingset/config.go
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:rebase

#10005 fix(liveslots): move passStyleOf from vatGlobals to inescapableGlobalProperties
  packages/SwingSet/test/vat-env.test.js
  packages/SwingSet/test/vat-envtest.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/test/vat-environment.test.js
Labels: automerge:rebase

#9961 fix(liveslots): collection deletion and retirement bugs
  packages/swingset-liveslots/src/boyd-gc.js
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/src/virtualReferences.js
  packages/swingset-liveslots/test/clear-collection.test.js
  packages/swingset-liveslots/test/collections.test.js
  packages/swingset-liveslots/test/gc-before-finalizer.test.js
  packages/swingset-liveslots/test/liveslots-mock-gc.test.js
  packages/swingset-liveslots/test/weakset-dropped-remotable.test.js
Labels: automerge:rebase, liveslots

#10008 fix(liveslots): collection.clear(pattern) vs getSize
  packages/swingset-liveslots/src/collectionManager.js
  packages/swingset-liveslots/test/collections.test.js
Labels: automerge:rebase

#9997 9900 elide comments in bundles
  multichain-testing/scripts/update-config.sh
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/src/devices/vat-admin/device-vat-admin.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/agoric-cli/package.json
  packages/agoric-cli/src/scripts.js
  packages/boot/package.json
  packages/boot/test/bootstrapTests/addAssets.test.ts
  packages/builders/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/create-dapp/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/src/node/createBundles.js
  packages/network/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#10001 Make maxVatsOnline customizable to optimize resource usage #9574
  golang/cosmos/x/swingset/config.go
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: SwingSet, automerge:rebase, force:integration

#9980 Endo Sync 2024-08-27
  packages/agoric-cli/package.json
  packages/agoric-cli/src/follow.js
  packages/xsnap/api.js
  patches/@endo+compartment-mapper+1.2.2.patch
  patches/@endo+eventual-send+1.2.5.patch
  yarn.lock
Labels: automerge:rebase, force:integration

#10010 improve agd build handling of corepack
  golang/cosmos/package.json
  scripts/agd-builder.sh
Labels: automerge:rebase
