Repository Agoric/agoric-sdk, pull requests merged in 2024-11, with the labels that each got.

#10354 feat(orchestration): lookup `ChainInfo` from address value
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/fetched-chain-info.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/address.js
  packages/orchestration/src/utils/registry.js
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/snapshots/chain-info.test.js.md
  packages/orchestration/test/snapshots/chain-info.test.js.snap
  packages/orchestration/test/utils/address.test.ts
Labels: automerge:rebase

#10381 test: make durable Orch tests able to run concurrently
  packages/orchestration/test/durability.ts
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/facade-durability.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/test/utils/zcf-tools.test.ts
Labels: automerge:rebase

#10383 scaffold Fast USDC contract
  packages/fast-usdc/package.json
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/supports.ts
  packages/fast-usdc/tsconfig.json
Labels: automerge:rebase, bypass:integration

#10379 ci: add job to send test results to gcp
  .github/actions/ci-test-result.cjs
  .github/actions/gcp-monitoring.cjs
  .github/actions/post-test/action.yml
  .github/workflows/test-all-packages.yml
  package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#10380 chore(notifier): Fix typo in README
  packages/notifier/README.md
Labels: automerge:squash, automerge:rebase

#10398 ci: multichain-testing log artifact upload
  .github/workflows/multichain-e2e-template.yml
Labels: automerge:rebase, force:integration

#10297 test(a3p): extend test coverage for Vaults on z:acceptance
  a3p-integration/proposals/n:upgrade-next/openVault.js
  a3p-integration/proposals/n:upgrade-next/sync-tools.js
  a3p-integration/proposals/n:upgrade-next/use.sh
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/test-lib/price-feed.js
  a3p-integration/proposals/z:acceptance/test-lib/psm-lib.js
  a3p-integration/proposals/z:acceptance/test-lib/utils.js
  a3p-integration/proposals/z:acceptance/test-lib/vaults.js
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/vaults.test.js
  a3p-integration/proposals/z:acceptance/wallet.test.js
  a3p-integration/proposals/z:acceptance/yarn.lock
Labels: automerge:rebase

#10404 chore(a3p): replace waitForBlock with retryUntilCondition on acceptance tests
  a3p-integration/proposals/z:acceptance/core-eval.test.js
  a3p-integration/proposals/z:acceptance/exitOffer.js
  a3p-integration/proposals/z:acceptance/localchain.test.js
  a3p-integration/proposals/z:acceptance/valueVow.test.js
  a3p-integration/proposals/z:acceptance/wallet.test.js
Labels: automerge:rebase

#10407 new client-utils package
  .github/workflows/test-all-packages.yml
  packages/agoric-cli/package.json
  packages/agoric-cli/src/commands/auction.js
  packages/agoric-cli/src/commands/gov.js
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/reserve.js
  packages/agoric-cli/src/commands/test-upgrade.js
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/chain.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/src/lib/network-config.js
  packages/agoric-cli/src/lib/wallet.js
  packages/agoric-cli/src/sdk-package-names.js
  packages/agoric-cli/test/inter-cli.test.js
  packages/casting/src/main.js
  packages/casting/src/makeHttpClient.js
  packages/casting/test/interpose-net-access.test.js
  packages/client-utils/CHANGELOG.md
  packages/client-utils/README.md
  packages/client-utils/package.json
  packages/client-utils/src/chain.js
  packages/client-utils/src/main.js
  packages/client-utils/src/rpc.js
  packages/client-utils/src/wallet-utils.js
  packages/client-utils/test/exports.test.js
  packages/client-utils/test/snapshots/exports.test.js.md
  packages/client-utils/test/snapshots/exports.test.js.snap
  packages/client-utils/tsconfig.build.json
  packages/client-utils/tsconfig.json
  packages/cosmic-proto/scripts/codegen.cjs
  packages/smart-wallet/package.json
  packages/smart-wallet/src/types.ts
Labels: automerge:rebase

#7903 refactor(PSM!): make PSM use zcf.atomicRearrange()
  packages/inter-protocol/src/psm/psm.js
Labels: Zoe, Inter-protocol, automerge:rebase, contract-upgrade

#10413 chore: move xsnap to a peer dependency
  packages/SwingSet/package.json
Labels: automerge:rebase, force:integration

#10250 feat(vtransfer): extract base address from parameterized address
  golang/cosmos/x/vtransfer/ibc_middleware_test.go
  golang/cosmos/x/vtransfer/keeper/keeper.go
  golang/cosmos/x/vtransfer/types/baseaddr.go
  golang/cosmos/x/vtransfer/types/baseaddr_test.go
Labels: automerge:no-update, agd

#10436 fix publishing to NPM
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/async-flow/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/client-utils/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/swing-store/package.json
  packages/telemetry/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/zoe/package.json
  packages/zone/package.json
Labels: automerge:rebase

#10165 feat(cosmic-swingset): Use vat cleanup budget values to allow slow cleanup
  golang/cosmos/ante/inbound_test.go
  golang/cosmos/proto/agoric/swingset/swingset.proto
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/types/default-params.go
  golang/cosmos/x/swingset/types/expected_keepers.go
  golang/cosmos/x/swingset/types/msgs.go
  golang/cosmos/x/swingset/types/params.go
  golang/cosmos/x/swingset/types/params_test.go
  golang/cosmos/x/swingset/types/swingset.pb.go
  golang/cosmos/x/vstorage/testing/queue.go
  golang/cosmos/x/vtransfer/types/genesis.pb.go
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/index.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/tools/bootstrap-relay.js
  packages/SwingSet/tools/vat-puppet.js
  packages/cosmic-proto/proto/agoric/swingset/swingset.proto
  packages/cosmic-proto/src/codegen/agoric/swingset/swingset.ts
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/helpers/bufferedStorage.js
  packages/cosmic-swingset/src/helpers/json-stable-stringify.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/src/params.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/cosmic-swingset/src/sim-params.js
  packages/cosmic-swingset/test/run-policy.test.js
  packages/cosmic-swingset/tools/test-kit.js
  packages/internal/README.md
  packages/internal/package.json
  packages/internal/src/action-types.js
  packages/internal/src/chain-utils.js
  packages/swing-store/src/exporter.js
  packages/swing-store/src/internal.js
  packages/swing-store/src/swingStore.js
  packages/vats/src/core/basic-behaviors.js
  packages/vats/src/core/lib-boot.js
  packages/vats/test/vat-bank-integration.test.js
  packages/vats/tools/bootstrap-chain-reflective.js
  packages/vats/tsconfig.build.json
Labels: automerge:rebase, force:integration

#10438 test(cosmic-swingset): Include the last three lines of stderr when a `make` test fails
  packages/cosmic-swingset/test/scenario2.js
Labels: automerge:squash

#10358 chore: move PR template comment to the top
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling, automerge:no-update, bypass:integration

#10440 chore(x/swingset): Add comments to chargeAdmission
  golang/cosmos/x/swingset/types/msgs.go
Labels: automerge:squash

#10422 vstorage published types mapping
  packages/boot/package.json
  packages/boot/test/bootstrapTests/ec-membership-update.test.ts
  packages/boot/test/bootstrapTests/liquidation-1.test.ts
  packages/boot/test/bootstrapTests/liquidation-2b.test.ts
  packages/boot/test/bootstrapTests/liquidation-concurrent-1.test.ts
  packages/boot/test/bootstrapTests/liquidation-concurrent-2b.test.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/price-feed-replace.test.ts
  packages/boot/test/bootstrapTests/vaults-upgrade.test.ts
  packages/boot/tools/drivers.ts
  packages/boot/tools/liquidation.ts
  packages/boot/tools/supports.ts
  packages/client-utils/package.json
  packages/client-utils/src/main.js
  packages/client-utils/src/types.d.ts
  packages/client-utils/src/types.js
  packages/client-utils/src/vstorage-kit.js
  packages/client-utils/src/wallet-utils.js
  packages/client-utils/tsconfig.build.json
Labels: automerge:rebase

#10450 use readPublished for types in agoric-cli
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/agoric-cli/src/commands/auction.js
  packages/agoric-cli/src/commands/gov.js
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/wallet.js
  packages/boot/package.json
  packages/cosmic-swingset/package.json
  packages/internal/package.json
  packages/vats/package.json
Labels: automerge:rebase, force:integration

#10406 feat: fusdc status manager states
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc/package.json
  packages/fast-usdc/src/constants.js
  packages/fast-usdc/src/exos/README.md
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/typeGuards.js
  packages/fast-usdc/src/types-index.d.ts
  packages/fast-usdc/src/types-index.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/address.js
  packages/fast-usdc/test/constants.test.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/typeGuards.test.ts
  packages/fast-usdc/test/utils/address.test.ts
  packages/orchestration/index.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/snapshots/exports.test.ts.md
  packages/orchestration/test/snapshots/exports.test.ts.snap
Labels: automerge:rebase

#10447 fix(agoric-cli): Default `agoric wallet send` to use `--gas=auto`
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/psm.test.js
  a3p-integration/proposals/z:acceptance/test-lib/psm-lib.js
  a3p-integration/proposals/z:acceptance/yarn.lock
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/helpers.js
  packages/agoric-cli/src/lib/chain.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/test/inter-cli.test.js
  packages/client-utils/src/sync-tools.js
  packages/internal/test/snapshots/exports.test.js.snap
Labels: automerge:rebase, force:integration

#10442 refactor(internal): Separate pure-JS vs. Hardened JS utils
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/devices/bridge/device-bridge.js
  packages/SwingSet/test/upgrade/upgrade-replay.test.js
  packages/SwingSet/test/vat-admin/replay.test.js
  packages/boot/test/upgrading/upgrade-vats.test.ts
  packages/cosmic-swingset/test/run-policy.test.js
  packages/cosmic-swingset/tools/test-kit.js
  packages/inter-protocol/src/auction/auctioneer.js
  packages/internal/src/index.js
  packages/internal/src/js-utils.js
  packages/internal/src/ses-utils.js
  packages/internal/src/types.ts
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/internal/test/utils.test.js
  packages/solo/src/vat-http.js
  packages/wallet/api/src/wallet.js
  packages/wallet/package.json
Labels: automerge:rebase

#10452 10387 simple transaction feed for Fast USDC
  packages/fast-usdc/package.json
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/transaction-feed.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/supports.ts
  packages/orchestration/src/utils/start-helper.js
  packages/zoe/tools/setup-zoe.js
Labels: automerge:rebase

#10455 fix(telemetry): add missing slog type
  packages/telemetry/src/slog-to-otel.js
Labels: automerge:rebase, force:integration

#9863 fix(ERTP,vats): fix 9407 AmountPatternShape
  packages/vats/src/virtual-purse.js
  packages/vats/test/vpurse.test.js
Labels: automerge:squash

#10458 fix(orchestration): denomAmounts must be non-negative
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/orchestration/src/typeGuards.js
Labels: automerge:squash

#10400 feat(fast-usdc): deposit, withdraw liquidity in exchange for shares
  packages/ERTP/src/typeGuards.js
  packages/ERTP/src/types.ts
  packages/fast-usdc/package.json
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/pool-share-math.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/test/supports.ts
  yarn.lock
Labels: automerge:rebase

#10453 chore(replace-fee-dist): create upgrade-19 dir, test new feeDistributor, stage in upgrade.go
  a3p-integration/proposals/p:upgrade-19/.gitignore
  a3p-integration/proposals/p:upgrade-19/.yarnrc.yml
  a3p-integration/proposals/p:upgrade-19/eval.sh
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/replaceFeeDistributor.test.js
  a3p-integration/proposals/p:upgrade-19/test.sh
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/inter-protocol/replace-feeDistributor.js
  packages/builders/scripts/testing/replace-feeDistributor-short.js
  packages/inter-protocol/src/proposals/replace-fee-distributor.js
Labels: automerge:rebase, force:integration

#10341 feat(cosmos-orch-account): expose `.executeEncodedTx`
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/types.test-d.ts
Labels: automerge:rebase

#10468 docs(deploy-script-support): Cleanup README
  packages/deploy-script-support/README.md
Labels: automerge:rebase

#10446 ci: Retain complete a3p-integration directories and resulting slogfiles
  .github/actions/post-test/action.yml
  .github/workflows/integration.yml
  a3p-integration/package.json
  a3p-integration/yarn.lock
  scripts/ci/collect-testruns.sh
  scripts/ci/export-a3p.sh
Labels: automerge:rebase, force:integration

#10466 refactor(a3p-integration): Document and clean up core-eval generation
  a3p-integration/README.md
  a3p-integration/debug-current.sh
  a3p-integration/scripts/build-all-submissions.sh
  a3p-integration/scripts/build-submission.sh
Labels: automerge:rebase, force:integration

#10467 fix(ertp): remove unneeded ertp type imports
  packages/ERTP/src/amountStore.js
  packages/ERTP/src/index.js
  packages/ERTP/src/legacy-payment-helpers.js
  packages/ERTP/src/purse.js
  packages/ERTP/src/transientNotifier.js
Labels: automerge:squash

#10475 chore(agoric-cli): Document external consumption of gettingStartedWorkflowTest
  packages/agoric-cli/integration-tests/workflow.test.js
  packages/agoric-cli/tools/getting-started.js
Labels: automerge:squash

#10462 feat(sync-tools): add method to wait until offer has exited
  packages/client-utils/src/sync-tools.js
  packages/client-utils/test/snapshots/exports.test.js.md
  packages/client-utils/test/snapshots/exports.test.js.snap
  packages/client-utils/test/sync-tools.test.js
Labels: automerge:rebase

#10464 refactor: fewer irritating warnings
  .eslintrc.cjs
  a3p-integration/proposals/n:upgrade-next/synthetic-chain-excerpt.js
  a3p-integration/proposals/z:acceptance/test-lib/vaults.js
  packages/SwingSet/test/metering/metered-code.js
  packages/deployment/src/init.js
  packages/deployment/src/main.js
  packages/network/test/fakes.js
  packages/notifier/test/makeNotifierFromSubscriber.test.js
Labels: automerge:squash

#10486 test(fast-usdc): fix cli test regex
  packages/fast-usdc/test/cli/cli.test.ts
Labels: automerge:squash, bypass:integration

#8061 consolidate lint job
  .github/workflows/test-all-packages.yml
  scripts/lint-with-types.sh
Labels: automerge:rebase, bypass:integration

#10470 fix(orchestration): harden exported patterns
  packages/ERTP/src/typeGuards.js
  packages/SwingSet/src/typeGuards.js
  packages/governance/src/typeGuards.js
  packages/orchestration/src/typeGuards.js
  packages/time/src/typeGuards.js
  packages/zoe/src/typeGuards.js
Labels: automerge:squash

#10487 feat(fast-usdc): add cli config and args for deposit and withdraw
  packages/fast-usdc/src/cli/cli.js
  packages/fast-usdc/test/cli/cli.test.ts
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.md
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.snap
Labels: automerge:squash

#10385 chore(sync-tools): implement `waitUntilElectionResults`
  packages/client-utils/src/sync-tools.js
  packages/client-utils/test/snapshots/exports.test.js.md
  packages/client-utils/test/snapshots/exports.test.js.snap
  packages/client-utils/test/sync-tools.test.js
Labels: automerge:rebase

#10489 FU transaction feed aggregation
  packages/fast-usdc/src/exos/operator-kit.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/exos/transaction-feed.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
Labels: automerge:rebase, bypass:integration

#10482 chore: Better accommodate non-GNU sed
  MAINTAINERS.md
  packages/cosmic-proto/scripts/codegen.cjs
  packages/cosmic-swingset/scripts/single-node.sh
Labels: automerge:squash

#10420 feat: fusdc advancer
  packages/fast-usdc/package.json
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/typeGuards.js
  packages/fast-usdc/src/utils/address.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/test/utils/address.test.ts
  packages/orchestration/src/cosmos-api.ts
Labels: automerge:rebase

#10481 chore(agoric-cli): Type-check *.js files
  packages/agoric-cli/src/anylogger-agoric.js
  packages/agoric-cli/src/chain-config.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/cosmos.js
  packages/agoric-cli/src/helpers.js
  packages/agoric-cli/src/install.js
  packages/agoric-cli/src/lib/network-config.js
  packages/agoric-cli/src/main.js
  packages/agoric-cli/src/scripts.js
  packages/agoric-cli/src/start.js
  packages/agoric-cli/test/bundles-regExp.test.js
  packages/agoric-cli/test/main.test.js
  packages/agoric-cli/test/upgrade-contract/init-proposal.js
  packages/agoric-cli/tsconfig.json
Labels: automerge:rebase

#10497 FU test improvements
  packages/fast-usdc/package.json
  packages/fast-usdc/src/cli/bin.js
  packages/fast-usdc/test/cli/cli.test.ts
  packages/fast-usdc/test/cli/config.test.ts
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.md
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.snap
  packages/fast-usdc/test/cli/transfer.test.ts
  yarn.lock
Labels: automerge:rebase, bypass:integration

#10500 build: Downgrade execa to 9.1.0 for Node.js 18.18 support
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/yarn.lock
  multichain-testing/package.json
  multichain-testing/yarn.lock
  packages/fast-usdc/package.json
  yarn.lock
Labels: automerge:squash, force:integration

#10483 chore(cosmic-proto): Add eslint coverage
  .eslintignore
  packages/cosmic-proto/.eslintignore
  packages/cosmic-proto/package.json
Labels: automerge:squash

#10477 feat(fast-usdc): core-eval, builder script
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/orchestration/contract-upgrade.test.ts
  packages/boot/tools/supports.ts
  packages/builders/package.json
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/fast-usdc/package.json
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/utils/config-marshal.js
  packages/fast-usdc/test/config-marshal.test.js
  packages/vm-config/decentral-itest-orchestration-config.json
Labels: automerge:rebase

#10494 feat: fusdc advancer with fees
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/operator-kit.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/typeGuards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/fees.js
  packages/fast-usdc/test/config-marshal.test.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/supports.ts
  packages/fast-usdc/test/type-guards.test.ts
  packages/fast-usdc/test/utils/address.test.ts
  packages/fast-usdc/test/utils/fees.test.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/cosmos-interchain-service.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/vat-orchestration.js
  packages/orchestration/test/snapshots/exports.test.ts.md
  packages/orchestration/test/snapshots/exports.test.ts.snap
Labels: automerge:rebase

#10515 chore(smart-wallet): less noisy watch outcome
  packages/smart-wallet/src/offerWatcher.js
Labels: automerge:squash

#10471 chore(swing-store): Consolidate keyType assertions
  packages/swing-store/src/exporter.js
  packages/swing-store/src/kvStore.js
  packages/swing-store/src/swingStore.js
Labels: automerge:squash

#10498 chore: Sync Endo release 2024-11-13
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  a3p-integration/proposals/s:stake-bld/yarn.lock
  a3p-integration/proposals/z:acceptance/yarn.lock
  a3p-integration/yarn.lock
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/xsnap-store.test.js.md
  packages/SwingSet/test/snapshots/xsnap-store.test.js.snap
  packages/agoric-cli/package.json
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/client-utils/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/fast-usdc/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/stat-logger/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zone/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#10488 feat(vbank): new param `allowed_monitoring_accounts`
  golang/cosmos/proto/agoric/vbank/vbank.proto
  golang/cosmos/x/vbank/README.md
  golang/cosmos/x/vbank/keeper/keeper.go
  golang/cosmos/x/vbank/keeper/migrations.go
  golang/cosmos/x/vbank/module.go
  golang/cosmos/x/vbank/types/params.go
  golang/cosmos/x/vbank/types/vbank.pb.go
  golang/cosmos/x/vbank/vbank_test.go
  packages/cosmic-proto/proto/agoric/vbank/vbank.proto
  packages/cosmic-proto/src/codegen/agoric/vbank/vbank.ts
Labels: automerge:no-update, agoric-cosmos

#10460 chore: upgrade-18 cherry-picks round 2
  a3p-integration/proposals/a:upgrade-18/prepare.sh
  a3p-integration/proposals/a:upgrade-18/use.sh
  golang/cosmos/app/upgrade.go
  packages/inter-protocol/src/proposals/add-auction.js
  packages/telemetry/src/slog-to-otel.js
Labels: force:integration

#10527 chore(release): publish upgrade-18-rc1
  golang/cosmos/CHANGELOG.md
  golang/cosmos/package.json
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/benchmark/CHANGELOG.md
  packages/benchmark/package.json
  packages/boot/CHANGELOG.md
  packages/boot/package.json
  packages/builders/CHANGELOG.md
  packages/builders/package.json
  packages/casting/CHANGELOG.md
  packages/casting/package.json
  packages/cosmic-proto/CHANGELOG.md
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/create-dapp/CHANGELOG.md
  packages/create-dapp/package.json
  packages/deploy-script-support/CHANGELOG.md
  packages/deploy-script-support/package.json
  packages/fast-usdc/CHANGELOG.md
  packages/fast-usdc/package.json
  packages/inter-protocol/CHANGELOG.md
  packages/inter-protocol/package.json
  packages/orchestration/CHANGELOG.md
  packages/orchestration/package.json
  packages/pegasus/CHANGELOG.md
  packages/pegasus/package.json
  packages/smart-wallet/CHANGELOG.md
  packages/smart-wallet/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
  packages/swingset-runner/CHANGELOG.md
  packages/swingset-runner/package.json
  packages/telemetry/CHANGELOG.md
  packages/telemetry/package.json
  packages/vats/CHANGELOG.md
  packages/vats/package.json
  packages/wallet/api/CHANGELOG.md
  packages/wallet/api/package.json
Labels: force:integration

#10474 feat: fusdc liquidity pool borrow and repay facets
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/fees.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/pool-share-math.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
Labels: automerge:rebase

#10525 chore: minor nitpicking
  .github/workflows/dump-ci-stats.yml
  .github/workflows/test-all-packages.yml
  multichain-testing/tools/e2e-tools.js
  packages/fast-usdc/CHANGELOG.md
  packages/fast-usdc/package.json
Labels: tooling, hygiene, automerge:no-update

#10473 refactor(SwingSet): Simplify upgradeSwingset
  packages/SwingSet/src/controller/upgradeSwingset.js
Labels: automerge:squash

#10485 chore(a3p-integration): Improve log output
  a3p-integration/.eslintignore
  a3p-integration/package.json
  a3p-integration/proposals/n:upgrade-next/.yarn/patches/axios-npm-1.7.7-cfbedc233d.patch
  a3p-integration/proposals/n:upgrade-next/.yarn/patches/protobufjs-npm-6.11.4-af11968b80.patch
  a3p-integration/proposals/n:upgrade-next/acceptInvites.js
  a3p-integration/proposals/n:upgrade-next/addGov4.js
  a3p-integration/proposals/n:upgrade-next/initial.test.js
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/priceFeed-follower-auction.test.js
  a3p-integration/proposals/n:upgrade-next/priceFeedUpdate.test.js
  a3p-integration/proposals/n:upgrade-next/replaceElectorate.test.js
  a3p-integration/proposals/n:upgrade-next/synthetic-chain-excerpt.js
  a3p-integration/proposals/n:upgrade-next/test-lib/price-feed.js
  a3p-integration/proposals/n:upgrade-next/test-lib/sync-tools.js
  a3p-integration/proposals/n:upgrade-next/verifyPushedPrice.js
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/p:upgrade-19/.yarn/patches/axios-npm-1.7.7-cfbedc233d.patch
  a3p-integration/proposals/p:upgrade-19/.yarn/patches/protobufjs-npm-6.11.4-af11968b80.patch
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/replaceFeeDistributor.test.js
  a3p-integration/proposals/p:upgrade-19/tsconfig.json
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  a3p-integration/proposals/s:stake-bld/package.json
  a3p-integration/proposals/s:stake-bld/stakeBld.test.js
  a3p-integration/proposals/s:stake-bld/test-lib/chain.js
  a3p-integration/proposals/s:stake-bld/test-lib/rpc.js
  a3p-integration/proposals/s:stake-bld/test-lib/wallet.js
  a3p-integration/proposals/s:stake-bld/tsconfig.json
  a3p-integration/proposals/s:stake-bld/yarn.lock
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/psm.test.js
  a3p-integration/proposals/z:acceptance/test-lib/chain.js
  a3p-integration/proposals/z:acceptance/test-lib/price-feed.js
  a3p-integration/proposals/z:acceptance/test-lib/psm-lib.js
  a3p-integration/proposals/z:acceptance/valueVow.test.js
  packages/client-utils/src/sync-tools.js
Labels: automerge:rebase, force:integration

#10518 feat: advancer integrates with LP and contract
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/fast-usdc.flows.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/test/supports.ts
  packages/fast-usdc/test/utils/fees.test.ts
Labels: automerge:rebase

#10519 chore(agoric-cli): Condense `agoric wallet show` output
  packages/agoric-cli/src/lib/format.js
Labels: automerge:squash

#10533 chore(a3p-integration): Bump @agoric/synthetic-chain dependencies
  a3p-integration/package.json
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  a3p-integration/proposals/s:stake-bld/package.json
  a3p-integration/proposals/s:stake-bld/yarn.lock
  a3p-integration/proposals/z:acceptance/governance.test.js
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/test-lib/governance.js
  a3p-integration/proposals/z:acceptance/yarn.lock
  a3p-integration/yarn.lock
Labels: automerge:rebase, force:integration

#10534 build(deps): bump cosmossdk.io/math to v1.4.0
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: automerge:rebase, force:integration

#10542 doc: fix alphabetical order in env.md
  docs/env.md
Labels: automerge:squash, bypass:integration

#10517 Fast USDC a3p deployment proposal
  a3p-integration/README.md
  a3p-integration/proposals/f:fast-usdc/.yarnrc.yml
  a3p-integration/proposals/f:fast-usdc/deploy.test.js
  a3p-integration/proposals/f:fast-usdc/package.json
  a3p-integration/proposals/f:fast-usdc/test.sh
  a3p-integration/proposals/f:fast-usdc/yarn.lock
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
Labels: automerge:rebase

#10344 `agd export` option for diagnosis
  golang/cosmos/app/app.go
  golang/cosmos/daemon/cmd/root.go
  golang/cosmos/x/swingset/genesis.go
  golang/cosmos/x/swingset/module.go
Labels: automerge:squash

#10532 feat(fast-usdc): write chain policies to vstorage
  a3p-integration/proposals/f:fast-usdc/package.json
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
Labels: automerge:squash

#10551 fix(telemetry): event name typo
  packages/telemetry/src/slog-to-otel.js
Labels: automerge:rebase

#10557 fix 'self' in prepareExo
  packages/fast-usdc/package.json
  packages/vat-data/src/exo-utils.js
  packages/zoe/src/zoeService/installationStorage.js
Labels: automerge:rebase, bypass:integration

#10556 coverage report untested files (and misc cleanup)
  COVERAGE.md
  package.json
  packages/access-token/package.json
  packages/agoric-cli/package.json
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/client-utils/package.json
  packages/cosmic-swingset/package.json
  packages/create-dapp/package.json
  packages/fast-usdc/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/vats/package.json
  packages/vm-config/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zone/package.json
  scripts/ava-nesm.cjs
  yarn.lock
Labels: automerge:rebase

#10560 report all files in CI test coverage
  .github/workflows/after-merge.yml
  COVERAGE.md
  package.json
  scripts/ci/generate-test-coverage-report.sh
Labels: automerge:rebase, bypass:integration

#10561 TypeScript 5.7 and fix coverage CI
  .github/workflows/after-merge.yml
  package.json
  packages/SwingSet/src/supervisors/subprocess-node/supervisor-subprocess-node.js
  packages/cosmic-proto/package.json
  packages/inter-protocol/src/provisionPoolKit.js
  packages/inter-protocol/src/reserve/params.js
  packages/inter-protocol/test/psm/setupPsm.js
  packages/internal/src/netstring.js
  packages/swingset-xsnap-supervisor/lib/supervisor-subprocess-xsnap.js
  packages/xsnap/src/avaXS.js
  packages/xsnap/src/globals.d.ts
  yarn.lock
Labels: automerge:rebase

#10553 fix(orchestration): subscribeToTransfers() atomically
  packages/orchestration/src/exos/packet-tools.js
Labels: automerge:rebase

#10530 feat(fast-usdc): settler disburses or forwards funds
  packages/fast-usdc/README.md
  packages/fast-usdc/src/constants.js
  packages/fast-usdc/src/exos/README.md
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
Labels: automerge:rebase, bypass:integration

#10569 test: reclaim stuck payment failing
  a3p-integration/proposals/z:acceptance/wallet.test.js
Labels: automerge:rebase

#10566 client utils vstorage without instance binding
  packages/client-utils/src/main.js
  packages/client-utils/src/vstorage-kit.js
  packages/client-utils/src/vstorage.js
  packages/client-utils/test/vstorage.test.js
Labels: automerge:rebase

#10329 feat: `CosmosChainInfo` includes `pfmEnabled: bool`
  a3p-integration/proposals/z:acceptance/wallet.test.js
  multichain-testing/test/send-anywhere.test.ts
  multichain-testing/test/support.ts
  multichain-testing/tools/deploy.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/builders/scripts/testing/init-send-anywhere.js
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/test/supports.ts
  packages/orchestration/index.js
  packages/orchestration/scripts/fetch-chain-info.ts
  packages/orchestration/src/chain-capabilities.js
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/exos/chain-hub-admin.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/proposals/start-send-anywhere.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/chain-hub-helper.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/snapshots/exports.test.ts.md
  packages/orchestration/test/snapshots/exports.test.ts.snap
Labels: automerge:rebase, force:integration

#10570 FU oracle operator CLI
  a3p-integration/package.json
  a3p-integration/proposals/f:fast-usdc/package.json
  a3p-integration/proposals/f:fast-usdc/test-cli.sh
  a3p-integration/proposals/f:fast-usdc/test.sh
  a3p-integration/proposals/f:fast-usdc/yarn.lock
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  a3p-integration/proposals/s:stake-bld/package.json
  a3p-integration/proposals/z:acceptance/package.json
  multichain-testing/package.json
  packages/agoric-cli/src/commands/auction.js
  packages/agoric-cli/src/commands/gov.js
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/reserve.js
  packages/agoric-cli/src/commands/test-upgrade.js
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/helpers.js
  packages/agoric-cli/src/lib/network-config.js
  packages/client-utils/src/cli.js
  packages/client-utils/src/main.js
  packages/client-utils/src/network-config.js
  packages/client-utils/src/rpc.js
  packages/client-utils/src/vstorage-kit.js
  packages/client-utils/src/vstorage.js
  packages/client-utils/src/wallet-utils.js
  packages/client-utils/test/snapshots/exports.test.js.md
  packages/client-utils/test/snapshots/exports.test.js.snap
  packages/fast-usdc/src/cli/bridge-action.js
  packages/fast-usdc/src/cli/cli.js
  packages/fast-usdc/src/cli/config-commands.js
  packages/fast-usdc/src/cli/config.js
  packages/fast-usdc/src/cli/operator-commands.js
  packages/fast-usdc/src/cli/transfer.js
  packages/fast-usdc/src/util/file.js
  packages/fast-usdc/test/cli/config.test.ts
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.md
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.snap
Labels: automerge:rebase, force:integration

#10552 feat(fast-usdc): write status updates to vstorage
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
Labels: automerge:squash

#10418 chore: upgrade v8, the priceAuthorityRegistry
  a3p-integration/proposals/n:upgrade-next/registry.test.js
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/vats/upgrade-paRegistry.js
  packages/vats/src/proposals/upgrade-paRegistry-proposal.js
Labels: automerge:squash, contract-upgrade, oracle, force:integration

#10572 test: fast-usdc contract flow
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/test/supports.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/utils/chain-hub-helper.js
Labels: automerge:rebase

#10587 feat(fast-usdc): publish feeConfig to vstorage
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/internal/src/storage-test-utils.js
Labels: automerge:rebase

#10584 feat: `chainHub.makeTransferRoute()`
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/asset.js
  packages/orchestration/src/utils/chain-hub-helper.js
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/snapshots/exports.test.ts.md
  packages/orchestration/test/snapshots/exports.test.ts.snap
Labels: automerge:rebase

#10516 feat: upgrade v7-board and test it
  a3p-integration/proposals/p:upgrade-19/.gitignore
  a3p-integration/proposals/p:upgrade-19/eval.sh
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/registry.test.js
  a3p-integration/proposals/p:upgrade-19/test.sh
  a3p-integration/proposals/p:upgrade-19/upgradedBoard.test.js
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/inter-protocol/replace-feeDistributor.js
  packages/builders/scripts/testing/replace-feeDistributor-short.js
  packages/builders/scripts/testing/test-upgraded-board.js
  packages/builders/scripts/vats/upgrade-board.js
  packages/vats/src/proposals/testUpgradedBoard.js
  packages/vats/src/proposals/upgrade-board-proposal.js
Labels: automerge:squash, contract-upgrade, force:integration
