Repository Agoric/agoric-sdk, pull requests merged in 2024-03, with the labels that each got.

#9013 Make Recovery sets optional
  packages/ERTP/src/issuerKit.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/src/types-ambient.js
  packages/inter-protocol/src/price/fluxAggregatorContract.js
  packages/zoe/src/contractSupport/priceAuthorityQuoteMint.js
Labels: ERTP, performance, automerge:rebase, resource-exhaustion, oracle

#8979 docs(network): networkVat core eval usage; scrub TODOs
  packages/network/src/network.js
  packages/vats/src/proposals/network-proposal.js
Labels: automerge:rebase

#9030 feat(vibc): preparation for Agoric ibc-hooks
  golang/cosmos/app/app.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/x/swingset/abci.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/keeper/proposal.go
  golang/cosmos/x/vibc/alias.go
  golang/cosmos/x/vibc/handler.go
  golang/cosmos/x/vibc/keeper/keeper.go
  golang/cosmos/x/vibc/keeper/triggers.go
  golang/cosmos/x/vibc/module.go
  golang/cosmos/x/vibc/types/expected_keepers.go
  golang/cosmos/x/vibc/types/ibc_module.go
  golang/cosmos/x/vibc/types/receiver.go
  packages/vats/src/ibc.js
Labels: automerge:no-update, IBC

#9028 ci(after-merge): handle uncommitted changes and report on failures
  .github/workflows/after-merge.yml
Labels: tooling, automerge:rebase, force:integration

#9050 misc RunUtils test improvements
  packages/boot/test/bootstrapTests/test-addAssets.ts
  packages/boot/test/bootstrapTests/test-vats-restart.ts
  packages/boot/test/bootstrapTests/test-walletSurvivesZoeRestart.ts
  packages/boot/test/bootstrapTests/test-zcf-upgrade.ts
  packages/boot/tools/supports.ts
Labels: automerge:rebase

#9051 fix: eliminate fee double-charge by using configurable decorator
  a3p-integration/proposals/a:upgrade-next/ante-fees.test.js
  golang/cosmos/ante/ante.go
  golang/cosmos/ante/fee.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  scripts/generate-a3p-submission-dir.sh
Labels: bug, automerge:rebase, agoric-cosmos, force:integration

#9041 feat(cosmos): Handle multiple upgrades of the same version
  golang/cosmos/app/app.go
  scripts/gen-upgrade-proposal.sh
Labels: force:integration

#9055 chore: Update comments referencing core eval handling
  golang/cosmos/proto/agoric/swingset/swingset.proto
  golang/cosmos/x/swingset/types/swingset.pb.go
  packages/cosmic-proto/proto/agoric/swingset/swingset.proto
  packages/cosmic-proto/src/codegen/agoric/swingset/swingset.ts
  packages/vats/src/core/README.md
Labels: automerge:rebase

#9056 Typescript 5.4
  package.json
  packages/agoric-cli/package.json
  packages/casting/package.json
  packages/cosmic-proto/package.json
  packages/pegasus/src/contract.js
  packages/pegasus/tsconfig.json
  packages/solo/src/start.js
  packages/swing-store/src/swingStore.js
  packages/vats/src/core/types-ambient.d.ts
  packages/wallet/api/src/lib-wallet.js
  packages/zoe/src/contractFacet/types-ambient.d.ts
  packages/zoe/test/privateArgsUsageContract.js
  packages/zoe/test/swingsetTests/brokenContracts/crashingAutoRefund.js
  patches/@endo+nat+5.0.4.patch
  yarn.lock
Labels: automerge:rebase

#9058 cleanup proposal output from extractor
  packages/boot/tools/supports.ts
Labels: automerge:rebase

#9062 chore: Cherry-pick DeductFeeDecorator changes for upgrade-14
  a3p-integration/proposals/a:upgrade-14/ante-fees.test.js
  golang/cosmos/ante/ante.go
  golang/cosmos/ante/fee.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: force:integration

#9073 chore(release): publish upgrade-14 RC1
  a3p-integration/proposals/a:upgrade-14/ante-fees.test.js
  golang/cosmos/CHANGELOG.md
  golang/cosmos/ante/ante.go
  golang/cosmos/ante/fee.go
  golang/cosmos/app/app.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/package.json
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/create-dapp/CHANGELOG.md
  packages/create-dapp/package.json
  packages/deploy-script-support/CHANGELOG.md
  packages/deploy-script-support/package.json
  packages/governance/CHANGELOG.md
  packages/governance/package.json
  packages/inter-protocol/CHANGELOG.md
  packages/inter-protocol/package.json
  packages/pegasus/CHANGELOG.md
  packages/pegasus/package.json
  packages/smart-wallet/CHANGELOG.md
  packages/smart-wallet/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
  packages/vats/CHANGELOG.md
  packages/vats/package.json
  packages/wallet-connection/CHANGELOG.md
  packages/wallet-connection/package.json
  packages/wallet/api/CHANGELOG.md
  packages/wallet/api/package.json
  packages/web-components/CHANGELOG.md
  packages/web-components/package.json
  scripts/gen-upgrade-proposal.sh
Labels: force:integration, bypass:automerge

#9076 end runtime imports of other packages for types
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/boot/package.json
  packages/builders/index.js
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/test/unitTests/test-coreProposalBehavior.js
  packages/import-manager/package.json
  packages/inter-protocol/test/smartWallet/test-oracle-integration.js
  packages/network/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/smart-wallet/src/invitations.js
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/vat-data/package.json
  packages/vats/index.js
  packages/vats/package.json
  packages/vats/src/core/utils.js
  packages/vow/package.json
  packages/zoe/package.json
Labels: automerge:rebase

#8829 feat(integration-test): use dapp-offer-up as target for getting-start…
  .github/workflows/integration.yml
  packages/agoric-cli/tools/getting-started.js
Labels: automerge:rebase, force:integration

#8638 drop tests for Node 16
  .github/workflow-templates/test-dapp.yml
  .github/workflows/after-merge.yml
  .github/workflows/test-dapp-card-store.yml
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml.DISABLED
  .github/workflows/test-documentation.yml
  docs/node-version.md
Labels: automerge:rebase, force:integration

#9057 chore(deps): bump c8 to latest
  package.json
  packages/access-token/package.json
  packages/agoric-cli/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/create-dapp/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/vats/package.json
  packages/vm-config/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  yarn.lock
Labels: automerge:rebase

#9031 docs: prune out-date node version in favor of LTS
  CONTRIBUTING.md
Labels: automerge:rebase

#8365 drop Node 16 (EOL)
  golang/cosmos/package.json
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/assert/package.json
  packages/base-zone/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/solo/package.json
  packages/sparse-ints/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swingset-liveslots/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vm-config/package.json
  packages/zoe/package.json
  packages/zone/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#9085 feat: support multiple submissions per proposal
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/b:localchain/README.md
  a3p-integration/proposals/b:localchain/package.json
  a3p-integration/scripts/generate-a3p-submission.sh
  a3p-integration/scripts/generate-a3p-submissions.sh
  scripts/generate-a3p-submission-dir.sh
  scripts/generate-a3p-submission-dirs.sh
  scripts/generate-a3p-submission.sh
Labels: automerge:rebase

#9061 test(ansible): Improve failure output
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
Labels: automerge:rebase

#9086 localchain queryMany and bankManager
  golang/cosmos/x/vlocalchain/vlocalchain.go
  golang/cosmos/x/vlocalchain/vlocalchain_test.go
  packages/vats/src/localchain.js
  packages/vats/src/proposals/localchain-proposal.js
  packages/vats/src/proposals/localchain-test.js
  packages/vats/src/vat-bank.js
  packages/vats/src/vat-localchain.js
Labels: automerge:rebase

#9088 misc type fixes
  package.json
  packages/ERTP/tsconfig.json
  packages/SwingSet/misc-tools/build-mezzanine-db.js
  packages/SwingSet/misc-tools/classify-promises.js
  packages/SwingSet/package.json
  packages/SwingSet/tsconfig.json
  packages/agoric-cli/tsconfig.json
  packages/benchmark/tsconfig.json
  packages/boot/tsconfig.json
  packages/builders/tsconfig.json
  packages/casting/tsconfig.json
  packages/cosmic-swingset/tsconfig.json
  packages/deploy-script-support/tsconfig.json
  packages/eslint-config/package.json
  packages/governance/tsconfig.json
  packages/inter-protocol/tsconfig.json
  packages/kmarshal/tsconfig.json
  packages/notifier/tsconfig.json
  packages/pegasus/tsconfig.json
  packages/smart-wallet/tsconfig.json
  packages/solo/tsconfig.json
  packages/store/tsconfig.json
  packages/swing-store/package.json
  packages/swing-store/src/exporter.js
  packages/swing-store/test/test-import.js
  packages/swing-store/test/test-snapstore.js
  packages/swing-store/tsconfig.json
  packages/swingset-liveslots/tsconfig.json
  packages/swingset-xsnap-supervisor/tsconfig.json
  packages/telemetry/tsconfig.json
  packages/vats/tsconfig.json
  packages/wallet/api/tsconfig.json
  packages/xsnap-lockdown/tsconfig.json
  packages/xsnap/tsconfig.json
  packages/zoe/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: automerge:rebase

#9092 types and tests for prepareOwnable
  packages/zoe/src/contractSupport/prepare-ownable.js
  packages/zoe/test/types.test-d.ts
  packages/zoe/test/unitTests/contracts/ownable-counter.js
  packages/zoe/test/unitTests/contracts/test-ownable-counter.js
Labels: automerge:rebase

#8780 feat(zoe): getInvitationDetails enforces singleton invitation
  packages/zoe/package.json
  packages/zoe/src/zoeService/invitationQueries.js
  packages/zoe/test/unitTests/contracts/test-invitation-details.js
  packages/zoe/test/unitTests/contracts/two-invitations.js
Labels: automerge:rebase

#9080 feat: Improve release steps
  MAINTAINERS.md
  scripts/get-released-tags
  scripts/npm-dist-tag.sh
Labels: automerge:rebase

#9094 fix Zoe Invitation types
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/deployment/package.json
  packages/inter-protocol/package.json
  packages/inter-protocol/src/reserve/assetReserveKit.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/internal/package.json
  packages/pegasus/package.json
  packages/stat-logger/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/vats/package.json
  packages/zoe/package.json
  packages/zoe/src/contractFacet/types-ambient.d.ts
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/prepare-ownable.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/contracts/auction/firstPriceLogic.js
  packages/zoe/src/contracts/auction/secondPriceLogic.js
  packages/zoe/src/contracts/loan/borrow.js
  packages/zoe/src/types.js
  packages/zoe/src/zoeService/types.js
  packages/zoe/test/types.test-d.ts
Labels: automerge:rebase

#9095 allow non-vat builders
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/b:localchain/package.json
  a3p-integration/scripts/generate-a3p-submission.sh
Labels: automerge:rebase

#9091 chore: clean up dead code for legacy REST methods
  golang/cosmos/x/swingset/module.go
  golang/cosmos/x/vbank/module.go
  golang/cosmos/x/vibc/module.go
  golang/cosmos/x/vstorage/module.go
Labels: hygiene, automerge:rebase, agoric-cosmos

#8964 Remove await when(...) in Network and IBC vats
  packages/boot/package.json
  packages/boot/test/bootstrapTests/ibcBridgeMock.js
  packages/boot/test/bootstrapTests/ibcClientMock.js
  packages/boot/test/bootstrapTests/ibcServerMock.js
  packages/boot/test/bootstrapTests/test-net-ibc-upgrade.ts
  packages/boot/test/bootstrapTests/test-vats-restart.ts
  packages/boot/tools/supports.ts
  packages/network/src/network.js
  packages/network/src/types.js
  packages/network/test/test-network-misc.js
  packages/pegasus/test/test-peg.js
  packages/vat-data/vow.js
  packages/vats/src/ibc.js
  packages/vats/src/proposals/network-proposal.js
  packages/vats/src/types.d.ts
  packages/vats/test/test-network.js
  packages/vow/src/tools.js
  packages/vow/src/types.js
  packages/vow/src/watch-utils.js
  packages/vow/src/watch.js
  packages/vow/test/test-watch-utils.js
Labels: automerge:squash

#9107 fix(scripts): Add go-getter subdirectory unwrapping to generated `agd tx submit-proposal`s
  scripts/gen-upgrade-proposal.sh
Labels: automerge:rebase

#9108 chore(agd): Handle multiple upgrades of the same version
  golang/cosmos/app/app.go
Labels: automerge:rebase

#9078 orchestration package with stakeBLD
  .github/workflows/test-all-packages.yml
  a3p-integration/proposals/c:stake-bld/.yarnrc.yml
  a3p-integration/proposals/c:stake-bld/README.md
  a3p-integration/proposals/c:stake-bld/package.json
  a3p-integration/proposals/c:stake-bld/stakeBld.test.js
  a3p-integration/proposals/c:stake-bld/test-lib/chain.js
  a3p-integration/proposals/c:stake-bld/test-lib/index.js
  a3p-integration/proposals/c:stake-bld/test-lib/rpc.js
  a3p-integration/proposals/c:stake-bld/test-lib/wallet.js
  a3p-integration/proposals/c:stake-bld/test.sh
  a3p-integration/proposals/c:stake-bld/yarn.lock
  packages/agoric-cli/src/sdk-package-names.js
  packages/boot/package.json
  packages/boot/test/bootstrapTests/test-orchestration.ts
  packages/boot/tools/supports.ts
  packages/builders/scripts/orchestration/init-stakeBld.js
  packages/orchestration/CHANGELOG.md
  packages/orchestration/README.md
  packages/orchestration/index.js
  packages/orchestration/package.json
  packages/orchestration/src/contracts/localchainAccountHolder.js
  packages/orchestration/src/contracts/stakeBld.contract.js
  packages/orchestration/src/proposals/start-stakeBld.js
  packages/orchestration/src/types.js
  packages/orchestration/test/stub.test.js
  packages/orchestration/tsconfig.build.json
  packages/orchestration/tsconfig.json
  packages/orchestration/typedoc.json
  packages/smart-wallet/src/offerWatcher.js
  packages/smart-wallet/src/smartWallet.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/core/utils.js
  packages/vats/src/localchain.js
Labels: automerge:rebase

#9102 feat(vow): fix issues revealed by new `Remote<T>` type
  packages/boot/test/bootstrapTests/ibcClientMock.js
  packages/boot/test/bootstrapTests/ibcServerMock.js
  packages/network/src/bytes.js
  packages/network/src/index.js
  packages/network/src/network.js
  packages/network/src/router.js
  packages/network/src/shapes.js
  packages/network/src/types.js
  packages/network/test/test-network-misc.js
  packages/pegasus/src/courier.js
  packages/pegasus/src/pegasus.js
  packages/vats/src/ibc.js
  packages/vats/src/proposals/network-proposal.js
  packages/vats/test/test-network.js
  packages/vow/src/E.js
  packages/vow/src/types.js
  packages/vow/src/when.js
Labels: automerge:rebase

#9113 feat(xsnap): Dispense with git when in node_modules
  packages/xsnap/package.json
  packages/xsnap/scripts/test-package.sh
  packages/xsnap/src/build.js
Labels: automerge:rebase, force:integration

#9044 a3p proposal to create new priceFeeds
  a3p-integration/proposals/a:upgrade-next/priceFeed.test.js
  golang/cosmos/app/app.go
  packages/builders/scripts/inter-protocol/price-feed-core.js
  packages/builders/scripts/vats/priceFeedSupport.js
  packages/builders/scripts/vats/updateAtomPriceFeed.js
  packages/builders/scripts/vats/updateStAtomPriceFeed.js
  packages/builders/scripts/vats/updateStOsmoPriceFeed.js
  packages/builders/scripts/vats/updateStTiaPriceFeed.js
  packages/inter-protocol/src/proposals/price-feed-proposal.js
Labels: performance, test, automerge:squash, contract-upgrade, oracle

#9122 fix(xsnap): Revert failed attempt to expedite xsnap builds
  packages/xsnap/package.json
  packages/xsnap/scripts/test-package.sh
  packages/xsnap/src/build.js
Labels: automerge:rebase

#9124 chore: Sync Endo 2024-03-21
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/xsnap/test/test-xs-perf.js
  packages/zoe/package.json
  packages/zone/package.json
  scripts/registry.sh
  yarn.lock
Labels: automerge:rebase, force:integration

#9116 chore(deps): bump telescope to latest (with our patch)
  packages/cosmic-proto/package.json
  packages/cosmic-proto/scripts/codegen.cjs
  packages/cosmic-proto/src/codegen/agoric/lien/genesis.ts
  packages/cosmic-proto/src/codegen/agoric/lien/lien.ts
  packages/cosmic-proto/src/codegen/agoric/swingset/genesis.ts
  packages/cosmic-proto/src/codegen/agoric/swingset/msgs.ts
  packages/cosmic-proto/src/codegen/agoric/swingset/query.ts
  packages/cosmic-proto/src/codegen/agoric/swingset/swingset.ts
  packages/cosmic-proto/src/codegen/agoric/vbank/vbank.ts
  packages/cosmic-proto/src/codegen/agoric/vibc/msgs.ts
  packages/cosmic-proto/src/codegen/agoric/vlocalchain/vlocalchain.ts
  packages/cosmic-proto/src/codegen/agoric/vstorage/genesis.ts
  packages/cosmic-proto/src/codegen/agoric/vstorage/query.ts
  packages/cosmic-proto/src/codegen/agoric/vstorage/vstorage.ts
  packages/cosmic-proto/src/codegen/binary.ts
  packages/cosmic-proto/src/codegen/cosmos/base/query/v1beta1/pagination.ts
  packages/cosmic-proto/src/codegen/cosmos/base/v1beta1/coin.ts
  packages/cosmic-proto/src/codegen/cosmos/upgrade/v1beta1/upgrade.ts
  packages/cosmic-proto/src/codegen/cosmos_proto/cosmos.ts
  packages/cosmic-proto/src/codegen/google/api/http.ts
  packages/cosmic-proto/src/codegen/google/protobuf/descriptor.ts
  packages/cosmic-proto/src/codegen/helpers.ts
  packages/cosmic-proto/src/codegen/ibc/core/channel/v1/channel.ts
  packages/cosmic-proto/src/codegen/ibc/core/client/v1/client.ts
  packages/cosmic-proto/src/codegen/index.ts
  packages/cosmic-proto/src/codegen/utf8.ts
  packages/cosmic-proto/src/codegen/varint.ts
  packages/cosmic-proto/test/snapshots/test-exports.js.md
  packages/cosmic-proto/test/snapshots/test-exports.js.snap
  packages/cosmic-proto/test/test-exports.js
  patches/@cosmology+telescope+1.4.12.patch
  yarn.lock
Labels: automerge:rebase

#9128 build(agd): more careful `stamp.sum` handling
  .github/actions/restore-node/action.yml
  bin/agd
Labels: automerge:rebase, force:integration

#9127 bump deps
  package.json
  packages/ERTP/package.json
  packages/cosmic-proto/package.json
  packages/internal/package.json
  packages/vat-data/package.json
  packages/zoe/package.json
  patches/@endo+nat+5.0.4.patch
  typings.d.ts
  yarn.lock
Labels: automerge:rebase

#9130 refactor: actually clearer stamps file name
  .github/actions/restore-node/action.yml
  bin/agd
Labels: automerge:rebase

#9129 bump GH runner versions
  .github/actions/get-latest-check/action.yml
  .github/actions/restore-golang/action.yml
  .github/actions/restore-node/action.yml
  .github/workflow-templates/test-dapp.yml
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/benchmarks.yml
  .github/workflows/docker.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
  .github/workflows/manage-integration-check.yml
  .github/workflows/mergify-ready.yml
  .github/workflows/proto.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-dapp-card-store.yml
  .github/workflows/test-dapp-otc.yml
  .github/workflows/test-dapp-pegasus.yml
  .github/workflows/test-dapp-simple-exchange.yml
  .github/workflows/test-dapp-treasury.yml.DISABLED
  .github/workflows/test-documentation.yml
  .github/workflows/test-golang.yml
  .github/workflows/test-scripts.yml
  .github/workflows/update-hackathon-branch.yml.DISABLED
Labels: automerge:rebase

#9120 feat(golang): bump PFM to v6.1.2
  golang/cosmos/app/app.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: automerge:squash

#9146 chore: typedoc markdown
  .github/workflows/test-all-packages.yml
  package.json
  packages/notifier/src/topic.js
  packages/zoe/src/zoeService/types.js
  yarn.lock
Labels: automerge:squash

#9149 TypeScript 5.5 with @import tag
  package.json
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/tools/run-utils.js
  packages/agoric-cli/src/helpers.js
  packages/agoric-cli/test/test-inter-cli.js
  packages/cache/src/types.js
  packages/casting/src/types.js
  packages/cosmic-proto/package.json
  packages/internal/src/callback.js
  packages/internal/src/lib-chainStorage.js
  packages/internal/src/utils.js
  packages/kmarshal/src/kmarshal.js
  packages/notifier/src/types-ambient.js
  packages/notifier/test/iterable-testing-tools.js
  patches/eslint-plugin-jsdoc+47.0.2.patch
  yarn.lock
Labels: automerge:rebase

#9154 feat(vow): VowShape, isVow
  packages/swingset-liveslots/src/watchedPromises.js
  packages/vow/src/index.js
  packages/vow/src/types.js
  packages/vow/src/vow-utils.js
Labels: automerge:squash

#8850 speed up sdk rebuild
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/priceFeed.test.js
  golang/cosmos/package.json
  packages/deployment/Dockerfile.sdk
  packages/deployment/Makefile
Labels: automerge:rebase, force:integration

#9159 chore: remove obsolete get-flattened-publication.sh script
  golang/cosmos/x/vstorage/keeper/grpc_query.go
  golang/cosmos/x/vstorage/keeper/keeper.go
  scripts/get-flattened-publication.sh
  scripts/test/test-get-flattened-publication/bin/curl
  scripts/test/test-get-flattened-publication/fixtures/capdata.json
  scripts/test/test-get-flattened-publication/fixtures/flattened-naked.json
  scripts/test/test-get-flattened-publication/fixtures/flattened-streamcell.json
  scripts/test/test-get-flattened-publication/test.sh
Labels: bug, hygiene, automerge:rebase, vstorage

#8779 feat(liveslots): virtual exo meta-ops
  packages/swingset-liveslots/src/vatDataTypes.d.ts
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/test/virtual-objects/test-cross-facet.js
  packages/vat-data/package.json
  packages/vat-data/test/test-amplify-virtual-class-kits.js
  packages/vat-data/test/test-is-instance-virtual-class-kits.js
Labels: automerge:squash

#9148 feat(repl): deal with Vows
  packages/vats/src/repl.js
  packages/vats/test/test-repl.js
Labels: solo, automerge:rebase

#9153 refactor: slightly better marshal identification for diagnostics
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/devices/lib/deviceTools.js
  packages/SwingSet/src/kernel/deviceSlots.js
  packages/swingset-liveslots/src/liveslots.js
  packages/swingset-liveslots/tools/fakeVirtualSupport.js
  packages/wallet/api/src/lib-dehydrate.js
Labels: automerge:squash

#9132 fix(swingset): force flaky GC test to use XS only
  packages/SwingSet/test/test-gc-kernel.js
Labels: SwingSet, automerge:rebase

#8977 feat(base-zone): alt revocable api using amplifier
  packages/base-zone/src/prepare-revocable.js
  packages/base-zone/test/test-prepare-revocable.js
  packages/zoe/src/contractSupport/prepare-ownable.js
Labels: automerge:squash

#9170 fix types compat with Endo master
  packages/base-zone/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/network/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/vat-data/package.json
  packages/vat-data/src/exo-utils.js
  packages/vats/package.json
  packages/vow/package.json
  packages/xsnap-lockdown/package.json
  packages/zoe/package.json
  packages/zoe/src/contractSupport/priceAuthorityInitial.js
  packages/zoe/src/contractSupport/priceAuthorityTransform.js
  packages/zone/src/durable.js
  scripts/check-dependency-cycles.sh
  scripts/ci-collect-testruns.sh
  scripts/configure-vscode.sh
  scripts/docker-tag.sh
  scripts/get-packed-versions.sh
  scripts/get-released-tags
  scripts/get-versions.sh
  scripts/npm-dist-tag.sh
  scripts/process-integration-results.sh
  scripts/registry.sh
  scripts/replace-packages.sh
  scripts/resolve-versions.sh
  scripts/run-deployment-integration.sh
  scripts/set-versions.sh
  scripts/smoketest-binaries.sh
  scripts/test/test.sh
  scripts/update-typeCoverage-floor.sh
Labels: automerge:rebase

#9147 fix(cosmos): share less state between Agoric Cosmos app instances
  golang/cosmos/app/app.go
  golang/cosmos/cmd/agd/main.go
  golang/cosmos/cmd/libdaemon/main.go
  golang/cosmos/daemon/cmd/root.go
  golang/cosmos/vm/client_test.go
  golang/cosmos/vm/controller.go
  golang/cosmos/vm/server.go
Labels: automerge:no-update, agd, agoric-cosmos
