Repository Agoric/agoric-sdk, pull requests merged in 2024-04, with the labels that each got.

#9177 test(boot): remove some unused imports
  packages/boot/test/bootstrapTests/test-zcf-upgrade.ts
Labels: automerge:squash

#9183 format .sh
  .prettierrc.json5
  golang/cosmos/scripts/protocgen.sh
  golang/cosmos/upgradegaia.sh
  package.json
  packages/ERTP/src/amountMath.js
  packages/ERTP/src/types-ambient.js
  packages/SwingSet/scripts/npm-audit-fix.sh
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/scripts/npm-audit-fix.sh
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/agoric-cli/test/agops-perf-smoketest.sh
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/agoric-cli/test/start-local-chain.sh
  packages/agoric-cli/test/upgrade-contract/contract-upgrade-smoketest.sh
  packages/cosmic-proto/src/codegen/binary.ts
  packages/cosmic-proto/src/codegen/helpers.ts
  packages/cosmic-proto/src/codegen/varint.ts
  packages/cosmic-swingset/perf.sh
  packages/cosmic-swingset/scripts/chain-entry.sh
  packages/cosmic-swingset/scripts/run-rosetta-ci.sh
  packages/cosmic-swingset/scripts/send_funds.sh
  packages/cosmic-swingset/scripts/single-node.sh
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
  packages/deployment/bigdipper/bigdipper.sh
  packages/deployment/docker/integration-test.sh
  packages/deployment/scripts/capture-integration-results.sh
  packages/deployment/scripts/install-deps.sh
  packages/deployment/scripts/integration-test.sh
  packages/deployment/scripts/start-github-integration-test.sh
  packages/deployment/scripts/test-docker-build.sh
  packages/governance/docs/gen.sh
  packages/telemetry/scripts/ingest.sh
  packages/telemetry/src/index.js
  packages/vat-data/vow.js
  packages/xsnap-lockdown/lib/object-inspect.js
  packages/zoe/src/zoeService/utils.d.ts
  scripts/check-dependency-cycles.sh
  scripts/check-mismatched-dependencies.cjs
  scripts/ci-collect-testruns.sh
  scripts/configure-vscode.sh
  scripts/create-agoric-cli.cjs
  scripts/docker-tag.sh
  scripts/gen-upgrade-proposal.sh
  scripts/get-packed-versions.sh
  scripts/get-versions.sh
  scripts/graph.sh
  scripts/lint-with-types.sh
  scripts/npm-dist-tag.sh
  scripts/process-integration-results.sh
  scripts/registry.sh
  scripts/replace-packages.sh
  scripts/resolve-versions.sh
  scripts/run-deployment-integration.sh
  scripts/set-versions.sh
  scripts/smoketest-binaries.sh
  scripts/test/test.sh
  scripts/update-typeCoverage-floor.sh
  yarn.lock
Labels: automerge:rebase

#9189 restore .d.ts emit for several packages
  docs/typescript.md
  packages/ERTP/exported.d.ts
  packages/ERTP/tsconfig.json
  packages/agoric-cli/src/commands/auction.js
  packages/agoric-cli/src/commands/gov.js
  packages/governance/exported.d.ts
  packages/governance/exported.js
  packages/governance/package.json
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/breakTie.js
  packages/governance/src/closingRule.js
  packages/governance/src/committee.js
  packages/governance/src/contractGovernance/governApi.js
  packages/governance/src/contractGovernance/governFilter.js
  packages/governance/src/contractGovernance/governParam.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/contractGovernance/typedParamManager.js
  packages/governance/src/contractGovernor.js
  packages/governance/src/contractGovernorKit.js
  packages/governance/src/contractHelper.js
  packages/governance/src/electorateTools.js
  packages/governance/src/index.js
  packages/governance/src/multiCandidateVoteCounter.js
  packages/governance/src/noActionElectorate.js
  packages/governance/src/question.js
  packages/governance/src/quorumCounter.js
  packages/governance/src/types.js
  packages/governance/src/validators.js
  packages/governance/src/voterKit.js
  packages/governance/test/swingsetTests/committeeBinary/bootstrap.js
  packages/governance/test/swingsetTests/committeeBinary/vat-voter.js
  packages/governance/test/swingsetTests/contractGovernor/bootstrap.js
  packages/governance/test/swingsetTests/contractGovernor/governedContract.js
  packages/governance/test/unitTests/test-committee.js
  packages/governance/test/unitTests/test-multiCandidateBallotCount.js
  packages/governance/test/unitTests/test-paramGovernance.js
  packages/governance/test/unitTests/test-puppetContractGovernor.js
  packages/governance/tools/puppetContractGovernor.js
  packages/governance/tools/puppetGovernance.js
  packages/governance/tsconfig.json
  packages/notifier/package.json
  packages/store/exported.d.ts
  packages/zoe/package.json
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/zoeService/zoe.js
Labels: automerge:rebase

#9186 fix(network): `Connection` should include negotiated remoteAddress and localAddress
  packages/network/src/network.js
  packages/vats/src/ibc.js
  packages/vats/test/test-network.js
Labels: automerge:rebase

#9114 feat: create chain account (ica)
  packages/boot/test/bootstrapTests/test-orchestration.ts
  packages/boot/test/bootstrapTests/test-vat-orchestration.ts
  packages/boot/tools/ibc/README.md
  packages/boot/tools/ibc/mocks.js
  packages/boot/tools/supports.ts
  packages/builders/scripts/orchestration/init-stakeAtom.js
  packages/builders/scripts/vats/init-orchestration.js
  packages/orchestration/index.js
  packages/orchestration/package.json
  packages/orchestration/src/contracts/stakeAtom.contract.js
  packages/orchestration/src/orchestration.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/types.d.ts
  packages/orchestration/src/types.js
  packages/orchestration/src/utils/address.js
  packages/orchestration/src/vat-orchestration.js
  packages/orchestration/test/utils/address.test.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/core/utils.js
Labels: automerge:rebase

#9160 feat(xsnap): Build sensitivity to presence of build toolchain
  packages/xsnap/package.json
  packages/xsnap/scripts/test-package.sh
  packages/xsnap/src/build.js
  packages/xsnap/src/xsnap.js
Labels: automerge:rebase

#9194 chore: Sync Endo versions 2024-04-04
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/xsnap/test/test-xs-perf.js
  packages/zoe/package.json
  packages/zone/package.json
  patches/@endo+exo+1.3.0.patch
  patches/@endo+exo+1.4.0.patch
  yarn.lock
Labels: automerge:rebase, force:integration

#9197 fix: update name of agd fee granter flag
  packages/solo/src/chain-cosmos-sdk.js
Labels: bug, solo, automerge:rebase

#9195 feat(orchestration): send message
  packages/boot/package.json
  packages/boot/test/bootstrapTests/test-orchestration.ts
  packages/boot/test/bootstrapTests/test-vat-orchestration.ts
  packages/boot/test/tools/ibc/test-mocks.js
  packages/boot/tools/ibc/mocks.js
  packages/boot/tools/supports.ts
  packages/cosmic-proto/package.json
  packages/orchestration/index.js
  packages/orchestration/package.json
  packages/orchestration/src/contracts/stakeAtom.contract.js
  packages/orchestration/src/contracts/stakingAccountHolder.js
  packages/orchestration/src/orchestration.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/types.d.ts
  packages/orchestration/src/utils/address.js
  packages/orchestration/src/utils/tx.js
  packages/orchestration/test/stub.test.js
  packages/orchestration/test/utils/tx.test.js
  packages/vats/src/ibc.js
  packages/vats/src/types.d.ts
  packages/vm-config/decentral-devnet-config.json
  packages/vow/src/types.js
Labels: automerge:rebase

#9179 build(agd): use timestamps again; hashes weren't necessary
  .github/actions/restore-node/action.yml
  bin/agd
  golang/cosmos/Makefile
  package.json
  packages/deployment/Dockerfile.sdk
  scripts/agd-builder.sh
Labels: tooling, automerge:no-update, agd, force:integration

#9191 IBC types and refactoring
  packages/ERTP/package.json
  packages/agoric-cli/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/casting/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/network/package.json
  packages/orchestration/package.json
  packages/store/package.json
  packages/swingset-liveslots/package.json
  packages/vats/package.json
  packages/vats/src/ibc.js
  packages/vats/src/types.d.ts
  packages/vats/test/test-ibc-utils.js
  packages/vats/tools/ibc-utils.js
  packages/vow/src/types.js
  packages/vow/src/watch.js
  packages/zone/package.json
Labels: automerge:rebase

#9093 Document process for creating proposals and submissions in a3p-integration.
  a3p-integration/README.md
  packages/deploy-script-support/README.md
Labels: documentation, automerge:squash

#9233 docs(eventual-send,pass-style): Add missing env var explanations
  docs/env.md
Labels: automerge:squash

#9243 more real imports
  packages/agoric-cli/src/commands/inter.js
  packages/agoric-cli/src/lib/format.js
  packages/agoric-cli/test/test-inter-cli.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/governance/src/types.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/test/auction/test-scheduler.js
  packages/internal/src/callback.js
  packages/internal/src/lib-chainStorage.js
  packages/internal/test/test-callback.js
  packages/network/src/types.js
  packages/smart-wallet/src/offerWatcher.js
  packages/smart-wallet/src/offers.js
  packages/swingset-liveslots/test/waitUntilQuiescent.js
  packages/vat-data/src/index.js
  packages/vats/src/virtual-purse.js
  packages/zoe/tools/internal-types.js
Labels: automerge:rebase

#9250 Upgrade ZCF only
  golang/cosmos/app/app.go
  packages/builders/scripts/vats/upgrade-zcf.js
  packages/vats/src/proposals/zcf-only-proposal.js
Labels: automerge:rebase

#9204 base upgrade-next on top of latest (use-upgrade-14)
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/README.md
  a3p-integration/proposals/a:upgrade-next/ante-fees.test.js
  a3p-integration/proposals/a:upgrade-next/initial.test.js
  a3p-integration/proposals/a:upgrade-next/invite-submission/README.md
  a3p-integration/proposals/a:upgrade-next/invite-submission/sendInvite-permit.json
  a3p-integration/proposals/a:upgrade-next/invite-submission/sendInvite.tjs
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/post.test.js
  a3p-integration/proposals/a:upgrade-next/probeZcfBundleCap.test.js
  a3p-integration/proposals/a:upgrade-next/provisioning.test.js
  a3p-integration/proposals/a:upgrade-next/test.sh
  a3p-integration/proposals/a:upgrade-next/wallet-repairs.test.js
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/proposals/b:localchain/package.json
  a3p-integration/proposals/b:localchain/yarn.lock
  a3p-integration/proposals/c:stake-bld/package.json
  a3p-integration/proposals/c:stake-bld/yarn.lock
  a3p-integration/yarn.lock
  golang/cosmos/app/app.go
  packages/deployment/Dockerfile.sdk
  packages/vats/src/proposals/probeZcfBundle.js
Labels: automerge:rebase, force:integration

#9251 fix: various fixes and features for u15
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: bug, enhancement, automerge:rebase, agoric-cosmos

#9242 chore(a3p-integration): Initialize dev-upgrade-15
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-14/ante-fees.test.js
  a3p-integration/proposals/a:upgrade-14/core-eval-test-submission/README.md
  a3p-integration/proposals/a:upgrade-14/core-eval-test-submission/send-script-permit.json
  a3p-integration/proposals/a:upgrade-14/core-eval-test-submission/send-script.tjs
  a3p-integration/proposals/a:upgrade-14/core-eval.test.js
  a3p-integration/proposals/a:upgrade-14/create-kread-item-test.sh
  a3p-integration/proposals/a:upgrade-14/generate-kread-item-request.mjs
  a3p-integration/proposals/a:upgrade-14/invite-submission/README.md
  a3p-integration/proposals/a:upgrade-14/invite-submission/sendInvite-permit.json
  a3p-integration/proposals/a:upgrade-14/invite-submission/sendInvite.tjs
  a3p-integration/proposals/a:upgrade-14/post.test.js
  a3p-integration/proposals/a:upgrade-14/wallet-repairs.test.js
  a3p-integration/proposals/a:upgrade-15/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-15/README.md
  a3p-integration/proposals/a:upgrade-15/initial.test.js
  a3p-integration/proposals/a:upgrade-15/package.json
  a3p-integration/proposals/a:upgrade-15/prepare.sh
  a3p-integration/proposals/a:upgrade-15/test.sh
  a3p-integration/proposals/a:upgrade-15/tsconfig.json
  a3p-integration/proposals/a:upgrade-15/use.sh
  a3p-integration/proposals/a:upgrade-15/yarn.lock
  a3p-integration/yarn.lock
  golang/cosmos/app/app.go
Labels: force:integration

#9236 fix(smart-wallet): handling payments in case of failure to create invitation
  packages/smart-wallet/package.json
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/test/test-invitation1.js
Labels: automerge:rebase, force:integration

#9237 ci(restore-node): preserve `package.json` timestamp
  .github/actions/restore-node/action.yml
Labels: tooling, automerge:no-update

#9238 feat(smart-wallet): tryExitOffer also tries to reclaim
  a3p-integration/proposals/a:upgrade-next/exit-reclaim.test.js
  a3p-integration/proposals/a:upgrade-next/exitOffer.js
  a3p-integration/proposals/a:upgrade-next/initial.test.js
  a3p-integration/proposals/a:upgrade-next/prepare.sh
  a3p-integration/proposals/a:upgrade-next/synthetic-chain-excerpt.js
  golang/cosmos/app/app.go
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:rebase

#9263 test: pick up cosmos-sdk with more abci flag tests
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: enhancement, automerge:rebase, agoric-cosmos

#9264 chore: Cherry-pick go.mod changes into dev-upgrade-15
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: force:integration

#9266 chore: Cherry-pick smart-wallet changes into dev-upgrade-15
  a3p-integration/proposals/a:upgrade-15/exit-reclaim.test.js
  a3p-integration/proposals/a:upgrade-15/exitOffer.js
  a3p-integration/proposals/a:upgrade-15/initial.test.js
  a3p-integration/proposals/a:upgrade-15/prepare.sh
  a3p-integration/proposals/a:upgrade-15/synthetic-chain-excerpt.js
  golang/cosmos/app/app.go
  packages/smart-wallet/package.json
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/test/test-invitation1.js
Labels: force:integration

#9257 stub for acceptance suite
  a3p-integration/proposals/z:acceptance/.gitignore
  a3p-integration/proposals/z:acceptance/.yarnrc.yml
  a3p-integration/proposals/z:acceptance/README.md
  a3p-integration/proposals/z:acceptance/core-eval-test-submission/README.md
  a3p-integration/proposals/z:acceptance/core-eval-test-submission/send-script-permit.json
  a3p-integration/proposals/z:acceptance/core-eval-test-submission/send-script.tjs
  a3p-integration/proposals/z:acceptance/core-eval.test.js
  a3p-integration/proposals/z:acceptance/eval.sh
  a3p-integration/proposals/z:acceptance/initial.test.js
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/tsconfig.json
  a3p-integration/proposals/z:acceptance/yarn.lock
Labels: automerge:rebase, force:integration

#9024 fix(agoric-cli): handle another vstorage error variation
  packages/agoric-cli/src/lib/rpc.js
Labels: automerge:rebase

#9275 refactor(internal): deprecate makeAggregateError in favor of Aggregat…
  packages/agoric-cli/src/install.js
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/internal/src/node/fs-stream.js
  packages/internal/src/utils.js
  packages/telemetry/src/slog-sender-pipe-entrypoint.js
Labels: automerge:squash

#9219 improve proto3 JSON types and utils
  packages/boot/package.json
  packages/boot/test/bootstrapTests/test-vat-orchestration.ts
  packages/cosmic-proto/package.json
  packages/cosmic-proto/src/helpers.ts
  packages/orchestration/package.json
  packages/orchestration/src/contracts/stakingAccountHolder.js
  packages/orchestration/src/orchestration.js
  packages/orchestration/src/utils/tx.js
  packages/orchestration/test/utils/tx.test.js
  packages/vats/package.json
  packages/zoe/src/contractFacet/types-ambient.d.ts
  yarn.lock
Labels: automerge:rebase

#9262 compat for NPM lifecycle scripts
  packages/cosmic-proto/package.json
  packages/xsnap/package.json
Labels: automerge:rebase

#9208 9207 orchestrator stub
  .eslintignore
  package.json
  packages/boot/test/bootstrapTests/test-vat-orchestration.ts
  packages/cosmic-proto/.eslintignore
  packages/cosmic-proto/package.json
  packages/orchestration/index.js
  packages/orchestration/package.json
  packages/orchestration/src/contracts/stakeAtom.contract.js
  packages/orchestration/src/contracts/stakingAccountHolder.js
  packages/orchestration/src/contracts/swapExample.contract.js
  packages/orchestration/src/contracts/unbondExample.contract.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/proposals/orchestration-proposal.js
  packages/orchestration/src/service.js
  packages/orchestration/src/types.d.ts
  packages/orchestration/src/utils/address.js
  packages/orchestration/src/utils/orc.js
  packages/orchestration/src/vat-orchestration.js
  packages/orchestration/test/types.test-d.ts
  packages/vats/src/core/types-ambient.d.ts
  yarn.lock
Labels: automerge:rebase

#9290 compat with Endo on Yarn 4
  scripts/agd-builder.sh
  scripts/get-packed-versions.sh
  scripts/get-versions.sh
  scripts/replace-packages.sh
  scripts/set-versions.sh
Labels: automerge:rebase, force:integration

#9293 ci: bump codecov-action to v4
  .github/actions/post-test/action.yml
Labels: automerge:rebase

#9295 chore: Update README prerequisites
  README.md
  docs/node-version.md
  golang/cosmos/x/vstorage/keeper/keeper.go
Labels: automerge:rebase

#9158 Start a new auction in a3p-integration
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/priceFeed-follower-auction.test.js
  a3p-integration/proposals/a:upgrade-next/vatDetails.js
  a3p-integration/yarn.lock
  golang/cosmos/app/app.go
  packages/builders/scripts/vats/add-auction.js
  packages/inter-protocol/src/proposals/add-auction.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
Labels: performance, automerge:rebase, contract-upgrade, auction

#9292 bump TypeScript to 5.5 beta
  package.json
  packages/cosmic-proto/package.json
  yarn.lock
Labels: automerge:rebase

#9291 build orc docs
  packages/boot/test/bootstrapTests/test-orchestration.ts
  packages/builders/scripts/orchestration/init-stakeAtom.js
  packages/builders/scripts/orchestration/init-stakeBld.js
  packages/orchestration/README.md
  packages/orchestration/src/examples/stakeAtom.contract.js
  packages/orchestration/src/examples/stakeBld.contract.js
  packages/orchestration/src/examples/swapExample.contract.js
  packages/orchestration/src/examples/unbondExample.contract.js
  packages/orchestration/src/exos/localchainAccountKit.js
  packages/orchestration/src/exos/stakingAccountKit.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeBld.js
  packages/orchestration/typedoc.json
Labels: automerge:rebase

#9230 fix(base-zone,zone): import `isPassable` from @endo/pass-style
  packages/base-zone/src/heap.js
  packages/base-zone/src/is-passable.js
  packages/zone/src/durable.js
  packages/zone/src/virtual.js
Labels: automerge:squash
