Repository Agoric/agoric-sdk, pull requests merged in 2024-02, with the labels that each got.

#8816 chore(zoe): Fix a typo in recorder.js
  packages/zoe/src/contractSupport/recorder.js
Labels: automerge:rebase

#8842 Cherry-pick sequential core proposals and create-dapp
  .github/workflows/after-merge.yml
  .github/workflows/ag-solo-xs.yml.DISABLED
  .github/workflows/docker.yml
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
  .github/workflows/pre-check-integration.yml
  .github/workflows/test-all-packages.yml
  a3p-integration/.gitignore
  a3p-integration/.yarnrc.yml
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-14/package.json
  a3p-integration/proposals/a:upgrade-14/yarn.lock
  a3p-integration/yarn.lock
  golang/cosmos/app/app.go
  golang/cosmos/vm/action.go
  golang/cosmos/vm/action_test.go
  golang/cosmos/vm/controller.go
  golang/cosmos/vm/core_proposals.go
  golang/cosmos/x/lien/keeper/keeper_test.go
  golang/cosmos/x/swingset/abci.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/keeper/proposal.go
  golang/cosmos/x/vbank/vbank.go
  golang/cosmos/x/vbank/vbank_test.go
  golang/cosmos/x/vibc/handler.go
  golang/cosmos/x/vibc/ibc.go
  packages/agoric-cli/package.json
  packages/agoric-cli/src/main.js
  packages/agoric-cli/src/sdk-package-names.js
  packages/agoric-cli/tools/getting-started.js
  packages/cosmic-swingset/economy-template.json
  packages/cosmic-swingset/src/launch-chain.js
  packages/create-dapp/.gitignore
  packages/create-dapp/.npmignore
  packages/create-dapp/CHANGELOG.md
  packages/create-dapp/README.md
  packages/create-dapp/jsconfig.json
  packages/create-dapp/package.json
  packages/create-dapp/src/create-dapp.js
  packages/create-dapp/test/test-sanity.js
  packages/deploy-script-support/src/extract-proposal.js
  packages/internal/src/action-types.js
  packages/vats/decentral-devnet-config.json
  packages/vats/package.json
  packages/vats/src/core/boot-chain.js
  packages/vats/src/core/boot-sim.js
  packages/vats/src/core/boot-solo.js
  packages/vats/src/core/lib-boot.js
  packages/vats/test/bootstrapTests/supports.js
  packages/xsnap/package.json
Labels: force:integration

#8777 chore(cosmic-swingset): Propagate errors from `main` in clean-core-eval.js
  packages/cosmic-swingset/scripts/clean-core-eval.js
Labels: automerge:rebase

#8855 docs(golang): Improve the description of PopulateAction
  golang/cosmos/vm/action.go
  golang/cosmos/vm/action_test.go
Labels: documentation, code-style, automerge:rebase, agoric-cosmos, go

#8745 feat(zoe): caretaker-style revocable, ownable
  packages/zoe/package.json
  packages/zoe/src/contractFacet/types-ambient.d.ts
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/prepare-ownable.js
  packages/zoe/src/contractSupport/prepare-revocable.js
  packages/zoe/test/unitTests/contractSupport/test-prepare-revocable.js
  packages/zoe/test/unitTests/contracts/ownable-counter.js
  packages/zoe/test/unitTests/contracts/test-ownable-counter.js
Labels: automerge:squash

#8136 fix: DEBUG harmony
  docs/env.md
  packages/agoric-cli/package.json
  packages/agoric-cli/src/anylogger-agoric.js
  packages/agoric-cli/src/cosmos.js
  packages/agoric-cli/src/start.js
  packages/agoric-cli/tools/getting-started.js
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/anylogger-agoric.js
  packages/smart-wallet/test/test-addAsset.js
  packages/solo/src/start.js
  packages/swingset-liveslots/package.json
  packages/swingset-liveslots/src/virtualObjectManager.js
  yarn.lock
Labels: automerge:squash, force:integration

#8791 feat: upgrade interchain stack to ibc5
  golang/cosmos/Makefile
  golang/cosmos/ante/ante.go
  golang/cosmos/app/app.go
  golang/cosmos/daemon/cmd/genaccounts.go
  golang/cosmos/daemon/cmd/root.go
  golang/cosmos/daemon/cmd/root_test.go
  golang/cosmos/daemon/cmd/testnet.go
  golang/cosmos/daemon/main.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/scripts/protocgen.sh
  golang/cosmos/third_party/proto/buf.yaml
  golang/cosmos/third_party/proto/cosmos/base/query/v1beta1/pagination.proto
  golang/cosmos/third_party/proto/cosmos/base/v1beta1/coin.proto
  golang/cosmos/third_party/proto/cosmos/upgrade/v1beta1/upgrade.proto
  golang/cosmos/third_party/proto/cosmos_proto/cosmos.proto
  golang/cosmos/third_party/proto/google/api/annotations.proto
  golang/cosmos/third_party/proto/google/api/http.proto
  golang/cosmos/third_party/proto/google/api/httpbody.proto
  golang/cosmos/third_party/proto/google/protobuf/any.proto
  golang/cosmos/third_party/proto/ibc/core/channel/v1/channel.proto
  golang/cosmos/third_party/proto/ibc/core/client/v1/client.proto
  golang/cosmos/upgradegaia.sh
  golang/cosmos/x/lien/keeper/account.go
  golang/cosmos/x/lien/keeper/keeper.go
  golang/cosmos/x/lien/keeper/keeper_test.go
  golang/cosmos/x/lien/lien_test.go
  golang/cosmos/x/swingset/client/cli/tx.go
  golang/cosmos/x/swingset/client/proposal_handler.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/keeper_test.go
  golang/cosmos/x/swingset/proposal_handler.go
  golang/cosmos/x/swingset/types/codec.go
  golang/cosmos/x/swingset/types/proposal.go
  golang/cosmos/x/vbank/keeper/keeper.go
  golang/cosmos/x/vbank/keeper/rewards.go
  golang/cosmos/x/vbank/vbank_test.go
  golang/cosmos/x/vibc/ibc.go
  golang/cosmos/x/vibc/keeper/keeper.go
  golang/cosmos/x/vibc/types/expected_keepers.go
  golang/cosmos/x/vibc/types/msgs.go
  golang/cosmos/x/vibc/types/msgs.pb.go
  golang/cosmos/x/vstorage/keeper/keeper.go
  golang/cosmos/x/vstorage/keeper/keeper_test.go
  golang/cosmos/x/vstorage/vstorage_test.go
Labels: enhancement, automerge:rebase, agoric-cosmos, force:integration, proto:expect-breakage

#8865 feat: upgrade interchain stack to ibc6
  golang/cosmos/Makefile
  golang/cosmos/ante/ante.go
  golang/cosmos/app/app.go
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/third_party/proto/ibc/core/channel/v1/channel.proto
  golang/cosmos/third_party/proto/ibc/core/client/v1/client.proto
  golang/cosmos/x/vibc/ibc.go
  golang/cosmos/x/vibc/keeper/keeper.go
  golang/cosmos/x/vibc/types/expected_keepers.go
  golang/cosmos/x/vibc/types/msgs.go
  golang/cosmos/x/vibc/types/msgs.pb.go
Labels: enhancement, automerge:rebase, agoric-cosmos, proto:expect-breakage

#8715 build(agd): rely on checksums, not timestamps
  .github/actions/restore-node/action.yml
  bin/agd
  golang/cosmos/index.cjs
  golang/cosmos/package.json
  packages/deployment/Dockerfile.sdk
  packages/deployment/ansible/config.yml
  packages/deployment/ansible/copy.yml
  packages/deployment/ansible/prepare-cosmos.yml
  packages/deployment/ansible/roles/copy/tasks/main.yml
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
  packages/deployment/scripts/integration-test.sh
  scripts/registry.sh
  scripts/smoketest-binaries.sh
Labels: automerge:no-update, force:integration

#8866 Tolerate `golangci-lint` deprecation errors
  .github/workflows/golangci-lint.yml
  bin/agd
  golang/cosmos/app/export.go
  packages/deployment/Dockerfile.sdk
Labels: automerge:no-update

#8802 8453 release2 zoe
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/test/swingsetTests/zoe/test-zoe-upgrade.js
  packages/zoe/test/unitTests/zcf/test-zcf.js
Labels: Zoe, force:integration

#8793 7918 upgrade15 update zoe zcf
  packages/vats/src/vat-zoe.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
Labels: Zoe, Zoe Contract, contract-upgrade, force:integration

#8872 Upgrade wallet-factory and zoe in handler
  a3p-integration/proposals/a:upgrade-next/post.test.js
  a3p-integration/proposals/a:upgrade-next/sanity.test.js
  golang/cosmos/app/app.go
  patches/@endo+patterns+1.1.0.patch
Labels: automerge:rebase, force:integration

#8807 fix: When setting a new zcfBundleCap, store it in baggage
  packages/zoe/src/zoeService/zoe.js
Labels: Zoe, force:integration

#8846 feat: replace zoe and zcf
  a3p-integration/proposals/a:upgrade-14/post.test.js
  a3p-integration/proposals/a:upgrade-14/sanity.test.js
  golang/cosmos/app/app.go
  packages/vats/scripts/replace-zoe.js
  packages/vats/src/proposals/zcf-proposal.js
Labels: force:integration

#8873 bump a3p
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/yarn.lock
Labels: automerge:rebase

#8836 bump types deps
  package.json
  packages/ERTP/package.json
  packages/ERTP/test/unitTests/test-issuerObj.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/test/basedir-circular/vat-bob.js
  packages/eslint-config/package.json
  packages/internal/package.json
  packages/swingset-liveslots/test/test-vpid-liveslots.js
  packages/swingset-runner/demo/promiseChainBenchmark/vat-bob.js
  packages/swingset-runner/demo/resolveChain/vat-bob.js
  packages/swingset-runner/demo/resolveCircular/vat-bob.js
  packages/swingset-runner/demo/resolveCircular2/vat-bob.js
  packages/swingset-runner/demo/resolveCircular3/vat-bob.js
  packages/swingset-runner/demo/resolveCircularMultiCrank/vat-bob.js
  packages/swingset-runner/demo/resolveCrosswise/vat-body.js
  packages/swingset-runner/demo/resolveIndirect/vat-bob.js
  packages/swingset-runner/demo/resolveSimpleCircular/vat-bob.js
  packages/swingset-runner/demo/resolveSimpleCircular2/vat-bob.js
  packages/swingset-runner/demo/resolveWithEmbeddedPromise/vat-bob.js
  packages/vat-data/package.json
  packages/zoe/package.json
  yarn.lock
Labels: automerge:rebase

#8856 refactor(zoe): Replace arrayToObj with objectMap
  packages/zoe/src/cleanProposal.js
  packages/zoe/src/issuerStorage.js
  packages/zoe/src/objArrayConversion.js
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/test/unitTests/test-objArrayConversion.js
Labels: enhancement, Zoe, code-style, automerge:rebase

#8892 ci: merge integration branch before endo checkout
  .github/actions/restore-node/action.yml
Labels: automerge:squash

#8861 feat(ertp): purse amountStore abstraction
  packages/ERTP/src/amountStore.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
Labels: automerge:squash

#8899 integration cleanup
  .github/ISSUE_TEMPLATE/manual_dapp_testing.md
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
Labels: automerge:rebase

#8898 fix(agoric-cli): Remove conflicting AggregateError declaration comment
  packages/agoric-cli/src/install.js
Labels: automerge:squash

#8902 Handle cosmos 0.46 gov breaking changes
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/post.test.js
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/yarn.lock
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/proposal.go
  packages/agoric-cli/test/upgrade-contract/contract-upgrade-smoketest.sh
  packages/cosmic-swingset/Makefile
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
  packages/inter-protocol/Makefile
Labels: automerge:rebase

#8905 Revert "test(a3p): restart-vats"
  a3p-integration/proposals/b:restart-vats/.yarnrc.yml
  a3p-integration/proposals/b:restart-vats/README.md
  a3p-integration/proposals/b:restart-vats/package.json
  a3p-integration/proposals/b:restart-vats/submission/b1-23367331a30b300c84bc01bccaab0c30ad71bef57308dbc7f3ff7f1f05725d01ba9b3de4a06f937b1834622cb4b45485d2610a3e6cc7f6e5bbf7b57311f91dc1.json
  a3p-integration/proposals/b:restart-vats/submission/restart-vats-permit.json
  a3p-integration/proposals/b:restart-vats/submission/restart-vats-plan.json
  a3p-integration/proposals/b:restart-vats/submission/restart-vats.js
  a3p-integration/proposals/b:restart-vats/test.sh
  a3p-integration/proposals/b:restart-vats/yarn.lock
Labels: automerge:squash

#8907 Re-add a CoreEval proposal to a3p-integration
  .github/workflows/integration.yml
  a3p-integration/package.json
  a3p-integration/proposals/b:restart-vats/.gitignore
  a3p-integration/proposals/b:restart-vats/.yarnrc.yml
  a3p-integration/proposals/b:restart-vats/README.md
  a3p-integration/proposals/b:restart-vats/package.json
  a3p-integration/proposals/b:restart-vats/test.sh
  a3p-integration/proposals/b:restart-vats/yarn.lock
  scripts/generate-a3p-submission.sh
Labels: automerge:rebase, force:integration

#8910 chore: more reliable collected check in gc test
  packages/swingset-liveslots/test/gc-and-finalize.js
  packages/swingset-liveslots/test/test-liveslots-real-gc.js
  packages/swingset-liveslots/test/virtual-objects/test-retain-remotable.js
  packages/swingset-liveslots/test/virtual-objects/test-vo-real-gc.js
Labels: automerge:squash

#8913 chore: tweak holding pattern in liveslots gc test
  packages/swingset-liveslots/test/test-liveslots-real-gc.js
Labels: automerge:squash

#8889 slogSender using positions in file instead of mmap
  .eslintrc.cjs
  packages/telemetry/package.json
  packages/telemetry/src/flight-recorder.js
  packages/telemetry/src/frcat-entrypoint.js
  packages/telemetry/src/index.js
  packages/telemetry/src/ingest-slog-entrypoint.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/src/otel-and-flight-recorder.js
  packages/telemetry/src/slog-to-otel.js
  packages/telemetry/test/test-flight-recorder.js
  patches/bufferfromfile+0.4.377.patch
  yarn.lock
Labels: automerge:rebase, force:integration

#8920 allow Node 20
  .github/workflows/test-all-packages.yml
  .node-version
  package.json
  packages/smart-wallet/test/test-addAsset.js
  packages/smart-wallet/test/test-walletFactory.js
  packages/swing-store/src/snapStoreIO.js
Labels: automerge:rebase

#8886 Clarify a3p-integration
  .dockerignore
  .github/actions/restore-node/action.yml
  .github/workflows/integration.yml
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/README.md
  a3p-integration/proposals/a:upgrade-next/prepare.sh
  a3p-integration/proposals/a:upgrade-next/test.sh
  a3p-integration/proposals/a:upgrade-next/use.sh
Labels: automerge:rebase, force:integration

#8737 chore(vats): Cleanup runModuleBehaviors
  packages/vats/src/core/utils.js
Labels: code-style, automerge:squash, javascript

#8929 feat(a3p-integration): add core eval in test
  a3p-integration/proposals/a:upgrade-next/core-eval-test-submission/README.md
  a3p-integration/proposals/a:upgrade-next/core-eval-test-submission/send-script-permit.json
  a3p-integration/proposals/a:upgrade-next/core-eval-test-submission/send-script.tjs
  a3p-integration/proposals/a:upgrade-next/core-eval.test.js
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/tsconfig.json
  a3p-integration/proposals/a:upgrade-next/yarn.lock
Labels: automerge:squash

#8940 fix(a3p): serial test execution
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/proposals/b:restart-vats/package.json
  a3p-integration/proposals/b:restart-vats/yarn.lock
Labels: automerge:squash

#8901 feat(cosmos): upgrade provisioning vat
  a3p-integration/proposals/a:upgrade-next/provisioning-test-submission/send-script-permit.json
  a3p-integration/proposals/a:upgrade-next/provisioning-test-submission/send-script.tjs
  a3p-integration/proposals/a:upgrade-next/provisioning.test.js
  golang/cosmos/app/app.go
Labels: automerge:squash

#8909 test: verify purse balances are updated after smartWallet upgrade
  a3p-integration/proposals/a:upgrade-next/invite-submission/README.md
  a3p-integration/proposals/a:upgrade-next/invite-submission/sendInvite-permit.json
  a3p-integration/proposals/a:upgrade-next/invite-submission/sendInvite.tjs
  a3p-integration/proposals/a:upgrade-next/wallet-repairs.test.js
Labels: wallet, automerge:squash, contract-upgrade, force:integration

#8941 chore(swingset-liveslots): handle GC test flake
  packages/swingset-liveslots/test/test-liveslots-real-gc.js
Labels: automerge:squash

#8943 fix(SwingSet): silence vat console output during replay
  packages/SwingSet/src/kernel/slogger.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:no-update, force:integration

#8944 refactor(a3p): reusable submission generation function
  scripts/generate-a3p-submission.sh
Labels: automerge:squash

#8942 Cherry-pick a3p and agd changes for upgrade-14
  .dockerignore
  .github/ISSUE_TEMPLATE/manual_dapp_testing.md
  .github/actions/restore-node/action.yml
  .github/workflows/integration.yml
  .github/workflows/test-dapp-fungible-faucet.yml.DISABLED
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-14/core-eval-test-submission/README.md
  a3p-integration/proposals/a:upgrade-14/core-eval-test-submission/send-script-permit.json
  a3p-integration/proposals/a:upgrade-14/core-eval-test-submission/send-script.tjs
  a3p-integration/proposals/a:upgrade-14/core-eval.test.js
  a3p-integration/proposals/a:upgrade-14/package.json
  a3p-integration/proposals/a:upgrade-14/post.test.js
  a3p-integration/proposals/a:upgrade-14/prepare.sh
  a3p-integration/proposals/a:upgrade-14/test.sh
  a3p-integration/proposals/a:upgrade-14/tsconfig.json
  a3p-integration/proposals/a:upgrade-14/use.sh
  a3p-integration/proposals/a:upgrade-14/yarn.lock
  a3p-integration/yarn.lock
  bin/agd
  golang/cosmos/index.cjs
  golang/cosmos/package.json
  packages/SwingSet/src/kernel/slogger.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/deployment/Dockerfile.sdk
  packages/deployment/ansible/config.yml
  packages/deployment/ansible/copy.yml
  packages/deployment/ansible/prepare-cosmos.yml
  packages/deployment/ansible/roles/copy/tasks/main.yml
  packages/deployment/ansible/roles/cosmos-genesis/files/faucet-helper.sh
  packages/deployment/scripts/integration-test.sh
  repoconfig.sh
  scripts/generate-a3p-submission.sh
  scripts/registry.sh
  scripts/smoketest-binaries.sh
Labels: force:integration

#8787 test: verify purse balances are updated after smartWallet upgrade
  a3p-integration/proposals/a:upgrade-14/invite-submission/README.md
  a3p-integration/proposals/a:upgrade-14/invite-submission/sendInvite-permit.json
  a3p-integration/proposals/a:upgrade-14/invite-submission/sendInvite.tjs
  a3p-integration/proposals/a:upgrade-14/wallet-repairs.test.js
Labels: wallet, contract-upgrade, force:integration

#8853 feat: repair KREAd contract on zoe upgrade
  a3p-integration/proposals/a:upgrade-14/create-kread-item-test.sh
  a3p-integration/proposals/a:upgrade-14/generate-kread-item-request.mjs
  a3p-integration/proposals/a:upgrade-14/test.sh
  golang/cosmos/app/app.go
  packages/vats/scripts/revive-kread.js
  packages/vats/src/proposals/kread-proposal.js
Labels: Zoe Contract, force:integration

#8949 Fix cosmic-proto generate and rebuild
  packages/cosmic-proto/MAINTAINERS.md
  packages/cosmic-proto/dist/agoric/swingset/swingset.d.ts
  packages/cosmic-proto/dist/agoric/swingset/swingset.js
  packages/cosmic-proto/dist/agoric/vstorage/query.d.ts
  packages/cosmic-proto/dist/agoric/vstorage/query.js
  packages/cosmic-proto/dist/cosmos/base/query/v1beta1/pagination.d.ts
  packages/cosmic-proto/proto/cosmos_proto
Labels: automerge:rebase

#8953 chore(deps): bump @agoric/synthetic-chain
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/a:upgrade-next/yarn.lock
  a3p-integration/proposals/b:restart-vats/package.json
  a3p-integration/proposals/b:restart-vats/yarn.lock
  a3p-integration/yarn.lock
Labels: automerge:rebase

#8956 Update cosmic-proto
  .gitignore
  packages/cosmic-proto/.gitignore
  packages/cosmic-proto/MAINTAINERS.md
  packages/cosmic-proto/dist/agoric/swingset/msgs.d.ts
  packages/cosmic-proto/dist/agoric/swingset/msgs.js
  packages/cosmic-proto/dist/agoric/swingset/swingset.d.ts
  packages/cosmic-proto/dist/agoric/swingset/swingset.js
  packages/cosmic-proto/dist/agoric/vstorage/query.d.ts
  packages/cosmic-proto/dist/agoric/vstorage/query.js
  packages/cosmic-proto/dist/cosmos/base/query/v1beta1/pagination.d.ts
  packages/cosmic-proto/dist/cosmos/base/query/v1beta1/pagination.js
  packages/cosmic-proto/dist/cosmos_proto/cosmos.d.ts
  packages/cosmic-proto/dist/cosmos_proto/cosmos.js
  packages/cosmic-proto/package.json
  packages/cosmic-proto/proto/cosmos_proto
  packages/cosmic-proto/test/sanity-test.js
Labels: force:integration

#8957 chore(deps): bump @agoric/synthetic-chain
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-14/package.json
  a3p-integration/proposals/a:upgrade-14/yarn.lock
  a3p-integration/yarn.lock
Labels: force:integration

#8966 more robust repairWalletForIncarnation2
  packages/deploy-script-support/src/offer.js
  packages/smart-wallet/src/offerWatcher.js
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:rebase

#8742 feat(vow): a pattern for promises that survive upgrades
  .github/workflows/test-all-packages.yml
  packages/agoric-cli/src/sdk-package-names.js
  packages/internal/src/queue.js
  packages/vat-data/package.json
  packages/vat-data/src/vat-data-bindings.js
  packages/vat-data/test/test-vow.js
  packages/vat-data/vow.js
  packages/vow/CHANGELOG.md
  packages/vow/README.md
  packages/vow/package.json
  packages/vow/src/E.js
  packages/vow/src/index.js
  packages/vow/src/message-breakpoints.js
  packages/vow/src/tools.js
  packages/vow/src/track-turns.js
  packages/vow/src/types.js
  packages/vow/src/vow-utils.js
  packages/vow/src/vow.js
  packages/vow/src/watch-promise.js
  packages/vow/src/watch.js
  packages/vow/src/when.js
  packages/vow/test/test-disconnect.js
  packages/vow/test/test-watch.js
  packages/vow/tsconfig.build.json
  packages/vow/tsconfig.json
  scripts/check-dependency-cycles.sh
Labels: enhancement, pegasus, automerge:no-update, far

#8968 U14/smart wallet repair
  packages/deploy-script-support/src/offer.js
  packages/smart-wallet/src/offerWatcher.js
  packages/smart-wallet/src/smartWallet.js
Labels: force:integration

#8970 PR feedback for PFM
  golang/cosmos/e2e_test/Makefile
  golang/cosmos/e2e_test/README.md
Labels: automerge:squash, agoric-cosmos

#8975 chore(cosmos): state-sync improvements
  golang/cosmos/daemon/cmd/root.go
  golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go
Labels: automerge:rebase, force:integration

#8971 golangci lint fix
  .github/workflows/golangci-lint.yml
  golang/cosmos/Makefile
  golang/cosmos/ante/ante.go
  golang/cosmos/ante/fee.go
  golang/cosmos/ante/inbound_test.go
  golang/cosmos/ante/vm_admission.go
  golang/cosmos/app/app.go
  golang/cosmos/cmd/libdaemon/main_test.go
  golang/cosmos/daemon/cmd/root.go
  golang/cosmos/x/lien/keeper/keeper.go
  golang/cosmos/x/lien/lien.go
  golang/cosmos/x/lien/lien_test.go
  golang/cosmos/x/swingset/client/cli/tx.go
  golang/cosmos/x/swingset/handler.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/querier.go
  golang/cosmos/x/swingset/keeper/swing_store_exports_handler.go
  golang/cosmos/x/swingset/proposal_handler.go
  golang/cosmos/x/swingset/types/expected_keepers.go
  golang/cosmos/x/swingset/types/msgs.go
  golang/cosmos/x/swingset/types/params.go
  golang/cosmos/x/swingset/types/proposal.go
  golang/cosmos/x/vbank/handler.go
  golang/cosmos/x/vbank/keeper/querier.go
  golang/cosmos/x/vibc/handler.go
  golang/cosmos/x/vibc/ibc.go
  golang/cosmos/x/vibc/keeper/keeper.go
  golang/cosmos/x/vstorage/handler.go
  golang/cosmos/x/vstorage/keeper/keeper.go
  golang/cosmos/x/vstorage/keeper/querier.go
  golang/cosmos/x/vstorage/keeper/querier_test.go
Labels: automerge:squash, agoric-cosmos

#8923 chore: Sync Endo versions 2024-02-14
  MAINTAINERS.md
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/test-xsnap-store.js.md
  packages/SwingSet/test/snapshots/test-xsnap-store.js.snap
  packages/agoric-cli/package.json
  packages/assert/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/xsnap/test/test-xs-perf.js
  packages/zoe/package.json
  packages/zone/package.json
  patches/@endo+patterns+1.1.0.patch
  yarn.lock
Labels: automerge:rebase, force:integration

#7116 refactor(ertp): ertp on zones
  packages/ERTP/package.json
  packages/ERTP/src/index.js
  packages/ERTP/src/issuerKit.js
  packages/ERTP/src/mathHelpers/copyBagMathHelpers.js
  packages/ERTP/src/payment.js
  packages/ERTP/src/paymentLedger.js
  packages/ERTP/src/purse.js
  packages/ERTP/src/types-ambient.js
  packages/ERTP/test/unitTests/mathHelpers/test-copyBagMathHelpers.js
Labels: ERTP, automerge:squash, stores

#8965 refactor(zoe,base-zone): move prepare-revocable to base-zone helper lib
  packages/base-zone/package.json
  packages/base-zone/src/prepare-revocable.js
  packages/base-zone/test/prepare-test-env-ava.js
  packages/base-zone/test/test-prepare-revocable.js
  packages/base-zone/zone-helpers.js
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/prepare-ownable.js
Labels: automerge:squash

#8984 fix: repair incorrect fix for repairWalletForIncarnation2
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:rebase

#8986 fix(agd): Support environments with shasum but not sha1sum
  bin/agd
Labels: automerge:rebase

#8985 port 8966 repair
  packages/smart-wallet/src/smartWallet.js
Labels: force:integration

#8973 refactor(SwingSet): Simplify makeRunUtils
  packages/SwingSet/tools/run-utils.js
  packages/boot/tools/supports.ts
Labels: automerge:rebase

#8988 feat: Simple removal of lien primarilly through code search
  golang/cosmos/app/app.go
  golang/cosmos/proto/agoric/lien/genesis.proto
  golang/cosmos/proto/agoric/lien/lien.proto
  golang/cosmos/x/lien/alias.go
  golang/cosmos/x/lien/genesis.go
  golang/cosmos/x/lien/genesis_test.go
  golang/cosmos/x/lien/keeper/account.go
  golang/cosmos/x/lien/keeper/keeper.go
  golang/cosmos/x/lien/keeper/keeper_test.go
  golang/cosmos/x/lien/lien.go
  golang/cosmos/x/lien/lien_test.go
  golang/cosmos/x/lien/module.go
  golang/cosmos/x/lien/spec/01_concepts.md
  golang/cosmos/x/lien/spec/02_messages.md
  golang/cosmos/x/lien/types/accountkeeper.go
  golang/cosmos/x/lien/types/accountstate.go
  golang/cosmos/x/lien/types/expected_keepers.go
  golang/cosmos/x/lien/types/genesis.pb.go
  golang/cosmos/x/lien/types/key.go
  golang/cosmos/x/lien/types/lien.pb.go
  packages/cosmic-swingset/src/chain-main.js
Labels: automerge:squash, agoric-cosmos

#8999 fix(agd): Support environments with shasum but not sha1sum (#8986)
  bin/agd
Labels: force:integration

#8998 smart wallet report rejections of durable promises
  packages/smart-wallet/src/offerWatcher.js
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:rebase, force:integration

#9004 remove restart-vats from a3p
  a3p-integration/README.md
  a3p-integration/proposals/b:localchain/README.md
  a3p-integration/proposals/g:restart-vats/.gitignore
  a3p-integration/proposals/g:restart-vats/.yarnrc.yml
  a3p-integration/proposals/g:restart-vats/README.md
  a3p-integration/proposals/g:restart-vats/package.json
  a3p-integration/proposals/g:restart-vats/test.sh
  a3p-integration/proposals/g:restart-vats/yarn.lock
  scripts/generate-a3p-submission.sh
Labels: automerge:rebase

#9012 refactor(smart-wallet): test UpgradeDisconnection correctly
  packages/smart-wallet/src/smartWallet.js
Labels: automerge:squash

#8992 fix(vow): simplify `watch` and promptly register reactions
  packages/boot/package.json
  packages/boot/test/upgrading/test-upgrade-vats.js
  packages/boot/test/upgrading/vat-vow.js
  packages/vat-data/test/test-vow.js
  packages/vat-data/vow.js
  packages/vow/README.md
  packages/vow/src/E.js
  packages/vow/src/tools.js
  packages/vow/src/vow-utils.js
  packages/vow/src/vow.js
  packages/vow/src/watch-promise.js
  packages/vow/src/watch.js
  packages/vow/src/when.js
  packages/vow/test/test-disconnect.js
  packages/vow/test/test-watch.js
Labels: automerge:no-update, IBC

#9007 misc typescript
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/agoric-cli/src/lib/format.js
  packages/base-zone/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/internal/src/batched-deliver.js
  packages/internal/src/marshal.js
  packages/smart-wallet/package.json
  packages/smart-wallet/src/smartWallet.js
  packages/solo/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/telemetry/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/vow/src/message-breakpoints.js
  packages/vow/src/track-turns.js
  packages/vow/tsconfig.json
  packages/xsnap/package.json
  packages/zoe/package.json
Labels: automerge:rebase

#8721 feat!: make Network and IBC vats durable
  bin/agd
  packages/boot/test/bootstrapTests/test-vats-restart.ts
  packages/builders/scripts/pegasus/init-core.js
  packages/network/package.json
  packages/network/src/index.js
  packages/network/src/network.js
  packages/network/src/router.js
  packages/network/src/types.js
  packages/network/test/test-network-misc.js
  packages/network/tsconfig.json
  packages/network/typedoc.json
  packages/notifier/src/index.js
  packages/pegasus/package.json
  packages/pegasus/src/contract.js
  packages/pegasus/src/courier.js
  packages/pegasus/src/pegasus.js
  packages/pegasus/src/proposals/core-proposal.js
  packages/pegasus/test/test-peg.js
  packages/vats/src/core/client-behaviors.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/ibc.js
  packages/vats/src/proposals/network-proposal.js
  packages/vats/src/proposals/restart-vats-proposal.js
  packages/vats/src/proposals/zcf-proposal.js
  packages/vats/src/vat-ibc.js
  packages/vats/src/vat-network.js
  packages/vats/test/test-network.js
  packages/vats/tools/boot-test-utils.js
  yarn.lock
Labels: automerge:squash

#9009 8868 gen submissions
  a3p-integration/README.md
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-next/package.json
  a3p-integration/proposals/b:localchain/README.md
  a3p-integration/proposals/b:localchain/package.json
  scripts/generate-a3p-submission-dir.sh
  scripts/generate-a3p-submission.sh
Labels: tooling, automerge:squash
