Repository Agoric/agoric-sdk, pull requests merged in 2024-12, with the labels that each got.

#10325 remove tsimp
  multichain-testing/.gitignore
  multichain-testing/ava.fusdc.config.js
  multichain-testing/ava.main.config.js
  multichain-testing/package.json
  multichain-testing/yarn.lock
  packages/cosmic-proto/.gitignore
  packages/cosmic-proto/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#10607 chore(fast-usdc): prune testBorrow, testRepay methods
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/pool-share-math.test.ts
Labels: automerge:rebase

#10419 chore(pp-upgrade): test functionality after provisionPool and bank upgrade
  a3p-integration/proposals/p:upgrade-19/.gitignore
  a3p-integration/proposals/p:upgrade-19/depositUSD-LEMONS/deposit-usd-lemons-permit.json
  a3p-integration/proposals/p:upgrade-19/depositUSD-LEMONS/deposit-usd-lemons.js
  a3p-integration/proposals/p:upgrade-19/nullUpgradePP/null-upgrade-pp-permit.json
  a3p-integration/proposals/p:upgrade-19/nullUpgradePP/null-upgrade-pp.js
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/provisionPool.test.js
  a3p-integration/proposals/p:upgrade-19/test-lib/provision-helpers.js
  a3p-integration/proposals/p:upgrade-19/test.sh
  a3p-integration/proposals/p:upgrade-19/tsconfig.json
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  a3p-integration/proposals/z:acceptance/yarn.lock
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/testing/add-USD-LEMONS.js
  packages/inter-protocol/package.json
  packages/inter-protocol/src/provisionPool.js
  packages/inter-protocol/src/provisionPoolKit.js
  packages/inter-protocol/test/provisionPool.test.js
  packages/vats/src/proposals/upgrade-provisionPool-proposal.js
Labels: automerge:rebase, force:integration

#10588 feat!: `chainHub.getAsset` requires `srcChainName` parameter
  a3p-integration/proposals/z:acceptance/vaults.test.js
  multichain-testing/test/send-anywhere.test.ts
  multichain-testing/test/support.ts
  multichain-testing/test/tools/asset-info.test.ts
  multichain-testing/tools/asset-info.ts
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/test/supports.ts
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/proposals/start-send-anywhere.js
  packages/orchestration/src/utils/chain-hub-helper.js
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/facade-durability.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/test/types.test-d.ts
Labels: automerge:rebase

#10603 refactor: Cleanup #10348
  packages/SwingSet/tools/run-utils.js
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/price-feed-replace.test.ts
  packages/boot/tools/liquidation.ts
  packages/boot/tools/supports.ts
  packages/cosmic-swingset/src/computron-counter.js
Labels: automerge:rebase

#10611 agoric-cli lib export
  a3p-integration/proposals/s:stake-bld/package.json
  a3p-integration/proposals/s:stake-bld/test-lib/chain.js
  a3p-integration/proposals/s:stake-bld/test-lib/index.js
  a3p-integration/proposals/s:stake-bld/test-lib/rpc.js
  a3p-integration/proposals/s:stake-bld/test-lib/wallet.js
  a3p-integration/proposals/s:stake-bld/yarn.lock
  packages/agoric-cli/package.json
  packages/agoric-cli/src/lib/index.js
Labels: automerge:rebase, force:integration

#10606 test(fast-usdc): bootstrap test for advancement
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/fast-usdc/src/type-guards.js
Labels: automerge:squash

#10591 test: `send-anywhere` pfm scenarios
  .github/workflows/multichain-e2e-template.yml
  multichain-testing/.gitignore
  multichain-testing/Makefile
  multichain-testing/README.md
  multichain-testing/scripts/deploy-cli.ts
  multichain-testing/scripts/make-bank-asset-info.ts
  multichain-testing/src/register-interchain-bank-assets.builder.js
  multichain-testing/src/revise-chain-info.builder.js
  multichain-testing/test/auto-stake-it.test.ts
  multichain-testing/test/scripts/make-bank-asset-info.test.ts
  multichain-testing/test/send-anywhere.test.ts
  multichain-testing/test/support.ts
  multichain-testing/test/tools/asset-info.test.ts
  multichain-testing/tools/agd-lib.js
  multichain-testing/tools/asset-info.ts
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/faucet-tools.ts
  multichain-testing/tools/ibc-transfer.ts
  multichain-testing/tools/sleep.ts
  multichain-testing/tsconfig.json
  packages/builders/scripts/testing/register-interchain-bank-assets.js
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/proposals/start-send-anywhere.js
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
Labels: automerge:rebase, force:integration

#10610 feat(fast-usdc): operator attest cli command
  packages/fast-usdc/package.json
  packages/fast-usdc/src/cli/cli.js
  packages/fast-usdc/src/cli/config.js
  packages/fast-usdc/src/cli/operator-commands.js
  packages/fast-usdc/src/cli/transfer.js
  packages/fast-usdc/test/cli/operator-commands.test.ts
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.md
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.snap
  packages/fast-usdc/test/cli/transfer.test.ts
  packages/fast-usdc/tools/cli-tools.ts
  packages/fast-usdc/tools/mock-io.ts
Labels: automerge:rebase

#10621 test(fast-usdc): count computrons for advancement
  packages/boot/package.json
  packages/boot/test/fast-usdc/fast-usdc.test.ts
Labels: automerge:rebase

#10615 don't reschedule auction's price notifier if we already have one
  packages/inter-protocol/src/auction/auctionBook.js
Labels: bug, automerge:squash, resource-exhaustion, contract-upgrade, auction

#10626 chore: fusdc multichain support
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/tools/ibc/mocks.ts
  packages/boot/tools/supports.ts
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc/src/cli/operator-commands.js
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/fast-usdc.flows.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/facade-durability.test.ts
Labels: automerge:rebase

#10634 chore: add dATOM brand name to DEVNET config
  packages/builders/scripts/inter-protocol/updatePriceFeeds.js
Labels: automerge:rebase

#10635 fix(telemetry): Empty context persisted when remaining beans are negative after run finish
  packages/telemetry/src/context-aware-slog.js
  packages/telemetry/src/otel-context-aware-slog.js
Labels: automerge:squash

#10630 misc dep bumps
  .eslintrc.cjs
  multichain-testing/package.json
  multichain-testing/test/chain-queries.test.ts
  multichain-testing/yarn.lock
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/agoric-cli/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/casting/package.json
  packages/client-utils/package.json
  packages/cosmic-proto/scripts/test-live.js
  packages/cosmic-swingset/package.json
  packages/eslint-config/package.json
  packages/fast-usdc/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/internal/tsconfig.json
  packages/notifier/tsconfig.json
  packages/orchestration/package.json
  packages/orchestration/tsconfig.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vats/package.json
  packages/vow/tsconfig.json
  packages/zoe/package.json
  patches/acorn+8.10.0.patch
  yarn.lock
Labels: automerge:rebase

#10609 feat(fast-usdc): core-eval to change fastUsdc.feedPolicy
  packages/boot/package.json
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/builders/scripts/fast-usdc/fast-usdc-update.build.js
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/fast-usdc/src/fast-usdc-policy.core.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/deploy-config.js
Labels: automerge:rebase

#10645 chore: upgrade 18 cherrypicks round 4
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/inter-protocol/updatePriceFeeds.js
  packages/inter-protocol/src/auction/auctionBook.js
  packages/telemetry/src/context-aware-slog.js
  packages/telemetry/src/otel-context-aware-slog.js
  packages/telemetry/src/slog-to-otel.js
Labels: force:integration

#10656 chore(release): publish upgrade-18-rc3
  golang/cosmos/CHANGELOG.md
  golang/cosmos/package.json
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/benchmark/CHANGELOG.md
  packages/benchmark/package.json
  packages/boot/CHANGELOG.md
  packages/boot/package.json
  packages/builders/CHANGELOG.md
  packages/builders/package.json
  packages/casting/CHANGELOG.md
  packages/casting/package.json
  packages/cosmic-proto/CHANGELOG.md
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/create-dapp/CHANGELOG.md
  packages/create-dapp/package.json
  packages/deploy-script-support/CHANGELOG.md
  packages/deploy-script-support/package.json
  packages/fast-usdc/CHANGELOG.md
  packages/fast-usdc/package.json
  packages/inter-protocol/CHANGELOG.md
  packages/inter-protocol/package.json
  packages/orchestration/CHANGELOG.md
  packages/orchestration/package.json
  packages/pegasus/CHANGELOG.md
  packages/pegasus/package.json
  packages/smart-wallet/CHANGELOG.md
  packages/smart-wallet/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
  packages/swingset-runner/CHANGELOG.md
  packages/swingset-runner/package.json
  packages/telemetry/CHANGELOG.md
  packages/telemetry/package.json
  packages/vats/CHANGELOG.md
  packages/vats/package.json
  packages/wallet/api/CHANGELOG.md
  packages/wallet/api/package.json
Labels: force:integration

#10469 chore(SwingSet): Improve anachrophobia messages
  packages/SwingSet/src/kernel/vat-warehouse.js
Labels: automerge:rebase

#10643 fix(z:acceptance): fix flakey `z:acceptance/vaults.test.js`
  a3p-integration/proposals/z:acceptance/vaults.test.js
Labels: automerge:rebase, force:integration

#10616 chore(vat-upgrade): upgrade agoricNames, test old values are preserved
  a3p-integration/proposals/p:upgrade-19/.gitignore
  a3p-integration/proposals/p:upgrade-19/agoricNames.test.js
  a3p-integration/proposals/p:upgrade-19/agoricNamesCoreEvals/depositUsdOlives/deposit-usd-olives-permit.json
  a3p-integration/proposals/p:upgrade-19/agoricNamesCoreEvals/depositUsdOlives/deposit-usd-olives.js
  a3p-integration/proposals/p:upgrade-19/agoricNamesCoreEvals/writeToAgoricNames/write-to-agoricNames-permit.json
  a3p-integration/proposals/p:upgrade-19/agoricNamesCoreEvals/writeToAgoricNames/write-to-agoricNames.js
  a3p-integration/proposals/p:upgrade-19/agoricNamesCoreEvals/writeToTestInfo/write-to-testInfo-permit.json
  a3p-integration/proposals/p:upgrade-19/agoricNamesCoreEvals/writeToTestInfo/write-to-testInfo.js
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/test-lib/index.js
  a3p-integration/proposals/p:upgrade-19/test-lib/psm-lib.js
  a3p-integration/proposals/p:upgrade-19/test-lib/utils.js
  a3p-integration/proposals/p:upgrade-19/test.sh
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/testing/add-USD-OLIVES.js
  packages/builders/scripts/testing/publish-test-info.js
  packages/builders/scripts/vats/upgrade-agoricNames.js
  packages/vats/src/proposals/upgrade-agoricNames-proposal.js
Labels: automerge:rebase, force:integration

#10641 chore(fast-usdc): limited operation before connecting to noble
  a3p-integration/proposals/f:fast-usdc/package.json
  a3p-integration/proposals/f:fast-usdc/test.sh
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/deploy-config.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
Labels: automerge:rebase, force:integration

#10636 feat(fast-usdc): cli for lp deposit and withdraw
  packages/fast-usdc/src/cli/bridge-action.js
  packages/fast-usdc/src/cli/cli.js
  packages/fast-usdc/src/cli/lp-commands.js
  packages/fast-usdc/src/cli/operator-commands.js
  packages/fast-usdc/test/cli/cli.test.ts
  packages/fast-usdc/test/cli/lp-commands.test.ts
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.md
  packages/fast-usdc/test/cli/snapshots/cli.test.ts.snap
Labels: automerge:rebase

#10668 Don't reschedule vault's priceNotifier if one exists
  packages/inter-protocol/src/vaultFactory/vaultManager.js
Labels: performance, automerge:rebase, resource-exhaustion, Vaults, force:integration, next-release, sdk-50-upgrade

#10613 feat: `bech32` Address Hooks
  a3p-integration/proposals/s:stake-bld/yarn.lock
  a3p-integration/proposals/z:acceptance/yarn.lock
  golang/cosmos/types/address_hooks.go
  golang/cosmos/types/address_hooks_test.go
  golang/cosmos/x/vtransfer/ibc_middleware_test.go
  golang/cosmos/x/vtransfer/keeper/keeper.go
  packages/cosmic-proto/package.json
  packages/cosmic-proto/src/address-hooks.js
  packages/cosmic-proto/test/address-hooks.test.js
  packages/cosmic-proto/test/vatsafe.test.js
  packages/cosmic-proto/typedoc.json
  typedoc.json
  yarn.lock
Labels: automerge:no-update, agd

#10672 fix(telemetry): timer-poll run.id
  packages/telemetry/src/context-aware-slog.js
Labels: automerge:squash

#10671 fix(client-utils): only call `fetch` as a function, not a method
  a3p-integration/proposals/z:acceptance/test-lib/rpc.js
  packages/client-utils/src/vstorage.js
Labels: automerge:squash

#10670 synchronous makeVstorageKit
  a3p-integration/proposals/s:stake-bld/package.json
  a3p-integration/proposals/s:stake-bld/stakeBld.test.js
  a3p-integration/proposals/s:stake-bld/test-lib/index.js
  a3p-integration/proposals/s:stake-bld/test-lib/wallet.js
  a3p-integration/proposals/s:stake-bld/yarn.lock
  a3p-integration/proposals/z:acceptance/psm.test.js
  a3p-integration/proposals/z:acceptance/test-lib/chain.js
  a3p-integration/proposals/z:acceptance/test-lib/errors.js
  a3p-integration/proposals/z:acceptance/test-lib/index.js
  a3p-integration/proposals/z:acceptance/test-lib/kread.js
  a3p-integration/proposals/z:acceptance/test-lib/psm-lib.js
  a3p-integration/proposals/z:acceptance/test-lib/rpc.js
  a3p-integration/proposals/z:acceptance/test-lib/utils.js
  a3p-integration/proposals/z:acceptance/test-lib/vaults.js
  a3p-integration/proposals/z:acceptance/test-lib/wallet.js
  a3p-integration/proposals/z:acceptance/valueVow.test.js
  a3p-integration/proposals/z:acceptance/vaults.test.js
  packages/agoric-cli/src/commands/auction.js
  packages/agoric-cli/src/commands/gov.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/src/commands/psm.js
  packages/agoric-cli/src/commands/reserve.js
  packages/agoric-cli/src/commands/vaults.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/wallet.js
  packages/client-utils/src/main.js
  packages/client-utils/src/smart-wallet-kit.js
  packages/client-utils/src/vstorage-kit.js
  packages/client-utils/src/wallet-utils.js
  packages/client-utils/test/snapshots/exports.test.js.md
  packages/client-utils/test/snapshots/exports.test.js.snap
  packages/client-utils/test/snapshots/vstorage-kit.test.js.md
  packages/client-utils/test/snapshots/vstorage-kit.test.js.snap
  packages/client-utils/test/vstorage-kit.test.js
  packages/fast-usdc/src/cli/lp-commands.js
  packages/fast-usdc/src/cli/operator-commands.js
  packages/fast-usdc/test/cli/lp-commands.test.ts
Labels: automerge:rebase, force:integration

#10679 chore: fusdc `ChainPolicy` schema
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/deploy-config.js
Labels: automerge:rebase

#10617 test(a3p): test mintHolder functionalities after contract null upgrade
  a3p-integration/proposals/p:upgrade-19/.gitignore
  a3p-integration/proposals/p:upgrade-19/mint-payment/send-script-permit.json
  a3p-integration/proposals/p:upgrade-19/mint-payment/send-script.tjs
  a3p-integration/proposals/p:upgrade-19/mintHolder.test.js
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/test-lib/mintHolder-helpers.js
  a3p-integration/proposals/p:upgrade-19/test-lib/psm-lib.js
  a3p-integration/proposals/p:upgrade-19/test.sh
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/vats/upgrade-mintHolder.js
  packages/vats/src/proposals/upgrade-mintHolder-proposal.js
Labels: automerge:rebase, force:integration

#10659 chore: fusdc recovery paths
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/orchestration/src/exos/local-orchestration-account.js
Labels: automerge:rebase

#10683 fix(address-hooks): version robustness and hardening
  golang/cosmos/types/address_hooks.go
  golang/cosmos/types/address_hooks_test.go
  packages/cosmic-proto/src/address-hooks.js
  packages/cosmic-proto/test/address-hooks.test.js
Labels: automerge:no-update, agd

#10682 chore: fusdc uses bech32 address hook encoding
  packages/cosmic-proto/src/address-hooks.js
  packages/fast-usdc/package.json
  packages/fast-usdc/src/cli/transfer.js
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/address.js
  packages/fast-usdc/test/cli/snapshots/transfer.test.ts.md
  packages/fast-usdc/test/cli/snapshots/transfer.test.ts.snap
  packages/fast-usdc/test/cli/transfer.test.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/utils/address.test.ts
Labels: automerge:rebase

#10618 test: fusdc multichain
  multichain-testing/ava.main.config.js
  multichain-testing/test/account-balance-queries.test.ts
  multichain-testing/test/auto-stake-it.test.ts
  multichain-testing/test/basic-flows.test.ts
  multichain-testing/test/chain-queries.test.ts
  multichain-testing/test/deposit-withdraw-lca.test.ts
  multichain-testing/test/deposit-withdraw-portfolio.test.ts
  multichain-testing/test/fast-usdc/config.ts
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/ica-channel-close.test.ts
  multichain-testing/test/send-anywhere.test.ts
  multichain-testing/test/stake-ica.test.ts
  multichain-testing/test/support.ts
  multichain-testing/tools/agd-lib.js
  multichain-testing/tools/asset-info.ts
  multichain-testing/tools/deploy.ts
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/noble-tools.ts
  multichain-testing/tools/purse.ts
  multichain-testing/tools/random.ts
  multichain-testing/yarn.lock
Labels: automerge:rebase, force:integration

#10638 chore(provisionPool): allow overriding PerAccountInitialAmount during contract upgrade
  packages/governance/src/contractHelper.js
  packages/inter-protocol/src/provisionPool.js
  packages/vats/src/proposals/upgrade-provisionPool-proposal.js
Labels: automerge:rebase, force:integration

#10680 Record instances that will be replaced so we can manage them
  a3p-integration/proposals/z:acceptance/.gitignore
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/recorded-retired.test.js
  a3p-integration/proposals/z:acceptance/test.sh
  packages/boot/test/bootstrapTests/price-feed-replace.test.ts
  packages/boot/test/bootstrapTests/updateGovernedParams.test.ts
  packages/builders/scripts/inter-protocol/updatePriceFeeds.js
  packages/builders/scripts/testing/recorded-retired-instances.js
  packages/inter-protocol/src/proposals/add-auction.js
  packages/inter-protocol/src/proposals/deploy-price-feeds.js
  packages/inter-protocol/src/proposals/replaceElectorate.js
  packages/inter-protocol/src/proposals/utils.js
Labels: deployment, code-style, Inter-protocol, automerge:rebase, contract-upgrade, force:integration, next-release

#10676 chore: uprade 18 cherrypicks round 5
  a3p-integration/proposals/z:acceptance/.gitignore
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/recorded-retired.test.js
  a3p-integration/proposals/z:acceptance/test.sh
  packages/boot/test/bootstrapTests/price-feed-replace.test.ts
  packages/boot/test/bootstrapTests/updateGovernedParams.test.ts
  packages/builders/scripts/inter-protocol/updatePriceFeeds.js
  packages/builders/scripts/testing/recorded-retired-instances.js
  packages/inter-protocol/src/proposals/add-auction.js
  packages/inter-protocol/src/proposals/deploy-price-feeds.js
  packages/inter-protocol/src/proposals/replaceElectorate.js
  packages/inter-protocol/src/proposals/utils.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/telemetry/src/context-aware-slog.js
Labels: force:integration

#10694 Save the contractKit for the auctioneer before overwriting it
  packages/builders/scripts/testing/recorded-retired-instances.js
  packages/inter-protocol/src/proposals/add-auction.js
Labels: automerge:squash, contract-upgrade, force:integration, auction

#10696 test: add proposal w/300 E(chainTimerService).getTimerBrand() calls
  packages/builders/scripts/testing/provokeBOYD.js
Labels: automerge:squash, next-release

#10704 build(deps): use backport of cosmos-sdk v0.46.15
  golang/cosmos/e2e_test/go.mod
  golang/cosmos/e2e_test/go.sum
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  packages/cosmic-swingset/Makefile
Labels: automerge:no-update, agd, agoric-cosmos, force:integration

#10692 test(multichain): fusdc "advance and settle" as a macro
  a3p-integration/proposals/z:acceptance/governance.test.js
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
Labels: automerge:rebase, force:integration

#10555 test(a3p): extend governance test coverage for acceptance proposal
  a3p-integration/proposals/z:acceptance/.gitignore
  a3p-integration/proposals/z:acceptance/governance.test.js
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/test-lib/governance.js
  a3p-integration/proposals/z:acceptance/test-lib/psm-lib.js
  a3p-integration/proposals/z:acceptance/test-lib/rpc.js
  a3p-integration/proposals/z:acceptance/test-lib/utils.js
  a3p-integration/proposals/z:acceptance/test.sh
  packages/builders/scripts/testing/upgrade-vaultFactory.js
  packages/inter-protocol/src/proposals/upgrade-vaults.js
  packages/vats/src/proposals/upgrade-vaultFactory-proposal.js
Labels: automerge:rebase, force:integration

#10711 chore: u18 cherrypicks round 6
  a3p-integration/proposals/z:acceptance/wallet.test.js
  golang/cosmos/e2e_test/go.mod
  golang/cosmos/e2e_test/go.sum
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  packages/builders/scripts/testing/provokeBOYD.js
  packages/builders/scripts/testing/recorded-retired-instances.js
  packages/cosmic-swingset/Makefile
  packages/inter-protocol/src/proposals/add-auction.js
Labels: force:integration

#10633 transaction vstorage
  multichain-testing/README.md
  multichain-testing/package.json
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/noble-tools.ts
  multichain-testing/tsconfig.json
  multichain-testing/yarn.lock
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/cli/operator-commands.js
  packages/fast-usdc/src/constants.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/test/supports.ts
  packages/internal/src/index.js
  packages/internal/src/marshal.js
  packages/internal/src/storage-test-utils.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
Labels: automerge:rebase, force:integration

#10541 Add AssetReserve to Upgrade 19 with A3P test coverage
  a3p-integration/proposals/p:upgrade-19/.gitignore
  a3p-integration/proposals/p:upgrade-19/addCollateral/add-collateral-permit.json
  a3p-integration/proposals/p:upgrade-19/addCollateral/add-collateral.js
  a3p-integration/proposals/p:upgrade-19/assetReserve.test.js
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/test.sh
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/vats/upgrade-asset-reserve.js
  packages/inter-protocol/src/proposals/econ-behaviors.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/test/swingsetTests/reserve/bootstrap-assetReserve-upgrade.js
  packages/vats/src/proposals/upgrade-asset-reserve-proposal.js
Labels: automerge:squash, force:integration

#10716 chore(release): publish upgrade-18-rc5
  golang/cosmos/CHANGELOG.md
  golang/cosmos/package.json
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/benchmark/CHANGELOG.md
  packages/benchmark/package.json
  packages/boot/CHANGELOG.md
  packages/boot/package.json
  packages/builders/CHANGELOG.md
  packages/builders/package.json
  packages/casting/CHANGELOG.md
  packages/casting/package.json
  packages/cosmic-proto/CHANGELOG.md
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/create-dapp/CHANGELOG.md
  packages/create-dapp/package.json
  packages/deploy-script-support/CHANGELOG.md
  packages/deploy-script-support/package.json
  packages/fast-usdc/CHANGELOG.md
  packages/fast-usdc/package.json
  packages/inter-protocol/CHANGELOG.md
  packages/inter-protocol/package.json
  packages/orchestration/CHANGELOG.md
  packages/orchestration/package.json
  packages/pegasus/CHANGELOG.md
  packages/pegasus/package.json
  packages/smart-wallet/CHANGELOG.md
  packages/smart-wallet/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
  packages/swingset-runner/CHANGELOG.md
  packages/swingset-runner/package.json
  packages/vats/CHANGELOG.md
  packages/vats/package.json
  packages/wallet/api/CHANGELOG.md
  packages/wallet/api/package.json
Labels: force:integration

#10715 record transaction fees
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/supports.ts
  packages/internal/src/storage-test-utils.js
Labels: automerge:rebase

#10721 Operator attestation policy
  packages/fast-usdc/src/exos/operator-kit.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/utils/deploy-config.js
  packages/fast-usdc/test/exos/transaction-feed.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
Labels: automerge:rebase

#10717 feat(fast-usdc): detect transfer completion in cli
  packages/fast-usdc/demo/testnet/config.json
  packages/fast-usdc/src/cli/cli.js
  packages/fast-usdc/src/cli/config.js
  packages/fast-usdc/src/cli/transfer.js
  packages/fast-usdc/src/util/bank.js
  packages/fast-usdc/src/util/cctp.js
  packages/fast-usdc/test/cli/transfer.test.ts
  packages/fast-usdc/testing/mocks.ts
Labels: automerge:rebase

#10731 Turn on test of priceAuthority registry
  a3p-integration/proposals/p:upgrade-19/test.sh
Labels: test, automerge:rebase, contract-upgrade, force:integration, next-release

#10723 chore: `advancer` validates `settlementAccount` address
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/boot/test/orchestration/contract-upgrade.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/boot/tools/supports.ts
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/cli/transfer.test.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/supports.ts
  packages/orchestration/package.json
  packages/orchestration/test/tools/make-test-address.test.ts
  packages/orchestration/tools/make-test-address.js
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase, force:integration

#10751 refactor(orchestration,time,zoe): Avoid name convention conflict
  packages/orchestration/src/examples/staking-combinations.flows.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/portfolio-holder-kit.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/fixtures/zoe-tools.flows.js
  packages/orchestration/tools/ibc-mocks.ts
  packages/time/src/types.ts
  packages/zoe/tools/manualTimer.js
Labels: automerge:squash

#10753 feat(fast-usdc): support risk assessment arg
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/README.md
  packages/fast-usdc/src/constants.js
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/operator-kit.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/exos/transaction-feed.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
Labels: automerge:rebase, force:integration

#10758 fix(liveslots): avoid slotToVal memory leak for watched promises
  packages/swingset-liveslots/src/watchedPromises.js
  packages/swingset-liveslots/test/watch-promise.test.js
Labels: SwingSet, automerge:rebase, liveslots

#10759 chore: `slog.slog` in `multichain-testing` ci artifacts
  .github/workflows/multichain-e2e-template.yml
  multichain-testing/.gitignore
Labels: automerge:rebase, force:integration

#10761 feat: migrate upgrade of v7-board from upgrade 19 to upgrade 18
  a3p-integration/proposals/n:upgrade-next/.gitignore
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/upgradedBoard.test.js
  a3p-integration/proposals/p:upgrade-19/.gitignore
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/test.sh
  golang/cosmos/app/upgrade.go
Labels: deployment, performance, automerge:squash, contract-upgrade, force:integration, next-release

#10765 chore(cosmic-swingset): Add `phase` to cosmic-swingset-run-{start,finish} slog entries
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:squash, force:integration

#10767 feat(cosmos): Support arbitrary core eval builder arguments
  golang/cosmos/app/upgrade.go
Labels: automerge:squash

#10768 Cherry-pick u18 branch a3p test change
  a3p-integration/proposals/n:upgrade-next/prepare.sh
  a3p-integration/proposals/n:upgrade-next/use.sh
Labels: automerge:rebase

#10764 chore(agd): upgrade all orchestration vats to new liveslots
  a3p-integration/proposals/n:upgrade-next/initial.test.js
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/vats/upgrade-orchestration.js
  packages/vats/src/proposals/upgrade-vats-generic-proposal.js
Labels: automerge:no-update, agd, liveslots

#10752 chore: Add core-eval for terminating v110 zcf-b1-9f877-stkATOM-USD_price_feed-governor
  a3p-integration/proposals/n:upgrade-next/initial.test.js
  a3p-integration/proposals/n:upgrade-next/priceFeedUpdate.test.js
  a3p-integration/proposals/n:upgrade-next/test.sh
  a3p-integration/proposals/p:upgrade-19/.gitignore
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/terminateGovernor.test.js
  a3p-integration/proposals/p:upgrade-19/test.sh
  a3p-integration/proposals/p:upgrade-19/vatDetails.js
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/vats/terminate-governor-instance.js
Labels: automerge:rebase, force:integration

#10770 build(deps): update to CometBFT with ping fix
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: automerge:no-update, agd, force:integration

#10747 fix(acceptance): fix flakey psm test
  a3p-integration/proposals/z:acceptance/psm.test.js
  a3p-integration/proposals/z:acceptance/test-lib/psm-lib.js
Labels: automerge:rebase, force:integration

#10775 fix(acceptance): fix flakey wallet test
  a3p-integration/proposals/z:acceptance/wallet.test.js
Labels: automerge:rebase, force:integration

#10769 docs(deploy-script-support): Document "options" in the README
  packages/deploy-script-support/README.md
Labels: automerge:squash

#6727 types test for casting
  packages/casting/package.json
  packages/casting/test/types.test-d.ts
  packages/casting/tsconfig.json
  yarn.lock
Labels: automerge:rebase, bypass:integration

#10785 fix(scripts): Support jq version 1.6
  scripts/npm-dist-tag.sh
Labels: automerge:squash

#10784 tighten typescript-eslint rules
  .aiderignore
  .eslintrc.cjs
  .gitignore
  package.json
  packages/async-flow/src/types.ts
  packages/boot/test/bootstrapTests/net-ibc-upgrade.test.ts
  packages/boot/tools/drivers.ts
  packages/casting/test/types.test-d.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/test/facade.test.ts
  packages/swingset-liveslots/src/vatDataTypes.ts
  packages/time/src/types.ts
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/types.ts
  packages/vats/test/types-ambient.test-d.ts
  packages/vow/src/types.ts
  packages/zoe/src/contractFacet/types-ambient.d.ts
  packages/zoe/src/zoeService/utils.d.ts
  packages/zoe/test/types.test-d.ts
  yarn.lock
Labels: automerge:rebase, bypass:integration

#10783 fix potential flake caused by checking IST balances
  a3p-integration/proposals/n:upgrade-next/priceFeedUpdate.test.js
  a3p-integration/proposals/n:upgrade-next/test-lib/price-feed.js
  a3p-integration/proposals/p:upgrade-19/test-lib/mintHolder-helpers.js
Labels: automerge:rebase, force:integration
