Repository Agoric/agoric-sdk, pull requests merged in 2025-05, with the labels that each got.

#11346 build(nix): use `corepack`
  nix/devShell.nix
  nix/nodejs.nix
Labels: tooling, automerge:no-update

#11349 feat: add helm support for nix devshell
  nix/devShell.nix
Labels: automerge:rebase

#11336 improvements to bridge mocks
  packages/fast-usdc-contract/test/contract-setup.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/exos/status-manager.test.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-contract/test/forwarding.test.ts
  packages/fast-usdc-contract/test/supports.ts
  packages/fast-usdc-contract/test/utils/cctp.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/tools/contract-tests.ts
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase

#11335 refactor: factor out advanceFunds() flow
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/src/fast-usdc.flows.ts
  packages/fast-usdc-contract/src/utils/cctp.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/src/types.ts
Labels: automerge:rebase

#11355 chore(a3p-integration): use prop 92
  a3p-integration/package.json
Labels: automerge:rebase, force:integration

#11302 retry FORWARD_FAILED in FUSDC
  packages/fast-usdc-contract/README.md
  packages/fast-usdc-contract/package.json
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/src/exos/status-manager.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/src/fast-usdc.flows.ts
  packages/fast-usdc-contract/src/typeGuards.ts
  packages/fast-usdc-contract/src/utils/forward-retrier.ts
  packages/fast-usdc-contract/src/utils/route-health.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/exos/status-manager.test.ts
  packages/fast-usdc-contract/test/forwarding.test.ts
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc-contract/test/utils/forward-retrier.test.ts
  packages/fast-usdc-contract/test/utils/route-health.test.ts
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  yarn.lock
Labels: automerge:rebase, force:integration

#11354 fix: repay liquidity pool on depositForBurn failure
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/src/fast-usdc.flows.ts
  packages/fast-usdc-contract/test/contract-setup.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-contract/test/mocks.ts
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
Labels: automerge:rebase, force:integration

#11363 feat(agoric-cli): Remove support for -r esm contract scripts
  a3p-integration/proposals/z:acceptance/yarn.lock
  packages/agoric-cli/package.json
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/entrypoint.js
  packages/agoric-cli/src/scripts.js
  packages/agoric-cli/test/main.test.js
Labels: automerge:rebase, force:integration

#11364 feat(solo): Move from RESM to NESM
  packages/solo/package.json
  packages/solo/src/entrypoint.js
  packages/solo/src/start.js
  yarn.lock
Labels: automerge:rebase, force:integration

#11367 Reproducible docker builds
  .dockerignore
  packages/deployment/Dockerfile.sdk
Labels: automerge:rebase, force:integration

#11172 FUSDC flows
  packages/fast-usdc-contract/README.md
  packages/fast-usdc-contract/src/exos/status-manager.ts
  packages/fast-usdc-contract/src/fast-usdc.flows.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc/README.md
Labels: automerge:rebase, bypass:integration

#11322 feat: `IcaAccount` can specify ICA packet timeout via `relativeTimeoutNs`
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/network/src/network.js
  packages/network/src/shapes.js
  packages/network/src/types.js
  packages/notifier/test/snapshots/exports.test.js.md
  packages/notifier/test/snapshots/exports.test.js.snap
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/ica-account-kit.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/snapshots/exports.test.ts.md
  packages/orchestration/test/snapshots/exports.test.ts.snap
Labels: automerge:rebase, force:integration

#11372 tools: `VBANK_GRAB` in mock bank bridge throws when insufficient funds are detected
  golang/cosmos/x/vbank/vbank_test.go
  packages/orchestration/test/examples/basic-flows.contract.test.ts
  packages/orchestration/test/utils/zoe-tools.test.ts
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase

#11370 remediate errant batch settlements
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/src/exos/status-manager.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-deploy/src/upgrade-evm-dests.core.js
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.md
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.snap
  packages/orchestration/src/utils/address.js
Labels: automerge:rebase

#11375 chore: implement `parseInboundTransfer`
  packages/cosmic-proto/src/helpers.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase

#11371 chore(SwingSet): Document ManagerType values
  packages/SwingSet/src/types-external.js
Labels: automerge:squash

#11382 feat(agoric-cli): Add `--verbose` option to `agops perf satisfaction`
  packages/agoric-cli/src/commands/perf.js
Labels: automerge:squash

#11358 test with Node 22
  .github/actions/restore-node/action.yml
  .github/workflows/integration.yml
  .github/workflows/test-all-packages.yml
  .node-version
  golang/cosmos/package.json
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-proto/test/address-hooks.test.js
  packages/cosmic-proto/test/vatsafe.test.js
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/test/examples/snapshots/stake-ica.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/stake-ica.contract.test.ts.snap
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/pegasus/package.json
  packages/solo/package.json
  packages/sparse-ints/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swingset-liveslots/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vm-config/package.json
  packages/zoe/package.json
  packages/zone/package.json
  repoconfig.sh
  yarn.lock
Labels: automerge:rebase, force:integration

#11384 feat(vats): Add success output to terminate-governed-instance.js core-evals
  packages/vats/src/proposals/terminate-governed-instance.js
Labels: automerge:squash

#11392 test(cosmic-swingset): Add retries for metrics comparison
  packages/cosmic-swingset/test/prometheus.test.ts
Labels: automerge:squash

#11385 express reimbursement in uusdc
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/fast-usdc/noble-forwarding.test.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-deploy/scripts/check-forward-fails.ts
  packages/fast-usdc-deploy/src/reimburse-manual-intervention.build.js
  packages/fast-usdc-deploy/src/reimburse-manual-intervention.core.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/utils/address.js
  packages/orchestration/test/supports.ts
  packages/orchestration/test/utils/address.test.ts
  packages/orchestration/tools/contract-tests.ts
Labels: automerge:rebase

#11390 miscellaneous fixes
  .github/workflows/integration.yml
  .github/workflows/test-all-packages.yml
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/test/kread.test.js
  a3p-integration/proposals/z:acceptance/test/test-lib/kread.js
  package.json
  packages/ERTP/package.json
  packages/SwingSet/src/types-external.js
  packages/agoric-cli/src/commands/perf.js
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/follow.js
  packages/casting/src/defaults.js
  packages/xsnap/README.md
  packages/xsnap/package.json
  packages/zoe/package.json
  scripts/check-untested-packages.mjs
  scripts/create-agoric-cli.cjs
  scripts/migrate-test-names.mjs
  scripts/registry.sh
  scripts/update-typedoc-functions-path.cjs
Labels: automerge:rebase

#11401 ci: add corepack enable to `dump-ci-stats.yml`
  .github/workflows/dump-ci-stats.yml
Labels: automerge:rebase

#11407 drop Node 18
  .github/actions/restore-node/action.yml
  .gitignore
  README.md
  golang/cosmos/package.json
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/pegasus/package.json
  packages/solo/package.json
  packages/sparse-ints/package.json
  packages/spawner/package.json
  packages/store/package.json
  packages/swingset-liveslots/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vm-config/package.json
  packages/zoe/package.json
  packages/zone/package.json
  repoconfig.sh
Labels: automerge:rebase

#11409 ci: remove `--ignore-workspace-root-check` flag in dump-ci-stats
  .github/workflows/dump-ci-stats.yml
Labels: automerge:rebase

#11406 test(cosmic-swingset): Implement subprocess-based retries for metrics comparison
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/test/prometheus.test.ts
  packages/telemetry/package.json
  packages/telemetry/src/otel-metrics.js
  packages/telemetry/src/slog-sender-pipe.js
  yarn.lock
Labels: automerge:rebase

#11417 test(cosmic-swingset): improve prometheus test reliability
  .github/workflows/nix-check.yml
  packages/cosmic-swingset/test/prometheus.test.ts
Labels: cosmic-swingset, test, automerge:no-update

#6262 fix device timer remove()
  packages/SwingSet/package.json
  packages/SwingSet/src/devices/timer/device-timer.js
  packages/SwingSet/test/timer-device.test.js
  packages/SwingSet/tools/manual-timer.js
Labels: SwingSet, security, automerge:rebase

#11425 test: Replace sinon with tinyspy
  packages/fast-usdc-contract/package.json
  packages/fast-usdc-contract/test/utils/forward-retrier.test.ts
  yarn.lock
Labels: automerge:rebase, bypass:integration

#11426 test(a3p-integration): update to `agoric-upgrade-20`
  a3p-integration/package.json
  a3p-integration/proposals/m:before-upgrade-next/test/initial.test.js
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/test-lib/provision-helpers.js
  a3p-integration/proposals/n:upgrade-next/test/depositUSD-LEMONS/deposit-usd-lemons-permit.json
  a3p-integration/proposals/n:upgrade-next/test/depositUSD-LEMONS/deposit-usd-lemons.js
  a3p-integration/proposals/n:upgrade-next/test/initial.test.js
  a3p-integration/proposals/n:upgrade-next/test/provisionPool.test.js
  golang/cosmos/app/upgrade.go
Labels: automerge:rebase, force:integration

#11429 Async flight recorder reads
  packages/telemetry/src/flight-recorder.js
  packages/telemetry/src/frcat-entrypoint.js
  packages/telemetry/test/flight-recorder.test.js
Labels: automerge:rebase
