Repository Agoric/agoric-sdk, pull requests merged in 2025-04, with the labels that each got.

#11200 ci(cosmic-swingset): disable rosetta test
  packages/cosmic-swingset/test/make.test.ts
Labels: automerge:squash, bypass:integration

#11156 chore(liveslots): remove unnecessary `promiseRegistrations`
  packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
  packages/SwingSet/test/virtualObjects/representatives.test.js
  packages/swingset-liveslots/src/watchedPromises.js
  packages/swingset-liveslots/test/gc-helpers.js
  packages/swingset-liveslots/test/handled-promises.test.js
  packages/swingset-liveslots/test/initial-vrefs.test.js
  packages/swingset-liveslots/test/liveslots-real-gc.test.js
  packages/swingset-liveslots/test/liveslots.test.js
  packages/swingset-liveslots/test/storeGC/lifecycle.test.js
  packages/swingset-liveslots/test/virtual-objects/virtualObjectManager.test.js
Labels: automerge:squash

#11196 feat(fusdc): `.depositForBurn` in `Forward` path
  packages/fast-usdc-contract/README.md
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/src/utils/cctp.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/fixtures.ts
  packages/fast-usdc-contract/test/mocks.ts
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc-contract/test/supports.ts
  packages/fast-usdc-contract/test/utils/cctp.test.ts
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  packages/fast-usdc/tools/mock-evidence.ts
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
Labels: automerge:rebase, force:integration

#11207 ci: free up disk space in acceptance fork test
  a3p-integration/proposals/z:acceptance/test/genesis-test.sh
Labels: automerge:rebase

#11204 test(cosmic-swingset): Add more fuzziness for comparing "heapStats_*" metrics
  packages/cosmic-swingset/test/prometheus.test.ts
Labels: automerge:squash

#11215 CAIP-10 EUDs
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/mocks.ts
  packages/fast-usdc-deploy/package.json
  packages/fast-usdc-deploy/src/update-fee-config.core.js
  packages/fast-usdc-deploy/src/update-settler-reference.core.js
  packages/fast-usdc-deploy/src/upgrade-evm-solana.core.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/chain-info.js
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/snapshots/exports.test.ts.md
  packages/orchestration/test/snapshots/exports.test.ts.snap
Labels: automerge:rebase, force:integration

#11217 fix(ci): docker-build-test failing with out of disk error
  .github/workflows/integration.yml
Labels: automerge:rebase, force:integration

#11100 test coverage over bundles
  packages/SwingSet/src/types-external.js
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/inter-protocol/test/psm/psm.test.js
  packages/inter-protocol/test/psm/snapshots/psm.test.js.md
  packages/inter-protocol/test/psm/snapshots/psm.test.js.snap
  packages/orchestration/test/examples/auto-stake-it.contract.test.ts
  packages/orchestration/test/examples/basic-flows.contract.test.ts
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/examples/send-cctp.test.ts
  packages/orchestration/test/examples/stake-bld.contract.test.ts
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/orchestration/test/examples/staking-combinations.test.ts
  packages/orchestration/test/examples/swap.contract.test.ts
  packages/orchestration/test/examples/unbond.contract.test.ts
  packages/orchestration/test/fixtures/query-flows.contract.test.ts
  packages/orchestration/test/utils/zoe-tools.test.ts
  packages/vats/test/bootstrapPayment.test.js
  packages/zoe/tools/fakeVatAdmin.js
  packages/zoe/tools/setup-zoe.js
  patches/@endo+import-bundle+1.4.0.patch
Labels: automerge:rebase

#11208 feat: custom `FeeConfig` per destination with optional `relay: Amount<'nat'>`
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/src/exos/liquidity-pool.ts
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-contract/test/supports.ts
  packages/fast-usdc-deploy/src/fast-usdc-evm-dests.build.js
  packages/fast-usdc-deploy/src/upgrade-evm-dests.core.js
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.md
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/fees.js
  packages/fast-usdc/test/pool-share-math.test.ts
  packages/fast-usdc/test/utils/fees.test.ts
  packages/orchestration/src/utils/address.js
  packages/orchestration/test/utils/address.test.ts
Labels: automerge:rebase

#11203 fix(multichain): find agoric CLI using npx
  multichain-testing/tools/deploy.ts
Labels: automerge:rebase, force:integration

#11194 test(orchestration): CCTP address encoding fixtures based on observed traffic
  multichain-testing/scripts/cctp-lab.ts
  multichain-testing/yarn.lock
  packages/orchestration/package.json
  packages/orchestration/src/utils/address.js
  packages/orchestration/test/utils/address.test.ts
  yarn.lock
Labels: automerge:rebase

#11206 smaller FUSDC build
  package.json
  packages/cosmic-proto/package.json
  packages/cosmic-proto/scripts/codegen.cjs
  packages/cosmic-proto/scripts/minify.cjs
  packages/cosmic-proto/tsconfig.build.json
  packages/cosmic-proto/tsconfig.json
  packages/fast-usdc-deploy/package.json
  scripts/report-globals.ts
  yarn.lock
Labels: automerge:rebase

#11209 feat(cosmos): `IBCPacket` type that round-trips to JS
  golang/cosmos/app/upgrade.go
  golang/cosmos/app/upgrade_test.go
  golang/cosmos/types/address_hooks.go
  golang/cosmos/types/address_hooks_test.go
  golang/cosmos/types/codec.go
  golang/cosmos/types/ibc_packet.go
  golang/cosmos/types/ibc_packet_test.go
  golang/cosmos/x/vibc/keeper/triggers.go
  golang/cosmos/x/vibc/types/expected_keepers.go
  golang/cosmos/x/vibc/types/ibc_module.go
  golang/cosmos/x/vibc/types/receiver.go
  golang/cosmos/x/vtransfer/ibc_middleware_test.go
  golang/cosmos/x/vtransfer/keeper/keeper.go
  multichain-testing/scripts/fund-provision-pool.ts
  multichain-testing/test/deposit-withdraw-lca.test.ts
  multichain-testing/tools/e2e-tools.js
  packages/boot/tools/ibc/mocks.ts
  packages/builders/scripts/vats/upgrade-orchestration.js
  packages/builders/scripts/vats/upgrade-vats.js
  packages/orchestration/test/network-fakes.ts
  packages/vats/src/ibc.js
  packages/vats/src/types.ts
Labels: automerge:no-update, agd, IBC

#11223 refactorings to support AccountId pervasively
  multichain-testing/test/fast-usdc/noble-forwarding.test.ts
  packages/boot/tools/drivers.ts
  packages/cosmic-proto/src/address-hooks.js
  packages/cosmic-proto/test/address-hooks.test.js
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-contract/test/fixtures.ts
  packages/fast-usdc/tools/mock-evidence.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/ica-account-kit.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/cosmos.js
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/orchestration/test/exos/chain-hub-transfer-routes.test.ts
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/exos/make-test-coa-kit.ts
  packages/orchestration/test/exos/make-test-loa-kit.ts
  packages/orchestration/test/ibc-mocks.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/tools/ibc-mocks.ts
  packages/orchestration/tools/make-test-address.js
  packages/vats/src/localchain.js
Labels: automerge:rebase

#11174 252 fu cctp
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/fixtures.ts
  packages/fast-usdc-contract/test/supports.ts
  packages/fast-usdc/tools/mock-evidence.ts
Labels: automerge:rebase, orchestration

#11232 deployment test of CCTP feature
  packages/boot/package.json
  packages/boot/tools/supports.ts
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.md
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.snap
Labels: automerge:rebase, bypass:integration

#11216 feat(swingset-liveslots): Support adding optional top-level fields to stateShape records
  packages/swingset-liveslots/src/types.js
  packages/swingset-liveslots/src/virtualObjectManager.js
  packages/swingset-liveslots/test/util.js
  packages/swingset-liveslots/test/virtual-objects/state-shape.test.js
  packages/zone/test/exos.test.js
Labels: automerge:rebase

#11236 multichain test refactorings
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  packages/client-utils/src/types.d.ts
  packages/deployment/Dockerfile
  packages/fast-usdc-deploy/src/start-fast-usdc.core.js
  packages/fast-usdc-deploy/src/utils/deploy-config.js
  packages/fast-usdc/src/types.ts
Labels: automerge:rebase, force:integration

#10979 bump non-matrixed CI jobs from Node 18 to 20
  .github/workflows/after-merge.yml
  .github/workflows/benchmarks.yml
  .github/workflows/dump-ci-stats.yml
  .github/workflows/integration.yml
  .github/workflows/multichain-e2e-template.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-documentation.yml
  packages/deployment/Dockerfile.sdk
  packages/deployment/ansible/prepare-machine.yml
  packages/fast-usdc/package.json
  packages/fast-usdc/test/cli/cli.test.ts
  yarn.lock
Labels: automerge:rebase

#11250 test(liveslots): retry storeGC lifecycle tests
  packages/swingset-liveslots/test/storeGC/lifecycle.test.js
Labels: automerge:squash

#11242 fix vow handling
  eslint.config.mjs
  packages/boot/tools/supports.ts
  packages/client-utils/src/types.d.ts
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/src/exos/liquidity-pool.ts
  packages/fast-usdc-contract/src/exos/operator-kit.ts
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  packages/fast-usdc/src/types.ts
  packages/orchestration/src/exos/packet-tools.js
Labels: automerge:rebase

#8699 Simplify typeGuards that allow instanceHandle or Bundle
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/installationStorage.js
Labels: Zoe, code-style, automerge:rebase

#11241 chore: Improve some doc comments
  golang/cosmos/types/codec.go
  packages/vats/src/ibc.js
Labels: automerge:no-update

#10739 clean up liveslots tests
  packages/SwingSet/test/vo-test-harness/dvo-test-harness.test.js
  packages/swingset-liveslots/test/vo-test-harness.test.js
  packages/swingset-liveslots/tools/vo-test-harness.js
Labels: automerge:rebase, bypass:integration

#11224 chore(orchestration): trace sequence on IBC packet send
  packages/orchestration/src/exos/ibc-packet.js
  packages/orchestration/src/exos/packet-tools.js
Labels: automerge:rebase

#11233 test(a3p-integration): update to agoric-upgrade-19
  a3p-integration/package.json
  a3p-integration/proposals/n:upgrade-next/eval.sh
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/test-lib/index.js
  a3p-integration/proposals/n:upgrade-next/test-lib/mintHolder-helpers.js
  a3p-integration/proposals/n:upgrade-next/test-lib/price-feed.js
  a3p-integration/proposals/n:upgrade-next/test-lib/provision-helpers.js
  a3p-integration/proposals/n:upgrade-next/test-lib/psm-lib.js
  a3p-integration/proposals/n:upgrade-next/test-lib/utils.js
  a3p-integration/proposals/n:upgrade-next/test/addCollateral/add-collateral-permit.json
  a3p-integration/proposals/n:upgrade-next/test/addCollateral/add-collateral.js
  a3p-integration/proposals/n:upgrade-next/test/agoricNames.test.js
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/depositUsdOlives/deposit-usd-olives-permit.json
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/depositUsdOlives/deposit-usd-olives.js
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/writeToAgoricNames/write-to-agoricNames-permit.json
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/writeToAgoricNames/write-to-agoricNames.js
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/writeToTestInfo/write-to-testInfo-permit.json
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/writeToTestInfo/write-to-testInfo.js
  a3p-integration/proposals/n:upgrade-next/test/assetReserve.test.js
  a3p-integration/proposals/n:upgrade-next/test/depositUSD-LEMONS/deposit-usd-lemons-permit.json
  a3p-integration/proposals/n:upgrade-next/test/depositUSD-LEMONS/deposit-usd-lemons.js
  a3p-integration/proposals/n:upgrade-next/test/initial.test.js
  a3p-integration/proposals/n:upgrade-next/test/mint-payment/send-script-permit.json
  a3p-integration/proposals/n:upgrade-next/test/mint-payment/send-script.tjs
  a3p-integration/proposals/n:upgrade-next/test/mintHolder.test.js
  a3p-integration/proposals/n:upgrade-next/test/nullUpgradePP/null-upgrade-pp-permit.json
  a3p-integration/proposals/n:upgrade-next/test/nullUpgradePP/null-upgrade-pp.js
  a3p-integration/proposals/n:upgrade-next/test/provisionPool.test.js
  a3p-integration/proposals/n:upgrade-next/test/psm.test.js
  a3p-integration/proposals/n:upgrade-next/test/replaceFeeDistributor.test.js
  a3p-integration/proposals/n:upgrade-next/test/swapAnchorForMintedSeat/swap-anchor-for-minted-seat-permit.json
  a3p-integration/proposals/n:upgrade-next/test/swapAnchorForMintedSeat/swap-anchor-for-minted-seat.js
  golang/cosmos/app/upgrade.go
Labels: automerge:rebase, force:integration

#11261 test: fast-usdc-cctp
  a3p-integration/proposals/f:fast-usdc-cctp/.yarnrc.yml
  a3p-integration/proposals/f:fast-usdc-cctp/README.md
  a3p-integration/proposals/f:fast-usdc-cctp/package.json
  a3p-integration/proposals/f:fast-usdc-cctp/test.sh
  a3p-integration/proposals/f:fast-usdc-cctp/test/deploy.test.js
  a3p-integration/proposals/f:fast-usdc-cctp/test/test-cli.sh
  a3p-integration/proposals/f:fast-usdc-cctp/yarn.lock
Labels: automerge:rebase, force:integration

#11263 chore(orchestration): Fix lint warnings
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/test/utils/address.test.ts
Labels: automerge:squash

#11267 Update all orchestration vats
  a3p-integration/.yarnrc.yml
  a3p-integration/package.json
  a3p-integration/proposals/f:fast-usdc-cctp/package.json
  a3p-integration/proposals/f:fast-usdc-cctp/test/deploy.test.js
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/test/initial.test.js
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/yarn.lock
  a3p-integration/yarn.lock
  golang/cosmos/app/upgrade.go
  multichain-testing/package.json
Labels: automerge:rebase

#11247 feat: Add terminate-governed-instance.js proposal
  a3p-integration/proposals/z:acceptance/yarn.lock
  multichain-testing/yarn.lock
  packages/boot/package.json
  packages/boot/test/bootstrapTests/terminate-governed.test.ts
  packages/boot/tools/supports.ts
  packages/builders/scripts/vats/terminate-governor-instance.js
  packages/governance/test/swingsetTests/contractGovernor/add-governedContract.js
  packages/governance/test/swingsetTests/contractGovernor/governedContract.js
  packages/internal/package.json
  packages/internal/src/module-utils.js
  packages/vats/src/proposals/terminate-governed-instance.js
Labels: automerge:rebase

#11254 fix: replace `abci_query` RPC `custom/...` path with `/agoric/...`
  a3p-integration/proposals/z:acceptance/yarn.lock
  golang/cosmos/x/vstorage/README.md
  golang/cosmos/x/vstorage/types/path_keys.go
  multichain-testing/yarn.lock
  packages/agoric-cli/package.json
  packages/agoric-cli/test/inter-cli.test.js
  packages/client-utils/package.json
  packages/client-utils/src/vstorage.js
  packages/client-utils/test/vstorage-kit.test.js
  packages/inter-protocol/test/auction/README-bidding-cli.md
  packages/internal/src/hex.js
  packages/solo/package.json
  packages/solo/src/chain-cosmos-sdk.js
Labels: automerge:no-update, force:integration

#11275 make fast-usdc multichain tests repeatable
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/fast-usdc/fu-actors.ts
  multichain-testing/test/fast-usdc/mocks.test.ts
  multichain-testing/test/fast-usdc/mocks.ts
  multichain-testing/tools/agd-lib.js
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/sleep.ts
Labels: automerge:rebase

#11260 ci: use depot runners
  .github/workflows/integration.yml
  .github/workflows/multichain-e2e-template.yml
Labels: automerge:squash, force:integration

#11269 Upgrade vat-bank
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/test-lib/provision-helpers.js
  a3p-integration/proposals/n:upgrade-next/test/depositUSD-LEMONS/deposit-usd-lemons-permit.json
  a3p-integration/proposals/n:upgrade-next/test/depositUSD-LEMONS/deposit-usd-lemons.js
  a3p-integration/proposals/n:upgrade-next/test/initial.test.js
  a3p-integration/proposals/n:upgrade-next/test/provisionPool.test.js
  golang/cosmos/app/upgrade.go
Labels: automerge:rebase, force:integration

#11279 feat(cosmos): Next upgrade is agoric-upgrade-20
  a3p-integration/proposals/a:upgrade-20/.gitignore
  a3p-integration/proposals/a:upgrade-20/.yarn/patches/axios-npm-1.7.7-cfbedc233d.patch
  a3p-integration/proposals/a:upgrade-20/.yarn/patches/protobufjs-npm-6.11.4-af11968b80.patch
  a3p-integration/proposals/a:upgrade-20/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-20/README.md
  a3p-integration/proposals/a:upgrade-20/package.json
  a3p-integration/proposals/a:upgrade-20/test-lib/provision-helpers.js
  a3p-integration/proposals/a:upgrade-20/test.sh
  a3p-integration/proposals/a:upgrade-20/test/depositUSD-LEMONS/deposit-usd-lemons-permit.json
  a3p-integration/proposals/a:upgrade-20/test/depositUSD-LEMONS/deposit-usd-lemons.js
  a3p-integration/proposals/a:upgrade-20/test/initial.test.js
  a3p-integration/proposals/a:upgrade-20/test/provisionPool.test.js
  a3p-integration/proposals/a:upgrade-20/tsconfig.json
  a3p-integration/proposals/a:upgrade-20/yarn.lock
  a3p-integration/proposals/n:upgrade-next/README.md
  golang/cosmos/app/app.go
  golang/cosmos/app/upgrade.go
Labels: force:integration

#11158 SwingSet tools for load testing contracts
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/test/reap-all/bootstrap-reap-all.js
  packages/SwingSet/test/reap-all/reap-all.test.js
  packages/SwingSet/test/reap-all/vat-dumbo.js
  packages/SwingSet/test/vat-warehouse/reload-snapshot.test.js
  packages/SwingSet/test/vat-warehouse/vat-warehouse-reload.js
  packages/boot/tools/supports.ts
Labels: automerge:rebase

#11289 chore: update EVM dest fees; test against product spreadsheet
  packages/fast-usdc-deploy/src/upgrade-evm-dests.core.js
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.md
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc-deploy/test/utils/fee-dest.test.ts
  packages/fast-usdc/src/type-guards.js
Labels: automerge:rebase

#11292 test: cctp configuration in `multichain-testing`
  multichain-testing/README.md
  multichain-testing/config.fusdc.go-relayer.yaml
  multichain-testing/config.fusdc.yaml
  multichain-testing/config.go-relayer.yaml
  multichain-testing/config.yaml
  multichain-testing/scripts/cctp-lab.ts
  multichain-testing/scripts/noble-update-genesis.sh
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
Labels: automerge:rebase, force:integration

#11294 fix(swing-store): Update archiveTranscript to wait for write stream conclusion
  packages/swing-store/package.json
  packages/swing-store/src/archiver.js
Labels: automerge:squash

#11234 test of Ethereum destination in Fast USDC
  multichain-testing/ava.config.js
  multichain-testing/scripts/install.sh
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/support.ts
  multichain-testing/test/tools/asset-info.test.ts
  multichain-testing/tools/asset-info.ts
  multichain-testing/tools/ibc-transfer.ts
  multichain-testing/tools/sleep.ts
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
Labels: automerge:rebase, force:integration

#11300 bump deps
  package.json
  packages/access-token/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/client-utils/package.json
  packages/cosmic-swingset/package.json
  packages/create-dapp/package.json
  packages/fast-usdc-contract/package.json
  packages/fast-usdc-deploy/package.json
  packages/fast-usdc/package.json
  packages/governance/package.json
  packages/import-manager/package.json
  packages/inter-protocol/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/swing-store/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/vats/package.json
  packages/vm-config/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/package.json
  packages/zoe/package.json
  yarn.lock
Labels: automerge:rebase

#11295 fix: forward timeout longer (10m) than advance timeout
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/utils/time.js
  packages/orchestration/test/utils/time.test.ts
Labels: automerge:rebase

#11301 types for Timer device and vat
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/src/devices/bridge/device-bridge.js
  packages/SwingSet/src/devices/timer/device-timer.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/vats/plugin-manager.js
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/SwingSet/src/vats/vat-admin/vat-vat-admin.js
  packages/SwingSet/tools/manual-timer.js
  packages/access-token/package.json
  packages/agoric-cli/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/inter-protocol/test/smartWallet/boot-test-utils.js
  packages/internal/package.json
  packages/orchestration/package.json
  packages/solo/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/vats/package.json
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/tools/boot-test-utils.js
  packages/vow/package.json
  packages/zoe/package.json
  packages/zone/package.json
Labels: automerge:rebase

#11308 feat(cosmic-swingset): Add helper function scanVatStore to inquisitor.mjs
  packages/cosmic-swingset/tools/inquisitor.mjs
Labels: automerge:rebase

#11311 fix type resolution regression in registry test
  packages/inter-protocol/src/proposals/econ-behaviors.js
Labels: automerge:rebase, bypass:integration

#11313 fix async assertions in multichain-testing
  multichain-testing/test/devex.test.ts
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
Labels: automerge:rebase

#11248 test: chain impact of Fast USDC w/CCTP
  packages/SwingSet/misc-tools/vat-map.py
  packages/boot/tools/supports.ts
  packages/fast-usdc-deploy/package.json
  packages/fast-usdc-deploy/test/chain-impact.test.ts
  packages/fast-usdc-deploy/test/fu-sim-iter.ts
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/types-index.d.ts
Labels: automerge:rebase

#11312 chore: do not write chain info to vstorage
  .github/workflows/multichain-e2e-template.yml
  multichain-testing/Makefile
  multichain-testing/config.fusdc.go-relayer.yaml
  multichain-testing/config.fusdc.yaml
  multichain-testing/config.go-relayer.yaml
  multichain-testing/config.yaml
  multichain-testing/test/fast-usdc/noble-forwarding.test.ts
  multichain-testing/test/queries/account-balance-queries.test.ts
  multichain-testing/test/queries/chain-queries.test.ts
  multichain-testing/test/staking/stake-ica.test.ts
  packages/boot/test/bootstrapTests/vow-offer-results.test.ts
  packages/boot/test/orchestration/contract-upgrade.test.ts
  packages/boot/test/orchestration/lca.test.ts
  packages/boot/test/orchestration/orchestration.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/boot/test/orchestration/snapshots/vstorage-chain-info.test.ts.md
  packages/boot/test/orchestration/snapshots/vstorage-chain-info.test.ts.snap
  packages/boot/test/orchestration/vstorage-chain-info.test.ts
  packages/builders/scripts/orchestration/helpers.js
  packages/builders/scripts/orchestration/init-basic-flows.js
  packages/builders/scripts/orchestration/init-stakeAtom.js
  packages/builders/scripts/orchestration/init-stakeOsmo.js
  packages/builders/scripts/testing/init-auto-stake-it.js
  packages/builders/scripts/testing/init-send-anywhere.js
  packages/builders/scripts/testing/start-query-flows.js
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/stake-ica.contract.js
  packages/orchestration/src/fixtures/query-flows.contract.js
  packages/orchestration/src/proposals/start-stakeAtom.js
  packages/orchestration/src/proposals/start-stakeOsmo.js
Labels: automerge:rebase, force:integration

#11314 feat(base-zone): attenuator as simplified revocable
  packages/base-zone/src/prepare-attenuator.js
  packages/base-zone/src/prepare-revocable.js
  packages/base-zone/test/prepare-attenuator.test.js
Labels: automerge:squash

#11307 ForwardSkipped and refactorings for retry
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  packages/fast-usdc-contract/README.md
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/src/exos/status-manager.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/src/fast-usdc.flows.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/mocks.ts
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/src/constants.js
Labels: automerge:rebase, force:integration

#11298 chore: refactor `enumeratePrefixedKeys` to return `{ key, suffix }`
  packages/SwingSet/src/controller/upgradeSwingset.js
  packages/SwingSet/src/kernel/state/deviceKeeper.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/storageHelper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/test/state.test.js
  packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
  packages/SwingSet/test/vat-admin/terminate/terminate.test.js
  packages/SwingSet/test/virtualObjects/representatives.test.js
Labels: automerge:squash, force:integration

#11315 fix(base-zone): Oops. Forgot to export `prepareAttenuatorMaker`
  packages/base-zone/zone-helpers.js
Labels: automerge:squash

#11221 bump better-sqlite to v11
  a3p-integration/package.json
  a3p-integration/proposals/m:before-upgrade-next/package.json
  a3p-integration/proposals/m:before-upgrade-next/yarn.lock
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/z:acceptance/setup-test.sh
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/yarn.lock
  a3p-integration/yarn.lock
  multichain-testing/yarn.lock
  packages/SwingSet/package.json
  packages/cosmic-swingset/package.json
  packages/deployment/package.json
  packages/swing-store/package.json
  packages/telemetry/package.json
  yarn.lock
Labels: automerge:squash, force:integration

#11318 repair transfer timeout tests
  packages/orchestration/src/exos/ibc-packet.js
  packages/orchestration/src/exos/packet-tools.js
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/staking-combinations.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/tools/ibc-mocks.ts
  packages/vats/src/types.ts
  packages/vats/tools/fake-bridge.js
Labels: automerge:rebase

#11243 refactor: move some type imports to @import
  packages/ERTP/src/issuerKit.js
  packages/ERTP/src/paymentLedger.js
  packages/SwingSet/src/types-external.js
  packages/pegasus/src/contract.js
  packages/vats/src/core/types-ambient.d.ts
  packages/vats/src/vat-mints.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contracts/loan/liquidate.js
  packages/zoe/src/instanceRecordStorage.js
  packages/zoe/src/internal-types.js
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/feeMint.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/originalZoeSeat.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/zoe.js
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/privateArgsUsageContract.js
  packages/zoe/test/swingsetTests/brokenContracts/crashingAutoRefund.js
  packages/zoe/test/unitTests/contracts/brokenAutoRefund.js
  packages/zoe/test/unitTests/contracts/two-invitations.js
Labels: automerge:squash

#11330 preparations for forward retry
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/test/contract-setup.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-contract/test/forwarding.test.ts
  packages/fast-usdc-contract/test/supports.ts
  packages/orchestration/src/utils/chain-hub-helper.js
  packages/orchestration/test/supports.ts
  packages/store/src/stores/scalarMapStore.js
  packages/vats/src/vat-bank.js
  packages/vats/src/virtual-purse.js
  packages/vats/tools/bank-utils.js
Labels: automerge:rebase, force:integration

#11333 docs(orchestration): getBalances @throws when prohibited by chain
  packages/orchestration/src/orchestration-api.ts
Labels: automerge:rebase

#11331 refactor(base-zone): attenuator and revocable share common code
  packages/base-zone/src/prepare-attenuator.js
  packages/base-zone/src/prepare-revocable.js
  packages/base-zone/test/prepare-attenuator.test.js
  packages/zoe/src/contractSupport/prepare-ownable.js
  packages/zoe/test/unitTests/contracts/ownable-counter.test.js
Labels: automerge:squash

#11327 refactor: use endo `getMethodNames` rather than agoric-sdk placeholder
  a3p-integration/proposals/z:acceptance/yarn.lock
  multichain-testing/yarn.lock
  packages/governance/src/contractHelper.js
  packages/internal/package.json
  packages/internal/src/method-tools.js
  packages/orchestration/package.json
  packages/orchestration/src/exos/combine-invitation-makers.js
  packages/orchestration/test/cosmos-interchain-service.test.ts
Labels: automerge:squash

#11340 refactor(base-zone): Fix Remotable debug prefix stripping in `attenuateOne`
  packages/base-zone/src/prepare-attenuator.js
Labels: automerge:squash
