Repository Agoric/agoric-sdk, pull requests merged in 2025-07, with the labels that each got.

#11549 fix: decimalPlaces: 0 for poc token; bump from 24/25 to 26
  .gemini/config.yaml
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/test/ymax0/ymax-deploy.test.ts
  packages/portfolio-contract/test/contract-setup.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-deploy/src/access-token-setup.core.js
  packages/portfolio-deploy/src/portfolio-start.core.js
  packages/portfolio-deploy/src/portfolio-start.type.ts
  packages/portfolio-deploy/src/portfolio.contract.permit.js
  packages/portfolio-deploy/test/portfolio-start.core.test.ts
  packages/portfolio-deploy/test/portfolio.test.ts
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.snap
Labels: automerge:rebase, ymax

#11541 feat(localchain): support `x/bank` `MsgSend` address hooks and taps
  a3p-integration/proposals/h:hook-msg-send/.yarnrc.yml
  a3p-integration/proposals/h:hook-msg-send/README.md
  a3p-integration/proposals/h:hook-msg-send/package.json
  a3p-integration/proposals/h:hook-msg-send/test.sh
  a3p-integration/proposals/h:hook-msg-send/test/deploy.test.js
  a3p-integration/proposals/h:hook-msg-send/yarn.lock
  a3p-integration/proposals/m:before-upgrade-next/test/initial.test.js
  a3p-integration/proposals/n:upgrade-next/test/initial.test.js
  a3p-integration/proposals/z:acceptance/test/localchain.test.js
  packages/builders/scripts/orchestration/hook-localchain-msg-send.js
  packages/cosmic-proto/src/address-hooks.js
  packages/cosmic-proto/test/address-hooks.test.js
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/tools/contract-tests.ts
  packages/orchestration/tools/ibc-mocks.ts
  packages/vats/src/bridge-target.js
  packages/vats/src/localchain.js
  packages/vats/src/proposals/localchain-hook-msg-send.js
  packages/vats/src/proposals/localchain-proposal.js
  packages/vats/src/proposals/localchain-test.js
  packages/vats/src/proposals/upgrade-vats-generic-proposal.js
  packages/vats/src/types.ts
  packages/vats/src/vat-localchain.js
  packages/vats/test/bridge-target.test.js
  packages/vats/test/localchain.test.js
  packages/vats/test/snapshots/bridge-target.test.js.md
  packages/vats/test/snapshots/bridge-target.test.js.snap
Labels: automerge:no-update, force:integration, orchestration, ymax

#11551 Update/Fix `ymax` Multichain-testing Deploy-Test
  multichain-testing/Makefile
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/test/ymax0/ymax-deploy.test.ts
Labels: automerge:rebase, force:integration, ymax

#11558 chore(multichain-testing): `ymax0` tweaks
  multichain-testing/Makefile
  multichain-testing/scripts/noble-v10-update-genesis.sh
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/test/ymax0/ymax-deploy.test.ts
Labels: automerge:no-update, ymax

#11567 chore: hardcode aave addresses and remove @bgd-labs/aave-address-book
  packages/portfolio-deploy/package.json
  packages/portfolio-deploy/src/axelar-configs.js
  yarn.lock
Labels: automerge:rebase, ymax

#11571 refactor: factor our USDN / Aave / Compound specific stuff
  packages/portfolio-contract/CONTRIBUTING.md
  packages/portfolio-contract/README.md
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.exo.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/pos-usdn.exo.ts
  packages/portfolio-contract/src/pos-usdn.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
Labels: automerge:rebase, bypass:integration, ymax

#11578 fix(multichain-testing): Import `makeSwapLockMessages` from the new location
  multichain-testing/scripts/noble-usdn-lab.ts
Labels: automerge:squash

#11577 chore(portfolio-contract): index positions by PoolKey, not number
  packages/portfolio-contract/src/constants.js
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.exo.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/pos-usdn.exo.ts
  packages/portfolio-contract/src/pos-usdn.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/portfolio-actors.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.snap
Labels: automerge:rebase, bypass:integration, ymax

#11576 feat(internal)!: Add helper `toCLIOptions`
  multichain-testing/package.json
  multichain-testing/tools/chaind-lib.js
  multichain-testing/tools/deploy.ts
  multichain-testing/tools/e2e-tools.js
  multichain-testing/yarn.lock
  packages/deploy-script-support/src/permissioned-deployment.js
  packages/internal/src/cli-utils.js
  packages/internal/src/index.js
  packages/internal/test/cli-utils.test.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/orchestration/src/utils/agd-lib.js
  packages/pola-io/package.json
  packages/pola-io/src/cmd.js
  packages/pola-io/test/snapshots/exports.test.js.md
  packages/pola-io/test/snapshots/exports.test.js.snap
  packages/portfolio-deploy/scripts/deploy-cli.ts
  yarn.lock
Labels: automerge:rebase

#11559 Changes to Multichain-Testing to Pass `portfolio-opened` and `usdc-available`
  multichain-testing/Makefile
  multichain-testing/scripts/ymax-tool.ts
Labels: automerge:rebase, ymax

#11579 chore(portfolio-contract): separate GMP Account from Position
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.exo.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/pos-usdn.exo.ts
  packages/portfolio-contract/src/pos-usdn.flows.ts
  packages/portfolio-contract/src/pos.exo.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
Labels: automerge:rebase, bypass:integration, ymax

#11572 ci(restore-node): fix caching problems
  .github/actions/restore-node/action.yml
Labels: tooling, automerge:no-update

#11586 fix(ci): Increase node process memory when collecting test coverage in `after-merge` workflow
  .github/workflows/after-merge.yml
  scripts/ci/generate-test-coverage-report.sh
Labels: automerge:squash

#11591 refactor: disambiguate axelar chain IDs from internal names
  packages/orchestration/src/cctp-chain-info.js
  packages/portfolio-contract/src/constants.js
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/contract-setup.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-contract/test/ymax-scenario.test.ts
  packages/portfolio-deploy/src/axelar-configs.js
  packages/portfolio-deploy/src/chain-info.build.js
  packages/portfolio-deploy/src/chain-info.core.js
  packages/portfolio-deploy/src/orch.start.js
  packages/portfolio-deploy/src/portfolio-start.core.js
  packages/portfolio-deploy/src/portfolio.build.js
  packages/portfolio-deploy/test/portfolio-start.core.test.ts
  packages/portfolio-deploy/test/portfolio.test.ts
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.snap
Labels: automerge:rebase, ymax

#11590 feat: offer specifies a flow as a sequence of steps
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/test/ymax0/ymax-deploy.test.ts
  packages/portfolio-contract/README.md
  packages/portfolio-contract/src/constants.js
  packages/portfolio-contract/src/evm-facade.ts
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/pos-usdn.flows.ts
  packages/portfolio-contract/src/type-guards-steps.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/contract-setup.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/move-cases.csv
  packages/portfolio-contract/test/offer-shapes.test.ts
  packages/portfolio-contract/test/open-pos-usdn.mmd
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/rebalance-cases.csv
  packages/portfolio-contract/test/rebalance-grok.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-contract/test/ymax-scenario.test.ts
  packages/portfolio-contract/tools/portfolio-actors.ts
  packages/portfolio-contract/tools/rebalance-grok.ts
  packages/portfolio-contract/tools/wallet-offer-tools.ts
  packages/portfolio-contract/tsconfig.json
  packages/portfolio-deploy/src/portfolio-start.core.js
  packages/portfolio-deploy/src/portfolio.build.js
  packages/portfolio-deploy/src/portfolio.contract.permit.js
  packages/portfolio-deploy/test/portfolio-start.core.test.ts
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.snap
Labels: automerge:rebase, bypass:integration, ymax

#11604 feat: ymax0 withdraw from USDN, Aave, Compound
  packages/portfolio-contract/src/evm-facade.ts
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/pos-usdn.flows.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/move-cases.csv
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/rebalance-grok.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/test/ymax-scenario.test.ts
  packages/portfolio-contract/tools/rebalance-grok.ts
  packages/portfolio-deploy/src/axelar-configs.js
  packages/portfolio-deploy/test/portfolio-start.core.test.ts
Labels: automerge:rebase, bypass:integration, ymax

#11607 build: update deploy-cli.ts to accept multiple peers
  packages/deploy-script-support/src/permissioned-deployment.js
  packages/portfolio-deploy/scripts/deploy-cli.ts
  packages/portfolio-deploy/src/chain-info.build.js
Labels: automerge:rebase

#11612 chore(portfolio-deploy): shrink aux bundle from 2,268K to 708K
  packages/portfolio-deploy/src/chain-name-service.js
Labels: automerge:rebase, ymax

#11620 docs(portfolio-contract): Commit Messages w.r.t. Last Release
  packages/portfolio-contract/CHANGELOG.md
  packages/portfolio-contract/CONTRIBUTING.md
Labels: automerge:rebase, bypass:integration

#11621 feat(portfolio-contract): set target allocation
  multichain-testing/package.json
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/test/ymax0/ymax-deploy.test.ts
  packages/portfolio-contract/CONTRIBUTING.md
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/type-guards-steps.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/offer-shapes.test.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/rebalance-grok.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/test/target-allocation.test.ts
  packages/portfolio-contract/tools/portfolio-actors.ts
Labels: automerge:rebase, bypass:integration

#11603 feat(portfolio-contract): claim rewards on Aave, Compound
  packages/portfolio-contract/src/evm-facade.ts
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/pos-usdn.flows.ts
  packages/portfolio-contract/src/type-guards-steps.ts
  packages/portfolio-contract/test/abi-utils.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-deploy/src/axelar-configs.js
Labels: automerge:rebase

#11655 chore(deps): use `@lerna-lite` instead
  .yarn/patches/@lerna-lite-version-npm-4.6.1-77cc9b6d7e.patch
  .yarn/patches/@types-glob-npm-8.1.0-bdb9d0520c.patch
  lerna.json
  package.json
  packages/xsnap/package.json
  yarn.lock
Labels: tooling, automerge:no-update, force:integration

#11657 feat: beefy protocol for ymax
  packages/portfolio-contract/src/constants.js
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-deploy/src/axelar-configs.js
  packages/portfolio-deploy/src/beefy-configs.js
Labels: automerge:rebase

#11667 fix(portfolio-contract): don't make new storage nodes on each update
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/test/portfolio.exo.test.ts
Labels: performance, automerge:rebase, bypass:integration, ymax

#11583 docs(portfolio-contract): create sequence diagrams for several user stories
  packages/portfolio-contract/DESIGN-BETA.md
Labels: automerge:squash, bypass:integration, ymax
