Repository Agoric/agoric-sdk, pull requests merged in 2025-02, with the labels that each got.

#10864 chore: Replace otel-trace with otel-context-aware-slog in integration test
  packages/deployment/scripts/integration-test.sh
Labels: automerge:squash, force:integration

#10881 chore(multichain-testing): remove starship repo from helm context on `make clean`
  multichain-testing/Makefile
Labels: automerge:rebase

#10320 chore: Move natural-sort functionality into packages/internal
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/internal/src/natural-sort.js
  packages/swingset-runner/src/dumpstore.js
Labels: automerge:rebase

#10922 deps cleanup
  README.md
  packages/agoric-cli/package.json
  yarn.lock
Labels: automerge:rebase

#7914 remove start-local-chain
  packages/agoric-cli/test/agops-governance-smoketest.sh
  packages/agoric-cli/test/agops-oracle-smoketest.sh
  packages/agoric-cli/test/agops-perf-smoketest.sh
  packages/agoric-cli/test/agops-vaults-smoketest.sh
  packages/agoric-cli/test/start-local-chain.sh
  packages/agoric-cli/test/upgrade-contract/contract-upgrade-smoketest.sh
  packages/inter-protocol/src/price/README.md
Labels: automerge:rebase, bypass:integration

#10933 test(internal): fake vstorage advance blockHeight
  packages/internal/src/storage-test-utils.js
  packages/internal/test/storage-test-utils.test.js
Labels: automerge:squash

#10921 fix(vtransfer): store in-flight packet data
  golang/cosmos/types/address_hooks.go
  golang/cosmos/types/address_hooks_test.go
  golang/cosmos/x/swingset/testing/queue.go
  golang/cosmos/x/vibc/keeper/keeper.go
  golang/cosmos/x/vibc/keeper/triggers.go
  golang/cosmos/x/vibc/types/receiver.go
  golang/cosmos/x/vstorage/testing/queue.go
  golang/cosmos/x/vtransfer/ibc_middleware.go
  golang/cosmos/x/vtransfer/ibc_middleware_test.go
  golang/cosmos/x/vtransfer/keeper/keeper.go
  golang/cosmos/x/vtransfer/utils_test.go
Labels: bug, automerge:no-update, agoric-cosmos, IBC

#10932 fix multichain-testing waitForBlock
  multichain-testing/tools/e2e-tools.js
Labels: automerge:rebase, force:integration

#10538 refactor(SwingSet): Improve config documentation, typing, and async function implementations
  packages/SwingSet/docs/configuration.md
  packages/SwingSet/src/controller/initializeKernel.js
  packages/SwingSet/src/controller/initializeSwingset.js
  packages/SwingSet/src/supervisors/supervisor-helper.js
  packages/SwingSet/src/typeGuards.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/gc/gc-vat.test.js
  packages/SwingSet/test/virtualObjects/weakcollections.test.js
  packages/SwingSet/tools/run-utils.js
Labels: automerge:rebase

#10929 fix(vat-bank): allow numeric or string nonces
  packages/cosmic-swingset/src/types.d.ts
  packages/internal/src/typeGuards.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/vats/src/vat-bank.js
  packages/vats/test/vat-bank.test.js
Labels: bug, automerge:no-update, agd, contract-upgrade

#10943 test: Stop leaking kernel promises from EV.sendOnly calls
  packages/SwingSet/tools/run-utils.js
Labels: automerge:rebase

#10872 bump synthetic-chain dep
  a3p-integration/package.json
  a3p-integration/proposals/b:beta-fast-usdc/package.json
  a3p-integration/proposals/b:beta-fast-usdc/yarn.lock
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/yarn.lock
  a3p-integration/yarn.lock
  multichain-testing/package.json
Labels: automerge:rebase, force:integration

#10923 feat(x/swingset): allow third party to provision wallet
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/keeper_test.go
  golang/cosmos/x/swingset/keeper/msg_server.go
Labels: automerge:squash

#10945 test(fast-usdc): test restart contract during long tx
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
Labels: automerge:rebase, bypass:integration

#10941 chore: Update OpenTelemetry dependencies
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/kernel-stats.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/solo/src/start.js
  packages/telemetry/package.json
  packages/telemetry/src/index.js
  packages/telemetry/src/otel-trace.js
  yarn.lock
Labels: automerge:rebase

#10946 feat(cosmos): Next Upgrade (patch) is agoric-upgrade-18a
  .github/workflows/multichain-e2e-template.yml
  a3p-integration/package.json
  a3p-integration/proposals/a:upgrade-18/.gitignore
  a3p-integration/proposals/a:upgrade-18/.yarn/patches/axios-npm-1.7.7-cfbedc233d.patch
  a3p-integration/proposals/a:upgrade-18/.yarn/patches/protobufjs-npm-6.11.4-af11968b80.patch
  a3p-integration/proposals/a:upgrade-18/acceptInvites.js
  a3p-integration/proposals/a:upgrade-18/addGov4.js
  a3p-integration/proposals/a:upgrade-18/agd-tools.js
  a3p-integration/proposals/a:upgrade-18/agoric-tools.js
  a3p-integration/proposals/a:upgrade-18/initial.test.js
  a3p-integration/proposals/a:upgrade-18/openVault.js
  a3p-integration/proposals/a:upgrade-18/package.json
  a3p-integration/proposals/a:upgrade-18/prepare.sh
  a3p-integration/proposals/a:upgrade-18/priceFeed-follower-auction.test.js
  a3p-integration/proposals/a:upgrade-18/priceFeedUpdate.test.js
  a3p-integration/proposals/a:upgrade-18/replaceElectorate.test.js
  a3p-integration/proposals/a:upgrade-18/synthetic-chain-excerpt.js
  a3p-integration/proposals/a:upgrade-18/test-lib/price-feed.js
  a3p-integration/proposals/a:upgrade-18/test.sh
  a3p-integration/proposals/a:upgrade-18/tsconfig.json
  a3p-integration/proposals/a:upgrade-18/upgradedBoard.test.js
  a3p-integration/proposals/a:upgrade-18/use.sh
  a3p-integration/proposals/a:upgrade-18/vatDetails.js
  a3p-integration/proposals/a:upgrade-18/verifyPushedPrice.js
  a3p-integration/proposals/a:upgrade-18/yarn.lock
  a3p-integration/proposals/a:upgrade-18a/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-18a/README.md
  a3p-integration/proposals/a:upgrade-18a/package.json
  a3p-integration/proposals/a:upgrade-18a/test.sh
  a3p-integration/proposals/a:upgrade-18a/tsconfig.json
  a3p-integration/proposals/a:upgrade-18a/yarn.lock
  golang/cosmos/app/app.go
  golang/cosmos/app/upgrade.go
  multichain-testing/scripts/install.sh
Labels: force:integration

#10944 build(golang): update `go.mod` for `agoric-labs/cometbft` `v0.35.30` fork
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
  .github/workflows/proto.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-golang.yml
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  packages/deployment/Dockerfile.sdk
  repoconfig.sh
Labels: bug, automerge:no-update, agd, agoric-cosmos, force:integration

#10959 Follow-up fake vstorage blockHeight advancement
  packages/internal/src/storage-test-utils.js
  packages/internal/test/storage-test-utils.test.js
Labels: automerge:rebase

#10964 chore: u18a cherrypicks
  .github/workflows/golangci-lint.yml
  .github/workflows/integration.yml
  .github/workflows/proto.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-golang.yml
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  golang/cosmos/types/address_hooks.go
  golang/cosmos/types/address_hooks_test.go
  golang/cosmos/x/swingset/testing/queue.go
  golang/cosmos/x/vibc/keeper/keeper.go
  golang/cosmos/x/vibc/keeper/triggers.go
  golang/cosmos/x/vibc/types/receiver.go
  golang/cosmos/x/vstorage/testing/queue.go
  golang/cosmos/x/vtransfer/ibc_middleware.go
  golang/cosmos/x/vtransfer/ibc_middleware_test.go
  golang/cosmos/x/vtransfer/keeper/keeper.go
  golang/cosmos/x/vtransfer/utils_test.go
  packages/deployment/Dockerfile.sdk
  repoconfig.sh
Labels: force:integration

#10954 test(cosmic-swingset): Add test coverage for Prometheus output
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/export-kernel-db.js
  packages/cosmic-swingset/src/helpers/maybe-unsafe-lockdown.js
  packages/cosmic-swingset/src/import-kernel-db.js
  packages/cosmic-swingset/test/prometheus.test.js
  packages/cosmic-swingset/test/run-policy.test.js
  packages/cosmic-swingset/test/snapshots/prometheus.test.js.md
  packages/cosmic-swingset/test/snapshots/prometheus.test.js.snap
  packages/cosmic-swingset/tools/test-kit.js
Labels: automerge:rebase

#10970 misc Fast USDC cleanup
  multichain-testing/tools/e2e-tools.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/test/exos/liquidity-pool.test.ts
Labels: automerge:rebase, force:integration

#10980 return funds to LP on AdvanceFailed
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/exos/advancer.test.ts
Labels: automerge:rebase

#10947 Repair u19 tests in a3p-integration
  a3p-integration/proposals/n:upgrade-next/.gitignore
  a3p-integration/proposals/n:upgrade-next/eval.sh
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/psm.test.js
  a3p-integration/proposals/n:upgrade-next/test-lib/mintHolder-helpers.js
  a3p-integration/proposals/n:upgrade-next/test-lib/psm-lib.js
  a3p-integration/proposals/n:upgrade-next/test.sh
  a3p-integration/proposals/n:upgrade-next/test/addCollateral/add-collateral-permit.json
  a3p-integration/proposals/n:upgrade-next/test/addCollateral/add-collateral.js
  a3p-integration/proposals/n:upgrade-next/test/agoricNames.test.js
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/depositUsdOlives/deposit-usd-olives-permit.json
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/depositUsdOlives/deposit-usd-olives.js
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/writeToAgoricNames/write-to-agoricNames-permit.json
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/writeToAgoricNames/write-to-agoricNames.js
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/writeToTestInfo/write-to-testInfo-permit.json
  a3p-integration/proposals/n:upgrade-next/test/agoricNamesCoreEvals/writeToTestInfo/write-to-testInfo.js
  a3p-integration/proposals/n:upgrade-next/test/assetReserve.test.js
  a3p-integration/proposals/n:upgrade-next/test/depositUSD-LEMONS/deposit-usd-lemons-permit.json
  a3p-integration/proposals/n:upgrade-next/test/depositUSD-LEMONS/deposit-usd-lemons.js
  a3p-integration/proposals/n:upgrade-next/test/initial.test.js
  a3p-integration/proposals/n:upgrade-next/test/mint-payment/send-script-permit.json
  a3p-integration/proposals/n:upgrade-next/test/mint-payment/send-script.tjs
  a3p-integration/proposals/n:upgrade-next/test/mintHolder.test.js
  a3p-integration/proposals/n:upgrade-next/test/nullUpgradePP/null-upgrade-pp-permit.json
  a3p-integration/proposals/n:upgrade-next/test/nullUpgradePP/null-upgrade-pp.js
  a3p-integration/proposals/n:upgrade-next/test/provisionPool.test.js
  a3p-integration/proposals/n:upgrade-next/test/psm.test.js
  a3p-integration/proposals/n:upgrade-next/test/replaceFeeDistributor.test.js
  a3p-integration/proposals/n:upgrade-next/test/swapAnchorForMintedSeat/swap-anchor-for-minted-seat-permit.json
  a3p-integration/proposals/n:upgrade-next/test/swapAnchorForMintedSeat/swap-anchor-for-minted-seat.js
  a3p-integration/proposals/n:upgrade-next/tsconfig.json
  a3p-integration/proposals/n:upgrade-next/vatDetails.js
  a3p-integration/proposals/n:upgrade-next/verifyPushedPrice.js
  golang/cosmos/app/upgrade.go
  packages/builders/scripts/inter-protocol/replace-feeDistributor-combo.js
  packages/builders/scripts/vats/upgrade-bank.js
  packages/builders/scripts/vats/upgrade-mintHolder.js
  packages/builders/scripts/vats/upgrade-psm.js
  packages/deploy-script-support/src/helpers.js
  packages/deploy-script-support/src/parseCoreEvalArgs.js
  packages/vats/src/proposals/upgrade-psm-proposal.js
Labels: deployment, test, Testnet, automerge:rebase, contract-upgrade, force:integration

#10981 chore(internal): Disable tsconfig suppressions
  packages/internal/src/priority-senders.js
  packages/internal/tsconfig.json
Labels: automerge:squash

#10718 feat(orch)!: opt-in publishing of account info
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/orchestration/src/examples/auto-stake-it.contract.js
  packages/orchestration/src/examples/basic-flows.contract.js
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/staking-combinations.contract.js
  packages/orchestration/src/examples/swap.contract.js
  packages/orchestration/src/examples/unbond.contract.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/facade.js
  packages/orchestration/src/fixtures/query-flows.contract.js
  packages/orchestration/src/utils/start-helper.js
Labels: automerge:rebase, force:integration

#10989 misc for extracting fast-usdc
  packages/base-zone/src/types.js
  packages/inter-protocol/src/price/fluxAggregatorKit.js
  packages/notifier/src/publish-kit.js
  packages/orchestration/package.json
  tsconfig.json
Labels: automerge:rebase

#10803 test: After updating vaultFactory params, verify the change
  a3p-integration/proposals/z:acceptance/test/governance.test.js
Labels: test, automerge:squash, contract-upgrade, force:integration

#10963 fix(fast-usdc): FORWARD_FAILED when EUD invalid
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/support.ts
  multichain-testing/tools/query.ts
  packages/fast-usdc/src/exos/settler.js
Labels: automerge:rebase

#10993 make SeenTxs prunable
  a3p-integration/proposals/b:beta-fast-usdc/test/test-cli.sh
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/fast-usdc/fu-actors.ts
  packages/fast-usdc/src/cli/operator-commands.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
Labels: automerge:rebase, force:integration

#10996 chore(fast-usdc): beta oracle addresses
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/fast-usdc/src/utils/deploy-config.js
Labels: automerge:rebase, force:integration

#10935 feat(SwingSet): Report vat snapshot size delta on save
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/kernel/vat-loader/manager-subprocess-xsnap.js
Labels: automerge:squash

#10985 standards-compliant import.meta.resolve
  a3p-integration/proposals/z:acceptance/yarn.lock
  multichain-testing/yarn.lock
  packages/SwingSet/package.json
  packages/boot/package.json
  packages/boot/test/configs.test.js
  packages/boot/test/upgrading/upgrade-contracts.test.js
  packages/boot/test/upgrading/upgrade-vats.test.ts
  packages/boot/tools/authorityViz.js
  packages/boot/tools/supports.ts
  packages/builders/package.json
  packages/builders/test/inter-proposals.test.js
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/sim-chain.js
  packages/deploy-script-support/package.json
  packages/deploy-script-support/test/unitTests/install.test.js
  packages/deploy-script-support/test/unitTests/offer.test.js
  packages/deploy-script-support/test/unitTests/startInstance.test.js
  packages/governance/package.json
  packages/governance/test/unitTests/paramGovernance.test.js
  packages/governance/test/unitTests/puppetContractGovernor.test.js
  packages/governance/tools/puppetGovernance.js
  packages/inter-protocol/package.json
  packages/inter-protocol/test/auction/tools.js
  packages/inter-protocol/test/swingsetTests/fluxAggregator/fluxAggregator-service-upgrade.test.js
  packages/inter-protocol/test/swingsetTests/psmUpgrade/psm-upgrade.test.js
  packages/inter-protocol/test/swingsetTests/reserve/assetReserve-upgrade.test.js
  packages/inter-protocol/test/vaultFactory/vault-interest.test.js
  packages/inter-protocol/test/vaultFactory/vault.test.js
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/smart-wallet/test/addAsset.test.js
  packages/smart-wallet/test/swingsetTests/upgradeWalletFactory/walletFactory-service-upgrade.test.js
  packages/solo/package.json
  packages/solo/src/start.js
  packages/solo/test/home.test.js
  packages/swingset-runner/demo/exchangeBenchmark/prepareContracts.js
  packages/swingset-runner/demo/swapBenchmark/prepareContracts.js
  packages/swingset-runner/demo/zoeTests/prepareContracts.js
  packages/swingset-runner/package.json
  packages/vats/package.json
  packages/wallet/api/package.json
  packages/wallet/api/test/lib-wallet.test.js
  packages/wallet/package.json
  packages/zoe/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#10999 chore: update installations when restarting or upgrading
  packages/builders/scripts/inter-protocol/replace-feeDistributor-combo.js
  packages/builders/scripts/inter-protocol/replace-feeDistributor.js
  packages/deploy-script-support/README.md
  packages/inter-protocol/src/proposals/replace-fee-distributor.js
  packages/smart-wallet/src/proposals/upgrade-wallet-factory2-proposal.js
  packages/vats/src/proposals/upgrade-asset-reserve-proposal.js
  packages/vats/src/proposals/upgrade-mintHolder-proposal.js
  packages/vats/src/proposals/upgrade-provisionPool-proposal.js
Labels: deployment, Zoe Contract, automerge:squash, contract-upgrade

#10871 Excise `reallocate()`
  golang/cosmos/app/upgrade.go
  packages/boot/test/bootstrapTests/zcf-upgrade.test.ts
  packages/boot/test/bootstrapTests/zcfProbe.contract.js
  packages/smart-wallet/test/gameAssetContract.js
  packages/zoe/docs/AttackGuide.md
  packages/zoe/docs/seats.md
  packages/zoe/docs/zcf-reallocate-flow.png
  packages/zoe/docs/zcf-reallocate-flow.puml
  packages/zoe/docs/zoe-catalog-of-storage.md
  packages/zoe/src/contractFacet/types-ambient.d.ts
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/internal-types.js
  packages/zoe/test/unitTests/contractSupport/zoeHelpers.test.js
  packages/zoe/test/unitTests/zcf/allStagedSeatsUsed.test.js
  packages/zoe/test/unitTests/zcf/reallocate-empty.test.js
  packages/zoe/test/unitTests/zcf/reallocateForZCFMint.test.js
  packages/zoe/test/unitTests/zcf/zcf.test.js
Labels: Zoe, code-style, automerge:rebase, contract-upgrade, force:integration

#11008 test(a3p-integration): update to agoric-upgrade-18a
  a3p-integration/package.json
Labels: automerge:rebase, force:integration

#10930 ci: remove DD unit tests metrics reporting from CI
  .github/actions/post-test/action.yml
  .github/workflows/test-all-packages.yml
  scripts/ava-etap-to-junit.mjs
  scripts/ci/collect-testruns.sh
Labels: automerge:rebase, force:integration

#11005 feat(fast-usdc): skipAdvance when preconditions fail
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/test/exos/advancer.test.ts
Labels: automerge:rebase

#11012 fewer packageManager assumptions
  a3p-integration/scripts/build-submission.sh
  golang/cosmos/package.json
  multichain-testing/package.json
  multichain-testing/yarn.lock
  package.json
  packages/agoric-cli/scripts/get-sdk-package-names.js
  packages/agoric-cli/src/install.js
  packages/agoric-cli/src/lib/packageManager.js
  packages/agoric-cli/test/helpers.test.js
  packages/boot/tools/supports.ts
  packages/cosmic-proto/package.json
  scripts/check-mismatched-dependencies.cjs
  scripts/check-untested-packages.mjs
  scripts/run-deployment-integration.sh
  scripts/update-typedoc-functions-path.cjs
  yarn.lock
Labels: automerge:rebase, force:integration

#10808 refactor(SwingSet): Cleanup vatManagerFactory
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/vat-loader/manager-factory.js
  packages/SwingSet/src/kernel/vat-loader/vat-loader.js
Labels: automerge:rebase

#11015 chore(swingset-liveslots): add retry logic to liveslots-real-gc test
  packages/internal/tools/avaRetry.js
  packages/swingset-liveslots/test/liveslots-real-gc.test.js
Labels: automerge:squash

#11009 fix(agoric-cli): agops oracle pushPriceRound will fail with some prices
  packages/agoric-cli/src/bin-agops.js
  packages/agoric-cli/src/commands/oracle.js
  packages/agoric-cli/test/oracle-cli.test.js
Labels: automerge:squash

#11006 fix(a3p-integration): replaceFeeDistributor flakiness fix
  a3p-integration/proposals/n:upgrade-next/test/replaceFeeDistributor.test.js
Labels: automerge:rebase, force:integration

#11018 ci: fix coverage reporting via Codecov
  .github/actions/post-test/action.yml
  scripts/ci/collect-testruns.sh
Labels: automerge:rebase

#11020 docs: `multichain-testing` resource reqs
  multichain-testing/README.md
Labels: automerge:rebase

#10934 feat: added nix flake
  .github/workflows/nix-check.yml
  flake.lock
  flake.nix
Labels: automerge:rebase

#11024 chore: remove ava timing patch
  patches/ava+5.3.1.patch
Labels: automerge:rebase, force:integration

#11029 integrate atop 87:fast-usdc-beta
  a3p-integration/package.json
  a3p-integration/proposals/b:beta-fast-usdc/.gitignore
  a3p-integration/proposals/b:beta-fast-usdc/.yarnrc.yml
  a3p-integration/proposals/b:beta-fast-usdc/README.md
  a3p-integration/proposals/b:beta-fast-usdc/package.json
  a3p-integration/proposals/b:beta-fast-usdc/test.sh
  a3p-integration/proposals/b:beta-fast-usdc/test/deploy.test.js
  a3p-integration/proposals/b:beta-fast-usdc/test/operators.test.js
  a3p-integration/proposals/b:beta-fast-usdc/test/test-cli.sh
  a3p-integration/proposals/b:beta-fast-usdc/yarn.lock
Labels: automerge:rebase

#10925 feat(SwingSet): Echo kernel console output to the slog
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/slogger.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/vatKeeper.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/src/types-internal.js
  packages/SwingSet/test/abandon-export.test.js
  packages/SwingSet/test/controller.test.js
  packages/SwingSet/test/gc-kernel-orphan.test.js
  packages/SwingSet/test/gc-kernel.test.js
  packages/SwingSet/test/state.test.js
  packages/SwingSet/test/util.js
  packages/SwingSet/test/vpid-kernel.test.js
  packages/internal/src/js-utils.js
  packages/internal/src/ses-utils.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/swingset-liveslots/src/liveslots.js
Labels: automerge:rebase

#10686 fix(vow): report unhandled vow rejections on collection or upgrade
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/internal/src/lib-nodejs/ava-unhandled-rejection.js
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/examples/staking-combinations.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/vow/package.json
  packages/vow/src/rejection-tracker.js
  packages/vow/src/tools.js
  packages/vow/src/types.ts
  packages/vow/src/vow-utils.js
  packages/vow/src/vow.js
  packages/vow/src/watch.js
  packages/vow/test/retryable.test.js
  packages/vow/test/unhandled-rejections.test.js
  packages/vow/test/watch-upgrade.test.js
  packages/vow/test/watch-utils.test.js
  packages/zoe/test/unitTests/contracts/snapshots/valueVow.test.js.md
  packages/zoe/test/unitTests/contracts/snapshots/valueVow.test.js.snap
  patches/ava+5.3.1.patch
Labels: devex, automerge:rebase, force:integration

#11011 Add chain node timing metrics
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/test/prometheus.test.js
  packages/cosmic-swingset/test/snapshots/prometheus.test.js.md
  packages/cosmic-swingset/test/snapshots/prometheus.test.js.snap
  packages/internal/src/js-utils.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
Labels: automerge:rebase

#11021 chore(swingset-liveslots): use avaRetry() in virtualObjectGC.test.js
  packages/swingset-liveslots/test/virtual-objects/virtualObjectGC.test.js
Labels: automerge:squash, flake

#9008 chore(SwingSet): Explain how `profileVats` affects node CLI options
  packages/SwingSet/src/controller/startNodeSubprocess.js
Labels: automerge:squash

#10997 Report vstorage size delta for set() operations via telemetry
  golang/cosmos/x/vstorage/keeper/keeper.go
Labels: automerge:squash

#11033 feat(cosmos): Next Upgrade is agoric-upgrade-19
  a3p-integration/proposals/a:upgrade-19/.gitignore
  a3p-integration/proposals/a:upgrade-19/.yarn/patches/axios-npm-1.7.7-cfbedc233d.patch
  a3p-integration/proposals/a:upgrade-19/.yarn/patches/protobufjs-npm-6.11.4-af11968b80.patch
  a3p-integration/proposals/a:upgrade-19/.yarnrc.yml
  a3p-integration/proposals/a:upgrade-19/README.md
  a3p-integration/proposals/a:upgrade-19/eval.sh
  a3p-integration/proposals/a:upgrade-19/package.json
  a3p-integration/proposals/a:upgrade-19/test-lib/index.js
  a3p-integration/proposals/a:upgrade-19/test-lib/mintHolder-helpers.js
  a3p-integration/proposals/a:upgrade-19/test-lib/price-feed.js
  a3p-integration/proposals/a:upgrade-19/test-lib/provision-helpers.js
  a3p-integration/proposals/a:upgrade-19/test-lib/psm-lib.js
  a3p-integration/proposals/a:upgrade-19/test-lib/utils.js
  a3p-integration/proposals/a:upgrade-19/test.sh
  a3p-integration/proposals/a:upgrade-19/test/addCollateral/add-collateral-permit.json
  a3p-integration/proposals/a:upgrade-19/test/addCollateral/add-collateral.js
  a3p-integration/proposals/a:upgrade-19/test/agoricNames.test.js
  a3p-integration/proposals/a:upgrade-19/test/agoricNamesCoreEvals/depositUsdOlives/deposit-usd-olives-permit.json
  a3p-integration/proposals/a:upgrade-19/test/agoricNamesCoreEvals/depositUsdOlives/deposit-usd-olives.js
  a3p-integration/proposals/a:upgrade-19/test/agoricNamesCoreEvals/writeToAgoricNames/write-to-agoricNames-permit.json
  a3p-integration/proposals/a:upgrade-19/test/agoricNamesCoreEvals/writeToAgoricNames/write-to-agoricNames.js
  a3p-integration/proposals/a:upgrade-19/test/agoricNamesCoreEvals/writeToTestInfo/write-to-testInfo-permit.json
  a3p-integration/proposals/a:upgrade-19/test/agoricNamesCoreEvals/writeToTestInfo/write-to-testInfo.js
  a3p-integration/proposals/a:upgrade-19/test/assetReserve.test.js
  a3p-integration/proposals/a:upgrade-19/test/depositUSD-LEMONS/deposit-usd-lemons-permit.json
  a3p-integration/proposals/a:upgrade-19/test/depositUSD-LEMONS/deposit-usd-lemons.js
  a3p-integration/proposals/a:upgrade-19/test/initial.test.js
  a3p-integration/proposals/a:upgrade-19/test/mint-payment/send-script-permit.json
  a3p-integration/proposals/a:upgrade-19/test/mint-payment/send-script.tjs
  a3p-integration/proposals/a:upgrade-19/test/mintHolder.test.js
  a3p-integration/proposals/a:upgrade-19/test/nullUpgradePP/null-upgrade-pp-permit.json
  a3p-integration/proposals/a:upgrade-19/test/nullUpgradePP/null-upgrade-pp.js
  a3p-integration/proposals/a:upgrade-19/test/provisionPool.test.js
  a3p-integration/proposals/a:upgrade-19/test/psm.test.js
  a3p-integration/proposals/a:upgrade-19/test/replaceFeeDistributor.test.js
  a3p-integration/proposals/a:upgrade-19/test/swapAnchorForMintedSeat/swap-anchor-for-minted-seat-permit.json
  a3p-integration/proposals/a:upgrade-19/test/swapAnchorForMintedSeat/swap-anchor-for-minted-seat.js
  a3p-integration/proposals/a:upgrade-19/tsconfig.json
  a3p-integration/proposals/a:upgrade-19/yarn.lock
  a3p-integration/proposals/n:upgrade-next/README.md
  golang/cosmos/app/app.go
  golang/cosmos/app/upgrade.go
Labels: force:integration

#11032 feat: nix improvements for modularity
  flake.lock
  flake.nix
  nix/devShell.nix
  nix/nodejs.nix
Labels: automerge:squash

#11036 chore: fix lint in golang, a3p, network, ERTP
  a3p-integration/proposals/n:upgrade-next/test/agoricNames.test.js
  a3p-integration/proposals/z:acceptance/test/initial.test.js
  golang/cosmos/x/vtransfer/handler.go
  golang/cosmos/x/vtransfer/keeper/keeper.go
  packages/ERTP/test/unitTests/mintObj.test.js
  packages/network/test/fakes.js
Labels: code-style, automerge:squash

#11040 feat(internal): Miscellaneous improvements
  packages/internal/src/js-utils.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/orchestration/src/facade.js
Labels: automerge:rebase

#11039 chore(vats): Fix typo in JSDoc
  packages/vats/src/core/utils.js
Labels: automerge:squash, bypass:integration

#11049 misc Fast USDC improvements
  multichain-testing/test/auto-stake-it.test.ts
  multichain-testing/test/send-anywhere.test.ts
  multichain-testing/test/stake-ica.test.ts
  packages/boot/test/bootstrapTests/lca.test.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/start-fast-usdc.core.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/snapshots/advancer.test.ts.md
  packages/fast-usdc/test/exos/snapshots/advancer.test.ts.snap
  packages/fast-usdc/test/exos/snapshots/settler.test.ts.md
  packages/fast-usdc/test/exos/snapshots/settler.test.ts.snap
  packages/fast-usdc/test/fixtures.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/send-anywhere.flows.js
  packages/orchestration/src/examples/stake-bld.contract.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/ica-account-kit.js
  packages/orchestration/src/exos/local-chain-facade.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/exos/portfolio-holder-kit.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/utils/cosmos.js
  packages/orchestration/src/utils/orc.js
  packages/orchestration/test/examples/auto-stake-it.contract.test.ts
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/examples/stake-ica.contract.test.ts
  packages/orchestration/test/examples/staking-combinations.test.ts
  packages/orchestration/test/examples/swap.contract.test.ts
  packages/orchestration/test/exos/chain-hub-transfer-routes.test.ts
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/exos/make-test-loa-kit.ts
  packages/orchestration/test/exos/portfolio-holder-kit.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/tx-encoding.test.ts
  packages/orchestration/test/typeGuards.test.ts
  packages/orchestration/test/types.test-d.ts
  packages/orchestration/test/utils/zoe-tools.test.ts
Labels: automerge:rebase, force:integration

#10807 feat(cosmic-swingset): Introduce inquisitor.mjs
  eslint.config.mjs
  packages/SwingSet/tools/run-utils.js
  packages/boot/test/upgrading/upgrade-vats.test.ts
  packages/boot/tools/supports.ts
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/helpers/bufferedStorage.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/test/inquisitor.test.js
  packages/cosmic-swingset/tools/inquisitor.mjs
  packages/cosmic-swingset/tools/test-kit.js
  packages/cosmic-swingset/tsconfig.json
  packages/internal/package.json
  packages/internal/src/index.js
  packages/internal/src/ses-utils.js
  packages/internal/src/types.ts
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/internal/test/types.test-d.ts
  packages/internal/test/utils.test.js
  packages/swing-store/src/assertComplete.js
  packages/swing-store/src/bundleStore.js
  packages/swing-store/src/exporter.js
  packages/swing-store/src/index.js
  packages/swing-store/src/internal.js
  packages/swing-store/src/kvStore.js
  packages/swing-store/src/snapStore.js
  packages/swing-store/src/swingStore.js
  packages/swing-store/src/transcriptStore.js
  yarn.lock
Labels: automerge:rebase

#11025 fix(fast-usdc): update noble connection info, make new ICA
  packages/boot/test/fast-usdc/bundles/b1-6f742c9506079a4ad917c50ef15cab85c5d2c8d562c04de72e9a79c2a192ba36e7c88aa365b740a0e1fd1968199289e20ed23ee62dd4a3240da78ebb6763fa34.json
  packages/boot/test/fast-usdc/bundles/b1-ff51ba7d4abbab92013467813379be4d428b0b7a3f1a6f2ebd06c9b774e0e4e6acfbd6aea9e508d53419c50e13495b314a1b1fb94392ce42ea8feb18de9b3fa7.json
  packages/boot/test/fast-usdc/bundles/dl.sh
  packages/boot/test/fast-usdc/bundles/start-fast-usdc-permit.json
  packages/boot/test/fast-usdc/bundles/start-fast-usdc-plan.json
  packages/boot/test/fast-usdc/bundles/start-fast-usdc.js
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/boot/tools/supports.ts
  packages/boot/tsconfig.json
  packages/builders/scripts/fast-usdc/fast-usdc-reconfigure.build.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/start-fast-usdc.core.js
  packages/fast-usdc/src/update-noble-ica.core.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/test/exos/chain-hub.test.ts
Labels: automerge:rebase, force:integration

#11065 fix(cosmos): upgrade to `agoric-labs/ibc-go` `v6.3.1-alpha.agoric.3`
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: automerge:no-update, agd, force:integration, IBC

#11055 chore(fast-usdc): update, test chain policies vs. spreadsheet
  a3p-integration/proposals/g:gtm-fast-usdc/.yarnrc.yml
  a3p-integration/proposals/g:gtm-fast-usdc/README.md
  a3p-integration/proposals/g:gtm-fast-usdc/package.json
  a3p-integration/proposals/g:gtm-fast-usdc/test.sh
  a3p-integration/proposals/g:gtm-fast-usdc/test/deploy.test.js
  a3p-integration/proposals/g:gtm-fast-usdc/test/test-cli.sh
  a3p-integration/proposals/g:gtm-fast-usdc/yarn.lock
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/update-noble-ica.core.js
  packages/fast-usdc/src/utils/chain-policies.js
  packages/fast-usdc/src/utils/deploy-config.js
  packages/fast-usdc/test/utils/chain-policies.test.ts
Labels: automerge:rebase
