Repository Agoric/agoric-sdk, pull requests merged in 2025-01, with the labels that each got.

#10787 fix(fast-usdc): recover from bad lp proposal
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/fast-usdc/src/cli/lp-commands.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/test/cli/lp-commands.test.ts
  packages/fast-usdc/test/pool-share-math.test.ts
Labels: automerge:rebase

#10738 make userSeat.getPayout(foo) throw if foo is not present
  packages/zoe/src/zoeService/originalZoeSeat.js
  packages/zoe/src/zoeService/types-ambient.js
  packages/zoe/src/zoeService/zoeSeat.js
  packages/zoe/test/unitTests/zcf/zcf.test.js
Labels: Zoe, hygiene, automerge:squash

#10729 chore(fusdc): settle `ForwardFailed`, minted while `Advancing`, and minted early txs
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc/test/supports.ts
Labels: automerge:rebase, force:integration

#10805 fix A3P test of fast-usdc
  a3p-integration/proposals/f:fast-usdc/README.md
  a3p-integration/proposals/f:fast-usdc/deploy.test.js
  a3p-integration/proposals/f:fast-usdc/package.json
  a3p-integration/proposals/f:fast-usdc/test-cli.sh
  a3p-integration/proposals/f:fast-usdc/test.sh
  a3p-integration/proposals/f:fast-usdc/yarn.lock
Labels: automerge:rebase

#10719 8606 invite proposals
  packages/zoe/src/contracts/coveredCall.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/types-ambient.js
  packages/zoe/test/unitTests/contracts/coveredCall.test.js
  packages/zoe/test/unitTests/zcf/offer-proposalShape.test.js
Labels: Zoe, test, Zoe Contract, automerge:rebase

#10304 feat: allow getBundleIDFromInstallation to be called with a promise
  packages/zoe/src/typeGuards.js
Labels: Zoe, automerge:rebase

#10823 chore(types): explicit ERTP type imports
  packages/fast-usdc/src/cli/lp-commands.js
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/fast-usdc-policy.core.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/test/config-marshal.test.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/pool-share-math.test.ts
  packages/fast-usdc/test/utils/fees.test.ts
  packages/inter-protocol/src/interest-math.js
  packages/zoe/tools/test-utils.js
  packages/zoe/tools/types.js
Labels: automerge:rebase

#10829 chore: chain policies for all chains
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/utils/chain-policies.js
  packages/fast-usdc/src/utils/deploy-config.js
Labels: automerge:rebase

#10814 chore: fusdc chain policy limits
  multichain-testing/package.json
  multichain-testing/scripts/fast-usdc-tool.ts
  multichain-testing/test/fast-usdc/config.ts
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/fast-usdc/noble-forwarding.test.ts
  multichain-testing/test/support.ts
  multichain-testing/tools/noble-tools.ts
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/builders/scripts/fast-usdc/init-fast-usdc.js
  packages/fast-usdc/src/fast-usdc-policy.core.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/chain-policies.js
  packages/fast-usdc/test/type-guards.test.ts
Labels: automerge:rebase, force:integration

#10755 ability to replace oracle operators in fast-usdc
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/fast-usdc.start.js
  packages/fast-usdc/test/exos/transaction-feed.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
Labels: automerge:rebase

#10817 chore(acceptance): upgrade pp's governor
  a3p-integration/proposals/p:upgrade-19/provisionPool.test.js
  a3p-integration/proposals/p:upgrade-19/test-lib/utils.js
  a3p-integration/proposals/z:acceptance/governance.test.js
  a3p-integration/proposals/z:acceptance/test-lib/governance.js
  a3p-integration/proposals/z:acceptance/test-lib/utils.js
  packages/vats/src/proposals/upgrade-provisionPool-proposal.js
Labels: automerge:rebase, force:integration

#10834 test of replacing fast-usdc operators
  a3p-integration/proposals/f:fast-usdc/.gitignore
  a3p-integration/proposals/f:fast-usdc/deploy.test.js
  a3p-integration/proposals/f:fast-usdc/operators.test.js
  a3p-integration/proposals/f:fast-usdc/package.json
  a3p-integration/proposals/f:fast-usdc/test.sh
  multichain-testing/scripts/fast-usdc-tool.ts
  multichain-testing/src/register-interchain-bank-assets.builder.js
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/tools/supports.ts
  packages/builders/scripts/fast-usdc/add-operators.build.js
  packages/builders/scripts/fast-usdc/fast-usdc-update.build.js
  packages/builders/scripts/fast-usdc/start-fast-usdc.build.js
  packages/fast-usdc/src/add-operators.core.js
  packages/fast-usdc/src/fast-usdc-policy.core.js
  packages/fast-usdc/src/start-fast-usdc.core.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/utils/core-eval.js
Labels: automerge:rebase, force:integration

#10835 migrate `s:stake-bld` to `z:acceptance`
  a3p-integration/proposals/s:stake-bld/.yarnrc.yml
  a3p-integration/proposals/s:stake-bld/README.md
  a3p-integration/proposals/s:stake-bld/package.json
  a3p-integration/proposals/s:stake-bld/test-lib/index.js
  a3p-integration/proposals/s:stake-bld/test-lib/wallet.js
  a3p-integration/proposals/s:stake-bld/test.sh
  a3p-integration/proposals/s:stake-bld/tsconfig.json
  a3p-integration/proposals/s:stake-bld/yarn.lock
  a3p-integration/proposals/z:acceptance/.gitignore
  a3p-integration/proposals/z:acceptance/.yarn/patches/axios-npm-1.7.7-cfbedc233d.patch
  a3p-integration/proposals/z:acceptance/.yarn/patches/protobufjs-npm-6.11.4-af11968b80.patch
  a3p-integration/proposals/z:acceptance/eval.sh
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/stakeBld.test.js
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/yarn.lock
Labels: automerge:rebase, force:integration

#10815 feat(fast-usdc): withdraw and distribute contract fees
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/wallet.ts
  packages/boot/package.json
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/builders/scripts/fast-usdc/fast-usdc-fees.build.js
  packages/fast-usdc/src/distribute-fees.core.js
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/src/start-fast-usdc.core.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/utils/core-eval.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
Labels: automerge:rebase, force:integration

#10860 chore: fix advance available condition
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
Labels: automerge:rebase, force:integration

#10859 chore: fusdc remove `maxVariable` from `FeeConfig`
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/builders/scripts/fast-usdc/start-fast-usdc.build.js
  packages/fast-usdc/src/type-guards.js
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/src/utils/fees.js
  packages/fast-usdc/test/config-marshal.test.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/mocks.ts
  packages/fast-usdc/test/utils/fees.test.ts
Labels: automerge:rebase

#10863 fix(multichain-testing): update starship helm chart repo URL
  .github/workflows/multichain-e2e-template.yml
  multichain-testing/scripts/install.sh
Labels: automerge:rebase, force:integration

#8544 BridgeMessage types
  packages/cosmic-swingset/src/types.d.ts
  packages/cosmic-swingset/src/types.js
  packages/cosmic-swingset/tsconfig.json
  packages/inter-protocol/src/provisionPoolKit.js
  packages/inter-protocol/test/provisionPool.test.js
  packages/vats/src/core/chain-behaviors.js
  packages/vats/src/vat-bank.js
Labels: automerge:rebase

#10848 test: allow workerThreads in swingset-vat
  packages/SwingSet/package.json
Labels: automerge:rebase, bypass:integration

#10845 feat(orchestration): add more chain infos for fusdc
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/orchestration/contract-upgrade.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/boot/test/tools/chainInfo.ts
  packages/fast-usdc/test/chain-info.test.js
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/scripts/fetch-chain-info.ts
  packages/orchestration/src/chain-capabilities.js
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/fetched-chain-info.js
  packages/orchestration/test/chain-info.test.js
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/snapshots/chain-info.test.js.md
  packages/orchestration/test/snapshots/chain-info.test.js.snap
Labels: automerge:rebase, force:integration

#10857 perf measurement for Fast USDC in multichain-testing
  multichain-testing/scripts/fast-usdc-tool.ts
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/fast-usdc/fu-actors.ts
  multichain-testing/tools/agd-lib.js
  multichain-testing/tools/block-iter.js
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/query.ts
  packages/client-utils/src/clock-timer.js
Labels: automerge:rebase, force:integration

#10822 support changes to governed APIs
  packages/boot/package.json
  packages/boot/test/bootstrapTests/governedContract.js
  packages/boot/test/bootstrapTests/governedContract2.js
  packages/boot/test/bootstrapTests/updateUpgradedVaultParams.test.ts
  packages/boot/test/bootstrapTests/upgradeAPI.test.ts
  packages/governance/src/contractGovernance/governApi.js
  packages/governance/src/contractGovernorKit.js
  packages/governance/src/contractHelper.js
  packages/governance/src/types.js
  packages/zoe/src/contractFacet/zcfZygote.js
Labels: Governance, automerge:rebase, contract-upgrade

#10874 test(liveslots): enable ava worker threads
  packages/swingset-liveslots/package.json
Labels: automerge:squash

#10869 chore(swingset-liveslots): export TypeScript definitions
  packages/swingset-liveslots/package.json
  packages/swingset-liveslots/tsconfig.build.json
  packages/swingset-liveslots/tsconfig.json
Labels: automerge:squash, force:integration

#10875 chore(types): compat with swingset-liveslots exports
  packages/SwingSet/src/vats/timer/vat-timer.js
  packages/governance/src/binaryVoteCounter.js
  packages/governance/src/committee.js
  packages/governance/src/contractGovernance/paramManager.js
  packages/governance/src/electorateTools.js
  packages/governance/src/multiCandidateVoteCounter.js
  packages/vat-data/src/index.js
  packages/zoe/src/contractFacet/offerHandlerStorage.js
  packages/zoe/src/contractFacet/reallocate.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractSupport/durability.js
  packages/zoe/src/contractSupport/zoeHelpers.js
  packages/zoe/src/issuerStorage.js
  packages/zoe/src/zoeService/escrowStorage.js
  packages/zoe/src/zoeService/installationStorage.js
  packages/zoe/src/zoeService/instanceAdminStorage.js
  packages/zoe/src/zoeService/internal-types.js
  packages/zoe/src/zoeService/startInstance.js
  packages/zoe/src/zoeService/types-ambient.js
  packages/zoe/tools/fakeVatAdmin.js
Labels: automerge:rebase, bypass:integration

#10846 Upgrade to ESLint v9
  .eslintignore
  .eslintrc.cjs
  eslint.config.mjs
  multichain-testing/eslint.config.mjs
  multichain-testing/package.json
  multichain-testing/scripts/fast-usdc-tool.ts
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tsconfig.json
  multichain-testing/yarn.lock
  package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/cosmic-proto/.eslintignore
  packages/cosmic-swingset/.eslintignore
  packages/cosmic-swingset/check-validator.cjs
  packages/cosmic-swingset/tsconfig.json
  packages/eslint-config/eslint-config.cjs
  packages/eslint-config/package.json
  packages/swingset-xsnap-supervisor/.eslintrc
  tsconfig.json
  yarn.lock
Labels: automerge:rebase, force:integration

#10870 fix(fast-usdc): consider encumberedBalance in withdrawCalc
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/pool-share-math.test.ts
Labels: automerge:rebase

#10878 fix(swingset-xsnap-supervisor): Add missing promise-kit dependency
  packages/swingset-xsnap-supervisor/package.json
Labels: automerge:rebase

#10853 segregate test files in a3p proposals
  a3p-integration/package.json
  a3p-integration/proposals/f:fast-usdc/package.json
  a3p-integration/proposals/f:fast-usdc/test.sh
  a3p-integration/proposals/f:fast-usdc/test/deploy.test.js
  a3p-integration/proposals/f:fast-usdc/test/operators.test.js
  a3p-integration/proposals/f:fast-usdc/test/test-cli.sh
  a3p-integration/proposals/f:fast-usdc/yarn.lock
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/test/core-eval-test-submission/README.md
  a3p-integration/proposals/z:acceptance/test/core-eval-test-submission/send-script-permit.json
  a3p-integration/proposals/z:acceptance/test/core-eval-test-submission/send-script.tjs
  a3p-integration/proposals/z:acceptance/test/core-eval.test.js
  a3p-integration/proposals/z:acceptance/test/genesis-test.sh
  a3p-integration/proposals/z:acceptance/test/governance.test.js
  a3p-integration/proposals/z:acceptance/test/initial.test.js
  a3p-integration/proposals/z:acceptance/test/invitation-test-submission/send-script-permit.json
  a3p-integration/proposals/z:acceptance/test/invitation-test-submission/send-script.tjs
  a3p-integration/proposals/z:acceptance/test/kread.test.js
  a3p-integration/proposals/z:acceptance/test/lib/vaults.ts
  a3p-integration/proposals/z:acceptance/test/localchain.test.js
  a3p-integration/proposals/z:acceptance/test/psm.test.js
  a3p-integration/proposals/z:acceptance/test/recorded-retired.test.js
  a3p-integration/proposals/z:acceptance/test/scripts/test-vaults.ts
  a3p-integration/proposals/z:acceptance/test/stakeBld.test.js
  a3p-integration/proposals/z:acceptance/test/state-sync-snapshots-test.sh
  a3p-integration/proposals/z:acceptance/test/test-lib/governance.js
  a3p-integration/proposals/z:acceptance/test/test-lib/index.js
  a3p-integration/proposals/z:acceptance/test/test-lib/kread.js
  a3p-integration/proposals/z:acceptance/test/test-lib/price-feed.js
  a3p-integration/proposals/z:acceptance/test/test-lib/psm-lib.js
  a3p-integration/proposals/z:acceptance/test/test-lib/rpc.js
  a3p-integration/proposals/z:acceptance/test/test-lib/utils.js
  a3p-integration/proposals/z:acceptance/test/test-lib/vaults.js
  a3p-integration/proposals/z:acceptance/test/test-lib/wallet.js
  a3p-integration/proposals/z:acceptance/test/valueVow.test.js
  a3p-integration/proposals/z:acceptance/test/vaults.test.js
  a3p-integration/proposals/z:acceptance/test/wallet.test.js
  a3p-integration/proposals/z:acceptance/yarn.lock
  a3p-integration/yarn.lock
Labels: automerge:rebase, bypass:integration

#10877 refactor(swingset-xsnap-supervisor): Replace Rollup with Endo
  packages/SwingSet/test/snapshots/xsnap-store.test.js.md
  packages/SwingSet/test/snapshots/xsnap-store.test.js.snap
  packages/xsnap-lockdown/lib/confined-object-inspect.js
  packages/xsnap-lockdown/package.json
  packages/xsnap-lockdown/rollup.config.js
  packages/xsnap-lockdown/scripts/build-bundle.js
  packages/xsnap-lockdown/src/paths.js
  yarn.lock
Labels: automerge:rebase

#10880 ci: build sdk image for multi-chain test
  .github/actions/starship-action/README.md
  .github/actions/starship-action/action.yaml
  .github/actions/starship-action/install.sh
  .github/actions/starship-action/port-forward.sh
  .github/workflows/multichain-e2e-template.yml
  multichain-testing/tools/e2e-tools.js
Labels: tooling, automerge:no-update, force:integration

#10892 fix wallet extract-id CLI
  packages/agoric-cli/package.json
  packages/agoric-cli/src/commands/wallet.js
  packages/agoric-cli/src/lib/chain.js
  packages/boot/package.json
  packages/builders/package.json
  packages/casting/package.json
  packages/cosmic-swingset/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/orchestration/package.json
  packages/store/package.json
  packages/swingset-liveslots/package.json
  packages/vats/package.json
  packages/xsnap-lockdown/package.json
  packages/zoe/package.json
Labels: automerge:rebase, bypass:integration

#10885 lint swingset-xsnap-supervisor imports
  eslint.config.mjs
  packages/swingset-xsnap-supervisor/package.json
Labels: automerge:rebase, bypass:integration

#10889 chore: Sync Endo versions 2025-01-24
  a3p-integration/proposals/f:fast-usdc/package.json
  a3p-integration/proposals/f:fast-usdc/yarn.lock
  a3p-integration/proposals/n:upgrade-next/package.json
  a3p-integration/proposals/n:upgrade-next/yarn.lock
  a3p-integration/proposals/p:upgrade-19/package.json
  a3p-integration/proposals/p:upgrade-19/yarn.lock
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/yarn.lock
  a3p-integration/yarn.lock
  multichain-testing/package.json
  multichain-testing/yarn.lock
  package.json
  packages/ERTP/package.json
  packages/SwingSet/package.json
  packages/SwingSet/test/snapshots/xsnap-store.test.js.md
  packages/SwingSet/test/snapshots/xsnap-store.test.js.snap
  packages/agoric-cli/package.json
  packages/async-flow/package.json
  packages/base-zone/package.json
  packages/benchmark/package.json
  packages/boot/package.json
  packages/builders/package.json
  packages/cache/package.json
  packages/casting/package.json
  packages/client-utils/package.json
  packages/cosmic-proto/package.json
  packages/cosmic-swingset/package.json
  packages/deploy-script-support/package.json
  packages/deployment/package.json
  packages/eslint-config/package.json
  packages/fast-usdc/package.json
  packages/governance/package.json
  packages/inter-protocol/package.json
  packages/internal/package.json
  packages/kmarshal/package.json
  packages/network/package.json
  packages/notifier/package.json
  packages/orchestration/package.json
  packages/pegasus/package.json
  packages/smart-wallet/package.json
  packages/solo/package.json
  packages/spawner/package.json
  packages/stat-logger/package.json
  packages/store/package.json
  packages/swing-store/package.json
  packages/swingset-liveslots/package.json
  packages/swingset-runner/package.json
  packages/swingset-xsnap-supervisor/package.json
  packages/telemetry/package.json
  packages/time/package.json
  packages/vat-data/package.json
  packages/vats/package.json
  packages/vow/package.json
  packages/wallet/api/package.json
  packages/xsnap-lockdown/package.json
  packages/xsnap/api.js
  packages/xsnap/package.json
  packages/zoe/package.json
  packages/zone/package.json
  yarn.lock
Labels: automerge:rebase, force:integration

#10888 feat(cosmic-swingset): add metrics for each action type
  packages/cosmic-swingset/src/launch-chain.js
  packages/internal/src/action-types.js
Labels: automerge:squash

#10908 bump eslint deps
  eslint.config.mjs
  package.json
  yarn.lock
Labels: automerge:rebase

#10828 fix Payment type
  package.json
  packages/ERTP/src/issuerKit.js
  packages/ERTP/src/legacy-payment-helpers.js
  packages/ERTP/src/payment.js
  packages/ERTP/src/types.ts
  packages/ERTP/test/unitTests/mintObj.test.js
  packages/deploy-script-support/test/unitTests/depositInvitation.test.js
  packages/deploy-script-support/test/unitTests/findInvitationAmount.test.js
  packages/inter-protocol/test/price/fluxAggregatorKit.test.js
  packages/inter-protocol/test/vaultFactory/driver.js
  packages/inter-protocol/test/vaultFactory/replacePriceAuthority.test.js
  packages/inter-protocol/test/vaultFactory/vaultFactoryUtils.js
  packages/internal/src/tagged.d.ts
  packages/smart-wallet/index.js
  packages/smart-wallet/src/index.js
  packages/smart-wallet/src/marshal-contexts.js
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/src/types.ts
  packages/smart-wallet/src/walletFactory.js
  packages/smart-wallet/test/marshal-contexts.test.js
  packages/wallet/api/test/middleware.test.js
  packages/zoe/src/contractSupport/priceQuote.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/typeGuards.js
  packages/zoe/src/zoeService/makeInvitation.js
  packages/zoe/src/zoeService/offer/burnInvitation.js
  packages/zoe/src/zoeService/types-ambient.js
  packages/zoe/test/unitTests/contracts/coveredCall.test.js
  packages/zoe/tools/fakePriceAuthority.js
  packages/zoe/tools/manualPriceAuthority.js
  packages/zoe/tools/scriptedPriceAuthority.js
  packages/zoe/tools/test-utils.js
  tsconfig-build-options.json
  yarn.lock
Labels: automerge:rebase, bypass:integration

#10909 Fast USDC beta polish
  a3p-integration/proposals/b:beta-fast-usdc/.gitignore
  a3p-integration/proposals/b:beta-fast-usdc/.yarnrc.yml
  a3p-integration/proposals/b:beta-fast-usdc/README.md
  a3p-integration/proposals/b:beta-fast-usdc/package.json
  a3p-integration/proposals/b:beta-fast-usdc/test.sh
  a3p-integration/proposals/b:beta-fast-usdc/test/deploy.test.js
  a3p-integration/proposals/b:beta-fast-usdc/test/operators.test.js
  a3p-integration/proposals/b:beta-fast-usdc/test/test-cli.sh
  a3p-integration/proposals/b:beta-fast-usdc/yarn.lock
  a3p-integration/proposals/f:fast-usdc/README.md
  packages/fast-usdc/src/cli/cli.js
  packages/fast-usdc/src/cli/config-commands.js
  packages/fast-usdc/src/cli/config.js
  packages/fast-usdc/src/cli/transfer.js
  packages/fast-usdc/src/cli/util/agoric.js
  packages/fast-usdc/src/cli/util/bank.js
  packages/fast-usdc/src/cli/util/cctp.js
  packages/fast-usdc/src/cli/util/file.js
  packages/fast-usdc/src/cli/util/noble.js
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/exos/operator-kit.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/liquidity-pool.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/snapshots/advancer.test.ts.md
  packages/fast-usdc/test/exos/snapshots/advancer.test.ts.snap
  packages/fast-usdc/test/exos/snapshots/liquidity-pool.test.ts.md
  packages/fast-usdc/test/exos/snapshots/liquidity-pool.test.ts.snap
  packages/fast-usdc/test/exos/snapshots/settler.test.ts.md
  packages/fast-usdc/test/exos/snapshots/settler.test.ts.snap
  packages/fast-usdc/test/exos/snapshots/status-manager.test.ts.md
  packages/fast-usdc/test/exos/snapshots/status-manager.test.ts.snap
  packages/fast-usdc/test/exos/snapshots/transaction-feed.test.ts.md
  packages/fast-usdc/test/exos/snapshots/transaction-feed.test.ts.snap
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/exos/transaction-feed.test.ts
  packages/fast-usdc/test/supports.ts
  packages/fast-usdc/test/util/file.test.ts
  packages/internal/src/testing-utils.js
  packages/zoe/src/contractSupport/recorder.js
Labels: automerge:rebase

#9011 adopt EReturn type
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/test/upgrade/upgrade.test.js
  packages/SwingSet/tools/bundleTool.js
  packages/boot/test/bootstrapTests/ec-membership-update.test.ts
  packages/boot/test/bootstrapTests/net-ibc-upgrade.test.ts
  packages/boot/test/bootstrapTests/upgradeAPI.test.ts
  packages/boot/test/bootstrapTests/vow-offer-results.test.ts
  packages/boot/test/upgrading/upgrade-contracts.test.js
  packages/casting/test/interpose-net-access.test.js
  packages/client-utils/src/smart-wallet-kit.js
  packages/cosmic-swingset/src/chain-main.js
  packages/fast-usdc/test/cli/lp-commands.test.ts
  packages/fast-usdc/test/exos/advancer.test.ts
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/exos/status-manager.test.ts
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/governance/src/contractGovernorKit.js
  packages/governance/test/swingsetTests/contractGovernor/vat-voter.js
  packages/inter-protocol/src/auction/auctionBook.js
  packages/inter-protocol/src/price/fluxAggregatorKit.js
  packages/inter-protocol/src/price/priceOracleKit.js
  packages/inter-protocol/src/psm/psm.js
  packages/inter-protocol/src/reserve/assetReserve.js
  packages/inter-protocol/src/reserve/assetReserveKit.js
  packages/inter-protocol/src/vaultFactory/vault.js
  packages/inter-protocol/src/vaultFactory/vaultDirector.js
  packages/inter-protocol/src/vaultFactory/vaultKit.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/price/fluxAggregatorKit.test.js
  packages/inter-protocol/test/provisionPool.test.js
  packages/inter-protocol/test/smartWallet/oracle-integration.test.js
  packages/inter-protocol/test/vaultFactory/replacePriceAuthority.test.js
  packages/inter-protocol/test/vaultFactory/vaultFactory.test.js
  packages/inter-protocol/test/vaultFactory/vaultLiquidation.test.js
  packages/orchestration/src/utils/time.js
  packages/orchestration/test/examples/basic-flows.contract.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/make-test-coa-kit.ts
  packages/orchestration/test/exos/make-test-loa-kit.ts
  packages/orchestration/test/fixtures/query-flows.contract.test.ts
  packages/orchestration/test/utils/zcf-tools.test.ts
  packages/orchestration/test/utils/zoe-tools.test.ts
  packages/smart-wallet/src/smartWallet.js
  packages/smart-wallet/test/startWalletFactory.test.js
  packages/telemetry/src/flight-recorder.js
  packages/vats/src/core/lib-boot.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/localchain.js
  packages/vats/src/proposals/transfer-proposal.js
Labels: automerge:rebase, bypass:integration

#10904 feat(cosmic-swingset): Split inbound queue length metrics by queue name
  packages/cosmic-swingset/src/kernel-stats.js
  packages/cosmic-swingset/src/launch-chain.js
Labels: automerge:rebase

#10915 fix multichain-testing flake
  multichain-testing/package.json
  multichain-testing/scripts/deploy-cli.ts
  multichain-testing/tools/agd-lib.js
  multichain-testing/tools/deploy.ts
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/faucet-tools.ts
  multichain-testing/tools/noble-tools.ts
  multichain-testing/yarn.lock
Labels: automerge:rebase, force:integration

#10916 enable erasableSyntaxOnly with TypeScript 5.8
  multichain-testing/package.json
  multichain-testing/yarn.lock
  package.json
  packages/cosmic-proto/package.json
  packages/internal/test/ts-erasureSyntaxOnly.ts
  tsconfig.json
  yarn.lock
Labels: automerge:rebase

#10917 chore: export @agoric/store types
  packages/store/package.json
  packages/store/tsconfig.build.json
  packages/store/tsconfig.json
Labels: automerge:rebase, bypass:integration
