Repository Agoric/agoric-sdk, pull requests merged in 2025-09, with the labels that each got.

#11835 feat(cosmic-proto): add `Codec` and `CodecHelper`
  a3p-integration/proposals/z:acceptance/package.json
  a3p-integration/proposals/z:acceptance/test/wallet.test.js
  a3p-integration/proposals/z:acceptance/yarn.lock
  multichain-testing/scripts/cctp-lab.ts
  multichain-testing/scripts/noble-usdn-lab.ts
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/test/queries/chain-queries.test.ts
  multichain-testing/tools/ibc-transfer.ts
  packages/agoric-cli/src/publish.js
  packages/boot/test/orchestration/vat-orchestration.test.ts
  packages/client-utils/src/signing-client.ts
  packages/cosmic-proto/package.json
  packages/cosmic-proto/src/codec-helpers.ts
  packages/cosmic-proto/src/index.ts
  packages/cosmic-proto/test/helpers.test.js
  packages/cosmic-proto/test/snapshots/exports.test.js.md
  packages/cosmic-proto/test/snapshots/exports.test.js.snap
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/fixtures/query-flows.contract.js
  packages/orchestration/src/utils/packet.js
  packages/orchestration/test/examples/auto-stake-it.contract.test.ts
  packages/orchestration/test/examples/send-cctp.test.ts
  packages/orchestration/test/examples/unbond.contract.test.ts
  packages/orchestration/test/exos/chain-hub-transfer-routes.test.ts
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/fixtures/query-flows.contract.test.ts
  packages/orchestration/test/ibc-mocks.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/tx-encoding.test.ts
  packages/orchestration/test/types.test-d.ts
  packages/orchestration/tools/ibc-mocks.ts
  packages/portfolio-contract/src/pos-usdn.flows.ts
  packages/solo/src/chain-cosmos-sdk.js
  packages/vats/src/localchain.js
  packages/vats/src/proposals/localchain-test.js
Labels: tooling, hygiene, automerge:no-update, force:integration

#11855 chore: update resolver service to resolve gmp transactions
  services/ymax-planner/package.json
  services/ymax-planner/src/config.ts
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/main.ts
  services/ymax-planner/src/pending-tx-manager.ts
  services/ymax-planner/src/resolver.ts
  services/ymax-planner/src/subscription-manager.ts
  services/ymax-planner/src/support.ts
  services/ymax-planner/src/watchers/cctp-watcher.ts
  services/ymax-planner/src/watchers/gmp-watcher.ts
  services/ymax-planner/test/cctp-watcher.test.ts
  services/ymax-planner/test/config.test.ts
  services/ymax-planner/test/gmp-watcher.test.ts
  services/ymax-planner/test/mocks.ts
  services/ymax-planner/test/pending-tx.test.ts
  yarn.lock
Labels: automerge:rebase, bypass:integration, ymax

#11839 remove Vaults from acceptance testing
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/test/governance.test.js
  a3p-integration/proposals/z:acceptance/test/lib/vaults.ts
  a3p-integration/proposals/z:acceptance/test/oracles.test.js
  a3p-integration/proposals/z:acceptance/test/scripts/test-vaults.ts
  a3p-integration/proposals/z:acceptance/test/test-lib/utils.js
  a3p-integration/proposals/z:acceptance/test/test-lib/vaults.js
  a3p-integration/proposals/z:acceptance/test/vaults.test.js
  multichain-testing/ava.staking.config.js
Labels: automerge:rebase, force:integration

#11865 ymax planner secret from GCP
  services/ymax-planner/package.json
  services/ymax-planner/src/config.ts
  services/ymax-planner/src/main.ts
  services/ymax-planner/test/config.test.ts
  yarn.lock
Labels: automerge:rebase

#11857 feat(internal): `trace.sub(prefixStep, subEnable = enable)` logs prefix paths
  packages/internal/package.json
  packages/internal/src/debug.js
  packages/internal/src/types.ts
  packages/internal/test/debug-11845.test.js
  packages/internal/test/debug-11847.test.js
  packages/internal/test/debug-11849.test.js
  packages/internal/test/debug-demo.test.js
  yarn.lock
Labels: automerge:rebase

#11873 chore(ymax-planner): add tags for image pushing
  .github/workflows/docker.yml
Labels: automerge:rebase

#11832 feat: add support for gov v1 core eval msg
  golang/cosmos/Makefile
  golang/cosmos/app/app.go
  golang/cosmos/go.mod
  golang/cosmos/proto/agoric/swingset/msgs.proto
  golang/cosmos/scripts/mockgen.sh
  golang/cosmos/tests/integrations/vbank/vbank_test.go
  golang/cosmos/types/kv_entry_helpers.go
  golang/cosmos/x/swingset/keeper/keeper.go
  golang/cosmos/x/swingset/keeper/msg_server.go
  golang/cosmos/x/swingset/keeper/msg_server_test.go
  golang/cosmos/x/swingset/keeper/proposal.go
  golang/cosmos/x/swingset/keeper/querier.go
  golang/cosmos/x/swingset/keeper/test_utils.go
  golang/cosmos/x/swingset/testing/queue.go
  golang/cosmos/x/swingset/testutil/mocks.go
  golang/cosmos/x/swingset/types/expected_keepers.go
  golang/cosmos/x/swingset/types/msgs.go
  golang/cosmos/x/swingset/types/msgs.pb.go
  golang/cosmos/x/vstorage/keeper/grpc_query.go
  golang/cosmos/x/vstorage/keeper/keeper.go
  golang/cosmos/x/vstorage/keeper/keeper_test.go
  golang/cosmos/x/vstorage/keeper/querier.go
  golang/cosmos/x/vstorage/vstorage.go
  packages/client-utils/src/codegen/agoric/swingset/msgs.rpc.msg.ts
  packages/client-utils/src/codegen/agoric/swingset/msgs.ts
  packages/cosmic-proto/proto/agoric/swingset/msgs.proto
  packages/cosmic-proto/src/codegen/agoric/swingset/msgs.ts
  packages/cosmic-proto/src/codegen/typeFromUrl.ts
  packages/cosmic-proto/test/snapshots/exports.test.js.md
  packages/cosmic-proto/test/snapshots/exports.test.js.snap
Labels: automerge:no-update, agoric-cosmos

#11876 fix: clean up portfolio `parseInboundPacket` and noisy logged errors
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/test/portfolio.exo.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/vats/tools/fake-bridge.js
Labels: automerge:no-update, agd, force:integration, orchestration, ymax

#11843 chore(docs): add sequence diagram for withdraw
  packages/portfolio-contract/DESIGN-BETA.md
Labels: automerge:squash, bypass:integration

#11814 feat(ymax-planner): Require direct vstorage read block height to be at or after the triggering event
  packages/client-utils/src/vstorage.js
  packages/internal/src/lib-chainStorage.js
  services/ymax-planner/src/cosmos-rpc.ts
  services/ymax-planner/src/engine.ts
Labels: automerge:rebase

#11833 feat(portfolio-contract): better output using `tracer.sub(prefix)`
  packages/portfolio-contract/src/portfolio.flows.ts
Labels: logging, automerge:rebase

#11871 chore(ymax-planner): monitor and resolve transfers to a noble account
  packages/portfolio-contract/src/resolver/types.ts
  packages/portfolio-contract/test/resolver.exo.test.ts
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/pending-tx-manager.ts
  services/ymax-planner/src/watchers/cctp-watcher.ts
  services/ymax-planner/src/watchers/gmp-watcher.ts
  services/ymax-planner/src/watchers/noble-watcher.ts
  services/ymax-planner/test/cctp-watcher.test.ts
  services/ymax-planner/test/gmp-watcher.test.ts
  services/ymax-planner/test/mocks.ts
  services/ymax-planner/test/noble-watcher.test.ts
  services/ymax-planner/test/pending-tx.test.ts
Labels: automerge:rebase, bypass:integration, ymax

#11864 feat(cosmos): Next upgrade is agoric-upgrade-22
  a3p-integration/proposals/a:before-upgrade-22/.yarnrc.yml
  a3p-integration/proposals/a:before-upgrade-22/README.md
  a3p-integration/proposals/a:before-upgrade-22/eval.sh
  a3p-integration/proposals/a:before-upgrade-22/package.json
  a3p-integration/proposals/a:before-upgrade-22/test.sh
  a3p-integration/proposals/a:before-upgrade-22/test/initial.test.js
  a3p-integration/proposals/a:before-upgrade-22/tsconfig.json
  a3p-integration/proposals/a:before-upgrade-22/yarn.lock
  a3p-integration/proposals/b:upgrade-22/.gitignore
  a3p-integration/proposals/b:upgrade-22/.yarnrc.yml
  a3p-integration/proposals/b:upgrade-22/README.md
  a3p-integration/proposals/b:upgrade-22/package.json
  a3p-integration/proposals/b:upgrade-22/test.sh
  a3p-integration/proposals/b:upgrade-22/test/initial.test.js
  a3p-integration/proposals/b:upgrade-22/tsconfig.json
  a3p-integration/proposals/b:upgrade-22/yarn.lock
  a3p-integration/proposals/k:param-change/drop-ist.json
  a3p-integration/proposals/n:upgrade-next/README.md
  golang/cosmos/app/upgrade.go
Labels: force:integration

#11903 fix(cosmos): snapshot init error is not fatal
  golang/cosmos/app/app.go
Labels: automerge:squash

#11906 u22 cherrypicks round 2
  golang/cosmos/app/app.go
Labels: automerge:rebase, force:integration

#11909 chore: fix ethereum tokenMessenger address
  packages/portfolio-deploy/src/axelar-configs.js
Labels: automerge:rebase, bypass:integration, ymax

#11916 chore(multichain-testing): Fix lint issues
  multichain-testing/tools/wallet-store-reflect.ts
Labels: automerge:squash

#11914 feat(ymax-planner): Account for Axelar Cosmos-EVM fees
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/tools/portfolio-actors.ts
  services/ymax-planner/README.md
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/main.ts
  services/ymax-planner/src/plan-deposit.ts
  services/ymax-planner/test/deposit-tools.test.ts
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.md
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.snap
Labels: automerge:rebase, ymax

#11910 chore(golang/cosmos): Treat mainfork like mainnet in upgrade.go
  golang/cosmos/app/upgrade.go
Labels: automerge:squash

#11920 Ymax Config: Adding Addresses for new Protocols
  packages/portfolio-api/src/constants.js
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/contract-setup.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-deploy/src/axelar-configs.js
  packages/portfolio-deploy/src/portfolio-start.core.js
  packages/portfolio-deploy/test/contract-control.test.ts
  packages/portfolio-deploy/test/portfolio.test.ts
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.snap
  services/ymax-planner/test/deposit-tools.test.ts
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.md
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.snap
Labels: automerge:rebase, ymax

#11937 fix(ymax-planner): Document optionality of agoricNetSubdomain config
  packages/client-utils/src/network-config.js
  services/ymax-planner/src/config.ts
Labels: automerge:squash

#11929 feat(ymax-planner): Respond to portfolio-level vstorage events
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/vstorage-utils.ts
Labels: automerge:rebase

#11925 feat(internal): Add utilities from ymax-planner
  packages/internal/README.md
  packages/internal/src/index.js
  packages/internal/src/js-utils.js
  packages/internal/src/ses-utils.js
  packages/internal/src/work-pool.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/internal/test/utils.test.js
  packages/internal/test/work-pool.test.js
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/vstorage-utils.ts
Labels: automerge:rebase

#11941 docs(portfolio-contract): updated high level system design
  packages/portfolio-contract/DESIGN-BETA.md
Labels: automerge:rebase, bypass:integration

#11942 chore: clean up lint uncovered in ymax contract
  eslint.config.mjs
  packages/portfolio-contract/eslint.config.js
  packages/portfolio-contract/package.json
  packages/portfolio-contract/src/planner.exo.ts
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/src/pos-usdn.flows.ts
  packages/portfolio-contract/src/resolver/resolver.exo.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/cctp-resolver.test.ts
  packages/portfolio-contract/test/contract-setup.ts
  packages/portfolio-contract/test/offer-shapes.test.ts
  packages/portfolio-contract/test/planner.exo.test.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.exo.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/rebalance-grok.test.ts
  packages/portfolio-contract/test/resolver-helpers.ts
  packages/portfolio-contract/test/resolver.exo.test.ts
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-contract/test/ymax-scenario.test.ts
  packages/portfolio-contract/tools/agents-mock.ts
  packages/portfolio-contract/tools/portfolio-actors.ts
  packages/portfolio-contract/tools/rebalance-grok.ts
  packages/portfolio-contract/tools/wallet-offer-tools.ts
  packages/portfolio-contract/tsconfig.json
  yarn.lock
Labels: automerge:rebase

#11939 fix(ymax-planner): Treat only direct children of published.ymax0.portfolios as portfolio paths
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/vstorage-utils.ts
  services/ymax-planner/test/vstorage-utils.test.ts
Labels: automerge:squash

#11944 Add Arb/Base Sepolia factory address
  packages/portfolio-deploy/src/axelar-configs.js
Labels: automerge:rebase, ymax

#11952 chore: fixed stream cell parsing
  services/ymax-planner/src/engine.ts
Labels: automerge:rebase, ymax

#11963 feat!: vstorage preview of ymax steps
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/offer-shapes.test.ts
  packages/portfolio-contract/test/portfolio.exo.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/tools/portfolio-actors.ts
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.snap
Labels: automerge:rebase

#11932 feat(ymax-planner): Calculate steps by linear programming over a model of the blockchain network
  .prettierrc.json5
  multichain-testing/scripts/ymax-tool.ts
  packages/portfolio-contract/package.json
  packages/portfolio-contract/solver-approach-design.md
  packages/portfolio-contract/src/graph-diagnose.ts
  packages/portfolio-contract/src/jsLPSolver.md
  packages/portfolio-contract/src/network/buildGraph.ts
  packages/portfolio-contract/src/network/network-spec.ts
  packages/portfolio-contract/src/network/network.prod.ts
  packages/portfolio-contract/src/network/path.ts
  packages/portfolio-contract/src/plan-rebalance.ts
  packages/portfolio-contract/src/plan-solve.ts
  packages/portfolio-contract/src/plan-transfers.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/test/network/buildGraph.test.ts
  packages/portfolio-contract/test/network/test-network.ts
  packages/portfolio-contract/test/plan-deposit-transfers.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/rebalance.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/tools/portfolio-actors.ts
  services/ymax-planner/src/plan-deposit.ts
  services/ymax-planner/test/deposit-tools.test.ts
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.md
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.snap
  yarn.lock
Labels: automerge:rebase

#11989 chore(resolver): increase timeout to 20 min
  services/ymax-planner/src/pending-tx-manager.ts
  services/ymax-planner/src/watchers/cctp-watcher.ts
  services/ymax-planner/src/watchers/gmp-watcher.ts
  services/ymax-planner/src/watchers/noble-watcher.ts
  services/ymax-planner/test/pending-tx.test.ts
Labels: automerge:rebase, bypass:integration, ymax

#11992 fix: allow unhardened arg to sendBridgeAction
  packages/client-utils/src/signing-smart-wallet-kit.ts
  packages/client-utils/test/signing-smart-wallet-kit.test.ts
Labels: automerge:rebase, bypass:integration, queued

#11980 feat(orchestration): new `*WithMeta(...)` methods
  .github/workflows/multichain-e2e.yml
  multichain-testing/Makefile
  multichain-testing/scripts/get-namespace.sh
  multichain-testing/tools/chaind-lib.js
  packages/cosmic-proto/package.json
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/network/README.md
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/auto-stake-it-tap-kit.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/exos/ibc-packet.js
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/src/exos/packet-tools.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/address.js
  packages/orchestration/src/utils/cosmos.js
  packages/orchestration/src/utils/orchestrationAccount.js
  packages/orchestration/test/cosmos-interchain-service.test.ts
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
  packages/orchestration/test/staking-ops.test.ts
  packages/orchestration/test/tx-encoding.test.ts
  packages/orchestration/test/types.test-d.ts
  packages/orchestration/test/utils/address.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/vats/src/ibc.js
  packages/vats/src/proposals/network-proposal.js
  packages/vats/src/types.ts
  packages/vats/test/ibc-utils.test.js
  packages/vats/test/network.test.js
  packages/vats/tools/ibc-utils.js
Labels: automerge:no-update, force:integration, ymax, queued

#11997 chore: publish flowN.steps before provideXYZAccount(...)
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
Labels: automerge:rebase, bypass:integration, queued

#11999 `ymax-tools` picks config based on `AGORIC_NET`
  multichain-testing/scripts/ymax-tool.ts
Labels: automerge:rebase, ymax, queued

#11875 ymaxControl mainnet tooling
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/tools/wallet-store-reflect.ts
  multichain-testing/ymax-ops/.gitignore
  multichain-testing/ymax-ops/Makefile
  packages/portfolio-deploy/package.json
  packages/portfolio-deploy/src/vstorage-outdated.js
Labels: automerge:rebase, bypass:integration, queued

#11996 fix(ymax-planner): Ignore policy rebalanceCount increments
  multichain-testing/scripts/ymax-tool.ts
  services/ymax-planner/src/engine.ts
Labels: automerge:rebase, queued

#11995 feat!: withdraw in coordination with ymax planner
  packages/portfolio-contract/DESIGN-BETA.md
  packages/portfolio-contract/src/planner.exo.ts
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/pos.exo.ts
  packages/portfolio-contract/src/resolver/resolver.exo.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/offer-shapes.test.ts
  packages/portfolio-contract/test/planner.exo.test.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.exo.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-contract/tools/agents-mock.ts
  packages/portfolio-contract/tools/portfolio-actors.ts
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.snap
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.snap
Labels: automerge:rebase, bypass:integration

#12004 Make deposit/withdraw helpers use NatValue for target allocations
  services/ymax-planner/src/plan-deposit.ts
Labels: bypass:integration, bypass:automerge

#12013 chore(ymax-planner): Minor cleanup
  packages/portfolio-contract/tools/plan-solve.ts
  services/ymax-planner/src/config.ts
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/gas-estimation.ts
  services/ymax-planner/src/main.ts
  services/ymax-planner/src/plan-deposit.ts
  services/ymax-planner/test/mocks.ts
Labels: automerge:rebase, queued

#12015 chore!(portfolio-contract): add stateShape to the 4 exos
  packages/portfolio-contract/src/planner.exo.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/pos.exo.ts
  packages/portfolio-contract/src/resolver/resolver.exo.ts
  packages/portfolio-contract/test/portfolio.exo.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.exo.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.exo.test.ts.snap
Labels: automerge:rebase, bypass:integration, queued

#11991 feat(portfolio-contract): creatorFacet.withdrawFees
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
Labels: automerge:rebase, bypass:integration, queued

#12019 chore: increase resolver timeout and document CCTP_TO_NOBLE denom
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/pending-tx-manager.ts
Labels: automerge:rebase, bypass:integration, ymax, queued

#12023 ci(Mergify): don't label on queuing
  .mergify.yml
Labels: bypass:integration, bypass:automerge

#12024 test: use noble1test for Noble ICA instead of cosmos1test
  packages/portfolio-contract/src/pos-gmp.flows.ts
  packages/portfolio-contract/test/contract-setup.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-deploy/test/portfolio-start.core.test.ts
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.snap
Labels: automerge:rebase, bypass:integration

#12025 chore(ymax-planner): manually copy highs.wasm to the right place
  services/ymax-planner/Dockerfile
Labels: automerge:squash, bypass:integration
