Repository Agoric/agoric-sdk, pull requests merged in 2025-03, with the labels that each got.

#11054 chore: Update feeConfig.variableRate to 0.5%, i.e. 5n/1000n
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/update-noble-ica.core.js
Labels: automerge:rebase, force:integration

#11060 test: multichain for Fast USDC noble ICA update
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/fast-usdc/fu-actors.ts
  multichain-testing/test/support.ts
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/src/exos/cosmos-orchestration-account.js
Labels: automerge:rebase, force:integration

#11066 fix: minted early tracking
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/utils/store.js
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/utils/store.test.js
  packages/store/src/stores/store-utils.js
Labels: automerge:rebase

#11052 fix: Properly synchronize slog sender termination
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/slogger.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/internal/src/node/fs-stream.js
  packages/telemetry/src/flight-recorder.js
  packages/telemetry/src/index.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/test/flight-recorder.test.js
Labels: automerge:rebase, force:integration

#11071 chore: u19 cherrypicks
  golang/cosmos/go.mod
  golang/cosmos/go.sum
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/slogger.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/internal/src/node/fs-stream.js
  packages/telemetry/src/flight-recorder.js
  packages/telemetry/src/index.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/test/flight-recorder.test.js
Labels: force:integration

#11059 Use a single atomicRearrange for liquidityPool repay
  packages/fast-usdc/src/exos/liquidity-pool.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/pool-share-math.test.ts
Labels: Zoe Contract, automerge:rebase

#11070 improve error handling
  packages/fast-usdc/src/exos/advancer.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/exos/transaction-feed.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/test/exos/transaction-feed.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/src/exos/packet-tools.js
  packages/orchestration/src/utils/zoe-tools.js
Labels: automerge:rebase, force:integration

#11073 chore: 0.1% variable rate
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/fast-usdc/src/update-noble-ica.core.js
Labels: automerge:rebase

#11051 test(xsnap): Verify npm install build process
  packages/xsnap/package.json
  packages/xsnap/test/install.test.js
  yarn.lock
Labels: automerge:rebase

#9674 refactor(xsnap): Cleanup build.js
  packages/xsnap/src/build.js
Labels: automerge:rebase

#10816 feat: Run monitoring follower with acceptance testing
  .github/workflows/integration.yml
  a3p-integration/package.json
  a3p-integration/proposals/z:acceptance/host/before-test-run.sh
  a3p-integration/proposals/z:acceptance/setup-test.sh
  a3p-integration/proposals/z:acceptance/test.sh
  a3p-integration/proposals/z:acceptance/wait-for-follower.mjs
  a3p-integration/yarn.lock
Labels: automerge:squash, force:integration

#11056 fix(vats): `vats/init-core.js` relies on econCommittee
  packages/cosmic-swingset/Makefile
  packages/cosmic-swingset/test/make.test.js
  packages/cosmic-swingset/test/scenario2.js
  packages/telemetry/src/flight-recorder.js
  packages/vats/src/core/promise-space.js
  packages/vats/src/core/startWalletFactory.js
  packages/vats/src/nameHub.js
  packages/vats/test/name-hub-published.test.js
  packages/vats/test/promise-space.test.js
Labels: bug, wallet, Inter-protocol, automerge:no-update

#11088 chore: cherrypicks for rc2
  .dockerignore
  README.md
  packages/builders/scripts/vats/upgrade-mintHolder.js
  repoconfig.sh
Labels: force:integration

#11090 chore(release): publish `upgrade-19-rc2`
  packages/agoric-cli/CHANGELOG.md
  packages/agoric-cli/package.json
  packages/benchmark/CHANGELOG.md
  packages/benchmark/package.json
  packages/boot/CHANGELOG.md
  packages/boot/package.json
  packages/builders/CHANGELOG.md
  packages/builders/package.json
  packages/cosmic-swingset/CHANGELOG.md
  packages/cosmic-swingset/package.json
  packages/create-dapp/CHANGELOG.md
  packages/create-dapp/package.json
  packages/solo/CHANGELOG.md
  packages/solo/package.json
Labels: force:integration

#11089 logging for multichain flake
  .github/workflows/multichain-e2e-template.yml
  multichain-testing/Makefile
  multichain-testing/scripts/fast-usdc-tool.ts
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/tools/batchQuery.js
  multichain-testing/tools/block-iter.js
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/query.ts
  multichain-testing/tools/queryKit.js
  packages/inter-protocol/src/provisionPoolKit.js
Labels: automerge:rebase, force:integration

#11079 fix(fast-usdc): disallow all non-positive integer counts in Multiset
  packages/fast-usdc/src/utils/store.js
  packages/fast-usdc/test/utils/store.test.js
Labels: automerge:squash

#11094 fix fund-provision-pool
  .github/copilot-instructions.md
  multichain-testing/Makefile
  multichain-testing/scripts/fund-provision-pool.ts
  multichain-testing/tools/agd-lib.js
  multichain-testing/tools/noble-tools.ts
Labels: automerge:rebase, force:integration

#11096 feat!: remove IBC relayer commands
  packages/agoric-cli/README.md
  packages/agoric-cli/registry.yaml
  packages/agoric-cli/src/main.js
Labels: automerge:rebase

#11099 misc Orchestration improvements for factoring out Fast USDC
  multichain-testing/config.fusdc.go-relayer.yaml
  multichain-testing/config.fusdc.yaml
  multichain-testing/config.go-relayer.yaml
  multichain-testing/config.yaml
  multichain-testing/package.json
  multichain-testing/patches/node-fetch+2.7.0.patch
  multichain-testing/patches/protobufjs+6.11.4.patch
  multichain-testing/scripts/fund-provision-pool.ts
  multichain-testing/yarn.lock
  packages/boot/test/bootstrapTests/lca.test.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/vow-offer-results.test.ts
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/orchestration/contract-upgrade.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/fast-usdc/src/cli/config.js
  packages/fast-usdc/src/cli/transfer.js
  packages/fast-usdc/src/distribute-fees.core.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/exos/status-manager.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/src/start-fast-usdc.core.js
  packages/fast-usdc/src/update-noble-ica.core.js
  packages/fast-usdc/test/fast-usdc.contract.test.ts
  packages/fast-usdc/test/type-guards.test.ts
  packages/fast-usdc/test/utils/chain-policies.test.ts
  packages/vats/src/core/types-ambient.d.ts
  packages/vm-config/decentral-itest-orchestration-chains-config.json
  packages/vm-config/decentral-itest-orchestration-config.json
  packages/zoe/exported.d.ts
Labels: automerge:rebase

#11074 test(cosmic-swingset): create `vstorage metrics` test.
  packages/cosmic-swingset/test/make.test.js
Labels: test, automerge:squash

#11105 build(cosmos): use latest `agoric-labs/ibc-go` branch
  golang/cosmos/e2e_test/go.mod
  golang/cosmos/e2e_test/go.sum
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: automerge:no-update

#11103 ensure `Advancer` has latest `Settler` reference
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/bootstrapTests/walletFactory.ts
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/boot/tools/supports.ts
  packages/builders/scripts/fast-usdc/fast-usdc-settler-ref.build.js
  packages/fast-usdc/src/exos/settler.js
  packages/fast-usdc/src/fast-usdc.contract.js
  packages/fast-usdc/src/update-settler-reference.core.js
  packages/fast-usdc/test/exos/settler.test.ts
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/tools/ibc-mocks.ts
Labels: automerge:rebase, force:integration

#11114 chore: u19 cherrypicks for rc3
  golang/cosmos/e2e_test/go.mod
  golang/cosmos/e2e_test/go.sum
  golang/cosmos/go.mod
  golang/cosmos/go.sum
Labels: force:integration

#11120 feat: `update-fee-config` proposal
  packages/boot/test/fast-usdc/fast-usdc.test.ts
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.md
  packages/boot/test/fast-usdc/snapshots/fast-usdc.test.ts.snap
  packages/builders/scripts/fast-usdc/fast-usdc-fee-config.build.js
  packages/fast-usdc/src/update-fee-config.core.js
Labels: automerge:rebase

#11121 fix: remove `intermediateRecipient` from `ForwardInfo`
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/test/exos/chain-hub-transfer-routes.test.ts
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
Labels: automerge:rebase

#11122 fix(agoric-cli): Specify active directory when querying workspaces
  packages/agoric-cli/src/install.js
  packages/agoric-cli/src/lib/packageManager.js
Labels: automerge:squash

#11124 refactor(send-anywhere): simplify denom lookup
  packages/boot/test/orchestration/contract-upgrade.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/send-anywhere.flows.js
  packages/orchestration/test/examples/send-anywhere.test.ts
Labels: automerge:rebase, force:integration

#11129 chore(ci): add `waitForBlock(1)` logic to `scripts/fund-provision-pool.ts`
  multichain-testing/scripts/fund-provision-pool.ts
  multichain-testing/tools/e2e-tools.js
Labels: automerge:rebase, force:integration

#11110 Fast USDC rc2 a3p test
  a3p-integration/package.json
  a3p-integration/proposals/g:gtm-fast-usdc/package.json
  a3p-integration/proposals/g:gtm-fast-usdc/test/deploy.test.js
  a3p-integration/proposals/g:gtm-fast-usdc/yarn.lock
  multichain-testing/tools/agd-lib.js
  multichain-testing/tools/noble-tools.ts
  multichain-testing/tools/relayer-tools.ts
  packages/agoric-cli/src/lib/chain.js
Labels: automerge:rebase, force:integration

#11141 chore(boot): Fix JSDoc warnings
  packages/boot/tools/supports.ts
Labels: automerge:squash

#11139 refactor: Consolidate `tmpDir` definitions into a package "internal" export
  a3p-integration/proposals/z:acceptance/yarn.lock
  packages/SwingSet/test/transcript/state-sync-reload.test.js
  packages/SwingSet/test/vat-admin/slow-termination/slow-termination.test.js
  packages/access-token/package.json
  packages/access-token/test/state.test.js
  packages/access-token/test/tmp.js
  packages/access-token/test/token.test.js
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/tools/test-kit.js
  packages/internal/src/index.js
  packages/internal/src/tmpDir.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/swing-store/test/bundles.test.js
  packages/swing-store/test/deletion.test.js
  packages/swing-store/test/export.test.js
  packages/swing-store/test/exportImport.test.js
  packages/swing-store/test/import.test.js
  packages/swing-store/test/repair-metadata.test.js
  packages/swing-store/test/snapstore.test.js
  packages/swing-store/test/state.test.js
  packages/swing-store/test/util.js
Labels: automerge:rebase

#11137 normalize package privacy
  .github/workflows/test-all-packages.yml
  package.json
  packages/agoric-cli/src/sdk-package-names.js
  packages/benchmark/benchmark/benchmark-liquidation.js
  packages/benchmark/doc/benchmarkerator.md
  packages/benchmark/package.json
  packages/benchmark/src/benchmarkerator.js
  packages/boot/package.json
  packages/deployment/package.json
  packages/fast-usdc/README.md
  packages/swingset-runner/package.json
  packages/vm-config/README.md
  scripts/verify-package-names.js
  tsconfig.json
Labels: automerge:rebase, force:integration

#11147 refactor(ertp,zoe): minor types gardening
  packages/ERTP/src/amountMath.js
  packages/zoe/src/contractFacet/zcfMint.js
  packages/zoe/src/contractFacet/zcfSeat.js
  packages/zoe/src/contractFacet/zcfZygote.js
  packages/zoe/src/contractSupport/atomicTransfer.js
  packages/zoe/src/contracts/autoswap.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/src/contracts/valueVow.contract.js
  packages/zoe/src/zoeService/types.ts
  packages/zoe/src/zoeService/zoeStorageManager.js
  packages/zoe/test/offerArgsUsageContract.js
  packages/zoe/test/unitTests/blockedOffers.test.js
  packages/zoe/test/unitTests/bounty.js
  packages/zoe/test/unitTests/zcf/zcfSeat.test.js
Labels: automerge:squash

#11138 chore(cosmic-swingset): Fix some broken README links
  packages/cosmic-swingset/README.md
Labels: automerge:squash

#10480 convert fast-usdc contract to .ts
  packages/fast-usdc-contract/src/exos/advancer.js
  packages/fast-usdc-contract/src/exos/operator-kit.ts
  packages/fast-usdc-contract/src/exos/settler.js
  packages/fast-usdc-contract/src/exos/status-manager.ts
  packages/fast-usdc-contract/src/exos/transaction-feed.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/src/fast-usdc.flows.js
  packages/fast-usdc-contract/src/fast-usdc.flows.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/exos/status-manager.test.ts
  packages/fast-usdc-contract/test/exos/transaction-feed.test.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-deploy/src/fast-usdc-fee-config.build.js
  packages/fast-usdc-deploy/src/fast-usdc-reconfigure.build.js
  packages/fast-usdc-deploy/src/fast-usdc-settler-ref.build.js
  packages/fast-usdc-deploy/src/start-fast-usdc.build.js
  packages/fast-usdc-deploy/src/start-fast-usdc.core.js
Labels: automerge:rebase

#11155 retry install-bundle in multichain test
  multichain-testing/scripts/fund-provision-pool.ts
  multichain-testing/tools/e2e-tools.js
Labels: automerge:rebase, force:integration

#11143 chore(scripts): add base release initializer
  MAINTAINERS.md
  scripts/init-release.sh
Labels: automerge:rebase, SRE

#11163 complete conversion of fast-usdc-contract to .ts
  multichain-testing/tools/batchQuery.js
  packages/ERTP/src/amountMath.js
  packages/SwingSet/src/vats/plugin-manager.js
  packages/fast-usdc-contract/src/exos/advancer.ts
  packages/fast-usdc-contract/src/exos/liquidity-pool.ts
  packages/fast-usdc-contract/src/exos/settler.ts
  packages/fast-usdc-contract/src/exos/transaction-feed.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/src/utils/store.ts
  packages/fast-usdc-contract/src/utils/zoe.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/exos/liquidity-pool.test.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/mocks.ts
  packages/fast-usdc-contract/test/utils/store.test.js
  packages/fast-usdc-contract/tsconfig.json
  packages/fast-usdc/src/cli/lp-commands.js
  packages/fast-usdc/src/type-guards.js
  packages/orchestration/src/examples/auto-stake-it-tap-kit.js
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/vats/tools/fake-bridge.js
  packages/vow/src/E.js
  packages/zoe/src/contractFacet/types.ts
  packages/zoe/src/contractSupport/ratio.js
  packages/zoe/src/zoeService/utils.d.ts
Labels: automerge:rebase

#11131 feat: `chainHub` supports `CAIP-2` chain info
  multichain-testing/test/support.ts
  packages/boot/test/bootstrapTests/orchestration.test.ts
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.md
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/builders/scripts/testing/append-chain-info.js
  packages/builders/scripts/testing/tweak-chain-info.js
  packages/builders/test/snapshots/orchestration-imports.test.js.md
  packages/builders/test/snapshots/orchestration-imports.test.js.snap
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc-deploy/src/fast-usdc-evm-solana.build.js
  packages/fast-usdc-deploy/src/upgrade-evm-solana.core.js
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  packages/fast-usdc/src/type-guards.js
  packages/orchestration/src/cctp-chain-info.js
  packages/orchestration/src/chain-capabilities.js
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/ethereum-api.ts
  packages/orchestration/src/examples/swap.contract.js
  packages/orchestration/src/exos/chain-hub-admin.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/orchestrator.js
  packages/orchestration/src/exos/remote-chain-facade.js
  packages/orchestration/src/fetched-chain-info.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/typeGuards.js
  packages/orchestration/src/types.ts
  packages/orchestration/src/utils/registry.js
  packages/orchestration/src/utils/start-helper.js
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/examples/staking-combinations.test.ts
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/facade-durability.test.ts
  packages/orchestration/test/snapshots/chain-info.test.js.md
  packages/orchestration/test/snapshots/chain-info.test.js.snap
  packages/orchestration/test/snapshots/exports.test.ts.md
  packages/orchestration/test/snapshots/exports.test.ts.snap
Labels: automerge:rebase, force:integration

#11164 test incarnation number in RunUtils/boot tests
  packages/boot/tools/supports.ts
  packages/cosmic-swingset/test/inquisitor.test.js
  packages/cosmic-swingset/tools/inquisitor.mjs
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
Labels: automerge:rebase

#11165 disable jsdoc/require-param
  eslint.config.mjs
  packages/boot/tools/supports.ts
  packages/fast-usdc-contract/src/exos/operator-kit.ts
  packages/fast-usdc-contract/src/exos/transaction-feed.ts
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/test/exos/advancer.test.ts
  packages/fast-usdc-contract/test/exos/settler.test.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-contract/tsconfig.json
  packages/fast-usdc/src/types.ts
  packages/inter-protocol/src/provisionPoolKit.js
  packages/vats/src/localchain.js
  packages/vats/src/transfer.js
Labels: automerge:rebase

#11159 fix(ci): Race condition in wait-for-follower script
  a3p-integration/proposals/z:acceptance/wait-for-follower.mjs
Labels: automerge:squash, force:integration

#11132 feat: Report cosmic-swingset metrics from a slog sender
  a3p-integration/proposals/z:acceptance/yarn.lock
  docs/env.md
  multichain-testing/yarn.lock
  packages/SwingSet/src/controller/controller.js
  packages/SwingSet/src/kernel/kernel.js
  packages/SwingSet/src/kernel/metrics.js
  packages/SwingSet/src/kernel/slogger.js
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/src/kernel/state/stats.js
  packages/SwingSet/src/kernel/vat-warehouse.js
  packages/SwingSet/src/lib/message.js
  packages/SwingSet/src/types-external.js
  packages/SwingSet/test/gc-kernel-orphan.test.js
  packages/SwingSet/test/gc-kernel.test.js
  packages/SwingSet/test/state.test.js
  packages/cosmic-swingset/README-telemetry.md
  packages/cosmic-swingset/src/chain-main.js
  packages/cosmic-swingset/src/kernel-stats.js
  packages/cosmic-swingset/src/launch-chain.js
  packages/cosmic-swingset/test/make.test.js
  packages/cosmic-swingset/test/prometheus.test.js
  packages/cosmic-swingset/test/snapshots/prometheus.test.js.md
  packages/cosmic-swingset/test/snapshots/prometheus.test.js.snap
  packages/cosmic-swingset/tools/prometheus.js
  packages/internal/package.json
  packages/internal/src/index.js
  packages/internal/src/js-utils.js
  packages/internal/src/metrics.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/solo/src/start.js
  packages/swingset-runner/src/push-metrics.js
  packages/telemetry/src/index.js
  packages/telemetry/src/make-slog-sender.js
  packages/telemetry/src/otel-metrics.js
  packages/telemetry/src/prometheus.js
  packages/telemetry/src/slog-sender-pipe-entrypoint.js
  packages/telemetry/src/slog-sender-pipe.js
  packages/vow/src/watch-utils.js
Labels: automerge:rebase, force:integration

#11171 252 simplify parse account
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/address.js
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/utils/address.test.ts
Labels: automerge:rebase, orchestration

#11170 feat: register CCTP chains in FUSDC `ChainHub`
  packages/boot/test/bootstrapTests/snapshots/orchestration.test.ts.snap
  packages/boot/test/orchestration/lca.test.ts
  packages/boot/test/orchestration/orchestration.test.ts
  packages/boot/test/orchestration/snapshots/orchestration.test.ts.md
  packages/boot/test/orchestration/snapshots/orchestration.test.ts.snap
  packages/boot/test/orchestration/vat-orchestration.test.ts
  packages/builders/scripts/testing/tweak-chain-info.js
  packages/fast-usdc-contract/src/fast-usdc.contract.ts
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/fast-usdc-contract/test/supports.ts
  packages/fast-usdc-deploy/src/update-noble-ica.core.js
  packages/fast-usdc-deploy/src/upgrade-evm-solana.core.js
  packages/fast-usdc-deploy/src/utils/deploy-config.js
  packages/fast-usdc-deploy/test/snapshots/fast-usdc.test.ts.md
  packages/fast-usdc/src/types.ts
  packages/fast-usdc/test/chain-info.test.js
  packages/orchestration/src/chain-capabilities.js
  packages/orchestration/src/chain-info.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/utils/chain-hub-helper.js
  packages/orchestration/test/chain-info.test.js
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/exos/chain-hub.test.ts
  packages/orchestration/test/snapshots/chain-info.test.js.md
  packages/orchestration/test/snapshots/chain-info.test.js.snap
  packages/orchestration/test/types.test-d.ts
Labels: automerge:rebase

#11180 test(cosmic-swingset): Add 20% fuzziness for comparing "heapStats_total_global_handles_size"
  packages/cosmic-swingset/test/prometheus.test.js
Labels: automerge:squash

#11184 move Ratio lib to ERTP
  a3p-integration/proposals/n:upgrade-next/test/replaceFeeDistributor.test.js
  a3p-integration/proposals/z:acceptance/test/test-lib/vaults.js
  multichain-testing/scripts/fast-usdc-tool.ts
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  packages/ERTP/src/ratio.js
  packages/ERTP/src/safeMath.js
  packages/ERTP/test/unitTests/ratio.test.js
  packages/fast-usdc-contract/test/fast-usdc.contract.test.ts
  packages/fast-usdc-contract/test/mocks.ts
  packages/fast-usdc-deploy/src/fast-usdc-fees.build.js
  packages/fast-usdc-deploy/src/start-fast-usdc.build.js
  packages/fast-usdc-deploy/src/update-noble-ica.core.js
  packages/fast-usdc-deploy/test/fast-usdc.test.ts
  packages/fast-usdc-deploy/test/utils/config-marshal.test.js
  packages/fast-usdc/src/cli/lp-commands.js
  packages/fast-usdc/src/pool-share-math.js
  packages/fast-usdc/src/utils/fees.js
  packages/fast-usdc/test/cli/lp-commands.test.ts
  packages/fast-usdc/test/pool-share-math.test.ts
  packages/fast-usdc/test/utils/fees.test.ts
  packages/governance/src/contractGovernance/assertions.js
  packages/inter-protocol/src/clientSupport.js
  packages/inter-protocol/src/interest-math.js
  packages/inter-protocol/src/interest.js
  packages/inter-protocol/src/proposals/addAssetToVault.js
  packages/inter-protocol/src/vaultFactory/math.js
  packages/inter-protocol/src/vaultFactory/params.js
  packages/inter-protocol/src/vaultFactory/vaultManager.js
  packages/inter-protocol/test/auction/auctionMath.test.js
  packages/inter-protocol/test/clientSupport.test.js
  packages/inter-protocol/test/interest-labeled.test.js
  packages/inter-protocol/test/interest-math.test.js
  packages/inter-protocol/test/interest.test.js
  packages/inter-protocol/test/provisionPool.test.js
  packages/inter-protocol/test/swingsetTests/psmUpgrade/bootstrap-psm-upgrade.js
  packages/inter-protocol/test/vaultFactory/interestSupport.js
  packages/inter-protocol/test/vaultFactory/prioritizedVaults.test.js
  packages/inter-protocol/test/vaultFactory/vault-contract-wrapper.js
  packages/inter-protocol/test/vaultFactory/vaultLiquidation.test.js
  packages/smart-wallet/test/supports.js
  packages/zoe/src/contractSupport/bondingCurves.js
  packages/zoe/src/contractSupport/index.js
  packages/zoe/src/contractSupport/priceAuthorityInitial.js
  packages/zoe/src/contracts/priceAggregator.js
  packages/zoe/test/unitTests/contracts/priceAggregator.test.js
  packages/zoe/test/unitTests/contracts/scaledPriceAuthority.test.js
  packages/zoe/tools/test-utils.js
Labels: automerge:rebase

#11177 chore(SwingSet): Harden outbound slog entry objects
  packages/SwingSet/src/controller/controller.js
  packages/telemetry/src/slog-sender-pipe-entrypoint.js
  packages/telemetry/test/flight-recorder.test.js
Labels: automerge:rebase

#11167 chore(ci): Make the Node versions in test matrix semantic
  .github/actions/restore-node/action.yml
  .github/workflows/after-merge.yml
  .github/workflows/benchmarks.yml
  .github/workflows/integration.yml
  .github/workflows/multichain-e2e-template.yml
  .github/workflows/test-all-packages.yml
  .github/workflows/test-documentation.yml
Labels: automerge:squash, force:integration

#11037 248 orchestration depositForBurn
  .github/workflows/multichain-e2e-template.yml
  multichain-testing/yarn.lock
  packages/boot/test/orchestration/contract-upgrade.test.ts
  packages/boot/test/orchestration/restart-contracts.test.ts
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.md
  packages/fast-usdc-contract/test/snapshots/fast-usdc.contract.test.ts.snap
  packages/orchestration/package.json
  packages/orchestration/src/cosmos-api.ts
  packages/orchestration/src/examples/send-anywhere.contract.js
  packages/orchestration/src/examples/send-anywhere.flows.js
  packages/orchestration/src/exos/README.md
  packages/orchestration/src/exos/chain-hub-admin.js
  packages/orchestration/src/exos/chain-hub.js
  packages/orchestration/src/exos/cosmos-orchestration-account.js
  packages/orchestration/src/orchestration-api.ts
  packages/orchestration/src/proposals/start-send-anywhere.js
  packages/orchestration/src/utils/address.js
  packages/orchestration/src/utils/chain-info.js
  packages/orchestration/test/examples/send-anywhere.test.ts
  packages/orchestration/test/examples/send-cctp.test.ts
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.md
  packages/orchestration/test/examples/snapshots/send-anywhere.test.ts.snap
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.md
  packages/orchestration/test/examples/snapshots/staking-combinations.test.ts.snap
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.md
  packages/orchestration/test/examples/snapshots/unbond.contract.test.ts.snap
  packages/orchestration/test/exos/cosmos-orchestration-account.test.ts
  packages/orchestration/test/exos/make-test-coa-kit.ts
  packages/orchestration/test/exos/portfolio-holder-kit.test.ts
  packages/orchestration/test/facade-durability.test.ts
  packages/orchestration/test/ibc-mocks.ts
  packages/orchestration/test/network-fakes.ts
  packages/orchestration/test/supports.ts
  packages/orchestration/test/types.test-d.ts
  packages/orchestration/test/utils/address.test.ts
Labels: enhancement, automerge:rebase, force:integration, orchestration

#11183 feat(SwingSet): Echo controller console output to the slog
  packages/SwingSet/src/controller/controller.js
  packages/cosmic-swingset/src/anylogger-agoric.js
  packages/telemetry/src/serialize-slog-obj.js
  packages/telemetry/src/slog-sender-pipe.js
Labels: automerge:rebase

#11166 convert cosmic-swingset tests to .ts
  packages/cosmic-swingset/package.json
  packages/cosmic-swingset/test/clean-core-eval.test.ts
  packages/cosmic-swingset/test/export-storage.test.js
  packages/cosmic-swingset/test/export-storage.test.ts
  packages/cosmic-swingset/test/inquisitor.test.ts
  packages/cosmic-swingset/test/make.test.ts
  packages/cosmic-swingset/test/prometheus.test.ts
  packages/cosmic-swingset/test/provision-smartwallet.test.ts
  packages/cosmic-swingset/test/run-policy.test.ts
  packages/cosmic-swingset/test/scenario2.js
  packages/cosmic-swingset/test/snapshots/prometheus.test.ts.md
  packages/cosmic-swingset/test/snapshots/prometheus.test.ts.snap
  packages/cosmic-swingset/tools/inquisitor.mjs
  packages/cosmic-swingset/tsconfig.json
Labels: automerge:rebase, bypass:integration
