Repository Agoric/agoric-sdk, pull requests merged in 2025-06, with the labels that each got.

#11430 chore: scaffold portfolio-contract
  .github/workflows/test-all-packages.yml
  packages/agoric-cli/src/sdk-package-names.js
  packages/portfolio-contract/README.md
  packages/portfolio-contract/package.json
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/open-pos-usdn.mmd
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-contract/tsconfig.json
  yarn.lock
Labels: automerge:squash, bypass:integration

#11410 chore: handle pfm of transfer with memo
  packages/orchestration/src/exos/local-orchestration-account.js
  packages/orchestration/test/exos/local-orchestration-account-kit.test.ts
Labels: automerge:rebase, force:integration

#11440 feat(cosmic-proto): noble USDN MsgSwap, MsgLock
  packages/cosmic-proto/package.json
  packages/cosmic-proto/proto/noble/dollar/vaults/v1/tx.proto
  packages/cosmic-proto/proto/noble/dollar/vaults/v1/vaults.proto
  packages/cosmic-proto/proto/noble/swap/v1/algorithm.proto
  packages/cosmic-proto/proto/noble/swap/v1/swap.proto
  packages/cosmic-proto/proto/noble/swap/v1/tx.proto
  packages/cosmic-proto/src/codegen/index.ts
  packages/cosmic-proto/src/codegen/noble/bundle.ts
  packages/cosmic-proto/src/codegen/noble/dollar/vaults/v1/tx.ts
  packages/cosmic-proto/src/codegen/noble/dollar/vaults/v1/vaults.ts
  packages/cosmic-proto/src/codegen/noble/swap/v1/algorithm.ts
  packages/cosmic-proto/src/codegen/noble/swap/v1/swap.ts
  packages/cosmic-proto/src/codegen/noble/swap/v1/tx.ts
  packages/cosmic-proto/src/codegen/stride/bundle.ts
  packages/cosmic-proto/src/codegen/tendermint/bundle.ts
Labels: automerge:rebase

#11438 ci(integration): skip getting-started
  .github/workflows/integration.yml
Labels: automerge:squash, force:integration

#11442 Handle Osmosis type base64 transfer/ack data
  multichain-testing/test/xcs-swap-anything/swap-anything.test.ts
  packages/orchestration/src/examples/swap-anything.flows.js
  packages/orchestration/src/exos/ibc-packet.js
Labels: automerge:rebase, force:integration

#11433 fix(cosmos-vm): prevent some hangs and crashes in `agd`
  golang/cosmos/cmd/libdaemon/main.go
  golang/cosmos/vm/client.go
Labels: automerge:no-update, agd

#11449 ci(proto): act on `proto:breakage` label in `proto.yml`
  .github/workflows/proto.yml
  .mergify.yml
Labels: automerge:rebase

#11470 docs(MAINTAINERS.md): Add a task to update cosmos/chain-registry
  MAINTAINERS.md
Labels: automerge:squash

#11458 refactor: use shorter failure idiom
  packages/ERTP/test/swingsetTests/basicFunctionality/bootstrap.js
  packages/ERTP/test/swingsetTests/splitPayments/bootstrap.js
  packages/zoe/test/swingsetTests/brokenContracts/vat-alice.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/bootstrap-coveredCall-service-upgrade.js
  packages/zoe/test/swingsetTests/upgradeCoveredCall/coveredCall-durable-V3.js
  packages/zoe/test/swingsetTests/zoe/vat-alice.js
  packages/zoe/test/swingsetTests/zoe/vat-bob.js
  packages/zoe/test/swingsetTests/zoe/vat-carol.js
  packages/zoe/test/swingsetTests/zoe/vat-dave.js
  packages/zoe/test/unitTests/bounty.js
  packages/zoe/test/unitTests/contracts/escrowToVote.js
  packages/zoe/test/unitTests/contracts/oracle.test.js
  packages/zoe/test/unitTests/contracts/useObjExample.js
Labels: automerge:squash

#11475 chore (multichain-testing): Support for Noble v9.0.4 with Ymax
  multichain-testing/README.md
  multichain-testing/config.ymax.yaml
  multichain-testing/scripts/noble-v9.0.4-update-genesis.sh
Labels: tooling, automerge:rebase, force:integration

#11477 integrate gmp with portfolio contract
  packages/boot/tools/axelar-supports.ts
  packages/orchestration/src/axelar-types.js
  packages/orchestration/src/examples/axelar-gmp-account-kit.js
  packages/portfolio-contract/package.json
  packages/portfolio-contract/src/constants.js
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio-actors.ts
  packages/portfolio-contract/test/portfolio-open.test.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  yarn.lock
Labels: automerge:rebase

#10852 test: IBC transfer scenarios
  multichain-testing/config.yaml
  multichain-testing/test/README.md
  multichain-testing/test/fast-usdc/fast-usdc.test.ts
  multichain-testing/test/ibc-transfers.ts
  multichain-testing/test/query-notes.md
  multichain-testing/tools/chaind-lib.js
  multichain-testing/tools/e2e-tools.js
  multichain-testing/tools/ibc-transfer.ts
Labels: automerge:rebase, force:integration

#11400 feat(swingset-runner): Add cpu/heap profiling support
  packages/swingset-runner/README.md
  packages/swingset-runner/src/main.js
Labels: automerge:squash

#11512 Update portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.exo.ts
Labels: automerge:rebase

#11508 feat(multichain-testing): noble-usdn-lab, ymax-tool
  multichain-testing/scripts/noble-usdn-lab.ts
  multichain-testing/scripts/ymax-tool.ts
Labels: automerge:rebase, bypass:integration, ymax

#11510 chore(multichain-testing): Upgrade to noblev10 in ymax config
  multichain-testing/config.ymax.yaml
  multichain-testing/scripts/noble-usdn-lab.ts
  multichain-testing/scripts/ymax-tool.ts
Labels: automerge:rebase, bypass:integration, SRE, ymax

#11499 feat: deploy funds to aave and compound
  packages/portfolio-contract/package.json
  packages/portfolio-contract/src/constants.js
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio-actors.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio-open.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio-open.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-deploy/src/portfolio-start.core.js
  yarn.lock
Labels: automerge:rebase, ymax

#11521 chore(portfolio-deploy): clarify what code is deployed
  packages/deploy-script-support/src/permissioned-deployment.js
  packages/pola-io/src/cmd.js
  packages/portfolio-deploy/package.json
  packages/portfolio-deploy/scripts/deploy-cli.ts
  packages/portfolio-deploy/src/config-marshal.js
  packages/portfolio-deploy/src/orch.start.js
  packages/portfolio-deploy/src/portfolio-start.core.js
  packages/portfolio-deploy/test/portfolio.test.ts
  yarn.lock
Labels: automerge:rebase, bypass:integration, ymax

#11525 chore(portfolio-contract): use denomAmount for .transfer()
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
Labels: automerge:rebase, bypass:integration, ymax

#11527 feat: for Noble Dollar, client can give USDN out with USDC in
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/portfolio-actors.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
Labels: automerge:rebase, bypass:integration, ymax

#11526 fix: make ethereum value capitalized
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-deploy/src/portfolio-start.core.js
Labels: automerge:rebase, ymax

#11519 chore(multichain-testing): Add liquidity in swap pool on noble chain start
  multichain-testing/scripts/create-noble-swap-pool.ts
  multichain-testing/scripts/noble-v10-update-genesis.sh
Labels: automerge:rebase, force:integration, SRE, ymax

#11532 fixes for gmp call flow in portfolio contract
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/test/supports.ts
Labels: automerge:rebase, ymax

#11533 feat: gate YMax PoC access with a token
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/supports.ts
  packages/portfolio-contract/test/wallet-offer-tools.ts
  packages/portfolio-deploy/README.md
  packages/portfolio-deploy/src/access-token-setup.build.js
  packages/portfolio-deploy/src/access-token-setup.core.js
  packages/portfolio-deploy/src/portfolio.contract.permit.js
  packages/portfolio-deploy/test/portfolio-start.core.test.ts
  packages/portfolio-deploy/test/portfolio.test.ts
Labels: automerge:rebase, bypass:integration, ymax

#11538 chore(portfolio.flows): offerResult -> portfolio; NobleFees; MsgSwap only
  packages/boot/tools/drivers.ts
  packages/client-utils/src/main.js
  packages/client-utils/src/marshalTables.js
  packages/client-utils/test/snapshots/exports.test.js.md
  packages/client-utils/test/snapshots/exports.test.js.snap
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-deploy/package.json
  packages/portfolio-deploy/src/orch.start.js
  packages/portfolio-deploy/src/portfolio-start.core.js
  packages/portfolio-deploy/src/portfolio-start.type.ts
  packages/portfolio-deploy/test/portfolio-start.core.test.ts
  packages/portfolio-deploy/test/portfolio.test.ts
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.snap
  test/portfolio.contract.test.ts
Labels: automerge:rebase, bypass:integration, ymax

#11539 test(multichain): deploy, use ymax0
  multichain-testing/Makefile
  multichain-testing/ava.rest.config.js
  multichain-testing/ava.ymd.config.js
  multichain-testing/package.json
  multichain-testing/scripts/noble-usdn-lab.ts
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/test/ymax0/ymax-deploy.test.ts
  packages/client-utils/src/marshalTables.js
  packages/client-utils/src/smart-wallet-kit.js
  packages/client-utils/src/types.ts
  packages/portfolio-deploy/src/access-token-setup.core.js
  packages/portfolio-deploy/src/chain-info.core.js
  packages/portfolio-deploy/src/orch.start.js
  packages/portfolio-deploy/src/portfolio.build.js
Labels: automerge:rebase, ymax

#11523 chore(portfolio-contract): simplify trackFlow; update status publishing
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/contract-setup.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio-actors.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/rebalance-cases.csv
  packages/portfolio-contract/test/rebalance-grok.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/test/wallet-offer-tools.ts
  packages/portfolio-contract/test/ymax-scenario.test.ts
  packages/portfolio-contract/tools/rebalance-grok.ts
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.snap
Labels: automerge:rebase, bypass:integration, ymax

#11545 chore: noble ica optional; exo: acct per chain
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/test/contract-setup.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio-start.core.test.ts.snap
Labels: automerge:rebase, bypass:integration, ymax
