Repository Agoric/agoric-sdk, pull requests merged in 2025-10, with the labels that each got.

#12030 feat(ymax-planner): Use flow-aware resolvePlan for rebalance and withdraw
  packages/SwingSet/src/kernel/state/kernelKeeper.js
  packages/SwingSet/test/stripPrefix.test.js
  packages/client-utils/src/vstorage.js
  packages/internal/src/natural-sort.js
  packages/internal/src/ses-utils.js
  packages/internal/test/snapshots/exports.test.js.md
  packages/internal/test/snapshots/exports.test.js.snap
  packages/internal/test/utils.test.js
  packages/portfolio-contract/package.json
  packages/portfolio-contract/src/type-guards.ts
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/plan-deposit.ts
  services/ymax-planner/src/vstorage-utils.ts
  services/ymax-planner/test/deposit-tools.test.ts
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.md
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.snap
Labels: automerge:rebase, bypass:integration

#12041 chore: update avalanche contract addresses
  packages/portfolio-deploy/src/axelar-configs.js
Labels: automerge:rebase

#12042 fix: add additional networks and pools to the routing graph
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/network/prod-network.test.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/tools/network/network.prod.ts
Labels: automerge:rebase, bypass:integration

#12038 Split-up portfolio-deploy and support contract name
  a3p-integration/package.json
  a3p-integration/proposals/f:ymax0-restart/.yarnrc.yml
  a3p-integration/proposals/f:ymax0-restart/README.md
  a3p-integration/proposals/f:ymax0-restart/eval.sh
  a3p-integration/proposals/f:ymax0-restart/package.json
  a3p-integration/proposals/f:ymax0-restart/test.sh
  a3p-integration/proposals/f:ymax0-restart/test/delegate.test.js
  a3p-integration/proposals/f:ymax0-restart/test/walletUpdates.js
  a3p-integration/proposals/f:ymax0-restart/yarn.lock
  a3p-integration/proposals/g:ymax1/.yarn/patches/@agoric-synthetic-chain-npm-0.6.1-f801222832.patch
  a3p-integration/proposals/g:ymax1/.yarnrc.yml
  a3p-integration/proposals/g:ymax1/README.md
  a3p-integration/proposals/g:ymax1/package.json
  a3p-integration/proposals/g:ymax1/test.sh
  a3p-integration/proposals/g:ymax1/test/consts.js
  a3p-integration/proposals/g:ymax1/test/ymax0.test.js
  a3p-integration/proposals/g:ymax1/test/ymax1.test.js
  a3p-integration/proposals/g:ymax1/use-invitation.js
  a3p-integration/proposals/g:ymax1/use.sh
  a3p-integration/proposals/g:ymax1/wallet-util.js
  a3p-integration/proposals/g:ymax1/walletUpdates.js
  a3p-integration/proposals/g:ymax1/yarn.lock
  a3p-integration/proposals/g:ymax1/ymax-util.js
  packages/boot/tools/supports.ts
  packages/client-utils/src/types.ts
  packages/orchestration/tools/contract-tests.ts
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-deploy/package.json
  packages/portfolio-deploy/src/access-token-setup.core.js
  packages/portfolio-deploy/src/attenuated-deposit.build.js
  packages/portfolio-deploy/src/attenuated-deposit.core.js
  packages/portfolio-deploy/src/contract-control.build.js
  packages/portfolio-deploy/src/contract-control.core.js
  packages/portfolio-deploy/src/contract-control.js
  packages/portfolio-deploy/src/get-upgrade-kit.build.js
  packages/portfolio-deploy/src/get-upgrade-kit.core.js
  packages/portfolio-deploy/src/portfolio-control.build.js
  packages/portfolio-deploy/src/portfolio-control.core.js
  packages/portfolio-deploy/src/postal-service.build.js
  packages/portfolio-deploy/src/postal-service.core.js
  packages/portfolio-deploy/test/contract-control.test.ts
  packages/portfolio-deploy/test/portfolio-start.core.test.ts
  packages/portfolio-deploy/test/portfolio.test.ts
  yarn.lock
Labels: automerge:rebase, force:integration

#12050 fix(ymax-planner): Allow target weight of zero
  services/ymax-planner/src/plan-deposit.ts
  services/ymax-planner/test/deposit-tools.test.ts
Labels: bypass:integration, bypass:automerge

#12051 chore(ymax-planner): Annotate plan errors with currentBalances
  services/ymax-planner/src/engine.ts
Labels: bypass:integration, bypass:automerge, bypass:linear-history

#12033 feat(client-utils): Add SigningSmartWalletKit reflection methods
  packages/client-utils/package.json
  packages/client-utils/src/signing-smart-wallet-kit.ts
  packages/client-utils/src/smart-wallet-kit.js
  packages/client-utils/src/sync-tools.js
  packages/client-utils/test/snapshots/exports.test.js.md
  packages/client-utils/test/snapshots/exports.test.js.snap
  yarn.lock
Labels: bypass:automerge

#12016 feat: deposit, rebalance w planner
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-contract/src/portfolio.exo.ts
  packages/portfolio-contract/src/portfolio.flows.ts
  packages/portfolio-contract/src/type-guards.ts
  packages/portfolio-contract/test/mocks.ts
  packages/portfolio-contract/test/portfolio.contract.test.ts
  packages/portfolio-contract/test/portfolio.exo.test.ts
  packages/portfolio-contract/test/portfolio.flows.test.ts
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.contract.test.ts.snap
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.md
  packages/portfolio-contract/test/snapshots/portfolio.flows.test.ts.snap
  packages/portfolio-contract/tools/portfolio-actors.ts
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.md
  packages/portfolio-deploy/test/snapshots/portfolio.test.ts.snap
  services/ymax-planner/src/plan-deposit.ts
  services/ymax-planner/test/deposit-tools.test.ts
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.md
  services/ymax-planner/test/snapshots/deposit-tools.test.ts.snap
Labels: automerge:rebase, bypass:integration

#12039 feat(ymax-planner): Replace tx-based deposit response with flow-based deposit/withdraw submission
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/plan-deposit.ts
Labels: automerge:rebase

#12057 feat(ymax-tool): REPL
  multichain-testing/Makefile
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/ymax-ops/Makefile
Labels: automerge:rebase

#12063 feat(ymax planner): Support "ymax1" contract
  multichain-testing/scripts/ymax-tool.ts
  services/ymax-planner/README.md
  services/ymax-planner/package.json
  services/ymax-planner/src/config.ts
  services/ymax-planner/src/engine.ts
  services/ymax-planner/src/main.ts
  services/ymax-planner/src/pending-tx-manager.ts
  services/ymax-planner/test/config.test.ts
  services/ymax-planner/test/mocks.ts
Labels: automerge:rebase, force:integration

#12069 chore: update factory addr for Arbitrum and Avalanche
  packages/portfolio-deploy/src/axelar-configs.js
Labels: automerge:rebase, bypass:integration, ymax

#12072 chore: ymax1 deployment tweaks
  multichain-testing/scripts/ymax-tool.ts
  multichain-testing/ymax-ops/Makefile
  packages/portfolio-contract/src/portfolio.contract.ts
  packages/portfolio-deploy/src/chain-info.build.js
  packages/portfolio-deploy/src/portfolio.build.js
  packages/portfolio-deploy/test/chain-info.fixture.js
  packages/portfolio-deploy/test/evm-overrides.test.ts
  packages/portfolio-deploy/test/snapshots/evm-overrides.test.ts.md
  packages/portfolio-deploy/test/snapshots/evm-overrides.test.ts.snap
Labels: automerge:rebase, bypass:integration
